### PR TITLE
CAMEL-7862-add CVSRecord annotation attribute to allow empty streams to be processed

### PR DESCRIPTION
**Pull request by onders86**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you fix checkstyle issues first

   mvn compile -P sourcecheck

**Comment by onders86** [comment]
sorry about that. my checkstyle plugin was deactivated somehow. added them. thanks.

**Comment by davsclaus** [comment]
@oscerd looks good for me

**Comment by oscerd** [comment]
Sure. Merging.

**Comment by oscerd** [comment]
@onders86 Thanks the PR has been merged. Can you close this?

**Comment by onders86** [comment]
sure. thanks.

**Pull request closed without merging**
