### PR TITLE
CAMEL-11006 Auto generate REST DSL for Camel from Swagger2.0/OAI specification

### PR DESCRIPTION
**Pull request by zregvart**
Submitting for review, thanks :1st_place_medal:

This is initial work on REST DSL code|object generation from Swagger specification.

Entry point to the implementation is RestDslGenerator::to...(...) methods. Several options are provided for generating source files:
 - for code generation in Maven plugin ones accepting Path or Appendable should be suitable
 - for generation in Annotation Processing ones accepting Filer are more appropriate
 - and for generation of the object graph in runtime the one accepting CamelContext is provided

Both the source code and object graph implementation depend on a CodeEmitter implementation: one relying on reflection (RestDefinitionEmitter) is used to generate the object graph, and the one generating the source code for the RouteBuilder::configure method body using the javapoet library (MethodBodySourceCodeEmitter).

CodeEmitter is driven by two visitor pattern implementations one for processing path elements of the specification (RestDslPathGenerator) and one for processing operation elements of he specification
(RestDslOperationGenerator). Both can be further adapted to support more of the Swagger specification. I believe they map the currently used / relevant parts of the Swagger specification covered by REST DSL.

Example of usage:

    RestDslGenerator.toPath(swagger)
        .withClassName("MyRestRoute")
        .withPackageName("com.example")
        .withIdent("\t")
        .generate(Paths.get("src", "generated"));

### CODE REVIEW

**Comment by davsclaus** [comment]
Looks great. 

And it seems that javapoet is a nice lille java generate library. We are using jboss roaster for other parts in camel such as the maven plugin that generates spring boot source code.

The big question is however 2 spaces vs 4 spaces in the indent, and after that the almighty tabs vs spaces ;).

But maybe add an option to configure the number of spaces for indent. Yeah we use spaces ;)

**Comment by zregvart** [comment]
@davsclaus thanks :+1:
Do the `RestDslGenerator::generate(...)` method signatures make sense?
Does the auto generated route with single processor make sense, like here https://github.com/apache/camel/pull/1574/files#diff-6482d2ba8e430a6ed09e7154c7520930R34?

**Comment by davsclaus** [comment]
No the process("xx") does not make sense.

You may want to create a router per verb, and link them together with direct:xx.

get
   ...
   to("direct:foo")
...

from("direct:foo")
   .to("log:foo")

If you have inlined routes in the rest-dsl then it gets IMHO to big and complex. It can be okay in some use-cases for demos / small rest apis / or in some use-cases.

**Comment by davsclaus** [comment]
For the generate signature. 

Then personally I do like when you can configure it using getter/setters (or maybe builder) instead of 10 different generate methods with a myrid of differnt options/types.

A static method can be fine if 95% of the time people use that same method.

You can make a GenerateConfig class or something to make it stand a bit out, or go down the fluent builder rabbit hole, and maybe do that on the generator.

**Comment by zregvart** [comment]
I've switched to code around a bit, now it's using a builder not static methods, and includes the all important option to further the spaces vs tabs debate :)
I'll leave it here for a bit if anyone else would like to comment and merge this to ASF later today.

**Pull request closed without merging**
