### PR TITLE
CAMEL-15710: Initial support for Open Tracing integration with third-party tracing

### PR DESCRIPTION
**Pull request by orange-buffalo**
Providing a test to reproduce CAMEL-15710 and a suggestion for its fix. There is a TODO in code to be addressed by the reviewers if they agree on the general approach - implementing a properly encapsulated solution would likely require public API changes to pass `tracer` into the `ActiveSpanManager` methods.

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Looks good, but please do the same for master and take into account the component architecture is a bit different on that branch

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Yeah you cannot change APIs on 3.4.x branch. 

It would be great if you could do this work on master, mind that tracing code has moved into a common module camel-tracing so you may need to look there too if it needs changes.

**Comment by orange-buffalo** [comment]
Created #4497 to port the changes to `master` branch. Unfortunately, I can't test this end-to-end as 3.7.x version has too many changes that are not compatible with our product code. Migrating to this version will be a separate activity for us.

Just one question about Open Tracing support. Currently Camel uses `0.31.0` (which is two years old already) while up-to-date version is `0.33.0`. Is there any specific reason to stick to the older version?

**Comment by oscerd** [comment]
The version at 0.31.0 is related to a problem with microprofile. We are waiting for a new release from them

**Comment by orange-buffalo** [comment]
I see.. That will be a blocker for our Camel upgrade - our other dependencies work with 0.33.0, but this version has removed methods Camel is using now.

**Comment by jam01** [comment]
@orange-buffalo @oscerd 

This was actually being done here https://github.com/apache/camel/blob/master/components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracingStrategy.java#L75

The change introduced here is not guaranteed to work if the span-aware processor executes in a different thread than the one where the route policy starts the exchange. The default Scope manager uses ThreadLocals.

Im not entirely sure if this addition really breaks anything, but the TracingStartegy should provide what you needed.

**Comment by orange-buffalo** [comment]
@jam01, thank you for your input. This PR is for `3.4.x` branch, where `TracingStartegy` does not exist. Introducing it seems to require a lot of changes and might be backwards incompatible with current branch solution. If you sure it is possible to safely back-port it, that would be much appreciated!

**Comment by jam01** [comment]
Hey @orange-buffalo , I commented here because it seemed this is where the discussion was. I think it's possible to backport the strategy to 3.4.x, but I think we should probably revert the changes made in master.

Unless I'm misunderstanding your use case, which is entirely possible :) I think the existing tracing strategy should cover what you needed, no?

**Comment by orange-buffalo** [comment]
Frankly speaking, I did not dig too deep into how `TracingStrategy` integrates with Camel internals, and my expertise in internal Camel details is rather at a low level. If I am not mistaken, I've started porting to `master` from creating `ThirdPartyInstrumentationIntegrationTest` and it failed. So at that moment, the implementation was not sufficient. If reverting the changes in production code of `master` will keep `ThirdPartyInstrumentationIntegrationTest` passing, then totally strategy is covering the case :)

**Comment by jam01** [comment]
There's another addition I wanted to make to the OpenTracing component soon. So I'll give the test another look and see if it was really covered or if I'm just talking nonsense. I'll let you know how that goes.

**Pull request merged**
