### PR TITLE
Fix IronMQ URLs in docs and configuration

### PR DESCRIPTION
**Pull request by alex-litvak**
http://dev.iron.io/mq/reference/clouds is deprecated

### CODE REVIEW

**Comment by pax95** [comment]
The documentation for option values i ironmq.adoc i generated from the javadoc during the build process. To fix the URL's you have to update the javadoc https://github.com/apache/camel/blob/master/components/camel-ironmq/src/main/java/org/apache/camel/component/ironmq/IronMQConfiguration.java#L124. Then the ascii doc will be updated.

**Comment by davsclaus** [comment]
@alex-litvak yes as @pax95 says, the documentation is in the source code as the javadoc on those setter methods. So just update it there, and the build tool automatic update the adoc file afterwards.

**Comment by alex-litvak** [comment]
@davsclaus @pax95 Thanks, updated

**Comment by davsclaus** [comment]
Thanks its been merged. Can you close this PR

**Pull request closed without merging**
