### PR TITLE
Added camel-tarfile component

### PR DESCRIPTION
**Pull request by sverkera**
I've created a tarfile component, based on the zipfile component, for packaging and unpackaging of tar files.

### CODE REVIEW

**Comment by raulk** [comment]
HI Sverker!

Thanks a lot for your contribution. I've reviewed it and it looks pretty good.

Would you mind opening a ticket of type New Feature in our JIRA and adding the link to this Pull Request, please?

It's just the "paperwork" and the typical path to accept a contribution into Camel.

Once you do that, I'll merge the PR.

Thanks!
Raúl.

**Comment by raulk** [comment]
Ping?

**Comment by sverkera** [comment]
Hi Raul
Sorry, I had missed your response. The jira request is now availible here: https://issues.apache.org/jira/browse/CAMEL-9111

**Comment by raulk** [comment]
Hey @sverkera, thanks a lot for your contribution.

Would it be possible to write a wiki page for this component, so that people know how to use it?

Thanks.

**Comment by sverkera** [comment]
Yes, it is on my todo list

"Raúl Kripalani" <notifications@github.com> skrev: (12 september 2015 17:42:28 CEST)
>Hey @sverkera, thanks a lot for your contribution.
>
>Would it be possible to write a wiki page for this component, so that
>people know how to use it?
>
>Thanks.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/apache/camel/pull/599#issuecomment-139788430

-- 
Skickat från min Android-telefon med K-9 E-post. Ursäkta min fåordighet.

**Comment by raulk** [comment]
Awesome, thanks! In case you don't have wiki edit permissions yet:
https://camel.apache.org/how-do-i-edit-the-website.html.

**Pull request closed without merging**
