### PR TITLE
CAMEL-11211 Remove the deprecated SpanManager, which uses threadlocal…

### PR DESCRIPTION
**Pull request by objectiser**
…, and instead just manage the spans within the exchanges

### CODE REVIEW

**Comment by objectiser** [comment]
@davsclaus Hi Claus - if you could review please.

Hoping this will be included in the rebuild of the release candidate, as it greatly simplifies the management of spans, removing dependence on use of threadlocals and instead just managing the span stack within the exchanges.

Let me know if you see any risks with this approach.

**Comment by davsclaus** [comment]
lgtm

**Comment by davsclaus** [comment]
@objectiser btw did you try the camel-example-opentracing with this change? 

I can merge this PR when we know the example still works.

**Comment by objectiser** [comment]
@davsclaus Yes it works with the camel-example-opentracing example. Thanks!

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by objectiser** [comment]
Thanks!

**Pull request closed without merging**
