### PR TITLE
[CAMEL-16181] Fix KafkaIdempotentRepository flagging cache as ready incorrectly

### PR DESCRIPTION
**Pull request by javierholguera**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

Jira ticket: https://issues.apache.org/jira/browse/CAMEL-16181

This PR fixes an issue where the `KafkaIdempotentRepository` flags its cache as ready before it has finished consuming all records in the backing Kafka repository

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Lgtm, we need to backport to 3.7 i believe

**Comment by javierholguera** [comment]
@oscerd happy to backport it. What branch should I checkout from to apply the changes?

**Comment by oscerd** [comment]
It is camel-3.7.x. thanks

**Review by davsclaus — APPROVED** [review]

**Comment by javierholguera** [comment]
@oscerd I've opened this PR for the backporting: https://github.com/apache/camel/pull/5075

It seems to automatically bump up the version number. Should I leave it or should I undo those changes?

**Comment by oscerd** [comment]
Yeah that's fine. Thanks for this.

**Review by omarsmak — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by valdar** [comment]
@javierholguera please see my comment on https://issues.apache.org/jira/browse/CAMEL-16181 if you can.

**Pull request merged**
