### PR TITLE
CAMEL-19164: upgrade to http components 5.x

### PR DESCRIPTION
**Pull request by jono-morris**
# Description

Upgrade camel-as2 to use httpcomponents v5.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by orpiske — COMMENTED** [review]
Probably good to run a manual full test of this one ... I'll trigger a test on my env

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Thanks @jono-morris - there are some other tickets about camel-as2 that would be good to take a look at

**Comment by davsclaus** [comment]
@orpiske have you done your tests

**Comment by orpiske** [comment]
> @orpiske have you done your tests

Oh, I almost forgot about this one ... thanks for the heads up.

Looking at the results, I noticed that the build has failed with an execution timeout. I don't think it's caused by this PR specifically, but because it may be lagging behind `main` (which had some fixes for this). So, in short, I cannot say for sure if it's working or not.

**Comment by davsclaus** [comment]
okay lets merge this as we need to move to http 5.x anyway and camel-as2 needs some cleanup and there are other JIRAs related to issues with camel-as2.

**Pull request merged**
