### PR TITLE
CAMEL-11977: MongoDB Tailable cursor consumer fails to stop on shutdown

### PR DESCRIPTION
**Pull request by igorko**
Is it still possible to include this fix into v2.20.1. It would be very good if so.

### CODE REVIEW

**Comment by oscerd** [comment]
No, 2.20.1 is alreay under vote after cut, it will be in 2.20.2. Thanks :-)

**Comment by oscerd** [comment]
Thanks for the PR. It has been merged on master and 2.20.x

**Comment by igorko** [comment]
SHould I create another pull request for branch or no?

**Comment by oscerd** [comment]
No need for a PR on the other branch. We usually ask for PR on master and we cherry-pick commit on old branches.

**Comment by igorko** [comment]
@oscerd Could you merge changes to 2.20.x ? I see that they are not present in branch.

**Pull request merged**
