### PR TITLE
CAMEL-16400: split unit and integration tests for camel-aws2-sqs

### PR DESCRIPTION
**Pull request by orpiske**
Run all tests: 
mvn verify

Run unit tests:
mvn test

To skip all tests:
mvn -DskipTests=true

To skip integration tests (default from failsafe):
mvn -DskipITs=true verify

Unit tests only run in 23s 
Integration + unit tests run in 2 min 12s

### CODE REVIEW

**Comment by orpiske** [comment]
@davsclaus @gnodet @oscerd FYI, this breaks the unit and integration tests in different phases in Maven. Wdyt?

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
How does it work with

    mvn clean install -P fastinstall

Its a habit I use for rebuilding the code (not tests at all)

**Review by oscerd — APPROVED** [review]
Looks really good!

**Comment by orpiske** [comment]
> How does it work with
> 
> ```
> mvn clean install -P fastinstall
> ```
> 
> Its a habit I use for rebuilding the code (not tests at all)

With fastinstall profile, it skips all the tests. I think this is the current behavior, right?

**Comment by davsclaus** [comment]
Yes thanks.

This is really great. No verbose pom.xml, and we can easily test for users not with docker.

I wonder if we can have the failsafe plugin in the components/pom.xml so you dont need it per component?

**Comment by orpiske** [comment]
> Yes thanks.
> 
> This is really great. No verbose pom.xml, and we can easily test for users not with docker.
> 
> I wonder if we can have the failsafe plugin in the components/pom.xml so you dont need it per component?

I think we can probably do that once we finish migrating all of them. IMHO, it would be safer to keep it as a plugin reference for now, and then cleanup after the migration is complete.

**Comment by davsclaus** [comment]
Ok sounds good

**Comment by oscerd** [comment]
The cs error should be fixed. Just rebase and merge @orpiske

**Comment by orpiske** [comment]
> The cs error should be fixed. Just rebase and merge @orpiske

Fantastic! Thanks @oscerd!

**Pull request merged**
