### PR TITLE
This reverts commit 8b63e4b89e9544018f9e61e996b23ec0f6673531.

### PR DESCRIPTION
**Pull request by johnpoth**
https://issues.apache.org/jira/browse/CAMEL-10672

### CODE REVIEW

**Comment by davsclaus** [comment]
There is a reason for this revert. It breaks the build order. Please find another solution.

**Comment by johnpoth** [comment]
Ah wasn't sure thanks for clarifying :) Wonder how it was working before.

We could declare the dependency in camel-itest-osgi (and other modules that use it too).

**Comment by davsclaus** [comment]
Yeah the latter would work.

**Comment by johnpoth** [comment]
PR updated. Looks like only camel-itest-osgi needed it in Camel.

Thanks for taking time and looking into this :)

**Comment by johnpoth** [comment]
Please hold on merging this PR while I do more testing.

**Comment by johnpoth** [comment]
It turns out the above approach won't work because camel-karaf will look for the karaf feature version to use in it's own [jar](https://github.com/apache/camel/blob/1abcb8a9f8a466b95b883ee9d2ef9c2b862637c1/components/camel-test-karaf/src/main/java/org/apache/camel/test/karaf/AbstractFeatureTest.java#L222) file only. 

Instead I propose a solution [similar](https://github.com/apache/camel/blob/1abcb8a9f8a466b95b883ee9d2ef9c2b862637c1/components/camel-test-karaf/src/main/java/org/apache/camel/test/karaf/AbstractFeatureTest.java#L246) to what is done to determine the karaf-version to use by way of specifying the version through the camelKarafFeatureVersion System property (and fail fast if none exist instead of fetching LATEST or hardcoding the version etc...).

Let me know what you think :)

**Comment by davsclaus** [comment]
Yeah that is a good idea @johnpoth

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by johnpoth** [comment]
Thanks for reviewing this :)

**Pull request closed without merging**
