### PR TITLE
initial commit support for service accounts

### PR DESCRIPTION
**Pull request by carljmosca**
initial commit for google calendar suport for service accounts

### CODE REVIEW

**Comment by WillemJiang** [comment]
Hi Carl,
There are some formate changes in the patch. Could you resubmit the PR without these code formate changes? It could be more easy for us to review the code.

**Comment by davsclaus** [comment]
@WillemJiang what is the status? Has this PR been merged?

**Comment by maciejwalkowiak** [comment]
Same feature would be nice for other Google integrations. After this one is merged I can prepare similar solution for Google Drive component.

**Comment by carljmosca** [comment]
Indeed it would be, thank you.

**Comment by davsclaus** [comment]
We have added some support for this in the google components.

It would be good to take a new look and see if something is still missing and do a new PR - then we can get the missing bits into the code base.

**Pull request closed without merging**
