### PR TITLE
CAMEL-20568: Set error handler on route level in YAML DSL

### PR DESCRIPTION
**Pull request by christophd**
# Description

Allow to set error handler on route level in Camel YAML DSL

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

See CAMEL-20568

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
--- a/dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/application.properties
+++ b/dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/application.properties

There is something wrong about this change. The CI job cannot run the test due to ^^

**Comment by christophd** [comment]
🤔 hm, I have added this `application.properties` to fix the build running locally. it somehow gets generated on CI jobs I guess. Let me revert the change

**Comment by davsclaus** [comment]
modified:   catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/releases/camel-releases.json

**Comment by christophd** [comment]
any hint how to resolve this please?

**Comment by davsclaus** [comment]
cd catalog/camel-catalog
mvn install -Pupdate-camel-releases

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
