### PR TITLE
Updates to latest zipkin, eliminating SpanCollector dependency

### PR DESCRIPTION
**Pull request by adriancole**
This reduces the effort of renovating the zipkin component by reducing
the apis used to send data to Zipkin.

### CODE REVIEW

**Comment by oscerd** [comment]
This LGTM, but since the original component was written by @davsclaus I'd like to wait for his feedback too

**Comment by oscerd** [comment]
Thanks @adriancole

**Comment by oscerd** [comment]
Sure

**Comment by oscerd** [comment]
I have only on test in error here:

```
[INFO] Running org.apache.camel.zipkin.SpringZipkinSimpleRouteTest
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 2.027 s <<< FAILURE! - in org.apache.camel.zipkin.SpringZipkinSimpleRouteTest
[ERROR] testZipkinRoute(org.apache.camel.zipkin.SpringZipkinSimpleRouteTest)  Time elapsed: 1.35 s  <<< ERROR!
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.github.kristofa.brave.LoggingReporter] for bean with name 'logSpanReporter' defined in class path resource [org/apache/camel/zipkin/SpringZipkinSimpleRouteTest.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: zipkin/reporter/Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
Caused by: java.lang.NoClassDefFoundError: zipkin/reporter/Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
Caused by: java.lang.ClassNotFoundException: zipkin.reporter.Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)

[ERROR] testZipkinRoute(org.apache.camel.zipkin.SpringZipkinSimpleRouteTest)  Time elapsed: 0.327 s  <<< ERROR!
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.github.kristofa.brave.LoggingReporter] for bean with name 'logSpanReporter' defined in class path resource [org/apache/camel/zipkin/SpringZipkinSimpleRouteTest.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: zipkin/reporter/Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
Caused by: java.lang.NoClassDefFoundError: zipkin/reporter/Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
Caused by: java.lang.ClassNotFoundException: zipkin.reporter.Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)

[ERROR] testZipkinRoute(org.apache.camel.zipkin.SpringZipkinSimpleRouteTest)  Time elapsed: 0.343 s  <<< ERROR!
org.springframework.beans.factory.CannotLoadBeanClassException: Error loading class [com.github.kristofa.brave.LoggingReporter] for bean with name 'logSpanReporter' defined in class path resource [org/apache/camel/zipkin/SpringZipkinSimpleRouteTest.xml]: problem with class file or dependent class; nested exception is java.lang.NoClassDefFoundError: zipkin/reporter/Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
Caused by: java.lang.NoClassDefFoundError: zipkin/reporter/Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
Caused by: java.lang.ClassNotFoundException: zipkin.reporter.Reporter
	at org.apache.camel.zipkin.SpringZipkinSimpleRouteTest.createApplicationContext(SpringZipkinSimpleRouteTest.java:31)
```

**Comment by oscerd** [comment]
Probably because now it's zipkin.reporter2.Reporter

**Comment by adriancole** [comment]
nice turnaround!

**Comment by davsclaus** [comment]
btw there is also a camel-example-zipkin - not sure if it needs any update as well

**Comment by adriancole** [comment]
thanks for checking. right now, no updates there because it is using http
already

**Comment by davsclaus** [comment]
Can we get that unit test fixed so we can get this merged

**Comment by adriancole** [comment]
the easiest fix would be to use Reporter.CONSOLE in that unit test https://github.com/openzipkin/zipkin-reporter-java/blob/master/core/src/main/java/zipkin2/reporter/Reporter.java

**Comment by oscerd** [comment]
I'm able to fix the test but:

- The karaf feature will still need io.zipkin.java/zipkin
- The camel zipkin starter will still try to use the zipkin reporter 2.3.1, while now we are using zipkin reporter2 with libthrift and version 2.7.1

I can merge my stuff, but what do you think @davsclaus and @adriancole ?

**Comment by davsclaus** [comment]
Do you mean that the spring-boot based camel-zipkin-starter is using an older version of Zipkin?

And about Karaf is it because a new OSGi bundle release is needed for zipkin or something?

For what its worth then I do think its worth to get this updated and into the 2.22 release as its a Spring Boot 2 focused release. If there is a bit that may not work on karaf, then we can add that in the known issues section and get it corrected for 2.23.

**Comment by oscerd** [comment]
A full rebuild fixed everything :-)

Now it works fine.

**Comment by oscerd** [comment]
Thanks @adriancole 

Merged on master

**Comment by oscerd** [comment]
@davsclaus for the Karaf feature the need for old zipkin stuff is related to the fact that brave-core depends on both version of zipkin 1 and 2 as far as I see.

**Comment by adriancole** [comment]
brave-core had an optional dependency on the old zipkin library. please
dont reintroduce that as we will stop publishing updates for it soon,
causing version skew.

**Comment by adriancole** [comment]
>
> @davsclaus <https://github.com/davsclaus> for the Karaf feature the need
>> for old zipkin stuff is related to the fact that brave-core depends on both
>> version of zipkin 1 and 2 as far as I see.
>>
> Actually you are correct. The 4.13.4 version had an accidental hard
dependency on io.zipkin.java used for constants and the like. Will make a
manual release of 4.13.5 to fix that.

**Comment by adriancole** [comment]
https://github.com/apache/camel/pull/2382 takes care of the dependency on io.zipkin.java:zipkin

Note: the example project has a configuration problem which is unrelated to zipkin library versions. I'll try to figure out what's behind it.

**Comment by adriancole** [comment]
PS I don't have time to redo things as brave 4 apis today as time was consumed on the spring configuration problem and decoupling things from io.zipkin.java:zipkin. It will stop bleeding a lot to upgrade this component. There are few projects that require so much backport work compared to original effort. Let's please work together to stop this maintenance pit.

**Comment by oscerd** [comment]
thanks @adriancole

**Pull request closed without merging**
