### PR TITLE
CAMEL-10222: Conflicts-free springboot BOM

### PR DESCRIPTION
**Pull request by nicolaferraro**
I created a camel BOM without conflicts with the spring-boot one, as discussed in the mailing list.
I removed the following modules from the list of starters (with reference to the previous PR):
- IBatis and Quartz (v1): deprecated and having many issues when running unit tests in sb mode
- Jclouds: Jclouds-core uses a specific version of Gson. Cannot work with the one in the spring-bom.
- SparkRest: Internally using a class that is missing in the version of Jetty used by spring-boot.

There are also other (10) modules having some problems, but issues might be caused by the testing environment. For example, the Cassandra module might work with v2 of the driver, but the tests cannot ensure this because unit tests include cassandra-all into the classpath and it is much more probable that cassandra-all cannot work in a spring-boot environment (and it must not).
I kept that starters, as they should work: Ahc, Cassandra, Consul, Jgroups, Jibx, Jpa, Xmljson, Mongodb, MongodbGridfs, Mybatis.

Waiting for feedbacks.

### CODE REVIEW

**Comment by davsclaus** [comment]
Yeah this is great work @nicolaferraro.

Have you tried updating the spring boot examples we have in examples to use the -starter modules? IMHO we should use this ourselves there also.

We could also consider having a readme.adoc file in the components-starter directory that explains a bit about that this is Spring Boot components. And that the following are not supported, and then list the few ones that do not work.

**Comment by nicolaferraro** [comment]
Yeah, sure! I can do it. Also the bom needs a bit of documentation.

**Comment by nicolaferraro** [comment]
I checked the examples and changed the ones that were not using starters. They work!

I also added some docs to the `components-starter` and `spring-boot-dm` directories.

**Comment by davsclaus** [comment]
+1

Lovely work @nicolaferraro

**Comment by oscerd** [comment]
Great work! Thanks a lot @nicolaferraro !

**Comment by davsclaus** [comment]
Ah Dhiraj just merged to master some massive code changes in the generated source code. I think you would need to rebase before you can merge this.

**Comment by nicolaferraro** [comment]
Yeah, np. I'm about to do it.

**Comment by oscerd** [comment]
```
oscerd@ghost:~/workspace/apache-camel/camel$ mvn clean install -DskipTests
[WARNING] 
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-blueprint-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-cdi-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-ejb-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-ibatis-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-jclouds-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-quartz-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-spark-rest-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-test-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[ERROR] Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-testng-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist @ 
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.camel:camel-spring-boot-starter:jar -> version (?) vs ${project.version} @ org.apache.camel:apache-camel:[unknown-version], /home/oscerd/workspace/apache-camel/camel/apache-camel/pom.xml, line 1916, column 17
[WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.camel:camel-zipkin-starter:jar -> version (?) vs ${project.version} @ org.apache.camel:apache-camel:[unknown-version], /home/oscerd/workspace/apache-camel/camel/apache-camel/pom.xml, line 2096, column 17
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.apache.camel:components-starter:2.18.0-SNAPSHOT (/home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml) has 9 errors
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-blueprint-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-cdi-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-ejb-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-ibatis-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-jclouds-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-quartz-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-spark-rest-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-test-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR]     Child module /home/oscerd/workspace/apache-camel/camel/components-starter/camel-testng-starter/pom.xml of /home/oscerd/workspace/apache-camel/camel/components-starter/pom.xml does not exist
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
```

Trying to run a full build. Am I losing something?

**Comment by oscerd** [comment]
My mistake. Forgive me :-)

**Pull request merged**
