### PR TITLE
CAMEL-13454

### PR DESCRIPTION
**Pull request by akoufoudakis**
As I mentioned in the comment in JIRA. The fix didn't work for my environment. So, trying to offer something more generic. Apologies for any confusion caused. https://issues.apache.org/jira/browse/CAMEL-13454

### CODE REVIEW

**Comment by akoufoudakis** [comment]
"can you please try with 3.6.0 or 3.6.1"
Hi! Thanks for the comment. Completely agree with your argumentation. Just tried with mvn 3.6.1, same problem.
So, just to be complete, I have:
JDK 1.8.0_191, Maven 3.6.1, surefire-plugin from Camel (2.22.1), macOS 10.14.5 (Mojave). Of course, we can say that it is a glitch somewhere in my environment, but if anyone could double check would be good.

**Comment by ramu11** [comment]
`mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-05T00:30:29+05:30)
Maven home: /home/kkakarla/development/apache-maven-3.6.1
Java version: 1.8.0_121, vendor: Oracle Corporation, runtime: /home/kkakarla/development/soft/jvm-stuff/jdk1.8.0_121/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-80.1.2.el8_0.x86_64", arch: "amd64", family: "unix"` 


`[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ camel-testcontainers ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/kkakarla/development/git/direct-camel/camel/components/camel-testcontainers/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ camel-testcontainers ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- camel-package-maven-plugin:3.0.0-SNAPSHOT:validate-components (validate) @ camel-testcontainers ---
[INFO] Validation complete
[INFO] 
[INFO] --- camel-package-maven-plugin:3.0.0-SNAPSHOT:prepare-spring-boot-starter (validate) @ camel-testcontainers ---
[INFO] Spring-Boot-Starter: starter not allowed for module camel-testcontainers: skipping.
[INFO] 
[INFO] --- camel-package-maven-plugin:3.0.0-SNAPSHOT:prepare-spring-boot-auto-configuration (validate) @ camel-testcontainers ---
[INFO] Component auto-configuration will not be created: the starter does not exist
[INFO] 
[INFO] --- camel-package-maven-plugin:3.0.0-SNAPSHOT:generate-legal (validate) @ camel-testcontainers ---
[INFO] 
[INFO] --- camel-package-maven-plugin:3.0.0-SNAPSHOT:generate-endpoint-dsl (validate) @ camel-testcontainers ---
[INFO] 
[INFO] --- maven-bundle-plugin:4.2.0:manifest (bundle-manifest) @ camel-testcontainers ---
[INFO] No previous run data found, generating manifest.
[INFO] 
[INFO] --- maven-jar-plugin:3.1.2:jar (default-jar) @ camel-testcontainers ---
[INFO] Building jar: /home/kkakarla/development/git/direct-camel/camel/components/camel-testcontainers/target/camel-testcontainers-3.0.0-SNAPSHOT.jar
[INFO] 
[INFO] --- camel-package-maven-plugin:3.0.0-SNAPSHOT:update-readme (readme) @ camel-testcontainers ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ camel-testcontainers ---
[INFO] Installing /home/kkakarla/development/git/direct-camel/camel/components/camel-testcontainers/target/camel-testcontainers-3.0.0-SNAPSHOT.jar to /home/kkakarla/.m2/repository/org/apache/camel/camel-testcontainers/3.0.0-SNAPSHOT/camel-testcontainers-3.0.0-SNAPSHOT.jar
[INFO] Installing /home/kkakarla/development/git/direct-camel/camel/components/camel-testcontainers/.flattened-pom.xml to /home/kkakarla/.m2/repository/org/apache/camel/camel-testcontainers/3.0.0-SNAPSHOT/camel-testcontainers-3.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
`

**Comment by akoufoudakis** [comment]
Thanks for the quick response. Really weird... Can you, please, also tell me, which mvn command(s) do you execute?

**Comment by ramu11** [comment]
mvn clean install

**Comment by akoufoudakis** [comment]
> mvn clean install

Hm... I execute the same and still get issues. Just pulled everything from master and have the same error. Surprisingly, I also have the same error when I execute the same goals on the "camel-pulsar" component. So, should be something strange in my environment...

**Comment by ramu11** [comment]
not sure what is going wrong in your env. can you please close this pull request

**Pull request closed without merging**
