### PR TITLE
Adding Nominatim support for geocoder

### PR DESCRIPTION
**Pull request by Delawen**
I added support for Nominatim servers to the geocoder component. By default it does a fallback to Google if no type specified, so it is backwards compatible.

Why add Nominatim?
Google is not only restricted licensed but also requires a key and even a paid user to be able to do geocoding.

The Nominatim option allows you to use your own hosted FOSS geocoder server (https://github.com/osm-search/Nominatim) with your custom geospatial objects (by default, based on OpenStreetMap). 

For low traffic sparse geocoding, you can also use the hosted nominating as reference, which is the one used on tests.

Not sure if tests should be disabled by default, as they query a remote server we don't have control over.

### CODE REVIEW

**Comment by Delawen** [comment]
The failure is not on the code I pushed. Is it related anyway? Maybe a pull rebase could fix it?

**Comment by Delawen** [comment]
I will need some pointers on the karaf stuff :)

**Comment by oscerd** [comment]
This has been merged and camel-karaf aligned. Thanks for this.

**Comment by Delawen** [comment]
Thanks!

**Pull request closed without merging**
