### PR TITLE
Add proper endChoice() and end() blocks

### PR DESCRIPTION
**Pull request by swapy**
Need to add proper endChoice() and end() blocks to show correct way to work with choices(as a best practice). 
Since this is quite fundamental requirement, it is necessary to have complete documentation stating all facts.

Also not sure about following:
1. do we need to add endChoice() after otherwise()?
2. do we need to make any changes in xml based configuration or it ends by default?(I suppose it works by default)
3. Do we also need to document meaning of endChoice() and end()?
4. Additionally, should we mention limitation on loop nesting in documentation, an example would also add value.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
The First PR need to be done on master and eventually, if it is correct, it will backported.

**Comment by swapy** [comment]
@oscerd Somehow I am not able to fork this repository.

It always creates a fork of 3.4.x
image


I am not sure what would be the correct way.

if I continue with the fork, it adds too many additional commits in PR

**Comment by oscerd** [comment]
You are looking at the 3.4.x docs. Switch to latest there is a drop-down menu if you are navigating the website

**Comment by swapy** [comment]
should close this PR in favour of #5311

**Pull request closed without merging**
