### PR TITLE
CAMEL-17197: camel-elasticsearch - Avoid using deprecated APIs

### PR DESCRIPTION
**Pull request by essobedo**
Fix for https://issues.apache.org/jira/browse/CAMEL-17197

## Motivation

When running test IT tests some warnings appear in the console, we would like to get rid of them.

## Modifications

* No more set the mapping type in the requests since it is [deprecated](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/removal-of-types.html)
* Re-add the test `ElasticsearchSizeLimitIT` as it passes (not related to the initial issue)
* Clean up the code by removing existing warnings raised by IntelliJ. (not related to the initial issue)

## Result

No more warnings in the log:

```
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchIndexIT
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.323 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchIndexIT
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchClusterIndexIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 12.788 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchClusterIndexIT
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchBulkIT
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.935 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchBulkIT
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchSizeLimitIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.515 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchSizeLimitIT
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchPingIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 10.191 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchPingIT
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchGetSearchDeleteExistsUpdateIT
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.271 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchGetSearchDeleteExistsUpdateIT
[INFO] Running org.apache.camel.component.elasticsearch.integration.ElasticsearchScrollSearchIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.558 s - in org.apache.camel.component.elasticsearch.integration.ElasticsearchScrollSearchIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 29, Failures: 0, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
For elasticsearch we need also to find a solution for upgrading to a newer version and use a client with a compatible license

**Comment by essobedo** [comment]
@oscerd this client seems to have the correct license (Apache v2) https://search.maven.org/artifact/org.elasticsearch.client/elasticsearch-rest-client/8.4.1/jar

**Comment by oscerd** [comment]
Yes, but some of the features of the high level client won't be available

**Comment by essobedo** [comment]
There is also [Elasticsearch Java API Client [8.4]](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/current/index.html) which also has  [the correct license](https://search.maven.org/artifact/co.elastic.clients/elasticsearch-java/8.4.1/jar) (Apache v2)

**Comment by essobedo** [comment]
It is actually the client that replaces the [Java High Level REST Client](https://github.com/elastic/elasticsearch/edit/7.17/docs/java-rest/high-level/index.asciidoc)
I quote:
```
Deprecated in 7.15.0.
The High Level REST Client is deprecated in favour of the [Java API Client](https://www.elastic.co/guide/en/elasticsearch/client/java-api-client/7.17/index.html).
```

**Comment by oscerd** [comment]
We do need to switch at some point

**Comment by essobedo** [comment]
There is a ticket for it [CAMEL-17780](https://issues.apache.org/jira/browse/CAMEL-17780).

**Comment by oscerd** [comment]
Yes, I didn't find the time to start to work on it. But I believe it needs to be done

**Pull request merged**
