### PR TITLE
CAMEL-19985: add Smooks component

### PR DESCRIPTION
**Pull request by cjmamo**
# Description

I've laid out the ground work to add the Smooks component as discussed in https://github.com/smooks/smooks-camel-cartridge/issues/211. I'm handing this PR over to the Camel maintainers to change as needed.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking

- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks for your contribution!

I did a quick review and found some items that need changes and adjustments.

**Comment by davsclaus** [comment]
@orpiske all those adjust to camel standard is something we do ourselves

**Comment by orpiske** [comment]
> @orpiske all those adjust to camel standard is something we do ourselves

Respectfully, I disagree. We should ensure that any code that enters the tree is in the most clean state possible. 
Otherwise, we have to keep polluting our git history with regen commits that add little to no value to the actual project history (and make bisecting the code base much harder).

At least that's my understanding from the discussion we had during the development discussions for Camel 4.

**Comment by davsclaus** [comment]
PR with adjusted code
https://github.com/apache/camel/pull/14310

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged via https://github.com/apache/camel/pull/14310

**Pull request closed without merging**
