### PR TITLE
CAMEL-13783: Fix the camel-archetype-component to inherit from DefaultConsumer instead of ScheduledPollConsumer

### PR DESCRIPTION
**Pull request by omarsmak**
Per the title, this will fix the generated `camel-archetype-component` project to inherit from `DefaultConsumer` instead of `ScheduledPollConsumer`

### CODE REVIEW

**Comment by omarsmak** [comment]
Thanks for the tip @davsclaus . Then to simulate the event, do you think it makes sense to use something like `CamelJmsTestHelper`  like [here](https://github.com/apache/camel/blob/master/components/camel-jms/src/test/java/org/apache/camel/component/jms/activemq/ActiveMQConsumeWildcardQueuesTest.jav) to in order simulate event trigger to the component ?

**Comment by jbonofre** [comment]
It sounds reasonable to align the archetype title with the actual implementation. Let me take a look.

**Comment by omarsmak** [comment]
Maybe it will make sense to create two different components archetypes, one for the event driven consumer and one for the polling consumer?

**Comment by jbonofre** [comment]
@omarsmak yes, it makes sense. I'm not using archetypes, but agree it could help some users.

**Comment by omarsmak** [comment]
Then if everyone agrees, we can limit the scope of this PR to change only the naming of the archetype for the current one (polling consumer) to something like `camel-archetype-synchronous-component` or `camel-archetype-polling-component`. 
Then for the event driven consumer, we can have it on a separate PR/JIRA, I think the naming for the event driven consumer can stay the same as now (`camel-archetype-component`) since is the default consumer I think (please correct me if I am wrong here :)). What everyone thinks?

**Comment by davsclaus** [comment]
Frankly I dont think it makes sense to have 2 archetypes. 99% of new components are DefaultConsumer so lets change it to be that and add some sample code that triggers an event (even if we build our own timer etc). We can mention in the docs  / code comments that there is a ScheduledConsumer for such use cases, where people can take a look at camel-scheduler

**Comment by omarsmak** [comment]
Hey @davsclaus @jbonofre , I have added an event bus helper to broadcast the events to the consumer in order to demonstrate the event driven consumer, please take a look at it and let me know what do you think and what I cam change further.

**Comment by oscerd** [comment]
Can you have another look @davsclaus ?

**Comment by davsclaus** [comment]
Yeah I will take a look later, in the middle of improving the mock component

**Pull request merged**
