### PR TITLE
CAMEL-13119: Feature JCachePolicy

### PR DESCRIPTION
**Pull request by bszeti**
A interceptor policy for routes with caching capabilities.
See https://issues.apache.org/jira/browse/CAMEL-13119

### CODE REVIEW

**Comment by davsclaus** [comment]
It would be good with an example in XML DSL how to setup and use this policy

**Comment by bszeti** [comment]
Example with XML DSL? Good point, I'll have a look.

**Comment by oscerd** [comment]
Thanks, merged on master. I'll leave the ticket open for the example in XML DSL

**Comment by bszeti** [comment]
Created tests and examples with XML DSL:
https://github.com/apache/camel/pull/2780

**Pull request closed without merging**
