### PR TITLE
CAMEL-13990: Add schema name checks in EndpointAnnotationProcessor

### PR DESCRIPTION
**Pull request by omarsmak**
In case if the schema name is not lowercase, the compilation will fail with an error message that indicates where it happened and why: For example:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.496 s
[INFO] Finished at: 2019-09-18T13:36:15+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project camel-debezium: Compilation failure
[ERROR] error: Schema name 'debezZum' in 'org.apache.camel.component.debezium.DebeziumEndpoint' must be lowercase!
[ERROR] 
...
-----------------------------------------------------------------------------------------------
```

### CODE REVIEW

**Comment by davsclaus** [comment]
Yeah letøs do a WARN logging and report this as a deprecated syntax. 
There can be 3rd party components that use mixed-case and this allows them to continue to work.

**Comment by omarsmak** [comment]
@davsclaus @oscerd changed it from `ERROR` to `WARN`.

**Comment by oscerd** [comment]
I'm merging this one.

**Comment by oscerd** [comment]
Merged on master

**Pull request closed without merging**
