### PR TITLE
[CAMEL-11487] provided support for resources load through custom defi…

### PR DESCRIPTION
**Pull request by valdar**
…ned protocols by registering custom UrlHandlersi

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR, can you run checkstyle and fix problems

    mvn compile -P sourcecheck

**Comment by davsclaus** [comment]
The javadoc at should be updated to mention about using the jdk url handler
https://github.com/valdar/camel/blob/04afd709415424107c8bc97dafc7e5c0ca81264e/camel-core/src/main/java/org/apache/camel/util/ResourceHelper.java#L122

**Comment by valdar** [comment]
I should have corrected style (`mvn compile -P sourcecheck`) is passing now. 
Added the javadoc documentation, let me know if it is clear.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by valdar** [comment]
Thanks.

**Pull request closed without merging**
