### PR TITLE
deliveryTag -> For manual ack

### PR DESCRIPTION
**Pull request by mayurvaid-redvest**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Comment by davsclaus** [comment]
Are you able to update the docs (see src/main/docs) about this delivery tag and how to do a manual commit

**Review by oscerd — CHANGES_REQUESTED** [review]
I think deliveryTag String should be declared in the Constants class.

**Comment by davsclaus** [comment]
> I think deliveryTag String should be declared in the Constants class.

Yes

**Comment by mayurvaid-redvest** [comment]
> Are you able to update the docs (see src/main/docs) about this delivery tag and how to do a manual ack

Thanks for reviewing , Will add this documentation

**Comment by davsclaus** [comment]
any update?

**Comment by mayurvaid-redvest** [comment]
> any update?

Updated the docs and added constant as well

**Review by oscerd — APPROVED** [review]

**Comment by mayurvaid-redvest** [comment]
> I wonder if the delivery tag only make sense to have as a header if ack mode is manual? Are there situations where you need this information elsewhere ?

Yes Even i am not aware of scenario where we would need this , But having and header would anyways help and gives flexibility to opt for it or not , What are your thoughts

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
