### PR TITLE
Suggestion

### PR DESCRIPTION
**Pull request by mikadev**
I want to continue use SpringRouteBuilder but i also want to use EndpointRouteBuilder so i suggest to inherit from EndpointRouteBuilder

### CODE REVIEW

**Comment by davsclaus** [comment]
Yes we dont want to tie to spring, and spring route builder dont give much value for end users. You can lookup via the Camel registry. And all the other bits you can get via spring camel context etc.

**Comment by mikadev** [comment]
Yeah of course we dont want to tie to spring, but why we should extending specific class to be allowed to use the component dsl for my point it should be available as core functionality, maybe isn't production ready yet ?

**Comment by mikadev** [comment]
@davsclaus what are your thinking about suggestion to avoid requirement of inheriting specific class ?

**Comment by davsclaus** [comment]
we have deprecated the spring route builder, its not really much in use and we wont have that for other runtimes - use plain route builder or the endpoint dsl route builder

**Comment by mikadev** [comment]
A ok so its design choice i understand thanks

**Pull request closed without merging**
