### PR TITLE
CAMEL-18932: Upgrade to slf4j-api 2.0.6

### PR DESCRIPTION
**Pull request by davsclaus**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I have something locally for this, but we need to move to logback 1.4.x and log4j 2.19.0 too

**Comment by oscerd** [comment]
@davsclaus I added the updates

**Comment by davsclaus** [comment]
Thanks a lot

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Seems to be good.

**Pull request merged**
