### PR TITLE
Update CamelJBang.java from 4.0.0 to 4.0.1

### PR DESCRIPTION
**Pull request by apupier**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
I think there is still a 2nd file with that same header, so it needs to be updated 2 places

**Comment by apupier** [comment]
Updated the second file

**Comment by davsclaus** [comment]
This should be backported to 4.0.x branch also

**Comment by apupier** [comment]
rebased on main branch and created PR to backport to 4.0.x

**Pull request merged**
