### PR TITLE
[CAMEL-13654] optaplanner-7.23 not usable in WildFly

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by davsclaus** [comment]
Hmm if we downgrade we just keep having the problem in the future, have you talked/reported to this optaplanner team

**Comment by tdiesler** [comment]
Yes, the comment is also referenced in [CAMEL-13654](https://issues.apache.org/jira/browse/CAMEL-13654)

https://github.com/kiegroup/drools/commit/85c5308031a84a0ac4086c1df363bb1b4b3c6af9

**Comment by oscerd** [comment]
The original commit https://github.com/apache/camel/commit/24a197c889df16add0065fce601810a3e288bc02

is not part of M3, so downgrade seems to be feasible, but as @davsclaus said we need to report this to the Optaplanner team. Also it's not a good idea to downgrade

> The original commit [24a197c](https://github.com/apache/camel/commit/24a197c889df16add0065fce601810a3e288bc02)
> 
> is not part of M3, so downgrade seems to be feasible, but as @davsclaus said we need to report this to the Optaplanner team. Also it's not a good idea to downgrade only Optaplanner, these projects: Optaplanner, JBPM, Kie and Drools are all strongly related, so if we downgrade we need to downgrade them all. But first is better to make them aware of the problem

I just read the comment in the code, it should be enough

**Comment by tdiesler** [comment]
Downgraded jbpm, drools, kie & optaplanner

**Comment by oscerd** [comment]
@davsclaus what do you think about downgrading here? I'm +1. I'd like to have more feedback.

**Comment by davsclaus** [comment]
@oscerd yeah I am +1 also. But I would maybe add a  so we remember and not upgrade in 3 months again

**Comment by oscerd** [comment]
Sure, I'll open an issue on our side and try to open an issue to Optaplanner too, linking the comment from @tdiesler

**Pull request merged**
