### PR TITLE
CAMEL-13592 Repeated parameters in URI are not treated correctly

### PR DESCRIPTION
**Pull request by sumeetpatil**

### CODE REVIEW

**Comment by bedlaj** [comment]
Thanks for contribution. I am adding few non binding opinions: There are some tests, which relies on the actual behavior. Eg `SedaBlockWhenFullInvalidConfigurationTest#testInvalidConfiguration` will most probably fail after this change. It also breaks CAMEL-12571 implementation. This change should be most probably discussed with some ASF member first.

**Comment by sumeetpatil** [comment]
Hi @bedlaj ,
Yes, you are right. Thanks for pointing that out. These test cases will fail. Looks like they have to be removed with this PR. I will check more on this and also wait for more comments/suggestions.

**Comment by davsclaus** [comment]
Thanks @sumeetpatil could you maybe build a PR with an unit test in camel-sql that has this 2x batch=true issue, that we can use to better find a correct solution.

Also its really a user mistake for you to do this, and thus the current logic is correct that it builds this up as a list of multi-values.

**Comment by davsclaus** [comment]
Thanks for the PR. The issue is related to we are too lenient when converting to boolean type, so we have logged a ticket: https://issues.apache.org/jira/browse/CAMEL-13732 and work on a general fix there.

**Pull request closed without merging**
