### PR TITLE
Backport CAMEL-17461 to 3.14.x

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.apache.org/jira/browse/CAMEL-17461

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@ppalaga there is a merge conflict - can you update this PR.

@oscerd we need to change camel-karaf also - so we need to fix the commits that changed in camel-karaf which we need to backport also.

**Review by zhfeng — APPROVED** [review]

**Comment by ppalaga** [comment]
> @ppalaga please just rebase and remove my commit [dbd82de](https://github.com/apache/camel/commit/dbd82de2af84a1d0c9c7d2c3e7c0fd4af2c47fa6). Sorry for that I have to forch push to fix the backport issue with [CAMEL-17474](https://issues.apache.org/jira/browse/CAMEL-17474).

Thanks @zhfeng, done.

**Comment by oscerd** [comment]
> There are these 3 karaf commits [apache/camel-karaf@38827c3](https://github.com/apache/camel-karaf/commit/38827c3c2fba5dea489204da67cb04752b1f3462) [apache/camel-karaf@e30ce28](https://github.com/apache/camel-karaf/commit/e30ce28997293eda9397c6529e5d77a1fe62f7ed) [apache/camel-karaf@38827c3](https://github.com/apache/camel-karaf/commit/38827c3c2fba5dea489204da67cb04752b1f3462)

I'll take care of this

**Comment by ppalaga** [comment]
> > There are these 3 karaf commits [apache/camel-karaf@38827c3](https://github.com/apache/camel-karaf/commit/38827c3c2fba5dea489204da67cb04752b1f3462) [apache/camel-karaf@e30ce28](https://github.com/apache/camel-karaf/commit/e30ce28997293eda9397c6529e5d77a1fe62f7ed) [apache/camel-karaf@38827c3](https://github.com/apache/camel-karaf/commit/38827c3c2fba5dea489204da67cb04752b1f3462)
> 
> I'll take care of this

Thanks a lot, @oscerd !

**Comment by oscerd** [comment]
Done.

**Comment by thorin8k** [comment]
I've found that in RabbitMQProduccer class there is a non existing method being used:

image

Based on the API of the commons-pool2 version used (2.11.1) that method is not present:
https://commons.apache.org/proper/commons-pool/apidocs/index.html

This fails since 3.14.1 so the only solution for me was downgrading to 3.14.0.

**Comment by oscerd** [comment]
https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/GenericObjectPoolConfig.html

I'm not quite sure what you mean:
- it's a class
- it's in commons-pool2

In Camel 3.14.1 tag the commons-pool library version is the v1 and not commons-pool2: https://github.com/apache/camel/blob/camel-3.14.1/components/camel-rabbitmq/pom.xml#L45

So probably the problem is on your side.

**Comment by thorin8k** [comment]
Sorry wrong explanation on my side.

The problem is with method `setMaxWait` which doesn't exist on class GenericObjectPoolConfig.

This pullrequest changed rabbitmq to use `commons-pool2` but its using a non existing method.
image


Here you can see the changes: https://github.com/apache/camel/pull/7030/files#diff-2425b237cac63ec03f8cfbe5ff202747f2bba084624a139cf32d9231d349229f

**Comment by oscerd** [comment]
The Class GenericObjectPoolConfig extend the BaseObjectPoolConfig which has the maxWait field.
https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseObjectPoolConfig.html
and in particular the setMaxWait method
https://commons.apache.org/proper/commons-pool/apidocs/org/apache/commons/pool2/impl/BaseObjectPoolConfig.html#setMaxWait-java.time.Duration-

However, with a non-existent method, the release 3.14.1 or subsequent wouldn't be possible, the build couldn't be completed and we wouldn't be able to release. I don't know what error you are getting but definitely is not something from the Camel side.

**Pull request merged**
