### PR TITLE
Feature/upgrade spring security

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Comment by oscerd** [comment]
You need to Change bundle version too

**Comment by davidkarlsen** [comment]
The bundle is for the 4.x? I upgraded the plain 5.x.
Where is the bundle used:
```
find . -name pom.xml|xargs fgrep -il spring-security-bundle-version
./parent/pom.xml
```

**Comment by oscerd** [comment]
oscerd@ghost:~/workspace/apache-camel/camel$ git grep "spring-security-bundle-version"
parent/pom.xml:    <spring-security-bundle-version>4.2.4.RELEASE_1</spring-security-bundle-version>
platforms/karaf/features/src/main/resources/features.xml:    <bundle dependency='true'>mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-security-core/${spring-security-bundle-version}</bund
platforms/karaf/features/src/main/resources/features.xml:    <bundle>mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-security-config/${spring-security-bundle-version}</bundle>

**Comment by oscerd** [comment]
Even though Spring Boot is important, OSGi support can't be totally ignored.

**Comment by davidkarlsen** [comment]
I can't find any more recent bundles for 4.x:
https://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.spring-security-core .
The boot upgrade is from https://github.com/apache/camel/pull/2331

**Comment by oscerd** [comment]
mvnrepository.com is not updated in real-time.

There is a new released bundle for 5.0.4.RELEASE

http://repo2.maven.org/maven2/org/apache/servicemix/bundles/org.apache.servicemix.bundles.spring-security-core/

For the moment I'd stay with the same version for plain too.

**Comment by oscerd** [comment]
Since #2331 has been merged, I'm merging this one

**Comment by oscerd** [comment]
The Karaf feature doesn't work actually, but we can revisit, because I believe it's a problem at bundle level.

**Comment by oscerd** [comment]
Merged on master. Thanks @davidkarlsen

**Pull request closed without merging**
