### PR TITLE
CAMEL-20686 -  Appended static test filenames with UUID (set 5)

### PR DESCRIPTION
**Pull request by jvsingh**
# Description
- Appended static test filenames with UUID (set 5)
- Fixed code smell issues flagged on Sonar: 
```
FileProducerFileExistOverrideTest.java
FileProducerFileExistTryRenameTest.java
FileConsumerIdempotentKeyChangedIssue2Test.java
FileBeginFailureOneTimeTest.java
```
- Prioritising tests in core/camel-core based on Devlocity flakiness & issues identified on sonar

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by orpiske — APPROVED** [review]
Thanks!

**Review by oscerd — APPROVED** [review]

**Comment by jvsingh** [comment]
Not sure why these PR Builds failed. I have no local changes after mvn verify , and these tests succeeded after the changes

**Comment by oscerd** [comment]
Tests are failing:

`
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.020 s <<< FAILURE! -- in org.apache.camel.component.file.FileProducerFileExistTryRenameTest
[ERROR] org.apache.camel.component.file.FileProducerFileExistTryRenameTest.testIgnore -- Time elapsed: 0.019 s <<< FAILURE!
java.lang.AssertionError: mock://result Content of file: /tmp/junit8691465796114605607/hello85e6d201-01b6-4c37-8a57-0b45b2a7340a.txt. Expected: <Bye World> but was: <Hello World>
	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1975)
	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1917)
	at org.apache.camel.component.mock.MockEndpoint.lambda$expectedFileExists$4(MockEndpoint.java:1071)
	at org.apache.camel.component.mock.MockEndpoint.runTests(MockEndpoint.java:489)
	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:470)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:432)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:422)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:218)
	at org.apache.camel.ContextTestSupport.assertMockEndpointsSatisfied(ContextTestSupport.java:887)
	at org.apache.camel.component.file.FileProducerFileExistTryRenameTest.testIgnore(FileProducerFileExistTryRenameTest.java:45)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.061 s -- in org.apache.camel.component.file.FileConsumerAbsolutePathDefaultMoveTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.060 s -- in org.apache.camel.processor.ResequenceBatchNotIgnoreInvalidExchangesTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.120 s -- in org.apache.camel.issues.ThreadsRejectedExecutionWithDeadLetterTest
[INFO] Running org.apache.camel.component.file.FileProducerFileExistTryRenameTest
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! -- in org.apache.camel.component.file.FileProducerFileExistTryRenameTest
[ERROR] org.apache.camel.component.file.FileProducerFileExistTryRenameTest.testIgnore -- Time elapsed: 0.009 s <<< FAILURE!
java.lang.AssertionError: mock://result Content of file: /tmp/junit13472529278761769903/hello85e6d201-01b6-4c37-8a57-0b45b2a7340a.txt. Expected: <Bye World> but was: <Hello World>
	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1975)
	at org.apache.camel.component.mock.MockEndpoint.assertEquals(MockEndpoint.java:1917)
	at org.apache.camel.component.mock.MockEndpoint.lambda$expectedFileExists$4(MockEndpoint.java:1071)
	at org.apache.camel.component.mock.MockEndpoint.runTests(MockEndpoint.java:489)
	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:470)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:432)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:422)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:218)
	at org.apache.camel.ContextTestSupport.assertMockEndpointsSatisfied(ContextTestSupport.java:887)
	at org.apache.camel.component.file.FileProducerFileExistTryRenameTest.testIgnore(FileProducerFileExistTryRenameTest.java:45)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] org.apache.camel.component.file.FileProducerFileExistTryRenameTest.testIgnore
[ERROR]   Run 1: FileProducerFileExistTryRenameTest.testIgnore:45->ContextTestSupport.assertMockEndpointsSatisfied:887 mock://result Received message count. Expected: <1> but was: <2>
[ERROR]   Run 2: FileProducerFileExistTryRenameTest.testIgnore:45->ContextTestSupport.assertMockEndpointsSatisfied:887 mock://result Content of file: /tmp/junit8691465796114605607/hello85e6d201-01b6-4c37-8a57-0b45b2a7340a.txt. Expected: <Bye World> but was: <Hello World>
[ERROR]   Run 3: FileProducerFileExistTryRenameTest.testIgnore:45->ContextTestSupport.assertMockEndpointsSatisfied:887 mock://result Content of file: /tmp/junit13472529278761769903/hello85e6d201-01b6-4c37-8a57-0b45b2a7340a.txt. Expected: <Bye World> but was: <Hello World>
[INFO] 
[WARN] Flakes: 
[WARN] org.apache.camel.component.file.FileConsumerAbsolutePathDefaultMoveTest.testConsumeFromAbsolutePath
[ERROR]   Run 1: FileConsumerAbsolutePathDefaultMoveTest.testConsumeFromAbsolutePath mock://report Body of message: 0. Expected: <Hello Paris> but was: <>
[INFO]   Run 2: PASS
[INFO] 
[WARN] org.apache.camel.issues.ThreadsRejectedExecutionWithDeadLetterTest.testThreadsRejectedExecution
[ERROR]   Run 1: ThreadsRejectedExecutionWithDeadLetterTest.testThreadsRejectedExecution:71->ContextTestSupport.assertMockEndpointsSatisfied:887 mock://failed Received message count. Expected: <1> but was: <0>
[INFO]   Run 2: PASS
[INFO] 
[WARN] org.apache.camel.processor.ResequenceBatchNotIgnoreInvalidExchangesTest.testBadThirdMessage
[ERROR]   Run 1: ResequenceBatchNotIgnoreInvalidExchangesTest.testBadThirdMessage mock://result Body of message: 1. Expected: <C> but was: <D>
[INFO]   Run 2: PASS
[INFO] 
[INFO] 
[ERROR] Tests run: 6413, Failures: 1, Errors: 0, Skipped: 94, Flakes: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:31 min (Wall Clock)
[INFO] Finished at: 2024-07-17T05:44:38Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.1:test (default-test) on project camel-core: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/runner/work/camel/camel/core/camel-core/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.3.1:test (default-test) on project camel-core: There are test failures.

Please refer to /home/runner/work/camel/camel/core/camel-core/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:347)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at io.takari.maven.builder.smart.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:204)
	at io.takari.maven.builder.smart.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:78)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.maven.plugin.MojoFailureException: There are test failures.

Please refer to /home/runner/work/camel/camel/core/camel-core/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
	at org.apache.maven.plugin.surefire.SurefireHelper.throwException(SurefireHelper.java:247)
	at org.apache.maven.plugin.surefire.SurefireHelper.reportExecution(SurefireHelper.java:159)
	at org.apache.maven.plugin.surefire.SurefirePlugin.handleSummary(SurefirePlugin.java:542)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1117)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:939)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	... 15 common frames omitted
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException`

**Comment by oscerd** [comment]
Thanks

**Pull request merged**
