### PR TITLE
Camel 14009: Add a maven plugin to generate Debezium configuration dynamically 

### PR DESCRIPTION
**Pull request by omarsmak**
This PR intends to add a maven plugin in order to generate DBZ configurations by supplying the configurations through POM. Scope of changes:

1. New structure for camel-debezium, by adding the maven plugin, core code for DBZ is mostly untouched, I only moved it to a new directory.
2. Adding `protected` and `static` support to https://github.com/apache/camel/blob/master/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/srcgen/Method.java.

### CODE REVIEW

**Comment by oscerd** [comment]
I'll merge this today.

**Comment by oscerd** [comment]
I think this needs more work. When you build the new component with this PR added, the component starter is not updated/generated anymore. Also the component won't show up in index.adoc of the components. So I think we can defer this after RC3. @davsclaus sounds good?

**Comment by oscerd** [comment]
My bad, the component starter is still generated. The only missing bits is related to the index.adoc for components

**Comment by omarsmak** [comment]
@oscerd thanks for spotting that, I can take a look at it today. If I can fix it today can we still merge it or anyhow defer it after RC3? Thanks

**Comment by oscerd** [comment]
It would be good to have it in RC3,

**Comment by omarsmak** [comment]
Aha okay. Then I will take a look at index.adoc why is not updated and update the PR today noon.

**Comment by oscerd** [comment]
If I won't be able to merge it I think @davsclaus can merge it too. I don't know if this could be related to the component folder structure

**Comment by davsclaus** [comment]
Ah you need to modify the camel-maven-package-plugin. As it has sub folders. We do this for camel-box and a few others, so just search for those and add for this too

**Comment by omarsmak** [comment]
@davsclaus @oscerd Thanks for the hint! I have added the component in `camel-maven-package-plugin`, I hope this fixes the issue. Thanks

**Comment by oscerd** [comment]
I'm going to merge this.

**Comment by oscerd** [comment]
Merged on master. Thanks.

**Pull request closed without merging**
