### PR TITLE
CAMEL-14910: Bundling of the heavily distributed components 

### PR DESCRIPTION
**Pull request by AemieJ**
* Changes made to `gulpfile.js` but when running the `mvn clean install`, it results in an error each time and my git commits are perhaps overwritten. 
* @djencks, I think it's best to rebase my branch on top of yours as I have tried with `CAMEL-14910-copy` branch within your repo and it resulted in the same FAILURE message. 
* If the java build is working perfectly for you, and the gulpfile works for mine, it's a good choice to go with rebasing.

### CODE REVIEW

**Comment by djencks** [comment]
Could you run `mvn clean install -DskipTests -e` and paste the error and stack trace and any other information that seems relevant?

**Comment by AemieJ** [comment]
```
[ERROR] Failed to execute goal org.apache.camel:camel-package-maven-plugin:3.4.0-SNAPSHOT:generate (generate) on project camel-file: Execution generate of goal org.apache.camel:camel-package-maven-plugin:3.4.0-SNAPSHOT:generate failed: An API incompatibility was encountered while executing org.apache.camel:camel-package-maven-plugin:3.4.0-SNAPSHOT:generate: java.lang.VerifyError: (class: ASMAccessorImpl_92443244515909899567040, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.camel:camel-package-maven-plugin:3.4.0-SNAPSHOT
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/jariw/Documents/Outreachy/camel-copy/tooling/maven/camel-package-maven-plugin/target/camel-package-maven-plugin-3.4.0-SNAPSHOT.jar
[ERROR] urls[1] = file:/C:/Users/jariw/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar
[ERROR] urls[2] = file:/C:/Users/jariw/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar
[ERROR] urls[3] = file:/C:/Users/jariw/Documents/Outreachy/camel-copy/tooling/camel-util-json/target/camel-util-json-3.4.0-SNAPSHOT.jar
[ERROR] urls[4] = file:/C:/Users/jariw/Documents/Outreachy/camel-copy/tooling/camel-tooling-util/target/camel-tooling-util-3.4.0-SNAPSHOT.jar
[ERROR] urls[5] = file:/C:/Users/jariw/Documents/Outreachy/camel-copy/tooling/camel-tooling-model/target/camel-tooling-model-3.4.0-SNAPSHOT.jar
[ERROR] urls[6] = file:/C:/Users/jariw/.m2/repository/org/mvel/mvel2/2.4.7.Final/mvel2-2.4.7.Final.jar
[ERROR] urls[7] = file:/C:/Users/jariw/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[8] = file:/C:/Users/jariw/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[9] = file:/C:/Users/jariw/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar
[ERROR] urls[10] = file:/C:/Users/jariw/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[11] = file:/C:/Users/jariw/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[12] = file:/C:/Users/jariw/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M5/org.eclipse.sisu.inject-0.0.0.M5.jar
[ERROR] urls[13] = file:/C:/Users/jariw/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.19/plexus-interpolation-1.19.jar
[ERROR] urls[14] = file:/C:/Users/jariw/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[15] = file:/C:/Users/jariw/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[16] = file:/C:/Users/jariw/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[17] = file:/C:/Users/jariw/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.6.0/maven-plugin-annotations-3.6.0.jar

at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution generate of goal org.apache.camel:camel-package-maven-plugin:3.4.0-SNAPSHOT:generate failed: An API incompatibility was encountered while executing org.apache.camel:camel-package-maven-plugin:3.4.0-SNAPSHOT:generate: java.lang.VerifyError: (class: ASMAccessorImpl_92443244515909899567040, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
```

```
Caused by: java.lang.VerifyError: (class: ASMAccessorImpl_92443244515909899567040, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
    at java.lang.Class.getDeclaredConstructors0 (Native Method)
    at java.lang.Class.privateGetDeclaredConstructors (Class.java:3215)
    at java.lang.Class.getConstructor0 (Class.java:3420)
    at java.lang.Class.newInstance (Class.java:585)
    at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor (ASMAccessorOptimizer.java:761)
    at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor (ASMAccessorOptimizer.java:895)
    at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor (ASMAccessorOptimizer.java:283)
    at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize (DynamicGetAccessor.java:95)
    at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue (DynamicGetAccessor.java:65)
    at org.mvel2.ast.ASTNode.getReducedValueAccelerated (ASTNode.java:108)
    at org.mvel2.compiler.ExecutableAccessor.getValue (ExecutableAccessor.java:42)
    at org.mvel2.MVEL.executeExpression (MVEL.java:929)
    at org.mvel2.templates.res.CompiledExpressionNode.eval (CompiledExpressionNode.java:45)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledForEachNode.eval (CompiledForEachNode.java:114)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CommentNode.eval (CommentNode.java:42)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledIfNode.eval (CompiledIfNode.java:44)
    at org.mvel2.templates.res.CompiledIfNode.eval (CompiledIfNode.java:46)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledExpressionNode.eval (CompiledExpressionNode.java:46)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.TerminalNode.eval (TerminalNode.java:35)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.TerminalNode.eval (TerminalNode.java:35)
    at org.mvel2.templates.res.CompiledForEachNode.eval (CompiledForEachNode.java:128)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CommentNode.eval (CommentNode.java:42)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledIfNode.eval (CompiledIfNode.java:44)
    at org.mvel2.templates.res.CompiledIfNode.eval (CompiledIfNode.java:46)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledExpressionNode.eval (CompiledExpressionNode.java:46)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledExpressionNode.eval (CompiledExpressionNode.java:46)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.CompiledExpressionNode.eval (CompiledExpressionNode.java:46)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.res.TextNode.eval (TextNode.java:42)
    at org.mvel2.templates.TemplateRuntime.execute (TemplateRuntime.java:285)
    at org.mvel2.templates.TemplateRuntime.execute (TemplateRuntime.java:247)
    at org.mvel2.templates.TemplateRuntime.execute (TemplateRuntime.java:255)
    at org.mvel2.templates.TemplateRuntime.execute (TemplateRuntime.java:203)
    at org.mvel2.templates.TemplateRuntime.eval (TemplateRuntime.java:103)
    at org.apache.camel.maven.packaging.UpdateReadmeMojo.evaluateTemplate (UpdateReadmeMojo.java:762)
    at org.apache.camel.maven.packaging.UpdateReadmeMojo.executeComponent (UpdateReadmeMojo.java:177)
    at org.apache.camel.maven.packaging.UpdateReadmeMojo.execute (UpdateReadmeMojo.java:116)
    at org.apache.camel.maven.packaging.AbstractGeneratorMojo.execute (AbstractGeneratorMojo.java:72)
    at org.apache.camel.maven.packaging.UpdateReadmeMojo.execute (UpdateReadmeMojo.java:110)
    at org.apache.camel.maven.packaging.AbstractGenerateMojo.invoke (AbstractGenerateMojo.java:75)
    at org.apache.camel.maven.packaging.GenerateMojo.doExecute (GenerateMojo.java:62)
    at org.apache.camel.maven.packaging.AbstractGenerateMojo.execute (AbstractGenerateMojo.java:60)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by djencks** [comment]
That’s not a problem with our work. Googling, it seems to be a problem with mvel on jdks >11. I’m u  sing Jdk 11, what are you using?

**Comment by AemieJ** [comment]
> That’s not a problem with our work. Googling, it seems to be a problem with mvel on jdks >11. I’m u sing Jdk 11, what are you using?

 jdk 14. I will use jdk 11 and check.

**Comment by AemieJ** [comment]
@djencks I am facing the same build problem at `CAMEL:: File` even for jdk 11

**Comment by djencks** [comment]
I'm often confused by what jdk maven is using.  If you run `mvn --version` does it say you have succeeding in getting it to run jdk 11 :-) ?

**Comment by AemieJ** [comment]
@djencks That solved the problem, however, the build works for components however it fails at `CAMEL:: Kudu`

```
 Could not resolve dependencies for project org.apache.camel:camel-kudu:jar:3.4.0-SNAPSHOT: Failure to find org.apache.kudu:kudu-binary:jar:windows-x86_64:1.10.0 in https://repo1.maven.org/maven2/ was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
```

The `pom.xml` is the same as the parent repo for camel-kudos.

**Comment by djencks** [comment]
I checked on maven central (https://search.maven.org/artifact/org.apache.kudu/kudu-binary/1.10.0/jar) and it looks like there are only binaries for linux and osx.
Unless you can find another solution, what I suggest is:
- Claus just applied my PR, so if you rebase on master your PR will be working with it and able to be applied directly.
- Tomorrow I'll work with your PR, run the build to generate the final adoc files, and either add a commit to your PR (I'm not sure if that's possible) or make another PR with the changes.  Hopefully we can then get them committed!

**Comment by AemieJ** [comment]
@djencks I was using windows till now to run maven, I will use Linux and try to make it work out.

**Comment by AemieJ** [comment]
@djencks I have done the java build and generated the `nav.adoc` the file however I found a slight issue in it though I manually resolved it. The issue was that `aws-summary.adoc` and `aws2-summary.adoc` when generated within the docs, for the nav.adoc they came in continuous and not segmented to their respective bundle. It appeared as followed within the nav.adoc: 
```
- aws-summary.adoc
- aws2-summary.adoc 
```

**Comment by djencks** [comment]
We need a better sorting algorithm.
If the summary-group was always the same as the docTitle, then I think the comparison for the sort could be (lets assume everything is uppercased already):
comparing (docTitle1, group1) and (docTitle2, group2):
- notice if they are equal, return 0
- if group1 and group2 are null, then return comparison docTitle1 and docTitle2
- if group1 and group2 are both present, compare them
-- if not equal, return comparison
-- if equal, return comparison of docTitle1 and docTitle2
- if only group1 is present:
-- if group1 === docTitle2, then the first item is after the second item.
-- otherwise, return the comparison of group1 and docTitle2.
- if only group2 is present:
-- if docTitle1 === group2, then the first item is before the second item.
-- otherwise, return the comparison of docTitle1 and group2.

Does this make sense?  Assuming it does, do you want to write the code for this or shall I?

**Comment by AemieJ** [comment]
@djencks By group you mean the sorting of **summary-group** right? 'cause that's the one where the issue is arising. Also for the 4th and 5th case, not all have **summary-group** attribute so when would the case be that group1 will be equal to docTitle2 and same equality thing for the 5th case.

**Comment by djencks** [comment]
I could have been a lot clearer :-)
I'm suggesting removing summary-group and using docTitle instead.
Then "summary-group" (docTitle) will always be present.
If we allow summary-group to differ from docTitle then we will need a much more complicated sorting algorithm, which would probably start by basically replacing summary-group values and the corresponding group values with docTitle.

The items in the current nav are actually sorted in lexicographical order, but that doesn't correspond to our desired grouping. 
```
** xref:aws-summary.adoc[AWS]
** xref:aws2-summary.adoc[AWS 2]
*** xref:aws2-cw-component.adoc[AWS 2 CloudWatch]
*** xref:aws2-ddb-component.adoc[AWS 2 DynamoDB]
...
*** xref:aws2-sqs-component.adoc[AWS 2 Simple Queue Service (SQS)]
*** xref:aws2-translate-component.adoc[AWS 2 Translate]
*** xref:aws-cw-component.adoc[AWS CloudWatch]
*** xref:aws-ddb-component.adoc[AWS DynamoDB]
```
`2` comes before `C`

**Comment by AemieJ** [comment]
Alright, summary group is the same as docTitle only. It makes sense now.

**Comment by AemieJ** [comment]
> We need a better sorting algorithm.
> If the summary-group was always the same as the docTitle, then I think the comparison for the sort could be (lets assume everything is uppercased already):
> comparing (docTitle1, group1) and (docTitle2, group2):
> 
> * notice if they are equal, return 0
> * if group1 and group2 are null, then return comparison docTitle1 and docTitle2
> * if group1 and group2 are both present, compare them
>   -- if not equal, return comparison
>   -- if equal, return comparison of docTitle1 and docTitle2
> * if only group1 is present:
>   -- if group1 === docTitle2, then the first item is after the second item.
>   -- otherwise, return the comparison of group1 and docTitle2.
> * if only group2 is present:
>   -- if docTitle1 === group2, then the first item is before the second item.
>   -- otherwise, return the comparison of docTitle1 and group2.
> 
> Does this make sense? Assuming it does, do you want to write the code for this or shall I?

For the  summary page of AWS i.e **aws-summary.adoc** will be always sorted before **aws2-summary.adoc**

**Comment by AemieJ** [comment]
@djencks I wrote a sorting function that works and also weren't we planning to use **summary-group** to create an index-list to auto-generate the list within the **-summary.adoc** instead of manual typing.

**Comment by djencks** [comment]
- I left out an important sorting case, when group1 <> group2 but both are present.  This results in the sub-list being unsorted.
- Please change the group for the `AWS 2` sublist rather than the docTitle for the parent.
- Use === and !== rather than == and !=
- Use const rather than let or var for constants
- line 166 is unnecessary and wrong (if present, it would need the symmetrical other case with the titles in the other order).
- The ternary operator looks best when there are spaces surrounding both the ? and : (at least that's what I'm used to).
- I think the sorting code, which is rather complicated and hard to understand, will be easier to read if we compute all the things we'll be comparing at the top rather than over and over again, something like:
```
    if (file1 === file2) return 0
    var t
    const group1 = (t = groupFrom(file1)) && t.toUpperCase()
    const group2 = (t = groupFrom(file2)) && t.toUpperCase()
...//same for title1, title2
```

Locally, I'm seeing an additional generated change to AWS x-ray.  Since this is an "other" component I don't think it needs a group.  I'm not sure why you wouldn't see this.

**Comment by djencks** [comment]
When I look at the aws xray component adoc, it appears to have a ":group: AWS" line that I'm pretty sure you added.  I don't think it's needed.

Have you noticed that the sublists are not sorted correctly? I was explaining what is missing.  There are two cases when both group1 and group2 are present, either they are equal or not.  We need to deal appropriately with both in the sort.

**Comment by AemieJ** [comment]
@djencks  Yea, I will correct that. I missed out on a condition for both groups not null. I will modify it.

**Comment by djencks** [comment]
This looks correct to me, although I didn't try it.  Apparently there are some merge conflicts, but I'm in favor of applying this if you can fix those.

Perhaps you would like to fix the == > === etc for the whole file in a separate issue? I suspect everyone has been used to looking at java and didn't notice the problem here -- I certainly didn't!

**Comment by AemieJ** [comment]
@djencks I don't know why the checks are failing, though it doesn't show any conflicts with the branch. 
And yes, that can be resolved in a different PR, the code structure for the **js** file.

**Comment by AemieJ** [comment]
@davsclaus, @djencks I performed `mvn clean install` command and it builds successfully. I am not sure why the check is failing here.

**Comment by djencks** [comment]
The maven source check problem is unrelated to this work. When this work is merged I think it should have 3 commits:

- the gulpfile changes
- the manual changes to components .adocs adding the "group" attribute
- the generated changes from the maven build and the gulpfile build.

When I tried to investigate the "can't rebase" warning I see from GitHub, and tried git rebase master on your branch, there was certainly a merge conflict, but I couldn't understand it.  I think if you start by running `git rebase -i c9d5377fd7a7888f9edeee649ead99084cccf64e` and reordering and squashing your commits into the above 3 it will be easier to see if there are any actual problems.

**Comment by AemieJ** [comment]
@djencks I did the process with the following 3 commits in the PR#3893 respect with the master branch commits.

**Comment by oscerd** [comment]
Closing this

**Pull request closed without merging**
