### PR TITLE
Manage single version of Guava or avoid it where possible

### PR DESCRIPTION
**Pull request by ppalaga**
https://issues.apache.org/jira/browse/CAMEL-19495
https://issues.apache.org/jira/browse/CAMEL-19496

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Another candidate would be protobuf maybe.

**Comment by ppalaga** [comment]
> Another candidate would be protobuf maybe.

Indeed, it is on my radar :-)

**Review by davsclaus — APPROVED** [review]

**Comment by ppalaga** [comment]
40f1b49 - upgraded to Guava 32.0.1-jre to make the dependency analysis happy.

**Comment by davsclaus** [comment]
############################################################
Testing component 6 of 17: components/camel-ignite
############################################################

Logging test to /home/runner/work/camel/camel/automated-build-log/components-camel-ignite.log
Failed components/camel-ignite test: 6 verified / 1 failed
Copying test log file at target/camel-ignite-test.log to the log directory

**Comment by davsclaus** [comment]
I wonder if you get error in camel-ignite also locally ?

**Comment by ppalaga** [comment]
I studied those logs thoroughly seeking for some hint which of the ignite and other modules' tests is failing on the CI but I have not found anything. Could please somebody share the secret sauce for deciphering those logs?

> I wonder if you get error in camel-ignite also locally ?

No, it is passing for me locally ignite, as well as with some other modules which have failures reported on the CI. Can it be that the CI reports are somehow broken?

**Comment by davsclaus** [comment]
LGTM lets merge this

**Pull request merged**
