### PR TITLE
Use label as ppc64le

### PR DESCRIPTION
**Pull request by Chandranana**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
The label is the one needed to use a PowerPC machine to run the build. Why change that?

https://ci-builds.apache.org/job/Camel/job/el/job/main/642/consoleFull

The current label is working fine. There are no reason to change the value.

**Comment by Chandranana** [comment]
ASF infra team has added the 'power-for-camel' label for testing purpose only, and it will be removed soon. We will have to revert back to ppc64le or power9 label hence made the changes.
Jira issue for reference: https://issues.apache.org/jira/browse/INFRA-24953

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I'm not even sure this is going to work.

**Comment by Chandranana** [comment]
thanks @oscerd. Yes were are working on fixing the CI build, so as per the Jira issue comment implemented this change:
`[Chris Lambertus]: This is not fixed. Please switch back to the ppc64le or power9 label. The problem is that you are not cleaning up your workspace properly, and your workspace is corrupted on power9-1. We will remove the power-for-camel as it was just for testing. Please discuss with the Camel project and have someone from the PMC address this ticket and what your relationship with the project is.`

**Comment by oscerd** [comment]
Well the workspace is cleaned up on each run.

**Pull request merged**
