### PR TITLE
CAMEL-14229: STOMP headers are missing in the Exchange

### PR DESCRIPTION
**Pull request by onlybytes**
The response from the Exchange contains only Body. The STOMP headers are missing in the response.

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks, but can you take a look and see if you can make the consumer use the header filter strategy as it should do that, eg the producer does that. But just make the filtering the reverse.

**Comment by onlybytes** [comment]
@davsclaus Thanks for taking time to review this PR. I need a clarification.
When you say make the filtering reverse, I assume you mean selecting the accepted headers as mentioned [here](https://camel.apache.org/manual/latest/faq/how-to-avoid-sending-some-or-all-message-headers.html)

If my assumption is right, then its perfectly fine to make the filtering reverse when users use the DefaultHeaderFilterStrategy. What if users do not want to use DefaultHeaderFilterStrategy but want to use their own strategy where they do not have filterOnMatch reverse.

**Comment by davsclaus** [comment]
Oh sorry I was really just referring to making the consumer also use the header filter strategy to apply filtering, see maybe one of the other components how it does that.

**Comment by onlybytes** [comment]
@davsclaus Comments incorporated. I have made consumer use the header filter strategy.

**Comment by davsclaus** [comment]
Thanks would you be able to build a unit test also?

**Comment by onlybytes** [comment]
Yes. The unit tests passed.

**Comment by onlybytes** [comment]
Sure. Will give it a try.
I am working on setting custom headers. When i raise a PR for custom headers, i will include this as well

**Comment by davsclaus** [comment]
Okay that sounds good, so will merge this, and you do another PR that incl tests, thanks.

**Pull request merged**
