### PR TITLE
CAMEL-10546: Renamed CamelContext.getProperties to getGlobalOptions

### PR DESCRIPTION
**Pull request by aldettinger**
See [camel-10546](https://issues.apache.org/jira/browse/CAMEL-10546) for more details.

### CODE REVIEW

**Comment by davsclaus** [comment]
I think some code in camel-core-xml / camel-spring and camel-blueprint may use the old deprecated api as you can configure those global options from xml as well.

I wonder if you had time to look there too, and migrate this code to use the newer api?

**Comment by aldettinger** [comment]
Yeah, I will take a look this week. I could also remove use of the old api inside camel-core itself.

**Comment by aldettinger** [comment]
Note that I didn't spot any use of the deprecated api in camel-blueprint. Did I miss something ?

**Comment by davsclaus** [comment]
No I dont think so as its inherited from camel-core-xml

**Comment by davsclaus** [comment]
@aldettinger thanks I will get this merged. There is more work I posted a comment on
https://issues.apache.org/jira/browse/CAMEL-10546

If you can help with that as well would be great. Then you can open a new PR with that work

**Comment by aldettinger** [comment]
Thanks Claus, I will follow your indications in another PR then.

**Pull request closed without merging**
