### PR TITLE
CAMEL-19615: Fix chmodDirectory option

### PR DESCRIPTION
**Pull request by michael-salzburg**
# Description

The current implementation steps down the directory and try to create each junk. If the chmodDirectory option is set then it will try for each (already existing junk) to change the directory permission and fails.
 
Expected Behaviour:
It should only try to change the permission if the directory does not yet exists

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks for your contribution, but the PR looks broken or targeting an incorrect branch.

**Comment by michael-salzburg** [comment]
I have set: apache:camel-3.x. Should I have set a dedicated e.g. 3.18.2, But which one?

**Review by oscerd — CHANGES_REQUESTED** [review]
You need to apply your fix to a fresh branch from camel-3.x

**Comment by michael-salzburg** [comment]
Wrong pull request

**Pull request closed without merging**
