### PR TITLE
CAMEL-14425: Polling Optimization: Remove for-loops and consider numb…

### PR DESCRIPTION
**Pull request by mash-sap**
CAMEL-14425: Polling Optimization: Remove for-loops and consider number of maximum messages to process earlier during the poll

### CODE REVIEW

**Comment by mash-sap** [comment]
I will need to update the commit. But first need to find out how to do that :)

**Comment by oscerd** [comment]
Ah no, I've seen you opened this PR against 2.24.x. Please open the PR against master, the project structure is different, but since this introduce a substantial change in the behavior we can only accept thay for Camel 3.1.0. So close this one and re-open against master please.

**Comment by oscerd** [comment]
Thanks.

**Comment by mash-sap** [comment]
Closing PR and reopen one for master

**Pull request closed without merging**
