### PR TITLE
CAMEL-19638 : Mockito core version update

### PR DESCRIPTION
**Pull request by mayyanar27**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I don't think is that easy.

**Comment by mayyanar27** [comment]
> I don't think is that easy.

This is WIP will updated the PR once done

**Comment by oscerd** [comment]
This also need a JIRA issue.

**Comment by mayyanar27** [comment]
> This also need a JIRA issue.

We have jira for this
https://issues.apache.org/jira/browse/CAMEL-19638

**Pull request closed without merging**
