### PR TITLE
update infinispan camel 2.x examples

### PR DESCRIPTION
**Pull request by lucamaf**
the previous example were using the camel 3.x constants

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
The original documentation is correct for 2.x

https://github.com/apache/camel/blob/camel-2.x/components/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/InfinispanConstants.java#L29

https://github.com/apache/camel/blob/camel-2.x/components/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/InfinispanConstants.java#L24

https://github.com/apache/camel/blob/camel-2.x/components/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/InfinispanOperation.java#L26

https://github.com/apache/camel/blob/camel-2.x/components/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/InfinispanConstants.java#L32

https://github.com/apache/camel/blob/camel-2.x/components/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/InfinispanConstants.java#L33

Also if you define the header in that way, you need to include them in "".

I don't think the PR is correct, but it might be I'm losing something

**Comment by lucamaf** [comment]
I just tried with documentation in the example and Fuse 7.8 and it was not picking up the value, only when I switched to the above format it worked

**Comment by oscerd** [comment]
I think you need to try with camel-2.x for this documentation or at least the last 2.25.x releases, not Fuse 7.8, it may be different.

**Comment by lucamaf** [comment]
then maybe I just need to add the "" to my pull request but the example wasn't working and Fuse7.8 is based on camel 2.x documentation : https://access.redhat.com/documentation/en-us/red_hat_fuse/7.8/html/apache_camel_component_reference/infinispan-component

**Comment by oscerd** [comment]
For the Fuse documentation, you have to ask to Fuse team. In terms of Camel 2.x, the references are completely coherent.

**Comment by oscerd** [comment]
If you report the example doesn't work with Camel 2.25.x releases, we can review them. For the Fuse side of stuff, you have to ask to Fuse team.

**Comment by davsclaus** [comment]
For 2.x you need to have the documentation similar to what it is using, see its unit test such as here
https://github.com/apache/camel/blob/camel-2.25.x/components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/InfinispanProducerTest.java#L65

**Comment by davsclaus** [comment]
And the branch should be `camel-2.25.x` that is the active 2.x branch upstream

**Comment by oscerd** [comment]
On the website we are pointing 2.x as branch btw

**Comment by davsclaus** [comment]
Okay then we should point to 2.25.x as that is where the active code is

**Comment by oscerd** [comment]
Let me close this.

**Pull request closed without merging**
