### PR TITLE
20008 xml tokenizer expected bodies check

### PR DESCRIPTION
**Pull request by apupier**
based on https://github.com/apache/camel/pull/11754

# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by apupier** [comment]
the job is failing without even really starting the build:

```
Run ./mvnw -l build.log -Dquickly install
  ./mvnw -l build.log -Dquickly install
  shell: /usr/bin/bash -e {0}
  env:
    MVND_OPTS: -V -e -ntp -Dmvnd.threads=[2](https://github.com/apache/camel/actions/runs/6560385887/job/17818487102?pr=11756#step:6:2) -Daether.connector.http.connectionMaxTtl=120 -Daether.connector.requestTimeout=[3](https://github.com/apache/camel/actions/runs/6560385887/job/17818487102?pr=11756#step:6:3)00000 -Daether.dependencyCollector.impl=bf -Dmaven.artifact.threads=25 -Dci.env.name=github.com -Dsurefire.rerunFailingTestsCount=2 -Dfailsafe.rerunFailingTestsCount=2
    JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.8-1/x6[4](https://github.com/apache/camel/actions/runs/6560385887/job/17818487102?pr=11756#step:6:4)
    JAVA_HOME_17_X[6](https://github.com/apache/camel/actions/runs/6560385887/job/17818487102?pr=11756#step:6:6)4: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/1[7](https://github.com/apache/camel/actions/runs/6560385887/job/17818487102?pr=11756#step:6:7).0.[8](https://github.com/apache/camel/actions/runs/6560385887/job/17818487102?pr=11756#step:6:9)-1/x64
Error: Process completed with exit code 1.
```

**Comment by oscerd** [comment]
You cannot see the log, because this is reserved to PMC and committer.

```
[ERROR] /home/runner/work/camel/camel/components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java:[817,71] cannot access org.xmlunit.builder.DifferenceEngineConfigurer
  class file for org.xmlunit.builder.DifferenceEngineConfigurer not found
```

**Comment by apupier** [comment]
ok, Eclipse IDE test runner was friendlier with dependencyManagement declared with test scope than Maven. I updated the branch.

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — CHANGES_REQUESTED** [review]
camel-mock should not have new dependency on some xml library.
this fix should not change camel-mock

**Comment by apupier** [comment]
> camel-mock should not have new dependency on some xml library.

Can you provide an explanation on the reason for it? it would help to find an alternative.

> this fix should not change camel-mock

I do not see an handy solution not modifying camel-mock at all. The comparison in Camel mock is on the exact message content equality but the idea is to compare similar xml content, not string comparison. We will have to introduce something to do this kind of comparison.
The alternative would be to provide another module specific to Mock with xml content but I feel it will feel weird to have different kind of camel-mock components.


Alternative: provide a specific class doing the comparison and provided as a parameter of the method `expectedXXX`. not sure where to host this method. It can be in camel-stax for now as it is the only one used but I imagine that it could be useful for other components too.

**Pull request closed without merging**
