### PR TITLE
camel-support - Add type-safe resolveEndpoint method

### PR DESCRIPTION
**Pull request by tadayosi**
It's too small changes to file a JIRA but I'd like you guys to check if I'm going in the right direction.

### CODE REVIEW

**Comment by tadayosi** [comment]
@davsclaus The doc changing is the exact reason I submitted this. The current doc is out-of-date for 3.2.0. Now `CamelContext` doesn't have `resolveEndpoint` method at all, and I only find it in `CamelContextHelper`. So do you think we should rather recover it in `CamelContext` API?

**Comment by oscerd** [comment]
No need to reintroduce the method.

**Comment by davsclaus** [comment]
Ah okay the doc should be changed to use `getEndpoint`

**Comment by tadayosi** [comment]
Thanks guys. That's the feedback that I expected!  Withdrawing it and I'll only change the doc in a next commit.

**Pull request closed without merging**
