### PR TITLE
CAMEL-8736 - Create new JCache component

### PR DESCRIPTION
**Pull request by lburgazzoli**
This PR is aimed to get some feedback on a new JCache component. 
At the moment the component lacks a proper set of tests, documentation and some more functionalities I will add in the coming days.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Findings fixed

**Comment by lburgazzoli** [comment]
@davsclaus I've added:
- test cases
- idemponent repository
- aggregation repository

Can anyone review  ?

**Comment by lburgazzoli** [comment]
Finding fixed

**Comment by davsclaus** [comment]
Thank merging now.

Can you create a new PR to add the component to apache-camel (so its in the zip) and also work on a feature for karaf, and a tests in tests/camel-itest-karaf.

**Comment by lburgazzoli** [comment]
is it not already in components/pom.xml ?

**Comment by davsclaus** [comment]
yes but it need to be added to parent/pom and apache-camel, and in the common file also.

do a "git grep camel-bam" etc to find where an existing components is already.

**Comment by lburgazzoli** [comment]
ah yep, that thing. I will

**Comment by lburgazzoli** [comment]
Done via https://github.com/apache/camel/pull/851

**Pull request closed without merging**
