### PR TITLE
CAMEL-16278: Migrate Azure dependencies to central Bom management

### PR DESCRIPTION
**Pull request by omarsmak**

### CODE REVIEW

**Review by jbonofre — APPROVED** [review]
LGTM, I will use this BoM in Camel Karaf (working on the full cleanup and packaging).

**Review by oscerd — APPROVED** [review]
Looks good to me, there is a disalignment with eventhubs (Bom is 5.4.0 vs 5.5.0 on Camel side) and datalake (12.4.0 BOM and 12.3.0 on camel side)

We can adjust on the Karaf side eventually or leave them as is.

**Comment by omarsmak** [comment]
> Looks good to me, there is a disalignment with eventhubs (Bom is 5.4.0 vs 5.5.0 on Camel side) and datalake (12.4.0 BOM and 12.3.0 on camel side)
> 
> We can adjust on the Karaf side eventually or leave them as is.

You mean on the Karaf side?

**Comment by oscerd** [comment]
Yes, I'm talking about the Karaf side.

**Comment by omarsmak** [comment]
> Yes, I'm talking about the Karaf side.

aha I see, as @jbonofre mentioned, he will also switch karaf side to use the bom instead :)

**Comment by oscerd** [comment]
yes, but I don't think it will be feasible for 3.9.0, so for this release we'll have this misalignment I guess.

**Comment by omarsmak** [comment]
so shall we this merge now?

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
