### PR TITLE
CAMEL-11574 - Switch lumberjack from Gson to Jackson in order to support long JSon values

### PR DESCRIPTION
**Pull request by adessaigne**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you fix the camel-luberjack osgi feature as well

**Comment by adessaigne** [comment]
Sorry I totally forgot updating it. I'll do that later tonight.

**Comment by adessaigne** [comment]
I've just updated karaf features. Tell me if there's something else to do.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by adessaigne** [comment]
Thanks for merging it.

**Pull request closed without merging**
