### PR TITLE
Document update

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Making the default value clear by abbreviating it

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This needs to be done in the javadoc of the EIP

**Comment by NiteshKoushik** [comment]
Is it possible to share the javadoc link.

**Comment by davsclaus** [comment]
See here
https://github.com/apache/camel/blob/4ea9e6c357371682b855d2d79655b41120331b7a/core/camel-core-engine/src/main/java/org/apache/camel/model/loadbalancer/WeightedLoadBalancerDefinition.java#L82

**Comment by NiteshKoushik** [comment]
Thanks @davsclaus for sharing the javadoc link. But I am not able to edit the page. On edit button, it is stating - you must be on branch to make or propose changes. 
Please let me know how to do the changes.

**Comment by NiteshKoushik** [comment]
Thanks @davsclaus , I have created a PR https://github.com/apache/camel/pull/4328 for the same.

**Pull request closed without merging**
