### PR TITLE
CAMEL-11541: Add "sendLocation", "editMessageLiveLocation" methods support

### PR DESCRIPTION
**Pull request by DenisIstomin**
Changes:
1. Added sendLocation method support
2. Added editMessageLiveLocation method support
3. Added example project

### CODE REVIEW

**Comment by oscerd** [comment]
LGTM, if you have time to split the fixes is good, otherwise we can merge as is

**Comment by DenisIstomin** [comment]
Changes where splitted. Example project: PR #2730.

**Comment by vgvineet4** [comment]
Doc file needs to be updated with the new API support.

**Comment by oscerd** [comment]
@DenisIstomin can you please update the docs? in src/main/docs

**Comment by DenisIstomin** [comment]
Fixed inline_message_id, added few changes to docs.

**Comment by oscerd** [comment]
Thanks, I will merge ASAP.

**Comment by vgvineet4** [comment]
Have you tested the routes to send the location to a telegram channel too. If not will take that separately.

LGTM :)

**Comment by oscerd** [comment]
Merged on master. Thanks!

**Pull request closed without merging**
