### PR TITLE
Consumer missed part fix

### PR DESCRIPTION
**Pull request by hamed-hatami**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by hamed-hatami** [comment]
Is this  the same issue , we saw for doc update too ?

**Comment by hamed-hatami** [comment]
Locally all UT and IT got green

**Comment by hamed-hatami** [comment]
Is there any workaround to merge for the time being ?

**Comment by oscerd** [comment]
I tested the PR locally, so I'm going to merge.

**Comment by orpiske** [comment]
> Same. @orpiske @davsclaus I think we should have a look at incremental test

There is something outdated on GH:


```
ERROR] Failed to execute goal on project camel-allcomponents: Could not resolve dependencies for project org.apache.camel:camel-allcomponents:pom:4.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-jira:jar:4.0.0-SNAPSHOT -> io.atlassian.fugue:fugue:jar:5.0.0: Failed to read artifact descriptor for io.atlassian.fugue:fugue:jar:5.0.0: The following artifacts could not be resolved: io.atlassian.fugue:fugue-parent:pom:5.0.0 (present, but unavailable): io.atlassian.fugue:fugue-parent:pom:5.0.0 was not found in https://repo1.maven.org/maven2/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project camel-allcomponents: Could not resolve dependencies for project org.apache.camel:camel-allcomponents:pom:4.0.0-SNAPSHOT: Failed to collect dependencies at org.apache.camel:camel-jira:jar:4.0.0-SNAPSHOT -> io.atlassian.fugue:fugue:jar:5.0.0

```

**Comment by davsclaus** [comment]
camel-allcomponents has been added the repo 30 min ago or so

**Pull request merged**
