### PR TITLE
CAMEL-11616: Upgraded Apache Curator version to 4.0.0

### PR DESCRIPTION
**Pull request by vrlgohel**
Upgraded Apache Curator version to 4.0.0, https://issues.apache.org/jira/browse/CAMEL-11616

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks, did you by any chance test if it can install and run on OSGi on Karaf ?

Sometimes with big updates then something dont work in OSGi so I am just saying we should give this some test there also.

**Comment by oscerd** [comment]
Even by aligning everything to make it works in OSGi, Curator 4.x still needs Zookeeper 3.5.x to work in OSGi.

{code}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.546 sec <<< FAILURE! - in org.apache.camel.itest.karaf.CamelZookeeperTest
test(org.apache.camel.itest.karaf.CamelZookeeperTest)  Time elapsed: 7.421 sec  <<< ERROR!
org.ops4j.pax.exam.WrappedTestContainerException: [test(org.apache.camel.itest.karaf.CamelZookeeperTest): Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-zookeeper; type=karaf.feature; version="[2.20.0.SNAPSHOT,2.20.0.SNAPSHOT]"; filter:="(&(osgi.identity=camel-zookeeper)(type=karaf.feature)(version>=2.20.0.SNAPSHOT)(version<=2.20.0.SNAPSHOT))" [caused by: Unable to resolve camel-zookeeper/2.20.0.SNAPSHOT: missing requirement [camel-zookeeper/2.20.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-zookeeper; type=osgi.bundle; version="[2.20.0.SNAPSHOT,2.20.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-zookeeper/2.20.0.SNAPSHOT: missing requirement [org.apache.camel.camel-zookeeper/2.20.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.curator.framework.listen)(version>=4.0.0)(!(version>=5.0.0)))" [caused by: Unable to resolve curator-framework/4.0.0: missing requirement [curator-framework/4.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.curator)(version>=4.0.0)(!(version>=5.0.0)))" [caused by: Unable to resolve curator-client/4.0.0: missing requirement [curator-client/4.0.0] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.zookeeper)(version>=3.5.0)(!(version>=4.0.0)))"]]]]]
	at org.apache.felix.resolver.ResolutionError.toException(ResolutionError.java:42)
	at org.apache.felix.resolver.ResolverImpl.doResolve(ResolverImpl.java:389)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:375)
	at org.apache.felix.resolver.ResolverImpl.resolve(ResolverImpl.java:347)
	at org.apache.karaf.features.internal.region.SubsystemResolver.resolve(SubsystemResolver.java:218)
	at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:285)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1170)
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$0(FeaturesServiceImpl.java:1069)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
{code}

Curator 4.x needs jackson 2.7.x at least and Guava 20.0. In this test I added them but still, we need to update Zookeeper to 3.5.x

**Comment by oscerd** [comment]
For the moment we cannot accept this PR.

**Comment by vrlgohel** [comment]
H Andrea, 
That means we need to upgrade the zookeeper version to 3.5 for this to make it work right?

**Comment by oscerd** [comment]
Yes, but it's not released yet and also Zookeeper is a bit sensitive to touch.

**Comment by vrlgohel** [comment]
Zookeeper version 3.5.3 Beta is available here, https://blog.cloudera.com/blog/2017/05/apache-zookeeper-3-5-3-beta-has-been-released/. 
But since Curator 4.0 has a hard dependency on Zk 3.5.x and the GA version of Zk is not released yet, maybe atm, we can close this PR and i will reopen this same PR or open a new one for this issue.

**Pull request closed without merging**
