### PR TITLE
Factorize Json schema loading code

### PR DESCRIPTION
**Pull request by apupier**
please note that test provided for the catalog are failing for me locally (even before the modification)

### CODE REVIEW

**Comment by zregvart** [comment]
The tests are OK for me, perhaps we should mark them as integration tests:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.camel.catalog.maven.MavenArtifactProviderTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 18.698 sec - in org.apache.camel.catalog.maven.MavenArtifactProviderTest
Running org.apache.camel.catalog.maven.MavenVersionManagerTest
2.18.1 has 205 components
2.19.0-SNAPSHOT has 221 components
2.18.1 has 205 components
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 106.715 sec - in org.apache.camel.catalog.maven.MavenVersionManagerTest

Results :

Tests run: 8, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by davsclaus** [comment]
Also mind about checkstyle error, eg run

     mvn compile -P sourcecheck

in that directory and fix what it reports as errors

**Comment by apupier** [comment]
> The tests are OK for me, perhaps we should mark them as integration tests:

I created https://issues.apache.org/jira/browse/CAMEL-11176
A part of them are just misconfiguration, maybe another part would be better as integration (for the several camel catalog version test)

**Comment by davsclaus** [comment]
i just fixed and merged this

**Pull request closed without merging**
