### PR TITLE
CAMEL-11891 - incase of empty body unmarshalling needed

### PR DESCRIPTION
**Pull request by onders86**

### CODE REVIEW

**Comment by richardgroote** [comment]
The proposed solution i have mentioned in the issue will fail in case of a stream cache. 
When a GET call is made through a servlet and the body is empty than the solution will return null, later on the HttpMessage tries to read the request.getInputStream for the second time and than a stream closed exception is thrown. 
The correct solution is to return the original stream cache

if (inBody instanceof StreamCache) {
        long length = ((StreamCache) inBody).length();
        if (length <= 0) {
            return inBody;
        }
}

**Comment by onders86** [comment]
integration testing in such a scenario similar to your case is not trivial to me who is trying to reproduce. i will try, anyway. 
However, in your code snippet in the issue does not reflect your current comment. Let's see if i can recreate.. Thanks.

**Comment by richardgroote** [comment]
The stream closed is already closed problem could only be reproduced on our server deployment (our local deployment, eclipse rcp with jetty had no problem). The server deployment is a jboss EAP 6.4.17.

The problem in our case was that a GET request was made to the servlet component. This GET request is read and added to the StreamCache. Later on the HttpMessage#createBody is called and the request was read for the second time.

**Comment by onders86** [comment]
Could you please review and possibly test besides UTs?

**Comment by richardgroote** [comment]
This works fine in our use cases

**Comment by oscerd** [comment]
@onders86 can you push your commit?

**Pull request merged**
