### PR TITLE
CAMEL-10696 - Allow Kafka to resume from any offset

### PR DESCRIPTION
**Pull request by adessaigne**
I created a new `StateRepository` _standard_ API in order to hold its state (the offset of each partition). This state looks like a `Map` whereas the `IdempotentRepository` behaves like a `Set` (that's why a created a new API).
Moreover this API can be later on reuse for other purpose like keeping the last index of database reads.

### CODE REVIEW

**Comment by davsclaus** [comment]
Can toy provide some documentation about this in the kafka-component.adoc file

**Comment by adessaigne** [comment]
Sure. I'll do that tonight.

**Comment by adessaigne** [comment]
So I've added a sample usage in the `kafka-component.adoc` file. Should I describe this on Confluence too ?

Side note : do you have a page somewhere explaining the best practices for writing the asciidoc documentation ? Like how you should write header, how many headers level there are, ... A doc that helps being consistent across all documentation ?

**Comment by davsclaus** [comment]
Yeah we are switching to use header styles using `##` style instead of that insane marksdown with all those weird underlines. So its `##` for top level, and then `###` and `####` for sub levels.

**Comment by davsclaus** [comment]
Can you update the docs a bit more with how to setup that file state repository as its a bit sparse with just a reference to `#myRepo`.

**Comment by adessaigne** [comment]
You're right, my documentation was a _bit_ light... So I've just improved it, the usage is quite simple.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by adessaigne** [comment]
It will be available in the 2.19 release, right ?

**Comment by davsclaus** [comment]
yes

**Comment by adessaigne** [comment]
Thanks a lot for merging it !

**Pull request closed without merging**
