### PR TITLE
CAMEL-10798 Splitted hazelcast component into 11 which correspond to …

### PR DESCRIPTION
**Pull request by igarashitm**
…each of endpoints

For post 2.19 release

### CODE REVIEW

**Comment by igarashitm** [comment]
Oops, I'll also update the camel-example-hazelcast-kubernates here soon

**Comment by igarashitm** [comment]
OK, good to go

**Comment by davsclaus** [comment]
Thanks we should wait till 2.19.0 is released so the master branch is "free" for such big changes

**Comment by igarashitm** [comment]
No problem, I can rebase it again once master get ready for 2.20 :)

**Comment by davsclaus** [comment]
@igarashitm do you mind rebase against master just in case something changed broke something, so we can get this merged?

**Comment by igarashitm** [comment]
Thanks for reminding me, done!

**Comment by oscerd** [comment]
Ready to merge IMO

**Comment by davsclaus** [comment]
lgtm

**Comment by oscerd** [comment]
I'm going to merge.

**Comment by oscerd** [comment]
@igarashitm thanks the PR has been merged, can you close this?

**Comment by igarashitm** [comment]
Thanks! closing

**Pull request closed without merging**
