### PR TITLE
CAMEL-15490 Specify source 8 for maven-javadoc-plugin

### PR DESCRIPTION
**Pull request by cunningt**
[ x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[x ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[x ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by cunningt** [comment]
https://issues.apache.org/jira/browse/CAMEL-15490

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Merged this into mater branch

**Comment by oscerd** [comment]
I guess we need to merge this one on 3.5.x too

**Comment by oscerd** [comment]
@davsclaus

**Comment by davsclaus** [comment]
Yeah that is fine to do

**Comment by oscerd** [comment]
Maybe only if someone want to build the 3.5.x from source or release it

**Comment by cunningt** [comment]
Please merge into 3.5.x also if possible, I'd like to build from source

**Pull request merged**
