### PR TITLE
Update pom.xml

### PR DESCRIPTION
**Pull request by btrice**
maven jetty run command

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks for the PR.

**Comment by davsclaus** [comment]
@oscerd its a good idea to use the "rebase and merge" button. Next to the green button, there is a little arrow where you can switch to "rebase and merge" then we get a nice clean git tree.

**Comment by oscerd** [comment]
@davsclaus yes, sure. Usually I merge locally on my branch and then rebase, but for the little PRs like this I avoid this. By the way I'll do as you describe for the next PRs.

**Comment by davsclaus** [comment]
yeah i would do the same for these small commits too by pressing the green button.

**Pull request merged**
