### PR TITLE
Cleanup dependency management

### PR DESCRIPTION
**Pull request by gnodet**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by davsclaus** [comment]
This may have caused camel-jbang-core to not compile

[ERROR] /Users/davsclaus/workspace/camel/dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/RunHelper.java:[47,47] cannot access org.codehaus.plexus.util.xml.pull.XmlPullParserException
[ERROR]   class file for org.codehaus.plexus.util.xml.pull.XmlPullParserException not found

**Comment by davsclaus** [comment]
okay it seems it causes more problems - we should consider reverting this.
tests in camel-jbang-core is failing, and the jbang is not working correctly.

I am trying again tomorrow to be sure, as I want to do a full rebuild with and without this commit

**Comment by gnodet** [comment]
> okay it seems it causes more problems - we should consider reverting this. tests in camel-jbang-core is failing, and the jbang is not working correctly.
> 
> I am trying again tomorrow to be sure, as I want to do a full rebuild with and without this commit

That could definitely be the cause.  I did a full successful rebuild, but without running tests...

**Comment by davsclaus** [comment]
Okay I did 2 full rebuilds this morning

- main (as is) = fails
- reverted = ok

I am going to revert this, and @gnodet maybe you can find out the problem or maybe do less of a cleanup to narrow down where it starts to fail

**Pull request merged**
