### PR TITLE
(chores) camel-kafka: Avoid misreporting liveness checks

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@davsclaus FYI, this is the strange behavior I mentioned on the Zulip Chat. It seems that invoking `HealthCheckHelper.invokeLiveness(context);` returns an empty result. Maybe we are doing something wrong on the test?

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Yeah we should revisit the health checks, as 98% should be readiness only (connectivity problems etc).

Liveness is harder to write as health check as its when you run low on memory, file descriptors, or some other weird errors, where the container needs to be restarted.

So we should likely make liveness = false by default. And then if possible write a basic liveness check to have it report as UP by default.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
I created a ticket about liveness = false by default for health checks
https://issues.apache.org/jira/browse/CAMEL-19118

**Review by davsclaus — APPROVED** [review]

**Comment by orpiske** [comment]
> I created a ticket about liveness = false by default for health checks https://issues.apache.org/jira/browse/CAMEL-19118

Oh, cool! Thanks @davsclaus

**Pull request merged**
