### PR TITLE
Add raw support for Splunk producer to input data 

### PR DESCRIPTION
**Pull request by pax95**
Splunk comes with build in support for tokenising data eg. json, xml, logs and what not.
With the new raw option set to true, the producer will insert the data raw into Splunk.

### CODE REVIEW

**Comment by oscerd** [comment]
Hi Preben, many thanks for the PR, it has been merged :-)

Do you mind closing this? 

Do you want to update the docs for the component http://camel.apache.org/splunk.html ?

Andrea

**Comment by pax95** [comment]
Thanks Andrea.

I'll do the docs asap

**Comment by pax95** [comment]
Should I create a JIRA too ?
I presumed that happened automatic upon PR

**Comment by oscerd** [comment]
Usually the JIRA has to be opened before the PR is submitted, then a
comment is posted by asfgit when a PR with a reference to that ticket is
opened on github platform.

However there is no problem :-)

Many thanks for your contributions :-)
Il 25/lug/2015 17:23, "Preben Asmussen" <notifications@github.com> ha
scritto:

**Pull request closed without merging**
