### PR TITLE
Update loadBalance-eip.adoc

### PR DESCRIPTION
**Pull request by fg78nc**
Correct Integer type declaration

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Thanks

**Comment by fg78nc** [comment]
Actually, I just tested and seems like API has changed weighted accepts a String and optional delimiter.
Do you want me to update the docs?

**Comment by oscerd** [comment]
Yeah, go ahead please

**Comment by fg78nc** [comment]
Done, please review.
I also noticed the weighted algorithm is not working exactly as expected -
the first batch is not distributed as per request.
Would you like me to create examples and push to Camel Spring Boot examples?

**Comment by oscerd** [comment]
If you time and will, sure. An example would be good.

**Comment by fg78nc** [comment]
Ok, I will work on it.
Can you merge my previous PR with a Type Converter example
https://github.com/apache/camel-spring-boot-examples/pull/18 ?

**Pull request merged**
