### PR TITLE
[CAMEL-10361] Expose cassandra-unit version through BOM

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by davsclaus** [comment]
@nicolaferraro wonder if this impacts the Spring Boot BOM generator. I remember something about camel-cassandra not working on SB.

**Comment by nicolaferraro** [comment]
@davsclaus dependencies under `com.datastax*` are not exported in the spring-boot BOM, because spring-boot provides its own versions, so the generator is not affected. There are no conflicts for `org.cassandraunit`, it will be added after a build of spring-boot-dm.

**Comment by davsclaus** [comment]
Thanks @oscerd this can be merged.

**Comment by oscerd** [comment]
Sure :-)

**Comment by oscerd** [comment]
Merged! Thanks @tdiesler :-)

**Pull request merged**
