### PR TITLE
CAMEL-15057: camel-telegram - Move the initialization codes in Telegr…

### PR DESCRIPTION
**Pull request by zhfeng**
…amEndpoint from doStart() to doInit()

https://issues.apache.org/jira/browse/CAMEL-15057

### CODE REVIEW

**Comment by davsclaus** [comment]
Oh a problem with this is that in doInit you end up creating http client that are creating thread pools and whatnot is doing too early. Init phase is also used for native mode in graal/quarkus to do build time optimizations (cc @gnodet) which means it would do on the image built time and not at runtime.

We should discuss this more or find another solution

**Comment by davsclaus** [comment]
@zhfeng can you try and test this PR instead
https://github.com/apache/camel/pull/3824

**Comment by zhfeng** [comment]
yeah, I will try it

**Comment by zhfeng** [comment]
@davsclaus the PR looks good to me. I have test it with the camel-main and works.

**Comment by zhfeng** [comment]
https://github.com/apache/camel/pull/3824 should be better solution. So I close this PR.

**Pull request closed without merging**
