### PR TITLE
CAMEL-20382: camel-kafka - RecordMetadata header naming convention

### PR DESCRIPTION
**Pull request by jono-morris**
# Description

Update the `KAFKA_RECORDMETA` header name for the `List<RecordMetadata>` metadata from `org.apache.kafka.clients.producer.RecordMetadata` to `kafka.RECORDMETA`

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Can we name the header `Kafka.RECORD_METADATA`

**Comment by jono-morris** [comment]
Yes of course.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
