### PR TITLE
[CAMEL-19709] yaml dsl: include additional information such as description and title in the jscon schema

### PR DESCRIPTION
**Pull request by lburgazzoli**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
@lburgazzoli you have some commits in this PR from seda and others that are not related. Maybe you can rebase and update this PR.

**Comment by lburgazzoli** [comment]
oh damn, I thought I had removed them, will rebase tomorrow

**Comment by lburgazzoli** [comment]
@davsclaus done

**Comment by davsclaus** [comment]
Should 

    "deprecated" : "false",

Not be a json boolean type (according to spec) ???

    "deprecated" : false,

**Comment by davsclaus** [comment]
The order of type, description, title, etc seems to not be strict/consistent. I wonder if we can make it the same order everywhere. Sometimes description is before title, and other times its after etc.

This file will be regen more often when we fix typo, add new option, change a default etc. So it would be good to ensure the generator is 100% on all OS (not like. that XML XSD that is a bit of a pain)

**Comment by lburgazzoli** [comment]
@davsclaus let me have a look

**Comment by lburgazzoli** [comment]
> Should
> 
> ```
> "deprecated" : "false",
> ```
> 
> Not be a json boolean type (according to spec) ???
> 
> ```
> "deprecated" : false,
> ```

done

**Comment by lburgazzoli** [comment]
> The order of type, description, title, etc seems to not be strict/consistent. I wonder if we can make it the same order everywhere. Sometimes description is before title, and other times its after etc.

I have changed the json schema generation to be consistent, at least with what Jackson's ObjectMapper allows to configure. Let me know if you spot any  inconsistency

**Comment by davsclaus** [comment]
Hmm jackson still dumps it in different order. They should use a linked map so the values are in the order they are added.

**Comment by davsclaus** [comment]
Our own library `camel-util-json` has a basic JsonObject / JsonArray which is consistent. And `JSooner` has prettyPrint methods to dump

**Review by davsclaus — APPROVED** [review]

**Comment by lburgazzoli** [comment]
> Hmm jackson still dumps it in different order. They should use a linked map so the values are in the order they are added.

can you give me an example ?

**Comment by davsclaus** [comment]
https://github.com/apache/camel/blob/3907d9991010aa7cbda1a8bb1f647911458a6cac/core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/BacklogTracer.java#L350

**Comment by davsclaus** [comment]
All the dev consoles uses it as well, see core/camel-console 

And mind that if you have some text then you can use the escape method to make it json safe (but you very likely do not need that, we use it to dump source code in json etc.)

**Comment by davsclaus** [comment]
Its likely a bunch of work to change so maybe create a JIRA ticket and put it as v4.1.

**Comment by lburgazzoli** [comment]
I mean, an example of a unordered property :)

But I think I got it so basically there were a discrepancy in the order the properties were set for types and related properties but Jackson did serialize them according to the insertion order. It should be fixed now. 

I'll try to use camel-util-json later as it would mean changing a number of things now :)

**Comment by lburgazzoli** [comment]
> Its likely a bunch of work to change so maybe create a JIRA ticket and put it as v4.1.

https://issues.apache.org/jira/browse/CAMEL-19717

**Comment by lburgazzoli** [comment]
ok, I think now the PR is now ready.

I did some investigation for https://issues.apache.org/jira/browse/CAMEL-19717 but I found that there is an issue with escaping https://issues.apache.org/jira/browse/CAMEL-19718 which seems not super easy to fix if we want to preserve the option to escapes forward slashes.

I will digg into that a little bit more in the coming days

**Comment by davsclaus** [comment]
LGTM

@lburgazzoli we need to merge this today so it has time to get into 4.0 GA

**Pull request merged**
