### PR TITLE
CAMEL-10697 - Workaround KAFKA-1894 by calling the wakeup method

### PR DESCRIPTION
**Pull request by adessaigne**

### CODE REVIEW

**Comment by adessaigne** [comment]
Do you know why the bot didn't saw this pull request ? Did I forgot do to something ?

**Comment by davsclaus** [comment]
Yeah ASF has some trouble.

Can you post the git merge command here as a comment?

**Comment by adessaigne** [comment]
Here is my best bot imitation : https://issues.apache.org/jira/browse/CAMEL-10697?focusedCommentId=15820601&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15820601

**Comment by oscerd** [comment]
Best BOT imitation ever :-)

**Comment by davsclaus** [comment]
Thanks merged to master and 2.18.x. Can you close this

**Comment by adessaigne** [comment]
Thanks for merging it ! GitHub is telling me that there are conflicted files, should I worry about that ?

**Pull request closed without merging**
