### PR TITLE
Means to specify the name of the attached file via header Content-Disposition

### PR DESCRIPTION
**Pull request by dk2k**
Some AS2 software processes headers like Content-Disposition: attachment; filename=sample.txt and allows to process this filename.

All the changes are HTTP compliant. New parameter attachedFileName is optional.

Tested against publicly accessible infrastructure of Mendelson Software. They have a site to check the properties of the sent AS2 message - headers, payload, errors, if present. The site: https://testas2.mendelson-e-c.com:8444/webas2/ login guest password guest

Added/updated several unit-tests as well - positive and negative.

Backward compatibility is preserved, I believe. If you don't specify the property attachedFileName, then no header is sent.

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by dk2k** [comment]
Severe conflict and build failure in the module, which I haven't changed. Will open another request and link it to this one.

**Comment by hiteshkaushik28** [comment]
@dk2k greetings!!

I am using camel-as2 in one of my projects. The problem I am facing is with file attachments.
This is how I am attaching a file to my exchange:
```
@Override
public void process(Exchange exchange) throws Exception {
    // other code
    
    
    String fileName = "FFE1235A_PPF070_PPF07000000000000000000000.xml";
    File file = new File(fileName);
    if (!file.exists()) {
        throw new IllegalArgumentException("File not found: " + file.getAbsolutePath());
    }
    InputStream inputStream = new FileInputStream(file);
    exchange.getIn().setBody(inputStream, InputStream.class);
    
    exchange.getIn().setHeader("CamelAs2.attachedFileName","FFE1235A_PPF070_PPF07000000000000000000000.xml");
    // remaining code
}
```

The issue is that while trying to debug the flow, I am not able to see the `Content-Disposition: attachment; filename=<name>` header at receiving end. I have tried looking both at the outer request headers as well as the ApplicationEntity's (EDIFACTEntity in my case) headers.
Even the mendelson server doesn't log this header.

I am sure I am doing something utterly wrong and silly. Any help is appreciated.

**Comment by dk2k** [comment]
@hiteshkaushik28 good day! please take a look at https://github.com/dk2k/camel-as2-usage/blob/main/src/main/java/ru/outofrange/as2/route/AS2ServerRouteBuilder.java and at the entire repository with this class

**Comment by hiteshkaushik28** [comment]
@dk2k thanks for replying. I have been following your project to build my as2 service. Upon debugging, I discovered that the header `Content-Disposition: attachment; filename=<name>` is only sent if the request is signed/signed_encrypted/encrypted. Why are we not creating a multipart entity in case of AS2MessageStructure.PLAIN requests?

**Comment by dk2k** [comment]
@hiteshkaushik28 thanks for reporting this behaviour. I will recheck. Maybe it's worth creating a bug ticket.

**Comment by dk2k** [comment]
My understanding is: multipart message for AS2MessageStructure.PLAIN type is an overkill, it slows down processing on the server side. Some embedded systems do not support multipart.
@orpiske can you please comment?

**Comment by orpiske** [comment]
> My understanding is: multipart message for AS2MessageStructure.PLAIN type is an overkill, it slows down processing on the server side. Some embedded systems do not support multipart. @orpiske can you please comment?

I agree that it could be overkill. We could implement something around this, though.

However I'd like to understand a bit more about why exactly that would be necessary? So, my .2 cents: 

1. Raise this on our community at https://camel.zulipchat.com (on the camel channel)
2. And, depending on the consensus, open a ticket (if none exists already).

**Comment by dk2k** [comment]
@orpiske I created a topic https://camel.zulipchat.com/#narrow/channel/257298-camel/topic/.5BAS2.5D.20Is.20it.20possible.20to.20send.20header.20with.20filename.20for.20PLAIN.3F

**Pull request closed without merging**
