### PR TITLE
(chores) camel-test-infra-elasticsearch: update ElasticSearch container to the latest version

### PR DESCRIPTION
**Pull request by orpiske**
Updates the container to 8.11.1

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
LGTM, but I think SB will update to 8.11.x only with 3.2.x

**Comment by orpiske** [comment]
> LGTM, but I think SB will update to 8.11.x only with 3.2.x

Should we wait on this one, them? We are already at the latest 8.10 ... so, not much harm IMHO.

**Comment by orpiske** [comment]
Marking as draft to avoid merging this by mistake.

**Comment by oscerd** [comment]
SB 3.2.0 is still using 8.10.4, but I think it's fine to move on.

**Comment by orpiske** [comment]
Alright. Let's try and see how it goes ... worst case scenario, we rollback. Thanks @oscerd

**Pull request merged**
