### PR TITLE
Upgrade Json Schema Validator to version 1.0.85

### PR DESCRIPTION
**Pull request by oscerd**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by oscerd** [comment]
@ppalaga I'll wait for your PR to be merged and then I'll rebase here.

**Comment by ppalaga** [comment]
Thanks for waiting @oscerd, https://github.com/apache/camel/pull/10586 is now merged

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
