### PR TITLE
Upgrade of Cassandra Java Driver to 4.10.0

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Upgrade of cassandra driver to 4.10.0, to be aligned with cassandra-quarkus 1.0.0 (https://github.com/datastax/cassandra-quarkus), which allow camel-quarkus extension for cassandra (https://github.com/apache/camel-quarkus/issues/1355) to be finished.

- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
It should work fine, but please check the karaf feature... @davsclaus i guess this should be merged for 3.8.0, but we need to double check karaf

**Comment by davsclaus** [comment]
yeah lets get this merged, karaf can always stay on older version if there is a problem

**Comment by JiriOndrusek** [comment]
@davsclaus @oscerd 
I've just tried to install cassandra feature onto clean karaf 4.2.10 and there is an error...

**Comment by davsclaus** [comment]
Yeah I am fixing the karaf upgrade

**Comment by davsclaus** [comment]
karaf has been fixed

**Comment by JiriOndrusek** [comment]
@davsclaus thanks

**Pull request merged**
