### PR TITLE
CAMEL-14043 - AWS-S3: Add proxyProtocol as endpoint configuration option

### PR DESCRIPTION
**Pull request by marius-cornescu**
CAMEL-14043 - AWS-S3: Add proxyProtocol as endpoint configuration option

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please rebase?

**Comment by marius-cornescu** [comment]
Reverted the hdfs change that was added by mistake.

**Comment by davsclaus** [comment]
Thanks did you spot that we miss this in some of the other aws components? If so you are surely welcome to add PRs for those too.

And btw it may be nice to add label="proxy" to those proxy related options

**Comment by oscerd** [comment]
I think this could be done on all the AWS component. I can do that this week.

**Comment by oscerd** [comment]
I'll merge this and add the same approach in the other components.

**Comment by oscerd** [comment]
Merged on master. Thanks.

**Pull request closed without merging**
