### PR TITLE
CAMEL-20722 increased timeout due to failure on ppc64le

### PR DESCRIPTION
**Pull request by jvsingh**
# Description

- These two KafkaBreakOnFirstError* tests had timeout errors on ppc64le in last two builds after being enabled there. 
- Increasing timeouts. 
- If this doesn't work, cannot increase timeouts indefinitely, so suggest we keep them disabled permanently on ppc64le, as root cause might be unrelated infrastructure limitations
- Most concurrency issues are resolved as we consistently get clean runs on amd64 arch

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue CAMEL-20722](https://issues.apache.org/jira/browse/CAMEL-20722) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
LGTM, but I need to test this one manually.

**Comment by orpiske** [comment]
Just for the record. This hasn't been tested yet due to a misconfiguration on my CI. The build did not trigger automatically and I had to trigger it manually today, so I am currently waiting for ppc64le result. It should be done in about 3 hours.

**Comment by orpiske** [comment]
Obs.: x86 look great, though.

**Review by davsclaus — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
Looking good on ppc64le. Let's merge. 

Thanks @jvsingh !

**Pull request merged**
