### PR TITLE
CAMEL-13826: Initial version of a camel-test module with JUnit 5

### PR DESCRIPTION
**Pull request by aldettinger**
Please find a minimal port of camel-test to JUnit 5 for early review, more context in https://issues.apache.org/jira/browse/CAMEL-13826. Changes of interest are mostly located in CamelTestSupport.

As next steps, I would:
+ Remove TestSupport and replace with some kind of CamelAssertions classes
+ Move route coverage to a dedicated class
+ Merely remove deprecated registry stuff from CamelTestSupport (as this class is not used by anyone yet)
+ Investigate whether JUnit 5 "per-class" test instance lifecycle could replace CamelTestSupport.isCreateCamelContextPerClass
+ Move to other class some methods that are candidate for being static imported like CamelTestSupport.assert*/send*/getMock*
+ Port tests of few components to JUnit 5 (the occasion to add a small migration kind in camel-test-junit5.adoc)
+ Add the possibility for camel-test and camel-test-junit5 tests to coexist (so users could migrate camel test per camel test)

### CODE REVIEW

**Comment by oscerd** [comment]
LGTM, lets wait for other feedback

**Comment by oscerd** [comment]
@aldettinger can you add the module where it is needed?

**Comment by aldettinger** [comment]
@oscerd There is indeed issue when I run mvn clean install -P fastinstall.
I'm looking at that.

**Comment by aldettinger** [comment]
@oscerd A final look to the third commit would be very much appreciated. If ok, I will then squash and rebase on top of master.

**Comment by aldettinger** [comment]
Logically, it's good but I'll double check after squash.
Thanks all.

**Pull request closed without merging**
