### PR TITLE
CAMEL 10776

### PR DESCRIPTION
**Pull request by chris-jh**
Optimisations, Check if there are no arguments/parameters then just return the doInvoke.

### CODE REVIEW

**Comment by davsclaus** [comment]
This PR causes unit test errors in camel-spring

**Comment by chris-jh** [comment]
Which ones? i ran the Unit tests in Camel-Spring all passed (1 skipped)?

Results :

Tests run: 1115, Failures: 0, Errors: 0, Skipped: 1

**Comment by chris-jh** [comment]
Hi


Which ones? I ran the Unit tests in Camel-Spring all passed (1 skipped)?

Results :

Tests run: 1115, Failures: 0, Errors: 0, Skipped: 1



I also ran the Unit tests on the Camel-Core all passed (4 skipped).


Regards


Chris

**Comment by davsclaus** [comment]
I am redoing the test again to double check

**Comment by davsclaus** [comment]
Its a bit weird I get these failures
```
Tests in error:
org.apache.camel.spring.remoting.SpringRemotingTwoCamelContextTest.testProxyWithTwoCamelContext(org.apache.camel.spring.remoting.SpringRemotingTwoCamelContextTest)
  Run 1: SpringRemotingTwoCamelContextTest.testProxyWithTwoCamelContext:34 » IllegalState
  Run 2: SpringRemotingTwoCamelContextTest.testProxyWithTwoCamelContext:34 » IllegalState
  Run 3: SpringRemotingTwoCamelContextTest.testProxyWithTwoCamelContext:34 » IllegalState

org.apache.camel.spring.remoting.SpringRemotingWithExportAndProxyTest.testBeanRoutes(org.apache.camel.spring.remoting.SpringRemotingWithExportAndProxyTest)
  Run 1: SpringRemotingWithExportAndProxyTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState
  Run 2: SpringRemotingWithExportAndProxyTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState
  Run 3: SpringRemotingWithExportAndProxyTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState

org.apache.camel.spring.remoting.SpringRemotingWithServiceExportAndNamespacesRouteTest.testBeanRoutes(org.apache.camel.spring.remoting.SpringRemotingWithServiceExportAndNamespacesRouteTest)
  Run 1: SpringRemotingWithServiceExportAndNamespacesRouteTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState
  Run 2: SpringRemotingWithServiceExportAndNamespacesRouteTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState
  Run 3: SpringRemotingWithServiceExportAndNamespacesRouteTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState

org.apache.camel.spring.remoting.SpringRemotingWithServiceExportRouteTest.testBeanRoutes(org.apache.camel.spring.remoting.SpringRemotingWithServiceExportRouteTest)
  Run 1: SpringRemotingWithServiceExportRouteTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState
  Run 2: SpringRemotingWithServiceExportRouteTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState
  Run 3: SpringRemotingWithServiceExportRouteTest>SpringRemotingRouteTest.testBeanRoutes:37 » IllegalState


Tests run: 1115, Failures: 0, Errors: 4, Skipped: 1
```

**Comment by chris-jh** [comment]
Looks like something not compiled correctly at my end (camel-core, maybe when i
did the merge to master). I get the same error now.

You do need to still do Bean invocation and set body.

Ok I'll remove the push. You can close the issue/improvement.

Regards

Chris

**Pull request closed without merging**
