### PR TITLE
CAMEL-15535 Camel Barcode : Add additional headers to the exchange su…

### PR DESCRIPTION
**Pull request by chandra-h-bitd**
…ch as orientation

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by bedlaj** [comment]
Thanks. I think this should be mentioned in documentation, so people can actually find that feature. Do you mind mention that in docs? Also small unit test would be great.

**Comment by chandra-h-bitd** [comment]
@bedlaj , Thanks for your suggestion, I'll update the doc and write a unit test

**Comment by chandra-h-bitd** [comment]
Raised new PR with unit test and updated doc --> https://github.com/apache/camel/pull/4253

**Comment by oscerd** [comment]
You can close this, it has been merged

**Comment by chandra-h-bitd** [comment]
Sure @oscerd

**Pull request closed without merging**
