### PR TITLE
CAMEL-14303: Handle duplicate matchOnUriPrefix on api docs jetty.

### PR DESCRIPTION
**Pull request by bobpaulin**

### CODE REVIEW

**Comment by oscerd** [comment]
@bobpaulin for the servlet PR, can you please raise the same for Camel-3.0.x?

**Comment by bobpaulin** [comment]
Yes i can.  Would it be easier to batch all these updates together for 3.0.x?

**Comment by oscerd** [comment]
Yes, I believe I already backported the first PR with the helper, so from servlet ahead.

**Comment by oscerd** [comment]
Merged on master. Thanks.

**Pull request closed without merging**
