### PR TITLE
CAMEL-19150: camel-olingo4 - Fix missing olingo4 endpoint property names

### PR DESCRIPTION
**Pull request by zhfeng**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
is there a similar problem with olingo2 ?

**Comment by zhfeng** [comment]
@davsclaus yeah, it looks like a similar issue with olingo2
https://github.com/apache/camel/blob/b2f6af4a695439d51ace77331f79157547f6cfd8/components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Endpoint.java#L167-L173

I will raise a other JIRA issue to fix with `camel-olingo2`.

**Comment by zhfeng** [comment]
Do we need to backport the fix to `camel-3.x`?

**Comment by davsclaus** [comment]
yes backport please

**Pull request merged**
