### PR TITLE
CAMEL-10002: migrate to netty 4.1.1.Final

### PR DESCRIPTION
**Pull request by anoordover**
CAMEL-10002: camel-netty4 - Upgrade to Netty 4.1.0.Final

### CODE REVIEW

**Comment by oscerd** [comment]
Have you verified that all the components that are using netty4 in their Karaf feature definition continues to work?

**Comment by anoordover** [comment]
No. I didn't do that. I didn't know about this dependency. Can you describe
how i can check thuis?
Op 8 jun. 2016 1:57 p.m. schreef "Andrea Cosentino" <
notifications@github.com>:

**Comment by oscerd** [comment]
Sure :-) With pleasure :-)

In Karaf we have the concept of feature.

You can see here the Karaf features we have for all the different Camel components.

https://github.com/apache/camel/blob/master/platforms/karaf/features/src/main/resources/features.xml

If you look at the camel-netty4 feature, you'll see it is still using ${netty-version} as version, so you'll need to use netty41-version property there, or maybe change netty-version with the 4.1.1.Final latest version of Netty.

When you have done this change you can install the new Karaf features in platform/karaf/features with mvn clean install.

After that you can run the itest for Karaf.

The folder for this is tests/camel-itest-karaf/.

Here you can run the single test with mvn clean install -Dtest=CamelNetty4Test and verify everything is fine.

As you can see in 

https://github.com/apache/camel/blob/master/platforms/karaf/features/src/main/resources/features.xml

There are features that are using camel-netty4 feature in their dependencies (because they are using the netty4 component as dependency), so you'll need to test them too in the same way: in tests/camel-itest-karaf by running the related test.

Another possible approach is to install the features directly in a Karaf instance.

```shell
oscerd@localhost:~/workspace/apache-camel/camel/platforms/karaf/features$ mvn clean install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=1024m; support was removed in 8.0
[WARNING] 
[WARNING] Some problems were encountered while building the effective settings
[WARNING] 'profiles.profile.id' must be unique but found duplicate profile with id jboss-public-repository @ /opt/apache-maven-3.3.9/conf/settings.xml
[WARNING] 'profiles.profile.id' must be unique but found duplicate profile with id redhat-earlyaccess-repository @ /opt/apache-maven-3.3.9/conf/settings.xml
[WARNING] 
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Camel :: Platforms :: Apache Karaf :: Features 2.18-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ apache-camel ---
[INFO] Deleting /home/oscerd/workspace/apache-camel/camel/platforms/karaf/features/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ apache-camel ---
[INFO] 
[INFO] --- maven-bundle-plugin:3.0.1:cleanVersions (versions) @ apache-camel ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ apache-camel ---
[INFO] 
[INFO] --- maven-resources-plugin:2.7:resources (filter) @ apache-camel ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-bundle-plugin:3.0.1:manifest (bundle-manifest) @ apache-camel ---
[WARNING] Ignoring project type pom - supportedProjectTypes = [jar, bundle]
[INFO] 
[INFO] --- maven-site-plugin:3.4:attach-descriptor (attach-descriptor) @ apache-camel ---
[INFO] 
[INFO] --- build-helper-maven-plugin:1.10:attach-artifact (attach-artifacts) @ apache-camel ---
[INFO] 
[INFO] --- ianal-maven-plugin:1.0-alpha-1:verify-legal-files (default) @ apache-camel ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ apache-camel ---
[INFO] Installing /home/oscerd/workspace/apache-camel/camel/platforms/karaf/features/pom.xml to /home/oscerd/.m2/repository/org/apache/camel/karaf/apache-camel/2.18-SNAPSHOT/apache-camel-2.18-SNAPSHOT.pom
[INFO] Installing /home/oscerd/workspace/apache-camel/camel/platforms/karaf/features/target/classes/features.xml to /home/oscerd/.m2/repository/org/apache/camel/karaf/apache-camel/2.18-SNAPSHOT/apache-camel-2.18-SNAPSHOT-features.xml
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.141 s
[INFO] Finished at: 2016-06-08T14:42:47+02:00
[INFO] Final Memory: 35M/1237M
[INFO] ------------------------------------------------------------------------
```

Then spin up a Karaf 4.0.4 or 4.0.5 instance and install the file directly in this way

```shell
oscerd@localhost:~/playground/apache-karaf/apache-karaf-4.0.4/bin$ ./karaf 
        __ __                  ____      
       / //_/____ __________ _/ __/      
      / ,<  / __ `/ ___/ __ `/ /_        
     / /| |/ /_/ / /  / /_/ / __/        
    /_/ |_|\__,_/_/   \__,_/_/         

  Apache Karaf (4.0.4)

Hit '<tab>' for a list of available commands
and '[cmd] --help' for help on a specific command.
Hit '<ctrl-d>' or type 'system:shutdown' or 'logout' to shutdown Karaf.

karaf@root()> feature:repo-add file:////home/oscerd/.m2/repository/org/apache/camel/karaf/apache-camel/2.18-SNAPSHOT/apache-camel-2.18-SNAPSHOT-features.xml
Adding feature url file:////home/oscerd/.m2/repository/org/apache/camel/karaf/apache-camel/2.18-SNAPSHOT/apache-camel-2.18-SNAPSHOT-features.xml
karaf@root()> 
```

In this situation you can try to install all the feature directly in Karaf. For example:

```shell
karaf@root()> feature:install -v camel-netty4
```

In this way we mantain also the OSGi universe aligned with our dependencies.

**Comment by anoordover** [comment]
When I run the karaf integration tests I get:
org.osgi.service.resolver.ResolutionException: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel; type=karaf.feature; version="[2.18.0.SNAPSHOT,2.18.0.SNAPSHOT]"; filter:="(&(osgi.identity=camel)(type=karaf.feature)(version>=2.18.0.SNAPSHOT)(version<=2.18.0.SNAPSHOT))" [caused by: Unable to resolve camel/2.18.0.SNAPSHOT: missing requirement [camel/2.18.0.SNAPSHOT] osgi.identity; osgi.identity=camel-blueprint; type=karaf.feature; version="[2.18.0.SNAPSHOT,2.18.0.SNAPSHOT]" [caused by: Unable to resolve camel-blueprint/2.18.0.SNAPSHOT: missing requirement [camel-blueprint/2.18.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-blueprint; type=osgi.bundle; version="[2.18.0.SNAPSHOT,2.18.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-blueprint/2.18.0.SNAPSHOT: missing requirement [org.apache.camel.camel-blueprint/2.18.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.apache.camel)(version>=2.18.0)(!(version>=2.18.1)))" [caused by: Unable to resolve org.apache.camel.camel-core/2.18.0.SNAPSHOT: missing requirement [org.apache.camel.camel-core/2.18.0.SNAPSHOT] osgi.wiring.package; filter:="(&(osgi.wiring.package=org.springframework.boot.autoconfigure.condition)(version>=4.1.0)(!(version>=5.0.0)))"]]]]
Am I missing something?

**Comment by oscerd** [comment]
I believe you need to recompile the project locally and completely.

In the camel directory run mvn clean install -DskipTests

**Comment by davsclaus** [comment]
To install camel its easier with:

    feature:repo-add camel 2.18-SNAPSHOT
    feature:install camel

And you can also just run the tests in tests/camel-itest-karaf
    
    runTests CamelNetty4Test

**Comment by anoordover** [comment]
feature:install camel-netty4 gives me:
Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-netty4; type=karaf.feature; version="[2.18.0.SNAPSHOT,2.18.0.SNAPSHOT]"; filter:="(&(osgi.identity=camel-netty4)(type=karaf.feature)(version>=2.18.0.SNAPSHOT)(version<=2.18.0.SNAPSHOT))" [caused by: Unable to resolve camel-netty4/2.18.0.SNAPSHOT: missing requirement [camel-netty4/2.18.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-netty4; type=osgi.bundle; version="[2.18.0.SNAPSHOT,2.18.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-netty4/2.18.0.SNAPSHOT: missing requirement [org.apache.camel.camel-netty4/2.18.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=io.netty.channel)" [caused by: Unable to resolve io.netty.transport/4.1.1.Final: missing requirement [io.netty.transport/4.1.1.Final] osgi.wiring.package; filter:="(&(osgi.wiring.package=io.netty.resolver)(version>=4.1.0)(!(version>=5.0.0)))"]]]

I guess I need to find out why the requirement io.netty.transport/4.1.1.Final is missing.
Where should I look to find this?

**Comment by davsclaus** [comment]
Use mvn search and type the package name in the advanced search
http://search.maven.org/#advancedsearch%7Cgav

And you can find there is a new netty-resolver JAR you need to add to the features xml file.

**Comment by anoordover** [comment]
Damn OSGI is complex when you have never done it.
I added a bundle line to the netty4 bundle and the building failed due to an old maven-resource-plugin (or whatever). I needed to used 3.0.1.
The problem is still persisting. Sorry.

**Comment by oscerd** [comment]
Welcome in the OSGi world, Arno :-)

**Comment by anoordover** [comment]
Btw the resource plug-in fails with "mark invalid". Could i use the karaf plugin for maven to help me.

**Comment by anoordover** [comment]
Yeah. It's working (camel-netty4). Now the cleaning up of the change and checking all the other netty4 dependencies.
I used org.apache.karaf.tooling:features-maven-plugin to help me to generate a base feature.xml.
Furthermore I changed the dependencies of camel-netty4 while generating the feature.xml from netty-all to netty-transport, netty-codec and netty-handler.

**Comment by anoordover** [comment]
checked:
- camel-amqp;
- camel-cassandraql
- camel-netty4
- camel-netty4-http
- camel-pgevent (index out of bounds?)
- camel-vertx
- camel-hl7

**Comment by davsclaus** [comment]
Looks good @oscerd I think its ready to merge.

**Comment by oscerd** [comment]
Yes :-) I'll merge later today :-) Thanks @anoordover @davsclaus

**Comment by oscerd** [comment]
Thanks @anoordover :-)

The PR has been merged. Can you close this PR? :-)

**Comment by davsclaus** [comment]
Can we remove netty41-version in parent/pom so all netty 4.x are using the same placeholder, eg netty-version.

**Comment by oscerd** [comment]
Yes, I'm working on it. Maybe @anoordover would like to take care of this?

**Comment by anoordover** [comment]
I will provide you with a new PR on a new branch.
OK?

**Comment by oscerd** [comment]
Yes, it's ok :-)

**Comment by anoordover** [comment]
Done

2016-06-10 9:29 GMT+02:00 Andrea Cosentino <notifications@github.com>:

**Comment by anoordover** [comment]
Who closes CAMEL-10002?

2016-06-10 9:29 GMT+02:00 Andrea Cosentino <notifications@github.com>:

**Comment by oscerd** [comment]
ASFGit bot I believe.

**Pull request closed without merging**
