### PR TITLE
upgrade to the latest roaster version supporting java 8

### PR DESCRIPTION
**Pull request by bvahdat**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Okay there is also roaster in the camel-SB repo

**Review by davsclaus — APPROVED** [review]

**Comment by bvahdat** [comment]
> Okay there is also roaster in the camel-SB repo

I suggest to remove that version definition completely and rely on whatever version `org.apache.camel:camel-dependencies:XYZ` has to offer. Makes sense?

**Comment by davsclaus** [comment]
yeah sure if that is possible

**Comment by bvahdat** [comment]
> yeah sure if that is possible

Running `mvn clean install -Pfastinstall` using Java 8 was successful:  https://github.com/apache/camel-spring-boot/commit/2e447afaca1605c71811bed13c1952f01e32b938

**Comment by bvahdat** [comment]
@davsclaus this PR is merged.

One question though, what would it take for me to be able to merge PRs more easily using those fancy "buttons" as documented here: https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request#merging-a-pull-request as I don't see them and don't know who could enable me for that.

**Comment by davsclaus** [comment]
Can you create a INFRA ticket as ASF infra should be able to help.

I think they need to get you into the camel-committers team
https://github.com/orgs/apache/teams/camel-committers/members

I can see you are not there, but I for example are.

**Pull request closed without merging**
