### PR TITLE
CAMEL-9737 - Create camel component for ServiceNow

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by davsclaus** [comment]
If I run mvn clean install in the camel-servicenow I get errors
```
testExceptions(org.apache.camel.component.servicenow.ServiceNowTest)  Time elapsed: 0.035 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route12 at: >>> To[servicenow:{{env:SERVICENOW_INSTANCE}}?userName={{env:SERVICENOW_USERNAME}}&password={{env:SERVICENOW_PASSWORD}}&model.incident=org.apache.camel.component.servicenow.model.Incident] <<< in route: Route(route12)[[From[direct:servicenow]] -> [To[servicenow:{... because of Property with key [env:SERVICENOW_INSTANCE] using function [env] returned null value which is not allowed, from input: servicenow:{{env:SERVICENOW_INSTANCE}}?userName={{env:SERVICENOW_USERNAME}}&password={{env:SERVICENOW_PASSWORD}}&model.incident=org.apache.camel.component.servicenow.model.Incident
Caused by: java.lang.IllegalArgumentException: Property with key [env:SERVICENOW_INSTANCE] using function [env] returned null value which is not allowed, from input: servicenow:{{env:SERVICENOW_INSTANCE}}?userName={{env:SERVICENOW_USERNAME}}&password={{env:SERVICENOW_PASSWORD}}&model.incident=org.apache.camel.component.servicenow.model.Incident
```

Looks like that profile in the pom.xml somehow do not cause the tests to skip by default.

**Comment by lburgazzoli** [comment]
Fixed by 75dd52c

**Comment by davsclaus** [comment]
Thanks code merged. Can you close.

Btw I fixed the component docs so the configuration is included and also the labels.

**Comment by lburgazzoli** [comment]
Is there any convention for naming labels ?

**Comment by davsclaus** [comment]
yes build camel-catalog and look at the existing labels. Also you can provide more labels separated by comma. A label is intended as a way of grouping the component. eg "to find all cloud components" etc.

**Pull request closed without merging**
