### PR TITLE
Enforce non-instantiability of utility classes

### PR DESCRIPTION
**Pull request by fvaleri**
We need to provide an AssertionError in case the constructor is accidentally
invoked from within the class or if there is some reflection trying to call the
private constructor. We also don't need final classes because each subclass
calls the super constructor.

### CODE REVIEW

**Comment by davsclaus** [comment]
What is the purpose of this PR?

**Comment by fvaleri** [comment]
This is just an improvement, a way to always ensure one instance and to give a better template for future utility implementations.

**Comment by oscerd** [comment]
I don't think this PR adds something more, so we can close it. Lets wait for more feedback btw

**Comment by fvaleri** [comment]
> AssertionError may be an option to enfore no instantion. but removing final makes the class extendible, wouldn't it?

No it wouldn't because all constructors must invoke a superclass constructor (explicitly or implicitly) and a subclass would have no working superclass constructor to invoke.

**Comment by lburgazzoli** [comment]
> > AssertionError may be an option to enfore no instantion. but removing final makes the class extendible, wouldn't it?
> 
> No it wouldn't because all constructors must invoke a superclass constructor (explicitly or implicitly) and a subclass would have no working superclass constructor to invoke.

`final` is a marker that says that the class can not be extended and this is checked at compile time so by removing it we say that you can but it will fail at runtime which is really bad.

In addition, if one really wish, I can easily bypass this check with `Unsafe.allocateInstance`

**Comment by davsclaus** [comment]
Yes I am -1 on this kind of change.

**Comment by fvaleri** [comment]
> > > AssertionError may be an option to enfore no instantion. but removing final makes the class extendible, wouldn't it?
> > 
> > 
> > No it wouldn't because all constructors must invoke a superclass constructor (explicitly or implicitly) and a subclass would have no working superclass constructor to invoke.
> 
> `final` is a marker that says that the class can not be extended and this is checked at compile time so by removing it we say that you can but it will fail at runtime which is really really bad.
> 
> In addition, if one really wish, the check can be work-round with `Unsafe.allocateInstance`

I see, thanks @lburgazzoli

**Comment by fvaleri** [comment]
Thanks for the feedback guys.
I'm going to close it.

**Pull request closed without merging**
