### PR TITLE
CAMEL-10966 Salesforce Maven Plugin doesn't escape strings when doing the camel-salesforce:generate phase

### PR DESCRIPTION
**Pull request by NickCis**
[Jira Ticket](https://issues.apache.org/jira/browse/CAMEL-10966)

Continuing with the previous [PR](https://github.com/apache/camel/pull/1511). 

This PR fixes escaping in `sobject-pojo` file.

In addition, it directly uses _apache lang3 EscapeUtils_ instead of relying in _Velocity Escape Tools_. This last change is done due to a bug in slash (`/`) escaping of the library.

Some tests were included, i think i coded them in an ugly way, please help me improve them.

### CODE REVIEW

**Comment by zregvart** [comment]
@NickCis thanks for following through on this, I created a pull request against your fork that cleans up the test a bit, if you can go through it and if you think its OK merge it in your fork.

After that if you could rebase your branch, i.e. `git pull --rebase` or if the `master` branch is not tracking the Camel GitHub mirror, add the `camel` remote, and set the `master` branch of your fork to track the `camel` remote:

    $ git remote add camel https://github.com/apache/camel.git
    $ git checkout master
    $ git branch --set-upstream-to=camel/master
    $ git pull

And then rebase the `salesforce-maven-plugin-escaping` branch on `master`:

    $ git checkout salesforce-maven-plugin-escaping
    $ git rebase master

Or something thereabouts, I'm no git guru :relaxed: 

And squash the top 3-4 commits (your changes) into one with the message `CAMEL-10966 Salesforce...` and force push those back to GitHub.

Thanks :+1:

**Comment by NickCis** [comment]
@zregvart I've merged your PR. And rebased the commit history. I think is Ok!.

Thanks for all the quick responses and explanations!.

**Comment by zregvart** [comment]
@NickCis thanks for all the work, this has been merged you can close this pull request :+1:

**Comment by NickCis** [comment]
Thank you for all the help and explanations!

**Pull request closed without merging**
