### PR TITLE
Hyperledger Aries - connectionless proofs

### PR DESCRIPTION
**Pull request by vchernetskyi993**
Added two Aries services: `/present-proof/create-request` (similar to `/present-proof/send-request`, but doesn't require connection upfront) and `/wallet/get-did-endpoint` (to populate service decorator with endpoint for proof presentation).

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@tdiesler ^^^ any feedback?

**Review by oscerd — APPROVED** [review]

**Comment by vchernetskyi993** [comment]
> Is there anything you think would be good to add to the docs of this component https://camel.apache.org/components/next/hyperledger-aries-component.html
> 
> The doc file is in the source code in src/main/docs

Added usage example for 2 new services.

**Comment by tdiesler** [comment]
@vchernetskyi993 thanks for this contribution. Could you please squash the PR? Otherwise its fine for me.

**Comment by davsclaus** [comment]
@tdiesler the PR has been squashed and merged (we do this from github)

**Pull request merged**
