### PR TITLE
CAMEL-10423 - Introduce XmppDirectProducer

### PR DESCRIPTION
**Pull request by allancth**
The order of which producer is used depends on what parameters are specified to the endpoint, with the following precendence: room (GroupChat), pubsub (PubSub), doc (Direct). When these parameters are not specified, by default, a PrivateChat producer will be used.

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please fix the codestyle?

[INFO] --- maven-checkstyle-plugin:2.17:checkstyle (validate) @ camel-xmpp ---
Downloading: http://repository.apache.org/snapshots/org/apache/camel/camel-buildtools/2.19.0-SNAPSHOT/maven-metadata.xml
[INFO] Starting audit...
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:30: 'member def modifier' have incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:30:1: File contains tab characters (this is the first instance). [FileTabCharacter]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:32: 'member def modifier' have incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:34: 'member def modifier' have incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:36: 'ctor def modifier' have incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:39: 'ctor def rcurly' have incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:41: 'method def modifier' have incorrect indentation level 8, expected level should be 4. [Indentation]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:57:82: '+' should be on a new line. [OperatorWrap]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:76:102: '+' should be on a new line. [OperatorWrap]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:80:102: '+' should be on a new line. [OperatorWrap]
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppDirectProducer.java:83: 'method def rcurly' have incorrect indentation level 8, expected level should be 4. [Indentation]
Audit done.

mvn -Psourcecheck to test

Thanks

**Comment by allancth** [comment]
Fixed.

**Comment by oscerd** [comment]
Thanks the PR has been merged. Do you mind closing this?

**Comment by allancth** [comment]
Thanks! :)

**Comment by oscerd** [comment]
:-)

**Comment by oscerd** [comment]
Good work!

**Pull request closed without merging**
