### PR TITLE
CAMEL-9570: Change CamelNamespaceHandler so that is doesn't force Blu…

### PR DESCRIPTION
**Pull request by hqstevenson**
…eprint Container to create objects too early

### CODE REVIEW

**Comment by hqstevenson** [comment]
Hold off on this one for a bit - I think I've found a better way that will ensure backward compatibility and not required the temporary CamelContext

**Comment by hqstevenson** [comment]
Never mind - I tried injecting the Camel Context into the CamelDependenciesFinder, but that causes the same issue with the Blueprint proxies.  Stick with this PR as-is.

I've tested it with my local projects, and I think it's good to go

**Comment by davsclaus** [comment]
I get an error in camel-test-blueprint with this PR
```
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 5.309 sec <<< FAILURE! - in org.apache.camel.test.blueprint.BlueprintPackageScan2Test
testRoute(org.apache.camel.test.blueprint.BlueprintPackageScan2Test)  Time elapsed: 3.196 sec  <<< ERROR!
java.lang.RuntimeException: Unable to initialize bean .camelBlueprint.factory.camel-1
Caused by: org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to initialize bean .camelBlueprint.factory.camel-1
Caused by: org.apache.camel.RuntimeCamelException: Error during post processing of bean Routes: []
Caused by: org.apache.camel.NoSuchBeanException: Cannot lookup: foo from registry: org.apache.camel.blueprint.BlueprintContainerRegistry@54cef2f8 with expected type: interface org.apache.camel.Endpoint due: Unable to initialize bean .camelBlueprint.bean.factory.foo
Caused by: org.osgi.service.blueprint.container.ComponentDefinitionException: Unable to initialize bean .camelBlueprint.bean.factory.foo
Caused by: org.apache.aries.blueprint.di.CircularDependencyException: [BeanRecipe[name='camel-1'], BeanRecipe[name='.camelBlueprint.factory.camel-1'], BeanRecipe[name='foo'], BeanRecipe[name='.camelBlueprint.bean.factory.foo'], BeanRecipe[name='camel-1']]
```

**Comment by davsclaus** [comment]
Do you see that error also? I will run this again to double check, and then also with the PR reverted as well.

**Comment by davsclaus** [comment]
Okay first run got these errors
```
Failed tests:
org.apache.camel.test.blueprint.PropertyInjectTest.testPropertyInject(org.apache.camel.test.blueprint.PropertyInjectTest)
  Run 1: PropertyInjectTest.testPropertyInject:39->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Body of message: 0. Expected: <Hello> but was: <null>
  Run 2: PropertyInjectTest.testPropertyInject:39->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Body of message: 0. Expected: <Hello> but was: <null>
  Run 3: PropertyInjectTest.testPropertyInject:39->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Body of message: 0. Expected: <Hello> but was: <null>

Tests in error:
org.apache.camel.test.blueprint.BlueprintPackageScan2Test.testRoute(org.apache.camel.test.blueprint.BlueprintPackageScan2Test)
  Run 1: BlueprintPackageScan2Test>CamelBlueprintTestSupport.setUp:241->CamelBlueprintTestSupport.createBundleContext:175 » Runtime
  Run 2: BlueprintPackageScan2Test>CamelBlueprintTestSupport.setUp:241->CamelBlueprintTestSupport.createBundleContext:175 » Runtime
  Run 3: BlueprintPackageScan2Test>CamelBlueprintTestSupport.setUp:241->CamelBlueprintTestSupport.createBundleContext:175 » Runtime

org.apache.camel.test.blueprint.management.ManagedEndpointInjectRefEndpointTest.testRef(org.apache.camel.test.blueprint.management.ManagedEndpointInjectRefEndpointTest)
  Run 1: ManagedEndpointInjectRefEndpointTest.testRef:58 » CamelExecution Exception occ...
  Run 2: ManagedEndpointInjectRefEndpointTest.testRef:58 » CamelExecution Exception occ...
  Run 3: ManagedEndpointInjectRefEndpointTest.testRef:58 » CamelExecution Exception occ...


Tests run: 102, Failures: 1, Errors: 2, Skipped: 0
```

**Comment by davsclaus** [comment]
Yes I get the same errors on the 2nd run as well with this PR

**Comment by hqstevenson** [comment]
Let me look at that - it's strange that what I've done would cause a circular dependency in the blueprint.

**Comment by davsclaus** [comment]
Yeah you are likely almost there, but osgi and blueprint is hard. Without this PR all the unit tests passes.

**Comment by davsclaus** [comment]
Also maybe some of those test failures may surfaced an issue in the test with your PR. However I haven't looked at those tests why the fail, but it has known in the past to happen.

**Comment by davsclaus** [comment]
An alternative way could maybe be in that dependency finder to collect those "links" and then later do some kind of osgi service reference or something to make the blueprint graceful wait, or some other way of waiting until they are there, and make blueprint be in grace wait mode.

**Comment by hqstevenson** [comment]
Well I'm stuck :-)

After pounding my head on this one test failure for the past couple of days, I don't really know if I can "fix" this.  The one test that fails looks like a completely valid condition/setup/route to me, but the PR breaks the test.  Somehow the change introduces a cyclic dependency - the endpoint depends on the camel context which depends on the endpoint - BOOM.

Digging through the code a bit, I think I see how this is happening.  There are several classes in the org.apache.camel.blueprint package that do something like blueprintContainer.getComponentInstance(camelContextId).  I think this may be causing the circular reference - Blueprint is trying to create the object (in this case, and endpoint) in order to inject it into the Camel Context, and then the object factory tries to get the Camel Context from Blueprint to create the object.

From my earlier experiments, it appeared that if blueprintContainer.getComponentInstance(...) was called during parsing/initialization phase of Blueprint lifecycle, my dynamic services were broken.  With these calls embedded in multiple factory classes (I counted at least 8), this problem just got much bigger.  I'll have to look at the whole parse/construction process again to see if I can come up with a good way to fix my services issue in a backward compatible fashion, but this one may be out of my league.  I'm very comfortable working with the OSGi/Blueprint pieces, but the tangle of the Camel pieces wrapped around the OSGi/Blueprint pieces is a little beyond me right now.

Personally, I think the circular dependency in the code is a real issue, regardless of my services issue.  If you have any suggestions on how to setup the factories to get rid of the dependency problem, I'd love to hear about it.

**Comment by davsclaus** [comment]
I think you are continued this effort on
https://github.com/apache/camel/pull/1297

If so maybe this PR can be closed

**Comment by hqstevenson** [comment]
This PR is trying to address a separate issue - the issue in CAMEL-9570 with Blueprint service proxies.  The 1297 PR is for improvement CAMEL-10513, which is different.  I had mixed the two of them up in CAMEL-9570 before, but I created a separate JIRA and PR just for the startup behavior.

Although this PR does fix CAMEL-9570, it breaks other functionality - so it obviously can't be merged to master.  However, I was hoping someone could take a look at it and give me some ideas on how to proceed.  CAMEL-9570 is one of the most problematic issues I'm facing from an operational standpoint.

**Comment by davsclaus** [comment]
Closing old PRs

**Pull request closed without merging**
