### PR TITLE
CAMEL-19725: replaced Thread.sleep() in camel-opensearch tests

### PR DESCRIPTION
**Pull request by LostArtist**

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
marking as request changes, so I can review it before merge.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
main branch is open for commits for 4.1 work

**Review by davsclaus — APPROVED** [review]

**Comment by orpiske** [comment]
> main branch is open for commits for 4.1 work

Thanks! I'll start merging the queued items

**Review by orpiske — APPROVED** [review]
Thanks, LGTM

**Pull request merged**
