### PR TITLE
CAMEL-10178: Added Google PubSub Component

### PR DESCRIPTION
**Pull request by evmin**
Google PubSub component with producer and consumer endpoints, unit and integration tests. Speed optimisation (mini batching, async processing) will be done in subsequent releases - dependent on the new client library from Google. For now it is synchronous, message by message processing.

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please run mvn -Psourcecheck and fix all the codestyle errors?

Thanks.

**Comment by evmin** [comment]
Sure. Is there a Intellij Scheme that would make it easy?

**Comment by oscerd** [comment]
@evmin no, there isn't at the moment.

https://github.com/apache/camel/tree/master/buildingtools

**Comment by evmin** [comment]
No issues. Is there some sort of a guideline.

I am getting cryptic errors like these:
`
[ERROR] /projects/camel/camel/components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/ExchangeAckTransaction.java:8: Line does not match expected header line of ' *'. [Header]

[ERROR] /projects/camel/camel/components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/ExchangeAckTransaction.java:24: Wrong order for 'java.util.ArrayList' import. [ImportOrder]
`

Just to get me started.

**Comment by oscerd** [comment]
Usually, it's like an exploration. Point after point. Otherwise you can open your project in eclipse, import the checkstyle from camel repo and update the indentation.

**Comment by oscerd** [comment]
Not sure if there is any scheme somewhere for Idea. We can ping @davsclaus for this :-)

**Comment by evmin** [comment]
@oscerd : No issues, I'll get cracking. I got what was the problem - I just copied the disclaimer from one of the Camel files and it came with the `<p>`

**Comment by evmin** [comment]
@oscerd Could you please check if the warning is correct?

`[ERROR] /projects/camel/camel/components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConstants.java:19:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]`

I am declaring an enum - is this warning correct?

**Comment by oscerd** [comment]
Yes, it is.

You'll need to define your utility class as final and then add a private constructor

```java
   private blablabla() {
      //not called
   }
```

**Comment by oscerd** [comment]
http://stackoverflow.com/questions/14398747/hide-utility-class-constructor-utility-classes-should-not-have-a-public-or-def

**Comment by tadayosi** [comment]
Hi @evmin,

> [ERROR] /projects/camel/camel/components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/ExchangeAckTransaction.java:8: Line does not match expected header line of ' *'. [Header]

This should mean you should not use `<p>` in the header comment. Compare the entire comment with other classes.

> [ERROR] /projects/camel/camel/components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/ExchangeAckTransaction.java:24: Wrong order for 'java.util.ArrayList' import. [ImportOrder]

This means `java.*` should come first.

> [ERROR] /projects/camel/camel/components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConstants.java:19:1: Utility classes should not have a public or default constructor. [HideUtilityClassConstructor]

I think it's just you should declare the private default constructor like this:

    private GooglePubsubConstants() {
    }

**Comment by evmin** [comment]
Thank you very much, @oscerd and @tadayosi !

Appreciate the guidance and your help - love the exercise.

**Comment by evmin** [comment]
@oscerd Done. Could you please advise on what else needs to be fixed?

**Comment by oscerd** [comment]
@evmin looks good to me. The only thing you can is a test in tests/camel-itest-karaf to test the karaf feature like the other components do.

@davsclaus what do you think of this PR? Do you have any other thought?

**Comment by oscerd** [comment]
One other thing why using SEVERE in logging.properties?

**Comment by evmin** [comment]
logging.properties is being used by the PubSub Emulator. With any other option it becomes a bit too verbose and produces a lot of output that is being registered by mvn as ERROR (even when it is INFO). So it is a hack to shut it up. I have raised this with Google, but not sure when (or if) it is going to be addressed.

Should I add a comment?

P.S. IN regards of Karaf - I will check out. How important is it, given that we have tested the component with unit and integratin tests?

**Comment by oscerd** [comment]
@evmin no problem then for SEVERE. I didn't notice it was in test. Sorry, my mistake.

Karaf integration is important. A lot of users are based on Karaf and on OSGi, so it is important that Karaf feature installs correctly.

**Comment by evmin** [comment]
@oscerd Ok I will have a look. Though I do not have any experience with PaxExam. Is there a guide how to start an environment or run a test?

**Comment by oscerd** [comment]
@evmin You can take a look here. For example the camel-facebook itests-karaf test

https://github.com/apache/camel/blob/master/tests/camel-itest-karaf/src/test/java/org/apache/camel/itest/karaf/CamelFacebookTest.java

You just need to create your own test for the component. Then you need to follow these steps:

- enter in platform/karaf/features and run

```
mvn clean install
```

- enter in tests/camel-itest-karaf and run

```
mvn clean test -Dtest=<your test class name>
```

This will spin up a karaf instance (4.0.7 on master) and installs your feature.

- Additionally you can also download a Karaf distribution (4.0.7 for example) and run a karaf instance with

```
/bin/karaf
```

In the shell you'll just need to run the following commands

```
> features:repo-add camel 2.19.0-SNAPSHOT
.
.
.
> features:install -v camel-google-pubsub
```

and verify the feature installs correctly

**Comment by evmin** [comment]
@oscerd Thank you very much. I think I got it. 

Would you be so kind to check as to what might be the issue with features.xml?

There were no problem this morning. I have checked out the master features, updated it again and pushed - the conflict seems to still be there. What do I miss?

**Comment by oscerd** [comment]
Try to do in this way.

on your branch:

- git reset --hard HEAD~2

This way you remove the latest commit you've pushed on your branch

- git pull --rebase <camel_apache_master_repo> master

where <camel_apache_master_repo> should be your upstream I suppose (https://github.com/apache/camel)

This way you solved the conflicts.

Then simply push the branch again

- git push -f origin CAMEL-10178

**Comment by oscerd** [comment]
Let me know. You just need to rebase.

**Comment by oscerd** [comment]
You pushed one more commit to resolve the conflict.

Do a 

- git reset --hard HEAD~1

and go back to the PR with this as last commit

CAMEL-10178: Karaf Test

Than rebase and push with -f

**Comment by evmin** [comment]
@oscerd Not sure I am getting it. If I checkout the apache master features - all looks good, no conflicts. But if I update it with the pubsub feature - it is in conflict.

**Comment by oscerd** [comment]
Let me have a look.

**Comment by evmin** [comment]
@oscerd I can prep a new pull request - from scratch - if required.

**Comment by oscerd** [comment]
This seems to be ok.

https://github.com/oscerd/camel/tree/CAMEL-10178

I added one commit and removed the conflicts and it seems to be able to merge without conflicts.

**Comment by evmin** [comment]
Thank you!

**Comment by oscerd** [comment]
Maybe it would be good to create a new PR.

I try to run the test and I get the following error

Running org.apache.camel.component.google.pubsub.unit.PubsubComponentTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.456 sec - in org.apache.camel.component.google.pubsub.unit.PubsubComponentTest
Running org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 1.638 sec <<< FAILURE! - in org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest
testEndpointConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest)  Time elapsed: 1.614 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[google-pubsub://test-project:test-sub-na... because of The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

testEndpointConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest)  Time elapsed: 0.011 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route2: Route(route2)[[From[google-pubsub://test-project:test-sub-na... because of The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

testEndpointConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest)  Time elapsed: 0.01 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route3: Route(route3)[[From[google-pubsub://test-project:test-sub-na... because of The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

Running org.apache.camel.component.google.pubsub.unit.PubsubProducerTest
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.031 sec <<< FAILURE! - in org.apache.camel.component.google.pubsub.unit.PubsubProducerTest
testProducerConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubProducerTest)  Time elapsed: 0.011 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route4: Route(route4)[[From[direct://from]] -> [To[google-pubsub://t... because of Failed to create Producer for endpoint: google-pubsub://test-project:test-topic-name. Reason: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: google-pubsub://test-project:test-topic-name. Reason: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

testProducerConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubProducerTest)  Time elapsed: 0.009 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route5: Route(route5)[[From[direct://from]] -> [To[google-pubsub://t... because of Failed to create Producer for endpoint: google-pubsub://test-project:test-topic-name. Reason: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: google-pubsub://test-project:test-topic-name. Reason: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.

testProducerConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubProducerTest)  Time elapsed: 0.009 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route6: Route(route6)[[From[direct://from]] -> [To[google-pubsub://t... because of Failed to create Producer for endpoint: google-pubsub://test-project:test-topic-name. Reason: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: org.apache.camel.FailedToCreateProducerException: Failed to create Producer for endpoint: google-pubsub://test-project:test-topic-name. Reason: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running on Google App Engine, Google Compute Engine, or Google Cloud Shell. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.


Results :

Tests in error: 
org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest.testEndpointConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubEndpointTest)
  Run 1: PubsubEndpointTest>CamelTestSupport.setUp:261->CamelTestSupport.doSetUp:360->CamelTestSupport.startCamelContext:676 » FailedToCreateRoute
  Run 2: PubsubEndpointTest>CamelTestSupport.setUp:261->CamelTestSupport.doSetUp:360->CamelTestSupport.startCamelContext:676 » FailedToCreateRoute
  Run 3: PubsubEndpointTest>CamelTestSupport.setUp:261->CamelTestSupport.doSetUp:360->CamelTestSupport.startCamelContext:676 » FailedToCreateRoute

org.apache.camel.component.google.pubsub.unit.PubsubProducerTest.testProducerConfiguration(org.apache.camel.component.google.pubsub.unit.PubsubProducerTest)
  Run 1: PubsubProducerTest>CamelTestSupport.setUp:261->CamelTestSupport.doSetUp:360->CamelTestSupport.startCamelContext:676 » FailedToCreateRoute
  Run 2: PubsubProducerTest>CamelTestSupport.setUp:261->CamelTestSupport.doSetUp:360->CamelTestSupport.startCamelContext:676 » FailedToCreateRoute
  Run 3: PubsubProducerTest>CamelTestSupport.setUp:261->CamelTestSupport.doSetUp:360->CamelTestSupport.startCamelContext:676 » FailedToCreateRoute


Tests run: 3, Failures: 0, Errors: 2, Skipped: 0


Maybe also these tests must be skipped.

**Comment by evmin** [comment]
Will do a new PR. 

As for failed tests - I will have a look. Could be the local setup leaking in where it should not.

**Comment by oscerd** [comment]
Many thanks @evmin :-)

By the way this is a great work. Glad you'd like donating it to Apache Camel project.

**Comment by evmin** [comment]
Absolutely. BTW it is indeed a leak within the local environment. Will get it fixed.

**Comment by oscerd** [comment]
Ok, we'll waiting your new PR. Thanks.

**Pull request closed without merging**
