### PR TITLE
[CAMEL-15285] fix broken anchors and images

### PR DESCRIPTION
**Pull request by ahus1**
This PR fixes some broken anchors with in valid characters and a broken image.

### CODE REVIEW

**Comment by ahus1** [comment]
> You need to fix this stuff into the src/main/docs of the single components and then run the build, the src/generated stuff depend from the src/main/docs files.

@oscerd - I double checked and for all generated files both the source and the generated file have been updated in the commits. Did you spot a file that I missed? 

I looked at the docs and didn't find a minimal command to just build the documentation. The `gulpfile.js` in the `docs` folder does some of it, but not all. I'd be happy for some advice.

**Comment by oscerd** [comment]
> > You need to fix this stuff into the src/main/docs of the single components and then run the build, the src/generated stuff depend from the src/main/docs files.
> 
> @oscerd - I double checked and for all generated files both the source and the generated file have been updated in the commits. Did you spot a file that I missed?
> 
> I looked at the docs and didn't find a minimal command to just build the documentation. The `gulpfile.js` in the `docs` folder does some of it, but not all. I'd be happy for some advice.

My fault, I've taken a look only at the beginning of the files list. Sorry. There is no command to build the docs directly. You need to build the project completely once, then you could edit the .adoc file on single components, run a component build and then come back to docs folder and run a build, the docs will be updated in that way

**Comment by oscerd** [comment]
Thanks a lot and sorry for the wrong review.

**Comment by ahus1** [comment]
@oscerd - thank you for the quick response and review.

**Pull request merged**
