### PR TITLE
Fix the problem of using '+' and '+=' operators to concatenate strings in a loop.

### PR DESCRIPTION
**Pull request by BruceKuiLiu**
The method is building a String using concatenation in a loop.
In each iteration, the String is converted to a StringBuilder, appended to, and converted back to a String.
This can lead to a cost quadratic in the number of iterations, as the growing string is recopied in each iteration.
Better performance can be obtained by using a StringBuilder explicitly.
http://findbugs.sourceforge.net/bugDescriptions.html#SBSC_USE_STRINGBUFFER_CONCATENATION

### CODE REVIEW

**Comment by oscerd** [comment]
I'm gonna merge this

**Comment by davsclaus** [comment]
@oscerd oh I just merged

There is a build error in this example, I wonder if you could take a look
```
[ERROR] /Users/davsclaus/workspace/camel/examples/camel-example-cdi-kubernetes/src/main/java/org/apache/camel/example/cdi/kubernetes/Application.java:[71,108] error: incompatible types: Time cannot be converted to CharSequence
```

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by BruceKuiLiu** [comment]
Thanks.

**Comment by oscerd** [comment]
@davsclaus I'll take a look :-)

**Comment by oscerd** [comment]
@davsclaus I can't reproduce the error on my side. Not sure why.

**Comment by davsclaus** [comment]
@BruceKuiLiu you need to create a new PR you cannot reopen old ones that has been merged.

**Comment by BruceKuiLiu** [comment]
I see, many thanks.

**Pull request closed without merging**
