### PR TITLE
Updating OpenLogic commercial support description

### PR DESCRIPTION
**Pull request by jreock**
Change to Commercial Support page, update offering for OpenLogic.

### CODE REVIEW

**Review by oscerd — COMMENTED** [review]
This is a spot. I don't think it is appropriate.

**Comment by jreock** [comment]
Hi -- apologies, it seemed to fit with the other entries on the page.  What would need to change?

**Comment by oscerd** [comment]
I think this "OpenLogic is the only vendor that can provide comprehensive support, consultative guidance, and training for your entire open source infrastructure stack" can be removed.

**Comment by jreock** [comment]
No problem, we are editing -- thank you!

**Review by davsclaus — COMMENTED** [review]
The blurb needs update and to focus only on what openlogic can do for Camel - its not a page for advertising all sort of non Camel stuff - and keep it neutral and dont say "truely only one that can ..."

**Comment by jreock** [comment]
That makes perfect sense, thank you! We're editing the copy now and will post it here for preview before issuing another PR.

**Comment by jreock** [comment]
This is the new suggestion:  "OpenLogic by Perforce has a team of Camel experts ready to help you. We provide 24/7 support for troubleshooting issues and outages, consulting on architecture and design, and instructor-led, hands-on training. https://www.openlogic.com/solutions/support-activemq-apache-camel-kafka#apache-camel[Learn more about OpenLogic's Camel support]"  If that verbiage is alright, let me know and I'll send another PR -- thanks for the support and patience!

**Review by jreock — COMMENTED** [review]
Changes based on discussion with dev community

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
