### PR TITLE
[CAMEL-16365] Support ecdsa-sha2-nistp256/384/521 and ssh-ed25519 algorithms in camel-ssh component

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
We need to have a look at camel-karaf repository too

**Comment by grgrzybek** [comment]
> We need to have a look at camel-karaf repository too

Sure - checking.

**Comment by grgrzybek** [comment]
@oscerd @zregvart the checks fail with:
```
 Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.2:yarn (yarn-install) on project docs: Failed to run task: 'yarn install --no-progress --force --non-interactive --frozen-lockfile' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

May I merge this PR?

**Comment by oscerd** [comment]
Go ahead and merge

**Pull request merged**
