### PR TITLE
CAMEL-18786: skeleton for reorganizing the Camel Core documentation

### PR DESCRIPTION
**Pull request by orpiske**
These changes introduce a new documentation module with the intention of creating a project page for Camel Core. Within that page, the documentation for the project is categorized and separated according to the audience.

### CODE REVIEW

**Comment by orpiske** [comment]
Here's a preview of the website with these changes: https://angusyoung.org/arquivos/camel-new-website/public/

**Comment by orpiske** [comment]
The part that matters for Camel Core is here: https://angusyoung.org/arquivos/camel-new-website/public/camel-core/

**Comment by orpiske** [comment]
@davsclaus @oscerd folks, FYI, I'm going to get this one merged so we can continue the work on the doc reorg. It should not break the doc ... but in case it does, please feel free to revert. I'll try to keep an eye on things, but I'm on PTO, so there's a chance I'll miss it.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Thanks.

**Comment by davsclaus** [comment]
Yeah lets get the ball rolling

**Pull request merged**
