### PR TITLE
Add PMD scanning for PR code

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
I really hate PMD, but it's just me.

**Comment by orpiske** [comment]
> I really hate PMD, but it's just me.

Yeah, there can be a lot of false negatives if we don't tune it accordingly. I'll definitely propose it with a ruleset that trying to balance this. 

BTW, the PR as it is cannot be accepted (I was testing if PMD action was whitelisted, but it's not).

**Comment by orpiske** [comment]
> Eventually, if it won't be whitelisted, we just need to add the action as git submodule, like the backport action. So no problem at all.

Oh, nice, I was reading about this on the wiki and it seems a reasonable way to do it too. I will open a ticket asking for Infra to take a look and see if they can whitelist it.

**Comment by orpiske** [comment]
Folks at Apache Infra approved the PMD action (INFRA-22883). Re-opening ...

**Comment by orpiske** [comment]
I am merging this one so I can test it and tweak it during the week based on what we receive/review/etc. In case of any problems, I'll fix it and tune it.

**Pull request merged**
