### PR TITLE
CAMEL-17062 Move properties sync to camel-dependencies to avoid deployment issues

### PR DESCRIPTION
**Pull request by cunningt**
Giving the changes from https://github.com/apache/camel/pull/6462 another try.      The properties in camel-dependencies are synced from camel-parent within camel-catalog, but there is not a guarantee that the sync will happen because of how maven determines the build order.    I don't believe that the module order change here https://github.com/apache/camel/commit/71e28ebe69a5c87721bbc63693a884473baf302e#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8 fixes the issue - maven's reactor determines the correct build order and factors in the dependencies of the modules (https://maven.apache.org/guides/mini/guide-multiple-modules.html).     camel-dependencies has no dependencies currently, so from what I've seen in building the project, the reactor views it as a good candidate to run early, despite the module ordering.

Moved the sync out of camel-catalog and into to camel-dependencies, which generates the camel-dependencies pom.   The change to SyncPropertiesMojo attaches the camel-dependencies artifact to the build so that it can be consumed by the downstream projects.

### CODE REVIEW

**Comment by davsclaus** [comment]
We want to cut 3.14.0 release later today.

Lets wait with this PR for Camel 3.15 as that is a better release to try this.

**Comment by oscerd** [comment]
We'll need to rebase.

**Comment by cunningt** [comment]
Sounds good to me - I'll rebase after the move to 3.15.0-SNAPSHOT

**Comment by davsclaus** [comment]
@cunningt we have moved to 3.15, can you rebase

**Comment by cunningt** [comment]
Rebased on top of current main

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Oh did we not merge this, now we have merge conflicts again. @cunningt wonder if you can rebase yet again (sorry)

**Comment by cunningt** [comment]
No worries, did another rebase.

**Pull request merged**
