### PR TITLE
[CAMEL-13275] Move camel-core-osgi and camel-core-xml modules to root…

### PR DESCRIPTION
**Pull request by fpapon**
… core module.

@jbonofre @davsclaus : can you review please?

There is 2 tag as changed by git in the license header but I can see any changes...

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks @fpapon did you run a full build of the project after this, eg such as running

     mvn clean install -P fastinstll

To see if you get any problems? Otherwise its a +1 from me.

**Comment by fpapon** [comment]
@davsclaus yes the full build is ok, I didn't see any problems ;)

**Comment by oscerd** [comment]
Let me merge this

**Comment by oscerd** [comment]
Thanks, merged. I'm running the full build on CI with this new commit.

**Pull request closed without merging**
