### PR TITLE
[CAMEL-13711] Files.createTempFile not equivalent to File.createTempFile

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by davsclaus** [comment]
Yeah this would affect all of the places this was changed. So I would like to know the reason behind from @coheigea - and we can then consider either to fix all of them, or revert it to use the old code, which has worked fine for all the time.

**Comment by coheigea** [comment]
@davsclaus The reasoning behind the change was the following comment:

https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createTempFile-java.lang.String-java.lang.String-

"The Files.createTempFile method provides an alternative method to create an empty file in the temporary-file directory. Files created by that method may have more restrictive access permissions to files created by this method and so may be more suited to security-sensitive applications."

I wasn't aware that the implementation was different though. I'm fine with reverting the commit if it's causing problems.

**Comment by oscerd** [comment]
+1 for revert

**Comment by tdiesler** [comment]
I would leave it in and handle those specific and rare cases where the fname contains a '.' individually. It may actually be an hdfs2 issue, because foo.open is not a good file name.

**Comment by oscerd** [comment]
So, we can merge this PR and search for individual usage of the method...

**Comment by tdiesler** [comment]
I'd say yes. And for potential problems we can cross that bridge when we come to it. Whoever owns hdfs2 may want to check that this change is consistent within hdfs2.

**Comment by davsclaus** [comment]
Okay lets merge this and keep the others as is

**Comment by oscerd** [comment]
Thanks all

**Comment by coheigea** [comment]
@oscerd - needs to be merged to camel-2.x as well

**Comment by oscerd** [comment]
Yes, I'll backport

**Comment by oscerd** [comment]
Done

**Pull request merged**
