### PR TITLE
Backport of the fix for CAMEL-7985 from trunk that makes camel-test-blueprint  usable again.

### PR DESCRIPTION
**Pull request by luigidemasi**
Backport  CAMEL-7985  fix from trunk that makes camel-test-blueprint in 2.15  branch usable again.
fixed also a duplicate dependency declaration of  org.apache.aries.proxy.api

### CODE REVIEW

**Comment by davsclaus** [comment]
This has already been done. Do you mind closing this PR.

**Comment by luigidemasi** [comment]
Are you sure? I can see it in trunk not in camel-2.15.x branch.

**Comment by davsclaus** [comment]
Ah gregor missed that one when he did a big backport - I will get the last piece he missed in.

**Comment by luigidemasi** [comment]
thanks.

**Pull request closed without merging**
