### PR TITLE
Make incremental-build action generic

### PR DESCRIPTION
**Pull request by Croway**
Make incremental-build action generic in order to be reused in camel-spring-boot repository

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
Nice one, thanks!

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
It may have caused a problem I see this now
```
Error: /home/runner/work/camel/camel/./.github/actions/incremental-build/action.yaml (Line: 42, Col: 13): Expected format {org}/{repo}[/path]@ref. Actual 'apache/camel/.github/actions/install-mvnd'
Error: System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at GitHub.Runner.Worker.TemplateTraceWriter.Error(String format, Object[] args)
   at GitHub.DistributedTask.ObjectTemplating.TemplateContext.Error(Nullable`1 fileId, Nullable`1 line, Nullable`1 column, String message)
   at GitHub.DistributedTask.ObjectTemplating.TemplateContext.Error(TemplateToken value, String message)
   at GitHub.DistributedTask.Pipelines.ObjectTemplating.PipelineTemplateConverter.ConvertToStep(TemplateContext context, TemplateToken stepsItem, ReferenceNameBuilder nameBuilder)
   at GitHub.DistributedTask.Pipelines.ObjectTemplating.PipelineTemplateConverter.ConvertToSteps(TemplateContext context, TemplateToken steps)
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Failed to load /home/runner/work/camel/camel/./.github/actions/incremental-build/action.yaml
```

**Comment by davsclaus** [comment]
https://github.com/apache/camel/actions/runs/9095168434/job/24997795312?pr=14157

**Comment by Croway** [comment]
> It may have caused a problem I see this now
> 
> ```
> Error: /home/runner/work/camel/camel/./.github/actions/incremental-build/action.yaml (Line: 42, Col: 13): Expected format {org}/{repo}[/path]@ref. Actual 'apache/camel/.github/actions/install-mvnd'
> Error: System.FormatException: Input string was not in a correct format.
>    at System.Text.ValueStringBuilder.ThrowFormatError()
>    at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
>    at System.String.Format(IFormatProvider provider, String format, Object[] args)
>    at GitHub.Runner.Worker.TemplateTraceWriter.Error(String format, Object[] args)
>    at GitHub.DistributedTask.ObjectTemplating.TemplateContext.Error(Nullable`1 fileId, Nullable`1 line, Nullable`1 column, String message)
>    at GitHub.DistributedTask.ObjectTemplating.TemplateContext.Error(TemplateToken value, String message)
>    at GitHub.DistributedTask.Pipelines.ObjectTemplating.PipelineTemplateConverter.ConvertToStep(TemplateContext context, TemplateToken stepsItem, ReferenceNameBuilder nameBuilder)
>    at GitHub.DistributedTask.Pipelines.ObjectTemplating.PipelineTemplateConverter.ConvertToSteps(TemplateContext context, TemplateToken steps)
>    at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
>    at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
> Error: Failed to load /home/runner/work/camel/camel/./.github/actions/incremental-build/action.yaml
> ```

I noticed, I am sorry for the issue, but should be already fixed with https://github.com/apache/camel/pull/14158#pullrequestreview-2057794488

**Pull request merged**
