### PR TITLE
Enable Case Sensitive pattern match for file include and exclude

### PR DESCRIPTION
**Pull request by dwarakart**
The changes are to enable the file consumer include and exclude patterns to be case sensitive. AntInclude & AntExclude with AntCaseSensitive options donot support java regex pattern match. To over come this, a new caseSesitive attribute is exposed in the FileEndpoint that determines the pattern match to be case sensitive or not. I have also added 3 new test classes and modified 3 existing tests that test with and with out the new flag.

Please review and approve

### CODE REVIEW

**Comment by davsclaus** [comment]
You can tell Java regular expressions to be case insensitive, so just use that. We should not add more options to the file component - it has a lot already.

**Comment by dwarakart** [comment]
Hi Claus, 

Thanks for the quick review. The issue that I ran into is as below 

Files to be matched (abc to be of any case): 20151116_103000_abc.txt, 20151116_123030_Abc.txt
Files that should not be matched: 20151116_123_abc.txt

Using java regex, include=[0-9]{8}_[0-9]{6}_abc.* (no option to say case insensitive match)

Using ant pattern matcher, antInclude=*_abc* &antFilterCaseSensitive=false
But this would also match the file 20151116_123_abc.txt

The GenericFileFilter also cannot be used as the accept method doesnt have access to other properties like include & exclude.

Due to the above reasons, I approached the addition of a new optional parameter on the FileEndpoint. I understand that there are a lot of options already but this would be useful just like the antFilterCaseSensitive

Thanks

**Comment by davsclaus** [comment]
See first answer
http://stackoverflow.com/questions/3436118/is-java-regex-case-insensitive

**Comment by davsclaus** [comment]
Sorry we do not want a gazillion of options to further complicate and confuse end users.

**Comment by davsclaus** [comment]
Can you try with the `(?i)` to turn on insenstive.

That said we could consider always being case insenstive on the file component. As IMHO people should not really use files with different case, eg `test.xml` and `Test.xml` should be the same file really.

**Comment by davsclaus** [comment]
You are welcome to work on a patch where the regular exp pattern in Camel is case insenstive by default which we can introduce from Camel 2.17 onwards, eg using `Pattern.CASE_INSENSITIVE`

**Comment by dwarakart** [comment]
Sounds great. I made and pushed the necessary changes in the same pull request. I tried to keep the changes simple. Please review and let me know in case further changes needed.

**Comment by davsclaus** [comment]
Thanks instead of the upperCase which you would have to provide a Locale.ENGLISH to support some i18n its imho better to create a Pattern and provide that insenstive flag. See for example that SO link. Then we can create the pattern once, so we do not have to re-create the regexp on each test. 

Wonder if you could look into that?

**Comment by dwarakart** [comment]
Hi Claus,
I was making changes so that the pattern can be reused across all consumers from the same endpoint. How should I progress with the changes? Please suggest.
Thanks
Dwaraka

**Pull request closed without merging**
