### PR TITLE
CAMEL-15496: Headers and Properties support

### PR DESCRIPTION
**Pull request by rgannu**
The additional headers will be added on top of the existing headers
from the message.

The properties added are only basic AMQP properties as defined in the
{@link com.rabbitmq.client.AMQP.BasicProperties.Builder}. When the
message contains already these properties then will be considered and
these additional properties will be ignored.

Introduced a SimpleDataHolderBean to hold a hashmap for adding any
header. As with this fix though we can add any header, only
static/hard-coded values could be associated.

The rabbitmq AMQP basic properties constant keys should not
have dot or hyphen in their prefixes. This gives problem in trying to
retrieve the value due to fix of CAMEL-15394. Changed to underscore.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by omarsmak — APPROVED** [review]

**Comment by rgannu** [comment]
@oscerd/@davsclaus,
 As part of this PR I created a file `components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/SimpleDataHolderBean.java`  and this bean class is missing in the `[camel-3.6.0](https://github.com/apache/camel/tree/camel-3.6.0/components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq)` and in the `[master](https://github.com/apache/camel/tree/master/components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq)`

**Comment by oscerd** [comment]
It has been removed https://github.com/apache/camel/commit/d376711c170500364025064799d8fcf6907c2fde#diff-b2917cb1b72d2ff1600107b5fd43fcd873c1b2dd8bcc7cb165259b3b3782d410

**Comment by rgannu** [comment]
> It has been removed [d376711#diff-b2917cb1b72d2ff1600107b5fd43fcd873c1b2dd8bcc7cb165259b3b3782d410](https://github.com/apache/camel/commit/d376711c170500364025064799d8fcf6907c2fde#diff-b2917cb1b72d2ff1600107b5fd43fcd873c1b2dd8bcc7cb165259b3b3782d410)

ok. I wasn't aware of that.. 
From sink connector json configuration, how do I pass in the map?
I couldn't do that with the following configuration.. 

```
    "camel.sink.endpoint.additionalProperties": "#bean:addProperties",
    "camel.beans.addProperties": "#class:java.util.HashMap",
    "camel.beans.addProperties[CamelRabbitmqContentType]": "${file:/secrets/amqp.properties:analytics.content.type}",
    "camel.beans.addProperties[CamelRabbitmqContentEncoding]": "${file:/secrets/amqp.properties:analytics.content.encoding}",
    "camel.beans.addProperties[CamelRabbitmqAppId]": "${file:/secrets/amqp.properties:analytics.app.id}",

    "camel.sink.endpoint.additionalHeaders": "#bean:addHeaders",
    "camel.beans.addHeaders": "#class:java.util.HashMap",
    "camel.beans.addHeaders[MSG_TYPE]": "${file:/secrets/amqp.properties:analytics.msg.type}",
    "camel.beans.addHeaders[MSG_ORIGINATOR]": "${file:/secrets/amqp.properties:analytics.msg.originator}",
    "camel.beans.addHeaders[DESTINATION]": "${file:/secrets/amqp.properties:analytics.destination}",

```

It is not getting set.. Something that I miss ?

**Comment by rgannu** [comment]
@oscerd / @davsclaus, Could you please let me know how I can set the HashMap entries via sink connector configuration?

I have tried these
1. The map is empty.. 
```
    "camel.sink.endpoint.additionalHeaders": "#bean:addHeaders",
    "camel.beans.addHeaders": "#class:java.util.HashMap",
    "camel.beans.addHeaders[MSG_TYPE]": "${file:/secrets/amqp.properties:analytics.msg.type}",
    "camel.beans.addHeaders[MSG_ORIGINATOR]": "${file:/secrets/amqp.properties:analytics.msg.originator}",
    "camel.beans.addHeaders[DESTINATION]": "${file:/secrets/amqp.properties:analytics.destination}",
```

2. I also tried by having my own class which extends from HashMap. Still only empty map is going in..
```
package aero.unifly.analytics.bean;

public class SimpleDataHolderBean extends java.util.HashMap<String, Object> {
}
```
```
    "camel.sink.endpoint.additionalHeaders": "#bean:addHeaders",
    "camel.beans.addHeaders": "#class:aero.unifly.analytics.bean.SimpleDataHolderBean",
    "camel.beans.addHeaders[MSG_TYPE]": "${file:/secrets/amqp.properties:analytics.msg.type}",
    "camel.beans.addHeaders[MSG_ORIGINATOR]": "${file:/secrets/amqp.properties:analytics.msg.originator}",
    "camel.beans.addHeaders[DESTINATION]": "${file:/secrets/amqp.properties:analytics.destination}",
```

3. When I do not have the `#class`, I get error `No bean could be found in the registry for: addHeaders of type: java.util.Map`
```
    "camel.sink.endpoint.additionalHeaders": "#bean:addHeaders",
    "camel.beans.addHeaders[MSG_TYPE]": "${file:/secrets/amqp.properties:analytics.msg.type}",
    "camel.beans.addHeaders[MSG_ORIGINATOR]": "${file:/secrets/amqp.properties:analytics.msg.originator}",
    "camel.beans.addHeaders[DESTINATION]": "${file:/secrets/amqp.properties:analytics.destination}",
```

4.
Test case I am able to set the map in the camel context and use
```
    @Override
    protected CamelContext createCamelContext() throws Exception {
        CamelContext context = super.createCamelContext();

        myMap = new HashMap<>();
        myMap.put("k1", "v1");
        myMap.put("k2", 1L);

        context.getRegistry().bind("myMap", myMap);

        return context;
    }

    @Test
    public void testResolveParameter() throws Exception {
        @SuppressWarnings("unchecked")
        Map<String, Object> mapGot = EndpointHelper.resolveParameter(context, "#myMap", Map.class);
        assertSame(myMap, mapGot);
    }
```

Please let me know how I need to set the Map via the Connector Configuration.

Thanks and Kind Regards
Ganesh

**Comment by oscerd** [comment]
What you're trying to do is a bit tricky, btw you can do in the following way: 
1. Create an archetype starting from the original connector: https://camel.apache.org/camel-kafka-connector/latest/archetypes.html
2. Add the bean you want, for example the SimpleDataHolderBean in the generated project
3. Repackage the connector as normal connector and deploy it
4. Use the bean by referencing the class.

**Comment by rgannu** [comment]
> What you're trying to do is a bit tricky, btw you can do in the following way:
> 
> 1. Create an archetype starting from the original connector: https://camel.apache.org/camel-kafka-connector/latest/archetypes.html
> 2. Add the bean you want, for example the SimpleDataHolderBean in the generated project
> 3. Repackage the connector as normal connector and deploy it
> 4. Use the bean by referencing the class.

Thanks @oscerd .. 
I thought this is what I tried in step 2 ? Or am i missing something?

**Comment by oscerd** [comment]
I don't know if you repackage the connector or you used the archetype, in your steps it's not reported, and by the way this is not related to camel, but to ckc, so this is not the correct place to discuss.

**Comment by oscerd** [comment]
You can do exactly as in your PR, in the archetype add

```
package org.apache.camel.component.rabbitmq;

import java.util.HashMap;
import java.util.Map;

public class SimpleDataHolderBean {
    private Map<String, Object> mapData;

    public SimpleDataHolderBean() {
        this.mapData = new HashMap<>();
    }

    public Map<String, Object> getMapData() {
        return mapData;
    }

    public void setMapData(Map<String, Object> mapData) {
        this.mapData = mapData;
    }

    @Override
    public String toString() {
        return "SimpleDataHolderBean{" +
               "mapData=" + mapData +
               '}';
    }
}
```

and use it as class.

**Comment by oscerd** [comment]
Or at least this is what you were doing originally.

**Comment by rgannu** [comment]
> Or at least this is what you were doing originally.

Thanks a lot. Will try it out as suggested...

**Pull request merged**
