### PR TITLE
CAMEL-16717: Base commit for Huawei Cloud IAM Component

### PR DESCRIPTION
**Pull request by hokutor**
JIRA - https://issues.apache.org/jira/browse/CAMEL-16717

Huawei Cloud's Identity and Access Management (IAM) enables you to easily manage users and control their access to Huawei Cloud services and resources. Refer to https://www.huaweicloud.com/intl/en-us/product/iam.html for more information.

This PR contains the Camel Component for integrating with existing users in the cloud. (created via the Huawei Cloud web console)

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by hokutor** [comment]
@davsclaus Some changes that were made to the documentation in this PR were reverted in this Regen commit (https://github.com/apache/camel/commit/daf5c6058b952850a8fc419fbf2fa5ac84050983). The doc title of every component was changed, and the component-header of the IAM component was also changed in the Regen commit. Is there any way to not have the changes be reverted during the regen stage? Thanks

**Comment by oscerd** [comment]
There is a condition missing in the prepare catalog mojo

**Comment by hokutor** [comment]
@oscerd Thanks for your comment. Is there something that I could do to update the prepare catalog mojo so it fixes this issue?

**Comment by oscerd** [comment]
It should be fixed now.

**Comment by oscerd** [comment]
There is a new issue about documentation of huawei components btw https://issues.apache.org/jira/browse/CAMEL-16723

**Pull request merged**
