### PR TITLE
RFC: Should we have AI in Camel JBang?

### PR DESCRIPTION
**Pull request by orpiske**
How it works:
[asciicast](https://asciinema.org/a/664711)

### CODE REVIEW

**Comment by orpiske** [comment]
Obs.: this short demo uses a true open source model (granite-code, Apache 2.0 licensed) running locally using Ollama (also open source).

**Comment by davsclaus** [comment]
You can make this as a plugin to camel-jbang (see the generate plugin)

**Comment by orpiske** [comment]
> You can make this as a plugin to camel-jbang (see the generate plugin)

Thanks! That sounds like a much better approach. I'll explore it.

**Comment by orpiske** [comment]
I am working on this idea as a plugin in a separate repository ... for now. 

Let's close this one. Thanks!

**Pull request closed without merging**
