### PR TITLE
Camel 13667

### PR DESCRIPTION
**Pull request by cblamauer**
As discussed in https://issues.apache.org/jira/browse/CAMEL-13667, I created a pull request (for camel-2.23.x).

### CODE REVIEW

**Comment by oscerd** [comment]
Merging stuff not on master as first step, or at least on camel-2.x, can create problem, like forgetting to push the fix on the newer branches

**Comment by davsclaus** [comment]
I think as 2.23.x branch and 2.x branch are very identical, we can then use this PR for all the 2.x branches.

But for master then camel-core is now in core/camel-core. And some of those util/helper classes are now in core/camel-util - so for that we would need a new PR for master

**Comment by oscerd** [comment]
Fine for me. I can merge it tomorrow if we all agree

**Comment by cblamauer** [comment]
I have created 2 separate PRs for 2.x & master:
2.x: https://github.com/apache/camel/pull/2989
master: https://github.com/apache/camel/pull/2990

**Comment by oscerd** [comment]
Merged on 2.23.x, thanks

**Pull request closed without merging**
