### PR TITLE
CAMEL-17258 - added support for changing length of tracing groups

### PR DESCRIPTION
**Pull request by bvn13**

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
There are too many changes in key APIs like Route etc which should NOT be done.

I suggest you do a change ONLY on DefaultTracer to implement being able to configure the tracing output pattern.

Then we can afterwards look at a way to configure this nicer if needed.

**Comment by bvn13** [comment]
Ok, Claus, I'll rewrite it.

**Comment by bvn13** [comment]
@davsclaus What do you think about applying parameters per route? Should I implement it like I did in this Pull Request? Or should I add parameters and getters/setters only for the whole DefaultTracer without looking back at whether it will be inconvenient to use in Java DSL for instance?

When I did prepare this PR I added only 2 params and setters first. But when I started to check how to use it in Java DSL in test, I saw that I was not able to set different groups length for separated routes. The each next route (from(...)) rewrote the previous one. Then I applied a refactoring to add capability for storing groups length per each route separately.

So... What tier of code do you wait me to implement?

**Comment by davsclaus** [comment]
only on default tracer - its only intended for development / troubleshooting, and we should not make it invasive into the DSL / camel-core - there are already alot of configuration options etc and ways to do things in Camel - we need to keep things simple.

**Comment by davsclaus** [comment]
I was working on the tracer anyway with the source line number thingy.

So I added config for the trace logging format 
https://github.com/apache/camel/commit/20bf274946fecf2da9791ddd55ee5d136c3ec05b

You are welcome to try it out, and also if you want to add unit test, or have ideas to improve it, then feedback and PRs is welcome

**Pull request closed without merging**
