### PR TITLE
CAMEL-16280: NettyEndpointUriFactory#buildUri() not compatible with Netty endpoint URL

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.apache.org/jira/browse/CAMEL-16280

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
LGTM, @davsclaus I think we need to add a note on the migration guide too.

**Comment by tadayosi** [comment]
@oscerd By the way, this type of endpoint declaration never got deployed prior to this fix, so probably changing the syntax to `netty:protocol://host:port` doesn't have any impact on users' applications.
```java
from("netty:tcp:localhost:9999")
```

**Comment by oscerd** [comment]
Yes, just to track the change.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Ah yeah netty and netty-http has this special thing by requiring the double slash.

@tadayosi you are welcome to look at camel-netty-http and build a similar unit test and fix if we have the same problem there.

**Comment by davsclaus** [comment]
On another thought then I can't remember why we require the double slash, most components dont do this.

**Comment by tadayosi** [comment]
@davsclaus camel-netty-http is already covered in this pull req ;-)

**Pull request merged**
