### PR TITLE
Add information to be logged about underlying exception on Object -> …

### PR DESCRIPTION
**Pull request by elomonosov**
…DBObject conversion

### CODE REVIEW

**Comment by oscerd** [comment]
Please open your PR against master. We will backport in case we evaluate it is useful for the project.

Thanks

**Comment by davsclaus** [comment]
Yeah against master is preferred. The the commiter will backport. 

However this is a useful change I think for 2.18.x also, so @oscerd you can switch to 2.18.x branch and merge this PR (and do a --rebase afterwards) and then switch to master and cherry pick it there also.

**Comment by davsclaus** [comment]
Also we prefer the git commit message has a link to a CAMEL-NNNN ticket in JIRA, if there is a corresponding ticket.

**Comment by oscerd** [comment]
Thanks. The PR has been merged. Can you close the PR?

**Comment by elomonosov** [comment]
Thank you! I'm sorry for all the mistakes, I will not repeat it.

**Pull request closed without merging**
