### PR TITLE
CAMEL-11860: camel-olingo4- Upgrade to olingo 4.4

### PR DESCRIPTION
**Pull request by vrlgohel**
Fix for issue: https://issues.apache.org/jira/browse/CAMEL-11860

Do we really need to set any baseUri here ? It works fine with 'null' as well, but i would avoid doing that. Guys, do we need to set some specific baseUri for this ? Let me know.

### CODE REVIEW

**Comment by vrlgohel** [comment]
Good point! I will try implementing the suggested changes. However, there's already a 'serviceUri', we set.  So, if i am understanding this right, are you suggesting this can be used as the baseUri ?  Maybe we can have something like this ?
private String serviceUri = "/".

**Comment by davsclaus** [comment]
Do we know what exactly is the meaning of the baseUri? And the difference it has to serviceUrl. eg can we find more details in the dropbox api / documentation about these?

**Comment by dmvolod** [comment]
I think it's suitable to pass null as baseUri, but from source code point of view https://github.com/apache/olingo-odata4/blob/38f77daa5c555af2012449e1f090a0395bd7a883/lib/server-core/src/main/java/org/apache/olingo/server/core/uri/parser/Parser.java#L173 this is a full service URI starting with http and finishing with query parameters. It's would be good to pass serviceUri variable as baseUri parameter to the parseUri method.

**Comment by vrlgohel** [comment]
Hi Dmitry,

Thank you for the pointers.  I actually went through that code (or similar) while trying to make the changes and then wasn't sure if passing simply a 'null'  would be fine. It looked ERROR prone. 
You make a good point on 'serviceUri', so, probably as i understand, we can directly have the setServiceUri as the 'baseUri'. But, as Claus suggested, i would still like to do more research on the 'serviceUri' and 'baseUri' differences in the Api's or code and see what is the difference.

**Comment by vrlgohel** [comment]
Hi Claus, 
As per Dmitry's suggestions, i have pushed the commit with changes. I believe we can also include this on 2.20 than wait for next one. Let me know.

**Comment by vrlgohel** [comment]
Adding to it, i also do not see any issues with spring-boot & karaf iTests.

**Comment by vrlgohel** [comment]
Hi Dmitry,
Okay,  so i will need to check further. But i did set the serviceUri as the baseUri.  I probably can't think of more flaws presently. What exactly can be the problem here ? It is affected because we defined a static serviceUri ?

**Comment by dmvolod** [comment]
Yes, it's related to static changes.

**Comment by vrlgohel** [comment]
Hi Dmitry, 
I have pushed commit with latest changes. As to what i can understand from the code and some docs, there isn't a clear mentioning on what the baseUri is introduced for or does it replace the serviceUri. To me, it looks the serviceUri is the baseUri. 
Do you see any issues with the latest code i pushed ?

**Comment by dmvolod** [comment]
Hi Viral!

Looks good. I think the baseUri introduced for the some exotic cases, which can be occurred very rearly.

**Comment by vrlgohel** [comment]
Thanks Dmitry for checking this. 
@davsclaus , can we merge this ? if there are no further changes required ?

**Comment by davsclaus** [comment]
@vrlgohel yeah +1

**Comment by oscerd** [comment]
I'm gonna merge this

**Comment by oscerd** [comment]
@vrlgohel Thanks, the PR has been merged. Can you close this?

**Comment by vrlgohel** [comment]
Thanks a lot Andrea!

**Pull request closed without merging**
