### PR TITLE
DynamoDB Stream Consumer

### PR DESCRIPTION
**Pull request by CandleCandle**
DynamoDB Streams offer a change feed from your dynamoDB.

While the API calls are very similar to the Kinesis API calls, the use of shards is quite different; in Kinesis they are intended to be parallel, to increase throughput. In DynamoDB Streams, shards are sequential, intended to be walked one at a time to get all the changes available.

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you log a JIRA ticket about this new aws component being added to camel-aws

**Comment by davsclaus** [comment]
The code has been merged, do you mind close this PR

**Comment by CandleCandle** [comment]
Closed; Merged. Noted the jira request.

**Comment by CandleCandle** [comment]
https://issues.apache.org/jira/browse/CAMEL-9443

**Pull request closed without merging**
