### PR TITLE
Providing abbreviation for the default value

### PR DESCRIPTION
**Pull request by NiteshKoushik**
This PR has been created based on the PR #4236 , Providing abbreviation for the default value

- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by davsclaus** [comment]
You always need to make PR against master, not other branches

**Review by oscerd — APPROVED** [review]

**Comment by NiteshKoushik** [comment]
Hello @davsclaus , should I do the changes again or is it fine.

**Comment by davsclaus** [comment]
This PR is agains apache:release/3.5.0 it should be agains master instead.

**Comment by NiteshKoushik** [comment]
I have done the changes in master, in the PR https://github.com/apache/camel/pull/4329

**Pull request closed without merging**
