### PR TITLE
CAMEL-10510: Change HL7AcknowledgementGenerator to set CamelMllpAckno…

### PR DESCRIPTION
**Pull request by hqstevenson**
…wledgement exchange property instead of message header

### CODE REVIEW

**Comment by davsclaus** [comment]
This PR causes unit test error for me on master branch
```
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 31.01 sec <<< FAILURE! - in org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest
testAcknowledgementDeliveryFailure(org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest)  Time elapsed: 10.206 sec  <<< FAILURE!
java.lang.AssertionError: mock://on-failure-only Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest.testAcknowledgementDeliveryFailure(MllpTcpServerConsumerAcknowledgementTest.java:173)

testAcknowledgementDeliveryFailure(org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest)  Time elapsed: 10.209 sec  <<< FAILURE!
java.lang.AssertionError: mock://on-failure-only Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest.testAcknowledgementDeliveryFailure(MllpTcpServerConsumerAcknowledgementTest.java:173)

testAcknowledgementDeliveryFailure(org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest)  Time elapsed: 10.259 sec  <<< FAILURE!
java.lang.AssertionError: mock://on-failure-only Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest.testAcknowledgementDeliveryFailure(MllpTcpServerConsumerAcknowledgementTest.java:173)

```

**Comment by davsclaus** [comment]
I ran this test 2 times and it failed both times

**Comment by davsclaus** [comment]
I see this in the logs
```
********************************************************************************
2016-11-22 20:50:51,005 [main           ] INFO  verConsumerAcknowledgementTest - Testing: testAcknowledgementDeliveryFailure(org.apache.camel.component.mllp.MllpTcpServerConsumerAcknowledgementTest)
2016-11-22 20:50:51,005 [main           ] INFO  verConsumerAcknowledgementTest - ********************************************************************************
2016-11-22 20:50:51,202 [main           ] INFO  DefaultTypeConverter           - Loaded 192 type converters
2016-11-22 20:50:51,203 [main           ] INFO  AvailablePortFinder            - getNextAvailable(1104) -> 1104
2016-11-22 20:50:51,204 [main           ] INFO  DefaultCamelContext            - Apache Camel 2.19.0-SNAPSHOT (CamelContext: MllpTcpServerConsumerAcknowledgementTest) is starting
2016-11-22 20:50:51,204 [main           ] INFO  DefaultCamelContext            - MDC logging is enabled on CamelContext: MllpTcpServerConsumerAcknowledgementTest
2016-11-22 20:50:51,204 [main           ] INFO  DefaultManagementStrategy      - JMX is disabled
2016-11-22 20:50:51,221 [main           ] INFO  DefaultCamelContext            - StreamCaching is not in use. If using streams then its recommended to enable stream caching. See more details at http://camel.apache.org/stream-caching.html
2016-11-22 20:50:51,222 [main           ] INFO  DefaultCamelContext            - Route: mllp-test-receiver-route started and consuming from: mllp://localhost:1104?autoAck=true&connectTimeout=500&receiveTimeout=5000
2016-11-22 20:50:51,223 [main           ] INFO  DefaultCamelContext            - Total 1 routes, of which 1 are started.
2016-11-22 20:50:51,223 [main           ] INFO  DefaultCamelContext            - Apache Camel 2.19.0-SNAPSHOT (CamelContext: MllpTcpServerConsumerAcknowledgementTest) started in 0.019 seconds
2016-11-22 20:50:51,224 [main           ] WARN  MllpClientResource             - Closing TCP connection
2016-11-22 20:50:51,224 [main           ] INFO  MockEndpoint                   - Asserting: mock://on-failure-only is satisfied
2016-11-22 20:50:51,325 [/127.0.0.1:1104] ERROR MllpTcpServerConsumer          - Exception accepting new connection - retrying
java.net.SocketException: Invalid argument
	at java.net.PlainSocketImpl.socketSetOption(Native Method) ~[?:1.8.0_31]
	at java.net.AbstractPlainSocketImpl.setOption(AbstractPlainSocketImpl.java:275) ~[?:1.8.0_31]
	at java.net.Socket.setKeepAlive(Socket.java:1310) ~[?:1.8.0_31]
	at org.apache.camel.component.mllp.MllpTcpServerConsumer$ClientSocketThread.<init>(MllpTcpServerConsumer.java:334) ~[classes/:?]
	at org.apache.camel.component.mllp.MllpTcpServerConsumer$ServerSocketThread.run(MllpTcpServerConsumer.java:247) [classes/:?]
2016-11-22 20:51:01,227 [main           ] INFO  verConsumerAcknowledgementTest - 
```

**Comment by davsclaus** [comment]
Ah it may be a problem that was there before, without the PR that same test fails also on my laptop. 

I guess its a flaky one on my side, not sure if others see that same error ?

**Comment by hqstevenson** [comment]
That is very strange - a socket exception claiming it's an invalid argument to Socket.setKeepAlive, when it's a boolean argument.  I'm passing in a boolean, so I'm not sure what's up with that.  I'm using 1.8.0_111 - could this be a JDK thing?

**Comment by davsclaus** [comment]
Yeah not sure, the CI servers haven reported that kind of error, I am on

```
davsclaus:/Users/davsclaus/workspace/camel/components/camel-mllp (master)/$ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by davsclaus** [comment]
But its not related to this PR so lets close this

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
