### PR TITLE
CAMEL-20253: camel-jbang - Add support for jolokia 2.x

### PR DESCRIPTION
**Pull request by kulagaIA**
# Description
Migration guide https://jolokia.org/migration.html does not specify api change, so org.apache.camel.dsl.jbang.core.commands.process.Jolokia was left as it is.
JolokiaHttpRequestHandlerSupport is expected to be made more pluggable in the future.

# Tracking
https://issues.apache.org/jira/browse/CAMEL-20253

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you remove the `@DevConsole` as its not needed

**Comment by kulagaIA** [comment]
> Can you remove the `@DevConsole` as its not needed

Indeed it is not needed, thanks, removed it

**Pull request merged**
