### PR TITLE
Adding support for defining custom swagger parameters

### PR DESCRIPTION
**Pull request by sebi-hgdata**
Hey,
   This PR adds support for defining swagger custom operation parameters in rest routes. 
    It has the options for specifying every swagger parameter option.

   An example route:
  rest("products")
                        .get("{url}").description("queries products by url")
                        .produces("application/json").outTypeList(Product.class)
                       .restParam().name("startDate").required(true).description("first verified date").type("query").endParam()
                        .restParam().name("headerName").required(false).description("some header desc").type("header").endParam()
                        .route().processRef("validator").process(proc)
                        .marshal().json(JsonLibrary.Jackson).endRest();

 This will add 1 query param  and one header param  in the swagger json.

Thanks

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR but the code does not compile in camel-spring. The JAXB changes you did to the model broke that part.

You would need to do a full build to ensure it all works

mvn clean install -Dtest=false

Also remember to add your model classes to the jaxb.index file.

**Comment by davsclaus** [comment]
And please create or refer to an JIRA ticket about this.

**Comment by sebi-hgdata** [comment]
Will do

Thanks

**Comment by davsclaus** [comment]
Also it would be great if you could run a checkstyle so the code format is correct

mvn compile -Psourcecheck

You can just run this in the camel-core module.

**Comment by davsclaus** [comment]
And we do not accept any `@author` tags in the source code. The source code should be _nameless_

**Comment by davsclaus** [comment]
But its a great addition to allow users to document those parameters so they are in the swagger model.

I wonder for the type if we could specify that using an enum so it becomes more type safe, eg so people can select among: header, query, and what else is possible to use. So its not just a plain string.

**Comment by sebi-hgdata** [comment]
There was an issue already logged for something like this https://issues.apache.org/jira/browse/CAMEL-7936

Anyway, I added the param type enum, fixed style issue and added  model classes to  jaxb.index. 

The only issue is that I could not build the spring module and I cant figure out what is the issue. I keep getting  the error :
"An Ant BuildException has occured: Error starting ap: java.lang.AssertionError: java.lang.ClassCastException: com.sun.tools.javac.api.JavacTrees cannot be cast to com.sun.source.util.Trees -> [Help 1] "

I'm on ubuntu and I tried different jdk, ant and maven. Is there something more that I need to set up?

**Comment by davsclaus** [comment]
Yeah unfortunately that error is not very informative - we have got that too in the past. I am afraid you would need some trial and error in the jaxb model classes. Usually related to references to others / list etc. Take a look at how the others working are done and try to do similar.

**Comment by sebi-hgdata** [comment]
Last commit fixes the issue. Let me know if there is anything else to be done.

**Comment by davsclaus** [comment]
Thanks for the PR. I have applied it to master branch.

I found some things to fix and I added this as TODO in the rest-dsl in the org.apache.camel.model.rest package in camel-core.

Could you take a look at that and if possible create a new PR with the fixes needed for that.

Also we would need some unit tests in camel-spring that tests that the XML DSL for this new param stuff works as well. As people should be able to use either java or xml dsl and it should be the same model at runtime.

**Comment by davsclaus** [comment]
Thanks for this PR. The code has been merged. Do you mind closing this.

**Pull request closed without merging**
