### PR TITLE
CAMEL-10016: Fix Crypto Syntax

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by oscerd** [comment]
Here:

https://github.com/apache/camel/blob/master/components/camel-crypto/src/main/java/org/apache/camel/component/crypto/DigitalSignatureConfiguration.java#L42

We need to use UriPath instead of UriParam.

Can you close this PR? If you want you can open another one with the fix suggested :-)

**Comment by oscerd** [comment]
What I mean is that we need to change @UriParam with @UriPath on name and then use "crypto:cryptoOperation:name" as it is now in the codebase.

Sorry I wrote a bit fast on the last comment :-)

**Comment by oscerd** [comment]
@apupier are you going to update this PR? :-)

**Comment by davsclaus** [comment]
@oscerd can you fix this so we will get this into the code base

**Comment by apupier** [comment]
sorry I won't be able to do it until next week.

**Comment by oscerd** [comment]
@davsclaus @apupier sure thing :-)

**Pull request closed without merging**
