### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by oscerd**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by oscerd** [comment]
This is the regen with mvn clean install -DskipTests after @gnodet commit.

**Review by gnodet — CHANGES_REQUESTED** [review]
There's a problem with this commit.  All the symlinks are removed, maybe because when you checked out, the files did not exist or something like that.  

I've added a full Regen script in `etc/scripts/regen.sh` and ran it a bunch of times this afternoon to make sure everything was clean.

**Comment by oscerd** [comment]
I rebased from main and then run min clean install. I also tried with git clean -dfX

**Comment by oscerd** [comment]
I'm closing this, and I'll try the script

**Pull request closed without merging**
