### PR TITLE
faq dirrectory moved to docs/user-manual/modules/ROOT/pages/, addient…  … …ries to the FAQ in the user-manual-nav.adoc.template, xml-configuration.adoc link issues fixed

### PR DESCRIPTION
**Pull request by Nayananga**
Hi all how can I auto generate user-manual-nav.adoc.template`s nav.adoc file?

### CODE REVIEW

**Comment by zregvart** [comment]
We're using [gulp-inject](https://github.com/klei/gulp-inject) in that `user-manual-nav.adoc.template` so anything between  and `<!-- endinject -->` will be replaced by the code here:

https://github.com/apache/camel/blob/5fbc859c822674b504cfe278f50bb1d99d35b0a4/docs/gulpfile.js#L113-L121

So the changes to `user-manual-nav.adoc.template` need to go at the very end of the file, after the last `<!-- endinject -->`.

I'm still unsure if we would like the FAQ to be in a separate module, I think we're fine as it is for now, perhaps in the future this might change.

**Comment by Nayananga** [comment]
Thank you Mr.Zoran, are these changes acceptable?

**Comment by zregvart** [comment]
@Nayananga sorry for not making this clearer the FAQ entries in `user-manual-nav.adoc.template` that were added are between `<!-- eips:adoc -->` and `<!-- endinject -->`, anything placed in there will be replaced when the build runs. You can check this by running `mvn package` from the `docs` directory, the resulting `docs/user-manual/modules/ROOT/nav.adoc` will not contain those FAQ entries.
They need to be placed at the end of the file, after the last `<!-- endinject -->`.

**Comment by Nayananga** [comment]
Hello Mr.Zoran I made above change, any suggestions?

**Comment by Nayananga** [comment]
may I proceed with other link errors like this?

**Comment by zregvart** [comment]
Thanks! 

> may I proceed with other link errors like this?

Yes, I think using `xref` will help. I'll trigger a new build of the staging website manually.

**Pull request merged**
