### PR TITLE
Move protobuf and salesforce component maven versions to the parent pom

### PR DESCRIPTION
**Pull request by dmvolod**
@zregvart please look at this PR, as junit-toolbox version inserted in parent pom as more than one components are using it now. Thank you.

### CODE REVIEW

**Comment by zregvart** [comment]
@dmvolod thank you that looks good 👍

**Comment by dmvolod** [comment]
thx, please merge PR.

**Comment by zregvart** [comment]
@dmvolod thank you for this 🥇, I was mistaken in thinking that you had commit bit 😳, it has been merged to `master` you can close this 👍

**Comment by dmvolod** [comment]
Thanks, PR closed

**Pull request closed without merging**
