### PR TITLE
Moved WebSocketStore and NodeSynchronization from the Endpoint to the…

### PR DESCRIPTION
**Pull request by tonswieb**
https://issues.apache.org/jira/browse/CAMEL-9348

### CODE REVIEW

**Comment by davsclaus** [comment]
Hi there is 3 PR's for this.

Which one should we use? I assume it would be pull 690 which has the highest number?

**Comment by tonswieb** [comment]
Hi Claus,

I created a PR for master (2.17), 2.16 branch and 2.15 branch. 2.17 and 2.16 are the same I believe. The 2.15 PR is different due to change in implementation.

Should I only have created 1 PR on master?

Regards, Ton


Verstuurd vanaf mijn iPhone

**Comment by davsclaus** [comment]
Yes only on master.

The Camel team decide whether to backport or not, and if so we cherry pick from master.

**Comment by tonswieb** [comment]
Ok. Good to know.
The first PR was on master. The second on 2.15 en the third on 2.16 which I cherry picked.

Verstuurd vanaf mijn iPhone

**Comment by davsclaus** [comment]
Thanks can you close this PR

**Pull request closed without merging**
