### PR TITLE
CAMEL-16698: do log when unable to determine docker availability

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
Please don't merge it yet. It may not be enough to solve the problems on CAMEL-16698, and I am opening it to collect more feedback.

**Review by oscerd — APPROVED** [review]

**Comment by gnodet** [comment]
I don't really see any change in the maven output:
```
➜  camel-couchbase git:(62058128e37) mvn install
[INFO] BuildTimeEventSpy is registered.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.camel:camel-couchbase >------------------
[INFO] Building Camel :: Couchbase 3.11.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.4.1:enforce (enforce-maven) @ camel-couchbase ---
[INFO] 
[INFO] --- impsort-maven-plugin:1.6.0:sort (sort-imports) @ camel-couchbase ---
[INFO] Processed 15 files in 00:00.022 (Already Sorted: 15, Needed Sorting: 0)
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.2:check (default-cli) @ camel-couchbase ---
[INFO] Starting audit...
Audit done.
[INFO] You have 0 Checkstyle violations.
[INFO] 
[INFO] --- camel-bundle-plugin:3.11.0-SNAPSHOT:cleanVersions (versions) @ camel-couchbase ---
[INFO] 
[INFO] --- formatter-maven-plugin:2.14.0:format (format) @ camel-couchbase ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Formatting is skipped for types: JavaScript, HTML, CSS
[INFO] Number of files to be formatted: 15
[INFO] Successfully formatted:          0 file(s)
[INFO] Fail to format:                  0 file(s)
[INFO] Skipped:                         15 file(s)
[INFO] Read only skipped:               0 file(s)
[INFO] Approximate time taken:          0s
[INFO] 
[INFO] --- build-helper-maven-plugin:3.2.0:add-source (default) @ camel-couchbase ---
[INFO] Source directory: /Users/gnodet/work/git/camel/components/camel-couchbase/src/generated/java added.
[INFO] 
[INFO] --- build-helper-maven-plugin:3.2.0:add-resource (default) @ camel-couchbase ---
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:resources (default-resources) @ camel-couchbase ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] skip non existing resourceDirectory /Users/gnodet/work/git/camel/components/camel-couchbase/src/main/resources
[INFO] Copying 6 resources
[INFO] 
[INFO] --- flatten-maven-plugin:1.2.5:flatten (default-cli) @ camel-couchbase ---
[INFO] Generating flattened POM of project org.apache.camel:camel-couchbase:jar:3.11.0-SNAPSHOT...
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ camel-couchbase ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- camel-package-maven-plugin:3.11.0-SNAPSHOT:generate (generate) @ camel-couchbase ---
[INFO] Skipping generation, everything is up to date.
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (recompile) @ camel-couchbase ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:3.2.0:testResources (default-testResources) @ camel-couchbase ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Using 'UTF-8' encoding to copy filtered properties files.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ camel-couchbase ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 8 source files to /Users/gnodet/work/git/camel/components/camel-couchbase/target/test-classes
[WARNING] [options] bootstrap class path not set in conjunction with -source 8
[WARNING] /Users/gnodet/work/git/camel/components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java:[39,68] [deprecation] getService() in CouchbaseServiceFactory has been deprecated
[INFO] 
[INFO] --- maven-surefire-plugin:3.0.0-M5:test (default-test) @ camel-couchbase ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.component.couchbase.CouchbaseComponentTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.555 s - in org.apache.camel.component.couchbase.CouchbaseComponentTest
[INFO] Running org.apache.camel.component.couchbase.CouchbaseEndpointTest
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in org.apache.camel.component.couchbase.CouchbaseEndpointTest
[INFO] Running org.apache.camel.component.couchbase.CouchbaseProducerTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.752 s - in org.apache.camel.component.couchbase.CouchbaseProducerTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- camel-package-maven-plugin:3.11.0-SNAPSHOT:generate-postcompile (generate-postcompile) @ camel-couchbase ---
[INFO] Skipping generation, everything is up to date.
[INFO] 
[INFO] --- camel-bundle-plugin:3.11.0-SNAPSHOT:manifest (bundle-manifest) @ camel-couchbase ---
[INFO] Skipping manifest generation, everything is up to date.
[INFO] 
[INFO] --- maven-jar-plugin:3.2.0:jar (default-jar) @ camel-couchbase ---
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M4:integration-test (integration-test) @ camel-couchbase ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.0.0-M4:verify (integration-test) @ camel-couchbase ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ camel-couchbase ---
[INFO] Installing /Users/gnodet/work/git/camel/components/camel-couchbase/target/camel-couchbase-3.11.0-SNAPSHOT.jar to /Users/gnodet/.m2/repository/org/apache/camel/camel-couchbase/3.11.0-SNAPSHOT/camel-couchbase-3.11.0-SNAPSHOT.jar
[INFO] Installing /Users/gnodet/work/git/camel/components/camel-couchbase/target/camel-couchbase-3.11.0-SNAPSHOT.pom to /Users/gnodet/.m2/repository/org/apache/camel/camel-couchbase/3.11.0-SNAPSHOT/camel-couchbase-3.11.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.623 s
[INFO] Finished at: 2021-06-09T08:40:24+02:00
[INFO] ------------------------------------------------------------------------
➜
```

**Comment by orpiske** [comment]
@gnodet there is a log file created by failsafe. Within the component directory (ie.: `component/camel-couchbase`) there should be a file named `target/camel-couchbase-test.log` which should display something like: 

```
2021-06-09 07:43:04,569 [main           ] ERROR ContainerEnvironmentUtil       - Failed to evaluate whether the docker environment is available:  <reason > 
<stack trace>
...
2021-06-09 07:43:04,572 [main           ] WARN  ContainerEnvironmentUtil       - Turning off container-based tests because docker does not seem to be working correctly
2021-06-09 07:43:04,573 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.RemoveMessagesIT is disabled because docker is not available
2021-06-09 07:43:04,577 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.ConsumeMessagesWithLimitIT is disabled because docker is not available
2021-06-09 07:43:04,579 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.ProduceMessagesSimpleIT is disabled because docker is not available
2021-06-09 07:43:04,581 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.ProduceMessagesWithAutoIDIT is disabled because docker is not available
```

Do you have that file?

**Comment by orpiske** [comment]
> > @gnodet there is a log file created by failsafe. Within the component directory (ie.: `component/camel-couchbase`) there should be a file named `target/camel-couchbase-test.log` which should display something like:
> > ```
> > 2021-06-09 07:43:04,569 [main           ] ERROR ContainerEnvironmentUtil       - Failed to evaluate whether the docker environment is available:  <reason > 
> > <stack trace>
> > ...
> > 2021-06-09 07:43:04,572 [main           ] WARN  ContainerEnvironmentUtil       - Turning off container-based tests because docker does not seem to be working correctly
> > 2021-06-09 07:43:04,573 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.RemoveMessagesIT is disabled because docker is not available
> > 2021-06-09 07:43:04,577 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.ConsumeMessagesWithLimitIT is disabled because docker is not available
> > 2021-06-09 07:43:04,579 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.ProduceMessagesSimpleIT is disabled because docker is not available
> > 2021-06-09 07:43:04,581 [main           ] WARN  ContainerService               - Test class org.apache.camel.component.couchbase.integration.ProduceMessagesWithAutoIDIT is disabled because docker is not available
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do you have that file?
> 
> Yes, you're right. The file is here and the reason `Could not find a valid Docker environment.` too. It seems not really intuitive to not have anything in the maven log somehow.

+1

> I wonder if we could have the tests flagged as if a junit assumption was not met (which is somewhat the case), the problem is that they are simply not listed at all.

1+. Currently the `ContainerService` inherits a `ExecutionCondition` to handle this, but this silent failure behavior could be improved.  I need to research what we could do here as I am not entirely sure I can use the assumption at that point.

**Comment by orpiske** [comment]
> It seems not really intuitive to not have anything in the maven log somehow.

I was hoping I could come up with a cleaner solution, but I wanted to avoid any more complex solution based on [TestExecutionListener ](https://github.com/junit-team/junit5/issues/2640#issuecomment-856876505) for now. 

So, what I end up doing is, I disabled the `redirectTestOutputToFile` and added and error message when Docker is not available.

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
Container-based tests were disabled because Docker is NOT available. Check the log files on target/failsafe-reports
Container-based tests were disabled because Docker is NOT available. Check the log files on target/failsafe-reports
Container-based tests were disabled because Docker is NOT available. Check the log files on target/failsafe-reports
Container-based tests were disabled because Docker is NOT available. Check the log files on target/failsafe-reports
```

**Comment by orpiske** [comment]
This one should be good to go.

**Pull request merged**
