### PR TITLE
CAMEL-15494 Document how to add Http/2 Protocol to camel-undertow

### PR DESCRIPTION
**Pull request by Gerry-Forde**
[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by Gerry-Forde** [comment]
@oscerd 

Can you please review this PR which documents the configuration of the HTTP/2 protocol for the Camel Undertow component.

Thanks,
Gerry

**Review by oscerd — CHANGES_REQUESTED** [review]
This branch is based on Camel 3, so probably this example is not accurate, can you please do the same but with the camel 3 material? Also, this seems a bit more an example extracted from some project. So probably in the documentation it could be enough to note the http2Enabled option and add a real example in camel-examples repository.

**Comment by Gerry-Forde** [comment]
@oscerd I have requested an example of the Camel 3 implementation to be created and will update this request in due course as you suggest - thank you for your feedback.

**Comment by oscerd** [comment]
I think we can close this and o

**Pull request closed without merging**
