### PR TITLE
CAMEL-21323: upgrade camel-http to 5.3

### PR DESCRIPTION
**Pull request by jonomorris**
# Description

1. We needed to set the uri-authority on the request via the `RequestValidateHost` request interceptor for the request-router that's been added to `Serverbootstrap`, and also the 'CanonicalHostName'. 

2. The default charset in `EntityUtils` has changed to UTF-8 from iso8859-1, and if we want to use iso8859-1 encoding we need to set the 'content-type' header, e.g. "text/plain;charset=iso8859-1".

3. HTTP 1.1 is now the default version in `Http1Config`, and this is set on http-requests.

# Target

- [x ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
There is even a 5.4 release I think. You are welcome to take a look at that after this PR is merged.

**Comment by jonomorris** [comment]
Looks like I don't have access to merge.

**Comment by davsclaus** [comment]
Hmm not sure what that requires, if you are in the ASF GH group which it seems if you hover mouse on your name. Maybe @oscerd can remember what it would need.

**Pull request merged**
