### PR TITLE
CAMEL-12982: Support RAW{} syntax in URISupport

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.apache.org/jira/browse/CAMEL-12982

Hi guys, please review it before merging it. I refactored the RAW handling part of the code a bit, so if we decide to support fancier syntax like `RAW[[[...]]]` and `RAWaaa...aaa` in the future, it should still serve such enhancements.

### CODE REVIEW

**Comment by tadayosi** [comment]
I'll take care of backporting to 2.24.0. Thanks.

**Comment by davsclaus** [comment]
@tadayosi there is a compile error in camel-catalog on master

**Comment by oscerd** [comment]
Do we want to revert?

**Comment by oscerd** [comment]
Reverted

**Comment by tadayosi** [comment]
My bad! I was so satisfied with passing tests for camel-core & camel-util that I totally forgot to run full build before sending it. Will fix the compile error soon.

**Pull request merged**
