### PR TITLE
Camel 19755

### PR DESCRIPTION
**Pull request by cziesman**
# Description

Provides a component for the Thymeleaf template engine.

# Target

main

# Tracking

CAMEL-19755

# Apache Camel coding standards and style

- [ X] I checked that each commit in the pull request has a meaningful subject line and body.

- [ X] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by orpiske — APPROVED** [review]
I looked briefly over it and it seemed OK. Still, I think it would be good to have more reviewers looking at this one.

**Comment by orpiske** [comment]
> I looked briefly over it and it seemed OK. Still, I think it would be good to have more reviewers looking at this one.

And, before I forget: thanks for your contribution!

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Thanks for this, I'm planning to integrate the PR this week.

**Comment by oscerd** [comment]
Merged. Thanks.

**Comment by davsclaus** [comment]
closing as merged

**Pull request closed without merging**
