### PR TITLE
Camel 10418, Deploy route with an error

### PR DESCRIPTION
**Pull request by Fabryprog**

### CODE REVIEW

**Comment by Fabryprog** [comment]
https://issues.apache.org/jira/browse/CAMEL-10418

**Comment by oscerd** [comment]
I don't think this is the right point to place this check. You're re-throwing the exception without really manage it. Not sure anyway. Lets wait for @davsclaus

**Comment by Fabryprog** [comment]
@oscerd it is the same code.... Today there is an implicit throw exception!!!!!

**Comment by oscerd** [comment]
I need to investigate a bit if it can be placed in deeper methods of the class.

**Comment by Fabryprog** [comment]
No problem, take your time!!!! ;-)

**Comment by Fabryprog** [comment]
@oscerd do you have any news?

**Comment by oscerd** [comment]
you're a bit eager. I'll merge it today.

**Comment by Fabryprog** [comment]
@oscerd, my company will pay me in relation to PR you will do! ;-) (I'm kidding)

**Comment by paoloantinori** [comment]
Hi please, check a different approach here: https://github.com/apache/camel/pull/1234

**Comment by oscerd** [comment]
Thanks to both @Fabryprog for spotting the problem and @paoloantinori for fixing it.

@Fabryprog can you close this PR? Maybe you can add some tests around this special cases.

**Pull request closed without merging**
