### PR TITLE
[CAMEL-9278] camel-undertow REST DSL support

### PR DESCRIPTION
**Pull request by jamesnetherton**

### CODE REVIEW

**Comment by davsclaus** [comment]
Yay thanks.

If I run all the tests with mvn clean install I get this one error at the end that only logs to the console
```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.603 sec <<< FAILURE! - in org.apache.camel.component.undertow.rest.RestUndertowHttpPostXmlJaxbPojoTest
testPostJaxbPojo(org.apache.camel.component.undertow.rest.RestUndertowHttpPostXmlJaxbPojoTest)  Time elapsed: 0.492 sec  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-davsclaus-air-63396-1447693695292-41-2][Message: <user name="Donald Duck" id="123"></user>]
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
	at org.xnio.BufferAllocator$2.allocate(BufferAllocator.java:57)
	at org.xnio.BufferAllocator$2.allocate(BufferAllocator.java:55)
	at org.xnio.ByteBufferSlicePool.allocate(ByteBufferSlicePool.java:143)
	at io.undertow.server.XnioByteBufferPool.<init>(XnioByteBufferPool.java:38)
	at org.apache.camel.component.undertow.UndertowProducer.process(UndertowProducer.java:80)
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:109)
	at org.apache.camel.processor.UnitOfWorkProducer.process(UnitOfWorkProducer.java:68)
	at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:412)
	at org.apache.camel.impl.ProducerCache$2.doInProducer(ProducerCache.java:380)
	at org.apache.camel.impl.ProducerCache.doInProducer(ProducerCache.java:270)
	at org.apache.camel.impl.ProducerCache.sendExchange(ProducerCache.java:380)
	at org.apache.camel.impl.ProducerCache.send(ProducerCache.java:221)
	at org.apache.camel.impl.DefaultProducerTemplate.send(DefaultProducerTemplate.java:124)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:163)
	at org.apache.camel.impl.DefaultProducerTemplate.sendBodyAndHeader(DefaultProducerTemplate.java:159)
	at org.apache.camel.component.undertow.rest.RestUndertowHttpPostXmlJaxbPojoTest.testPostJaxbPojo(RestUndertowHttpPostXmlJaxbPojoTest.java:35)


Results :

Tests in error:
  RestUndertowHttpPostXmlJaxbPojoTest.testPostJaxbPojo:35 » CamelExecution Excep...

Tests run: 42, Failures: 0, Errors: 1, Skipped: 0
```

I wonder if its running out of memory and the allocate cannot reserve the memory?

If I run the  test isolated then it works fine

**Comment by jamesnetherton** [comment]
Wonder if it's a regression of CAMEL-9195? From this commit:

https://github.com/apache/camel/commit/d01138809efed863aa3bb575b38078075cbe1a57

Maybe we should not be repeatedly creating XnioByteBufferPool?

**Comment by davsclaus** [comment]
Yeah I am not sure about the code either. 

Maybe if you could build an unit test that runs for a longer time and call the undertow consumer repeativly to see if a memory issue builds up and cause an OOME.

Likewise for the undertow producer.

Also maybe some of the jboss guys that developed undertow can take a peak at the code to advice us.

**Comment by jamesnetherton** [comment]
I'll close this PR for now.

I can only replicate the OOME in a Docker container where I restrict the container memory to 1GB or less.

I'm pretty sure this is the source of the problem:

https://github.com/apache/camel/blob/master/components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowProducer.java#L130

Allocating a huge ByteBufferSlicePool to every producer probably isn't what we want to do. The suite runs fine if I reduce the size of it.

I've sent a mail out to the undertow-dev mailing list and I'll follow up with another PR if and when I resolve the problem.

**Pull request closed without merging**
