### PR TITLE
camel-plc4x Implemented Plc4XPollingConsumer and some refactoring (CAMEL-18861)

### PR DESCRIPTION
**Pull request by SteinOv**
The main goal of this PR was to implement a PollingConsumer to add the ability of consecutive polling without stopping and starting the Consumer everytime. Additionally, I made some other improvements:
- Moved all connection responsibility to Plc4XEndpoint
- Improved behavior with autoReconnect=true. Before no Exchanges were created if there was no connection, now an Exchange is created with an empty map. So this can now be handled from the route.
- Removed usage of reflection from Endpoint and Producer tests (this fixed the issue that unit tests sometimes passed/failed incosistently)

Related to [this JIRA issue](https://issues.apache.org/jira/browse/CAMEL-18861)

### CODE REVIEW

**Comment by SteinOv** [comment]
The build fails, but I can't figure out why. There is no error message and locally it does succeed.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
@otavioprado knows better how to get CI build logs - but its not so easy. Also main is under development for v4 so there can be some bumps on the road

**Comment by SteinOv** [comment]
Ah yeah, the main branch doesn't build for me (without my changes). 

Btw, I'd like my changes (this PR and two previous PR's I made) to be included with the next camel 3 release. Should I make a separate PR to merge into 3.20.x?

**Comment by davsclaus** [comment]
PRs for camel-3.x branch

**Comment by oscerd** [comment]
If you rebase on main, it should work now.

**Comment by oscerd** [comment]
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.21.0:validate (validate) on project camel-plc4x: File '/home/runner/work/camel/camel/components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java' has not been previously formatted. Please format file (for example by invoking `mvn net.revelc.code.formatter:formatter-maven-plugin:2.21.0:format`) and commit before running validation! -> [Help 1]

**Comment by davsclaus** [comment]
One of the tests is maybe a bit flaky

[WARNING] Flakes:
[WARNING] org.apache.camel.component.plc4x.Plc4XComponentTest.testSimpleRouting
[ERROR]   Run 1: Plc4XComponentTest.testSimpleRouting:37 mock://result Received message count. Expected: <2> but was: <1>
[ERROR]   Run 2: Plc4XComponentTest.testSimpleRouting:37 mock://result Received message count. Expected: <2> but was: <1>
[INFO]   Run 3: PASS

**Comment by SteinOv** [comment]
> One of the tests is maybe a bit flaky
> 
> [WARNING] Flakes: [WARNING] org.apache.camel.component.plc4x.Plc4XComponentTest.testSimpleRouting [ERROR] Run 1: Plc4XComponentTest.testSimpleRouting:37 mock://result Received message count. Expected: <2> but was: <1> [ERROR] Run 2: Plc4XComponentTest.testSimpleRouting:37 mock://result Received message count. Expected: <2> but was: <1> [INFO] Run 3: PASS

@davsclaus I thought I fixed the inconsistency, but it turns out I didn't. I made a new [PR](https://github.com/apache/camel/pull/9280) which should fix it. Can you test whether it is consistent for you too now?

**Pull request merged**
