### PR TITLE
CAMEL-11454 use provided input stream when unmarshalling instead of creating a new one

### PR DESCRIPTION
**Pull request by adioss**
see JIRA ticket for more information (investigation part)

### CODE REVIEW

**Comment by oscerd** [comment]
@onders86 do you want to review since you assigned the issue to yourself?

**Comment by onders86** [comment]
@oscerd, i dont remember i assigned it to myself, not a problem i ll review tonight.

**Comment by oscerd** [comment]
Thanks :-) not sure why, but it's assigned to you.

**Comment by davsclaus** [comment]
@adioss thanks for the PR. Do you mind creating a similar PR for camel-tarfile as I believe its similar code to camel-zipfile.

**Comment by adioss** [comment]
@oscerd @onders86 assignment have been done "automatically" I think because I cloned CAMEL-11120 to create CAMEL-11454, since I'm not able to reopen tickets.

**Comment by onders86** [comment]
@adioss, i have not run cs against your pr, the reason why i commented is because the code contains empty lines removed and readded, there are very few lines which have almost no change except whitespaces chars i guess. nevermind if your cs run is ok, good to go. for tar, imho, it is ok, no pr or jira needed. and for camel-11120, i guess i missed the comment. otherwise i would help. thanks for the pr. looks good

**Comment by davsclaus** [comment]
Yeah that sounds good @adioss with a new PR for tests to camel-tarfile, cleanup the code, and align with zipfile. 

And yeah who is that Claus, he seems to be everywhere and then nowhere. Can't trust these kind of guys ;)

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
