### PR TITLE
CAMEL-10859 - doc update for noclassdef found in classpath

### PR DESCRIPTION
**Pull request by onders86**
added a tip for NoClassDefFound error.

### CODE REVIEW

**Comment by davsclaus** [comment]
Oh I suggest to specify which JARs to include in the `java -jar xxx` you can use `-cp` I think to add additional jars.

Having to copy a JAR to your JDK libe/ext folder is not something we recommend users to do. I wonder if you mind to look at this again?

**Comment by onders86** [comment]
Yes sure. 
However using java -jar <executable_file> does not allow setting classpath via -cp.
if we would suggest -cp then, main class should specified like below;
eg.
java -cp <path>/jasypt-1.9.2.jar:'*' org.apache.camel.component.jasypt.Main -c encrypt -p secret -i tiger

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by onders86** [comment]
thanks. sure.

**Pull request closed without merging**
