### PR TITLE
Aws2 kinesis doc update

### PR DESCRIPTION
**Pull request by hamed-hatami**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I think you need to rebase because there shouldn't be update to the java code.

**Comment by hamed-hatami** [comment]
I got it, I'll do it right away

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@oscerd can we merge this, and then we can kick off a CI dryRun job afterwards

**Comment by oscerd** [comment]
Merged

**Pull request merged**
