### PR TITLE
Update spanmanager version, add decorators and tests for other camel …

### PR DESCRIPTION
**Pull request by objectiser**
…components

### CODE REVIEW

**Comment by objectiser** [comment]
@davsclaus Hi Claus - update to the opentracing component to add decorator support for some other components, mainly http, some dbs. Related to https://issues.apache.org/jira/browse/CAMEL-10825. Would you prefer a separate jira for this?

**Comment by davsclaus** [comment]
Ah this is fine as its a new component that has not been released before. The JIRA is more needed when has been released to have changelog and allow to backport easier etc.

**Comment by davsclaus** [comment]
For next PR please run checkstyle first

    mvn compile -P sourcecheck

**Comment by objectiser** [comment]
@davsclaus Sorry, will do.

**Pull request closed without merging**
