### PR TITLE
CAMEL-20503: camel-http OAuth2 support for caching / refreshing tokens

### PR DESCRIPTION
**Pull request by kulagaIA**
# Description
- added caching oauth2 tokens for http component, and configuration parameters for caching

# Tracking
https://issues.apache.org/jira/browse/CAMEL-20503

### CODE REVIEW

**Comment by kulagaIA** [comment]
Will make a pr out of this draft after making tests for token caching

**Comment by davsclaus** [comment]
Great start on this

**Comment by davsclaus** [comment]
are you able to pick this work - would be good to get done within a few weeks so we can get 4.9 released incl this

**Comment by kulagaIA** [comment]
> are you able to pick this work - would be good to get done within a few weeks so we can get 4.9 released incl this

Hello, will finish on this week

**Comment by davsclaus** [comment]
This PR has many modified files that are not in the commit so the PR cannot do automated testing

**Comment by davsclaus** [comment]
it seems this PR is somehow half broken with a lot of not related files in DSL etc.


I wonder if you could do a clean PR where changes are only in http component and its "friends" such as atmosphere or else that may extend http component.

**Pull request closed without merging**
