### PR TITLE
Maven plugins: m2e compatibility

### PR DESCRIPTION
**Pull request by victornoel**
Hi, here is a PR following a discussion on the mailing list.

The idea is that currently, the camel-package-maven-plugin does not integrate very well with Eclipse: when the goals (listed below) are triggered, they trigger a rebuild of the project which triggers the goals and so on indefinitely.

The m2e project provides guidelines to improve maven plugins compatibility with Eclipse in the following page: http://eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html

I thus propose these (simple) changes for the (listed below) goals of camel-package-maven-plugin.
If I understood well they are the only ones really meant to be used by people developing components.

 - Uses BuildContext to support m2e and improve user experience in Eclipse
  - Only trigger execution when input has changed
  - Notify eclipse of change of output
 - Only support the following goals in camel-package-maven-plugin
  - generate-components-list
  - generate-dataformats-list
  - generate-languages-list
  - prepare-components

I also had to increase the required version for one dependency (only used in the maven plugins normally) because it was needed by the added dependency providing the BuildContext.

Thank you very much, I hope this will be accepted, I'm available to improve anything in there.
If I understood well @davsclaus you are taking care of the maven plugins, if you could give your opinion about that PR and merge it when it's done, it would be great :)

### CODE REVIEW

**Comment by victornoel** [comment]
Hmm, maybe it's not completely working, I'm doing more tests!

**Comment by victornoel** [comment]
Now it should be ok!

**Comment by davsclaus** [comment]
Thanks for the PR. The code has been merged. Do you mind closing this.

**Comment by victornoel** [comment]
Great, thanks!

**Pull request closed without merging**
