### PR TITLE
CAMEL-12978 - Add support to configure CamelContext created by KIE-Se…

### PR DESCRIPTION
**Pull request by mswiderski**
…rver extension

### CODE REVIEW

**Comment by DuncanDoyle** [comment]
Tested it successfully with custom CamelContext with REST DSL configuration. LGTM.

**Comment by mswiderski** [comment]
@oscerd this is the last feature to be included and then we can back port as discussed in jira

**Comment by oscerd** [comment]
Merged on master. I'm backporting to 2.23.x

**Comment by oscerd** [comment]
Backported to 2.23.x too.

Thanks :-)

**Pull request closed without merging**
