### PR TITLE
Fix CometD replay extension license

### PR DESCRIPTION
**Pull request by sirlatrom**
Granted by Salesforce Developers in https://github.com/developerforce/StreamingReplayClientExtensions/commit/dca278fa5f8b97bb9f714954b72ddd5a431c8e7d

### CODE REVIEW

**Comment by sirlatrom** [comment]
This should conclude the discussion in https://github.com/apache/camel/pull/1035

**Comment by sirlatrom** [comment]
Ping @davsclaus

**Comment by davsclaus** [comment]
This is currently under talks with ASF legal to ensure whether we can accept this code or not.

**Comment by davsclaus** [comment]
@sirlatrom would it be possible to have SalesForce donate the code to ASF using the ASL license, like all the other PRs we accept from the community?

If not can the SalesForce do a release of their source code as a JAR file and publish that to Maven Central?

In other words, can this either be

- a regular code contribution to ASF using the ASL license
- or a 3rd party dependency we can use instead that has been released to Maven Central

**Comment by sirlatrom** [comment]
@davsclaus I had hoped that http://www.apache.org/legal/resolved.html#category-a would be an authoritative reference, but I've forwarded your questions to Salesforce and I'll get back to you with an answer as soon as I get one.

**Comment by sirlatrom** [comment]
Answer from product manager Jay Hurst:
> No, as of now we are not prepared to release the sample code to any maven or ASF repos. The code is provided as-is with no warranty/support/or contract for updates.
> 
> We are working on an open-sourced connector which would be supported, but that will be a release or so away

Could ASF Legal accept the code as 3-C BSD?

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
