### PR TITLE
Upgrade recipes based on openrewrite

### PR DESCRIPTION
**Pull request by JiriOndrusek**
ticket: https://issues.apache.org/jira/browse/CAMEL-20896

This is a draft of a migration module using Openrewrite recipes for Camel migration.
This version is a extraction of recipes from project https://github.com/quarkusio/quarkus-updates/ into a Camel repository.
Please look at the README.adoc to understand more about the module.

Here is a list with TODOs (the reason why this PR is a draft)
- **This module should be standalone project**.
It might be necessary to release new version of recipes and it wouldn't be possible if whole Camel has to be released as well.
- Better CLI for executing the migration would be nice. Look for example on quarkus [guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0)
It would be nice to use something like `camel update 4.4` (which in case of camel 3.x would trigger update to 4.0 and then to 4.4)
- Some recipes from quarkus-updates can not be used, as they are quarkus related. (org.openrewrite.java.camel.migrate.removedExtensions)

Thequarkus-update refactor is in progress, the initial proposal is https://github.com/quarkusio/quarkus-updates/pull/177

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
@davsclaus What do you think?

**Comment by ammachado** [comment]
I have some recipes I'd like to contribute, if this PR eventually gets merged.

**Comment by davsclaus** [comment]
@JiriOndrusek thanks for starting on this - looks good. We can keep the docs in the readme file here in the beginning. When its more ready then it would be good to have docs that are published on the website too.
And later a blog post to introduce this feature is also welcome.

And surely rules is welcome @ammachado

**Comment by JiriOndrusek** [comment]
> @JiriOndrusek thanks for starting on this - looks good. We can keep the docs in the readme file here in the beginning. When its more ready then it would be good to have docs that are published on the website too. And later a blog post to introduce this feature is also welcome.
> 
> And surely rules is welcome @ammachado

I'm not sure about the one thing mostly. 
I know that Quarkus team keeps recipes in the repository separated from the Quarkus project. This approach seems to me  as a right call. If recipes are separated from the main repo, the release cycle is not dictated by the main repo. Therefore if some kind of change (like missing recipe) or fix needs to be released, there is no need to release the whole project (Camel in this case). I'm not sure what is needed for the recipes to be located in the standalone repository, but I'd vote for doing so. 

Next action:
- Next week my [proposal](https://github.com/quarkusio/quarkus-updates/pull/177) to Quarkus-updates should be reviewed.  Based on that, I might need to update this draft.
Once proposal to Quarkus is approved, we can continue with making this draft merged and recipes artifact released (because the artifact would be required for the Quarkus's draft to be merged).

**Review by oscerd — APPROVED** [review]
Thanks for this. I think It would be nice to have also documentation published on the website showing the usage and some examples.

**Comment by JiriOndrusek** [comment]
@davsclaus @oscerd 
would it be possible to create a separated project for this recipes?

- If some kind of change (like missing recipe) or fix needs to be provided in the recipes, if they are part of Camel, the whole project needs to be released.
- Or  if some lower version of camel is released, we would like to have the recipes for such version in the newest recipes artifact, therefore we would need to release recipes module, which might be problematic if it is part of Camel).

What do you think?

(current status update: Quarkus-updates changes are going to be approved, I have to run manually some tests and comparisons to make that happen. )

**Comment by JiriOndrusek** [comment]
The previous comment brings other features.

Currently the recipes could upgrade only to the newest camel version. It would be nice to add an option to upgrade to a specific version or to upgrade in the stream (like LTS stream 4.4.x). These functionality is not part of this PR but it would be nice to have it as an option in some CLI wrapper.

**Comment by oscerd** [comment]
> @davsclaus @oscerd would it be possible to create a separated project for this recipes?
> 
> * If some kind of change (like missing recipe) or fix needs to be provided in the recipes, if they are part of Camel, the whole project needs to be released.
> * Or  if some lower version of camel is released, we would like to have the recipes for migration to such version in the newest recipes artifact, therefore we would need to release recipes module, which might be problematic if it is part of Camel).
> 
> What do you think?
> 
> (current status update: Quarkus-updates changes are going to be approved, I have to run manually some tests and comparisons to make that happen. )

I don't see particular reason to avoid the creation of a separated repository for this.

**Comment by davsclaus** [comment]
Yeah we could create a new repo (need to come up with a good name): camel-upgrade (or camel-upgrade-recipes) or what a good git repo name can be. Then its easier to start there and build up a set of recipies and have this released indepdent to get started and worked out.

**Comment by JiriOndrusek** [comment]
> Yeah we could create a new repo (need to come up with a good name): camel-upgrade (or camel-upgrade-recipes) or what a good git repo name can be. Then its easier to start there and build up a set of recipies and have this released indepdent to get started and worked out.

I agree with both suggested names. 
For the future I think hat the `camel-upgrade-recipes` might be better, because it would allow to create multi-module project where all modules would start with `camel-upgrade-`. (more modules might be necessary in the future if we would need to enhance the user experience with some helper tooling)

Questions:

1. Once the name is settled, who would be able to create an empty project in camel repo? (I'm going to prepare changes from this PR to create a standalone project)
2. Should I place the recipes into the sub-module for the sake of future? (I'd say yes, because  it won't complicate anything even if we won't create other sub-modules

**Comment by davsclaus** [comment]
I think @oscerd can help setup the git repo

**Comment by oscerd** [comment]
I can create that even now.

**Comment by oscerd** [comment]
Is the name camel-upgrade-recipes?

**Comment by davsclaus** [comment]
> Is the name camel-upgrade-recipes?

Yes

**Comment by oscerd** [comment]
https://github.com/apache/camel-upgrade-recipes

**Comment by JiriOndrusek** [comment]
> https://github.com/apache/camel-upgrade-recipes

Thank yuo, I'll prepare a new PR to that project with the content from this PR (and fixes to make it standalone)

**Comment by JiriOndrusek** [comment]
Superseded by https://github.com/apache/camel-upgrade-recipes/pull/1

**Pull request closed without merging**
