### PR TITLE
CAMEL-10837 - Migrate EIP patterns to adoc

### PR DESCRIPTION
**Pull request by ouapdouap**
Commits after Feb 19 included are new. I don't why the commits of my previous PR are still here.
Sebastien

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you squash your commits before the PR so its only 1 commit.

We rebase on master so your commits are merged on top and that leads to merge conflicts sometimes when you have 20+ commits.

**Comment by ouapdouap** [comment]
How do I do that?
I have forked, then worked on the doc, work that you merged last week in my first PR.
Then I migrated more EIPs and created this PR but I still see the commits of the first PR in this one. This morning I rebased my fork so its up-to-date with the upstream/master so I see all commits that happened since I forked.
So I guess my repository is in sync with the camel/master.
Is ti a good way to work or should I have forked again after you merge my first PR?

**Comment by davsclaus** [comment]
Create a branch each time you want to work on something.
And then when that PR is merged
Then delete your branch and go back to master and do a `git pull --rebase` on the master to be up to date. And then create a new branch from master from that point when you work on new docs.

I can get this merged but it takes more time for me to manual resolve the merge conflicts, so let me do this first. Then PRs in the future can be as said above

**Comment by ouapdouap** [comment]
I saved added files aside so I can start again from the master and add my work again.
Then I'll submit a new PR which will be easier to merge.
Is it ok for you?

**Comment by davsclaus** [comment]
Yeah this PR is toasted, you should have started on the latest master branch so its clean. And make sure to use those files.

And do one change at a time, eg do only START END in one commit.
And then other changes like changing the content etc in other commits.

And make sure to use the right EIP names as they are now - be careful with aggregator and filter vs message-filter etc

I suggest to close this PR and start over in a new PR

**Pull request closed without merging**
