### PR TITLE
CAMEL-15978 Fixes in Buy in JIRA CAMEL-15978

### PR DESCRIPTION
**Pull request by mike-costello**
All tests pass when using env var TESTCONTAINERS_RYUK_DISABLED=TRUE

- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Can you please rebase and fix conflicts? Also I don't think it's ok to set an environment variable to make the test pass, we need to set the env variable through maven so it will be always the same.

**Comment by davsclaus** [comment]
I fxed the merge conflict

**Comment by davsclaus** [comment]
Okay this requires also upgrading smack to 4.4 as then it uses jxmpp 1.0.x library.
And after that there are some security tests failing with certificates (yeah lovely). So its actually a harder work to do.

**Comment by omarsmak** [comment]
Any updates on this one?

**Comment by davsclaus** [comment]
Closing inactive PRs

**Pull request closed without merging**
