### PR TITLE
CAMEL-10730: Camel-Telegram: Support for type "Document" 

### PR DESCRIPTION
**Pull request by Neffez**
The telegram type "Document" is a general file (as opposed to photos, videos or audio files) and can be in any format. A Document can also be one of the already supported types, but then it's uncompressed (e.g. photos).

The benefits of using the Document type are:
- Receiving and sending uncompressed files
- Receiving and sending files of any format

This pull request contains the support for incoming and outgoing documents and unit tests.

Also see: https://core.telegram.org/bots/api#document

### CODE REVIEW

**Comment by davsclaus** [comment]
@nicolaferraro wonder if you could take a look as well.

@Neffez do you mind creating a JIRA ticket also so we can track this there too.

**Comment by Neffez** [comment]
Here it is: https://issues.apache.org/jira/browse/CAMEL-10730

**Comment by nicolaferraro** [comment]
@Neffez thanks for the PR, I'll review it soon.

**Comment by nicolaferraro** [comment]
Great work @Neffez! (sorry for the delay)

The changes have been merged into master. I've just changed few bits and done a source check (`mvn clean install -P sourcecheck` on the component).

Do you mind closing this PR?

**Comment by Neffez** [comment]
Cheers!

**Pull request closed without merging**
