### PR TITLE
Camel-Tracing: Removing NsqSpanDecorator since component is no more a…

### PR DESCRIPTION
**Pull request by oscerd**
…vailable

# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by oscerd** [comment]
@marcingrzejszczak I'm looking at the span decorator available and I do think we could add some more. Do you have any suggestions on this particular task? Thanks.

**Comment by marcingrzejszczak** [comment]
@oscerd I don't exactly follow. What is the concrete question? Are you trying to add more span decorators?

**Comment by oscerd** [comment]
Yes, I meant to ask if you have idea of what component decorators make more sense in your experience

**Comment by marcingrzejszczak** [comment]
I mean all components can be interesting to the users. Preferably we should ask the users what are they most interested in or which telemetry data they feel that they are currently missing.

**Comment by oscerd** [comment]
@davsclaus I do think this is could be a good approach (asking users) for improving the decorators' coverage.

**Comment by davsclaus** [comment]
Yes that would be good to have more of them

**Comment by marcingrzejszczak** [comment]
Another option would be to go through https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/ to see which conventions are defined today (remember that these are not stable so let's not ever say that we are OTel semantic convention compatible because if we do we will have to keep on doing breaking changes) and try to double check if our instrumentations are setting similar meta data.

**Comment by davsclaus** [comment]
@marcingrzejszczak that is a great idea - we should make these camel components use same convention if possible. I have created a JIRA: https://issues.apache.org/jira/browse/CAMEL-19812

**Comment by davsclaus** [comment]
Yes its okay, we will add notes in our upgrade guides if tags are renamed, and can also do dual names to keep the deprecated for a number of releases.

**Comment by oscerd** [comment]
I think it would be beneficial to have a look at what we have as decorators today and do a little example to what we want to have

**Pull request merged**
