### PR TITLE
CAMEL-14027 Update to fix the NettyHttpStreamTest to release the buffer

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.apache.org/jira/browse/CAMEL-14027

### CODE REVIEW

**Comment by davsclaus** [comment]
Is it only the unit test that has a problem? I assume if you use this in a production use-case then camel-netty-http wont have a leaking buffer problem?

**Comment by oscerd** [comment]
From a first analysis this comes from the getcontent on the request set on the body

**Comment by oscerd** [comment]
So, I think this will fix the test, but the problem seems to be at higher level in the component.

**Comment by zhfeng** [comment]
@davsclaus from [DefaultNettyHttpBinding.toCamelMessge(FullHttpRequest)](https://github.com/apache/camel/blob/master/components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/DefaultNettyHttpBinding.java#L104), it retain the content. So it's the consumer's responsibility to release the body.

**Comment by zhfeng** [comment]
It looks like we need to release this body on the exchange completion ? Does it make sense ?
```
answer.setBody(request.content().retain());
exchange.addOnCompletion(new SynchronizationAdapter() {
                @Override
                public void onDone(Exchange exchange) {
                    ReferenceCountUtil.release(request.content());
                }
            });
```

**Comment by zhfeng** [comment]
please hold the PR and I'm testing locally to verify the above changes. Thanks !

**Comment by oscerd** [comment]
Yes, @zhfeng, I think it would make sense to do this inside the component.

**Comment by zhfeng** [comment]
@oscerd OK, I made the changes to release the content inside the component.

**Comment by davsclaus** [comment]
+1 thanks for getting to the bottom of this

**Comment by oscerd** [comment]
Ok. I'll merge tomorrow

**Comment by oscerd** [comment]
thx merged.

**Pull request closed without merging**
