### PR TITLE
fix(jbang): include platform-http dependency

### PR DESCRIPTION
**Pull request by squakez**
only when necessary

Closes CAMEL-21294

# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by davsclaus** [comment]
if you have a rest app then you need platform-http. I wonder if you could try export these kinds before merging.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Also the openapi examples would be using platform-http such as
https://github.com/apache/camel-kamelets-examples/tree/main/jbang/open-api-contract-first
https://github.com/apache/camel-kamelets-examples/tree/main/jbang/open-api

**Comment by squakez** [comment]
> Also the openapi examples would be using platform-http such as https://github.com/apache/camel-kamelets-examples/tree/main/jbang/open-api-contract-first https://github.com/apache/camel-kamelets-examples/tree/main/jbang/open-api

I tested with and without the platform. Sure, let me try testing with rest and openapi as well. I feel it should work because it is normally working with main, but let's make sure with some test.

**Comment by davsclaus** [comment]
I am wonder about whether export to Q and SB works for these examples

**Comment by squakez** [comment]
I've tested REST and Openapi examples against all runtimes. The openapi contract first is suffering this problem https://issues.apache.org/jira/browse/CAMEL-21301 - but it seems it was an existing regression as I've tested with released 4.8.0 and it is getting the very same result. I'm going to merge this and solve the other separately as they does not seem to be related.

**Pull request merged**
