### PR TITLE
CAMEL-16482: HazelCastSet and HazelCastList getAll() added and tests modified

### PR DESCRIPTION
**Pull request by mroldan747**
Add getAll() method to HazelCastSet and HazelCastList and also update of the tests without mock, but testing the actual methods

- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [x ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Looks good to me, just curious about why you switched from HazelcastTestSupport to CamelTestSupport directly. It's fine, but I think it makes sense to use the same approach on all the tests.

**Comment by zbendhiba** [comment]
> Looks good to me, just curious about why you switched from HazelcastTestSupport to CamelTestSupport directly. It's fine, but I think it makes sense to use the same approach on all the tests.

I started that here https://github.com/apache/camel/blob/c94f811ea315cf7a603ea08e5f67643df230242b/components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastReplicatedmapConsumerTest.java#L38, the idea was not to have those methods related to mock. But now there are 3 classes extending CamelTestSupport directly.

As a follow up I created this JIRA https://issues.apache.org/jira/browse/CAMEL-16660, to make HazelcastTestSupport use camel-test-infra-Hazelcast

**Review by zbendhiba — APPROVED** [review]

**Comment by mroldan747** [comment]
> > Looks good to me, just curious about why you switched from HazelcastTestSupport to CamelTestSupport directly. It's fine, but I think it makes sense to use the same approach on all the tests.
> 
> I started that here
> 
> https://github.com/apache/camel/blob/c94f811ea315cf7a603ea08e5f67643df230242b/components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastReplicatedmapConsumerTest.java#L38
> 
> , the idea was not to have those methods related to mock. But now there are 3 classes extending CamelTestSupport directly.
> As a follow up I created this JIRA https://issues.apache.org/jira/browse/CAMEL-16660, to make HazelcastTestSupport use camel-test-infra-Hazelcast

 I can follow up with this new JIRA, to fix the usage of CamelTestSupport, unless it is blocking for this PR ?

**Review by omarsmak — APPROVED** [review]

**Comment by oscerd** [comment]
Thanks @mroldan747

**Pull request merged**
