### PR TITLE
CAMEL-16532: Prevent unregistration of existing endpoints after attem…

### PR DESCRIPTION
**Pull request by mash-sap**
…pt to register a already existing endpoint

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Please open or against master

**Review by tadayosi — CHANGES_REQUESTED** [review]
I don't think it's the right fix. It should be ok for your specific case that the server was not started because the consumer endpoint has the exact same URI, but what happens if it wasn't started for other reasons?  In such a case, I suspect we'll see a regression issue that the previous fix tried to resolve.

**Comment by mash-sap** [comment]
@tadayosi The change to destroy the server on stop was introduced to cleanup mbeans (CAMEL-10914). Can we check if the proposed change has a impact on that specific mbean-use-case? Do you know what would need to be done to check?

**Comment by tadayosi** [comment]
@mash-sap Maybe you can try to make some CXF consumers fail to start and check if there are really no dangling MBeans for them.

**Comment by tadayosi** [comment]
And you should create the patch against {{main}} from scratch, otherwise it'll see merge conflicts like this.

**Comment by mash-sap** [comment]
@tadayosi How could I check for dangling mbeans?

**Comment by tadayosi** [comment]
You can check them by using some JMX viewers such as Hawtio.

**Comment by mash-sap** [comment]
I was not able to update the branch. Therefore I created a new PR: https://github.com/apache/camel/pull/5454

**Pull request closed without merging**
