### PR TITLE
CAMEL-13534

### PR DESCRIPTION
**Pull request by dimitrisli**
Addressing https://issues.apache.org/jira/browse/CAMEL-13534

Adding support to navigate with colon (:) for env: / sysenv: / header: / headers: aside from the regular support env. / sysenv. / header. / headers. respectively

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR. Do you mind updating the documentation too, see the simple-language.adoc file

**Comment by davsclaus** [comment]
Ah darn we have just moved the simple language to camel-base directory instead. I wonder if you can try to rebase on your end and resolve any merge conflicts etc.

**Comment by dimitrisli** [comment]
@davsclaus thanks for making it so accessible for people to contribute. I've added the documentation mirroring the existing entries. It seems there are conflicts on some files taking a look now

**Comment by fatihpense** [comment]
Hello,
The new location is here:

> Moved files from core/camel-core/src/main/docs/ to docs/user-manual/modules/ROOT/pages/ flattening the directories.
https://github.com/apache/camel/pull/2930

Regards,
Fatih

**Comment by dimitrisli** [comment]
Closing since something went wrong with the rebase. Will open right after a new PR

**Pull request closed without merging**
