### PR TITLE
[CAMEL-17159] Changes to support multiple valid content types

### PR DESCRIPTION
**Pull request by henka-rl**
Added tests for this in jetty, servlet and undertow components

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by henka-rl** [comment]
I also found a strange behaviour in undertow. Then the body is null undertow it sets the body to "No response available":
https://github.com/apache/camel/blob/b87886bfe576e4ccb5513d9bb98a45a903711464/components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java#L249

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Can you please fix the code style? Thanks.

**Comment by henka-rl** [comment]
In progress...

**Comment by davsclaus** [comment]
> I also found a strange behaviour in undertow. Then the body is null undertow it sets the body to "No response available":
> 
> https://github.com/apache/camel/blob/b87886bfe576e4ccb5513d9bb98a45a903711464/components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java#L249

Can you try git blame to find out if there is a JIRA or more? Also check if other http component does that.

**Comment by henka-rl** [comment]
> > I also found a strange behaviour in undertow. Then the body is null undertow it sets the body to "No response available":
> > https://github.com/apache/camel/blob/b87886bfe576e4ccb5513d9bb98a45a903711464/components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java#L249
> 
> Can you try git blame to find out if there is a JIRA or more? Also check if other http component does that.

I found CAMEL-14025

**Comment by davsclaus** [comment]
Can you check what camel-jetty does?

**Comment by henka-rl** [comment]
camel-jetty returns an empty ("") response:
image

**Comment by davsclaus** [comment]
Thanks can you create a JIRA. Then lets fix this to make them do the same, to return an empty body.

**Comment by davsclaus** [comment]
@henka-rl I created a JIRA
https://issues.apache.org/jira/browse/CAMEL-17166

You are welcome to send PRs

**Pull request merged**
