### PR TITLE
[CAMEL-19613] Convert components to use the camel-test-infra-core: AS2 component

### PR DESCRIPTION
**Pull request by ammachado**
# Description

Convert components to use the camel-test-infra-core: AS2 component

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
LGTM. There is failure, but it happens only on github. Probably a test that has always been flaky:

```
[ERROR] org.apache.camel.component.as2.AS2ClientManagerIT.asyncMDNTest -- Time elapsed: 0.169 s <<< ERROR!
```

It's good to merge.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
It may be that this PR is causing some of the as2 tests to fail on CI
https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/lastCompletedBuild/testReport/

**Comment by davsclaus** [comment]
Oh it seems like its some tests that was only supposed to be run if you have setup an AS2 server

[ERROR]   AS2ServerManagerIT.sendEditMessageToFailingProcessorTest » FailedToCreateRoute Failed to create route route7: Route(route7)[From[as2://server/listen?requestUriPattern=/] ... because of Failed to resolve endpoint: as2://server/listen?requestUriPattern=/ due to: serverPortNumber must be specified

**Comment by orpiske** [comment]
> Oh it seems like its some tests that was only supposed to be run if you have setup an AS2 server
> 
> [ERROR] AS2ServerManagerIT.sendEditMessageToFailingProcessorTest » FailedToCreateRoute Failed to create route route7: Route(route7)[From[as2://server/listen?requestUriPattern=/] ... because of Failed to resolve endpoint: as2://server/listen?requestUriPattern=/ due to: serverPortNumber must be specified

ACK. I remember pointing out in a review that some of these tests were missing assumptions to skip them if certain properties were not provided. I'll investigate.

**Pull request merged**
