### PR TITLE
CAMEL-13417: Move mock component out of camel-core

### PR DESCRIPTION
**Pull request by davsclaus**
Took me 3-4 days to get all of this done ;)

### CODE REVIEW

**Comment by davsclaus** [comment]
Tried to resolve the readme file via github web - but its generated anyway, when we do a new build

**Comment by oscerd** [comment]
No, problem. Just merge and we rebuild.

**Comment by davsclaus** [comment]
As part of this work we had to also remove some old stuff in bean regarding remote rpc calls and its BeanInovcation that today is not in use/bad-design, and in line of this also remove camel-rmi component. And a few other bits to get it all separated and also prepared for eventually one day to move out the bean component too.

**Comment by oscerd** [comment]
We can create subtask for this

**Pull request merged**
