### PR TITLE
CAMEL-13026 - Header written out on each message when marshalling

### PR DESCRIPTION
**Pull request by ribeaud**

### CODE REVIEW

**Comment by onderson** [comment]
@ribeaud , could you please run mvn clean install -Psourcecheck and rebase the PR. there seems to be unchanged lines but they look like they are edited, a bit hard to review.

**Comment by ribeaud** [comment]
Good morning @onderson. When running `mvn clean install -Psourcecheck` in my environment (*Win10*, *Java1.8.0*), I am getting following exception:
```
 mvn clean install -Psourcecheck
'nrecognized VM option 'UseStringDeduplication
Did you mean '(+/-)UseStringDeduplication'?
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
An ending line break in `jvm.config` seems to be the problem. By removing it, the **JVM** could then be started (NOTE: I have `core.autocrlf` set to _true_).

Running now `mvn clean install -Psourcecheck`. What do you mean exactly by _rebasing_ the PR? Onto the current `upstream/master`?

Thanks and cheers,
christian

**Comment by ribeaud** [comment]
The issue with `jvm.config` seems to be specific to the **Win10** _subsystem_. Everything works fine when running **Maven** in my IDE. I see as well the **Checkstyle** errors. I will correct them (by the way, why is the build NOT failing as soon as we have some **Checkstyle** errors?).

**Comment by ribeaud** [comment]
Hi @onderson. Like this?
Cheers,
christian

**Comment by onderson** [comment]
@ribeaud sorry for the delay, this is not what i meant. it is a bit messed up now. could you please close and open a clean PR?

**Comment by ribeaud** [comment]
See #2705. Cheers, christian.

**Pull request closed without merging**
