### PR TITLE
CAMEL-12703: camel-salesforce - Added JSON as a valid contentType

### PR DESCRIPTION
**Pull request by jsight**
Added JSON to JobInfo ContentType. Documented here: https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_reference_jobinfo.htm

### CODE REVIEW

**Comment by jsight** [comment]
@oscerd - Done, let me know if there is anything else.

**Comment by oscerd** [comment]
Lgtm. @zregvart wdyt?

**Comment by zregvart** [comment]
Thanks @jsight!

**Comment by jsight** [comment]
yw, thanks for the review and merge!

**Pull request merged**
