### PR TITLE
CAMEL-11144: Add components to component table, add description

### PR DESCRIPTION
**Pull request by ctron**
Signed-off-by: Jens Reimann <jreimann@redhat.com>

### CODE REVIEW

**Comment by davsclaus** [comment]
@ctron that table is auto generated, you change this in the javadoc on the endpoint java source file.

**Comment by ctron** [comment]
Ok, sorry for that. I will update the PR.

**Comment by ctron** [comment]
What is the correct/quickest way to update the readme file after making those changes?

**Comment by davsclaus** [comment]
cd platforms
cd camel-catalog
mvn clean install

**Comment by davsclaus** [comment]
You would need to run mvn clean install first in that component so its built first before the readme files can be updated

**Comment by ctron** [comment]
I seem to have trouble getting both endpoints showing up in the table.

**Comment by davsclaus** [comment]
Thanks likely because you would need to have build all source code first locally.

**Comment by ctron** [comment]
My mistake. The sort order seems to be the `title` attribute of the annotation instead of the actual component name.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by ctron** [comment]
That was quick. Let me double check.

**Comment by davsclaus** [comment]
Ah darn the title was wrong. It should be a short title of the scheme, eg "JMS", "MQTT", "Mina" etc

**Comment by ctron** [comment]
Ok, that was a bit too quick ...

**Comment by ctron** [comment]
Commit 47d09346e9dbb39d2ad8fc433cb1e83ed4c3464b should fix this

**Comment by ctron** [comment]
I am using "OPC UA Server" and "OPC UA Client" for both now.

**Comment by davsclaus** [comment]
Thanks this has been merged

**Comment by ctron** [comment]
Looks good! Thanks!

**Pull request closed without merging**
