### PR TITLE
[CAMEL-20298] Enhancing JSONata Compatibility for Full Reference Port

### PR DESCRIPTION
**Pull request by otavioprado**
# Description

This pull request replaces the JSONAta library with a new one that provides full compatibility with the features of the spec.

New (with full compability): https://github.com/dashjoin/jsonata-java
Old ([with no full compability](https://github.com/IBM/JSONata4Java?tab=readme-ov-file#current-limitations)): https://github.com/IBM/JSONata4Java

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks for your contribution @otavioprado!

Overall, I am OK with it. The technical solution seems OK to me, however:

1. I feel like we should have a ticket for this one as this needs to be added to the release notes
2. This is changing a dependency, and this is not always as trivial as it seems, I'd like to hear community feedback on this 
3. It needs to be documented on the 4.4 migration guide

For now I am marking as request changes just to hear more feedback and to prevent it from being merged by mistake.

Thanks!

**Comment by otavioprado** [comment]
Happy to help @orpiske :)
I've created a Jira ticket, [CAMEL-20298](https://issues.apache.org/jira/browse/CAMEL-20298), to track this activity

If there's anything I can assist with, please let me know

**Comment by orpiske** [comment]
Thank you @otavioprado. Many members of the community are currently on / returning from PTO. So, let's just wait a bit more until they are fully back in the game.

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]

**Comment by oscerd** [comment]
I think we could merge this one. But we should add a note in the migration guide between 4.3 and 4.4

**Comment by aeberhart** [comment]
I am one of the maintainers of the new jsonata lib. I wanted to provide some context on this lib and hopefully ease some of the concerns that @orpiske rightfully voiced about changing dependencies.

You can find a list of JSONata implementations here: https://docs.jsonata.org/next/overview.
At the moment there are two Java implementations: [JSONata4Java](https://github.com/IBM/JSONata4Java) and [jsonata-java](https://github.com/dashjoin/jsonata-java).

We use JSONata heavily for our low code platform (https://github.com/dashjoin/platform) and started out with JSONata4Java. Works great but there are some [limitations](https://github.com/IBM/JSONata4Java?tab=readme-ov-file#current-limitations) with more complex expressions which can be frustrating because something that works in the JSONata playground does not in the Java environment.

Then we decided to leverage the JS language reference via graal, which worked but had some performance issues. Finally, we started our Java version which is a 1:1 port of the original JS reference implementation to Java. This ensures

* 100% compatibility with the language specification
* an easy path to port future changes in the language and bugfixes into the Java world by keeping the code structure, comments, formatting of the original as much as possible

As far as I know, there are no expressions that evaluate differently when changing the library. This means that Camel code does not have to be changed when upgrading. We're also committed to maintaining the library. Of course more contributors are always welcome :)

**Comment by otavioprado** [comment]
> I think we could merge this one. But we should add a note in the migration guide between 4.3 and 4.4

I've just added a note about this to the following location: docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc. Please let me know if any further adjustments are necessary. :)

**Comment by oscerd** [comment]
I guess you'll need to rebase @otavioprado and fix the conflict. All good after that.

**Comment by otavioprado** [comment]
@oscerd, to address the build issue, should I have run `mvn clean install -DskipTests` locally and committed all the auto-generated changes? Please note that there are numerous changes if I need to do this.

**Comment by oscerd** [comment]
You could do something like mvnd clean install -Dquickly

**Pull request merged**
