### PR TITLE
CAMEL-15591 - Put a configurable limit on the size of unzipped data u…

### PR DESCRIPTION
**Pull request by coheigea**
…sing camel-zipfile + camel-tarfile

For camel-zipfile + camel-tarfile, there is no limit on the size of uncompressed data, potentially leading to an OOM Error. Instead we should have a configurable limit.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Can you add a test for this? Thank you

**Review by bedlaj — COMMENTED** [review]
Why 1GB default? This can be extremely high for microservice and also very low for monolytic app with hundreds of GB free RAM. I would personally keep default unlimited. If you want keep 1GB, you should mention that in migration guide, as user can easilly miss this limit during migration and testing.

Also there is some checkstyle issue reported in github action. Please run `mvn org.apache.camel:camel-format-plugin:format` in `camel-util` module and commit changes in `IOHelper` file.

**Comment by davsclaus** [comment]
I think if you use stream caching then the output stream will spool to disk and therefore you dont have a memory limit problem with 1GB limit (output stream builder). @bedlaj is right with the new world of cloud and microservices vs the old way of big monolithic app servers.

**Comment by coheigea** [comment]
@oscerd  Done.
@bedlaj 1GB is admittedly arbitrary - I just chose it as it seems unlikely to me for most use-cases that one will be uncompressing to a size  > 1GB. Agreed about having to update the migration guide if this change is accepted. I don't see the Checkstyle issue any more - can you double-check?
@davsclaus The problem is that with one of the files here (https://www.bamsoftware.com/hacks/zipbomb/) it can potentially unzip to 4.5 PB, so spooling to disk won't help. I don't really mind disabling the default limit, but then this is not "secure by default". Would a higher limit of say 10GB be more acceptable? Let me know + I'll change it to whatever you suggest.

**Comment by bedlaj** [comment]
Thanks for mentioning zip bombs. I was not thinking about this attack vector while reviewing this PR. Still not sure, if there is any magic default value, which will be secure on all platforms. Maybe another option would be computing compress ration on the fly while decompressing and throw exception while it is going to exceed configured max compress ratio Eg. 50 or 100 ratio might be reasonable default.

**Comment by davsclaus** [comment]
Yeah I think an upper limit by default is more safe than not. So if you can easily set the value to 0 or -1 to disable it then that would be good. A limit of 1gb is reasonable. I dont want to have some free memory calculator that attempt to set a setting, then its better with a hardcoded limit especially for file transfer. Then you can say, okay we support up to X GB of files etc.

**Comment by davsclaus** [comment]
Yeah I think its fine.

**Pull request merged**
