### PR TITLE
https://issues.apache.org/jira/browse/CAMEL-10158

### PR DESCRIPTION
**Pull request by ssharma**
Support to add tags to workflow execution in camel-aws component

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks :-)

The PR has been merged, can you close the PR? Also, can you documentation here:
http://camel.apache.org/aws-swf.html

You'll need a signed ICLA with Apache Software Foundation

**Comment by ssharma** [comment]
Sure. I will sign ICLA and wait for the approval before editing the documentation.

**Comment by oscerd** [comment]
Hi @davsclaus can you grant Karma to @ssharma? His username is sidshar

I don't know if I can grant Karma on Confluence.

**Comment by oscerd** [comment]
@ssharma I granted you Karma

**Pull request closed without merging**
