### PR TITLE
[CAMEL-17579] Preserve the data type of a message on copy

### PR DESCRIPTION
**Pull request by essobedo**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

## Motivation

The data type of a message is lost when it is copied which causes issue when the data transformer can only be found thanks to the provided data type.

## Modifications:

* Add an utility method `copyBody(Message source, Message target)` to copy the body of a message to another message while taking care of the data type internally when applicable
* Modify the different implementations of  `copyFrom(org.apache.camel.Message that)` to replace `setBody` with `copyBody` to preserve the data type
* Modify the implementation of `AbstractExchange#copy()` to replace `setBody` with `copyBody` to preserve the data type

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by essobedo** [comment]
@davsclaus I've noticed that you added the label `backport camel-3.14.x`, Does it mean that I need to propose the backport in another PR or will you do it yourself?

**Comment by davsclaus** [comment]
I have backported. 

Unfortunatly the label does not automatic create a PR - that was the idea. But we have permission problems with github actions for this kind - @oscerd knows more

So what we usually do is to manual backport via cherry picks

**Comment by essobedo** [comment]
@davsclaus I see. Regarding the backport, I can't see it in the list of commits of what sounds like the corresponding branch https://github.com/apache/camel/commits/camel-3.14.x, or maybe it is another branch?

**Comment by davsclaus** [comment]
Oh I didnt push - I am in the middle of other things, can you backport via a PR

**Comment by essobedo** [comment]
> Oh I didnt push - I am in the middle of other things, can you backport via a PR

OK, no problem

**Pull request merged**
