### PR TITLE
CAMEL-12011: Add RestletHost abstraction for creation of Restlet server

### PR DESCRIPTION
**Pull request by jamesnetherton**
https://issues.apache.org/jira/browse/CAMEL-12011

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks for the PR

**Comment by jamesnetherton** [comment]
Thanks for merging...

As this is a refactoring, I'm guessing it's not something that we would consider backporting to the 2.20.x branch?

**Comment by oscerd** [comment]
It's a medium refactoring, so IMO it's better to avoid backporting in this case. By the way lets ask to @davsclaus

**Comment by davsclaus** [comment]
Yeah lets wait for 2.21 release

**Pull request merged**
