### PR TITLE
[Hyperledger-Aries] Add support for service=didexchange

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@tdiesler is this ready to merge?

**Comment by tdiesler** [comment]
@davsclaus yes

**Comment by tdiesler** [comment]
@davsclaus when it passes QA, it is always good to go. As I work my way through the TCK, stuff may change in a later PR

**Comment by davsclaus** [comment]
the failed test are in core not hyperledger

**Pull request merged**
