### PR TITLE
Document update

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Change in the sentence from "The value are in seconds and the default is 5 seconds." to "The values are in seconds and the default value is 5 seconds."

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This is autogenerated from javadoc or description, so you'll need to change this in the java class https://github.com/apache/camel/blob/master/core/camel-core-engine/src/main/java/org/apache/camel/model/FaultToleranceConfigurationCommon.java#L88

**Comment by NiteshKoushik** [comment]
Changes made in code section of the below link and created a PR #4200, I don't had an option of building the solution file, so that it can generate the desired output.
https://github.com/apache/camel/blob/master/core/camel-core-engine/src/main/java/org/apache/camel/model/FaultToleranceConfigurationCommon.java#L88

Please suggest, if I can do from my end.

**Comment by NiteshKoushik** [comment]
Should I close this request ? as the same changes is done #4200

**Comment by oscerd** [comment]
Yes, please

**Pull request closed without merging**
