### PR TITLE
Salesforce composite api external ids in body support

### PR DESCRIPTION
**Pull request by vspiliop**
Hope it is of use :-)

1. Introducing support for Salesforce Composite REST API (https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_composite.htm). I could not find any related jira..

2. Extending the salesforce maven plugin to generate of DTO(s) for doing updates via Salesforce External Ids in the “body” json field. 
` 
         "body" : {
              "Account__r":
              {
                "External_Id_Of_Account__c" : "123456"
              } ,
            "AnotherField__c":"1234"
          }
`
Related jira is https://issues.apache.org/jira/browse/CAMEL-10193. The implementation is the proposed solution mentioned in the discussion.

Thanks!!

### CODE REVIEW

**Comment by zregvart** [comment]
@vspiliop this is awesome thank you for this contribution. We don't usually add new features to patch branches and if its OK with you I would like this to be added to the next release of (2.21.x). I can rebase this on current master and create a PR so that you can review it also, would that be OK?

**Comment by vspiliop** [comment]
@zregvart Yes it is perfectly fine from my end. I am more than happy to see this on the latest Camel so I can upgrade as well!

Regards!

**Comment by jopierce** [comment]
@vspiliop wow, you literally read my mind. I was looking for composite support.. and here it is!
Thanks!

**Comment by oscerd** [comment]
Since the fix is done in #2085 I'm closing this.

**Comment by vspiliop** [comment]
Hello @oscerd ,

#2085 is strictly for the Composite API support (number 1), but not for the new feature mentioned in number 2 above.

**Comment by vspiliop** [comment]
Hi @oscerd,

#2085 only includes the composite api support (number 1 above), and not the feature mentioned in number 2 (https://issues.apache.org/jira/browse/CAMEL-10193).

**Comment by vspiliop** [comment]
Hi @zregvart,

Many thanks for https://github.com/apache/camel/pull/2085!

Just wanted to kindly express my strong interest in having feature number 2 (salesforce maven plugin related one) into an official Camel version. That you be great for me, as I will not have to maintain a separate jar for camel-salesforce.

Regards!

**Comment by zregvart** [comment]
Hey @vasilievip, thank you for doing this great work. It has prompted me to do a refactor on the Salesforce Maven Plugin ([CAMEL-12043](https://issues.apache.org/jira/browse/CAMEL-12043)) and I've started to work on that first. Then I'll incorporate the additions for lookups you added here also (for [CAMEL-10193](https://issues.apache.org/jira/browse/CAMEL-10193)). I hope to have all of this for 2.21, and very soon in `master`. Thank you for your contribution 👍. I'll notify you here when it's all done.

**Comment by vasilievip** [comment]
@zregvart, no problem, glad to help
BTW: you probably wanted to say thank you to @vspiliop

**Comment by zregvart** [comment]
@vasilievip and @ vspiliop thank you both for contributing, stay tuned...

**Comment by vspiliop** [comment]
Thank you all for the great work! 👍

**Comment by davsclaus** [comment]
The master branch has moved on since this PR. What is the status, do we have something already, is this still needed, etc?

**Comment by zregvart** [comment]
> The master branch has moved on since this PR. What is the status, do we have something already, is this still needed, etc?

I've rebased and worked on this in a separate branch in my fork. I think we can close this.

**Comment by davsclaus** [comment]
Ok closing

**Comment by vspiliop** [comment]
Hello @zregvart,

Is there a jira or PR that I can follow for the introduction of external ids support (number 2 in the PR description)? It is quite important for the company I am working to drop our local fork and use the official camel-salesforce version once done.

Many thanks again!

**Comment by jeremyross** [comment]
Hi @zregvart, did specifying lookup relationships with an external Id, i.e. the "__r" suffix, ever make it into master/

**Comment by zregvart** [comment]
@jeremyross if you're thinking of this issue [CAMEL-12963](https://issues.apache.org/jira/browse/CAMEL-12963), it was merged to  master, 2.24.0, 2.23.3 and 2.22.5, see https://github.com/apache/camel/commit/1eb6a7ad79ffa47ce6f108a5bb302acc2a0ac243

**Pull request closed without merging**
