### PR TITLE
CAMEL-15326: fix incorrect handling of API responses

### PR DESCRIPTION
**Pull request by orpiske**
Includes:
- fix a NPE thrown when the slack conversation.list request fails
- report missing scopes when polling data from Slack

[x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[x] Each commit in the pull request should have a meaningful subject line and body.
[x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by orpiske** [comment]
With this patch, if there are errors ... For example, if the Slack permissions/scopes are missing, the error is raised and the details are logged. 

Here's an example of trying to poll messages from Slack without the proper scopes:

```
2020-07-22 15:40:02,816 [/opensourcetest] WARN org.apache.camel.component.slack.SlackConsumer - Consumer Consumer[slack://opensourcetest?maxResults=1&token=removed] failed polling endpoint: slack://opensourcetest?maxResults=1&token=removed. Will try again at next poll. Caused by: [org.apache.camel.RuntimeCamelException - API request to Slack failed: missing_scope]
org.apache.camel.RuntimeCamelException: API request to Slack failed: missing_scope
	at org.apache.camel.component.slack.SlackConsumer.checkSlackReply(SlackConsumer.java:171) ~[camel-slack-3.4.2-SNAPSHOT.jar:3.4.2-SNAPSHOT]
	...
```

**Comment by oscerd** [comment]
Thanks!

**Comment by oscerd** [comment]
Maybe we could backport to 3.4.x too. Can you please open a PR to camel-3.4.x branch?

**Comment by orpiske** [comment]
> Maybe we could backport to 3.4.x too. Can you please open a PR to [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).4.x branch?

Absolutely. I will open a PR with this patch for the 3.4.x branch, thanks!

**Pull request merged**
