### PR TITLE
(chores) camel-endpointdsl: use unique data directory for tests

### PR DESCRIPTION
**Pull request by orpiske**
This helps prevents misbehaved tests from causing other tests to fail

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by essobedo** [comment]
What about using the [TempDirectory extension](https://www.baeldung.com/junit-5-temporary-directory)?

**Comment by orpiske** [comment]
> What about using the [TempDirectory extension](https://www.baeldung.com/junit-5-temporary-directory)?

I confess I don't know about this one. Let me take a look and see how it goes. (so, please, don't merge it yet).

**Comment by essobedo** [comment]
If you don't want it to be merged, you should convert it to a draft

**Comment by orpiske** [comment]
> What about using the [TempDirectory extension](https://www.baeldung.com/junit-5-temporary-directory)?

So, this is a very cool feature of JUnit. I didn't know about it. However, I won't do this one for now. We have a lot more code that could be converted / cleanup with this, so I want to look at it with more time (please, do feel free to create an issue on Jira if you want).

**Review by oscerd — APPROVED** [review]

**Pull request merged**
