### PR TITLE
As slightly more typesafe impl of the connector mojo which leverages …

### PR DESCRIPTION
**Pull request by chirino**
…jackson object binding to do most of the json parsing and formatting.

### CODE REVIEW

**Comment by davsclaus** [comment]
I dont think this brings any value, and it also breaks the output now.

**Comment by davsclaus** [comment]
I didn't explain this to well. Sorry about that.

Today we improved the JSon schema that is generated by Camel and it uses boolean, numeric, types etc. This is done by ticket: https://issues.apache.org/jira/browse/CAMEL-10842

So we dont need this jackson and can rely on the same parser all over in Camel.

**Comment by chirino** [comment]
@davsclaus I don't fully understand where it's breaking the output.  Is there a failing test case or perhaps you can point me to example that causes a failure?

**Comment by davsclaus** [comment]
Camel is now already more type-safe in the generated json schema. Jackson is not needed. Instead we use the same parser all around in Camel.

**Comment by chirino** [comment]
@davsclaus I'm mostly trying to take fix code like can be seen at:
https://github.com/apache/camel/pull/1470/files#diff-419cb00ca9372e6591f0fc003d48fda9L357
which will break json encoding depending on content of what's in the description.  Better to have a clean data model and let jackson properly encode the json.

**Comment by davsclaus** [comment]
The description is being sanitized for invalid content
https://github.com/apache/camel/blob/master/connectors/camel-connector-maven-plugin/src/main/java/org/apache/camel/maven/connector/JSonSchemaHelper.java#L249

**Pull request closed without merging**
