### PR TITLE
CAMEL-10901 Implemented support for Kafka consumer to seek to either ...

### PR DESCRIPTION
**Pull request by sverkera**
… beginning or end of topic on startup

### CODE REVIEW

**Comment by oscerd** [comment]
Since we are changing the old behavior maybe it can be better if you add something in the .adoc file.
I mean a little section where you describe how the behavior changed.

**Comment by davsclaus** [comment]
Yeah the seek to beginning is from CAMEL-9716. So it may be better to have seekToEnd as new option, so its backwards compatible

**Comment by sverkera** [comment]
I did implement at first like Claus suggests, but as these are conflicting parameters and the usual way to implement that in Camel is to use an enum I changed to that instead.

As seekToBeginning functionality was added in 2.19.0-SNAPSHOT it has never been part of a release version and hence it is better in my opinion to keep consistent with how other parameters are handled. I have added a note in the description about it as Andrea suggests.

**Comment by davsclaus** [comment]
Its in the 2.18.x releases
https://github.com/apache/camel/blob/camel-2.18.x/components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java#L98

**Comment by sverkera** [comment]
Ok, it wasn't mentioned on http://camel.apache.org/kafka.html and fix version of CAMEL-9716 said 2.19.0 so that was why I missed it.

Still in my opinion it is better to keep consistency but if you prefer I can implement it as seekToEnd and throw an exception if they are set to conflicting values.

**Comment by davsclaus** [comment]
Yeah its better with a seekToEnd option.

**Comment by oscerd** [comment]
We will wait for your fix, by the way add a note in the docs with an example would be nice

**Comment by sverkera** [comment]
There are no backwards compatibility anyway on the kafka component between 2.19.x and 2.18.x as there are fundamental changes in how brokers and topic are specified:

2.18.x:
kafka:mybrokers?topic=mytopic

2.19.x:
kafka:mytopic?brokers=mybrokers

**Comment by davsclaus** [comment]
You can have a point  that users would need to migrate and that seek to beginning was only added in 2.18.x so its only 1 release back.

So we can likely just do the seekTo stuff. And add a note in the 2.19 release note about the option change

**Comment by sverkera** [comment]
I would vote for that but it's up to you to decide.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by oscerd** [comment]
I was waiting for your opinion before merging @davsclaus 

By the way that's fine :-)

**Comment by sverkera** [comment]
Thank you

**Pull request closed without merging**
