### PR TITLE
Close GroovyClassLoader

### PR DESCRIPTION
**Pull request by apupier**
it avoids to have files that can't be deleted on Windows

### CODE REVIEW

**Comment by zregvart** [comment]
@apupier thank you for this, do you mind opening a JIRA issue for this and mentioning it in the commit message? thanks 🥇

**Comment by davsclaus** [comment]
Also mind about checkstyle error, eg run

     mvn compile -P sourcecheck

in that directory and fix what it reports as errors

**Comment by davsclaus** [comment]
A JIRA is not so needed as this is new functionality that has not been in a release before.

**Comment by davsclaus** [comment]
i just fixed and merged this

**Pull request closed without merging**
