### PR TITLE
Example for camel-geocoder-starter

### PR DESCRIPTION
**Pull request by manosbatsis**
Was just passing through trying out camel and the geocoder component, thought it might be proper to try producing a sample while at it

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks. I think the servlet is automatic configured (you may not need that @Bean), and you can configure the path from spring boot application.properties which is likely nicer.

**Comment by manosbatsis** [comment]
Good point, replaced the servlet bean with the camel-servlet-starter dependency

**Comment by davsclaus** [comment]
For Camel with SB its better to use the -starter modules, and you don't need to have the regular component name also, eg camel-servlet-starter is fine, dont need to have camel-servlet also. There is a camel-jackson which should be camel-jackson-starter instead etc.

**Comment by manosbatsis** [comment]
Nice, Hadn’t noticed all the available starters. Same for the redundant deps in the POM. I'm fresh here but rather late anywhere else. Please let me know if you find anything else..

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by manosbatsis** [comment]
You are welcome, cheers.

**Pull request closed without merging**
