### PR TITLE
CAMEL-13807: Add Component DSL fluent builders

### PR DESCRIPTION
**Pull request by omarsmak**
This PR implements components DSL according to CAMEL-13807. Few notes:

1. To use it to create a component, it can be used like this `ComponentsBuilderFactory.kafka().setBrokers("{{host:port}}").build()`
2. Since I needed to maintain the POM file and `ComponentsBuilderFactory` interface, I used a metadata json file to keep track on the generated DSL classes and update whatever needed. 
3. To set the properties, I used component property configurer since it generates what is needed and I made use of that. 
4. Since I used the metadata file approach, the build speed wasn't impacted much which is good.
5. If the placeholder needs to be resolved, the component needs to be built with the context being passed as parameter: 
`ComponentsBuilderFactory.kafka().setBrokers("{{host:port}}").build(camelContext)`
6. There are a lot of shared functionality between endpoinsDslMojo and componentsDslMojo, hence 
I have created an abstract class for both and helpers that can be shared in both. However, I left EndpointDslMojo untouched for now. Will remove some shared core once I am done from this PR. 

Topics need to be done:

- [x] Fix checkstyle.
- [x] Add unit tests for the maven plugin generators.
- [x] Add more unit tests for `camel-componentDsl`.
- [x] Optimize some classes on the go.

### CODE REVIEW

**Comment by omarsmak** [comment]
Build is green. PR is ready for review

**Comment by oscerd** [comment]
@davsclaus @gnodet can you give a look?

**Comment by gnodet** [comment]
At first glance, I would think about switching to a more "fluent" way using  `allowReplyManagerQuickStop` instead of `setAllowReplyManagerQuickStop`.
I'll try to build this locally and dive deeper this evening.

**Comment by omarsmak** [comment]
@gnodet correct me if I am wrong, now with the scope provided for the dependencies, the user will have to explicitly add the component in the `pom` file  of his/her project besides the component-dsl dependency, or maybe you mean something else perhaps?

**Comment by omarsmak** [comment]
I relized we have the component's class name in the metadata json file, hence we can load the component with reflection and the user can cast it:
`final KafkaComponent kafkaComponent =(KafkaComponent)ComponentsBuilderFactory.kafka().buildTesting();`  
I am just not fan of reflections in general, however I am not sure what could be a better approach for this :/

**Comment by gnodet** [comment]
@omarsmak i missed the provided scope, that looks good with it.

So 2 points:
  * use "fluent" names, without the `setXxx`
  * i'm not at ease with the way the components are created in  https://github.com/omarsmak/camel/blob/CAMEL-13807/core/camel-componentdsl/src/main/java/org/apache/camel/builder/component/AbstractComponentBuilder.java#L30-L54 

I think we should modify `build` methods to not initialize the component and maybe create the property configurer to not rely on the existence of a `CamelContext`, so rather a single method doing something around:
```
    public C build() {
        final C component = buildConcreteComponent();
        PropertyConfigurer propertyConfigurer = component.getComponentPropertyConfigurer();
        if (propertyConfigurer == null) {
            org.apache.camel.spi.annotations.Component ann = ObjectHelper.getAnnotation(this, org.apache.camel.spi.annotations.Component.class);
            String name = ann.value();
            // just grab first scheme name if the component has scheme alias (eg http,https)
            if (name.contains(",")) {
                name = StringHelper.before(name, ",");
            }
            propertyConfigurer = new DefaultFactoryFinder(new DefaultClassResolver(null),
                        "META-INF/services/org/apache/camel/configurer/")
                    .newInstance(name + "-component", PropertyConfigurer.class)
                    .orElse(null);
        }
        configureComponentProperties(component, (GeneratedPropertyConfigurer) propertyConfigurer);
        return component;
    }
```

**Comment by omarsmak** [comment]
@gnodet Thanks a lot for the hints!

Yeah, I wasn't happy about initializing the component in the build method, the reason was because I wanted the `PropertyConfigurer` to set the properties. Then I shall do on what you suggested, to load PropertyConfigurer explicitly, not from the camel context. 
Sure, I will add some examples (camel-kafka-example).

**Comment by omarsmak** [comment]
@gnodet , I have a question regarding the usage of the came context in the `PropertyConfigurerSupport`, as I can see [here](https://github.com/apache/camel/blob/master/core/camel-support/src/main/java/org/apache/camel/support/component/PropertyConfigurerSupport.java#L40), it loads type converter from the camel context in order to convert the value before setting it into the component. As a result, this could be an issue if we want to avoid using the camel context as is being needed by the `PropertyConfigurerSupport`. However, I was thinking of couple ideas to go around it:

- Since we don't need the value conversion as long the values being set in type safe manner, we extend `PropertyConfigurerSupport` to support casting values using the provided type as well as the type converter from the context.
- We set the values in the componentdsl directly, so we need generate setters similar to the propertyConfiguer. However, this is the least option I prefer as it sounds to me is double work for something has been done pretty well by the property configurer.

What do you think?

**Comment by gnodet** [comment]
@omarsmak you're right, i missed the fact that the property configurer requires a CamelContext.
A first option is to mandate the use of the CamelContext and pass it to the builder when the builder is created, this would obviously alleviate the problem about using a 

But if we don't use conversion and use direct values, why not setting them directly given we already depend on the component ? i.e., the builder instantiates the component at the beginning, and then, we just call the setters directly, this would avoid the need for property configurer completely.

Another option, would be to create  a "dumb" component, that would delay the instantiation / injection of real component and delegate to it, thereby ensuring we have a proper camel context and relying on the existing mechanism.  That would be closer to the Endpoint DSL.

**Comment by omarsmak** [comment]
@gnodet yes, you are right. In the matter of fact, I am now changing to just set it directly on the component instead of the property configurier. It turns out to be simple actually :D 
I will push the commit soon.

**Comment by omarsmak** [comment]
@gnodet I have pushed a new commit with the following fixes:
- Changed to fluent methods without `set`.
- Removed `PropertyConfigurerSupport` and replaced it with generated setters that is lazley initialized. It happens in the `build` method. 
- Added a an example using `camel-kafka`. 

Please take a look and let me know.

**Comment by davsclaus** [comment]
There are a lot of changed files here, would it be possible to just post a snippet of how for example you can use this to configure Kafka, eg you mentioned the camel-kafka-example etc.

**Comment by omarsmak** [comment]
Sure, here is an example:
```
KafkaComponent kafka = ComponentsBuilderFactory.kafka()
                        .brokers("{{kafka.host}}:{{kafka.port}}")
                        .build(camelContext);
```
Or from the unit tests:
```
 KafkaComponent kafkaComponent = ComponentsBuilderFactory.kafka()
                .allowManualCommit(true)
                .configuration(kafkaConfiguration)
                .brokers("localhost:9092")
                .build();
```
Note: In order to resolve the placeholders, the camel context needs to be passed in the build method

**Comment by davsclaus** [comment]
Ah thanks, yeah that looks lovely.

For the placeholders then maybe we can have a ComponentsBuilderFactory instance you can dependency inject etc

```
@Inject
ComponentsBuilderFactory cb
```

Which will have CamelContext out of the box. But lets wait with this kind and get a first cut implemented first. Looks cool. And it has javadoc on the methods like the endpoint dsl ?

**Comment by davsclaus** [comment]
Also there could be a method that registers the component to CamelContext with an optional name etc

 .register(camelContext, "mykafka");

**Comment by omarsmak** [comment]
Yes, it has everything generated, very similar to the endpointdsl. 
Sure, I can add one `register` API  besides `build` API. So we can have the following:

- `Component build()`/  `Component build(camelContext)` -> Build a component and returns back as return type. 
-  `void register(camelContext, name)`  -> Build and register component to the camel context

**Comment by dmvolod** [comment]
@omarsmak , I'm not sure, but looks like you are missing just one thing, there are set of components (a few but important) which contains set of components inside. 
For example camel-mail
https://github.com/apache/camel/blob/f33587010d210c9152d1c30e439b5caf75866eaa/components/camel-mail/src/main/java/org/apache/camel/component/mail/MailComponent.java#L39

but ComponentsBuilderFactory set only imap for camel-mail

**Comment by omarsmak** [comment]
Ahh, thanks @dmvolod for the hints, I will take a look what we can do about.

**Comment by omarsmak** [comment]
@davsclaus @dmvolod I have pushed a new commit with that fixes the component aliases not being generated and add a new `register` API, e.g: 
```
ComponentsBuilderFactory.kafka()
                        .brokers("{{kafka.host}}:{{kafka.port}}")
                        .register(camelContext, "kafka");
```

**Comment by omarsmak** [comment]
If there is no further comments, I would like to squash and merge this PR today

**Comment by davsclaus** [comment]
Yeah I think it seems good, would really like to have this, and we can then improve on it.

**Comment by davsclaus** [comment]
The componentdsl cannot compile - error in camel-hdfs. Also camel-jira needs a 3rd part repo (i may add that to the pom.xml).

**Comment by davsclaus** [comment]
Also it may be that the generated code in the dsl is not sorted a..z either, eg so when others compile they may get a different order and the code is changed. eg make it sort so components that start with a in the top and so on.

**Comment by davsclaus** [comment]
Okay with latest code and doing a full rebuild it seems the camel-hdfs issue is gone.

**Comment by omarsmak** [comment]
Yeah that sort issue has to be addressed

**Comment by davsclaus** [comment]
btw I wonder if we have a catch-22 situation. That the componentdsl, requires all components to be pre-build, eg what if you have a empty m2 repo and build from 100% scratch

**Comment by omarsmak** [comment]
A full rebuild? I am curious about it, let me give a test :D

**Comment by oscerd** [comment]
After merging this each time I rebuild (full rebuild) I'm getting these files modified

#	modified:   core/camel-componentdsl/pom.xml
#	modified:   core/camel-componentdsl/src/main/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java
#	modified:   core/camel-componentdsl/src/main/java/org/apache/camel/builder/component/dsl/SparkComponentBuilderFactory.java
#	modified:   core/camel-componentdsl/src/main/java/org/apache/camel/builder/component/dsl/WebsocketComponentBuilderFactory.java
#	modified:   core/camel-componentdsl/src/main/resources/metadata.json
#	modified:   core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/SparkEndpointBuilderFactory.java

**Comment by omarsmak** [comment]
Yeah is because of the order. Pushing a fix for it now to have it ordered

**Comment by gnodet** [comment]
@oscerd @omarsmak @davsclaus I'm working on a fix to stabilize the generation while merging those changes in my local branch, I should push very soon.

**Comment by omarsmak** [comment]
Hey @gnodet I pushed a PR https://github.com/apache/camel/pull/3541 before saw your message to fix it. If you are already pushed it, please feel free to push it and I can close that PR

**Pull request merged**
