### PR TITLE
CAMEL-12246 Fix broken links

### PR DESCRIPTION
**Pull request by fbolton**
@davsclaus and @oscerd, here are the changes to the AsciiDoc linking that we discussed. Here's a summary of what was done:

* Resolve the duplicate IDs (can't do any harm, and is actually required for our downstream builds)
* Take into account the -eip suffix, which might reduce the number of unresolved links.
* All resolvable links to be transformed to AsciiDoc cross-reference format, as follows:
```
link:LINKNAME.html[Text of Link]  =>  <<LINKNAME, Text of Link>>
```
  Where, in some cases, `LINKNAME` might be augmented by a `-component`, `-dataformat`, `-language`, or `-eip` suffix.
* Identify the broken EIP links and leave them alone. These will continue to show up as broken links, but we can easily fix them later.
* All other unresolved links will be removed. Probably do this by replacing:
```
link:LINKNAME.html[Text of Link]   =>  Text of Link
```

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks for the PR :-)

**Comment by oscerd** [comment]
This will work once the docs will be generated, but actually with this the link won't work in Github.

@davsclaus do we have to revert?

**Comment by fbolton** [comment]
@oscerd yes, but I have the impression that most links were already broken in GitHub anyway. For example, if you look at the camel-http doc page in the commit *before* this PR was merged:
https://github.com/apache/camel/blob/ee26d31bcc10fad113fa46cbf0bf4b36f9f0cfbc/components/camel-http/src/main/docs/http-component.adoc

Search for the link to "Jetty Component". When you click on it, you get a 404. My impression is that this is fairly typical of the links that were already there.

**Comment by oscerd** [comment]
Yeah, true. You're right.

**Pull request closed without merging**
