### PR TITLE
export-component-csv mojo for exporting the list of components to CSV

### PR DESCRIPTION
**Pull request by ppalaga**
I just wrote this to export the list of components to CSV. I thought this might be useful for others in the future.

### CODE REVIEW

**Comment by ppalaga** [comment]
bbccbf6 fixed the style violations

**Comment by davsclaus** [comment]
This is quarkus specific, this should be made vanilla

**Comment by ppalaga** [comment]
> This is quarkus specific

I think that statement is stronger than the reality. The mojo is Camel specific with one optional Camel Quarkus parameter that fills the "Supported on Camel Quarkus" column. If that param is not provided, all values in that column are left blank. Similar params can eventually be added in the future for Karaf and SpringBoot so that the mojo can be used for exporting a full platform support matrix.

**Comment by oscerd** [comment]
You're welcome to add the karaf and sb part too

**Comment by ppalaga** [comment]
Not a priority ATM, sorry.

**Comment by janstey** [comment]
I think this is still valuable. Let's leave it open. I wonder can we merge this and open JIRAs for Karaf and SB to be added later?

**Comment by oscerd** [comment]
What to do with this?

**Comment by omarsmak** [comment]
Are we planning to do anything with this PR? If no longer needed, I'd say then we close it

**Comment by oscerd** [comment]
Eventually someone will revive this.

**Pull request closed without merging**
