### PR TITLE
Fix up documentation of Camel Milo

### PR DESCRIPTION
**Pull request by ctron**
This change fixes up the documentation of the camel-milo component. This
includes a fix of the node id table, which was rendered in a corrupt
format.

### CODE REVIEW

**Comment by oscerd** [comment]
@davsclaus was faster :-)

**Comment by davsclaus** [comment]
The old man can still click on a button - this circus horse can still play some tricks and are not yet ready for being retired.

**Comment by oscerd** [comment]
I lost the race, because I click on approve first :-D

**Comment by davsclaus** [comment]
Ahh yeah you need a couple of more years to have that privilege with just click a single button ;)

**Pull request merged**
