### PR TITLE
camel-ftp - SftpOperations should set byte[] instead of OutputStream …

### PR DESCRIPTION
**Pull request by tadayosi**
…for exchange file body

Otherwise simple SFTP-to-File integrations like:

    from("sftp://sample@localhost:2222/in?password=password&delete=true&charset=Shift_JIS")
        .to("file:/tmp/samples-camel/SftpToFileTest/out?charset=EUC-JP");

fails.

The changed code is mostly identical to that of `FtpOperations`.

Thanks!

https://issues.apache.org/jira/browse/CAMEL-12724

### CODE REVIEW

**Comment by davsclaus** [comment]
You should log a JIRA ticket, or in other ways discuss this first (with such a code change). What does it fail with, and is it only because you have set charset options. Loading into memory is not desireable as the files may be big and cause OOME.

**Comment by tadayosi** [comment]
@davsclaus OK, I can log a JIRA, but note that the FTP counterpart has had the same behaviour already:
https://github.com/apache/camel/blob/camel-2.22.0/components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java#L429-L434

Loading into memory and potential risk of OOME may be another issue.

**Comment by davsclaus** [comment]
Ah okay there is a streamDownload option for the streaming behavior, then this change seems okay and as you say would be similar to the regular FTP

**Comment by tadayosi** [comment]
And yes, the `charset` option is the key here. I tried the same reproducer without the option but didn't see the issue.

Please wait for me to file a JIRA and update the pull req accordingly. Thanks.

**Comment by davsclaus** [comment]
Ah okay, yeah the charset option requires to load the data into memory so you can do the charset encoding.

**Comment by tadayosi** [comment]
JIRA created https://issues.apache.org/jira/browse/CAMEL-12724 and commit commend adjusted. Please review and merge it if it's okay.

**Pull request merged**
