### PR TITLE
CAMEL-10491 - Spring-LDAP - Utilizing java.util.function.BiFunction (Java 8) for FUNCTION_DRIVEN operation.

### PR DESCRIPTION
**Pull request by bhaveshdt**

### CODE REVIEW

**Comment by davsclaus** [comment]
This is a little API breaking for old users whom may have been using that LdapOperations api in the past. So they would need to migrate to use Java 8 BiFunction now.

What is the benefit of this, except for using that Java 8 API instead?

Is that what spring-ldap project is recommending users to do?

**Comment by bhaveshdt** [comment]
I read that 2.18.0 release onwards Java 8 is required (http://camel.apache.org/camel-2180-release.html) and felt obligated to update my earlier patch to make use of Java 8. This patch and the earlier one are being made in 2.19.x and did not exist in prior releases.

**Comment by oscerd** [comment]
@davsclaus this will be only in 2.19.0, if you think this is breaking change we can leave the situation as it is now.

**Comment by davsclaus** [comment]
Ah not its fine with a little change in a minor release. Just add it to the API breaking section in the release notes: http://camel.apache.org/camel-219-release.html

+1

**Comment by oscerd** [comment]
Ok, I will merge soon :-)

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close this?

**Comment by bhaveshdt** [comment]
Thank You!

**Pull request closed without merging**
