### PR TITLE
Update because of class cast

### PR DESCRIPTION
**Pull request by richardgroote**
See CAMEL-11892

### CODE REVIEW

**Comment by onders86** [comment]
Imho, this can be workaround. Because in this case, breadcrumb id is not read from transport headers and is not set as pteviously done for saajsoapmessage. This brings assumptions...

**Comment by onders86** [comment]
please see this PR;

https://github.com/apache/camel/pull/2028

**Comment by onders86** [comment]
and it would be perfect if you could test and share your results.

**Comment by richardgroote** [comment]
This works fine

**Pull request closed without merging**
