### PR TITLE
Fixed the Defect manual commit not working

### PR DESCRIPTION
**Pull request by mchandwani**
partitionLastOffset value always remains -1 so consumer.commitSync is never called in method commitOffset

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR. Because it was a bug fix, it would have been good next time to log a JIRA ticket first and then refer to the CAMEL-NNNN number from the commit log message.

**Comment by mchandwani** [comment]
Thanks for information. I have one question we are using 2.21 version of
this component. In which version this fix will be available to be
downloaded as maven dependency?

**Comment by davsclaus** [comment]
2.21.1 and 2.22.0

**Comment by mchandwani** [comment]
hello claus,

I am facing issues when using manual commit. It commits the offset as soon
as it is retrieved and using autocommit disable properties dont work
properly. I need to open a ticket for this but not able to do so.
can you provide me the appropriate link for opening the ticket where i can
put the issue i am facing.

Thanks,
Mukesh

**Comment by oscerd** [comment]
Here you are:

https://issues.apache.org/jira/projects/CAMEL/issues

**Comment by mchandwani** [comment]
Thank you for assistance. created issue  CAMEL-12525
<https://issues.apache.org/jira/browse/CAMEL-12525>

**Pull request merged**
