### PR TITLE
CAMEL-16179: prevent a NPE on the MongoDB component if unable to resolve the DB connection

### PR DESCRIPTION
**Pull request by orpiske**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by davsclaus** [comment]
It would be good to make this autowried = true so the component will auto configure it present
https://github.com/apache/camel/blob/6377a997c2a831ab8fc80cf5eca7d552c94bc18a/components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbComponent.java#L43

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
> It would be good to make this autowried = true so the component will auto configure it present
> 
> https://github.com/apache/camel/blob/6377a997c2a831ab8fc80cf5eca7d552c94bc18a/components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbComponent.java#L43

Thanks Claus, let me give it a try with that instead.

**Comment by davsclaus** [comment]
Oh just mind that the autowried will just do this once. You NPE fix is also correct, in case there was no mongodb client at all.

**Comment by orpiske** [comment]
> Oh just mind that the autowried will just do this once. You NPE fix is also correct, in case there was no mongodb client at all.

Ahh, thanks for the clarification. I will keep the original changes + the autowired.

**Review by davsclaus — APPROVED** [review]

**Review by omarsmak — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
