### PR TITLE
CAMEL-15105: move handling of internal services to a separate class

### PR DESCRIPTION
**Pull request by orpiske**
This helps further work to decouple and standardize the extension/plugin management

### CODE REVIEW

**Comment by orpiske** [comment]
How about Proxy? Looking at what I have to do next, it will end up changing to a proxy instead of a facade.

**Comment by davsclaus** [comment]
its not really a proxy, its some thing that helps with add a service internally in camel, to make sure its done in the correctly.

**Comment by orpiske** [comment]
> Okay but what is the reason for introducing a proxy - that is something we should avoid, and leave objects as-is.

I may have confused you because I am talking about not about this change, but the upcoming one. The proxy I am talking about is the [Proxy design pattern](https://refactoring.guru/design-patterns/proxy).  

As in: 

Current state (tightly coupled) -> evolves to Facade (which I'll name as Helper) -> then evolves to a Proxy. 

The reason it evolves to a Proxy is that then, in the future, we can simplify / more easily abstract the service handling. Alternatively I have been thinking of using a Bridge, but I am thinking it won't be as flexible.

**Comment by orpiske** [comment]
@davsclaus For this one, any other comments besides renaming it to Helper?

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
