### PR TITLE
upgrade spring-boot and spring

### PR DESCRIPTION
**Pull request by davidkarlsen**

### CODE REVIEW

**Comment by oscerd** [comment]
This will break the build:

`[ERROR] Failed to execute goal org.apache.camel:bom-generator-maven-plugin:2.22.0-SNAPSHOT:generate (default) on project camel-spring-boot-dependencies-generator: Found 2 conflicts between the current managed dependencies and the external BOMS:
[ERROR]  - org.apache.kafka:kafka-clients:jar
[ERROR]  - org.apache.kafka:kafka_2.11:jar
`

**Comment by davsclaus** [comment]
Okay so its likely because Spring Boot upgraded Kafka in their dependencies. To fix this in that BOM generator is a bit tricky as it has some "magic code" that checks for all weirdness.

**Comment by davidkarlsen** [comment]
I had a look, but didn't get any more bright.
Should this be fixed by aligning the version of kafka-version and kafka-bundle-version with the ones from boot?

**Comment by davsclaus** [comment]
Okay so its because they upgraded to Kafka 1.1.0, and we are using 1.0.1.

So @davidkarlsen can you try to do a PR to upgrade kafka to 1.1.0, so its aligned with Spring Boot. And create a JIRA so we have a ticket for it - IMHO its a little bit bigger upgrade of kafka (not only a patch)

**Comment by oscerd** [comment]
In 2.0.2.Final the version is still 1.0.1

**Comment by davsclaus** [comment]
Ah okay my bad. Hmm its a bit bad thing they did in a patch release.

**Comment by oscerd** [comment]
Yeah, in 2.0.1 they have only spring-kafka stuff, in 2.0.2 they introduced plain kafka dependencies

**Comment by davsclaus** [comment]
Okay I am working on a fix

**Comment by davsclaus** [comment]
Okay got it working and have merged this PR, thanks @davidkarlsen

**Pull request closed without merging**
