### PR TITLE
Optimize DefaultCamelContext#getComponent CAMEL-10269

### PR DESCRIPTION
**Pull request by ssharma**
#CAMEL-10269

Add DCL idiom to lower lock semantics and used CHM. Didn't retrofit put to use putIfAbsent as the change would have been instrusive

### CODE REVIEW

**Comment by oscerd** [comment]
I don't think it's a good idea using the double-checked locking mechanism: it is unsafe.

http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html

**Comment by ssharma** [comment]
I agree DCL is a broken premise for initializing objects. However, since ConcurrentHashMap is used and the happens before operation of 'put' will guarantee that the 'get' always returns a fully initialized object from the map.

Please correct me if I'm wrong. 

~Sid

**Comment by oscerd** [comment]
@davsclaus What do you think here?

**Comment by lburgazzoli** [comment]
As a first look I would say that you could have some benefits if the method is invoked with the same name but if you have a number of distinct names, the code is essential the same as the original one.

I would instead explore the possibility to use a "map of locks", like:

```
synchronized(acquireObjectLock(name)) {
   ...
}
```

Indeed, I do not know the impact.

**Comment by ssharma** [comment]
@lburgazzoli The goal is to avoid global lock on the map when some component is already initialized. 

E.g. Assume component 'B' and 'C' are already initialized and 'A' is not initialized. Now, if 3 threads are invoked in below sequence, Thread 2 and 3 would block as long as 1 finishes initialization and starting of component.

1. Thead A -> getComponent(A)
2. Thread B -> getComponent(B)
3. Thread C -> getComponent(C)

**Comment by lburgazzoli** [comment]
The scope is clear but I'm wondering if we could do it better, maybe using CHM::computeIfAbsent ?

**Comment by ssharma** [comment]
I'm not sure if Camel 2.18 uses Java 8 patterns. If yes, then CHM::computeIfAbsent is great!

**Comment by lburgazzoli** [comment]
Yes it does ;)

**Comment by ssharma** [comment]
Great! I will submit a new PR with revised Java 8 code

**Comment by ssharma** [comment]
Closing this PR as by mistake pulled 2 unwanted files. A new PR has been opened to track this
https://github.com/apache/camel/pull/1152

**Pull request closed without merging**
