### PR TITLE
align output log

### PR DESCRIPTION
**Pull request by Croway**
```
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/   (POST) (accept:application/json produce:application/json)
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/dev    (produce:text/plain,application/json)
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/health    (produce:application/json)
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/jolokia    (produce:text/plain,application/json)
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
You can maybe do so '%s:30.30` or whatever syntax to make the text more aligned as 3 columns in a spreadsheet.

You can also loop the lines and calculate the longest and then adjust the `%sN..N` syntax accordingly.

**Comment by orpiske** [comment]
I wonder if there's a project that we could use that could take a bean as input and would pretty print the information as the output. 
Quite frankly, this is very hard to read.

**Comment by orpiske** [comment]
Obs.: no talking about your proposal. Just venting my frustration that we have to keep concatenating strings and doing a lot of ifs and elses on the code. 

IMHO, the view should always be separated from the other layers on the code.

**Comment by Croway** [comment]
@orpiske I agree, I was thinking about using some kind of template, but seems a bit overkill for this use case, the latest commit uses format with `%-Ns` and seems a bit more readable, I am open to using some kind of template though.

**Comment by orpiske** [comment]
> @orpiske I agree, I was thinking about using some kind of template, but seems a bit overkill for this use case, the latest commit uses format with `%-Ns` and seems a bit more readable, I am open to using some kind of template though.

Yeah. I think the proposed change is OK given the constraints we have right now. 

Longer term, I think we need to find something that could be used globally on the code and would allow us to separate the (usually messier) presentation code from the rest.

**Comment by davsclaus** [comment]
we use a table printer library in jbang

**Comment by orpiske** [comment]
> we use a table printer library in jbang

That one looks pretty cool

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
