### PR TITLE
Update DefaultHeaderFilterStrategy.java

### PR DESCRIPTION
**Pull request by amassana**
Flexible outcome when there is amatch against a pattern or filter. Before a match meant to reject a given header and to accept anything else. Now this can be reverted: accept only some headers based on the pattern / filter, reject anything else.

### CODE REVIEW

**Comment by oscerd** [comment]
And I miss the advantage related to this PR. That's why I'm asking to raise a JIRA

**Comment by davsclaus** [comment]
Yes we need to have more details of the use-cases for this. And we would need unit tests as well.

**Comment by amassana** [comment]
In my particular case, I am sending a JMS message to a remote system and I'm requested to add some additional headers to the JMS message. But of course I don't want to send more headers / info from my route to the target system.

The current implementation keeps anything except what you ask it to remove. With this change you'd only keep what you need to send.

I created as suggested an entry in JIRA, CAMEL-13116.

I hope the use case clear. The change is quite simple. I can provide unit tests if needed - can you forward me some existing example you'd accept?

**Comment by davsclaus** [comment]
I think we can use a better name for the option that actionOnMatch.

**Comment by davsclaus** [comment]
And we need unit test for covering this change/functionality as well

**Comment by oscerd** [comment]
any news on this one?

**Comment by amassana** [comment]
The property has been renamed, test cases were added and the documentation was updated.

**Comment by dmvolod** [comment]
@amassana , could you please rebase on actual master

**Pull request closed without merging**
