### PR TITLE
Add Lumberjack component

### PR DESCRIPTION
**Pull request by adessaigne**
The camel-lumberjack component allows to receives log streams over the lumberjack protocol. For instance it can receives logs from Filebeat.

### CODE REVIEW

**Comment by davsclaus** [comment]
Is there a reason why you have 2 component lumberjack and lumberjacks ?

**Comment by adessaigne** [comment]
Hello Claus,

You have `lumberjack` and `lumberjacks` because the first one is without SSL and the second one is with SSL. Why I used 2 classes :
* In the endpoint, you can ensure that the secured version has the SSL configuration defined
* It avoid checking against the component name
* It's 2 classes that are really easy to write
* The 2 versions use the same consumer in the end

That being said, if you prefer, I can update the code to use only one component class and one endpoint class.

**Comment by davsclaus** [comment]
Yeah can you make this 1 component/endpoint.

**Comment by adessaigne** [comment]
Ok ! I'll do that on Monday, I'm nowhere near my dev computer.

In order to do it properly,can you answer these functionnal questions :
A. When using `lumberjacks`, should I ensure that `sslContextParameters` is filled ?
B. When using `lumberjack` and you configured `sslContextParameters`, does it : use SSL ? ignore SSL ? put a warning ? throw an exception ?

**Comment by davsclaus** [comment]
No there should only be 1 endpoint, lumberjack. If you want SSL you set the SSLContextParameters.

**Comment by adessaigne** [comment]
OK, I'll do that !

**Comment by adessaigne** [comment]
Hi Claus,

I've updated the pull request with your remarks. So, from now on, we no longer create new component versions for SSL (like `ahc-wss`, `cometds`, `ftps`...) ?

**Comment by davsclaus** [comment]
The PR has a test that seems flaky. I get always this error on the 1st run

Running org.apache.camel.component.lumberjack.LumberjackComponentSSLTest
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.91 sec <<< FAILURE! - in org.apache.camel.component.lumberjack.LumberjackComponentSSLTest
shouldListenToMessagesOverSSL(org.apache.camel.component.lumberjack.LumberjackComponentSSLTest)  Time elapsed: 1.466 sec  <<< FAILURE!
java.lang.AssertionError: expected:<[10, 15]> but was:<[15]>
	at org.apache.camel.component.lumberjack.LumberjackComponentSSLTest.shouldListenToMessagesOverSSL(LumberjackComponentSSLTest.java:75)

**Comment by adessaigne** [comment]
I'll have a look, sorry about that.

**Comment by davsclaus** [comment]
No problem. I have merged this PR. Do you mind create a new PR if you have a fix for the flaky unit test?

Also I added a test for spring-boot in tests/camel-itest-spring-boot

**Comment by adessaigne** [comment]
Thank you very much for merging it !

**Comment by adessaigne** [comment]
I have created a new PR for the unit test https://github.com/apache/camel/pull/1077

**Pull request closed without merging**
