### PR TITLE
Removing unused parameters from method signature

### PR DESCRIPTION
**Pull request by lhsribas**
# Description

 I have worked on the following class removing the unused parameters from method signature.

# Tracking
- [Removing Unuse parameters from method signature] https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS1172&id=apache_camel

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks for your contribution @lhsribas. 

As I explained on ZulipChat, the PR is a little bit too big for us to review. Maybe try to break it into smaller pieces (one for `core`, another for `component`, etc).

**Comment by orpiske** [comment]
Folks, I've been giving some ideas/help for @lhsribas on his first contribution to Camel. Please, feel free to step in and provide more comments.

**Comment by rhuan080** [comment]
Hi, 

I would like to suggest using method overload to createBaseDescription and turning the method with unused parameters deprecated. Thus, you can change the call to the need method in many other PRs. I think it is more secure approach.

**Comment by orpiske** [comment]
This one has stalled, therefore closing.

**Pull request closed without merging**
