### PR TITLE
CAMEL-20563: shutdown existing consumer instance to release resources…

### PR DESCRIPTION
**Pull request by samipeltola81**
… (heartbeat) before creating new ones

# Description

Fix for "[CAMEL-20563](https://issues.apache.org/jira/browse/CAMEL-20563) camel-kafka - breakOnFirstError causes thread and memory leaks"

Closing existing Kafka client consumer instance releases heartbeat-threads started by ConsumerCoordinator.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by samipeltola81** [comment]
@oscerd should i to include the generated classes?

**Comment by oscerd** [comment]
@samipeltola81, No I guess it's a leftover from other PR, you're fine. @lburgazzoli @zbendhiba can you have a look at why the langchain embeddings metadata still talk about qdrant? Thanks.

**Review by davsclaus — APPROVED** [review]

**Review by orpiske — CHANGES_REQUESTED** [review]
FYI, the tests are not running due to (unrelated) uncommitted changes. So, it needs to be check manually or rebased to get the latest changes.

**Review by orpiske — APPROVED** [review]
I tested it manually and the tests seem to be running fine. LGTM.

**Comment by zbendhiba** [comment]
@oscerd Looking at the issue.

**Comment by oscerd** [comment]
@zbendhiba it should be fixed already. Thanks a lot anyway! It was a leftover of the generated json files.

**Comment by zbendhiba** [comment]
okay thanks

**Pull request merged**
