### PR TITLE
CAMEL-11832: Add support for Lambda

### PR DESCRIPTION
**Pull request by tlehoux**
This is a camel component for aws-lambda service. It allows to invoke lambda function with Camel. Beside, it allows to create function, get function, list functions and delete function (essentially for testing purpose).

### CODE REVIEW

**Comment by davsclaus** [comment]
There is some checkstyle you need to fix

    mvn compile -P sourcecheck

**Comment by davsclaus** [comment]
I wonder if those mandatory headers for role etc, cannot be optional so you can specify that in the endpoint uri as well. Having to use mandatory headers is a bit cumbersome.

Also are some of those roles the same for different functions, then maybe those can be configured globally on the lambda component class instead. And used as a fallback value if no explicit value was specified in the header or endpoint.

**Comment by tlehoux** [comment]
@davsclaus I dont have checkstyle issue on my side (maven-checkstyle-plugin:2.17). That's weird. What issues do you get ?

Regarding mandatory headers, there are only usefull for createFunction operation. So I'm not sure if it's relevant to configure them globally on the lambda component class. On the other hand, they are mandatory to create a lambda function (otherwise, a AWSServiceException is thrown). 

I put them as mandatory header because that's the way it's done for mandatory thing in others aws component (ec2 or S3 for example). That was for keeping consistancy between this component family.

I can put them as URI param and check if they are filled for createFunction processing. Let me know.

**Comment by davsclaus** [comment]
Okay as its only for the createFunction then its likely okay. I assume its the invokeFunction operation that would be the more commonly used.

**Comment by tlehoux** [comment]
You're right. Creating function in Lambda is much more something done with aws-cli or directly in AWS Lambda Console. I've added support for creating and deleting function essentially for testing purpose.

**Pull request closed without merging**
