### PR TITLE
[CAMEL-16567]: Set CamelContext on producer to fix mocking problem

### PR DESCRIPTION
**Pull request by dschulten**
fixes CAMEL-16567

* added test
* made InterceptSendToEndpointProcessor CamelContextAware to fix mocking problem

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you try in doBuild of the endpoint processor to do

CamelContextAware.trySetCamelContext(producer, endpoint.getCamelContext());

Instead of impl CamelContextAware and set it in the setter - a setter should ideally just be set.

**Comment by dschulten** [comment]
Great, I knew this one needed deeper knowledge of instance construction.

**Comment by davsclaus** [comment]
@dschulten let us know if you get a chance to update this PR

**Comment by dschulten** [comment]
working on it

**Comment by dschulten** [comment]
Changed fix is in

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
