### PR TITLE
CAMEL-11107: Create a new camel-grpc component

### PR DESCRIPTION
**Pull request by dmvolod**
Create a new camel-grpc component which allows to do Remote Procedure Call (RPC) Protocol Buffers (protobuf)] format over HTTP/2 transport.
Stage 1 - Producer with basic parameters and calling sync and async methods

### CODE REVIEW

**Comment by oscerd** [comment]
Hello @dmvolod thanks for this PR. I will review soon. :-)

**Comment by oscerd** [comment]
@dmvolod since we are about to start the release for 2.19.0 maybe we can postpone this new component to 2.20.0 and in this way you should be able to add the stage 2 features listed in the JIRA issue.

@davsclaus what do you think about?

**Comment by davsclaus** [comment]
Oh I think if the current code brings value then its okay to see if it can get into 2.19. And then we can add in the docs that more functionality is coming in 2.20 etc.

Its good to get new components out in the hands of the community for them to provide feedback.

I have not looked at all this code but at first glance it looks like it has usable functionality already.

**Comment by oscerd** [comment]
The code looks good. I already reviewed it a bit. So I'll merge it this week :-)

thanks @dmvolod and @davsclaus

**Comment by oscerd** [comment]
Thanks! The PR has been merged. Can you close this?

**Comment by dmvolod** [comment]
@oscerd , @davsclaus thanks a lot. PR closed.

**Pull request closed without merging**
