### PR TITLE
Camel-20439: move camel-cloudevent api to camel-api

### PR DESCRIPTION
**Pull request by jono-morris**
# Description

Moved camel-cloudevents api into camel-api and removed dependencies on this component.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
@christophd It should have some effect on camel k and quarkus too

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Update the 4.7 upgrade guide as well about this change

**Comment by davsclaus** [comment]
I wonder if you could merge `main` branch into this PR so its up to date, and can be tested

**Comment by jono-morris** [comment]
Yes, will do shortly.

**Pull request merged**
