### PR TITLE
Support for PATCH method in Rest DSL

### PR DESCRIPTION
**Pull request by spegelref**
Added new verb to the Rest model, the PatchVerbDefinition and made made
the jaxb parser aware of this new file.
Added instructions in RestDefinition and VerbDefinition on how to handle
this new verb.

### CODE REVIEW

**Comment by spegelref** [comment]
I didn't find any issue in the issue tracker for this. But I think this is a necessary feature to support in the Rest DSL.

**Comment by davsclaus** [comment]
What is your use-case for using PATCH

**Comment by arnaud-deprez** [comment]
Hi Claus,

Here is the use case for PATCH according to what I understand from here http://www.restapitutorial.com/lessons/httpmethods.html.
- PUT is used for an update/replace operation which means that the whole payload must be sent (including the fields we don't want to modify).
- PATCH is used for an update/patch operation which means that a partial payload can be sent where only present datas will be updated.

Rgds,

**Comment by spegelref** [comment]
Hi Claus,
As arnaud-deprez links, to send updates to instead of a full replace of a resource.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
