### PR TITLE
CAMEL-11532 Java DSL enhancement to accept supplier and function arguments

### PR DESCRIPTION
**Pull request by sermojohn**
@lburgazzoli the PR to master

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks @lburgazzoli I assume this looks good and if so we can get it merged

**Comment by sermojohn** [comment]
I do not have permissions to merge the PR to master, so I wait until merged and close the PR. Thanks

**Comment by sermojohn** [comment]
I looks like I cannot close it either.

**Comment by oscerd** [comment]
Already merged. Thanks.

**Pull request merged**
