### PR TITLE
CAMEL-11221- 409(which was a wrong default value) should have been 4096

### PR DESCRIPTION
**Pull request by onders86**

### CODE REVIEW

**Comment by davsclaus** [comment]
The commit message could likely have been better as its not a typo in the regular sense as a cosmetic message, its a wrong default value which is much more severe.

**Comment by onders86** [comment]
I thought former committer tried to write 4096 but instead accidentally wrote 409 by missing 6 at the end. that's why i logged it as typo fix. will update commit log.

**Comment by davsclaus** [comment]
btw do you mind check if we have the same problem in the camel-netty-http (eg the one using netty 3.x)

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by onders86** [comment]
camel-netty-http looks OK. thanks for accepting. closing.

**Pull request closed without merging**
