### PR TITLE
CAMEL-15520: replace deprecated maven property maven.test.skip.exec

### PR DESCRIPTION
**Pull request by chiragsanghavi**
# Description

Backporting of the changes from main.

# Target

- [X] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [X] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you send a PR for camel-3.x branch instead.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
We are doing a release tomorrow on 3.20.x. I wonder if this is a easy and safe change?

**Comment by orpiske** [comment]
> We are doing a release tomorrow on 3.20.x. I wonder if this is a easy and safe change?

In theory it should be: per Maven folks, `maven.test.skip.exec` and `skipTests` are basically the [same thing](https://maven.apache.org/surefire-archives/surefire-2.22.1/maven-failsafe-plugin/verify-mojo.html#skipExec). 

I think we should be fine unless there is something particular to the way we perform the release.

**Comment by chiragsanghavi** [comment]
@orpiske 
I noticed the warning coming in as I was compiling a snapshot build and noticed that a fix was already coded for 4.x to eliminate. 
I backported this change as per @davsclaus recommandation  to camel-3.x branch. We may want to take it from camel-3.x to other 3.x.x branches and reject this one.

**Comment by chiragsanghavi** [comment]
I have moved it into draft. Is there a way to cancel this one?

**Pull request closed without merging**
