### PR TITLE
CAMEL-19065: camel-kafka - Add KafkaSagaIT test

### PR DESCRIPTION
**Pull request by zhfeng**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Comment by davsclaus** [comment]
Hmm so there is a a special for this in camel-kafka - I dont like that, what about camel-jms and so on.
Does kafka not just store the header as-is, eg a byte[]. And if so can you not just in camel-saga convert the header to a String in case its byte[] or something else.

**Review by oscerd — CHANGES_REQUESTED** [review]
This is wrong because we are adding logic not related to kafka in the Kafka component. This should be done internally in the LRA component. Same for any other headers with the same problem

**Comment by zhfeng** [comment]
For `camel-jms`, it seems that it allows `String` as a value. So I think it should be OK in propagating the `SAGA_LONG_RUNNING_ACTION`
https://github.com/apache/camel/blob/f955a62d128804b45791d4f7e40b58ead58c866b/components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsBinding.java#L489-L491

**Comment by zhfeng** [comment]
Hmm, I added a `KafkaSagaIT` test and it works. After debugging, it looks like
https://github.com/apache/camel/blob/f955a62d128804b45791d4f7e40b58ead58c866b/core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java#L329-L331

which does this `byte[]` to `String` convertion. 
Anyway the reproducer https://github.com/codependent/booking-service is based on `camel-spring-boot`, so it might be some issues there and I will keep investigating.

**Comment by zhfeng** [comment]
@davsclaus How to make sure such a `Converter` is also available for `camel-spring-boot`?

**Comment by zhfeng** [comment]
`camel-spring-boot` also should work. There is an isue in the reproducer https://github.com/codependent/booking-service and it needs to use
```java
log("LRA id is \${headers.Long-Running-Action}")
```
to convert it to `String` explicitly.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Now it's just an it test. Good to merge.

**Pull request merged**
