### PR TITLE
CAMEL-16503: Fix unresolved camel version in the generated spring schemas

### PR DESCRIPTION
**Pull request by omarsmak**
Perviously the generated schemes will have unresolved camel version, e.g: 
```
http\://camel.apache.org/schema/spring=org.apache.camel.spring.xml.handler.CamelNamespaceHandler
http\://camel.apache.org/schema/spring/v${camel.schema.version}=org.apache.camel.spring.xml.handler.CamelNamespaceHandler
```

and 
```
http\://camel.apache.org/schema/spring/camel-spring.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring=camel-spring.xsd
http\://camel.apache.org/schema/spring/v${camel.schema.version}=camel-spring-v${camel.schema.version}.xsd

http\://camel.apache.org/schema/spring/camel-spring-2.0-M1.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.0-M2.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.0-M3.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.0.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.1.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.2.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.3.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.4.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.5.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.6.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.7.0.xsd=camel-spring.xsd
...
...
http\://camel.apache.org/schema/spring/camel-spring-${project.version}.xsd=camel-spring.xsd
```

This attempts to fix that so it should be like this:
```
http\://camel.apache.org/schema/spring=org.apache.camel.spring.xml.handler.CamelNamespaceHandler
http\://camel.apache.org/schema/spring/v3.10=org.apache.camel.spring.xml.handler.CamelNamespaceHandler
```
```
http\://camel.apache.org/schema/spring/camel-spring.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring=camel-spring.xsd
http\://camel.apache.org/schema/spring/v3.10=camel-spring-v3.10.xsd
....
http\://camel.apache.org/schema/spring/camel-spring-3.8.0.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-3.10.0-SNAPSHOT.xsd=camel-spring.xsd
```

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
cc @davsclaus

**Comment by davsclaus** [comment]
LGTM

You could add the 3.9.0 release, as 3.8.0 was the last in the file
http\://camel.apache.org/schema/spring/camel-spring-3.8.0.xsd=camel-spring.xsd

**Comment by omarsmak** [comment]
@davsclaus this was also affecting `camel-cxf`, applied the fix there as well

**Comment by davsclaus** [comment]
Oh yeah that too, and maybe in camel-spring-integraiton - it may also have a custom XSD - thought not sure anymore

**Comment by omarsmak** [comment]
> Oh yeah that too, and maybe in camel-spring-integraiton - it may also have a custom XSD - thought not sure anymore

Yep apparently as well `camel-spring-security`.

**Pull request merged**
