### PR TITLE
Fix typos in documentation navigation

### PR DESCRIPTION
**Pull request by gurpal2000**
Fixed "Hidding" to "Hiding" in the documentation navigation source.

### CODE REVIEW

**Comment by gurpal2000** [comment]
My first ever Camel PR :)

**Comment by oscerd** [comment]
Can you please rebase?

**Comment by gurpal2000** [comment]
Is this fine for me to close now? thank you

**Comment by oscerd** [comment]
No, first we need to merge it then you can close it :-) lgtm now btw

**Pull request merged**
