### PR TITLE
CAMEL-11633 - Upgrade client mqtt paho base lib

### PR DESCRIPTION
**Pull request by Fabryprog**
lib upgrade https://issues.apache.org/jira/browse/CAMEL-11633

### CODE REVIEW

**Comment by oscerd** [comment]
Did you run Karaf integration test too?

**Comment by Fabryprog** [comment]
umm... i run only **mvn clean test** before PR

How to run Karaf intetegration test?

**Comment by oscerd** [comment]
in tests/camel-itest-karaf

mvn clean test -Dtest=CamelPahoTest

**Comment by oscerd** [comment]
and before under platform/karaf/feature run mvn clean install

**Comment by Fabryprog** [comment]
FIRST COMAMND OUTPUT:
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

SECOND COMMAND OUTPUT:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.961 s
[INFO] Finished at: 2017-08-04T16:55:17+02:00
[INFO] Final Memory: 33M/360M

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close this?

**Pull request closed without merging**
