### PR TITLE
[IRC] Add commandTimeout parameter for IRC

### PR DESCRIPTION
**Pull request by avano**
The connector sends the `JOIN` command too early and it results in not joining the channel at all.

Introduced a new param for a delay before sending the commands

### CODE REVIEW

**Comment by avano** [comment]
@oscerd done

**Comment by oscerd** [comment]
Great. Thanks. Not sure this will be merged before the holidays. LGTM by the way. If it's not merged before I'll merge it back from vacations

**Comment by avano** [comment]
@oscerd np, thanks, enjoy the holidays!

**Comment by oscerd** [comment]
You too!

**Comment by davsclaus** [comment]
Just a note that the `label` attribute on the `@UriParam` is intended for category/group, eg common, security, logging, advanced, etc. So that needs to be set to something else.

**Comment by davsclaus** [comment]
And yeah label was maybe a bit bad name, maybe group was better. But it was a bit inspired by gmail labels you can group all your emails by.

**Comment by avano** [comment]
@davsclaus ah, makes sense :-) so maybe leaving out the label would be enough?

**Pull request merged**
