### PR TITLE
[CAMEL-13529] Update to make sure the camel-jdbc work with the spring tx manager

### PR DESCRIPTION
**Pull request by zhfeng**
https://issues.apache.org/jira/browse/CAMEL-13529

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks the karaf features.xml file needs to be updated to have the spring-jdbc dependency added too. Also it would be good to add a little code comment or comment in the pom.xml that spring-jdbc is there to ensure transaction support works with Spring and JEE

**Comment by oscerd** [comment]
I'll merge once we update the Karaf feature. LGTM so far.

**Comment by davsclaus** [comment]
@zhfeng are you working on this so we can get this fixed/merged

**Comment by zhfeng** [comment]
@davsclaus I add a comment in the pom.xml as your suggestion. And feel free to merge it.

**Comment by zhfeng** [comment]
@oscerd I add the fix for features.xml

**Comment by oscerd** [comment]
thx

**Comment by oscerd** [comment]
Merged on master. Can you please create a PR for camel-2.x? Thanks

**Pull request closed without merging**
