### PR TITLE
CAMEL-20888 - Remove Kotlin DSL

### PR DESCRIPTION
**Pull request by apupier**
Kotlin DSL was deprecated in Camel 4.7
It was not used a lot and it takes a fair part of the build time.

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by apupier** [comment]
better to merge these other Pull Requests first to avoid breaking them:

* https://github.com/apache/camel-kamelets-examples/pull/91
* https://github.com/apache/camel-quarkus-examples/pull/270
* list in progress

**Review by orpiske — APPROVED** [review]
+1

**Comment by davsclaus** [comment]
Need to regen as main branch has updated since

**Comment by davsclaus** [comment]
@apupier the upgrade guide doc has a conflict

**Comment by apupier** [comment]
while checking camel-website if requring new changes, I found https://camel.apache.org/blog/2024/02/camel44-whatsnew/#kotlin-api

```
Kotlin API is not the replacement of Kotlin DSL (it is a separate module for now). While it is experimental there may be breaking changes in upcoming releases.
```

This PR is in fact removing all kotlin related things

**Comment by davsclaus** [comment]
> while checking camel-website if requring new changes, I found https://camel.apache.org/blog/2024/02/camel44-whatsnew/#kotlin-api
> 
> ```
> Kotlin API is not the replacement of Kotlin DSL (it is a separate module for now). While it is experimental there may be breaking changes in upcoming releases.
> ```
> 
> This PR is in fact removing all kotlin related things

That is fine - all of this was experimental and manually hand code to be up to date. And there is little uptake of this.
This kind of stuff is better first done outside ASF to build up and gain momentum before dumped to core project and left for us to maintain.

**Pull request merged**
