### PR TITLE
CAMEL-10298: Remove readLockTimeout check from readLockMinAge

### PR DESCRIPTION
**Pull request by yuruki**
https://issues.apache.org/jira/browse/CAMEL-10298

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you update the javadoc of the option as well so the documentation matches.

**Comment by yuruki** [comment]
I couldn't find any documentation that mentioned the restriction. Wiki is up-to-date.

**Comment by davsclaus** [comment]
The doc is in the javadoc, see
https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java#L845

**Comment by yuruki** [comment]
That javadoc seems to be about readLockTimeout versus readLockCheckInterval policy which is valid and still in the code. This PR removes the readLockTimeout versus readLockMinAge check.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
