### PR TITLE
CAMEL-10768: Dropbox component support specifying route params using headers

### PR DESCRIPTION
**Pull request by tlehoux**
This a patch to support setting options with headers for dropbox component. It's for all endpoint options except accessToken and clientIdentifier, for which, IMO, it was not relevant. 
- remotePath
- localPath
- newRemotePath
- uploadMode
- query

### CODE REVIEW

**Comment by davsclaus** [comment]
For headers we tend to prefix them with the name of the component, eg CamelDropBoxXXX. Also the header should likely just be a plain String type so you can set it easily from XML DSL also. Though Camel has a type converter for String -> enum. We tend to use a xxxConstants class for header keys etc.

**Comment by davsclaus** [comment]
Thanks. Next time remember to use CAMEL-NNNN in the commit log messages.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by tlehoux** [comment]
Ok for the next commit log messages. Thanks for the quick merge.

**Pull request closed without merging**
