### PR TITLE
CAMEL-11695: Add security and advanced properties to the camel-grpc component

### PR DESCRIPTION
**Pull request by dmvolod**
Added following options to the component:
1. Additional channel and server options (message size, max concurrent connections, agent name, etc)
2. Standard security features with TLS/SSL
3. Advanced security with custom JSON Web Token implementation

### CODE REVIEW

**Comment by oscerd** [comment]
I'll review tomorrow. Thanks :-)

**Comment by oscerd** [comment]
LGTM, @davsclaus may I ask your feedback too?

**Comment by davsclaus** [comment]
+1

We do however usually add `label = "security"` to those UriParam options that is related to security settings.

**Comment by oscerd** [comment]
@dmvolod can you amend the labels? :-) Thanks.

**Comment by dmvolod** [comment]
@davsclaus , @oscerd I set label = "security" for related options

**Comment by oscerd** [comment]
Great thanks, I'm gonna merge this PR :-)

**Comment by dmvolod** [comment]
Thanks, @oscerd !!!

**Comment by oscerd** [comment]
@dmvolod thanks for the PR. It has been merged. Can you close this?

Side note: camel-grpc currently cannot work in OSGi, the new auth stuff brings us into the wonderful world of multiple guava version in multiple different dependency. I spent the last hour to try to make the component install in Camel, but no luck. Not everything can work in OSGi.

**Comment by dmvolod** [comment]
Thanks a lot, @oscerd !
I will check a version of the google-auth-library, may be the problem is related to higher version of it.
The first correction may be a set ${grpc-google-auth-library-version} = 0.7.0 instead of 0.7.1
If it will work, this is my fault.

**Comment by oscerd** [comment]
@dmvolod you're welcome to work on the Karaf feature. I'll try to change the version and see how it goes, but I guess it is something bigger.

**Comment by oscerd** [comment]
It's not the google-auth version by the way :-)

**Comment by dmvolod** [comment]
it's very strange, as mvn dependency:tree -Dverbose | grep guava says only 19.0 version
[INFO] |  |  +- (com.google.guava:guava:jar:19.0:compile - omitted for duplicate)
[INFO] |  |  |  \- (com.google.guava:guava:jar:19.0:compile - omitted for duplicate)
[INFO] |  |     \- (com.google.guava:guava:jar:19.0:compile - omitted for duplicate)
[INFO] |  +- com.google.guava:guava:jar:19.0:compile
[INFO] |  |  +- (com.google.guava:guava:jar:19.0:compile - omitted for duplicate)
[INFO] |     \- (com.google.guava:guava:jar:19.0:compile - omitted for duplicate)
[INFO] |  \- (com.google.guava:guava:jar:19.0:compile - omitted for duplicate)

**Comment by oscerd** [comment]
You can test the camel-grpc Karaf feature through tests/camel-itest-karaf and mvn clean test -Dtest=CamelGrpcTest

Each time you change the feature run mvn clean install in platform/karaf/feature

**Comment by oscerd** [comment]
at the beginning the feature will ask for jwt

**Comment by dmvolod** [comment]
Thanks, @oscerd 
After jwt dependencies fix i've got very strange which is not very detail for me
org.apache.karaf.features.internal.util.MultiException: Error
	at org.apache.karaf.features.internal.download.impl.MavenDownloadManager$MavenDownloader.<init>(MavenDownloadManager.java:84)
...

**Comment by oscerd** [comment]
That's because jwt is not a bundle, you need to wrap the jar. Usually that error is because of this.

Essentially:

<bundle dependency='true'>wrap:mvn:groupId/artifactId/version</bundle>

**Comment by dmvolod** [comment]
Thanks, but next message says that missing bundle requirements [org.apache.servicemix.bundles.grpc/1.6.1.1] osgi.wiring.package

**Comment by oscerd** [comment]
Yeah, you've to add a bunch of other bundles/jars to try to make it works..

**Comment by dmvolod** [comment]
I was able to fix test. The correct feature is:
  <feature name='camel-grpc' version='${project.version}' resolver='(obr)' start-level='50'>
    <feature version='${project.version}'>camel-core</feature>
    
    <bundle dependency='true'>wrap:mvn:io.grpc/grpc-core/${grpc-version}</bundle>
    <bundle dependency='true'>wrap:mvn:io.grpc/grpc-auth/${grpc-version}</bundle>
    <bundle dependency='true'>wrap:mvn:io.grpc/grpc-netty/${grpc-version}</bundle>
    <bundle dependency='true'>wrap:mvn:io.grpc/grpc-protobuf/${grpc-version}</bundle>
    <bundle dependency='true'>wrap:mvn:io.grpc/grpc-stub/${grpc-version}</bundle>
    
      
    <bundle dependency='true'>wrap:mvn:io.netty/netty-handler/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-buffer/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-common/4.1.14.Final</bundle>
    
    <bundle dependency='true'>wrap:mvn:io.netty/netty-codec/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-codec-http/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-codec-http2/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-codec-socks/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-handler-proxy/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-resolver/4.1.14.Final</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-transport/4.1.14.Final</bundle>
    
    <bundle dependency='true'>mvn:org.javassist/javassist/${javassist-version}</bundle>
    <bundle dependency='true'>wrap:mvn:com.auth0/java-jwt/${grpc-java-jwt-version}</bundle>
    <bundle dependency='true'>wrap:mvn:com.google.auth/google-auth-library-oauth2-http/${grpc-google-auth-library-version}</bundle>
    <bundle dependency='true'>wrap:mvn:com.google.auth/google-auth-library-credentials/${grpc-google-auth-library-version}</bundle>
    <bundle dependency='true'>wrap:mvn:io.netty/netty-tcnative-boringssl-static/${grpc-netty-tcnative-boringssl-static-version}</bundle>
    
    <bundle>mvn:org.apache.camel/camel-grpc/${project.version}</bundle>    
  </feature>

**Comment by oscerd** [comment]
Maybe raise a PR for this. Netty is already a bundle, so no need for wrap instruction

**Pull request closed without merging**
