### PR TITLE
[CAMEL-18327] added method isKafkaConsumerRunnableAndNotStopped() to continue polling eve if the consumer is suspended

### PR DESCRIPTION
**Pull request by geekrupam**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
LGTM, thanks for your contribution!

**Comment by orpiske** [comment]
We should backport this one. I'll take care of this during this week.

**Review by davsclaus — APPROVED** [review]

**Comment by geekrupam** [comment]
How can one view the checkstyle error?

**Comment by orpiske** [comment]
> How can one view the checkstyle error?

Hi, the log is available only to the committers, but I checked the violation and it's not related to your changes. There was a change in another part of the code that introduced the violation (I fixed it already). Thanks for your contribution!

**Pull request merged**
