### PR TITLE
CAMEL-9219: Base64 Spring XML tests and documentation

### PR DESCRIPTION
**Pull request by atoulme**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR. Do you mind working on the formatting so the license header is like the others in the xml file. And also use spaces instead of tabs.

We have a checkstyle you can run also to catch other such issues. See building with checkstyle at
http://camel.apache.org/building.html

**Comment by atoulme** [comment]
Thanks @davsclaus for the review. I have made the changes as requested, and I will try checkstyle.

**Comment by atoulme** [comment]
I ran checkstyle and have removed all errors reported.

**Comment by davsclaus** [comment]
Please the spring xml files are in wrong package name, the dataFormat should be in lower case only.

eg the files in src/test/resources.

**Comment by atoulme** [comment]
Got it. Fixed this and more style issues as discussed on IRC.

**Comment by davsclaus** [comment]
Thanks it works now. I just pushed it. You are welcome to close this

**Pull request closed without merging**
