### PR TITLE
CAMEL-11348 - small optimization & cs fix in MethodInfo

### PR DESCRIPTION
**Pull request by onders86**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by oscerd** [comment]
@onders86 can you check your gmail account? Maybe you have an email in your spam folder or something. Thanks.

**Comment by davsclaus** [comment]
@onders86 the Camel team have sent you an email recently, we wonder if you have received it. So can you check your mailbox, and maybe it went into a spam folder or something.

**Comment by onders86** [comment]
thanks. i think first email's slipped into my inbox but i could not somehow catch it. Thanks for reminder. Great team :1st_place_medal:

**Pull request closed without merging**
