### PR TITLE
CAMEL-21403: retrieve full message for content containing non ASCII chars

### PR DESCRIPTION
**Pull request by jonomorris**
# Description

For a message containing non ASCII chars the length of the message byte array may be longer than the EDI message string length since non ASCII chars can be more that one byte. 

Also fixes one of the Integration tests that appeared a bit flaky.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by jonomorris** [comment]
Just noticed that this doubles up a PR provided by [poncyliuszm](https://github.com/poncyliuszm) [1]. Happy to close this PR or merge into his for the flaky test fixup. 

https://github.com/apache/camel/pull/16148

**Review by oscerd — CHANGES_REQUESTED** [review]
We could merge the other one and then you could rebase on main branch. Thanks.

**Comment by davsclaus** [comment]
Oh @jonomorris there was another PR that also fixed this. Can you maybe update this PR to include your set of unit tests as they better cover this bug.

**Comment by jonomorris** [comment]
I've rebased the changes on main.  Thanks.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
