### PR TITLE
CAMEL-19650: Camel Kafka doesn't honor 'workerPool' configuration

### PR DESCRIPTION
**Pull request by Kartikvk1996**
# Description

# What
The camel kafka component when provided with a custom worker pool is not used.

# Why
The KafkaProducer.java code in doStart() function doesn't check the configuration of whether a custom worker pool is provided or not. It directly goes ahead and creates a new one. This is now fixed by adding a check and using the worker pool if provided.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by essobedo — APPROVED** [review]

**Comment by Kartikvk1996** [comment]
@essobedo @davsclaus PR for https://issues.apache.org/jira/browse/CAMEL-19650 kindly review

**Review by davsclaus — APPROVED** [review]

**Review by orpiske — APPROVED** [review]

**Comment by orpiske** [comment]
Probably needs to be forward ported to 4.x

**Comment by essobedo** [comment]
There are some checkstyle issues in the branch, let me fix them

**Comment by Kartikvk1996** [comment]
There is no space given after "if" condition, I am fixing it.

**Comment by Kartikvk1996** [comment]
@essobedo I have fixed checkstyle issue kindly have a look

**Comment by essobedo** [comment]
It is not only on your side see https://github.com/apache/camel/pull/10829

**Comment by essobedo** [comment]
Please rebase on [apache:camel-3.x](https://github.com/apache/camel/tree/camel-3.x)

**Pull request merged**
