### PR TITLE
CAMEL-18416: Upgrade to slf4j 2.0

### PR DESCRIPTION
**Pull request by ramu11**
upgraded sl4j version to 2.x

### CODE REVIEW

**Comment by essobedo** [comment]
Could you please remove the double quotes from your commit message?

**Comment by davsclaus** [comment]
I think this is maybe something to wait for Camel 4 where major runtimes are upgraded. Lets keep 3.x as-is

**Comment by essobedo** [comment]
I converted it as a draft to avoid merging it in Camel 3.x by mistake

**Comment by essobedo** [comment]
@ramu11 Could you please, modify your commit message as suggested thanks to the command `git commit --amend`?

**Comment by oscerd** [comment]
Let's have a PR when it's time.

**Comment by ramu11** [comment]
closing the PR to open new one when camel has 4.x release

**Pull request closed without merging**
