### PR TITLE
[CAMEL-14140] Remove global dependency on outdated guava

### PR DESCRIPTION
**Pull request by tdiesler**
https://issues.apache.org/jira/browse/CAMEL-14140

### CODE REVIEW

**Comment by oscerd** [comment]
Just as example:

`[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.091 s <<< FAILURE! - in org.apache.camel.itest.karaf.CamelAzureTest
[ERROR] test(org.apache.camel.itest.karaf.CamelAzureTest)  Time elapsed: 8.992 s  <<< ERROR!
org.ops4j.pax.exam.WrappedTestContainerException: [test(org.apache.camel.itest.karaf.CamelAzureTest): Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=camel-azure; type=karaf.feature; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=camel-azure)(type=karaf.feature)(version>=3.0.0.SNAPSHOT)(version<=3.0.0.SNAPSHOT))" [caused by: Unable to resolve camel-azure/3.0.0.SNAPSHOT: missing requirement [camel-azure/3.0.0.SNAPSHOT] osgi.identity; osgi.identity=org.apache.camel.camel-azure; type=osgi.bundle; version="[3.0.0.SNAPSHOT,3.0.0.SNAPSHOT]"; resolution:=mandatory [caused by: Unable to resolve org.apache.camel.camel-azure/3.0.0.SNAPSHOT: missing requirement [org.apache.camel.camel-azure/3.0.0.SNAPSHOT] osgi.wiring.package; filter:="(osgi.wiring.package=com.microsoft.azure.storage.blob)" [caused by: Unable to resolve org.apache.servicemix.bundles.azure-storage/8.4.0.1: missing requirement [org.apache.servicemix.bundles.azure-storage/8.4.0.1] osgi.wiring.package; filter:="(&(osgi.wiring.package=com.google.common.util.concurrent)(version>=20.0.0)(!(version>=21.0.0)))"]]]]
`

**Comment by oscerd** [comment]
So, we cannot merge this.

**Comment by tdiesler** [comment]
Eventually, you'll in one way or the other need to get rid of deprecated guava-19.0 as globaly/exported artifact. Can we fix the above instead of not doing this upgrade/consolidation move at all?

**Comment by oscerd** [comment]
We can change the globally exported guava version, but the problem will be the same for the Karaf features involved. We need to define the guava-osgi-version for any single library involved in this.

**Comment by davsclaus** [comment]
Yeah sadly osgi imports|exports with guava are often very stricted to a single version, so while you can change this for non OSGi, then we would need to hardcode the guava version in the karaf features.xml file to what version that works currently.

**Comment by oscerd** [comment]
@davsclaus I'll work with @tdiesler on upgrading the guava property and check all the karaf features involved.

**Comment by oscerd** [comment]
Thanks, merged on master

**Pull request merged**
