### PR TITLE
Update QuickFIX J to version 1.6.0

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you run the tests reliably?

They run out of memory

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.343 sec - in org.apache.camel.component.quickfixj.QuickfixjConvertersTest
Exception in thread "main" Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"

I suspect there is something that eats up the memory in this upgrade. Wonder if you could take a look?

**Comment by davsclaus** [comment]
This is with Java 7. Maybe you have only tried with Java 8?

**Comment by lburgazzoli** [comment]
Ah yes sorry, I have my maven options configured to handle this [problem](https://github.com/quickfix-j/quickfixj/wiki/QFJ-1.6.0-release-notes) as I'm using quickfixj 1.6.0 also in other projects.

Can I add something like the snippet below ?

```xml
  <profiles>
    <profile>
      <id>permgen</id>
      <activation>
        <jdk>(,1.7]</jdk>
      </activation>
      <build>
        <plugins>
            <plugin>
              <groupId>org.apache.maven.plugins</groupId>
              <artifactId>maven-surefire-plugin</artifactId>
              <configuration>
                  <argLine>-XX:MaxPermSize=180m</argLine>
              </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

**Comment by davsclaus** [comment]
Yeah sure you are welcome to update the PR with the fix

**Comment by lburgazzoli** [comment]
Done, but with the latest sources I see the following error in both my branch and main

```
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.386 sec <<< FAILURE! - in org.apache.camel.component.quickfixj.QuickfixjLazyProducerTest
processWithLazyEngine(org.apache.camel.component.quickfixj.QuickfixjLazyProducerTest)  Time elapsed: 2.059 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is <true>
     but: was <false>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:865)
        at org.junit.Assert.assertThat(Assert.java:832)
        at org.apache.camel.component.quickfixj.QuickfixjLazyProducerTest.processWithLazyEngine(QuickfixjLazyProducerTest.java:80)
```

**Comment by davsclaus** [comment]
Thanks it works now. No I dont get that error. Smells like a timing issue

**Comment by oscerd** [comment]
Hi Luca,

Sorry, I didn't see this PR, even if I have the ticket assigned. I apologize for this.

Thanks for the PR and thank you Claus to take care of this PR.

**Comment by lburgazzoli** [comment]
@davsclaus definitively possible, ran it on a poor vm
@oscerd not a problem at all

**Comment by lburgazzoli** [comment]
I noticed that the patch has been merged, should I close it ?

**Comment by oscerd** [comment]
Yes. Thanks for the PR :-)

**Pull request closed without merging**
