### PR TITLE
Added option for path-style access to S3

### PR DESCRIPTION
**Pull request by FingolfinTEK**

### CODE REVIEW

**Comment by oscerd** [comment]
I'm reviewing this :-) thanks @FingolfinTEK

**Comment by FingolfinTEK** [comment]
That was quick, thanks!

**Comment by oscerd** [comment]
Can you open a PR on the master branch? Since this is an enhancement we will add this to master and you'll find this on Camel 2.18

Thanks :-)

**Comment by FingolfinTEK** [comment]
Already created a PR on the master branch - #1032 ; however, the commits will differ because the versions of the AWS library are different between the branches as S3ClientOptions should now be constructed via its builder.

**Comment by oscerd** [comment]
Great, @davclaus can we backport this enhancement to camel-2.17.x too?

**Comment by davsclaus** [comment]
+1 go ahead @oscerd

**Comment by oscerd** [comment]
Merged this one too. Many thanks @FingolfinTEK :-)

Can you close the PR? :-)

**Comment by FingolfinTEK** [comment]
No, thank you for the quick merge!

Closed.

**Pull request closed without merging**
