### PR TITLE
CAMEL-12334: Allow customizations of date/time types in generated DTOs

### PR DESCRIPTION
**Pull request by zregvart**
This adds support for using any of the following date/time classes:
 - java.util.Date
 - java.time.Instant
 - java.time.LocalDate
 - java.time.ZonedDateTime
 - java.time.OffsetDateTime

With this all usage of Jackson `ObjectMapper` and `XStream` instances
goes through the single utility method in `JsonUtils` or `XStreamUtils`
in order to register default serializers/deserializers/converters.

With this customized types can be used instead of default ones for
fields in generated Java DTO classes. The Salesforce Maven plugin now
supports specifying `customTypes` property, for instance:

```xml
<plugin>
  <groupId>org.apache.camel</groupId>
  <artifactId>camel-salesforce-maven-plugin</artifactId>
  <configuration>
    <!-- ... -->
    <customTypes>
      <date>java.time.LocalDate</date>
    </customTypes>
  </configuration>
</plugin>
````

@hemangajmera I've opted to remain on defaults, a lot of client's code would break otherwise, and allow type customizations instead. Can you have a look?

### CODE REVIEW

**Comment by hemangajmera** [comment]
@zregvart 
I will run your changes locally and let you know how it went soon.
Thanks for efforts.

**Comment by hemangajmera** [comment]
@zregvart 
I tested the your PR. It works as expected!

Thanks a lot for this.

Do you know when will this release?

Also wanted to understand one thing, since for date field, the default ZonedDateTime is not working, shouldn't change the default in some major version in future?

**Comment by zregvart** [comment]
> Do you know when will this release?

This will be included in 2.22 scheduled to be released in Spring, we're trying to do more frequent releases. When it gets merged a built -SNAPSHOT version will be available on the Apache Maven Snapshot repository at:

https://repository.apache.org/content/groups/snapshots/org/apache/camel/camel-salesforce/2.22.0-SNAPSHOT/

> Also wanted to understand one thing, since for date field, the default ZonedDateTime is not working, shouldn't change the default in some major version in future?

Yeah, I think that I'll go back on that and change the defaults, your suggestion makes much more sense. And with those types being configurable I can add to the docs how to set previous behavior for anyone wishing to do so. I also forgot to include the test cases you did on your pull request.

So let me change the defaults and add those tests again. Sorry for this taking so long.

**Comment by zregvart** [comment]
@hemangajmera this is now in `master` branch. In a couple of hours when the CI job succeeds a -SNAPSHOT version will be built and deployed to ASF snapshot Maven repository.

Thank you :100: for your contribution the Salesforce component is much better in handling date/time values now :fireworks:

**Comment by hemangajmera** [comment]
I just raised a issue which I faced and tried to fix it.

Thanks a ton to you for your efforts in improvising and redoing the entire fix in much better way!

**Pull request merged**
