### PR TITLE
CAMEL-14199 : camel-hdfs - Add maxMessagesPerPoll for Consumer

### PR DESCRIPTION
**Pull request by marius-cornescu**
CAMEL-14199 : camel-hdfs - Add maxMessagesPerPoll for Consumer

### CODE REVIEW

**Comment by omarsmak** [comment]
Is this depending on the other PR of yours https://github.com/apache/camel/pull/3354 ?

**Comment by davsclaus** [comment]
Thanks. Is there not a way to limit directly on hadoop file system to tell it to not give all file status, but only X number?

Also I forgot how it works about avoiding processing the same files again on next pool. So if you limit to 10, and there are a total of 65 files. Then pool #1 will process 10 files, then pool #2 will it then know that the previous 10 was processed, or would hadoop return 55 files now?

**Comment by marius-cornescu** [comment]
> Is this depending on the other PR of yours #3354 ?

These are independent, though touch the same areas of code.

**Comment by marius-cornescu** [comment]
> Thanks. Is there not a way to limit directly on hadoop file system to tell it to not give all file status, but only X number?
**[MC]** Not with the 2.x hadoop version; I didn't check with 3.x; This is just a file reference, so memory impact should be minimal. Also, the FileStatus[] is only filtered by pattern, then an extra check for owner is done (_hadoop client has no other api to get only for owner_). It may be so that out of the 100 matched files, only 10 are for that owner. So this is a more greedy fetch.

> 
> Also I forgot how it works about avoiding processing the same files again on next pool. So if you limit to 10, and there are a total of 65 files. Then pool #1 will process 10 files, then pool #2 will it then know that the previous 10 was processed, or would hadoop return 55 files now?

**[MC]** Files are renamed with the ".OPEN" extension then to the ".READ" extension; So it works as you would expect even without an idempotent or inprogress repo.

**Comment by davsclaus** [comment]
ok thanks

**Pull request merged**
