### PR TITLE
Enable camel-nats component of Camel 4.0.x on PPC64LE

### PR DESCRIPTION
**Pull request by shreyakajbaje**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — COMMENTED** [review]
What is the point of this change? 4.0.x is an LTS so upgrading the infra without a good reason and without checking if the component still works is not good.

**Comment by davsclaus** [comment]
Is this done for the `main` branch already?
We should make sure it works there first before doing any kind of backports to LTS branches

**Comment by shreyakajbaje** [comment]
> Is this done for the `main` branch already? We should make sure it works there first before doing any kind of backports to LTS branches

Hi @davsclaus @oscerd have validated this on main branch. shoud I raise PR on main branch ?

**Comment by davsclaus** [comment]
yes main branch please

**Comment by davsclaus** [comment]
okay I have merged this to main branch

**Pull request closed without merging**
