### PR TITLE
[CAMEL-18728]: Fix elasticsearch-rest component name to prevent component name clash

### PR DESCRIPTION
**Pull request by ludovic-boutros**
Fix elasticsearch-rest component name in order to prevent component name clash.

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by essobedo — CHANGES_REQUESTED** [review]
Thx for the contribution and for reporting. Regarding the PR, it is a lot of changes, I hope we can find a smaller fix. First of all, we need to avoid moving classes in `camel-elasticsearch-rest` as it is a very old component it is in maintenance mode so we are not supposed to change it a lot.

**Comment by essobedo** [comment]
I rather prefer that we add an exception in the maven plugin directly as it has already been done [here](https://github.com/apache/camel/blob/main/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java#L1000-L1005)

Simply adds:
```
            case "org.apache.camel.component.elasticsearch.ElasticsearchComponent":
                return "ElasticsearchRest";
```

**Review by oscerd — CHANGES_REQUESTED** [review]
I think this is a bit overkilling, I would follow the way suggested by @essobedo: the main reason is just because we are planning to remove the rest component at some point.

**Comment by ludovic-boutros** [comment]
I will follow the way you all suggested.
I did not know it. It's far more simple !

**Comment by ludovic-boutros** [comment]
It should be ok now. So easy when you understand the build process a bit more 👍 .
Thank you.

**Review by essobedo — CHANGES_REQUESTED** [review]
Much better thx 👍. 

One last remark, could you please revert the changes in `camel-spring.xsd`, they are not related and are due to some kind of reformatting that will be reverted anyway by the next "Regen commit". Let's keep it as small as possible. Thx in advance 🙏

**Comment by essobedo** [comment]
Could you please also remove "in order" from your commit message?

**Comment by ludovic-boutros** [comment]
@essobedo it should be good now.

**Review by essobedo — APPROVED** [review]
That's it, great job, many thx 👍

**Pull request merged**
