### PR TITLE
[CAMEL-18530] Camel box cannot authorize

### PR DESCRIPTION
**Pull request by Croway**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by essobedo** [comment]
Are you sure that it is the right branch for 3.18.x? For me the right branch is rather https://github.com/apache/camel/commits/camel-3.18.x

**Comment by davsclaus** [comment]
Yes that is wrong - we should delete this faulty branch and we can cherry pick from main

**Comment by essobedo** [comment]
ok let me do it

**Comment by Croway** [comment]
Thanks @essobedo @davsclaus, I was wondering why the naming convention was different between camel-3.14.x and 3.18.x branches, I'm sorry!

**Pull request merged**
