### PR TITLE
cassandra-kubernates, cxf-blueprint, hazelcast-kubernates: Fixed typo…

### PR DESCRIPTION
**Pull request by igarashitm**
… in readme

servlet-tomcat-no-spring: added finalName so the contextPath would match with the URL described in readme

### CODE REVIEW

**Comment by igarashitm** [comment]
oops, sorry opened too early, I'll reopen after I add a few more

**Comment by davsclaus** [comment]
@oscerd looks good to me, do you mind merging?

**Comment by oscerd** [comment]
@davsclaus yes, no problem

**Comment by oscerd** [comment]
@igarashitm thanks, the PR has been merged. Can you close this?

**Comment by igarashitm** [comment]
Thanks! closing

**Pull request closed without merging**
