### PR TITLE
CAMEL-11417: Fixed tab completion for route-reset-stats command

### PR DESCRIPTION
**Pull request by saravanakumar1987**
https://issues.apache.org/jira/browse/CAMEL-11417

Thanks,
Saravanakumar

### CODE REVIEW

**Comment by oscerd** [comment]
Please open the PR against master. We will eventually backport on other branches. Thanks.

**Comment by saravanakumar1987** [comment]
I thikn this change can be backported only at 2.18.x branch unless if we still work on 2.17.x. Correct me if I am wrong.

**Comment by oscerd** [comment]
Yeah, you're right, and we don't plan to release 2.17 anymore.

**Comment by oscerd** [comment]
I'll take care of this.

**Comment by oscerd** [comment]
Thanks for the PR

**Pull request merged**
