### PR TITLE
camel-olingo4 support json string as payload

### PR DESCRIPTION
**Pull request by johnpoth**
That way we don't have to create a ClientEntity on the application side for each request (we can just pass a string as the payload). Let me know if more details/JIRA is required. Thanks!

### CODE REVIEW

**Comment by oscerd** [comment]
Maybe a Jira could be better. I'll merge soon :-)

**Comment by johnpoth** [comment]
@oscerd no worries :) JIRA created, PR updated

**Comment by davsclaus** [comment]
Would there be a similar thing in camel-olingo2 ?

**Comment by oscerd** [comment]
Thanks the PR has been merged :-)

**Pull request closed without merging**
