### PR TITLE
CAMEL-10543: New Apache Camel Logo

### PR DESCRIPTION
**Pull request by daklassen**
My proposal for the new logo. As this is just a first preview I am open for any kind of feedback/critics/change request. I will add final files (png, vector based, different sizes, ...) later.

### CODE REVIEW

**Comment by zregvart** [comment]
Really good, I like it :clap: I would like to see some versions in colour.

**Comment by pax95** [comment]
Really nice. Best so far I think.

**Comment by daklassen** [comment]
Thanks for the feedback. I just **added a few more preview pictures** (different sizes and colors) and a "clean"/transparent png version.

**Comment by zregvart** [comment]
Hi we are voting on the received proposals, the vote is open till 15.5. see all the proposals and [cast the vote](https://goo.gl/forms/A3pIzPyWzU8rlMJ13) for the three designs you prefer the most.
Also read the news announcement on [Camel blog](https://camel.apache.org/2017/05/03/new-apache-camel-logo-voting-is-now-open.html).

**Comment by oscerd** [comment]
Since the vote ended I'm closing the related PRs

**Pull request closed without merging**
