### PR TITLE
[CAMEL-18612] Inconsistency in JsonPath component causes problems with databinding

### PR DESCRIPTION
**Pull request by rnetuka**
Issue: https://issues.apache.org/jira/browse/CAMEL-18612

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
What happens with a list with a single element if you removed that block? It seems to be a corner case we won't cover anymore.

**Comment by rnetuka** [comment]
@oscerd nothing, the result will be a list with a single element. A one-element list is still a list in my opinion. Is there some case when you actually _need_ the unwrapping?

**Comment by oscerd** [comment]
As far as It seems there is no specific needs for that, but maybe I would git blame around to find something. Maybe there is some specific reason or something we don't need anymore.

**Comment by rnetuka** [comment]
@oscerd I doubt this corner case ever was supported. When I try the reproducer from the issue, the list element unwraps as a LinkedHashMap and a type converter calls LinkedHashMap#toString to create the return value, which is not a valid Json string.

**Comment by davsclaus** [comment]
Is there an unit test that can reproduce this that can be added to camel-jsonpath. As a PR that removes code claiming to fix a bug, then I would like to see if possible a testcase for such bug first.

**Comment by rnetuka** [comment]
@davsclaus I've added a unit test. Without the changes, it throws an error. With the changes, it works.

**Comment by rnetuka** [comment]
Based on the JIRA discussion, this has been replaced by https://github.com/apache/camel/pull/8571

**Pull request closed without merging**
