### PR TITLE
Add OpenTracing span decorators for cassandra (cql), direct-vm, disru…

### PR DESCRIPTION
**Pull request by objectiser**
…ptor[-vm], elasticsearch and stomp

### CODE REVIEW

**Comment by objectiser** [comment]
@davsclaus Another set of span decorators, if you could review when you get a chance? Thanks.

**Comment by davsclaus** [comment]
I wonder since we start to have many of these, if we could annotate or anyhow mark the options in the camel endpoints to indicate which is operation name, and which is a tag.

Then the endpoint could have an api that can provide such details so the span decorators could be done more generally.

Just a thought as I am not sure how easy that would be to do. And I guess sometimes you may need a bit of per component logic which you can do easily in a span decorator per component

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by objectiser** [comment]
Yes was thinking the same thing, but at the moment I am just adding mainly standard tags - and expect further tags to be added on a per component basis as we start to get feedback from component users on what information they want to see in the trace data.

Thanks!

**Pull request closed without merging**
