### PR TITLE
CAMEL-12288: Initial implementation of method calls in the client

### PR DESCRIPTION
**Pull request by ctron**
This change refactors the code and adds the ability to perform method
calls instead of write operations.

### CODE REVIEW

**Comment by oscerd** [comment]
I'll test and merge on master later or tomorrow. Thanks @ctron

**Comment by ctron** [comment]
Thanks @oscerd 

It would be great if you could run the tests with `mvn -Pmilo-test`. IIRC there were some initial issues with a used port. But all tests should use dynamic ports now and I would like to re-enable the tests if possible.

**Comment by oscerd** [comment]
Sure, I'll let you know

**Comment by oscerd** [comment]
Running directly with -Pmilo-test I got a bunch of errors

**Comment by oscerd** [comment]
Do I need to spin up a milo server?

**Comment by oscerd** [comment]
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 63.165 s <<< FAILURE! - in org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest
[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest)  Time elapsed: 21.986 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest.testMonitorItem1(MonitorItemMultiConnectionsCertTest.java:127)

[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest)  Time elapsed: 20.392 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest.testMonitorItem1(MonitorItemMultiConnectionsCertTest.java:127)

[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest)  Time elapsed: 20.301 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest.testMonitorItem1(MonitorItemMultiConnectionsCertTest.java:127)

[INFO] Running org.apache.camel.component.milo.MonitorItemMultiConnectionsTest
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 62.962 s <<< FAILURE! - in org.apache.camel.component.milo.MonitorItemMultiConnectionsTest
[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsTest)  Time elapsed: 21.743 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.milo.MonitorItemMultiConnectionsTest.testMonitorItem1(MonitorItemMultiConnectionsTest.java:97)

[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsTest)  Time elapsed: 20.516 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.milo.MonitorItemMultiConnectionsTest.testMonitorItem1(MonitorItemMultiConnectionsTest.java:97)

[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsTest)  Time elapsed: 20.27 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.milo.MonitorItemMultiConnectionsTest.testMonitorItem1(MonitorItemMultiConnectionsTest.java:97)

[INFO] Running org.apache.camel.component.milo.MonitorItemTest
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 51.573 s <<< FAILURE! - in org.apache.camel.component.milo.MonitorItemTest
[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemTest)  Time elapsed: 18.044 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <3> but was: <0>
	at org.apache.camel.component.milo.MonitorItemTest.testMonitorItem1(MonitorItemTest.java:87)

[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemTest)  Time elapsed: 16.434 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <3> but was: <0>
	at org.apache.camel.component.milo.MonitorItemTest.testMonitorItem1(MonitorItemTest.java:87)

[ERROR] testMonitorItem1(org.apache.camel.component.milo.MonitorItemTest)  Time elapsed: 16.501 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <3> but was: <0>
	at org.apache.camel.component.milo.MonitorItemTest.testMonitorItem1(MonitorItemTest.java:87)

[INFO] Running org.apache.camel.component.milo.WriteClientTest
[ERROR] Tests run: 9, Failures: 9, Errors: 0, Skipped: 0, Time elapsed: 94.729 s <<< FAILURE! - in org.apache.camel.component.milo.WriteClientTest
[ERROR] testWrite1(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 11.706 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite1(WriteClientTest.java:107)

[ERROR] testWrite2(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.409 s  <<< FAILURE!
java.lang.AssertionError: mock://test2 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite2(WriteClientTest.java:125)

[ERROR] testWrite3(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.43 s  <<< FAILURE!
java.lang.AssertionError: mock://test2 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite3(WriteClientTest.java:147)

[ERROR] testWrite3(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.435 s  <<< FAILURE!
java.lang.AssertionError: mock://test2 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite3(WriteClientTest.java:147)

[ERROR] testWrite1(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.289 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite1(WriteClientTest.java:107)

[ERROR] testWrite2(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.252 s  <<< FAILURE!
java.lang.AssertionError: mock://test2 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite2(WriteClientTest.java:125)

[ERROR] testWrite1(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.248 s  <<< FAILURE!
java.lang.AssertionError: mock://test1 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite1(WriteClientTest.java:107)

[ERROR] testWrite3(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.295 s  <<< FAILURE!
java.lang.AssertionError: mock://test2 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite3(WriteClientTest.java:147)

[ERROR] testWrite2(org.apache.camel.component.milo.WriteClientTest)  Time elapsed: 10.238 s  <<< FAILURE!
java.lang.AssertionError: mock://test2 Received message count. Expected: <2> but was: <0>
	at org.apache.camel.component.milo.WriteClientTest.testWrite2(WriteClientTest.java:125)

[INFO] Running org.apache.camel.component.milo.call.CallClientTest
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 3.653 s <<< FAILURE! - in org.apache.camel.component.milo.call.CallClientTest
[ERROR] testCall1(org.apache.camel.component.milo.call.CallClientTest)  Time elapsed: 2.362 s  <<< FAILURE!
java.lang.AssertionError: array lengths differed, expected.length=2 actual.length=0
	at org.apache.camel.component.milo.call.CallClientTest.testCall1(CallClientTest.java:119)

[ERROR] testCall1(org.apache.camel.component.milo.call.CallClientTest)  Time elapsed: 0.385 s  <<< FAILURE!
java.lang.AssertionError: array lengths differed, expected.length=2 actual.length=0
	at org.apache.camel.component.milo.call.CallClientTest.testCall1(CallClientTest.java:119)

[ERROR] testCall1(org.apache.camel.component.milo.call.CallClientTest)  Time elapsed: 0.367 s  <<< FAILURE!
java.lang.AssertionError: array lengths differed, expected.length=2 actual.length=0
	at org.apache.camel.component.milo.call.CallClientTest.testCall1(CallClientTest.java:119)

[INFO] Running org.apache.camel.component.milo.client.NodeIdTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.379 s - in org.apache.camel.component.milo.client.NodeIdTest
[INFO] Running org.apache.camel.component.milo.converter.ConverterTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.71 s - in org.apache.camel.component.milo.converter.ConverterTest
[INFO] Running org.apache.camel.component.milo.server.ServerLocalTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.007 s - in org.apache.camel.component.milo.server.ServerLocalTest
[INFO] Running org.apache.camel.component.milo.server.ServerSetCertificateManagerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.023 s - in org.apache.camel.component.milo.server.ServerSetCertificateManagerTest
[INFO] Running org.apache.camel.component.milo.server.ServerSetSecurityPoliciesTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.908 s - in org.apache.camel.component.milo.server.ServerSetSecurityPoliciesTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR] org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest.testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsCertTest)
[ERROR]   Run 1: MonitorItemMultiConnectionsCertTest.testMonitorItem1:127->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <1> but was: <0>
[ERROR]   Run 2: MonitorItemMultiConnectionsCertTest.testMonitorItem1:127->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <1> but was: <0>
[ERROR]   Run 3: MonitorItemMultiConnectionsCertTest.testMonitorItem1:127->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <1> but was: <0>
[INFO] 
[ERROR] org.apache.camel.component.milo.MonitorItemMultiConnectionsTest.testMonitorItem1(org.apache.camel.component.milo.MonitorItemMultiConnectionsTest)
[ERROR]   Run 1: MonitorItemMultiConnectionsTest.testMonitorItem1:97->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <1> but was: <0>
[ERROR]   Run 2: MonitorItemMultiConnectionsTest.testMonitorItem1:97->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <1> but was: <0>
[ERROR]   Run 3: MonitorItemMultiConnectionsTest.testMonitorItem1:97->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <1> but was: <0>
[INFO] 
[ERROR] org.apache.camel.component.milo.MonitorItemTest.testMonitorItem1(org.apache.camel.component.milo.MonitorItemTest)
[ERROR]   Run 1: MonitorItemTest.testMonitorItem1:87->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <3> but was: <0>
[ERROR]   Run 2: MonitorItemTest.testMonitorItem1:87->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <3> but was: <0>
[ERROR]   Run 3: MonitorItemTest.testMonitorItem1:87->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <3> but was: <0>
[INFO] 
[ERROR] org.apache.camel.component.milo.WriteClientTest.testWrite1(org.apache.camel.component.milo.WriteClientTest)
[ERROR]   Run 1: WriteClientTest.testWrite1:107->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <2> but was: <0>
[ERROR]   Run 2: WriteClientTest.testWrite1:107->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <2> but was: <0>
[ERROR]   Run 3: WriteClientTest.testWrite1:107->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test1 Received message count. Expected: <2> but was: <0>
[INFO] 
[ERROR] org.apache.camel.component.milo.WriteClientTest.testWrite2(org.apache.camel.component.milo.WriteClientTest)
[ERROR]   Run 1: WriteClientTest.testWrite2:125->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test2 Received message count. Expected: <2> but was: <0>
[ERROR]   Run 2: WriteClientTest.testWrite2:125->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test2 Received message count. Expected: <2> but was: <0>
[ERROR]   Run 3: WriteClientTest.testWrite2:125->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test2 Received message count. Expected: <2> but was: <0>
[INFO] 
[ERROR] org.apache.camel.component.milo.WriteClientTest.testWrite3(org.apache.camel.component.milo.WriteClientTest)
[ERROR]   Run 1: WriteClientTest.testWrite3:147->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test2 Received message count. Expected: <2> but was: <0>
[ERROR]   Run 2: WriteClientTest.testWrite3:147->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test2 Received message count. Expected: <2> but was: <0>
[ERROR]   Run 3: WriteClientTest.testWrite3:147->CamelTestSupport.assertMockEndpointsSatisfied:888 mock://test2 Received message count. Expected: <2> but was: <0>
[INFO] 
[ERROR] org.apache.camel.component.milo.call.CallClientTest.testCall1(org.apache.camel.component.milo.call.CallClientTest)
[ERROR]   Run 1: CallClientTest.testCall1:119->Assert.assertArrayEquals:298->Assert.assertArrayEquals:283->Assert.internalArrayEquals:532->Assert.fail:88 array lengths differed, expected.length=2 actual.length=0
[ERROR]   Run 2: CallClientTest.testCall1:119->Assert.assertArrayEquals:298->Assert.assertArrayEquals:283->Assert.internalArrayEquals:532->Assert.fail:88 array lengths differed, expected.length=2 actual.length=0
[ERROR]   Run 3: CallClientTest.testCall1:119->Assert.assertArrayEquals:298->Assert.assertArrayEquals:283->Assert.internalArrayEquals:532->Assert.fail:88 array lengths differed, expected.length=2 actual.length=0
[INFO] 
[INFO] 
[ERROR] Tests run: 27, Failures: 7, Errors: 0, Skipped: 0
```

**Comment by oscerd** [comment]
ping @ctron

**Comment by ctron** [comment]
@oscerd Sorry, I was out of office yesterday. I will have a look at this today.

**Comment by ctron** [comment]
> Do I need to spin up a milo server?
No, it should spin up one during the unit tests. Do you get any additional errors?

**Comment by oscerd** [comment]
I have a connection refused 

```
java.util.concurrent.ExecutionException: UaException: status=Bad_ConnectionRejected, message=java.net.ConnectException: Connection refused: ghost/192.168.1.11:42081
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[?:1.8.0_65]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[?:1.8.0_65]
	at org.apache.camel.component.milo.client.internal.SubscriptionManager.performConnect(SubscriptionManager.java:475) ~[classes/:?]
	at org.apache.camel.component.milo.client.internal.SubscriptionManager.performAndEvalConnect(SubscriptionManager.java:394) ~[classes/:?]
	at org.apache.camel.component.milo.client.internal.SubscriptionManager.connect(SubscriptionManager.java:389) ~[classes/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_65]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_65]
Caused by: org.eclipse.milo.opcua.stack.core.UaException: java.net.ConnectException: Connection refused: ghost/192.168.1.11:42081
	at org.eclipse.milo.opcua.stack.client.UaTcpStackClient.lambda$bootstrap$15(UaTcpStackClient.java:510) ~[stack-client-0.2.1.jar:0.2.1]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:683) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:604) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:564) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:425) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:276) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:292) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:545) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
	... 1 more
Caused by: java.net.ConnectException: Connection refused: ghost/192.168.1.11:42081
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[?:1.8.0_65]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[?:1.8.0_65]
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:224) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:289) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:545) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371) ~[netty-transport-4.0.36.Final.jar:4.0.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) ~[netty-common-4.0.36.Final.jar:4.0.36.Final]
```

**Comment by ctron** [comment]
Ok .. there we have the problem :smile: it is using your local host name instead of "localhost". The server however only binds to "localhost". Let me try a fix for that.

**Comment by ctron** [comment]
Ok, would it be possible for you to re-try the unit tests?

**Comment by oscerd** [comment]
Yeah, running now.

**Comment by oscerd** [comment]
All green.

**Comment by ctron** [comment]
Yeay! … Ok, the problem simply was that the milo server reported "ghost" as endpoint, which is correct (to some degree). I have a mapping of "my-host" to "127.0.0.1" in my `/etc/hosts`, but that is not always the case. And you probably don't have.

Automatic service endpoint discoveries can be a nightmare … but with one of the recent changes it can be overridden to the original requested host ("localhost" in this case) and this is what I enabled now for the unit tests.

**Comment by oscerd** [comment]
Merged on master :-) Thanks a lot

**Comment by ctron** [comment]
Cool. Thanks for your help!

Do you think it is ok to create a new PR, enabling all the unit tests now, dropping the `milo-test` profile.

**Comment by oscerd** [comment]
I believe it should be fine now, using the dynamic port choice should solve any conflicts and we already do like that in other components. So go ahead if you have time :-) Thanks.

**Pull request closed without merging**
