### PR TITLE
CAMEL-16639: Use `jsonpathTable2` macro in docs

### PR DESCRIPTION
**Pull request by zregvart**
This uses the `jsonpathTable2` macro to generate the configuration
instead of the UpdateReadmeMojo. This way the content of the
configuration tables is generated directly from the JSON Camel metadata
files during the website build; eliminating need to regenerate the .adoc
files.

### CODE REVIEW

**Comment by zregvart** [comment]
The issue with Bindy data format still remains and needs to be addressed. This also doesn't include the regeneration commit, I'll push the result on a separate branch and test locally the build of the website. This is to gather feedback.

**Review by djencks — APPROVED** [review]
LGTM.  I believe the bindy problem can be fixed by changing UpdateReadmeMojo line 511 to

```
            String shortName = "mail".equals(name) ? "imap" : "bindy".equals(name) ? "bindy-csv" : name;
```

**Comment by zregvart** [comment]
> LGTM. I believe the bindy problem can be fixed by changing UpdateReadmeMojo line 511 to
> 
> ```
>             String shortName = "mail".equals(name) ? "imap" : "bindy".equals(name) ? "bindy-csv" : name;
> ```

Seems that there are more than one bindy-*.json files, and I guess we want to include all of them:

```
./components/camel-bindy/src/generated/resources/org/apache/camel/dataformat/bindy/csv/bindy-csv.json
./components/camel-bindy/src/generated/resources/org/apache/camel/dataformat/bindy/fixed/bindy-fixed.json
./components/camel-bindy/src/generated/resources/org/apache/camel/dataformat/bindy/kvp/bindy-kvp.json
```

I was thinking either creating three .adoc files for bindy based on the curent single one, or to invoke the jsonPathTable macro three times, which I think will be a bit simpler. I'm trying the latter approach now.

**Review by mamadaliev — APPROVED** [review]

**Comment by zregvart** [comment]
I did not push the _Regen_ commit here to help with the review, the simplest solution for the Bindy issue that I could think of is in ee4f0ce. Though that rendered three identical tables because the JSON files are identical. Not sure what the fix here should be:
 - use the single JSON file as the source for the options
 - fix metadata generation so single JSON file is generated
 - fix metadata generation so that it generates three different JSON files (based on appropriate configuration for each data format)
 - something else?

**Comment by djencks** [comment]
I strongly think that changes in the number or information content of the bindy pages should be done under a separate JIRA issue.  There are some comments scattered here and there that led me to believe that someone decided that one page for the three bindy flavors was the correct documentation approach, so if we change that I suggest  that it be discussed separately from this set of changes which is intended to be format-only.

My view based on the previous code and the identity of the rendered parts of the 3 bindy json files is that the existing single page is adequate as is.

David Jencks

**Comment by zregvart** [comment]
Created an issue for the Bindy to followup: https://issues.apache.org/jira/browse/CAMEL-16982

**Comment by zregvart** [comment]
I've added commit that regenerates the documentation with the changes on this PR. This is now ready to be merged.

**Comment by djencks** [comment]
Can this be merged now?

**Comment by djencks** [comment]
I did something wrong with the eips and they still aren't getting generated. I expect to have a PR tomorrow fixing this and the AsciiDoc attribute case for the generated attribute values (such as docTitle > doctitle).

**Pull request merged**
