### PR TITLE
CAMEL-20044 Backport breakOnFirstError Fix to Camel 4

### PR DESCRIPTION
**Pull request by CodeSmell**
# Description

The fix for breakOnFirstError that was merged in #11959 

# Target
main

# Tracking
CAMEL-20044

### CODE REVIEW

**Comment by CodeSmell** [comment]
@orpiske 
Just copied over the commits 
Am looking at changes that may be necessary for the tests

**Comment by CodeSmell** [comment]
> @orpiske Just copied over the commits Am looking at changes that may be necessary for the tests

Ok updated tests

**Review by oscerd — APPROVED** [review]
Please rebuild the full project so you can commit regenerated files.

**Comment by oscerd** [comment]
https://github.com/apache/camel/actions/runs/6888126595

**Comment by orpiske** [comment]
[tests 2.log](https://github.com/apache/camel/files/13375494/tests.2.log)

Camel 4 changes probably need a bit more adjustments. Attaching the logs ...

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
The CI cannot run full test as there are local files changed that are not in the PR. This usually happens in camel-catalog etc.

**Review by orpiske — APPROVED** [review]
LGTM. Let's merge.

**Comment by orpiske** [comment]
Thanks for your contribution @CodeSmell!

**Pull request merged**
