### PR TITLE
CAMEL-10303 - added ability to detect when the consumer fails to deli…

### PR DESCRIPTION
**Pull request by hqstevenson**
…ver the MLLP acknowledgement

### CODE REVIEW

**Comment by davsclaus** [comment]
Looks good, @oscerd you are welcome to merge. 

This component was created by Quinn Stevenson and his team so they know what they are doing ;)

**Comment by oscerd** [comment]
I will take care of this :-)

**Comment by oscerd** [comment]
Running test locally I got the following errors

```shell
Running org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 10.551 sec <<< FAILURE! - in org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest
testIdleConnection(org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest)  Time elapsed: 2.684 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Broken pipe]> but was:<[Connection reset]>
	at org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest.testIdleConnection(MllpTcpServerConsumerConnectionTest.java:128)

testIdleConnection(org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest)  Time elapsed: 2.246 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Broken pipe]> but was:<[Connection reset]>
	at org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest.testIdleConnection(MllpTcpServerConsumerConnectionTest.java:128)

testIdleConnection(org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest)  Time elapsed: 2.246 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[Broken pipe]> but was:<[Connection reset]>
	at org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest.testIdleConnection(MllpTcpServerConsumerConnectionTest.java:128)


Results :

Failed tests: 
org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest.testIdleConnection(org.apache.camel.component.mllp.MllpTcpServerConsumerConnectionTest)
  Run 1: MllpTcpServerConsumerConnectionTest.testIdleConnection:128->Assert.assertEquals:144->Assert.assertEquals:115 expected:<[Broken pipe]> but was:<[Connection reset]>
  Run 2: MllpTcpServerConsumerConnectionTest.testIdleConnection:128->Assert.assertEquals:144->Assert.assertEquals:115 expected:<[Broken pipe]> but was:<[Connection reset]>
  Run 3: MllpTcpServerConsumerConnectionTest.testIdleConnection:128->Assert.assertEquals:144->Assert.assertEquals:115 expected:<[Broken pipe]> but was:<[Connection reset]>
```

**Comment by oscerd** [comment]
@hqstevenson, maybe it's an environment problem on my machine. Do you have the same problem?

**Comment by hqstevenson** [comment]
That is very strange - I don't see that failure.

The test is checking the message of the SocketException to make sure it get's the right SocketException, but you're getting a different message in the SocketException than I am.

It's probably too specific anyway - that message could potentially change with every version of Java, and I guess it could be different on every OS.

I removed the part of the test that checks the exception message - I still assert that I get the SocketException, but I don't mess with the message anymore.

**Comment by hqstevenson** [comment]
@devclaus - one other thing I wanted you to take a look at if you could.

The MllpProducerConsumerLoopbackTest had an "@Ignore" on it because sometimes it fails in the CI build.

I wanted this test to run when I was working locally, so I removed the "@Ignore" and added the following method

@BeforeClass
    public static void setUpClass() throws Exception {
        assumeTrue("Skipping test running in CI server - Fails sometimes on CI server with address already in use", System.getenv("BUILD_ID") == null);
    }

This seems to work for me, but I'm assuming the CI server will set the BUILD_ID environment variable.

If there is another variable that would make more sense to check, I'm all for it - I just wanted something that would be different on the CI server so I don't have to keep messing with the "@Ignore" locally

**Comment by oscerd** [comment]
@davscalus I'll wait for your answer to @hqstevenson and then I'll merge this PR :-)

Thanks @hqstevenson and @davsclaus

**Comment by hqstevenson** [comment]
I'd missed on test - to verify that in the case of a failure to deliver the acknowledgement, transactions would rollback.  I added that test

**Comment by davsclaus** [comment]
Yeah sure if the tests passes locally now then go ahead.

**Comment by oscerd** [comment]
Merging.

**Comment by oscerd** [comment]
Merged. Thanks @hqstevenson :-)

Can you close the PR?

**Comment by hqstevenson** [comment]
Thanks everyone

**Pull request closed without merging**
