### PR TITLE
CAMEL-18593: Platform-http : add reverse proxy feature

### PR DESCRIPTION
**Pull request by zbendhiba**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
A problem is that this is only in the vertx implementation so this will not work for others, such as with spring boot that uses servlet.

So it would be good to make this clear in the documentation that currently its only supported when using camel-platform-http-vertx.

**Comment by zbendhiba** [comment]
> A problem is that this is only in the vertx implementation so this will not work for others, such as with spring boot that uses servlet.
> 
> So it would be good to make this clear in the documentation that currently its only supported when using camel-platform-http-vertx.

@davsclaus  I've just updated the documentation

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Hmm there is an error in components/camel-swagger-java maybe its already there and not due to this PR

**Comment by zbendhiba** [comment]
Yes I don't think so, All I changed since last build is the doc file.
I wonder which test is failing, can't reproduce it locally

**Comment by davsclaus** [comment]
@zbendhiba I wonder if you can send a PR for 3.18.x branch.

**Comment by zbendhiba** [comment]
> @zbendhiba I wonder if you can send a PR for 3.18.x branch.

there it is : https://github.com/apache/camel/pull/8581

**Pull request merged**
