### PR TITLE
[CAMEL-10853] Support 'ignoreHeaderCase', 'trim' and 'trailingDelimiter'

### PR DESCRIPTION
**Pull request by ribeaud**
The next time, I will need your formatter. I spent quite some time fixing **Checkstyle** errors...
And I still did not fix the EOL issue. But anyway, you're probably to review, reformat the code anyway. Cheers, christian.

### CODE REVIEW

**Comment by oscerd** [comment]
The code formatter is here

https://github.com/apache/camel/tree/master/etc/eclipse

**Comment by davsclaus** [comment]
Please dont make so many changes. The PR should only be about the extra code.

It should be possible to find what you did to add support for 3 new options only, and any new additional tests. I suggest to redo the PR

**Comment by ribeaud** [comment]
I did not make so many changes. I really try to keep the changes as small as possible. But, because of the EOLs, **GitHub** is thinking I changed the whole file (my guess). Do you know how to fix this? Is that an **IDE** issue, a **Git** one? What should I do? I am working with **Mac** (`git version 2.5.4 (Apple Git-61)`)

**Comment by ribeaud** [comment]
When I am checking in (with **Eclipse**), I do NOT see so many changes, only in the diff of the pull request.

**Pull request closed without merging**
