### PR TITLE
Changes made to CSVrecord section

### PR DESCRIPTION
**Pull request by cudand**
FUSEDOC - 3102 - Made changes to CSVrecord section of bindy data format

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This is autogenerated and needs to be done at java doc level

**Comment by cudand** [comment]
@oscerd Can you point out the java file?

**Comment by oscerd** [comment]
My bad, that table is done by hand. Looks good.

**Comment by cudand** [comment]
Thanks

**Pull request merged**
