### PR TITLE
Update kafka-component.adoc

### PR DESCRIPTION
**Pull request by mikadev**
Adding example for Spring to use FileStateRepository

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR

Can you not use some kind of `startMethod` and `stopMethod` or something similar on Springs `@Bean` annotation to tell spring about the lifecycle methods, that would be better IMHO

**Comment by mikadev** [comment]
Done :)

**Comment by davsclaus** [comment]
Ah they are called initMethod and destroyMethod, so all you need to do is

    @Bean(name = "offsetRepo", initMethod="start", destroyMethod="stop")

**Comment by mikadev** [comment]
Ok nice :+1:  done

**Pull request merged**
