### PR TITLE
camel-websocket: safe extension of endpoint

### PR DESCRIPTION
**Pull request by pgalbraith**
Moving the endpoint initialization code from the component into the endpoint constructor makes it considerably easier to extend WebsocketEndpoint with your own customized endpoint.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I don't think it is a good idea to move all the init logic in the endpoint constructor. Those operations needs to be done on the component side.

**Comment by pgalbraith** [comment]
> I don't think it is a good idea to move all the init logic in the endpoint constructor. Those operations needs to be done on the component side.

Ok I'll see if I can find a better way to do this.

**Comment by pgalbraith** [comment]
@oscerd what do you think of this alternative?

It's clearly less code so cleaner from that perspective.  I prefer the original commit, though, because:

1. This introduces a new protected API method that needs to be supported going forwards
2. If you extend the WebSocketendpoint and change parameters in your endpoint constructor, they will be (possibly) overridden by init code in the component createEndpoint method.  This is not intuitive behaviour to me ... endpoint is a natural Camel extension point so I would expect that parameters I set in my endpoint constructor will 'stick'.

**Comment by oscerd** [comment]
I meant to say that, there are options only set at component level and to me they should be maintained in the component class and managed there, the others could be manipulated also on the endpoint class.

**Comment by pgalbraith** [comment]
Hey @oscerd I'd definnitely agree with that concern, but if you look at the endpoint constructor in the original commit, https://github.com/apache/camel/pull/5824/commits/e702a35958d833791acd7878e70b4f96649ea4a6#diff-a48e9686a61008bb4f518d2f32f50dd73b622e9bc2d912c36fe7f69c0163dcdc, I don't think there's any component data being changed, this is only changing endpoint parameters.  It's definitely not doing it in the cleanest way possible but I tried to preserve (i.e. cut/paste :-o) as much of the original code from the component createEndpoint as I could, to reduce any possibility of refactoring mistakes.

**Comment by oscerd** [comment]
Let's wait for feedback from @davsclaus

**Comment by davsclaus** [comment]
Yes @oscerd is correct - Camel does *NOT* use constructors to initialize endpoints - all such logic must be done in its lifecycle phase, build, init, start etc. There may be some components doing some of this still (old way) but there are 300+ so a few may have some old code - and this websocket component is old and based on jetty.

The last commit to introduce a protected method with newXXX is okay - we do something like that in jms component for example.

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by pdg-chargelab** [comment]
Thanks guys, this is educational for me.  Would it be too ambitious to think about trying to align this component with the new way of doing things?

**Comment by davsclaus** [comment]
The endpoint constructor takes in a set of standard options like uri, remaning, component etc so it looks okay as it is now. Then the endpoint is further configurered via getter/setter and whatnot, and potential afterProperties and other special interfaces it can extend. Then there are the lifecycle phases with build, init, start that setup the endpoint and load resources, create clients, thread pools or whatnot.

Where do you see current code that this component could do something the "new way" ?

**Comment by pgalbraith** [comment]
@davcalus I think I misunderstood what you were saying; I wouldn't know one way or the other.  If the existing PR is good please merge as I can use it to extend, thanks!

**Pull request merged**
