### PR TITLE
CAMEL-11062 : Camel digitalocean component

### PR DESCRIPTION
**Pull request by tlehoux**
I've created a new component to work with DigitalOcean API (https://developers.digitalocean.com/). It's based on work I did at https://github.com/tlehoux/camel-digitalocean where you can find in Readme.md the documentation I wrote.

### CODE REVIEW

**Comment by davsclaus** [comment]
There is some checkstyle issues, can you run

    mvn compile -P sourcecheck

And fix those and push here. Also mind you should remove some stuff in the pom.xml so its similar to the other pom.xml file in the other Camel components.

**Comment by tlehoux** [comment]
Fixed.

**Comment by davsclaus** [comment]
@oscerd I wonder if you want to help review and if possible merge. 

The readme file would need those START END comments for the auto generation to work. And the JAR version need to be put in parent/pom.xml - the usual stuff.

**Comment by oscerd** [comment]
Sure. I'll take care of this

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close this? :-)

**Comment by tlehoux** [comment]
Sure. Thanks for the quick merge.

**Comment by oscerd** [comment]
@tlehoux thanks for your contribution!

**Pull request closed without merging**
