### PR TITLE
camel-15754-Improve the propagation consumer strategy

### PR DESCRIPTION
**Pull request by rajasekharb**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by rajasekharb** [comment]
Not able to understand why build is failing. Getting the below error message.

`Error:  Failed to execute goal org.apache.camel:camel-format-plugin:3.7.0-SNAPSHOT:validate (validate) on project camel-api: File '/home/runner/work/camel/camel/core/camel-api/src/main/java/org/apache/camel/spi/MockSendToEndpointStrategyFactory.java' has not been previously formatted. Please format file and commit before running validation!`

How can I fix the build issue?

**Comment by dmvolod** [comment]
@rajasekharb this error not related to your fix and we can ignore it.

**Comment by dmvolod** [comment]
I will add some fix and merge this PR today

**Review by dmvolod — APPROVED** [review]

**Comment by dmvolod** [comment]
Thanks @rajasekharb , merged. Please close this PR manually, looks like git-hook didn't close daft RR

**Comment by rajasekharb** [comment]
Closed as per @dmvolod 's request

**Pull request closed without merging**
