### PR TITLE
CAMEL-11570: Added example for camel-google-pubsub

### PR DESCRIPTION
**Pull request by sarelp**

### CODE REVIEW

**Comment by sarelp** [comment]
I used the kafka example as basis which also has an application.properties. Maybe change it to example.properties?

**Comment by davsclaus** [comment]
You are also welcome to change the kafka example in another PR

**Comment by sarelp** [comment]
I've renamed application.properties to example.properties

**Comment by dwsjax** [comment]
file:///storage/sdcard1/Android/data/com.acer.ccd/cache/users/000000000110f8c6/mm/mu/t/.sync_temp/2-17889478-111891189-1.db-shm.      That file was added to my phone and pc and I was hacked and please reverse it came from donakdhan 's blog

**Comment by dwsjax** [comment]
file:///storage/sdcard1/Android/data/com.acer.ccd/cache/users/000000000110f8c6/mm/mu/t/.sync_temp/2-17889478-111891189-1.db-shm.      That file was added to my phone and pc and I was hacked and please reverse it came from donakdhan 's blog

**Pull request closed without merging**
