### PR TITLE
upgrade to pubnub 4.13.0

### PR DESCRIPTION
**Pull request by pax95**

### CODE REVIEW

**Comment by oscerd** [comment]
I'll merge today

**Comment by pax95** [comment]
wow. They already released 4.14.0 https://github.com/pubnub/java/releases/tag/v4.14.0
Maybee you could wait until it's synched with central and take that instead.

**Comment by pax95** [comment]
@oscerd You can take it if you don't mind. I'm not sure I'll be able to update the PR before they have made a new release :-)

**Comment by oscerd** [comment]
Sure :-)

**Comment by oscerd** [comment]
Superseded by https://github.com/apache/camel/commit/ec6a5d86f812e0a73bcedc5abbc5377a267f10ca

Thanks for the PR @pax95 :-)

**Pull request closed without merging**
