### PR TITLE
CAMEL-17835 - switch camel-ftp and camel-jsch to forked version of jsch. Add relevant tests.

### PR DESCRIPTION
**Pull request by grgrzybek**

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This looks good, but I would wait for release 3.16.0 and then merge this one. 

There is a checkstyle error in the build.

**Comment by grgrzybek** [comment]
yikes, I've `-Psourcecheck` ed only camel-ftp.

**Comment by grgrzybek** [comment]
Sure. So fix version 3.17.0, right?

**Comment by gzurowski** [comment]
> Let's only wait for @gzurowski to start the release on 3.16.x and rebasing main

I've created and pushed new branches for the 3.16 release. You can go ahead and merge the changes into `main`.

**Comment by grgrzybek** [comment]
Thanks @gzurowski for confirmation!

**Pull request merged**
