### PR TITLE
(chores) camel-kafka: fix a few flaky tests

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Comment by zhfeng** [comment]
It looks like some IT tests don't run.

```
[INFO] Running org.apache.camel.component.kafka.integration.KafkaToDIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.apache.camel.component.kafka.integration.KafkaToDIT
[INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerWithResumeRouteStrategyIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.camel.component.kafka.integration.KafkaConsumerWithResumeRouteStrategyIT
[INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithCustomSerializerIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithCustomSerializerIT
[INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithProcessorIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithProcessorIT
[INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerLastRecordHeaderIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.camel.component.kafka.integration.KafkaConsumerLastRecordHeaderIT
[INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerFullIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.apache.camel.component.kafka.integration.KafkaConsumerFullIT
[INFO] Running org.apache.camel.component.kafka.integration.KafkaProducerFullIT
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.apache.camel.component.kafka.integration.KafkaProducerFullIT
```

**Comment by orpiske** [comment]
> It looks like some IT tests don't run.
> 
> ```
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaToDIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 s - in org.apache.camel.component.kafka.integration.KafkaToDIT
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerWithResumeRouteStrategyIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.camel.component.kafka.integration.KafkaConsumerWithResumeRouteStrategyIT
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithCustomSerializerIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithCustomSerializerIT
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithProcessorIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.apache.camel.component.kafka.integration.KafkaConsumerIdempotentWithProcessorIT
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerLastRecordHeaderIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 s - in org.apache.camel.component.kafka.integration.KafkaConsumerLastRecordHeaderIT
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaConsumerFullIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 s - in org.apache.camel.component.kafka.integration.KafkaConsumerFullIT
> [INFO] Running org.apache.camel.component.kafka.integration.KafkaProducerFullIT
> [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 s - in org.apache.camel.component.kafka.integration.KafkaProducerFullIT
> ```

Yes. And they have not been running on the Apache CI either.

**Review by davsclaus — APPROVED** [review]

**Comment by zhfeng** [comment]
@orpiske Good job! and I just want to know why some kafka IT tests do not run before?

**Comment by orpiske** [comment]
> @orpiske Good job! and I just want to know why some kafka IT tests do not run before?

Thanks. The tests where not running previously because the `KafkaConsumerHealthCheckIT` was self-managing the lifecycle of the service and that was causing subsequent tests to fail to launch (i.e.: because of changed parameters, properties and addresses that happen whenever you bounce a service in the test-infra). 

By isolating it, the other services could proceed executing. 

That said, we still have an issue that we need to solve: https://issues.apache.org/jira/browse/CAMEL-18003.

**Pull request merged**
