### PR TITLE
Update DefaultJdbcPrepareStatementStrategy.java

### PR DESCRIPTION
**Pull request by turongfan**
Support Chinese

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
In this way the regex seems to support only CJK characters. It is not correct

**Comment by oscerd** [comment]
I'm from mobile so I could be wrong

**Comment by davsclaus** [comment]
We only support US ASCII characters for the name placeholder.

**Comment by oscerd** [comment]
Sorry we cannot accept this.

**Pull request closed without merging**
