### PR TITLE
CAMEL-20968 : Camel LangChain4j : add the RAG feature

### PR DESCRIPTION
**Pull request by zbendhiba**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
modified:   components/camel-ai/camel-langchain4j-chat/src/test/java/org/apache/camel/component/langchain4j.chat/LangChain4jChatIT.java

**Review by davsclaus — APPROVED** [review]

**Comment by orpiske** [comment]
> Can you update this file in the PR as its changed
> 
> ```
> modified:   components/camel-ai/camel-langchain4j-chat/src/test/java/org/apache/camel/component/langchain4j.chat/LangChain4jChatIT.java
> ```

Zineb will be on PTO until September. If that's OK, I can merge this code and fix the style issues ...

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
Nice one!

**Comment by davsclaus** [comment]
yeah sure go ahead

**Comment by orpiske** [comment]
Thanks. Let's merge.

**Pull request merged**
