### PR TITLE
CAMEL-12685: fix xslt nested relative refs

### PR DESCRIPTION
**Pull request by pvdbosch**
If an XSLT A includes XSLT B which includes XSLT C using relative references, XSLT C is resolved relative to A instead of B.
An example is added in unit test XsltIncludeRelativeNestedTest.

This PR changes this behavior to the expected one, i.e. resolve relative references based on the location of the direct parent XSLT.

### CODE REVIEW

**Comment by oscerd** [comment]
Please create an issue on https://issues.apache.org/jira/browse/CAMEL with details and reference it in the commit message.

**Comment by oscerd** [comment]
Yes, but in the commit message too, that way we can track the change.

**Comment by pvdbosch** [comment]
OK, I rebased and squashed the commits with a new commit message.

**Comment by oscerd** [comment]
Great thanks.

**Comment by oscerd** [comment]
Thanks. Merged on master.

**Pull request merged**
