### PR TITLE
Fix for CAMEL-8452: Camel route model - Preserve {{ }} placeholders 

### PR DESCRIPTION
**Pull request by chirino**
We preserve just the uri property of ProcessorDefinitions before we create the associated Processor and restore the original value after the the processor is created.

We can probably target more properties to be preserved/restored as the need arrises.

### CODE REVIEW

**Comment by davsclaus** [comment]
There would be more work to do as I think a general approach is needed and not only for uri attributes.

But the idea of restoring after creating processor is good. So IMHO we should be able to

1. remember which we have changed
2. restore back

Ad 1)
By letting resolvePropertyPlaceholders return a Map<String, Object> with the original options that was replaced.

And the same for this guy
https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/model/ProcessorDefinition.java#L430

Ad 2)
And then after the processor is created, then restore them back on the model

Mind that resolvePropertyPlaceholders is used a few places in the ProcessorDefinition so you need to do this in both places.

And also in DataFormatDefinition and RouteDefinitionHelper

**Comment by chirino** [comment]
Hey @davsclaus, i've just push my latest version of the fix.  It has one problem, it's that you have to use replaced route id's in the getRouteDefinition() calls and show up replaced in the id attribute of the route element of the dumpModelAsXml().  See:
https://github.com/chirino/camel/commit/7de51fd5ff33dc83dc58894b38b9ecc87619cf14#diff-2f0c2e22792869e439b2459cbc483a29R32

If you uncomment a [few lines][1] in DefaultCamelContext, then you can use the un-replaced values in those tests.  But then a bunch of other tests start failing.  So I decided to keep it commented for now.

[1]: https://github.com/chirino/camel/commit/7de51fd5ff33dc83dc58894b38b9ecc87619cf14#diff-8f0cf9b8920187a5f4df03841a9ff3f8R2466

**Comment by davsclaus** [comment]
Its a bit ugly to restore after camel context has been started, and doing that around staring camel context. I think this is the taking it too far in a wrong direction.

Okay so lets for now not restore route ids, as that can cause issues (we can look at those later)
And instead implement this where it belongs in the logic of processor definition / prepare route.

**Comment by davsclaus** [comment]
We chatted about this, let me add the chat log here

[13:57:59]  <chirino>	 davsclaus:  CAMEL-8452?
[14:00:12]  <davsclaus>	 ya its only the commented out in the doStart i think its the wrong direction
[14:00:19]  <davsclaus>	 doing stuff after the context has been started
[14:00:23]  <davsclaus>	 but that is not enabled
[14:00:44] 	 mhautman (~mhautman@94.143.188.0) left IRC. (Ping timeout: 20 seconds)
[14:00:54]  <davsclaus>	 having a runnable / callable as the redo action is great/clever
[14:01:19]  <davsclaus>	 you may want to add a little bit of javadoc to the RestoreAction class to desribe a bit of its purpose
[14:01:29]  <davsclaus>	 so when others come along the code that have a better idea what it does
[14:01:35]  <davsclaus>	 because we dont do this elsewhere
[14:01:51]  <davsclaus>	 also the code should pass checkstyle
[14:01:55]  <davsclaus>	 so from cmd run
[14:02:01]  <davsclaus>	 mvn install -Dsourcecheck
[14:02:09]  <davsclaus>	 in camel-core
[14:02:33]  <davsclaus>	 and also create this unit test DumpModelAsXmlPlaceholdersTest
[14:02:35]  <davsclaus>	 in camel-spring
[14:02:44]  <davsclaus>	 so we test it when using spring xml dsl as primary
[14:02:49]  <davsclaus>	 as there can be subtle difference

**Comment by davsclaus** [comment]
Thanks for the PR this has been merged. Do you mind closing this

**Pull request closed without merging**
