### PR TITLE
CAMEL-18275: Address issue of completions not being run in SEDA pipeline

### PR DESCRIPTION
**Pull request by klease**
When synchronizations are handed over, add a method to allow some housekeeping
to be performed. In the OnCompletionProcessor.OnCompletionSynchronizationAfterConsumer
this method stores the routeId on the Exchange.

### CODE REVIEW

**Comment by klease** [comment]
There is some analysis in the JIRA issue from Eduard and myself.

**Comment by jeremyross** [comment]
My tests for this issue are passing with this PR. Also did some regression testing with another decent size integration. All tests pass.

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by Gems** [comment]
Thank you for your effort, guys.
I'd like to understand the way the system is supposed to work after the fix.

Looking at the code I assume that all the completions will be executed when the SEDA pipelist gets completed. Is my assumption correct?

I want to add here that in case "before consumer" mode is used, I'd expect the completions to be executed before the message gets processed in the next queue of the defined pipeline. Does the fix provide such behavior?

**Comment by klease** [comment]
>  Looking at the code I assume that all the completions will be executed when the SEDA pipelist gets completed. Is my assumption correct?

Yes, this is correct.
> I want to add here that in case "before consumer" mode is used, I'd expect the completions to be executed before the message gets processed in the next queue of the defined pipeline. Does the fix provide such behavior?

Unfortunately not. In fact, the current PR doesn't handle the before consumer mode at all. I can add this but unfortunately the completions are still called at the end of the entire pipeline. The change in the PR doesn't prevent the handover from occurring; it only ensures that when the handed-over completions execute, they will perform the logic for all the routes traveled by the exchange and not only the last one.

**Comment by klease** [comment]
I think https://github.com/apache/camel/pull/8105 will make the beforeConsumer mode work as expected by preventing the handover.

**Pull request merged**
