### PR TITLE
CAMEL-16119 Update vertx to version 4.0.3.

### PR DESCRIPTION
**Pull request by jameshilliard**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL-16119) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for this work, but the vertx upgrade should be coordinated upgrade with camel quarkus when we upgrade to quarkus 2 (vertx 4 based). So this is a bit too soon.

However we would like help to upgrade to latest vertx 3.9.x there is some API change that causes a problem in vertx-http component (or was it the vertx-websocket). You are very much welcome to help with that.

**Comment by jameshilliard** [comment]
> the vertx upgrade should be coordinated upgrade with camel quarkus when we upgrade to quarkus 2 (vertx 4 based)

Maybe I've missed something but shouldn't this be a trivial change for something consuming the camel API like quarkus? I tried to minimize the amount of differences to the exposed API and the stuff that did change should be fairly trivial to port best I can tell. I can probably help with that since I'm now fairly familiar with the API changes required.

> However we would like help to upgrade to latest vertx 3.9.x there is some API change that causes a problem in vertx-http component (or was it the vertx-websocket). You are very much welcome to help with that.

I'm currently using this for a vertx 4.0.0 based app so that wouldn't really work for what I'm doing, also I haven't worked with pre-4.0.0 vertx much at all(it's for a fairly new project).

**Review by oscerd — CHANGES_REQUESTED** [review]
Quarkus 2 will be based on Vertx 4, if we upgrade now to Vertx 4, we'll create troubles to camel-quarkus to work.

**Comment by jameshilliard** [comment]
> Quarkus 2 will be based on Vertx 4, if we upgrade now to Vertx 4, we'll create troubles to camel-quarkus to work.

Is there anything holding up the upgrade of Quarkus to version 2? I skimmed the [camel quarkus codebase](https://github.com/apache/camel-quarkus) for vertx usages and didn't notice anything that looked to require a major change.

**Comment by oscerd** [comment]
Quarkus 2 Is not released yet

**Comment by jameshilliard** [comment]
> Quarkus 2 Is not released yet

Oh, so if I'm understanding this correctly [quarkus](https://github.com/quarkusio/quarkus) and [camel](https://github.com/apache/camel/) are both dependencies of [camel quarkus](https://github.com/apache/camel-quarkus) and both need the vertx4 update before [camel quarkus](https://github.com/apache/camel-quarkus) can be updated to vertx4(got a bit confused there and hadn't realized quarkus was different from camel-quarkus)?

I assume it's just finishing [this](https://github.com/quarkusio/quarkus/tree/vertx4) that's a blocker for updating [camel quarkus](https://github.com/apache/camel-quarkus) along with this PR updating [camel](https://github.com/apache/camel/)?

I guess that the quarkus vertx4 update will be around march/april based on [this](https://github.com/quarkusio/quarkus/issues/13768#issuecomment-741648453)? Should we be trying to have vertx4 in a [camel](https://github.com/apache/camel/) release around the same time then?

Would it make sense to merge this PR to [camel](https://github.com/apache/camel/) master or some other non-release branch like how they are doing the [vertx4 quarkus branch](https://github.com/quarkusio/quarkus/tree/vertx4) so that both are ready around the same time so that [camel quarkus](https://github.com/apache/camel-quarkus) can then be updated shortly after both?

**Comment by omarsmak** [comment]
Not only the above, but this as well will break camel-vertx-kafka as the APIs have changed from vertx 3.9.x to 4.x. Nevertheless, if you upgrade to the latest 3.9.x, please make sure camel-vertx-kafka is not broken as well as all the camel-vertx-* components.

**Comment by jameshilliard** [comment]
> this as well will break camel-vertx-kafka as the APIs have changed from vertx 3.9.x to 4.x

Hmm, I ran the tests in `camel-vertx-kafka` and didn't see any failures with 4.x. Is there something specific you're seeing fail there?

**Comment by omarsmak** [comment]
> > this as well will break camel-vertx-kafka as the APIs have changed from vertx 3.9.x to 4.x
> 
> Hmm, I ran the tests in `camel-vertx-kafka` and didn't see any failures with 4.x. Is there something specific you're seeing fail there?

I was under the impression that they have changed the kafka consumer/producer APIs from callback base to Future base and hence it should theoretically fail to even build the component since these APIs are breaking change. However I will need to double check later once we can upgrade to vertx 4.x for any potential breaking changes

**Comment by jameshilliard** [comment]
> I was under the impression that they have changed the kafka consumer/producer APIs from callback base to Future base and hence it should theoretically fail to even build the component since these APIs are breaking change.

From my understanding they added Future style API's but did not remove the callback based API's.

**Comment by omarsmak** [comment]
> > I was under the impression that they have changed the kafka consumer/producer APIs from callback base to Future base and hence it should theoretically fail to even build the component since these APIs are breaking change.
> 
> From my understanding they added Future style API's but did not remove the callback based API's.

Ah then that is good news. I thought they removed the callback based APIs. Thanks for the heads up

**Comment by jameshilliard** [comment]
rebased on master

**Comment by jameshilliard** [comment]
Conflicts resolved and rebased, not sure if this is still too early to be merged but quarkus has a [vertx 4 draft PR](https://github.com/quarkusio/quarkus/pull/14868) now.

**Comment by oscerd** [comment]
It's still too early.

**Comment by oscerd** [comment]
@jameshilliard can you please rebase and fix conflicts? @davsclaus I guess we can start looking at merging this?

**Comment by jameshilliard** [comment]
rebased on master

**Comment by oscerd** [comment]
This the related PR for Microprofile 4.x https://github.com/apache/camel/pull/5390

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
