### PR TITLE
CAMEL-5558 - add file existing move strategy interface to let custom

### PR DESCRIPTION
**Pull request by onderson**
implementations be provided and add a test case for file component

### CODE REVIEW

**Comment by davsclaus** [comment]
LGTM.

The interface for the file exist move strategy would be good to have its method and parameters javadoc'ed as that is what end users can implement for custom strategy.

Does camel-jsch component compile and test with this as its AFAIR also extends the file component.

**Comment by onderson** [comment]
I had a similar requirement. I implemented and tested with file component and naturally ftp component. Have not checked upon jsch. I will look into and improve javadoc. Thanks for reviewing

**Comment by onderson** [comment]
Javadoc improved and no affect on jsch.

**Comment by oscerd** [comment]
I'll merge this today.

**Comment by oscerd** [comment]
Thanks @onderson

**Comment by oscerd** [comment]
Merged on master

**Pull request closed without merging**
