### PR TITLE
CAMEL-12334: Mapped date to LocalDate and time to LocalTime

### PR DESCRIPTION
**Pull request by hemangajmera**
All the changed needed are included.

Please review it carefully as it is my first commit  and PR to camel source.

### CODE REVIEW

**Comment by zregvart** [comment]
Thanks for your contribution :100:

I wonder if it would make more sense to use https://github.com/FasterXML/jackson-modules-java8 module instead of custom converters for `java.time` types.

I also wonder if we want to encourage the use of date/time without timezone information, could lead to subtle bugs.

**Comment by hemangajmera** [comment]
I am not seasoned java developer. I copied the existing code for DateTime to make is work for Date and Time since I got error. So please excuse me if some of my comment doesnt make full sense, since I am not used to most of the libraries and framework used.

1. Regarding use of Jackson Modules. I think that will be better and it may clean up lot of unwanted code which is written. But for XStream, do we still need to have our custom code.

2. Salesforce returns only date without timezone, for eg. "2017-02-17". While receiving data from salesforce and sending it back to salesforce we need to use only date and time in UTC timezone (https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/primitive_data_types.htm)
Also there was no suitable class for Date with timezone in java.time package, hence I used LocalDate and LocalTime. I could have use OffsetTime, but kept it identical.

**Comment by zregvart** [comment]
@hemangajmera thank you for clarifying this, I think we should address this issue so we can parse given dates properly. What do you think, given that Salesforce documentation specifies that `date` and `dateTime` primitive data types will be returned in UTC timezone, should we make sure that when parsing those they are converted to the proper local timezone when mapped to LocalDate and LocalDateTime?

**Comment by hemangajmera** [comment]
@zregvart Thanks for your feedback..

We are using ZonedDateTime, so DateTime is not an issue.

Time can be converted to OffsetTime, so that conversion to localTime can be handled properly.

Regarding Date, I think it should be still LocalTime, since most of the Business UseCases which I have seen, date should be date only. Common example of dates are BirthDate, etc, where time is not significant, or should not be considered. Let me know your thought,

**Comment by hemangajmera** [comment]
@zregvart  Should I change LocalTime to OffsetTime with Offset Value as 0? That way we get exact time value irrespective of timezone.

**Comment by zregvart** [comment]
I think the most widely used one is ZonedDateTime for holding date and time values.  That doesn't prevent us from supporting all combinations and letting the user choose the type in the data transfer object.
The default, I think, in the Maven plugin for generating data transfer objects should stay ZonedDateTime. We could make it configurable, so that the user can some control over the code generation. That would also be good in the interest of keeping the generated code backward compatible.

**Comment by hemangajmera** [comment]
@zregvart  I will update the code which property to control if we want ZonedDateTime or other. I will also change LocalTime to OffsetTime.

**Comment by davsclaus** [comment]
@zregvart yeah good idea to make it compatible and an option to turn this on|off.

**Comment by hemangajmera** [comment]
Changes are done. Please review it. The default value of parameter is set such that it does not use ZonedDateTime, since we cannot marshal/unmarshal to ZonedDateTime from "yyyy-MM-dd" format of Date which is used by salesforce. So I thought it will be better to have default value which works out of the box.

However this break backward compatibility for generating the DTO, unless useZonedDateTimeForDate and useZonedDateTimeForDate are set to true.

I have also updated the documents to reflect these changes.

**Comment by zregvart** [comment]
Thank you for your effort @hemangajmera :1st_place_medal:. I don't think we should change the defaults but we should make date/date and time objects in DTOs configurable. Also the defaults as they were using ZonedDateTime are the safest way of handling date/time values. Relying just on offset could lead to wrong values with regards to daylight saving time.
I see that we have a bit of work left to make this a bit better and I'm working in parallel on this. I think the best approach would be that I create a pull request with this work and invite you to review it. I'll incorporate bits that you have worked on.

**Comment by hemangajmera** [comment]
@zregvart 
Thanks for taking out time for this. I had already made default value as the one what we have right now, but was not able to commit it earlier. I have committed that now.

I will wait for your pull request to see how you are doing. It is good learning for me!

**Comment by zregvart** [comment]
@hemangajmera I've created #2263 and I'll close this.

**Pull request closed without merging**
