### PR TITLE
CAMEL-11242 Split camel-twitter component/endpoint into 4 (directmess…

### PR DESCRIPTION
**Pull request by igarashitm**
…age, search, streaming, timeline)

### CODE REVIEW

**Comment by davsclaus** [comment]
We should maybe consider twitter-search:endpointId, to let endpointId be the keywords, so you can do a search using `twitter-search:#apachecamel` to search for `#apachecamel` etc.

And there is another one of them that has an unused path param. Maybe we can turn that into something useful?

**Comment by davsclaus** [comment]
But maybe we should do that in another PR so this big PR is just the migration as-is, and then a separate PRs for more refinements.

**Comment by davsclaus** [comment]
Just to be sure, you updated the twitter examples as well we have in the examples directory?

**Comment by igarashitm** [comment]
Good point! I thought about using search keyword for URI path, but I focused on refactoring this time. The direct message also has a dummy URI path, which could be a destination user ID for producer, but still wondering if there's something good for consumer. Anyway I'll raise a follow up JIRA and submit another PR.
And yes, I updated a few examples which are using twitter endpoint to use new URI.

**Pull request closed without merging**
