### PR TITLE
Moves the Kafka test infrastructure

### PR DESCRIPTION
**Pull request by orpiske**
Moves part of the Kafka test infrastructure from the Camel Kafka Connector to Camel Core

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by orpiske** [comment]
@lburgazzoli this is related to the discussion about moving some of the reusable test infra from CKC to Camel  Core. 

Do you think this would do the trick for Camel Quarkus as well?

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
The license headers in the XML files are using the wrong style (eg ~)

**Comment by oscerd** [comment]
When you want @orpiske this can be merged.

**Comment by orpiske** [comment]
> When you want @orpiske this can be merged.

Thanks Andrea, I think we are good to go. 

Just let me have a quick chat w/ Luca on Monday morning to make sure this covers the basics for Camel Quarkus as well.

**Review by lburgazzoli — APPROVED** [review]

**Comment by orpiske** [comment]
Just talked to Luca, we are good to go. Subsequently, I can/will adjust if needed.

**Pull request merged**
