### PR TITLE
CAMEL-18170 - Enabling to serviceAccountKey as base64 to google-drive…

### PR DESCRIPTION
**Pull request by rhuan080**
… component

Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>

Enabling to use service account key as base64.

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by davsclaus** [comment]
There should already be support for this out of the box
org.apache.camel.impl.engine.DefaultResourceResolvers.Base64Resolver

Does it not already work?

**Comment by rhuan080** [comment]
Hi @davsclaus,

Yes! Actually, it is working. Thus, I think the issue was a misunderstanding caused by the option name. The BigQuery use the `serviceAccountKey` name and the google drive (and remaining components) uses `keyResource`. Thus, I think the changes are just about docs. 

I think we should rename the option `keyResource` to `serviceAccountKey`.

**Comment by davsclaus** [comment]
> I think we should rename the option keyResource to serviceAccountKey.

Yeah if its for this then a better name is a good idea. You are welcome to rename the option.
We then need to add a note in the 3.18 upgrade guide at about this:
https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_18.adoc

**Comment by rhuan080** [comment]
Updated! I`ll upgrade the guide! Thank you @davsclaus :-)

**Review by davsclaus — APPROVED** [review]

**Comment by rhuan080** [comment]
I sent a PR to update the doc --> https://github.com/apache/camel/pull/7763

**Pull request merged**
