### PR TITLE
CAMEL-14588: New setting to allow mails to be moved after processing

### PR DESCRIPTION
**Pull request by mash-sap**
New setting to allow mails to be moved after processing

### CODE REVIEW

**Comment by oscerd** [comment]
And please run the build on camel-mail with the profile sourcecheck enabled and fix the warnings you'll get the github action reports 4 errors.

**Comment by davsclaus** [comment]
The moveTo option must also be add as configuration option, find the copyTo option and do similar code.

**Comment by mash-sap** [comment]
> The moveTo option must also be add as configuration option, find the copyTo option and do similar code.

I added the moveTo option to MailConfiguration.java similar to the copyTo commit (b5be70cbba264856dd0291a583a5d3cb1047bdfe). Is there any other place where it has to be added?

**Comment by mash-sap** [comment]
> Please add some documentation about this possibility in src/main/docs adoc file

Done

**Pull request merged**
