### PR TITLE
RFC: fix deployment job

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
@davsclaus @ppalaga the [deployment job on CI](https://ci-builds.apache.org/job/Camel/job/Camel%20Daily%20Snapshot%20Deploy/job/main/) is broken for several days. It seems that these 2 patches have broken it ... unfortunately I am not sure if that would cause other things to break. Please, would you mind taking a look and let me know what you think?

**Comment by davsclaus** [comment]
The `jar-no-fork` was a fix for building the RC1 release. But we did also fix some other bits. Maybe its no longer needed

**Comment by ppalaga** [comment]
```
[INFO] --- source:3.3.0:jar (attach-sources) @ camel-util ---
[INFO] Building jar: /home/jenkins/workspace/Camel_Daily_Snapshot_Deploy_main/core/camel-util/target/camel-util-4.0.0-SNAPSHOT-sources.jar
[INFO] 
[INFO] --- source:3.3.0:jar-no-fork (attach-sources) @ camel-util ---
[ERROR] We have duplicated artifacts attached.
```

There are two source jars with the same coordinates produced, where there must be only one. I guess using jar-no-fork everywhere could solve it.

**Comment by ppalaga** [comment]
Let me try that

**Comment by ppalaga** [comment]
> Let me try that

Done here https://github.com/apache/camel/pull/10662

**Comment by orpiske** [comment]
> > Let me try that
> 
> Done here #10662

The other PR solves the problem. Closing this one as invalid.

**Pull request closed without merging**
