### PR TITLE
[CAMEL-15276] camel-weather: properly initialize GeoLocationProvider

### PR DESCRIPTION
**Pull request by amdmdi**
- Fix this issue (CAMEL-15276) by using the geolocationAccessKey and geolocationRequestHostIP from the WeatherConfiguration instead of WeatherComponent
- Move httpClient parameter to WeatherConfiguration
- Introduce a new parameter geoLocationProvider to allow the use of a custom GeolocationProvider (the default implementation relies on a third party service i.e. the ipstack API)

### CODE REVIEW

**Comment by amdmdi** [comment]
This PR changes the parameters and options of the component. If that's not desirable, then I can try to just fix the issue without those changes.

PS: this component needs more work imo, for example **WeatherQuery.getQuery** changes some values in the WeatherConfiguration which is a side effect.

**Comment by amdmdi** [comment]
I added the note in this PR. Is that okey ?

**Comment by oscerd** [comment]
Perfect, thanks.

**Comment by oscerd** [comment]
Thanks

**Comment by amdmdi** [comment]
my pleasure

**Pull request merged**
