### PR TITLE
upgrade versions of optaplanner and kie as they are from same release…

### PR DESCRIPTION
**Pull request by mswiderski**
… cycle

@oscerd this should resolve any issues with version mismatch, though I didn't run complete build so can't say for sure, would it be possible to somehow double check that?

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks, but actually this will break the camel-optaplanner Karaf feature, can you take a look?

**Comment by mswiderski** [comment]
@oscerd features for optaplanner updated and the karat test (org.apache.camel.itest.karaf.CamelOptaplannerTest) is green

**Comment by oscerd** [comment]
I'll merge ASAP, thanks for this

**Comment by mswiderski** [comment]
just a sec, one small version update is coming...

**Comment by mswiderski** [comment]
@oscerd ok, all done - just used lie-version property for org.kie stuff.

btw not sure how you deal with that but feel free to set me as default assignee for jiras for camel-jbpm component so I could react to any issues raised :)

**Comment by oscerd** [comment]
Sure, it would be great if you can take a look at new issues.

**Comment by oscerd** [comment]
This has been merged, thanks @mswiderski :-)

**Pull request closed without merging**
