### PR TITLE
CAMEL-17131: camel-kafka - Consumer should not be in reconnect state …

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Review by orpiske — APPROVED** [review]

**Comment by orpiske** [comment]
I think it should be fine, but I'll only be able to test it for sure on Monday.

**Comment by orpiske** [comment]
I am looking at this one right now. My morning was busier than usual.

**Comment by orpiske** [comment]
I test this and it is failing. 

The problem is that the current consumer initialization is unnecessarily complex (it's a leftover from the previous logic) and it depends on the status of the reconnecting flag: https://github.com/apache/camel/blob/main/components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java#L128-L136 

Using your patch, I did a small refactoring to simplify the initialization logic: https://github.com/orpiske/camel/commit/79a39b7cb1f08ba033bf2f27d249c787da5c9002

**Comment by orpiske** [comment]
@davsclaus if you are fine w/ the approach, I think we can go ahead and merge this one ... and I'll open a PR to merge the remaining cleanup f/ the subscription logic (including the logs). That should also fix the double-initialization problem.

**Comment by davsclaus** [comment]
yes +1

**Review by oscerd — APPROVED** [review]

**Pull request merged**
