### PR TITLE
"camel-jackson - Upgrade to 2.13.x"

### PR DESCRIPTION
**Pull request by ramu11**
CAMEL-17469:camel-jackson - Upgrade to 2.13.x

### CODE REVIEW

**Comment by ramu11** [comment]
Both camel-spring-boot and Quarkus using camel-jackson 

I run the build with test cases for both

**Review by oscerd — CHANGES_REQUESTED** [review]
You need to check the camel-karaf features and camel-azure real integration tests. There is some mess with eventhubs and Jackson.

**Comment by ramu11** [comment]
can i update this version also to the 2.13.1

**Comment by ramu11** [comment]
>

**Comment by ramu11** [comment]
camel-karaf is removed as per this commit

https://github.com/apache/camel/commit/db7b13344b1c2dc4bfdd8de4530d0aaae4f01a93

**Comment by davsclaus** [comment]
The json-validator in karaf needed to be updated too - I have done that

**Pull request closed without merging**
