### PR TITLE
CAMEL-16853: fix resultHandlerFactory, add unit test

### PR DESCRIPTION
**Pull request by rikvb**
Unit test provided that demonstrates the flaw in current code.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
There is a cycle dependency with maven now
```
Error: ] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.camel:camel-test-spring-junit5:3.12.0-SNAPSHOT'}' and 'Vertex{label='org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT'}' introduces to cycle in the graph org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT --> org.apache.camel:camel-management:3.12.0-SNAPSHOT --> org.apache.camel:camel-core:3.12.0-SNAPSHOT --> org.apache.camel:camel-xslt:3.12.0-SNAPSHOT --> org.apache.camel:camel-test-spring-junit5:3.12.0-SNAPSHOT --> org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT @ 
Error:  The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.apache.camel:camel-test-spring-junit5:3.12.0-SNAPSHOT'}' and 'Vertex{label='org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT'}' introduces to cycle in the graph org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT --> org.apache.camel:camel-management:3.12.0-SNAPSHOT --> org.apache.camel:camel-core:3.12.0-SNAPSHOT --> org.apache.camel:camel-xslt:3.12.0-SNAPSHOT --> org.apache.camel:camel-test-spring-junit5:3.12.0-SNAPSHOT --> org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT -> [Help 1]
```

Can you avoid using camel-test-spring5 and just build a unit test that are Java DSL based

**Comment by rikvb** [comment]
Apologies, I borrowed some code from saxon-xslt since it's very similar and forgot to check for this. I have rewritten the unit test using DSL and camel-test-junit5, but the cyclic dependency still exists:

cyclic reference: Edge between
	'Vertex{label='org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT'}' and
	'Vertex{label='org.apache.camel:camel-management:3.12.0-SNAPSHOT'}'
		introduces to cycle in the graph
			org.apache.camel:camel-management:3.12.0-SNAPSHOT
			--> org.apache.camel:camel-core:3.12.0-SNAPSHOT
			--> org.apache.camel:camel-xslt:3.12.0-SNAPSHOT
			--> org.apache.camel:camel-test-junit5:3.12.0-SNAPSHOT
			--> org.apache.camel:camel-management:3.12.0-SNAPSHOT @

Any suggestions?

**Comment by davsclaus** [comment]
Yes the unit test should not be in camel-xslt, but in core/camel-core, there are some xslt tests there

**Comment by rikvb** [comment]
Moved test to core, reverted changes to camel-xslt pom. Change is now just 1 new unit test and a 3-line move

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
