### PR TITLE
[CAMEL-7810] Fix JdbcAggregationRepository optimistic locking feature (2.25.x)

### PR DESCRIPTION
**Pull request by fvaleri**
Running JdbcAggregationRepository on a distributed environment (multiple independent
threads or multiple JVMs) we have silently dropped exchanges. This PR aims at introducing
a version identifier to avoid the lost update problem (overwrites when updating the
aggregate row) as stated by the OptimisticLockingAggregationRepository SPI.

Tested running 100 threads to aggregate 10k messages on MySQL 5.7 and PostgreSQL 11.5.

Will also create a proper unit test from my testing application.
After review we can also port this on master.

### CODE REVIEW

**Comment by davsclaus** [comment]
Ah this is 2.x - We dont do this upstream as it breaks users there, so we need a PR for master branch only.

**Comment by oscerd** [comment]
If we don't consider that a bug.. We can add this to master and maybe consider a backport if we'll ever release a 2.26.0 at some point.

**Comment by davsclaus** [comment]
Yeah lets gets this merged on master, if @fvaleri can provide a new PR. If not we can take this PR and then put on 2.25.x temporary on local and then cherry-pick to master and remove the 2.25.x PR. We cannot apply this to 2.25.x as its a breaking change for existing users.

If Camel 2.26 is done then yeah we can go back and cherry pick this PR.

**Comment by fvaleri** [comment]
Thanks guys. 
I'm going to open the same PR against master, also adding changes to the update guide.

I think this should be considered an old bug, but it's up to you :)

**Comment by davsclaus** [comment]
For 2.25.x you could create the fix with the version column in a new class so the end users can decide to use this new version by using the new class and keep the old

**Comment by fvaleri** [comment]
Fixed some failing tests, I'm creating the master PR right now.
@davsclaus yep, will look at this strategy

**Comment by fvaleri** [comment]
Added `JdbcAggregationRepositoryNew` as separate class to avoid breaking applications using the old repository layout and a note about it in the component page. Will add an example on how to use it with another PR later.

**Pull request merged**
