### PR TITLE
[CAMEL-11257] Fixed multipart parsing logic and updated tests

### PR DESCRIPTION
**Pull request by punkhorn**

### CODE REVIEW

**Comment by davsclaus** [comment]
There is likely some checkstyle issues (code formatting), you can run from command line in the camel-as2 folder

    mvn compile -P sourcecheck

And then fix the reported issues.

**Comment by oscerd** [comment]
The component is missing the adoc file for the documentation

**Comment by oscerd** [comment]
and since we added the component to the build the CI job for master branch is failing as @PascalSchumacher reported

**Comment by punkhorn** [comment]
@davsclaus I always do a full build with the sourcecheck profile enabled. There were no issues reported when submitting this pull request and I have rebuilt again with no issues. Can you point me to specific issues with code formatting in this pull request you have encountered?

**Comment by punkhorn** [comment]
@oscerd can you point me to the build issues you are encountering in CI job?

**Comment by davsclaus** [comment]
Found these
```
[INFO] Starting audit...
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java:24: Wrong order for 'java.io.IOException' import. [ImportOrder]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MultipartSignedEntity.java:56:5: File contains tab characters (this is the first instance). [FileTabCharacter]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:97: 'if' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:97:9: File contains tab characters (this is the first instance). [FileTabCharacter]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:99: 'else' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:115: 'if' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:117: 'else' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:151: 'if' child have incorrect indentation level 16, expected level should be 12. [Indentation]
[ERROR] /Users/davsclaus/workspace/camel/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MimeEntity.java:153: 'else' child have incorrect indentation level 16, expected level should be 12. [Indentation]
Audit done.
[INFO] There are 9 errors reported by Checkstyle 7.6.1 with camel-checkstyle.xml ruleset.
```

I have merged the PR as its just a click of a button.

You can fix these in another PR

**Comment by punkhorn** [comment]
@davsclaus Hmm not seeing these locally. I will rebase and see if I encounter.

**Comment by oscerd** [comment]
@punkhorn here is the job https://builds.apache.org/view/C/view/Apache%20Camel/job/Camel/job/master/256/console

**Comment by punkhorn** [comment]
@oscerd can't reproduce CI issue locally. Rebased on master locally and rebuilt without issues. I am not running into the issue with camel-api-component-maven-plugin not do I have any checkstyle errors. Do you have a custom configuration for this build that may not be generating JavaDoc and with alternate checkstyle rules?

**Comment by oscerd** [comment]
@punkhorn I'm unable to reproduce locally too.

I added the first skeleton of the documentation here:

https://github.com/apache/camel/blob/master/components/camel-as2/camel-as2-component/src/main/docs/as2-component.adoc

You can start adding information and examples.. The endpoint options and component options are generated automatically on each build if something has changed.

**Comment by PascalSchumacher** [comment]
I can replicated the build failure locally.

It occurs if I execute `mvn test` (like jenkins does) and do not have `camel-as2-api-javadoc.jar` in my local maven repository.

If I execute `mvn install` the build works.

For some reason the javadoc artifact is not downloaded from the camel snapshot repository.

What is confusing me, is that the build of `camel-box` does not display the same problem, even though is very similar.

**Pull request merged**
