### PR TITLE
CAMEL-11626 - Provide a value for the %d in String format

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Can you rebase on master ?

**Comment by apupier** [comment]
@lburgazzoli I'm already on latest master

**Comment by lburgazzoli** [comment]
One commit is missing:

```
7996012    | 2017-08-03 | Andrea Cosentino     | Upgrade Kubernetes client to version 2.5.8
```

**Comment by lburgazzoli** [comment]
Thx @apupier

**Pull request merged**
