### PR TITLE
CAMEL-11048 Jetty Producer always uses "Transfer-Encoding: chunked" header

### PR DESCRIPTION
**Pull request by mluckam**

### CODE REVIEW

**Comment by davsclaus** [comment]
The code has some small formatting issues. Do you mind running

    mvn compile -P sourcecheck

In the camel-jetty component and fix the issues reported. And then push a commit up here.

**Comment by oscerd** [comment]
Looks good to me.

**Comment by davsclaus** [comment]
@oscerd yeah you are welcome to merge

**Comment by oscerd** [comment]
Sure. I'll merge later today.

**Comment by oscerd** [comment]
@mluckam thanks! The PR has been merged. Can you close this?

**Pull request closed without merging**
