### PR TITLE
[Documentation] Fixing operators 'starts with' and 'ends with'

### PR DESCRIPTION
**Pull request by claudiohigashi**
The correct operators are:
- starts with
- ends with
All lowercase and with a space between them. It was previously startsWith and endsWith, which is not accepted by Camel (fails at runtime).

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by claudiohigashi** [comment]
> I think this is wrong the correct name for simple operator are "startsWith" and "endsWith"

No. Definitely that's right.

When I use 'startsWith' I get this exception at runtime:

	Caused by: org.apache.camel.language.simple.types.SimpleIllegalSyntaxException: Unexpected token s at location 20
	${body.messageType} startsWith '112'
						*

		at org.apache.camel.language.simple.SimplePredicateParser.parsePredicate(SimplePredicateParser.java:69) ~[camel-core-2.18.1.jar:2.18.1]
		at org.apache.camel.language.simple.SimpleLanguage.createPredicate(SimpleLanguage.java:115) ~[camel-core-2.18.1.jar:2.18.1]
		at org.apache.camel.builder.SimpleBuilder.createPredicate(SimpleBuilder.java:102) ~[camel-core-2.18.1.jar:2.18.1]
		... 13 common frames omitted

When I replace it by 'starts with' then it works perfectly.

I found the correct operators in an old Camel documentation. Somehow this typo was introduced in the new documentation. Please, check this:
https://cwiki.apache.org/confluence/display/CAMEL/Simple

**Comment by oscerd** [comment]
The documentation you're trying to modify refers to camel 3 master and on camel 3 master it's startsWith and endsWith, and "starts With" and "ends with" (both are valid as you can see from the example)

You can see the difference here: 
https://github.com/apache/camel/blob/master/core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleOperatorTest.java#L673

and on 2.18.x, the version you're referring to
https://github.com/apache/camel/blob/camel-2.18.x/camel-core/src/test/java/org/apache/camel/language/simple/SimpleOperatorTest.java#L551

So the documentation is correct.

**Comment by claudiohigashi** [comment]
> The documentation you're trying to modify refers to camel 3 master and on camel 3 master it's startsWith and endsWith, and "starts With" and "ends with" (both are valid as you can see from the example)
> 
> You can see the difference here:
> https://github.com/apache/camel/blob/master/core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleOperatorTest.java#L673
> 
> and on 2.18.x, the version you're referring to
> https://github.com/apache/camel/blob/camel-2.18.x/camel-core/src/test/java/org/apache/camel/language/simple/SimpleOperatorTest.java#L551
> 
> So the documentation is correct.

Okay. Agreed. I"ll close this then.

**Comment by oscerd** [comment]
I'll add a note about the possibilty of using also starts With and ends with because they are supported.

Thanks for spotting this different @claudiohigashi 
if you want you can open another PR with this note. Thanks

**Comment by claudiohigashi** [comment]
> I'll add a note about the possibilty of using also starts With and ends with because they are supported.
> 
> Thanks for spotting this different @claudiohigashi
> if you want you can open another PR with this note. Thanks

I just created this new PR:
https://github.com/apache/camel/pull/3728

**Pull request closed without merging**
