### PR TITLE
CAMEL-19409: WIP PR for 401 error in streaming API

### PR DESCRIPTION
**Pull request by jeremyross**
Reauthenticate and subscribe if a 401 error is received in the META_SUBSCRIBE channel.

### CODE REVIEW

**Comment by jeremyross** [comment]
@jsight Can you please give this a whirl?

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@jeremyross is this PR ready for merging or do you want more time / feedback etc?

**Comment by davsclaus** [comment]
Any update on this PR

**Comment by jeremyross** [comment]
No one could confirm this PR helped. Let's close.

**Pull request closed without merging**
