### PR TITLE
(chores) camel-http / camel-rest: fix usage of deprecated option

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
its maybe a few other places too


components/camel-http/src/test/java/org/apache/camel/component/http/rest/RestCamelComponentVerifierTest.java:        parameters.put("componentName", "http");
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowComponentVerifierTest.java:        parameters.put("componentName", "undertow");
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowComponentVerifierTest.java:        parameters.put("componentName", "undertow");
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowComponentVerifierTest.java:        parameters.put("componentName", "undertow");
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowComponentVerifierTest.java:        parameters.put("componentName", "undertow");
core/camel-core/src/test/java/org/apache/camel/component/rest/RestComponentVerifierExtensionTest.java:        parameters.put("componentName", "rest-component");
core/camel-core/src/test/java/org/apache/camel/component/rest/RestComponentVerifierExtensionTest.java:        parameters.put("componentName", "rest-component");
core/camel-core/src/test/java/org/apache/camel/component/rest/RestComponentVerifierTest.java:        parameters.put("componentName", "rest-component");
core/camel-core/src/test/java/org/apache/camel/component/rest/RestComponentVerifierTest.java:        parameters.put("componentName", "rest-component");

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
btw undertow = I have fixed that

**Comment by orpiske** [comment]
> btw undertow = I have fixed that

Ah, thanks! That will be a good one to test the GH actions changes for Camel 3 and 4.

**Comment by orpiske** [comment]
> > btw undertow = I have fixed that
> 
> Ah, thanks! That will be a good one to test the GH actions changes for Camel 3 and 4.

BTW, I can't find the commit. We'll need to cherry-pick that to 3.x.

**Comment by davsclaus** [comment]
ah sorry it was only on main and not committed yet - and btw the tests was removed as I removed a deprecated feature in undertow

**Pull request merged**
