### PR TITLE
CAMEL-10296: waitForConfirmsOrDie does not return if no timeout is set

### PR DESCRIPTION
**Pull request by gessnerfl**
for publisher acks and guaranteed delivery

### CODE REVIEW

**Comment by davsclaus** [comment]
The boolean should likely be volatile, or an AtomicBoolean. 

Also mind about checkstyle. You can run a build with

    mvn compile -Psourcecheck

**Comment by oscerd** [comment]
Yes, I was looking at the PR and I noticed a bit of sourcecheck errors

**Comment by oscerd** [comment]
Thanks, I'm reviewing and I'll merge soon

**Comment by gessnerfl** [comment]
Already saw the checkstyle violations this morning and fixed them right now. 
As each message publish is handled by a new RabbitMQMessagePublisher there should be no concurrent access on the local variables. But to be on the save side I set the variable to volatile to make sure we do not run into any concurrency issues here.

**Comment by oscerd** [comment]
I merged the PR, but I amended the last commit message to refer to CAMEL-10296 and not CAMEL-10239

Thanks a lot @gessnerfl 

Can you close the PR?

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
