### PR TITLE
CAMEL-11304

### PR DESCRIPTION
**Pull request by elihusmails**
Added functionality for distinct queries in the camel-mongodb3 component.  Source code has been merged with latest from upstream and code style has been verified.

### CODE REVIEW

**Comment by onders86** [comment]
Hi, Could you squash your changes to a single commit?

**Comment by oscerd** [comment]
This looks good, btw as @onders86 suggested it's better to squash the commit.

**Comment by davsclaus** [comment]
We can also squash it for you, I have a squash alias I find handy
```
squash	 => !f(){ git reset --soft HEAD~${1} && git commit --edit -m"$(git log --format=%B --reverse HEAD..HEAD@{1})"; };f
```
I found it somewhere on one of those git expert sites

And remember to run a --rebase before merging so the git tree is a straight line

**Comment by davsclaus** [comment]
Okay I have cherry-picked the commit into master, this PR can be closed

**Pull request closed without merging**
