### PR TITLE
CAMEL-11281: added org.apache.camel.model.Constants.JAXB_CONTEXT_PACK…

### PR DESCRIPTION
**Pull request by guyv**
…AGES to Import-Package osgi header

### CODE REVIEW

**Comment by guyv** [comment]
not 100% sure about the ${camel.osgi.import.strict.version}

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by guyv** [comment]
@davsclaus do you need a PR for 2.19.x as well?

**Comment by davsclaus** [comment]
No it has been fixed on other branches

**Pull request closed without merging**
