### PR TITLE
CAMEL-20051: do cache fallback conversions

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
Tentative fix for Camel Quarkus performance issue reported on apache/camel-quarkus#5452.

**Comment by orpiske** [comment]
c/c @aldettinger

**Comment by orpiske** [comment]
Obs.: waiting for the tests on my own CI before removing the draft mark.

**Review by oscerd — APPROVED** [review]

**Review by aldettinger — APPROVED** [review]
Ok, it looks good to me with Camel 4.2.0-SNAPSHOT + fix cherry-picked

```
 Camel Quarkus Throughput Performance Increase Compared to Previous Version  
 Camel Quarkus version  |  Duration  |   JVM req/s [%increase]   |  Status  |
-----------------------------------------------------------------------------
                 3.4.0  |       10m  |  36196.56 req/s [+0.00%]  |      OK  |
        3.5.0-SNAPSHOT  |       10m  |  36679.73 req/s [+1.33%]  |      OK  |
```

**Pull request merged**
