### PR TITLE
CAMEL-11117: Fix searchTerm error with unseen and subjectOrBody

### PR DESCRIPTION
**Pull request by lio-p**

### CODE REVIEW

**Comment by davsclaus** [comment]
Looks good @oscerd do you mind merging to 2.18.x and master branches. Pay attention that this PR is against 2.18.x branch.

**Comment by oscerd** [comment]
Sure

**Comment by oscerd** [comment]
Merged on master and 2.18.x

**Comment by oscerd** [comment]
Thanks for the PR @lio-p

**Pull request merged**
