### PR TITLE
CAMEL-9684 - camel-infinispan : add support for setting query builder…

### PR DESCRIPTION
**Pull request by lburgazzoli**
… in InifispanConfiguration

### CODE REVIEW

**Comment by davsclaus** [comment]
After merging this our CI server fails with

```
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project camel-infinispan: Compilation failure -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:testCompile (default-testCompile) on project camel-infinispan: Compilation failure
```

See
https://builds.apache.org/job/Camel.trunk.notest/2682/consoleText

I wonder if you have that problem to? Or is it a java 7 vs java 8 issue when using either one to compile?

**Comment by lburgazzoli** [comment]
I have the same error but on main branch too.
As far as I know camel-infinispan requires java 8 for the test to run:

```xml
        <profile>
            <id>jdk8-test</id>
            <activation>
                <jdk>!1.8</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

**Comment by lburgazzoli** [comment]
Digging into the problem a little bit more, I see that the problem is caused by : 

```
An exception has occurred in the compiler (1.7.0_80). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for java.util.function.Supplier not found
```

@davsclaus should we skip building tests on on JDK < 1.8 ? The following tweak seems wotking:

```xml
        <profile>
            <id>jdk8-test</id>
            <activation>
                <jdk>!1.8</jdk>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <skipTests>true</skipTests>
                        </configuration>
                    </plugin>
                    <plugin>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>default-testCompile</id>
                                <phase>test-compile</phase>
                                <goals>
                                    <goal>testCompile</goal>
                                </goals>
                                <configuration>
                                    <skip>true</skip>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
```

**Comment by davsclaus** [comment]
Yeah we should skip building the tests on java 7.

**Comment by lburgazzoli** [comment]
Done by https://github.com/apache/camel/pull/893

**Pull request closed without merging**
