### PR TITLE
Initial version of camel-everit-json-schema component

### PR DESCRIPTION
**Pull request by ullgren**
Initial pull request for a JSON Schema validator component based on the Everit JSON Schema library. If this is of interest I have backport for 2.19 and 2.18 branches.

It also lacks the karaf feature for this component that is work in progress. The Everit JSON Schema is already packaged as a bundle.

### CODE REVIEW

**Comment by erosb** [comment]
Hello!

I'm the maintainer of `everit-org/json-schema`. Thank you for your efforts on this, I have been following the updates on CAMEL-9799 for a long time. A few comments at the first glance:

 * `JsonSchemaValidatorEndpoint` loads the JSON Schema with the default schema loader config (I mean the `SchemaLoader.load(rawSchema)` call in line 80). It would be better to let the schema loading be customizable by the camel users. I'm not sure how does it fit into the concept of a camel endpoint though. At the first glance I suggest 
    - creating a `JsonSchemaLoaderBuilderFactory` interface (maybe with a simpler name..) with a `SchemaLoaderBuilder createSchemaLoader()` method
    - the `JsonSchemaValidatorEndpoint` would have a `schemaLoaderBuilderFactory` member, with a default implementation, but it should be injectable by users (this is the point where I'm not sure how dependency injection works for these endpoints).

Its advantage would be letting users configure their schema loader, eg. adding [custom format validators](https://github.com/everit-org/json-schema#format-validators), etc.

I think the default implementation of `JsonSchemaLoaderBuilderFactory` should create the loader builder with `return SchemaLoader.builder().draftV6Support();` so users can take the advantage of the latest draft without any additional configuration. 

FYI, `everit-org/json-schema` considers draft v4 by default, which is currently deprecated, and is not compatible with draft v6 (which is currently published on json-schema.org as "the" specification). This is implemented this way for compatibility reasons for developers willing to upgrade from prior versions - see more [here](https://github.com/everit-org/json-schema#draft-4-or-draft-6).

Also, around `JsonSchemaValidatorEndpoint` line 80 it would be probably better to catch `SchemaException` and handle malformed schemas.

**Comment by ullgren** [comment]
Thanks for you suggestions sounds very sound and I will implement them as suggested.

**Comment by davsclaus** [comment]
Great work. btw a new component only goes into the master branch.

**Comment by davsclaus** [comment]
Is there more work to be done on this PR ?

**Comment by davsclaus** [comment]
Can you try to see if you can make this component extend `ResourceEndpoint` which is an endpoint that is specialized for template resources, see for example camel-velocity for an example. Then its more consistent with the others, and allow to load the resources via different ways.

**Comment by ullgren** [comment]
OK will change to use `ResourceEndpoint`.

Also the new component is not added into `platforms/karaf/features/src/main/resources/features.xml` yet. I'm not that experienced with Karaf but can make a stab on trying to get that working.

**Comment by davsclaus** [comment]
About karaf that is okay, we can do that later

**Comment by davsclaus** [comment]
Just a heads up that we cut the new Camel release in the weekend

**Comment by ullgren** [comment]
Updated to use ResourceEndpoint and cleaned up the code.

**Comment by onders86** [comment]
@ullgren i think rebase is needed..

**Comment by ullgren** [comment]
Did a rebase yesterday and according to github there are no conflicts with the base branch (apache/camel master). But I will do a new rebase later today.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request merged**
