### PR TITLE
CAMEL-20060 - Add Azure SAS support for azure blob storage

### PR DESCRIPTION
**Pull request by oscerd**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by essobedo** [comment]
/component-test foo" && ls / && echo "

**Comment by essobedo** [comment]
/component-test azure" true build.log && ls / && echo "

**Comment by klease** [comment]
BTW, I notice that the generated classes in camel-endpointdsl treat sasToken as a path parameter and not a normal uri parameter.

**Comment by oscerd** [comment]
but it is uriParam..

**Comment by oscerd** [comment]
I'll take a look on Monday, because it's really weird.

**Comment by klease** [comment]
Agreed. But currently committed generated files declare it as "Path parameter: sasToken"

**Pull request merged**
