### PR TITLE
Camel 10307: Upgrade docker java version

### PR DESCRIPTION
**Pull request by Fabryprog**
https://issues.apache.org/jira/browse/CAMEL-10307

### CODE REVIEW

**Comment by Fabryprog** [comment]
@oscerd wait a few minutes that maybe I found a little problem! :-(

**Comment by oscerd** [comment]
Actually tests and build are ok. @Fabryprog, ok, I'll wait.

**Comment by Fabryprog** [comment]
@oscerd i had test into my docker swarm cluster! It is ok!

**Comment by oscerd** [comment]
@Fabryprog Good, thanks!

**Comment by oscerd** [comment]
Thanks! The PR has been merged. Can you close this?

**Comment by Fabryprog** [comment]
Mythical! It 'a pleasure to work with you!

**Pull request closed without merging**
