### PR TITLE
CAMEL-11696: Add an advanced properties to the camel-thrift component

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
To configure ssl stuffs we usually rely on [SSLContextParameters](https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/util/jsse/SSLContextParameters.java), do you think camel-thrift can leverage it so we have a common way to configure ssl across components ?

**Comment by dmvolod** [comment]
Good point, @lburgazzoli , will try to use it with relation to libthrift API. Thank you.

**Comment by dmvolod** [comment]
@lburgazzoli, I've changed code according your recommendation. Please review.

**Comment by lburgazzoli** [comment]
@dmvolod lgtm, I'm going to merge it

**Comment by lburgazzoli** [comment]
PR has been merged, do you mind closing it ?

**Pull request closed without merging**
