### PR TITLE
CAMEL-10350: Add Bonita Component

### PR DESCRIPTION
**Pull request by lio-p**
Add a new component to communicate with Bonita. 
The only operation available for now is startCase which allows to start a new case in Bonita Engine.

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks, can you fix the code formatting by running

   mvn compile -Psourcecheck

In the bonita directory and fix the errors reported.

Also will you work on more functionality in this component in the near future?

**Comment by lio-p** [comment]
Done for checkstyle. 

I'd like to work on adding more functionalities but that won't happen before early next year.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by lio-p** [comment]
Thanks!

**Pull request closed without merging**
