### PR TITLE
correct examples/README due to change from .md to .adoc in #3235

### PR DESCRIPTION
**Pull request by froque**

### CODE REVIEW

**Comment by davsclaus** [comment]
Yeah its in the tooling that generates that table
https://github.com/apache/camel/blob/master/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/ExampleModel.java#L25

**Comment by davsclaus** [comment]
Also it would be nice to align the names as some are readme.md, readme.txt, readme.adoc and in different case - some all upper etc.

**Comment by oscerd** [comment]
> Yeah its in the tooling that generates that table
> https://github.com/apache/camel/blob/master/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/ExampleModel.java#L25

Btw here https://github.com/apache/camel/blob/master/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java#L131 the readmeFileName should be overriden

Not sure why the name is not picked up.

**Comment by oscerd** [comment]
If you run a build from examples, the readme file is correctly updated. It's weird.

**Comment by oscerd** [comment]
Merged, we'll rework on this later. Thanks @froque

**Pull request closed without merging**
