### PR TITLE
CAMEL-9614: use https protocol for schema location of osgi blueprint xsd

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks @oscerd do you wanna merge this

**Comment by oscerd** [comment]
I'm merging @davsclaus @apupier

**Comment by oscerd** [comment]
Many thanks @apupier, the PR has been merged. Can you close this?

Andrea

**Comment by apupier** [comment]
thanks for the quick review and merge

**Pull request closed without merging**
