### PR TITLE
Fixup Workaround INFRA-24713 in the deploy script rather than for all possible builds

### PR DESCRIPTION
**Pull request by ppalaga**
Is this the right way to do it @orpiske?

### CODE REVIEW

**Comment by ppalaga** [comment]
> Is this the right way to do it @orpiske?

Let's try.

**Comment by orpiske** [comment]
> > Is this the right way to do it @orpiske?
> 
> Let's try.

Sorry for the late reply ... LGTM. Let's try.

**Comment by orpiske** [comment]
@ppalaga no luck:

```
+ ./mvnw -U -B -e -fae -V -Dnoassembly -Dmaven.compiler.fork=true -Pdeploy,apache-snapshots -Dmaven.test.skip.exec=true clean deploy
Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)
Maven home: /home/jenkins/.m2/wrapper/dists/apache-maven-3.9.2-bin/3238cb54/apache-maven-3.9.2
Java version: 17.0.7, vendor: Eclipse Adoptium, runtime: /usr/local/asfpackages/java/adoptium-jdk-17.0.7+7
Default locale: en_US, platform encoding: ISO-8859-1
OS name: "linux", version: "4.15.0-212-generic", arch: "amd64", family: "unix"
```

I am under the impression that we need to also save the updated text to the file.

**Comment by orpiske** [comment]
I'm trying 2 things. Let's see how it goes.

**Comment by orpiske** [comment]
@ppalaga trying this: https://github.com/apache/camel/commit/9f1f3a7604a589e72df8690e523f268ad262fa83. It seems to have worked when replaying on Jenkins. 🤞

**Comment by orpiske** [comment]
The in-place replacement works and the deployment is using 3.8.8. Now it's a matter of fixing the issues preventing the deployment: 
- https://ci-builds.apache.org/job/Camel/job/Camel%20Daily%20Snapshot%20Deploy/job/main/368/console 


And also the one preventing the build:
- https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/951/console

**Comment by orpiske** [comment]
Actually, let me move the discussion to the original thread of the PR. As more people are subscribed there.

**Pull request merged**
