### PR TITLE
[CAMEL-15691] ensure johnzon format doc does not inherit inaccurate jackson doc

### PR DESCRIPTION
**Pull request by rmannibucau**
- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
This needs to be updated on the javadoc of the getter/setter for mapper, then rebuild and you'll get adoc and catalog updated. Thanks for the PR

**Comment by rmannibucau** [comment]
@oscerd hmm, not sure i'm following, the setter is in JsonDataFormat (grabbed by the plugin cause johnzon is a json dataformat) - and you likely don't want I write something specific about Johnzon I guess even if it had been done historically for jackson ;); The opposite is true for JohnzonDataFormat where I don't want to add a setObjectMapper(String) to do the lookup myself to ensure I inherit from org.apache.camel.reifier.dataformat.DataFormatReifier#configureDataFormat to do it in an unified way. What do I miss?

**Comment by oscerd** [comment]
What I meant was just that the mapper description is autogenerated starting from
https://github.com/apache/camel/blob/master/core/camel-core-engine/src/main/java/org/apache/camel/model/dataformat/JsonDataFormat.java#L101

So if you wanted to have effective change in the documentation, you'll need to modify the javadoc accordingly. Otherwise at the next build the documentation would have been overriden. But I saw you workarounded this through the packageDataformatMojo, which should work anyway. So that's fine.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Yeah data formats are special and then those json data formats even more as they inherit a bit from each other.

**Pull request merged**
