### PR TITLE
CAMEL-19997: initial implementation of a SMB component

### PR DESCRIPTION
**Pull request by essobedo**
Fixes https://issues.apache.org/jira/browse/CAMEL-19997 for 3.22

## Motivation

Provide an SMB component for Camel 3

## Modifications:

* backport all changes made in the main branch
* change the first version to 3.22

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
Thanks for back-porting. It LGTM.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
You also need to add SB starter for this in 3.x branch

**Comment by essobedo** [comment]
The checkstyle issue is due to `Could not find artifact org.apache.camel:camel-smb:jar:3.22.0-SNAPSHOT`, I guess I need to merge it first then publish snapshots, do you agree?

**Comment by davsclaus** [comment]
No problem go ahead to merge

**Pull request merged**
