### PR TITLE
setting span kind as producer/consumer depending on the type of component in the route. If the span kind is set to producer then it changes the tracing header being set to b3 single format

### PR DESCRIPTION
**Pull request by samratdhillon**
Fixes https://issues.apache.org/jira/browse/CAMEL-15316

### CODE REVIEW

**Comment by oscerd** [comment]
If this is a wrong behaviour we should backport to 3.4.x too

**Comment by samratdhillon** [comment]
@oscerd Current behaviour in 3.4 is not correct. Not sure what is the process to backport. Is it as simple as cherry-picking this change into 3.4.x branch and opening another PR?

**Comment by oscerd** [comment]
Yes, it is.

**Comment by oscerd** [comment]
Thanks, merged

**Pull request closed without merging**
