### PR TITLE
CAMEL-16607: Allow to use #type and #class for local beans

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by lburgazzoli** [comment]
@davsclaus https://github.com/apache/camel/pull/5559/files#diff-8d4f32940be9a942bf113511beb43560dcea834c768adae2f47e1f4c5def1248R93 this test is failing because of "org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: {{myProcessor}} of type: org.apache.camel.Processor" do you see any missing bits on the YAML integration ?

**Comment by davsclaus** [comment]
Okay I have debugged and can see the problem. The script binds the created bean as java.lang.Object type and we do a lookup expecting for Processor type.

**Comment by davsclaus** [comment]
Have a fix on the way

**Comment by davsclaus** [comment]
Not sure how to collaborate more easier on a PR, so I ended up with a new PR with a fix for this
https://github.com/apache/camel/pull/5560

**Pull request closed without merging**
