### PR TITLE
CAMEL-16726: openapi generator: generate YAML DSL

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Not sure if the generated definition can be parsed by the YAML DSL as the auto generated parser support something like:

```yaml
 - rest:
     verb:
       - method: get
         uri: "/foo"
         type: ${MyFooBar.name}
         out-type: ${MyBean.name}
         to: "direct:bar"
```

So I don't think it is able to parse:

```
rest:      
      put:
        consumes: "application/json,text/xml"
        produces: "application/json,text/xml"
        uri: "/pet"
        param:      
          name: "body"      
          required: "true"      
          type: "body"
        to: ...
```

Is the YAML parser wrong ?

**Comment by lburgazzoli** [comment]
ok I got something working to support this but there is something that does not look good to me as example:

```yaml
  delete:
  - id: "deletePet"
    uri: "/pet/{petId}"
    param:
      - dataType: "string"
        name: "api_key"
        required: "false"
        type: "header"
      - dataType: "integer"
        description: "Pet id to delete"
        name: "petId"
        required: "true"
        type: "path"

  - id: "deleteOrder"
    uri: "/store/order/{orderId}"
    param:
      dataType: "integer"
      description: "ID of the order that needs to be deleted"
      name: "orderId"
      required: "true"
      type: "path"
```

`deletePet` has `param` defined as array
`deleteOrder` has `param` defined as object

I think it should be consistent and it should be an array otherwise it would be a little bit misleading and complex to parse and to validate it

@davsclaus what do you think ?

**Comment by davsclaus** [comment]
Yes so the object param vs array param, is because the XML -> Jackson Node mapper that parses that into a single object vs an array list

**Comment by davsclaus** [comment]
@lburgazzoli okay have. fix for the param as array problem.

Need to work on the root tag when you have
restConfiguration
rest

You talked about this should be an array?

**Comment by lburgazzoli** [comment]
> Need to work on the root tag when you have
> restConfiguration
> rest
> 
> You talked about this should be an array?

yes, like

```yaml
- res-configuration:
    component: ...
- rest:
    ...
```

**Comment by davsclaus** [comment]
@lburgazzoli okay so its an array now if both rest-configuration and rest exists.
For only rest, does it make sense to have it as an array or keep it as now as map type

```
rest:
   ...
```

vs

```
- rest:
   ...
```

**Comment by lburgazzoli** [comment]
an array would be better as it would match the expectations of the loader, but I can support also having a single root element if needed

**Comment by davsclaus** [comment]
Okay so its fixed now
- always array in root
- required is a boolean value
- param is always an array

**Pull request merged**
