### PR TITLE
Upgrade AWS SDK v2 to version 2.21.19

### PR DESCRIPTION
**Pull request by oscerd**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by oscerd** [comment]
Weird it's broken... Maybe it's related to the fix of @simon-ras in the other PR I merged this morning.

**Comment by oscerd** [comment]
More work needed.

**Comment by simon-ras** [comment]
> Weird it's broken... Maybe it's related to the fix of @simon-ras in the other PR I merged this morning.

More likely due to https://github.com/apache/camel/pull/11940. I re-ran tests on HEAD of main on camel-aws2-sqs, and they pass, but it fails on this branch where the only change is the sdk version.

**Comment by simon-ras** [comment]
It is broken when upgrading to 2.21.18 already. My guess is that this https://github.com/aws/aws-sdk-java-v2/commit/35807ed4d6abf6c77b7991f2a2b5862ef153d007 broke the integration with localstack?

**Review by davsclaus — APPROVED** [review]

**Comment by oscerd** [comment]
It could be @simon-ras, let's stick with 2.21.17 for the moment.

**Comment by oscerd** [comment]
Thanks for investigating. I'll check on localstack repo and we could also open a bug. For the moment we won't upgrade the SDK

**Pull request closed without merging**
