### PR TITLE
Introduce XmppDirectProducer

### PR DESCRIPTION
**Pull request by allancth**
@oscerd You are right. The factory is totally unnecessary.

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks @allancth :-)

I will review as soon as possible :-)

**Comment by allancth** [comment]
No worries, thanks.

On a side note, Smack latest version is now 4.1.8 if not mistaken, which they do have the packet extension class required for FCM connectivity. Would it be a good idea to update Smack's library?

**Comment by oscerd** [comment]
Yes, it's a good idea but you have to take care of the karaf features that are using smack:

https://github.com/apache/camel/blob/master/platforms/karaf/features/src/main/resources/features.xml

and check they install correctly

**Comment by allancth** [comment]
Noted. I'll have a look and see what needs or can be done.

**Comment by oscerd** [comment]
Subscribe yourself to JIRA to open an issue for this. Then open another PR for the upgrade in case :-) Thanks

**Comment by allancth** [comment]
Noted. JIRA created: CAMEL-10423 - Integration with FCM

**Comment by oscerd** [comment]
The commit breaks tests:

```shell
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.camel.component.xmpp.GoogleTalkEndpointTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.066 sec - in org.apache.camel.component.xmpp.GoogleTalkEndpointTest
Running org.apache.camel.component.xmpp.GoogleTalkTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.051 sec - in org.apache.camel.component.xmpp.GoogleTalkTest
Running org.apache.camel.component.xmpp.UriConfigurationTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.554 sec - in org.apache.camel.component.xmpp.UriConfigurationTest
Running org.apache.camel.component.xmpp.XmppDeferredConnectionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 14.265 sec - in org.apache.camel.component.xmpp.XmppDeferredConnectionTest
Running org.apache.camel.component.xmpp.XmppMultiUserChatTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.011 sec - in org.apache.camel.component.xmpp.XmppMultiUserChatTest
Running org.apache.camel.component.xmpp.XmppProducerConcurrentTest
Tests run: 6, Failures: 6, Errors: 0, Skipped: 0, Time elapsed: 62.781 sec <<< FAILURE! - in org.apache.camel.component.xmpp.XmppProducerConcurrentTest
testNoConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)  Time elapsed: 11.534 sec  <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.doSendMessages(XmppProducerConcurrentTest.java:58)
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testNoConcurrentProducers(XmppProducerConcurrentTest.java:34)

testConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)  Time elapsed: 10.021 sec  <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <10> but was: <0>
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.doSendMessages(XmppProducerConcurrentTest.java:58)
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testConcurrentProducers(XmppProducerConcurrentTest.java:39)

testConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)  Time elapsed: 10.019 sec  <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <10> but was: <0>
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.doSendMessages(XmppProducerConcurrentTest.java:58)
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testConcurrentProducers(XmppProducerConcurrentTest.java:39)

testNoConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)  Time elapsed: 10.017 sec  <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.doSendMessages(XmppProducerConcurrentTest.java:58)
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testNoConcurrentProducers(XmppProducerConcurrentTest.java:34)

testConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)  Time elapsed: 10.015 sec  <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <10> but was: <0>
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.doSendMessages(XmppProducerConcurrentTest.java:58)
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testConcurrentProducers(XmppProducerConcurrentTest.java:39)

testNoConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)  Time elapsed: 10.016 sec  <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <1> but was: <0>
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.doSendMessages(XmppProducerConcurrentTest.java:58)
	at org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testNoConcurrentProducers(XmppProducerConcurrentTest.java:34)

Running org.apache.camel.component.xmpp.XmppRobustConnectionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 36.708 sec - in org.apache.camel.component.xmpp.XmppRobustConnectionTest
Running org.apache.camel.component.xmpp.XmppRouteChatTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.435 sec - in org.apache.camel.component.xmpp.XmppRouteChatTest
Running org.apache.camel.component.xmpp.XmppRouteMultipleProducersSingleConsumerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.545 sec - in org.apache.camel.component.xmpp.XmppRouteMultipleProducersSingleConsumerTest
Running org.apache.camel.component.xmpp.XmppRouteTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.009 sec - in org.apache.camel.component.xmpp.XmppRouteTest

Results :

Failed tests: 
org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)
  Run 1: XmppProducerConcurrentTest.testConcurrentProducers:39->doSendMessages:58->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Received message count. Expected: <10> but was: <0>
  Run 2: XmppProducerConcurrentTest.testConcurrentProducers:39->doSendMessages:58->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Received message count. Expected: <10> but was: <0>
  Run 3: XmppProducerConcurrentTest.testConcurrentProducers:39->doSendMessages:58->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Received message count. Expected: <10> but was: <0>

org.apache.camel.component.xmpp.XmppProducerConcurrentTest.testNoConcurrentProducers(org.apache.camel.component.xmpp.XmppProducerConcurrentTest)
  Run 1: XmppProducerConcurrentTest.testNoConcurrentProducers:34->doSendMessages:58->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Received message count. Expected: <1> but was: <0>
  Run 2: XmppProducerConcurrentTest.testNoConcurrentProducers:34->doSendMessages:58->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Received message count. Expected: <1> but was: <0>
  Run 3: XmppProducerConcurrentTest.testNoConcurrentProducers:34->doSendMessages:58->CamelTestSupport.assertMockEndpointsSatisfied:875 mock://result Received message count. Expected: <1> but was: <0>


Tests run: 16, Failures: 2, Errors: 0, Skipped: 6
```

Can you take a look? Thanks.

**Comment by allancth** [comment]
Noted.

**Comment by allancth** [comment]
Will do another PR when ready.

**Pull request closed without merging**
