### PR TITLE
CAMEL-10347: camel-scr todos and polish

### PR DESCRIPTION
**Pull request by yuruki**
https://issues.apache.org/jira/browse/CAMEL-10347

### CODE REVIEW

**Comment by davsclaus** [comment]
You are changing to many things and without really explaining why you do all this, and also do some stuff that looks like it breaks old behavior.

**Comment by yuruki** [comment]
I agree it looks really bad on diff because I moved things around to make the code more understandable (for me)...

Functionality-wise I just addressed some long-standing todos (dropping hardcoded defaults and direct member access) plus returned access to local registry (SimpleRegistry) which was IMO unnecessarily removed after 2.15.4 by double-wrapping an OsgiServiceRegistry.

I'll move things back to their original places to clean up the diff.

**Comment by yuruki** [comment]
There, it looks much clearer now.

API changes in this PR are:
- context member variable is no longer accessible from subclasses. Use getContext() which has been available for a long time now.
- registry member variable is no longer accessible from subclasses. Use getRegistry() from CamelContext, or the new helper from AbstractCamelRunner if you want to throw exceptions.
- getRouteBuilders() may now throw exceptions.
- Some methods are marked as final.

The above should be alright for a new point release 2.18.0.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by yuruki** [comment]
Thank you.

**Pull request closed without merging**
