### PR TITLE
CAMEL-21067: marked camel-univocity as deprecated

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by apupier** [comment]
Shouldn't it be added to the migration guide?

**Review by davsclaus — APPROVED** [review]

**Comment by apupier** [comment]
Also shouldn't we mark all public classes as Deprecated inside this module?

**Comment by davsclaus** [comment]
No its fine just to mark the component as deprecated as Otavio do. No need to do more.

**Comment by davsclaus** [comment]
Ah okay its a data format, so its a good idea to add `@Deprecated` to its model definition classes, so its also marked as deprecated in the DSL and in catalog and so on. So there is a bit more work when its a dataformat / language vs a regular component.

**Comment by orpiske** [comment]
Let's mark this one as a draft. Later I'll take a look at the public classes we should deprecate.

**Comment by orpiske** [comment]
Changes done. Let's merge.

**Pull request merged**
