### PR TITLE
CAMEL-21286 - Add a cache for JAXB ObjectFactory lookup

### PR DESCRIPTION
**Pull request by ammachado**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.
- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
It would make sense to make the dimension selectable

**Comment by ammachado** [comment]
@oscerd and how you'd configure that? There are other options on `FallbackConverter`, but they're implemented using Camel's global context options. Should I use a similar pattern?

**Comment by oscerd** [comment]
I think there is no value in adding an arbitrary dimension here. It could work for your case but it could be useless for others. So we need to find a good way @davsclaus

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
This feature is only relevant if you turn on a special option so it will only affect a small set of users. And the cache will speedup in those cases. Setting a dimension is likely only needed in rare cases if you have a lot of different JAXB classes that you process by Camel, causing the cache to run out of space.

**Pull request merged**
