### PR TITLE
changed multiplication by a pow of two to bit shift or to the result of multiplication

### PR DESCRIPTION
**Pull request by dk2k**
changed multiplication by a pow of two to bit shift or to the result of multiplication

### CODE REVIEW

**Comment by dk2k** [comment]
@orpiske Hi, would you change your mind if I added into the code comments (sometimes I did already) as for what is multiplicated?

**Comment by orpiske** [comment]
> @orpiske Hi, would you change your mind if I added into the code comments (sometimes I did already) as for what is multiplicated?

Yes. I think it would help to make it easier to understand.

Thanks

**Comment by davsclaus** [comment]
Is the JDK compiler not optimising such things automatically ? Its a lot harder to read and understand as bit shifting operation only makes sense when you work with bit values / computations.

**Comment by orpiske** [comment]
Yeah, the JDK is very likely to optimize this automatically.

**Comment by dk2k** [comment]
@orpiske @davsclaus I found an article dated to 2020 https://programmer.help/blogs/the-optimization-and-application-of-bit-operation-in-java.html Left shift gives some performance gain.
My idea was to get as more performance as possible since Camel is a server software. Bit shifts are basis of computer science. If one doesn't know them, the sources of Camel can't help him/her.

**Comment by orpiske** [comment]
> @orpiske @davsclaus I found an article dated to 2020 https://programmer.help/blogs/the-optimization-and-application-of-bit-operation-in-java.html Left shift gives some performance gain. My idea was to get as more performance as possible since Camel is a server software. Bit shifts are basis of computer science. If one doesn't know them, the sources of Camel can't help him/her.

While, indeed, even ourselves do micro-optimizations from time to time, we usually try to favor the ones that improve readability (i.e.: like the ones yourself did replacing the `""` checks for `isEmpty()`). These micro-optimizations hardly have any meaningful result on how Camel performs: bottlenecks are more often than not elsewhere in the code. 

Ultimately, the reduced readability ends up affecting the maintainers more - as we'll take longer to understand the code in 1, 2 ... 3 months from now. When you have to deal with such a large code base, balancing things like these become just as important.

**Comment by davsclaus** [comment]
okay lets keep as-is to make maintaining code easier

**Pull request closed without merging**
