### PR TITLE
CAMEL-11919 Adding new feature

### PR DESCRIPTION
**Pull request by DG007**
Salesforce REST API request headers not included in update,upsert,create
and query operations

### CODE REVIEW

**Comment by oscerd** [comment]
Please, can you open the PR against master branch? this is a new feature.

**Comment by oscerd** [comment]
I guess this PR is wrong. Start from a fresh master branch

**Comment by DG007** [comment]
okay, i'll try again.

**Comment by oscerd** [comment]
Thank you :-)

**Pull request closed without merging**
