### PR TITLE
CAMEL-18447 Camel-pubsub: AsyncTaskException: Asynchronous task failes

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes: https://issues.apache.org/jira/browse/CAMEL-18447

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
I'm switching to the draft as I can see some warnings in IT tests (using mocked backend)

**Review by rhuan080 — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
@JiriOndrusek can you please backport to 3.18.x too?

**Comment by JiriOndrusek** [comment]
I'll do that

**Comment by JiriOndrusek** [comment]
Backport PR: https://github.com/apache/camel/pull/8667

**Pull request merged**
