### PR TITLE
[CAMEL-16172] Update to OpenTelemetry v0.15.0

### PR DESCRIPTION
**Pull request by theggelund**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

---
This change is [Reviewable](https://reviewable.io/reviews/apache/camel/5063)

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Looks good to me, can you please double check the karaf feature too and the opentelemetry spring boot starter test?

https://github.com/apache/camel-karaf
https://github.com/apache/camel-spring-boot

If you don't have time I can have a look.

**Comment by theggelund** [comment]
I do not have the time today, I could probably do it tomorrow @oscerd

**Comment by oscerd** [comment]
Since it is a major upgrade it can only be on a new release. We are cutting 3.8 already. This will be on 3.9.0. I'll have a look at karaf and sb, no worries. Thanks

**Comment by oscerd** [comment]
Checked on SB and Karaf, aligned there and merged this PR. Thanks.

**Pull request closed without merging**
