### PR TITLE
failIfNoConsumers default value

### PR DESCRIPTION
**Pull request by mikadev**
The failIfNoConsumers default value is true and not false

### CODE REVIEW

**Comment by davsclaus** [comment]
You need to change it in the java source code at
https://github.com/apache/camel/blob/4eb611282b53c64f91a3fa22c682c2f5d011ef28/components/camel-direct/src/main/java/org/apache/camel/component/direct/DirectEndpoint.java#L51

**Comment by mikadev** [comment]
@davsclaus  What is weird is i check the code before and i see that default value is the right one so ?

**Comment by oscerd** [comment]
> @davsclaus What is weird is i check the code before and i see that default value is the right one so ?
> 
> > @UriParam(label = "producer")
> > private boolean failIfNoConsumers = true;

You need to add defaultValue="true" to the annotation of UriParam

**Comment by mikadev** [comment]
Not a valid PR

**Pull request closed without merging**
