### PR TITLE
CAMEL-12742: Upgrade maven wrapper to 0.4.2

### PR DESCRIPTION
**Pull request by vrlgohel**
Upgraded wrapper to 0.4.2 with, `mvn io.takari:maven:wrapper -Dmaven=3.5.3`

### CODE REVIEW

**Comment by vrlgohel** [comment]
@dmvolod, i didn't change any permissions on the file. Not sure what is the default file permission. Can you let me know ? Is it 604 ?

**Comment by dmvolod** [comment]
@vrlgohel if look at the PR file change tab, you can get the following info
BIN .mvn/wrapper/maven-wrapper.jar 100644 → 100755
If you didn't change any file permissions, lets merge PR and we will sea this in the tree.

**Comment by vrlgohel** [comment]
@dmvolod, hmm, if i checkout master again and check the octal code, 

[vgohel@dhcp193-119 wrapper]$ stat -c "%a %n" *
664 maven-wrapper.jar
664 maven-wrapper.properties

i see 644. Do you want me to change to 644 ? or we are fine now ?

**Comment by dmvolod** [comment]
I don't know why it happens after PR checkout, but permissions have changes 
[dvolodin@dvolodin camel]$ git checkout pr-2492 
Switched to branch 'pr-2492'
[dvolodin@dvolodin camel]$ 
[dvolodin@dvolodin wrapper]$ ls -la
total 52
drwxrwxr-x. 1 dvolodin dvolodin    82 Aug 23 17:13 .
drwxrwxr-x. 1 dvolodin dvolodin    34 Aug  3 08:45 ..
-rwxrwxr-x. 1 dvolodin dvolodin 48337 Aug 23 17:13 maven-wrapper.jar
-rw-rw-r--. 1 dvolodin dvolodin   110 Aug  3 08:45 maven-wrapper.properties

Ok, lets merge it and fix manually.

**Pull request merged**
