### PR TITLE
Camel tests consolidating

### PR DESCRIPTION
**Pull request by kulagaIA**
# Description
Tests from tests/camel-itest-jms2 were moved to components/camel-jms. Some of them were deleted as duplicates of existing components/camel-jms tests.
Module tests/camel-itest-jms2 was then removed as no relevant tests remained there.

# Tracking
https://issues.apache.org/jira/browse/CAMEL-20113

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by orpiske** [comment]
Thanks for your contribution! I will take a closer look as on Tuesday, after I come back.

**Review by orpiske — CHANGES_REQUESTED** [review]
Just marking as request changes because I would like to take a closer look, but I am currently traveling.

**Comment by orpiske** [comment]
I am back from PTO and I'll be looking at this one today.

**Review by orpiske — APPROVED** [review]
This looks great. Thanks @kulagaIA !

**Pull request merged**
