### PR TITLE
Revert "Regen for commit 030a83b75c951c7eb52e178ccbdb6877936f61cb (#10723)"

### PR DESCRIPTION
**Pull request by orpiske**
This reverts commit 84330f9dbeaf0d1ebf9d6125f135e45e772f3e7d.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I don't know if it makes sense to disable the regen action

**Comment by orpiske** [comment]
> I don't know if it makes sense to disable the regen action

I'm wondering if we should reset its branch again.

**Comment by oscerd** [comment]
Let's try

**Comment by davsclaus** [comment]
Yeah the regen bot seems out of touch

**Comment by oscerd** [comment]
Rebased regen_bot branch

**Pull request merged**
