### PR TITLE
[Website] Use @djencks/asciidoctor-jsonpath to generate component doc content

### PR DESCRIPTION
**Pull request by djencks**
See https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16854

As a preliminary step this assumes an upgrade to Antora 3 alpha.9 to replace copying with symlinks.

Most of the UpdateReadmeMojo functionality is now done by asciidoctor-jsonpath, with "templates" as included partials.

Likely this should be updated just before merging to rebase on main and regenerate the generated changes, which are in the last commit.

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]
LGTM. Lets wait for @zregvart

**Comment by zregvart** [comment]
Thanks for this @djencks!

I'll quickly rebase this and do a review locally. I'm guessing there will it'll take a bit of time to go through this.

**Comment by djencks** [comment]
I found that somehow one of the component partials wasn’t getting included and I found another docTitle/doctitle problem and just force-pushed changes.  I hope this doesn’t make reviewing too hard.

David Jencks

**Comment by oscerd** [comment]
@zregvart @djencks I think this has been completed through other PRs, can we close this PR?

**Comment by djencks** [comment]
No, so far Zoran has only merged the preliminary work: the actual use of the extension to generate content is not yet merged.

Zoran, is there anything I can do to help?

Thanks
David Jencks

**Comment by oscerd** [comment]
Ok, thanks for letting me know.

**Comment by zregvart** [comment]
I would still like to split the changes in this PR into independent change sets. I see two changes here:
 - use of partials with `jsonpathTable2` macro
 - attribute rename (`docTitle` -> `doctitle`)

There is also a change image paths that we already merged, and this is conflicting right now.

I'm working on incorporation of the first change, to use the `jsonpathTable2` macro and I'm nearly there. I wanted to double check that every .adoc file has a corresponding .json file with the Camel metadata. I'm a bit spotty with time right now, but this is something I would like to get done today/tomorrow.

**Comment by djencks** [comment]
Your PR looks good to me, I made a suggestion about the bindy problem.

I think that the jasonpath extension will produce a warning if there’s no json file, it certainly should.  I’ve been revamping the extension locally to among other things improve logging, so it’s possible this is only happening with my uncommitted changes.

I see that there are a lot of other attribute names that aren’t lower-case, so after this current PR is merged I’d like to make a new PR that lower-cases all the AsciiDoc attribute names.

David Jencks

**Comment by zregvart** [comment]
> I see that there are a lot of other attribute names that aren’t lower-case, so after this current PR is merged I’d like to make a new PR that lower-cases all the AsciiDoc attribute names.

Yeah, I did not want to include that to keep the change specific to jsonpathTable macro, but I do welcome that change. Thanks!

**Review by mamadaliev — APPROVED** [review]

**Comment by davsclaus** [comment]
I assume we have done this work and this PR can be closed?

**Comment by djencks** [comment]
All the changes proposed here have been applied though other PRs. Thanks to Zoran for making it into comprehensible-sized chunks!

**Pull request closed without merging**
