### PR TITLE
fix for https://issues.apache.org/jira/browse/CAMEL-12119 [CAMEL-12119]

### PR DESCRIPTION
**Pull request by sijskes**

### CODE REVIEW

**Comment by davsclaus** [comment]
You need to fix code formatting, run

    mvn compile -P sourcecheck

in the camel-mail folder.

Also as commented on the JIRA ticket we cannot just do this as `X-xxx` is not a standard header. So if something like this is to be implemented then we need an option to turn this explicit on, so existing users are not affected.

**Comment by sijskes** [comment]
so what is the issue with the header exact? that it is undocumented, or that is leaks in the email?

**Comment by sijskes** [comment]
after reading your comment again, you are never going to accept this patch are you?

**Comment by onders86** [comment]
I guess the PR will be acceptable if you can modify as per requested..

**Comment by davsclaus** [comment]
Yes we need an option on the mail component / endpoint to explicit turn this on, so it behaves as-is today. Naming such an option can be a bit harder - 'recipientXHeaderOverride' or something

**Pull request closed without merging**
