### PR TITLE
CAMEL-17897: camel-exec - add exitValues parameter

### PR DESCRIPTION
**Pull request by sbalmer**
Add `exitValues` parameter to `camel-exec` component as documented in https://issues.apache.org/jira/browse/CAMEL-17897

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
cc @davsclaus

**Comment by oscerd** [comment]
There are some conflicts, can you please rebase?

**Comment by sbalmer** [comment]
Unresolved issues:

* I just used the name from the underlying library. But I'm not too happy with the `exitValues` name. Something like `expectedExitValues`, `acceptedExitValues` or just `failOnNonzeroExitValue` would be other possibilities.
* There is no functional test because I couldn't get `ExecScriptTest` to work on my installation. It complained about a missing JAVA_HOME which is set. I'm unclear on how to proceed. I hacked `ExecJava8IssueTest` to test whether it fails with `exitValues=1` locally, and that worked.

**Comment by sbalmer** [comment]
Improvements left out for now:

- Catching the ExecException and throwing an exception with better diagnostics. I'd prefer using it first as-is and then see what would be useful.
- Syntax for ranges: `exitValues=0-100`. Because the underlying API supports list, adding support for comma-separated lists was easy. But more parsing would complicate matters and I don't have a use case. My use will be `exitValues=0` in all cases.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
