### PR TITLE
Additional headers and properties support

### PR DESCRIPTION
**Pull request by rgannu**
CAMEL-15496 Support additional headers and properties

The additional headers will be added on top of the existing headers
from the message.

The properties added are only basic AMQP properties as defined in the
{@link com.rabbitmq.client.AMQP.BasicProperties.Builder}. When the
message contains already these properties then will be considered and
these additional properties will be ignored.

Made RabbitMQConstants to enum and added the documentation from docs.
ToDo: The documentation needs to be generated from the source code.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
These are new options. This PR needs to be open against master and only there. 3.4.x is LTS

**Comment by oscerd** [comment]
Ckc Will be updated whenever the release is out (3.6.0 I mean)

**Comment by davsclaus** [comment]
Yes we cannot accept this on 3.4 branch as its for maintenance only (bug fixes and security stuff etc) not really for new features.

Also that SimpleBeanDataHolder etc is not something we want. It should be a plain Map with just string, object or string, string types.

**Comment by oscerd** [comment]
I believe we could close this, since 3.4.x is not a target.

**Comment by rgannu** [comment]
Yes.. I will create a new PR against master. Thanks

**Pull request closed without merging**
