### PR TITLE
CAMEL-19879: camel-rest- Add option to set headerfilterStrategy

### PR DESCRIPTION
**Pull request by TUCJVXCB**
# Description

wish camel-rest can support custom headerfilterStrategy

# Target

- [X] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [X] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [X] I checked that each commit in the pull request has a meaningful subject line and body.

- [X] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
It is not good to use custom header filter strategy with rest as it requires to use functionality that are from the special one we have. So if you use custom then "stuff" does not work.

**Comment by davsclaus** [comment]
To make this tolerable, then you could add a note in the docs for camel-rest about using custom header filter strategy, that its recommended to extend the rest based and ensure to call its super methods.

**Comment by TUCJVXCB** [comment]
alright，i update docs now

**Comment by davsclaus** [comment]
You need to update in the src/main/docs folder - the json file doc is hardcoded via camel-core and cannot be changed

**Comment by davsclaus** [comment]
There is also special code in camel-vertx-http and camel-netty-http that needs adjustments

**Comment by TUCJVXCB** [comment]
Are you referring to documents or code？

**Comment by TUCJVXCB** [comment]
> There is also special code in camel-vertx-http and camel-netty-http that needs adjustments

Are you referring to documents or code？

**Comment by davsclaus** [comment]
> > There is also special code in camel-vertx-http and camel-netty-http that needs adjustments
> 
> Are you referring to documents or code？

I think code, can you look into these 2 components, they also set a rest based filter startegy by default I assume

**Comment by TUCJVXCB** [comment]
> > > There is also special code in camel-vertx-http and camel-netty-http that needs adjustments
> > 
> > 
> > Are you referring to documents or code？
> 
> I think code, can you look into these 2 components, they also set a rest based filter startegy by default I assume

Alright, I'll take a look.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
the PR says that there are missing files in the commit. If you build camel-catalog, and endpointdsl / componentdsl then there are changed files to be added in the PR.

**Comment by TUCJVXCB** [comment]
> the PR says that there are missing files in the commit. If you build camel-catalog, and endpointdsl / componentdsl then there are changed files to be added in the PR.

ok

**Comment by TUCJVXCB** [comment]
> the PR says that there are missing files in the commit. If you build camel-catalog, and endpointdsl / componentdsl then there are changed files to be added in the PR.

I'm sorry, I followed your instructions to build camel-catalog, and endpointdsl / componentdsl, but there no files are added, only some files are deleted.
image

**Comment by oscerd** [comment]
You need to fully build the project.

**Comment by TUCJVXCB** [comment]
> You need to fully build the project.

thx, i will try

**Comment by TUCJVXCB** [comment]
> You need to fully build the project.

image
May I ask what could be the reason for this?

**Comment by davsclaus** [comment]
You can build without testing

mvn clean install -D quickly

**Comment by TUCJVXCB** [comment]
> You can build without testing
> 
> mvn clean install -D quickly

thanks very much！🙏

**Comment by davsclaus** [comment]
> There are uncommitted changes

I wonder if you could do a rebuild of your PR and find the uncommitted files and add to the PR

    mvn clean install -Dquickly

**Comment by TUCJVXCB** [comment]
> > There are uncommitted changes
> 
> I wonder if you could do a rebuild of your PR and find the uncommitted files and add to the PR
> 
> ```
> mvn clean install -Dquickly
> ```

it seems that because I manually added a [note] in rest.adoc, I only added it in one place. Do I need to add notes in other documents as well?

**Comment by TUCJVXCB** [comment]
> > There are uncommitted changes
> 
> I wonder if you could do a rebuild of your PR and find the uncommitted files and add to the PR
> 
> ```
> mvn clean install -Dquickly
> ```

i rebuild just now, it just remove that [note]

**Pull request merged**
