### PR TITLE
CAMEL-9586 - Create new Etcd component

### PR DESCRIPTION
**Pull request by lburgazzoli**
This PR is aimed to get some feedback on a new Etcd component. 

At the moment the component lacks a proper set of tests, documentation and some more functionalities I will add in the coming days.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Findings fixed

**Comment by davsclaus** [comment]
Thanks it has been merged, can you close this PR

**Comment by lburgazzoli** [comment]
I will. Doc should be done on confluence or as asciidoc ?

**Comment by davsclaus** [comment]
in the source code so we get in adoc generated. 

And then yeah a new page in wiki about  this new etcd component
http://camel.apache.org/components.html

You add to the list at
http://camel.apache.org/component-list

And just copy an existing component doc page in wiki and change

**Pull request closed without merging**
