### PR TITLE
CAMEL-16927 fixes spring creating multiple camel contexts resulting in deadlock

### PR DESCRIPTION
**Pull request by PiotrKlimczak**
Fixes spring creating multiple camel contexts, affecting DefaultReactiveExecutor/Worker resulting in deadlock

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Thanks, but this first need to be done on main branch, then we could eventually backport to other LTS branches.

**Comment by PiotrKlimczak** [comment]
@oscerd I am confused with what has happened for CAMEL-16170 where Spring Proxy support seems to be removed?
Right now in the main branch I can only see one test using proxy and it is in CDI component.
Has native support for Proxy been removed from 3.9+?

**Comment by davsclaus** [comment]
I am not keen on doing such a dramatic change in a stable version of Camel in a feature that is deprecated and removed (eg spring proxy).

Other users of Camel 3.7.x should rely on it being stable as-is.

**Comment by PiotrKlimczak** [comment]
I think there might be misunderstanding in all above. 
The problem is not with proxy itself but rather with the fact that camel spring is creating multiple CamelContext instances and then is getting confused with them. 
It only involves proxy because it is where the problem manifested itself for us. 
The same problem might possibly occur without using proxies. 
My problem with making the change to main branch was mostly with inability to reproduce the problem + there are so many changes that the problem might not be there anymore. 
Regardless of above, 3.7 is LTS so even if proxy specific, I would still expect fix as a user for it. 
Personally I don’t mind as we have it fixed internally this way and it works for us.

**Comment by davsclaus** [comment]
Made your change to the main branch for Camel 3.12 onwards, as the spring-xml xsd creates the SpringCamelContext where the application context can be set safely aftwards

**Comment by PiotrKlimczak** [comment]
Thanks Claus. Will change my pr this evening as requested.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
