### PR TITLE
WIP: DOCUMENTATION generator for the user manual

### PR DESCRIPTION
**Pull request by fpapon**
This is a WIP PR concerning a proposal about the generation of the user manual.

A pom.xml was added into the `docs` folder including :

- the css for the html generation of the documentation (`user-manual/en/apache.css`)
- the theme for the pdf generation of the documentation (`theme`)

The theme for the html and the pdf is based on the [ASF](https://apache.org) website.

The generation use the `asciidoctor-maven-plugin` for html and pdf.

To generate the html documentation, use the **html** maven profile :
```
$ cd docs
$ mvn -Phtml
```
The website is generated under `target/generated-html` and the main page is `index.html`

To generate the pdf documentation, use the **pdf** maven profile :
```
$ cd docs
$ mvn -Ppdf
```
The pdf is generated under the repository `target/generated-pdf` and the main document is `index.pdf`

### CODE REVIEW

**Comment by fpapon** [comment]
@jbonofre: can I have your feeback for a pre-review please ?

**Comment by oscerd** [comment]
Impressive, thanks a lot for this work!

**Comment by fpapon** [comment]
Thanks very much !
This is my first contribution to Camel and I will do my best to make more :)

**Comment by jbonofre** [comment]
That's really great, with consistency to what we have in Karaf and unomi. Great job !

**Comment by jbonofre** [comment]
@fpapon, just keep on contributing, you do a great job ! I would be more than happy to help and "mentor" you as I also plan to be back more active on camel.

**Comment by fpapon** [comment]
@jbonofre Thanks !!

**Comment by oscerd** [comment]
There is only on thing I noticed while navigating, from the components table we still have links to the .adoc files of the single components and the links are not working, but I believe this is something we'll have time to fix.

**Comment by fpapon** [comment]
@oscerd Yes there is a lot of adoc files and for the WIP I didn't check all ;)
I will start to check all of them one by one.

**Comment by zregvart** [comment]
I actually don't mind if we merge this to `master` seems like it would be easier for everyone to work there, I can always rebase `website` branch from there. I'm going to merge this to `website` and then cherry pick to `master`.

**Comment by fpapon** [comment]
@zregvart Thanks for merging

**Pull request merged**
