### PR TITLE
[3.18.x] CAMEL-21057: camel-rest-openapi - fallback to use specification host …

### PR DESCRIPTION
**Pull request by zhfeng**
…if there is the relative URL in the servers

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by oscerd** [comment]
We won't release 3.18 anymore..

**Comment by zhfeng** [comment]
OK, so what 3.x branch should I rebase?

**Comment by oscerd** [comment]
3.22.x

**Comment by zhfeng** [comment]
Thanks @oscerd and @davsclaus . There is a different way in main branch. I'm still investigating.

**Pull request closed without merging**
