### PR TITLE
CAMEL-19846: yaml and xml DSL - Add support for BeanLoader so they ca…

### PR DESCRIPTION
**Pull request by davsclaus**
…n define beans that can be used for advanced global configuration on camel context which the legacy spring/blueprint XML DSL can do.

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by igarashitm** [comment]
@davsclaus so what I learned from @grgrzybek is that this is already supported by:

1. Register beans before DefaultConfigurationConfigurer searches
https://github.com/apache/camel/blob/main/dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java#L83-L102

3. DefaultConfigurationConfigurer search in bean registry, if CamelContext related bean is found, use them 
https://github.com/apache/camel/blob/main/core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java#L894

It's already working for XML IO
 https://github.com/apache/camel-kamelets-examples/blob/main/jbang/app-routes-spring-beans/app.xml#L20-L22

So once YamlRoutesBuilderLoader#preParseRoute() supports loading beans into bean registry, this should work for YAML DSL as well.

@grgrzybek could you chime in if there's something to add?

**Comment by grgrzybek** [comment]
See my comment under https://issues.apache.org/jira/browse/CAMEL-19846 ;)
Camel changes very fast, so I'd have to catch up a bit again. But when I was preparing https://github.com/apache/camel-kamelets-examples/blob/main/jbang/app-routes-spring-beans/app.xml, it worked ;)

**Comment by davsclaus** [comment]
> @davsclaus so what I learned from @grgrzybek is that this is already supported by:
> 
> 1. Register beans before DefaultConfigurationConfigurer searches
>    https://github.com/apache/camel/blob/main/dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java#L83-L102
> 2. DefaultConfigurationConfigurer search in bean registry, if CamelContext related bean is found, use them
>    https://github.com/apache/camel/blob/main/core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java#L894
> 
> It's already working for XML IO https://github.com/apache/camel-kamelets-examples/blob/main/jbang/app-routes-spring-beans/app.xml#L20-L22
> 

This is only when using spring-beans (eg real spring dependency injection). If you just have 100% camel xml files (routes and beans) then spring is NOT used at all, and this PR would be needed to have beans working for that - just like in YAML DSL.

> So once YamlRoutesBuilderLoader#preParseRoute() supports loading beans into bean registry, this should work for YAML DSL as well.
> 
> @grgrzybek could you chime in if there's something to add?

**Comment by igarashitm** [comment]
I also looked at it with debugger on main branch and the preParseRoute() is still invoked before DefaultConfigurationConfigurer.afterConfigure(), so for me it looks @grgrzybek 's work is still valid.

**Comment by igarashitm** [comment]
It's not the spring injection, XmlRoutesBuilderLoader.preParseRoute() parses beans and register them.

**Comment by davsclaus** [comment]
Ah yes that is another possibility to move the "beans" parsing out of the regular phase, and make it part of preParse only with some special code in the route builder, ala we do for camel-k stuff.

Then the beans are eager and would be set during bootstrap

**Comment by davsclaus** [comment]
Yeah I have a better PR in the works, so will close this - I just need to copy over some of the unit tests as we should have them for the new PR

**Comment by davsclaus** [comment]
Replaced by https://github.com/apache/camel/pull/11476

**Pull request closed without merging**
