### PR TITLE
CAMEL-10503 - Camel-Git: Add RemoteAdd command

### PR DESCRIPTION
**Pull request by chenapan**
Finally add RemoteList command too as it goes together. Tried to update issue but JIRA were down.

### CODE REVIEW

**Comment by chenapan** [comment]
I was a bit confused with my commits as I worked on my master that wasn't merged yet, I created a branch per defect based on the official master. You may have a conflict in a Test class as used by both pull request, my appologies for that. I'll wait for your merge to go on.

**Comment by oscerd** [comment]
I merged this one:

https://github.com/apache/camel/pull/1291

Can you please rebase this? :-)

Thanks!

**Comment by chenapan** [comment]
Done.

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close this?

**Pull request closed without merging**
