### PR TITLE
Camel 2.19.x

### PR DESCRIPTION
**Pull request by DG007**
CAMEL-11668: CompositeApiClient class in the camel-salesforces component cannot close a null InputStream

### CODE REVIEW

**Comment by onders86** [comment]
This PR is probably based on 2.19.x branch. We use master branch and backport if needed. Could you please close and renew your PR?

**Comment by DG007** [comment]
I thought this is what I tried. The PR is for 2.19.x branch. I can't seem to open a PR on the master branch. Does this PR help to fix the issue?

**Comment by onders86** [comment]
You can open PR against 2.19.x. In that case, it may require forward porting. This is not what we usually do, we always first go to master branch for any fix, feature / other implementation and cherry-pick to other branches if it seems relevant to backport.

**Comment by DG007** [comment]
So do i just reopen my current PR? because this is opened on 2.19.x right? Or did I get that wrong?

**Comment by onders86** [comment]
this is opened against master branch and it is already probably based on 2.19.x. Nobody can easily review and approve your changes. That's why I am requesting you to reopen your PR against master branch after you also do your changes on your cloned master branch.

**Comment by DG007** [comment]
Thanks for the quick replies and help "onders86". This is me first contribution to the apache camel community. Thats why I have soo many questions.  I have created a fork of the master branch now and made my patch on the 2.19.x branch. Now I will create the PR on the master branch from my clone. I believe this is what is expected right?

**Comment by onders86** [comment]
not a problem. As far as i can, i will help you.
yes, that's right.

**Pull request closed without merging**
