### PR TITLE
Support for java 9 

### PR DESCRIPTION
**Pull request by johnpoth**
https://issues.apache.org/jira/browse/CAMEL-10141

This PR adds support for java 9 up to camel-core in the reactor build order. I've tested with the latest java 9 (Build 156).

I'll squash the commits once approved (left them for clarity).

Thanks!

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks looks good.

**Comment by davsclaus** [comment]
The commits don't need to be squashed as its really easier to understand when they are separated with different commit log message as you have done.

**Comment by davsclaus** [comment]
This causes Java 8 to fail building

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:21 min
[INFO] Finished at: 2017-02-14T09:20:41+01:00
[INFO] Final Memory: 1149M/2089M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.0.2:jar (bundle-jar) on project camel-salesforce-maven-plugin: You have to use a classifier to attach supplemental artifacts to the project instead of replacing them. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

In the module: 
```
 mvn clean install -P fastinstall -rf :camel-salesforce-maven-plugin
```

I think its due that jar plugin upgrade from 2.x to 3.0.x. Can you take a look at that?

**Comment by johnpoth** [comment]
Sure I'm on it. I'll test the build on Java 8 as well. Thanks!

**Comment by johnpoth** [comment]
Merged the fixes for the maven jar plugin into the previous related commit. The jar goal binds by default to the package phase so no need to specify it (an error will be thrown if it is as shown above). mvn clean install -Pfastinstall now runs smoothly. Sorry for the trouble, thanks for looking into this!

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
