### PR TITLE
CAMEL-11279 test and fix

### PR DESCRIPTION
**Pull request by anton-k11**
Fix and JUnit test for https://issues.apache.org/jira/browse/CAMEL-11279

### CODE REVIEW

**Comment by oscerd** [comment]
This looks good to me. @davsclaus what do you think?

**Comment by davsclaus** [comment]
The code need a little bit of cleaning up. Also you should set the mock exceptions before doing any sending / processing etc, and then assert afterwards, eg move the mock set stuff higher up. 

And reset the mock between multiple tests in the same test method.

**Comment by davsclaus** [comment]
Also next time use CAMEL-NNNN in the commit log messages, it makes it much easier to track what the change is from. You may want to squash your commits and use CAMEL-NNNN in the commit message when doing so.

**Comment by davsclaus** [comment]
@anton-k11 thanks for the PR. I have polished it a bit.

@oscerd yeah it was a good PR but needed a little bit of polish. Also there was another problem with a wrong default when using spring boot in 2.19 onwards and the example needed to be updated as well.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
