### PR TITLE
CAMEL-14910: Bundling of the heavily distributed components

### PR DESCRIPTION
**Pull request by AemieJ**
Particular queries were raised in this issue.
1. Should there be summary pages for groups of related components?
There already existed summary pages for groups including Ignite, Spring, and a few others. However, as this brings in clarification to understand the documentation, I also added a summary for other groups including AWS, AWS 2, Google.

2. What should their structure and appearance be?
In the nav panel, I believe that the highly distributed related components should be bundled and grouped together within the parent component.

3. Should the nav pane indent the components in a group?
As for user manual documentation under camel Kafka and others, the nav pane is well indented with subgroups and parent groups. Thus, it has been done in the same manner for this PR.

### CODE REVIEW

**Comment by AemieJ** [comment]
@djencks some issues occurred with my git commands. However, the problem I face is when I use `mvn clean install`, it resulted in a bunch of errors. Along with it, `mvn compile` resulted in `plugin directory` error.

**Comment by djencks** [comment]
Can you be more specific about what you ran `mvn clean install` against? For instance, could you supply the git commit hash? Does it include my PR?
I would guess the `plugin directory` error is not related to our commits, since we didn't modify it.

**Comment by AemieJ** [comment]
I ran it under the `camel-package-maven-plugin`, both `mvn clean install` and `mvn compile` have built successfully now. However, I haven't observed any changes in the **.adoc** after the build was a success. Am I meant to run any other command apart from `mvn compile`?

**Comment by djencks** [comment]
My PR won't change any of the .adoc files without your changes to them.  For a file to which you've added `:group: Ignite` it will move that to the end of the header attributes, preceded by a comment.  What did you run the build on?
Thinking about how to get both our work in, I think it would give the clearest history if you rebased your work on top of mine.  I think we can end up with three (or possibly more commits):
- my java generation patch
- your javascript generation changes
- manual .adoc changes, reformatted by running the java build and then the gulp build.

**Comment by AemieJ** [comment]
I am currently running the build on the components folder.

**Comment by AemieJ** [comment]
@djencks I think it's the best if I rebase all my commits on top of yours. I don't personally have a lot of experience with the use of maven with Java.

**Comment by djencks** [comment]
I'm also trying a local build after rebasing your work on top of mine.  By the way, you probably want to run `mvn clean install -DskipTests` as otherwise the build is apt to take hours and fail several times. (at least in my experience).
There are severa pre-Antoral generation steps involved:
- the java build of each component updates the .adoc file in that component source
- the docs gulpfile build copies those files to docs/components
- the docs gulpfile build also generates the nav file
The gulpfile build is run by maven in the docs folder, so a full maven build should perform all the generation steps.  You can also just run the gulpfile build by running mvn in the docs folder or more directly with `yarn gulp`.  Running the maven build in components will perform the first generation step on all components.

**Comment by djencks** [comment]
My build succeeded and the resulting changes look good to me, for example
```
diff --git a/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc b/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc
index 21c62157e34..0da14768328 100644
--- a/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc
+++ b/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc
@@ -6,6 +6,7 @@
 :since: 2.11
 :supportLevel: Stable
 :component-header: Only producer is supported
+//Manually maintained attributes
 :group: AWS
 
```

**Comment by AemieJ** [comment]
> My build succeeded and the resulting changes look good to me, for example
> 
> ```
> diff --git a/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc b/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc
> index 21c62157e34..0da14768328 100644
> --- a/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc
> +++ b/components/camel-aws-cw/src/main/docs/aws-cw-component.adoc
> @@ -6,6 +6,7 @@
>  :since: 2.11
>  :supportLevel: Stable
>  :component-header: Only producer is supported
> +//Manually maintained attributes
>  :group: AWS
>  
> ```

Do you run `mvn clean install` within the components folder? It seems to give me an error for a particular component.

**Comment by djencks** [comment]
I ran `mvn clean install -DskipTests` at the project root (..../camel/).  I committed the generated changes and pushed my branch to CAMEL-14910-copy in my repo. Perhaps comparing our trees would be useful.
Sometimes it can be hard to figure out what went wrong, and sometimes running mvn with `-e` produces some useful information.

**Comment by AemieJ** [comment]
I will try running mvn for the repo you have created and figure out where I might be going wrong. I will let you know by tomorrow. Thanks @djencks 👍

**Pull request closed without merging**
