### PR TITLE
CAMEL-10701 - Use proper classloader for loading authentication settings in Kafka

### PR DESCRIPTION
**Pull request by adessaigne**

### CODE REVIEW

**Comment by oscerd** [comment]
Looks good to me. I guess we need to merge on 2.18.x too.

@davsclaus what do you think?

**Comment by davsclaus** [comment]
Yeah sure +1

**Comment by oscerd** [comment]
Thanks. The PR has been merged. Can you close this? :-)

**Comment by adessaigne** [comment]
Thanks for merging it !

**Pull request closed without merging**
