### PR TITLE
[CAMEL-15204] Correct IBM i naming/branding in the jt400 component

### PR DESCRIPTION
**Pull request by ThePrez**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-15204) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.

**Description**
The current documentation for the JT400 component references AS/400 systems throughout. AS/400 no longer exists in any suppported capacity. AS/400 was rebranded in 2000, with its successor being fully discontinued on [Sep 30, 2013](https://en.wikipedia.org/wiki/IBM_System_i). In 2008, AS/400 was replaced by [IBM i](https://en.wikipedia.org/wiki/IBM_i) on Power Systems.

However, since the IBM i system supports many of the same constructs as AS/400 and has the ability to run AS/400 programs, people (understandably) have a tendency to incorrectly identify IBM i systems as "AS/400."

This trivial PR simply intends to correct the server name accordingly, to properly reflect reality.

### CODE REVIEW

**Comment by ThePrez** [comment]
CI error looks to be unrelated: ` [ERROR] /home/runner/work/camel/camel/components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcComponent.java:78:56: ',' is not followed by whitespace. [WhitespaceAfter]`

**Comment by ThePrez** [comment]
FWIW, looks like that CI failure has been corrected at https://github.com/apache/camel/commit/cc0aea56d45537cc2d689577f015749f19f21e85

**Comment by davsclaus** [comment]
There should be AS/400 still in the description so users can still find - so can you add (formerly known as AS/400) or something like that.

**Comment by ThePrez** [comment]
> 
> 
> There should be AS/400 still in the description so users can still find - so can you add (formerly known as AS/400) or something like that.

I agree. For this reason, I left the AS/400 references (and added the commonly-Googled "iSeries") in the `JT400Endpoint` and `JT400Component` classes, and by proxy the main `jt400-component.adoc`. Should I also keep "AS/400" throughout the more detailed docs at all the IBM i reference points?

**Pull request merged**
