### PR TITLE
core-main: modularize BaseMainSupport for easy subclassing

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@davsclaus I've splitted the BaseMainSupport::postProcessCamelContext in multiple methods for fine grained customization by subclasses

**Comment by lburgazzoli** [comment]
@davsclaus should we wait for this LGTM thing to complete ?

**Comment by oscerd** [comment]
It's experimental. You can merge if you want

**Comment by davsclaus** [comment]
No you are welcome to merge

**Pull request merged**
