### PR TITLE
Added Null validation for Host to display validation message

### PR DESCRIPTION
**Pull request by ramu11**
possible fix for 👎 
https://issues.apache.org/jira/browse/CAMEL-11216

### CODE REVIEW

**Comment by onders86** [comment]
please reference your PR with JIRA issue id like CAMEL-XXXXX

**Comment by ramu11** [comment]
updated commit message with Jira ID

**Comment by davsclaus** [comment]
There is a better fix here
https://github.com/apache/camel/commit/045a23054e266df6ae09c17744d240012938b83c

**Comment by davsclaus** [comment]
Do you mind closing this PR

**Comment by ramu11** [comment]
This closes #1702

**Comment by ramu11** [comment]
I don't see changes merged to master branch

**Comment by oscerd** [comment]
Here is the fix from Claus

https://github.com/apache/camel/commit/045a23054e266df6ae09c17744d240012938b83c

So the PR can be closed.

**Comment by ramu11** [comment]
Closed  #1702

**Pull request closed without merging**
