### PR TITLE
CAMEL-18376: camel-pulsar: add redelivery backoff for ack timeout, nack

### PR DESCRIPTION
**Pull request by anthonywu-toast**
Resolves the following Jira issue: https://issues.apache.org/jira/browse/CAMEL-18376

This PR adds in the ability to add a [RedeliveryBackoff](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/RedeliveryBackoff.java) for both the [ack timeout](https://pulsar.apache.org/docs/concepts-messaging/#acknowledgement-timeout) and[ negative acknowledgement](https://pulsar.apache.org/docs/concepts-messaging/#negative-acknowledgement) cases (details linked). Modifications to existing tests and the addition of a new test should ensure that the backoff works as expected.

Checklist:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Review by connormcauliffe-toast — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by anthonywu-toast** [comment]
Will take a peek at job failures and fix shortly.

**Comment by orpiske** [comment]
Attaching the logs:

[build.log(2).zip](https://github.com/apache/camel/files/9307160/build.log.2.zip)
[test-logs(9).zip](https://github.com/apache/camel/files/9307161/test-logs.9.zip)
[checkstyle.log(4).zip](https://github.com/apache/camel/files/9307162/checkstyle.log.4.zip)

**Comment by anthonywu-toast** [comment]
If there's another test failure, do you mind attaching the logs (or showing me where I can find them), @orpiske? My local machine seems to have trouble running these Docker-based tests.

**Comment by orpiske** [comment]
> If there's another test failure, do you mind attaching the logs (or showing me where I can find them), @orpiske? My local machine seems to have trouble running these Docker-based tests.

Access to the test logs is restricted by the organization, but I can upload them here as needed. 
[test-logs(1).zip](https://github.com/apache/camel/files/9309145/test-logs.1.zip)

**Comment by anthonywu-toast** [comment]
@orpiske mind if I get logs for the last failed run?

**Comment by orpiske** [comment]
> @orpiske mind if I get logs for the last failed run?

[test-logs.zip](https://github.com/apache/camel/files/9315983/test-logs.zip)

**Comment by anthonywu-toast** [comment]
Thanks for sending the files; I managed to commandeer a coworker's laptop running on x86_64 to avoid the local issues I was seeing (since I'm on an M1 it revolves around https://github.com/apache/pulsar/issues/12944). I left configuring container startup/timeouts, etc. out of the loop for now. Tests pass locally so hopefully this should be the last commit!

**Comment by davsclaus** [comment]
Yeah it works now, thanks for contributing to Camel. You are welcome to keep improving ;)

**Pull request merged**
