### PR TITLE
CAMEL-13747: Added basic auth support to camel-solr

### PR DESCRIPTION
**Pull request by renjfk**
This is an attempt of implementing basic auth on solr component according to recommended way mentioned [here](https://lucene.apache.org/solr/guide/7_7/basic-authentication-plugin.html#using-basic-auth-with-solrj). Concurrent client seems to be failing though for some reason when basic auth is enabled.

### CODE REVIEW

**Comment by renjfk** [comment]
Ah well it was never implemented on ConcurrentUpdateSolrClient

**Comment by oscerd** [comment]
Can you please raise also a issue here? https://issues.apache.org/jira/projects/CAMEL so we can track it better?

**Comment by renjfk** [comment]
Yes of course, just created.

**Comment by oscerd** [comment]
And can you please open this against master branch and against camel-2.x? 2.24.x is already out and there is already 2.24.1. This is a new feature, so it should be part of camel-2.25.0. Thanks. You can close this PR and open another one against camel-2.x or closing this once you'll open the new one.

**Comment by renjfk** [comment]
Sure, changed this PR against master do you want me to create another PR against camel-2.x?

**Comment by oscerd** [comment]
Yes. Please

**Comment by renjfk** [comment]
Oki before that if you can review I have a small issue. I enabled basic auth for all tests so the feature can be tested along with all available methods but right now streaming tests are failing because of ConcurrentUpdateSolrClient does not implement it at all. Setting `blockUnknown` in `security.json` `false` would let it pass and other tests still wouldn't lose purpose because Solr only allows requests without `Authorization` header but still checks the ones with it. What do you think?

**Comment by oscerd** [comment]
I think it makes sense to set blockUnknown to false for tests purpose

**Comment by renjfk** [comment]
Alright changed it that way.

**Comment by renjfk** [comment]
Another thing occurred to me. Currently we use this component on production and input body comes as `Map` and we are handling using custom type converter to `SolrInputDocument`. Not sure if that sounds a common use but if it does maybe it would make sense to extend component to handle `Map`s and/or `Collection` of `Map`s within the component. What do you think?

**Comment by oscerd** [comment]
It could be part of another issue and another PR. Thanks

**Comment by renjfk** [comment]
Alright then.

**Comment by oscerd** [comment]
Thanks, merged on master

**Pull request closed without merging**
