### PR TITLE
CAMEL-16374: allow multiple onCompletion at route scope

### PR DESCRIPTION
**Pull request by klease**
Remove the limitation for a single onCompletion at route scope.
As for global scope, any number of onCompletion are supported.
Adapt the unit tests and the documentation.

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]
Looks good, but please start from a fresh git tree

**Comment by oscerd** [comment]
We cannot merge or rebase currently

**Comment by davsclaus** [comment]
Can you not use the green button "Squash and merge", then its 1 commit only

**Comment by oscerd** [comment]
With squash it works.

**Pull request merged**
