### PR TITLE
CAMEL-17859: increase logs in critical smpp code for diagnosing the issue root cause

### PR DESCRIPTION
**Pull request by orpiske**
This is a WIP and available for the user to help diagnose and fix the
issue

### CODE REVIEW

**Comment by orpiske** [comment]
c/c: @PascalSchumacher if you can give it a try and see if we can collect more information with these ... Thanks in advance.

**Comment by PascalSchumacher** [comment]
Sorry I am not able to reduce the issue. 😞 

I am able to simulate part of the events from the log in the issue (existing connection, enquire link timeout) using a hacked copy of `DefaultSmppServer` from https://github.com/fizzed/cloudhopper-smpp.

But I do not know how to simulate `SocketException` (and the `InterruptedException` with the right timing).

**Comment by orpiske** [comment]
> Sorry I am not able to reduce the issue. 😞
> 
> I am able to simulate part of the events from the log in the issue (existing connection, enquire link timeout) using a hacked copy of `DefaultSmppServer` from https://github.com/fizzed/cloudhopper-smpp.
> 
> But I do not know how to simulate `SocketException` (and the `InterruptedException` with the right timing).

That's OK. For now, let's increase the logs in the `tryLock` failures so we are not in the dark in the case it fails. Based on our discussion on the ticket, I also believe they could play a role in this, but I don't want to change the code without a solid evidence of the root cause - primarily to avoid making it even worse.

**Comment by orpiske** [comment]
And thanks for taking the time to try to reproduce it!

**Comment by PascalSchumacher** [comment]
Yes, the logging should make it easier to diagnose the problem if it occurs again.

**Pull request merged**
