### PR TITLE
CAMEL-10947: camel-box - Upgrade to log4j2 and fix Karaf feature

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.apache.org/jira/browse/CAMEL-10947

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks a lot. @oscerd do you mind taking a look and merge this PR ?

**Comment by oscerd** [comment]
Sure thing :-)

**Comment by oscerd** [comment]
@tadayosi thanks a lot. The PR has been merged. Do you mind closing this?

**Comment by tadayosi** [comment]
Great. thanks!

**Pull request closed without merging**
