### PR TITLE
CAMEL-11234: NullPointerException while trying to get the Route Status on startup

### PR DESCRIPTION
**Pull request by prashant2402**
Please review the fix.

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please PR create from master? This PR has commit already squashed with the last PR you opened.

**Comment by prashant2402** [comment]
sorry, will do that.

**Comment by oscerd** [comment]
No worries! Thanks for your contributions!

**Comment by onimurasame** [comment]
This was exactly what I was thinking of doing. Unluckily I wasn't able to build Camel to test...

**Pull request closed without merging**
