### PR TITLE
CAMEL-10723: Improved camel-aws kinesis documentation

### PR DESCRIPTION
**Pull request by ullgren**

### CODE REVIEW

**Comment by davsclaus** [comment]
@oscerd looks good to merge

**Comment by oscerd** [comment]
I'll merge soon :-) Thanks @ullgren

**Comment by oscerd** [comment]
Thanks @ullgren . The PR has been merged. Can you close this?

**Comment by davsclaus** [comment]
@oscerd do you mind checking if 2.18.x branch can have this PR as well, as that default value in the component doc schema would be good to have backported

**Comment by oscerd** [comment]
Sure, I'll check

**Comment by oscerd** [comment]
Backported on 2.18.x too

**Comment by ullgren** [comment]
Thanks for merging.

**Pull request closed without merging**
