### PR TITLE
AWS refresh secret

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
@oscerd here is a PR that adds AWS refresh as first-class. You need to set `camel.vault.aws.refresh-enabled=true` and it checks every 30 sec by default (there is a setting to custom that). Also you need to specify which secrets to trigger (we should auto-detect from property placeholder in another PR).

`camel.vault.aws.secrets=foo,bar,dude*`

its a pattern so you can use * for wildcards and comma for multi valued.

Maybe you can try with PR with the example
https://github.com/apache/camel-examples/tree/main/examples/aws/aws-secrets-manager-reloading

When we get AWS done then we can do similar for the other clouds.

**Comment by davsclaus** [comment]
And we also need to update spring boot starter with the new config values

**Review by oscerd — APPROVED** [review]
Looks really good, thanks a lot! Can we also support more task? Like not aws-secret-refresh but selectable from multiple? We could maybe add a resolver or set an enum. Looks perfect by the way. Please merge and I'll try the example with this. Many thanks

**Comment by oscerd** [comment]
> Looks really good, thanks a lot! Can we also support more task? Like not aws-secret-refresh but selectable from multiple? We could maybe add a resolver or set an enum. Looks perfect by the way. Please merge and I'll try the example with this. Many thanks

I think we could make it configurable, like having some kind of policy or strategy parameter for the task to use. But it's an improvement

**Comment by davsclaus** [comment]
At the moment its one task per cloud, but we can look at adding support for multiple. Lets take one step at a time.

**Comment by davsclaus** [comment]
merged to main, give it a try @oscerd and we can improve this in new PRs as we learn

**Pull request closed without merging**
