### PR TITLE
Added spring-boot archetype

### PR DESCRIPTION
**Pull request by fg78nc**
Added spring-boot archetype for v 3.7.0-SNAPSHOT (Spring Boot 2.3.5)

### CODE REVIEW

**Review by oscerd — COMMENTED** [review]
There is already an archetype in camel sb repo. So we have separation. Here it's not needed. Also sb is still not updated to 2.3.5 in camel. Please close this

**Comment by oscerd** [comment]
Thanks anyway. You can improve the existing sb archetype if you have time and will.

**Comment by fg78nc** [comment]
Where can I find it? I looked at the spring repo, did not find anything
related to camel, expect camel spring archetype 3.6.0.
Is the one you are referring to?

https://repo.spring.io/webapp/#/artifacts/browse/tree/General/jcenter-cache/org/apache/camel/archetypes/camel-archetype-java/3.6.0/camel-archetype-java-3.6.0.pom

**Comment by oscerd** [comment]
It's for 3.7.0, https://github.com/apache/camel-spring-boot/tree/master/archetypes/camel-archetype-spring-boot

**Pull request closed without merging**
