### PR TITLE
Apply website doc changes after 3.15.0 release

### PR DESCRIPTION
**Pull request by gzurowski**
Website/doc changes after Camel 3.15.0 release

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by djencks — CHANGES_REQUESTED** [review]
The antora.yml versions aren't quite right yet, and the camel-spring-boot and camel-karaf antora.ymls also need version 3.15.x (I didn't check what is in them now)

**Comment by gzurowski** [comment]
@djencks Thanks for your feedback. I have made the requested updates, could you please take a quick look?

**Comment by djencks** [comment]
The updates here look good, but we need similar changes in camel-spring-boot and camel-karaf.  I've made what's needed for the docs in https://github.com/apache/camel-spring-boot/pull/434 and https://github.com/apache/camel-karaf/pull/113 and set up a preview build with https://github.com/apache/camel-website/pull/775.  The website PR has 2 commits: after we like the preview the 3 content branches need to be merged, the 2nd commit removed from the preview PR and the first commit merged.  I hope we can make this process simpler soon!!!

**Comment by gzurowski** [comment]
> The updates here look good, but we need similar changes in camel-spring-boot and camel-karaf. I've made what's needed for the docs in [apache/camel-spring-boot#434](https://github.com/apache/camel-spring-boot/pull/434) and [apache/camel-karaf#113](https://github.com/apache/camel-karaf/pull/113) and set up a preview build with [apache/camel-website#775](https://github.com/apache/camel-website/pull/775). The website PR has 2 commits: after we like the preview the 3 content branches need to be merged, the 2nd commit removed from the preview PR and the first commit merged. I hope we can make this process simpler soon!!!

Thanks for reviewing and making the necessary changes in the Spring Boot and Karaf subprojects. Can I go ahead and merge this PR?

**Pull request merged**
