### PR TITLE
CAMEL-15704: camel-csimple - Compiled simple language

### PR DESCRIPTION
**Pull request by ppalaga**
Improve the 100% build time compiled use case

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
There is some code generated scripts that needs to be regen:

core/camel-core/src/test/java/org/apache/camel/language/csimple/HighPredicate.java:public class HighPredicate extends CSimpleSupport {
core/camel-core/src/test/java/org/apache/camel/language/csimple/MedPredicate.java:public class MedPredicate extends CSimpleSupport {
tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript1.java:import org.apache.camel.language.csimple.CSimpleSupport;
tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript1.java:public class CSimpleScript1 extends CSimpleSupport {
tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript2.java:import org.apache.camel.language.csimple.CSimpleSupport;
tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript2.java:public class CSimpleScript2 extends CSimpleSupport {
tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript3.java:import org.apache.camel.language.csimple.CSimpleSupport;
tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript3.java:public class CSimpleScript3 extends CSimpleSupport {

**Comment by davsclaus** [comment]
eg just git grep CSimpleSupport as this class was changed its constructor

**Comment by ppalaga** [comment]
Do I need to run the tests to regenerate those?

**Comment by davsclaus** [comment]
No these are hand coded, so you just go and change their code.

**Comment by ppalaga** [comment]
911e778: fixed the classes extending CSimpleSupport

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
