### PR TITLE
CAMEL-11725 applied a new way of Atmosphere Framework initialization

### PR DESCRIPTION
**Pull request by pkletsko**
This commit will fix the problem with initialisation of Atmosphere framework and gives ability to use this component with combination of spring boot. It is important for now to keep version of atmosphere 2.4.10

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks, I'll review soon :-)

**Comment by pkletsko** [comment]
cool thanks

**Comment by oscerd** [comment]
Thanks for the PR. This will be available in Camel 2.20.0

**Comment by pkletsko** [comment]
Super thanks , waiting for 2.20.0

**Comment by oscerd** [comment]
Thanks for your contribution :-)

**Pull request merged**
