### PR TITLE
Upgrade opentelemetry to the version 1.20.1

### PR DESCRIPTION
**Pull request by bvahdat**
- Will separately look into `camel-opentelemetry-starter` and provide PR by it's related repo if required.

### CODE REVIEW

**Comment by davsclaus** [comment]
Why do you remove the public in all that source code ?

**Comment by bvahdat** [comment]
I have only removed the `public` modifiers in Tests, please see Sam Brannen's answer here:

https://stackoverflow.com/a/55230350

Who is the main contributor to JUnit 5:

https://github.com/junit-team/junit5/graphs/contributors

And I think @essobedo also applies the same pattern by all his PRs which makes sense to me as well.

Also please see the INFO box here:

https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Please keep as before, this PR is about dependency upgrade.

We should not change `public` in test methods which causes backport problems as the code is changed compared to older branches.

**Comment by bvahdat** [comment]
> Please keep as before, this PR is about dependency upgrade.
> 
> We should not change `public` in test methods which causes backport problems as the code is changed compared to older branches.

Sure, is done.

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
I am not sure why the CI server failed the 2nd time

**Comment by bvahdat** [comment]
> I am not sure why the CI server failed the 2nd time

These are test failures in core not relevant to this PR. Though not sure why those tests are run in the first place, as this PR has no effect on e.g. `camel-core`, but maybe @orpiske knows more about it.

Screen Shot 2022-12-04 at 18 56 49

Screen Shot 2022-12-04 at 18 57 06

Anyway going to rebase & merge.

**Comment by orpiske** [comment]
> > I am not sure why the CI server failed the 2nd time
> 
> These are test failures in core not relevant to this PR. Though not sure why those tests are run in the first place, as this PR has no effect on e.g. `camel-core`, but maybe @orpiske knows more about it.


One of the core tests is flaky on Github actions. Let's see if #8835 improves a bit.

**Comment by orpiske** [comment]
> We should not change public in test methods which causes backport problems as the code is changed compared to older branches.

IMHO, that's a cleanup we need to do separately and in one shot per component (so we can cherry-pick) and only removing the `public` modifier. Maybe for Camel 4 ...

**Comment by bvahdat** [comment]
> > We should not change public in test methods which causes backport problems as the code is changed compared to older branches.
> 
> IMHO, that's a cleanup we need to do separately and in one shot per component (so we can cherry-pick) and only removing the `public` modifier. Maybe for Camel 4 ...

Thanks @orpiske for your feedback. This has been now taken care of separately through https://github.com/apache/camel/pull/8831

**Pull request merged**
