### PR TITLE
Integration with FCM

### PR DESCRIPTION
**Pull request by allancth**
No privilege to create JIRA yet. Will request next round.

### CODE REVIEW

**Comment by allancth** [comment]
It is not used in the component nor in the project itself. Should it be removed?

**Comment by oscerd** [comment]
Why did you add that ConnectionFactory to the PR?

**Comment by allancth** [comment]
The connectivity to FCM with Smack's ConnectionConfiguration are configured with some specific parameters:
config.setSecurityMode(SecurityMode.enabled);
config.setReconnectionAllowed(true);
config.setRosterLoadedAtLogin(false);
config.setSendPresence(false);
config.setSocketFactory(SSLSocketFactory.getDefault());

The current ConnectionConfiguration creation did not allow users to configure the parameters. I didn't test and know how each parameters will affect the connection. I'm also not sure if the using the default values are sufficient.

I will give it a test. Meanwhile, should I close this PR?

**Comment by oscerd** [comment]
We'll wait for your PR :-) Thanks.

**Pull request closed without merging**
