### PR TITLE
should servlet and rest throw exceptions when duplicate and ambiguous paths occur

### PR DESCRIPTION
**Pull request by EvanMi**
1. throw exception when duplicate servlet path occur in create stage.
2. throw exception when ambiguous path occur in rest requesting stage.

### CODE REVIEW

**Comment by davsclaus** [comment]
There is some code changes for camel-elasticsearch which should not be in this PR

**Comment by EvanMi** [comment]
> There is some code changes for camel-elasticsearch which should not be in this PR

my mistake, thaks! @davsclaus

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
@EvanMi oh sorry we merged this too soon. There is test error in camel-serlvet in RestServletGetWildcardsTest. 

You changes seems to pick the wrong matching. Can you take another look and send a new PR.
Also can you create a JIRA ticket so we can better track this change.

**Comment by EvanMi** [comment]
> @EvanMi oh sorry we merged this too soon. There is test error in camel-serlvet in RestServletGetWildcardsTest.
> 
> You changes seems to pick the wrong matching. Can you take another look and send a new PR. Also can you create a JIRA ticket so we can better track this change.

Sure,i'll take care of this.

**Pull request merged**
