### PR TITLE
CAMEL-13185: Add splitResults implementations to Olingo Components

### PR DESCRIPTION
**Pull request by phantomjinx**
* Adds splitResults methods to both Olingo 2 & 4 Consumers

### CODE REVIEW

**Comment by phantomjinx** [comment]
Partner PR for camel-2.x branch

**Comment by phantomjinx** [comment]
@oscerd 

> Olingo4 tests are failing. Also can you run a mvn clean install -Psourcecheck and fix the CS? Thanks.

Would you mind being more specific as I've just run the tests locally and they pass fine. Obviously, some fragility somewhere.

**Comment by oscerd** [comment]
> @oscerd
> 
> > Olingo4 tests are failing. Also can you run a mvn clean install -Psourcecheck and fix the CS? Thanks.
> 
> Would you mind being more specific as I've just run the tests locally and they pass fine. Obviously, some fragility somewhere.

Now it seems they are passing. The original errors were:

```
[ERROR] Tests run: 13, Failures: 0, Errors: 6, Skipped: 0, Time elapsed: 26.594 s <<< FAILURE! - in org.apache.camel.component.olingo4.Olingo4AppAPITest
[ERROR] testReadUnparsedEntity(org.apache.camel.component.olingo4.Olingo4AppAPITest)  Time elapsed: 0.833 s  <<< ERROR!
org.apache.olingo.client.api.serialization.ODataDeserializerException: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntity(Olingo4AppAPITest.java:226)
Caused by: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntity(Olingo4AppAPITest.java:226)

[ERROR] testReadUnparsedEntitySet(org.apache.camel.component.olingo4.Olingo4AppAPITest)  Time elapsed: 0.832 s  <<< ERROR!
org.apache.olingo.client.api.serialization.ODataDeserializerException: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntitySet(Olingo4AppAPITest.java:189)
Caused by: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntitySet(Olingo4AppAPITest.java:189)

[ERROR] testReadUnparsedEntity(org.apache.camel.component.olingo4.Olingo4AppAPITest)  Time elapsed: 0.208 s  <<< ERROR!
org.apache.olingo.client.api.serialization.ODataDeserializerException: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntity(Olingo4AppAPITest.java:226)
Caused by: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntity(Olingo4AppAPITest.java:226)

[ERROR] testReadUnparsedEntitySet(org.apache.camel.component.olingo4.Olingo4AppAPITest)  Time elapsed: 0.831 s  <<< ERROR!
org.apache.olingo.client.api.serialization.ODataDeserializerException: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntitySet(Olingo4AppAPITest.java:189)
Caused by: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntitySet(Olingo4AppAPITest.java:189)

[ERROR] testReadUnparsedEntity(org.apache.camel.component.olingo4.Olingo4AppAPITest)  Time elapsed: 0.255 s  <<< ERROR!
org.apache.olingo.client.api.serialization.ODataDeserializerException: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntity(Olingo4AppAPITest.java:226)
Caused by: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntity(Olingo4AppAPITest.java:226)

[ERROR] testReadUnparsedEntitySet(org.apache.camel.component.olingo4.Olingo4AppAPITest)  Time elapsed: 0.833 s  <<< ERROR!
org.apache.olingo.client.api.serialization.ODataDeserializerException: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntitySet(Olingo4AppAPITest.java:189)
Caused by: java.net.SocketException: Socket is closed
	at org.apache.camel.component.olingo4.Olingo4AppAPITest.testReadUnparsedEntitySet(Olingo4AppAPITest.java:189)
```

**Comment by oscerd** [comment]
Not sure, maybe it was my enviroment. Btw, just fix the CS when you've time and I'll merge.

**Comment by phantomjinx** [comment]
Sorry ... CS?

**Comment by oscerd** [comment]
The checkstyle. If you run mvn clean install -Psourcecheck you should see a list of errors, both on olingo2 and olingo4. Inside etc there is an eclipse file for importing a code formatter template. Thanks.

**Comment by phantomjinx** [comment]
Cool .... found them now.

FYI
Just to note (as its just dawned on me), the sourcecheck profile is not visible inside the camel-olingoN directories themselves so have to execute from the root directory:

`mvn install -Psourcecheck -pl components/camel-olingo4/camel-olingo4-component`

**Comment by phantomjinx** [comment]
@oscerd 
Commit source fixed. Update pushed.

**Comment by oscerd** [comment]
Merged, thanks

**Pull request closed without merging**
