### PR TITLE
CAMEL-19386: Support object property on template bean

### PR DESCRIPTION
**Pull request by igarashitm**
# Description
Fixes: https://issues.apache.org/jira/browse/CAMEL-19386

Also fixed the annotation for `beans` property on TemplatedRouteDefinitionDeserializer and RouteTemplateDefinitionDeserializer to represent what deserializers actually supports in the generated schema

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

Cc @lburgazzoli 

Hi @grgrzybek , I believe I made it backward compatible for XML DSL for template bean `property`, while it adds `properties` to accept object property like non-template bean style. Hopefully this won't bother your current work...

### CODE REVIEW

**Comment by igarashitm** [comment]
hmm components/camel-spring-xml tests doesn't fail for me, can I look at the workflow test log?

**Comment by grgrzybek** [comment]
I'll check this PR before noon (CEST).

**Comment by grgrzybek** [comment]
This YAML/XML/JAXB consistency is tricky, but finally I got the PR - looks good ;)

**Review by grgrzybek — APPROVED** [review]

**Review by oscerd — APPROVED** [review]
It's there something to know in relation to the work ongoin in https://github.com/apache/camel-kamelets/issues/1475

**Review by oscerd — APPROVED** [review]
It's there something to know in relation to the work ongoin in https://github.com/apache/camel-kamelets/issues/1475

**Comment by igarashitm** [comment]
@oscerd There shouldn't be any problem - this change fixes the schema to allow both property styles, so https://github.com/apache/camel-kamelets/issues/1475 is not mandatory after this. But I think it's still beneficial to do that and align the style with non-template bean on official Kamelets.

**Comment by oscerd** [comment]
I'll complete the work on that side. Thanks

**Pull request merged**
