### PR TITLE
TestSupport: Deprecate methods which redirect to deprecated methods o…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…f org.apache.camel.builder.Builder

### CODE REVIEW

**Comment by davsclaus** [comment]
This is really only for testing camel-core itself, and as such has little value for end users. Please look at camel-test as that is for end users to use

**Comment by davsclaus** [comment]
Thanks can you close this PR

**Comment by PascalSchumacher** [comment]
I'm very new to camel so thanks for the hint and thanks for merging.

I will create another other pull request for camel-test.

**Comment by davsclaus** [comment]
A good beginner ticket is this one
https://issues.apache.org/jira/browse/CAMEL-9340

**Comment by PascalSchumacher** [comment]
Thanks. I will take a look at the ticket.

**Pull request closed without merging**
