### PR TITLE
CAMEL-11345: Remove dependency on spring-core from gRPC component

### PR DESCRIPTION
**Pull request by dmvolod**
I've added an advanced findMethod and invokeMethod methods to the org.apache.camel.util.ReflectionHelper

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you use `invokeMethod` from `ObjectHelper` which we already have.

**Comment by dmvolod** [comment]
@davsclaus thanks for the feedback, code changed

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by dmvolod** [comment]
Thanks, PR closed

**Pull request closed without merging**
