### PR TITLE
Refines zipkin download instructions

### PR DESCRIPTION
**Pull request by adriancole**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by adriancole** [comment]
I don't. thanks for the quick fix!

**Comment by davsclaus** [comment]
btw just a heads up. We have a PR on the way about opentracing
https://github.com/apache/camel/pull/1467

**Comment by adriancole** [comment]
yep noticed that. opentracing is a abstraction library, so the MockTracer
shows something similar to what the data might look like in a real system.

Incidentally, zipkin has a junit rule which 100% implements the server api.
So, in this case, you can test with complete confidence of what trace data
will look like when in use (and any side-effects like what if zipkin is
down, etc).

**Comment by oscerd** [comment]
This is great for testing.

@objectiser , can you take a look ?

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin/tree/master/zipkin-junit is what I was
referring to

(incidentally, this can also be used by opentracing-zipkin bridge if you
plumb your tests to use http)

On Fri, Feb 17, 2017 at 10:15 AM, Andrea Cosentino <notifications@github.com

**Comment by oscerd** [comment]
thanks @adriancole

**Comment by objectiser** [comment]
@oscerd sure will take a look - although ideally it would be better to ensure MockTracer gave us what we need from a test perspective, to remain independent of the tracing solution being used.

@adriancole Thanks for the reference.

**Comment by adriancole** [comment]
reason I mention is that often there's no strict relationship between tags
etc used in opentracing and how it ends up in representation across any
system.

In Zipkin, this frequently results in low quality traces and support
problems. Many times people do things like serialize timestamps into a
key/value pair, or completely drop data. They end up pasting this stuff
into gitter :)

That's one reason it could be handy to test at least one system (especially
if it has a junit rule).

Regardless, the zipkin tracing module could use this, even if the
opentracing one doesn't. While there's less chance of signal loss in the
zipkin impl, there's still chance of bugs around transport etc, which are
easily solvable by using the junit rule.

Anyway, it is all food for thought, since asked figured I'd give 2p

**Pull request closed without merging**
