### PR TITLE
Ban com.sun.xml.bind:jaxb-impl, replace it with jaxb-runtime where needed

### PR DESCRIPTION
**Pull request by ppalaga**
# Description

org.glassfish.jaxb:jaxb-runtime is the new Jakarta implementation of JAXB. It should be preferred to the old com.sun.xml.bind:jaxb-impl

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking

No Jira, because this is just housekeeping. But I can create one, if needed.

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.
- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by davsclaus** [comment]
Where is this information. Do we have a page that states this.

At this page the front page says
https://eclipse-ee4j.github.io/jaxb-ri/

```
        <dependencies>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>4.0.2</version>
            </dependency>
        </dependencies>

        <dependencies>
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>4.0.5</version>
                <scope>runtime</scope>
            </dependency>
```

**Comment by ppalaga** [comment]
Thanks for the pointer, @davsclaus. Well, the authoritative resources about JAXB implementations are rather sparse and confusing. 
[This SO answer](https://stackoverflow.com/a/72151763) seems to describe the situation in the most complete way: 
* com.sun.xml.bind:jaxb-impl is marked as "old" in its own pom description: https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/4.0.5/jaxb-impl-4.0.5.pom
* org.glassfish.jaxb:jaxb-runtime and com.sun.xml.bind:jaxb-impl classes overlap and differ only in whether they include or depend on some transitives (istack/txw2)
* The SO answer proposes to use newest versions of org.glassfish.jaxb:jaxb-runtime for projects after Jakarta migration and com.sun.xml.bind:jaxb-impl (versions before v3) for projects that still require javax.xml.bind. They can even co-exist in that way. 

Mainly the last point makes great sense to me. 

What are other's thoughts? Maybe I am missing something?

**Comment by davsclaus** [comment]
And it would be good to add a note in the 4.8 upgrade docs about this change (so users would be aware) but hopefully they dont need to worried.

**Comment by ppalaga** [comment]
> So this would need to check that camel and CSB and CEQ still works aftwards.

It is fine for Camel Quarkus, where we already merged a similar change https://github.com/apache/camel-quarkus/pull/6382

> And it would be good to add a note in the 4.8 upgrade docs 

Where can I do that?

**Comment by davsclaus** [comment]
upg doc here
https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc

**Comment by davsclaus** [comment]
I wonder if CSB need some kind of update as well since CEQ had that ?

**Comment by ppalaga** [comment]
> I wonder if CSB need some kind of update as well since CEQ had that ?

Yes, having an enforcer check might be a good idea to make sure that `com.sun.xml.bind:jaxb-impl` is not smuggled back by SB deps.

**Comment by ppalaga** [comment]
> upg doc here https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc

Thanks, done in 57f07d3. Please review.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
