### PR TITLE
pass rest prams and messages

### PR DESCRIPTION
**Pull request by sebi-hgdata**
Hey,
  I've added support for directly passing rest prams and messages

### CODE REVIEW

**Comment by davsclaus** [comment]
Hi

The DSL is not intended to use the definition classes as parameters. We dont do that in the regular route dsl.

You can use the regular getter/setter to build with defintions outside the DSL.

Do you mind closing this PR?

**Comment by sebi-hgdata** [comment]
This was the best option for sharing same definitions across rest routes... if there is a better solution, I can do them. Do you have an example approach for using getters/setters?

**Comment by davsclaus** [comment]
Why are the the same, or in other words how many api documentations do you have that are 100% identical?

**Comment by sebi-hgdata** [comment]
Quick example would be pagination and ordering params and not authorized , generic error response messages. These are the same across the API

**Comment by davsclaus** [comment]
Okay that makes sense. I just merged this PR. Do you mind closing it.

**Comment by sebi-hgdata** [comment]
Thanks

**Pull request closed without merging**
