### PR TITLE
CAMEL-16178: camel-netty should invoke callback exactly once even when there was no UnitOfWork

### PR DESCRIPTION
**Pull request by k-jamroz**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Please first open the PR against master and eventually we'll backport. Is the regression test related to a different issue?

**Comment by k-jamroz** [comment]
> Please first open the PR against master and eventually we'll backport. 

Ok, I will rebase to master.

> Is the regression test related to a different issue?

Fix of CAMEL-9527 fixed errors during shutdown but broke enricher with camel-netty (the main issue I am trying to fix: CAMEL-16178). I do not want my fix to reintroduce CAMEL-9527. Shall I separate these pull requests? These commits are almost independent except for adding org.assertj in pom.xml

**Comment by oscerd** [comment]
Important part is referencing the correct issue number with a good commit message, no need for separate PR, they seem to be related

**Review by davsclaus — APPROVED** [review]
Thanks this is great work

**Comment by k-jamroz** [comment]
I rebased PR to master and updated descriptions. Still need to fix {{NettyReuseChannelTest}}. It seems that camel-netty behavior was wrong earlier and this PR only exposed the problem.

**Review by oscerd — APPROVED** [review]
LGTM, I think we can wait for the test fix.

**Pull request merged**
