### PR TITLE
Added Null validation for Host to display validation message

### PR DESCRIPTION
**Pull request by ramu11**
Possible Improvement for 👍 
https://issues.apache.org/jira/browse/CAMEL-11216

### CODE REVIEW

**Comment by ramu11** [comment]
In my test  when the host is empty it displays
java.lang.IllegalArgumentException: Invalid uri: http://:8080/pets/2. If you are forwarding/bridging http endpoints, then enable the bridgeEndpoint option on the endpoint: http4:/pets/%7Bid%7D
Now the fix display same messages when host is null instead of NPE

**Comment by davsclaus** [comment]
Thanks for the PR. Can you run checkstyle and fix the issue, eg run

     mvn compile -P sourcecheck

In that module with your code changes.

**Comment by davsclaus** [comment]
Thanks. I do ponder if we should not add some more validation that checks for null/empty host and then throw a more appropriate exception with a description telling the user to specify the hostname. 

The trick is that this applies to the producer as the consumer may infer to use localhost. So would maybe need to dive a bit more into the code to find the correct spot to do this

**Comment by ramu11** [comment]
Thanks for the update.Actually I haven't added  any validation message as part of the fix.It is being  thrown from  **createMethod** of **HttpProducer** class. when I DEBUG the code having **Host** not provided .it is by passing the below  check 

`// there must be a host on the method
        if (method.getURI().getScheme() == null || method.getURI().getHost() == null) {
            throw new IllegalArgumentException("Invalid uri: " + uri
                    + ". If you are forwarding/bridging http endpoints, then enable the bridgeEndpoint option on the endpoint: " + getEndpoint());
        }`

So I have set Host to empty  to pass the above check.

**Comment by davsclaus** [comment]
I wonder if you can rebase or redo this PR as you now have all the other commits in this PR. We should only have YOUR code changes in the PR.

**Comment by davsclaus** [comment]
And can you please use `master` branch instead of `2.19.x`. All changes MUST go to master, and then we decide from there which fixes can be backported or not.

**Comment by ramu11** [comment]
Will Create new PR on Master Branch. Closing this

**Pull request closed without merging**
