### PR TITLE
Update Woodstox to version 6.0.3

### PR DESCRIPTION
**Pull request by PascalSchumacher**

### CODE REVIEW

**Comment by davsclaus** [comment]
Okay this does not work in OSGi. Run

mvn clean install in this folder

camel/platforms/karaf/features

**Comment by PascalSchumacher** [comment]
Sorry for wasting you time.

I will check if there is a recent version of Woodstox that works with OSGI.

**Comment by oscerd** [comment]
Do you think we can close this one?

**Comment by davsclaus** [comment]
yeah maybe create a JIRA so we wont forget and then later can try to find a solution that works on OSGi too

**Pull request closed without merging**
