### PR TITLE
CAMEL-11011 Make all Services Closeable

### PR DESCRIPTION
**Pull request by zregvart**
I'm doing this as a PR so that it can be reviewed, anyone with a comment about this? Thanks :+1: 

This prodvides Service with default implementation of `close` method that delegates to `stop`.

### CODE REVIEW

**Comment by davsclaus** [comment]
Interesting idea.

A service however is not so often used as a one-time thing
http://camel.apache.org/why-does-camel-use-too-many-threads-with-producertemplate.html

I suppose java will only auto close the service if its specified in a try resource block, and there should fit this pattern, and not cause side effects?

**Comment by zregvart** [comment]
Yup if not used in try-with-resources it should not have any side effects, the only thing is that it expands the API that has to be carried forward, so if there is not a good use case it I think it should be dropped.

I was indeed thinking about one-shot producers/consumers, perhaps in a batch/utility context it would make sense.

Don't know if it can be used internally to simplify try-finally blocks in Camel code, but I found one instance in `camel-salesforce` where such a construct could be used.

**Comment by davsclaus** [comment]
Well it makes it a bit more modern java with support for those try .. with resource thingys

**Comment by zregvart** [comment]
I'll take that as an endorsement :+1: :smile:

**Comment by zregvart** [comment]
Merged into master

**Pull request closed without merging**
