### PR TITLE
CAMEL-17500: Simplified Dynamic Router control channel messages.

### PR DESCRIPTION
**Pull request by Steve973**
This pull requests provides simplification to the Dynamic Router EIP component with regard to control channel messages.  Instead of only having the option to create and send a POJO for all of the parameters of subscribing or unsubscribing, this pull request allows a user to:

- use the URI for all parameters, or to use a combination of URI parameters and a bean in the registry that contains the exchange filtering predicate
- use a combination of URI parameters and a Predicate as the message body to use as the exchange filtering predicate
- omit the subscription ID URI parameter to have the subscription ID generated as a UUID string and returned as the message body

The asciidoc file has been updated accordingly.

A pull request will follow this one, in the near future for an update to the corresponding Spring Boot example.  The spring boot starter, itself, is not affected.  Pull request is : https://github.com/apache/camel-spring-boot-examples/pull/46 but will not pass until this one is merged.

- [x] [JIRA issue](https://issues.apache.org/jira/browse/CAMEL-17500)
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations.

### CODE REVIEW

**Comment by Steve973** [comment]
Hi, @davsclaus and @zregvart I did not get this same error when running the exact same command on my machine.  It is also in a different module, so do you have any idea what might be causing the checkstyle violation?

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by Steve973** [comment]
@davsclaus and @oscerd  please don't merge this yet.  I have questions about parallel processing of exchanges.  Merging this in will result in a broken dynamic router component (which is why it's marked as draft).  I posted to the mailing list, for whenever you might have some time.  Thank you!

**Comment by davsclaus** [comment]
You can make a PR as "draft"

**Comment by Steve973** [comment]
@davsclaus and @oscerd If you guys still approve, it should be ok to merge this now, and if the performance can be improved for the mode that matches all recipients, then we can do that in a follow-up pull request, if you both agree.

**Pull request merged**
