### PR TITLE
Optimize DefaultCamelContext#getComponent CAMEL-10269

### PR DESCRIPTION
**Pull request by ssharma**
Further to the conversation in https://github.com/apache/camel/pull/1139, used CHM::computeIfAbsent to avoid global locks and optimize initialization of components. Had to refactor other methods to ensure they reap benefits of CHM.

### CODE REVIEW

**Comment by ssharma** [comment]
@oscerd @davsclaus @lburgazzoli : Moved old PR here

**Comment by davsclaus** [comment]
This looks better. @lburgazzoli any thoughts?

**Comment by oscerd** [comment]
Looks good to me

**Comment by lburgazzoli** [comment]
LGTM

**Pull request closed without merging**
