### PR TITLE
CAMEL-10780 Add test for DefaultFactoryFinder

### PR DESCRIPTION
**Pull request by zregvart**
I was hoping on doing some refactoring of `DefaultFactoryFinder` but,
the functionality I was hoping on doing turned out not to need it. So at
the end I was left with this unit test for DefaultFactoryFinder that
could help someone refactoring in the future.

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you run checkstyle, I think you have missing license headers

**Comment by zregvart** [comment]
Sorry about that, I've added the license headers

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by zregvart** [comment]
Thanks @davsclaus :+1:

**Pull request closed without merging**
