### PR TITLE
CAMEL-18355: Fix bug when both proxy and basic authentication credent…

### PR DESCRIPTION
**Pull request by klease**
…ials provided

Add helper class to manage credentials to set on the HttpClient.
Add a unit test reproducing the issue.

### CODE REVIEW

**Comment by davsclaus** [comment]
The HttpCredentialsHelper is static which means you cant have 2+ http components in the same JVM with different settings.

**Comment by klease** [comment]
> The HttpCredentialsHelper is static which means you cant have 2+ http components in the same JVM with different settings.

True. I'll address that.

**Comment by davsclaus** [comment]
If you do a hot reload updating routes that used http, then the map could be growing forever causing a memory leak.

A better approach is to store that help as a instance on the http component, then its private to this component. You can create the helper in the doInit method etc.

**Comment by klease** [comment]
Thanks for the feedback Claus.
There isn't a doInit method on HttpComponent so I just create it in the method which creates the ClientBuilder and pass it to the private methods creating the configurers.
I also had to modify HttpComponentVerifierExtension.java which creates a ClientBuilder.
Perhaps it would be better to move the Helper to the main http package and give it package visiblity following these changes?

**Comment by davsclaus** [comment]
Yeah if you think this is better and have time to do so

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
