### PR TITLE
CAMEL-14301: Stomp Component has no option to set custom headers

### PR DESCRIPTION
**Pull request by onlybytes**
The org.fusesource.stomp.client.Stomp class has setter method for custom headers, the Camel-Stomp has not exposed that option to be set by the users.

The StompEndpoint and StompConfiguration classes need changes to allow users to set custom headers.

### CODE REVIEW

**Comment by davsclaus** [comment]
How does this unit test use the custom headers? The test seems more for testing header filter strategy.

**Comment by onlybytes** [comment]
Hi @davsclaus 
The unit test was for my previous PR. During that time you had asked for Unit test for header filter strategy.

Agree that it is causing confusion.

**Comment by onlybytes** [comment]
Should i Split this into two PRs?

**Comment by davsclaus** [comment]
Yeah if you have a PR with the header filter unit test. And then another for the new feature

**Comment by onlybytes** [comment]
The header filter PR is closed. Thats fine. I will create a new PR for test. And then a separate PR for new feature.

Thank you for your comments

**Comment by onlybytes** [comment]
Hi @davsclaus 

Incorporated the comments. Please Check

**Comment by oscerd** [comment]
Merged on master. Thanks.

**Pull request closed without merging**
