### PR TITLE
Dk2k code inspection

### PR DESCRIPTION
**Pull request by dk2k**
# Description
Fixes for code issues found by inspection.

# Target

main branch

# Tracking
https://issues.apache.org/jira/browse/CAMEL-19217

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [ x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
This PR is just too big for being reviewed. Please, can you break it in smaller pieces, so that review is easier?

**Comment by dk2k** [comment]
Is it possible to break it after it was submitted into my forked repository? I thought separating changes into commits per issue type would make reviewing more comfortable

**Comment by orpiske** [comment]
> Is it possible to break it after it was submitted into my forked repository? I thought separating changes into commits per issue type would make reviewing more comfortable

Yes. Follow these steps:

1. Create a branch that groups certain types of fixes logically (i.e.: one branch for fixing logging issues, another for fixing Collection issues, another for fixing cast/conversion issues, and so on). 
2. Cherry pick the changes accordingly on each of those branches (please do make sure to test them)
3. Review the commit messages to ensure they follow the description patterns we use in the project (i.e.: have a ticket on them or use `"(chores) name-of-the-component: commit message")
4. Make sure that even so the PR is not too large (otherwise break it even further)
5. Send one PR for each branch

Additional tips: 
- be very conservative when changing `core` code (ideally, separate the PRs for `core` changes and `component` changes)
- if there's a performance benefit of the change you are making, please make sure to contribute some numbers, reasoning or provide JMH tests we can use to verify (specially for larger changes on the core code). 

This is +/- the process I follow myself.

**Comment by dk2k** [comment]
In the ideal world this cherry pick approach would work, but not in this case. I fixed checkstyle issues (I doubt that some of them caused by my changes) in the end - there were several commits.
For example, automated change from my side:
(b << 0) become (b) 
and only in the end I removed redundant parenthesis. Another example: made a field static final. In the end I had to rename it and reorder the declaration. The fixes for checkstyle got mixed up. The PR is consistent, but it's eventual consistency.

Please consider the option of reviewing separate commits from this PR. These commits can be distributed between several reviewers or you can decide for yourself: today I review this commit, tomorrow I will review that one.

For me the reworking will take too much additional time. I will have to build each separate branch. Easy and brute solution is to take a new branch and say copy camel-core folder with the changes. But the readibility will suffer: all the inspection types will get mixed up. 

As for building. In ths page https://camel.apache.org/manual/building.html it states:
A normal build without running tests but auto formatting and checkstyle verification enabled
mvn clean install -Pfastinstall,format,sourcecheck

It's fair if the build is OK right from the first attempt. But if some attempt fails, you should execute it without clean target:
mvn install -Pfastinstall,format,sourcecheck
It will rebuild only what needs rebuilt and saves time.

I won't be able to provide digital data to justify optimizations.
For now I will leave the PR open, maybe you will change your mind.

**Comment by orpiske** [comment]
I am sorry, but -1 for this change is final. As it is, it won't even be automatically tested by our GitHub automation (as there are too many affected components).

**Review by oscerd — CHANGES_REQUESTED** [review]
I'm sorry but I'm not a fan of static code tool and this PR is too big to be reviewed

**Pull request closed without merging**
