### PR TITLE
CAMEL-17579: Preserve the data type of a message on copy

### PR DESCRIPTION
**Pull request by essobedo**
Backport of https://github.com/apache/camel/pull/6866 for 3.14

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project camel-support: Compilation failure
Error:  /home/runner/work/camel/camel/core/camel-support/src/test/java/org/apache/camel/support/AbstractExchangeTest.java:[161,19] error: MyCamelContext is not abstract and does not override abstract method setBeanPostProcessor(CamelBeanPostProcessor) in ExtendedCamelContext

**Comment by oscerd** [comment]
@essobedo

**Comment by oscerd** [comment]
Please open another PR to fix this.

**Comment by essobedo** [comment]
@oscerd ok

**Comment by davsclaus** [comment]
@essobedo the camel-spring-xml has an unit test that reuses a test from camel-core, and now it fails because it was updated as part of this PR


I wonder if you could take a look, see in camel-spring-xml, its the SpringTransformerRouteTest

You likely need to add a route for the new test in the XML file this test uses.

**Comment by essobedo** [comment]
@davsclaus of course, no problem, in which branch?

**Comment by essobedo** [comment]
@davsclaus all branches obviously

**Pull request merged**
