### PR TITLE
doc: Improve CoAP component description

### PR DESCRIPTION
**Pull request by apupier**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by apupier** [comment]
How can I regenrate the parts in kotlin-api-dsl and camel-kotlin-api locally?

or is it fine to merge and it iwill be regenerated automatically?

**Comment by davsclaus** [comment]
you build catalog/camel-catalog
and then afterwards you can build dsl

**Comment by davsclaus** [comment]
but if you have a fast computer its easier just to

```
mvn clean install -P fastinstall
```
from root folder

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
