### PR TITLE
CAMEL-10397 SJMS - Raise an error against InOut+transacted producer a…

### PR DESCRIPTION
**Pull request by igarashitm**
…s it causes a deadlock

### CODE REVIEW

**Comment by igarashitm** [comment]
Hold on one sec, I'd like to move that check from SjmsEndpoint.createProducer() to InOutProducer.doStart()

**Comment by igarashitm** [comment]
OK done.

**Comment by oscerd** [comment]
@igarashitm Thanks for the contribution!

The PR has been merged. Can you close this?

**Comment by igarashitm** [comment]
Thanks! closing

**Pull request closed without merging**
