### PR TITLE
CAMEL-19070: disable ElasticSearch tests on Apache CI until the failure reason can be investigated

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Comment by orpiske** [comment]
@essobedo FYI (I think this component interests you, right?)

**Review by oscerd — APPROVED** [review]

**Comment by essobedo** [comment]
> @essobedo FYI (I think this component interests you, right?)

Thx for letting me know, let me check what's going on

**Comment by essobedo** [comment]
Please close this PR, I'm about to propose another PR to fix it

**Comment by orpiske** [comment]
> Please close this PR, I'm about to propose another PR to fix it

Great news! I'll close it, thanks!

**Pull request closed without merging**
