### PR TITLE
CAMEL-10837: Migrate EIP patterns to adoc

### PR DESCRIPTION
**Pull request by ouapdouap**
This is ongoing work but I wanted to check that I'm doing well.
The main problem for now is that there are some links from the wiki to sections of the documentation (for example the Camel architecture section) that I don't find in the new adoc documentation.

Any idea, thoughts?
Regards,
Sebastien

### CODE REVIEW

**Comment by davsclaus** [comment]
Just remove links to those none existing docs. We will rewamp the docs with new material over the time.

At first its better to get each EIP migrated and let them be part of the auto generated docs.

**Comment by davsclaus** [comment]
@ouapdouap this PR has merge conflicts. Do you mind fixing them and update the PR?

**Comment by davsclaus** [comment]
You should not change the text between the START .. END in the readme file as its auto generated. So all the TODOs will be lost on rebuild.

**Comment by ouapdouap** [comment]
Ok, didn't know that. I'll fix conflicts later today.

**Comment by davsclaus** [comment]
Just added so when you build camel-core you get a WARN for missing eip doc files.

**Comment by davsclaus** [comment]
Can you migrate the options in those files to be doing like the aggregate does with the START and STOP markers

**Comment by ouapdouap** [comment]
I resolved conflicts. As grouping all eips in the eips folder seems ok, I'll keep working on the migration.
Whether you merge this PR now or once I finished the migration is up to you.
Let me know.

**Comment by ouapdouap** [comment]
Ok, I'll do that

**Comment by davsclaus** [comment]
If an EIP doc is not in that WARN list, then its because its `@Metadata` label attribute does not start with `eip`. This can then be changed in the source code to have it in that list.

**Comment by ouapdouap** [comment]
Ok thanks. I'll check the whole consistency of code and doc of EIPs

**Comment by davsclaus** [comment]
I suggest to get the last bits of this PR done with those START and END then we can get this merged. And then new doc changes you can do in another PR.

**Comment by ouapdouap** [comment]
I think I'm ok with the START and END tags.

**Comment by ouapdouap** [comment]
Ok for START/END options.
I'll start working on the missing files in another PR.

**Comment by davsclaus** [comment]
Thanks it was a bit harder to merge as we always rebase so I had to merge and squash the 23 commits.

You future PRs should be easier as we can merge them faster

**Comment by ouapdouap** [comment]
Should I do smaller and more frequent PRs so they are easier to merge?

**Comment by davsclaus** [comment]
Yeah its easier to merge when there are 4-8 commits than 27 etc spread over 5 days. Also a problem was that we implemented that START END thingy in between and also changed some of the same files as you etc.

**Pull request closed without merging**
