### PR TITLE
CAMEL-11315 camel-twitter: Replace dummy URI paths on directmessage a…

### PR DESCRIPTION
**Pull request by igarashitm**
…nd search with something meaningful

### CODE REVIEW

**Comment by davsclaus** [comment]
A problem with this is that you know have a clash with the uri path option and the uri param option as well, eg keywords and user are now duplicates. This is not allowed.

We need to think about a better solution

**Comment by igarashitm** [comment]
Yep, agree it's not clean. I thought it's still acceptable to allow overrinding uri path option by uri param option though. If it's not allowed then we may want to remove keywords/user (or just remove @UriParam)  from TwitterConfiguration and move it to each endpoints. I'll give it a second shot later.

**Comment by igarashitm** [comment]
OK, moved those options from TwitterConfiguration into each endpoints. Now only twitter-streaming endpoint uses keywords uri param and noone uses user uri param.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by igarashitm** [comment]
Thanks! closing

**Pull request closed without merging**
