### PR TITLE
Exposing isActive(), getter and setter methods to extending classes.

### PR DESCRIPTION
**Pull request by maxfortun**
Useful for dynamic configuration updates, such as scheduled retrieval from config source.

### CODE REVIEW

**Comment by oscerd** [comment]
Please when you work on components can you create a JIRA issue to track what you're doing? For the next time. Thanks.

**Comment by oscerd** [comment]
Can you please rebase and avoid the commit syncing with master? Thanks.

**Comment by davsclaus** [comment]
I wonder if a "squash and merge" is okay and the PR can be applied?

**Comment by oscerd** [comment]
I think it should work. Let me try.

**Comment by oscerd** [comment]
Ok done. Thanks @maxfortun

**Comment by maxfortun** [comment]
Did not realize there was a better way to synch the fork up. Thank you.

**Pull request merged**
