### PR TITLE
restdsl-openapi/swagger-plugin: support for component-starter dep

### PR DESCRIPTION
**Pull request by jam01**
This enables the plugins to identify rest component through
org.apache.camel.springboot:camel-{component}-starter dependencies. 

Instead of needing
```
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-netty-http-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.camel</groupId>
            <artifactId>camel-netty-http</artifactId>
        </dependency>
```
for the generator to pick up netty-http, we can just do 
```
        <dependency>
            <groupId>org.apache.camel.springboot</groupId>
            <artifactId>camel-netty-http-starter</artifactId>
        </dependency>
```

### CODE REVIEW

**Comment by jam01** [comment]
If you do need me to create a Jira ticket for this let me know.

**Comment by jam01** [comment]
Oh... Maybe I misunderstood something.

The code already has Spring Boot specific logic:
https://github.com/apache/camel/blob/master/tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java#L247
https://github.com/apache/camel/blob/master/tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/GenerateMojo.java#L153

It adds spring boot camel-servlet-starter when other camel-{component} is not found. So it felt appropriate to find existing camel-{component}-starter if they were declared
https://github.com/apache/camel/blob/master/tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/GenerateMojo.java#L106

**Comment by jam01** [comment]
Oh actually, if the app is Spring boot and the generator defaults to `camel-servlet-starter` it'd use the wrong groupId `org.apache.camel`
 https://github.com/apache/camel/blob/master/tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/GenerateMojo.java#L110

which I think has been deprecated? So probably left over code before migrating starters to `org.apache.camel.springboot`

**Comment by davsclaus** [comment]
Ah sorry yeah if you can update the group id for spring boot so it would work for all runtimes.

**Comment by jam01** [comment]
No worries, camel is a huge project. I should've been more descriptive...

In this last commit I'm pulling duplicated logic from Generate and GenerateXml into AbstractGenerate and making the groupId fix there. The same treatment for both swagger and openapi plugins

**Pull request merged**
