### PR TITLE
[CAMEL-19563] Refactor raw generic type usage

### PR DESCRIPTION
**Pull request by ammachado**
# Description

Refactor raw generic type usage.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

I'll create a PR for Camel 3.x if/when this is accepted.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
This can make backporting to 3.x a bit harder, but since this is usually just a code change on the same code line, then I think its okay.

**Review by davsclaus — APPROVED** [review]

**Comment by orpiske** [comment]
> This can make backporting to 3.x a bit harder, but since this is usually just a code change on the same code line, then I think its okay.

Maybe we could split this PR in two parts: one for the `core` and another for the `components`? I think it would make it easier to bisect, as well.

**Comment by davsclaus** [comment]
There is a merge conflict, can we get this resolved

**Comment by ammachado** [comment]
> There is a merge conflict, can we get this resolved

Resolved.

**Comment by davsclaus** [comment]
I get this compile error
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project camel-spring-redis: Compilation failure: Compilation failure:
[ERROR] /Users/davsclaus/workspace/camel/components/camel-spring-redis/src/main/java/org/apache/camel/component/redis/RedisEndpoint.java:[50,116] incompatible types: org.springframework.data.redis.core.RedisTemplate<capture#1 of ?,capture#2 of ?> cannot be converted to org.springframework.data.redis.core.RedisTemplate<java.lang.String,java.lang.Object>
[ERROR] /Users/davsclaus/workspace/camel/components/camel-spring-redis/src/main/java/org/apache/camel/component/redis/processor/idempotent/RedisIdempotentRepository.java:[43,90] incompatible types: org.springframework.data.redis.core.RedisTemplate<capture#3 of ?,capture#4 of ?> cannot be converted to org.springframework.data.redis.core.RedisTemplate<java.lang.String,java.lang.String>
```

**Pull request merged**
