### PR TITLE
Migration to Jakarta EE 8

### PR DESCRIPTION
**Pull request by bvfalcon**
This pull request contains changes described in [CAMEL-17136](https://issues.apache.org/jira/browse/CAMEL-17136): dependencies are updated to their Jakarta EE 8 analogues then possible.
Current known limitations and notices:
1. Jetty 9 -> Jetty 10 migration: Websocket. Jetty 10 is compatible with Jakarta EE 8, but many Apache Camel components use Jetty 9 specific websocket realization. This components are now unchanged left. This components are [camel-ahc-ws](https://github.com/bvfalcon/apache-camel/commit/b4560b8d8920fc94e31a07e7653dde27eaf6d6b5?diff=unified#diff-d65c79e479029c9f001d7b8cfccafd01b672034226508d7d61b6b8d9e9eefaa5R77), [camel-atmosphere-websocket](https://github.com/bvfalcon/apache-camel/commit/b4560b8d8920fc94e31a07e7653dde27eaf6d6b5?diff=unified#diff-abff75be18147d2a8d817e47f92137de2c4008ea31a5f5f732f4e4694b6233bbR98), [camel-websocket](https://github.com/bvfalcon/apache-camel/commit/b4560b8d8920fc94e31a07e7653dde27eaf6d6b5?diff=unified#diff-ce3286f1bc9fcf984529bbc4b5fa9d242cb0d9512342bcbae30a1aaf1196898eR55). 
2. Jetty 9 -> Jetty 10 migration: Continuation. Jetty specific mechanism Continuation for asynchronous request processing is obsolete and was removed in Jetty 10. Component camel-jetty-common contains CamelContinuationServlet, which [actively uses Continuation](https://github.com/apache/camel/blob/main/components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/CamelContinuationServlet.java#L165). Within current changes Continuation [is replacing with AsyncContext](https://github.com/bvfalcon/apache-camel/commit/b4560b8d8920fc94e31a07e7653dde27eaf6d6b5?diff=split#diff-9d3da7276f4a6488c4828380dfc4dee0711e523e5ab41ddae8f91de9c482e5aaR167), but existent junit-tests not give a confidence in full correctness of this change.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Thanks for the PR. We need to align also camel-karaf repository to use the same deps

**Comment by bvfalcon** [comment]
> Thanks for the PR. We need to align also camel-karaf repository to use the same deps

Appropriated [changes are made](https://github.com/apache/camel-karaf/pull/151)

**Comment by orpiske** [comment]
@bvfalcon Is this still valid? 

c/c: @davsclaus @oscerd

**Comment by bvfalcon** [comment]
> @bvfalcon Is this still valid?

Yes, completely. I actualize periodically with last changes from branch "main" and hope, PR will be reviewed and merged sometime ;)

**Comment by orpiske** [comment]
> > @bvfalcon Is this still valid?
> 
> Yes, completely. I actualize periodically with last changes from branch "main" and hope, PR will be reviewed and merged sometime ;)

Thank you for clarifying ... I have some work ahead that may overlap with this, so I am trying to understand at what point we are :)

**Comment by orpiske** [comment]
I believe we can close this ticket by now, right @oscerd / @davsclaus ?

**Comment by oscerd** [comment]
Yes, I think so. There is also a PR on Karaf side probably, we should close there too.

**Comment by davsclaus** [comment]
yes it can be closed

**Pull request closed without merging**
