### PR TITLE
Update rabbitmq-component.adoc

### PR DESCRIPTION
**Pull request by ZodZekri**
i think there is problem queueargs is unkown parametre so  the example its worng 

queueargs => queue?args

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by ZodZekri** [comment]
fix example of conf rabbitMQ

**Comment by ZodZekri** [comment]
thanks for report but you are agree with me that is queue?args not queueargs !

**Comment by oscerd** [comment]
yes, it is. In the javadoc is correctly reported indeed.

**Comment by ZodZekri** [comment]
ok Thanks

**Comment by ZodZekri** [comment]
I will try to find solution to edit in javadoc  for fix it . thanks

**Comment by davsclaus** [comment]
Ah yeah the ? is removed from ascii doc as invalid chars are removed. So edit the example to just remove all the stuff before the ? and just say args.xxx=yyy

**Comment by oscerd** [comment]
Let me close this one @ZodZekri 

Please open a new PR if you'll find a solution.

**Pull request closed without merging**
