### PR TITLE
[CAMEL 13812] Break FAQ into separate component

### PR DESCRIPTION
**Pull request by aashnajena**
Refer to [this JIRA issue](https://issues.apache.org/jira/browse/CAMEL-13812)

Created a separate module for FAQs and done subsequent changes on camel-website repository to make a separate page for FAQs with its own index. The User Manual now has a link titles "Frequently asked Questions" to the index page of the FAQ module.

### CODE REVIEW

**Comment by djencks** [comment]
-1 the commits need to be squashed in order to provide a comprehensible view of what is proposed.
The comments claim to be putting the FAQs into a separate module, which I support, but the changesactually put them into a separate component, which I oppose strongly.

**Comment by zregvart** [comment]
We also need to be aware that the links to FAQ on `2.x` and `3.0.x` branches need to be updated otherwise the website build will fail when checking for broken links.

**Comment by aashnajena** [comment]
@djencks  @oscerd  I'm very sorry for the confusion. I'm a new contributor, so I wasn't clear about the difference between component and module. 

If I revert these changes, and make a separate module for faq as `/docs/user-manual/modules/faq`, will that be useful? Also, I think I'll have to through all the files under FAQ and check all the xref links, I think some of them point to files inside `user-manual/ROOT/pages`. 

@zregvart  I'm not sure what you mean in your comment. Are you referring to changing the xref links as well? Links which would eventually point to files in other modules?

Sorry for the confusion again. Please tell me how to proceed from here, and I will make all the required changes today.

**Comment by zregvart** [comment]
> @zregvart I'm not sure what you mean in your comment. Are you referring to changing the xref links as well? Links which would eventually point to files in other modules?

@aashnajena We build documentation from several branches, this is [an Antora feature](https://docs.antora.org/antora/2.2/component-versions/#branches-as-versions). There is one caveat, we build only the `latest` version of the user manual. So if we reorganize the user manual, which changes how pages are addressed using `xref` we also need to change those `xref` not only on the `master` branch but also on branches `2.x` and `3.0.x`, otherwise the links from those pointing to FAQ entries will be broken.

**Pull request closed without merging**
