### PR TITLE
Formatting and writing in camel-file docs

### PR DESCRIPTION
**Pull request by gsoto**
Bulleted lists inside the parameters table are not properly formatted and very hard to read (see 'fileExist' and 'readLock' parameters).
I just added cell styling by prepending an 'a' to the cell: https://asciidoctor.org/docs/user-manual/#cell
I also cleaned the descriptions for those parameters along with the formatting adjustments.

### CODE REVIEW

**Comment by gsoto** [comment]
Oh, I read the contributing guide but got the impression that that was the static part of the documentation. Sorry.
I see that the correction in formatting is not trivial. I'll have to check the doc generator later.
I'll open another PR with the writing corrections done in the annotations. Is that OK?

**Comment by oscerd** [comment]
Sounds good, but I think it won't be easy to do, especially on the javadoc side. Thanks a lot!

**Comment by zregvart** [comment]
We kinda do something like that, I wonder why it stopped working:

https://github.com/apache/camel/blob/8de21431e91a8fd1351c0d9a6ec65df6119e0f51/tooling/maven/camel-package-maven-plugin/src/main/resources/main-options.mvel#L5

If there's a newline in the description the cell gets the `a` prefix. I'm guessing this is not correctly formatted:

https://github.com/apache/camel/blob/5af1c628e089d4478bc8c959382080c1db139ca6/components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java#L1334-L1349

A very complicated but correct way of doing this would be to use HTML in JavaDoc and (since I _think_ cells in Asciidoc can't contain HTML) transform that HTML to Asciidoc in the `camel-package-maven-plugin`.

**Comment by gsoto** [comment]
I haven't dug into the site generator yet, but I see the same text is also inside a field annotation:

https://github.com/apache/camel/blob/5af1c628e089d4478bc8c959382080c1db139ca6/components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java#L112-L124

Is it possible that the generator is getting the description from there? The HTML tagging looks a bit weird in there.

**Comment by djencks** [comment]
Certainly an ‘a’ cell can contain a pre block, I think this is the usual way of including existing html in a page.  I’m not sure about a non-‘a’ cell.

David Jencks

**Pull request closed without merging**
