### PR TITLE
CAMEL-11292: Upgrade to scala 2.12.x

### PR DESCRIPTION
**Pull request by sinwe**

### CODE REVIEW

**Comment by davsclaus** [comment]
Hi there is compile error in camel-scala
```
[ERROR] /Users/davsclaus/workspace/camel/components/camel-scala/src/main/scala/org/apache/camel/scala/Preamble.scala:86: error: type mismatch;
[ERROR]  found   : Any
[ERROR]  required: Boolean
[ERROR]         } getOrElse false
[ERROR]           ^
[ERROR] one error found
```

**Comment by sinwe** [comment]
@davsclaus How did you compile? I did `mvn package -pl components/camel-scala -am -DskipTests` and it can compile

**Comment by davsclaus** [comment]
mvn clean install in that directory

**Comment by sinwe** [comment]
And here is what I got

```
[INFO] Results:                                                                                                                                                                                                                                                                 
[INFO]                                                                                                                                                                                                                                                                          
[ERROR] Errors:                                                                                                                                                                                                                                                                 
[ERROR] org.apache.camel.model.ModelSanityCheckerTest.testSanity(org.apache.camel.model.ModelSanityCheckerTest)                                                                                                                                                                 
[ERROR]   Run 1: ModelSanityCheckerTest.testSanity:83 » NoSuchMethod org.apache.camel.model.dat...                                                                                                                                                                              
[ERROR]   Run 2: ModelSanityCheckerTest.testSanity:83 » NoSuchMethod org.apache.camel.model.dat...                                                                                                                                                                              
[ERROR]   Run 3: ModelSanityCheckerTest.testSanity:83 » NoSuchMethod org.apache.camel.model.dat...                                                                                                                                                                              
[INFO]                                                                                                                                                                                                                                                                          
[WARNING] Flakes:                                                  
[WARNING] org.apache.camel.component.dataset.CustomDataSetTest.testUsingCustomDataSet(org.apache.camel.component.dataset.CustomDataSetTest)
[ERROR]   Run 1: CustomDataSetTest>TestSupport.runBare:58->testUsingCustomDataSet:54->ContextTestSupport.assertMockEndpointsSatisfied:352 dataset://foo?initialDelay=0 Received message count. Expected: <10> but was: <9>
```

I've just pulled from apache/camel:master, so I'm not sure if the master is green at this moment.

**Comment by davsclaus** [comment]
Here is how to preproduce your issue

Run from root folder to build the project locally

    mvn clean install -P fastinstall

When it comes to the scala module it should fail, if not run

    cd components/camel-scala 
    mvn clean install

**Comment by sinwe** [comment]
I tried the steps you provided but failed on the following
`[INFO] Camel :: ASN.1 ..................................... FAILURE [  0.100 s]`
with error
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1.1:java (generate-test-sources) on project camel-asn1: An exception occured while executing the Java class. null: InvocationTargetException: javax/xml/bind/DatatypeConverter: javax.xml.bind.DatatypeCo
nverter -> [Help 1]`
So I continued to the scala module and ran the steps you provided above and it's successful.

**Comment by sinwe** [comment]
@davsclaus Can you comment on the failed issue I have?

**Comment by davsclaus** [comment]
I dont know why you get that error, it works for everybody else

**Comment by davsclaus** [comment]
This PR causes camel-scala compile errors, closing now

**Pull request closed without merging**
