### PR TITLE
CAMEL-15751: Base improvement to provide access to stream observer in the camel exchange

### PR DESCRIPTION
**Pull request by rajasekharb**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Why opening another PR?

**Comment by rajasekharb** [comment]
Hi oscerd, had a series of changes as suggested by @dmvolod 
And in the process created a new local branch by mistake. Discussed with @dmvolod and gave this new PR.

**Comment by dmvolod** [comment]
Name of the PR should start from: CAMEL-15751:

**Review by dmvolod — APPROVED** [review]

**Comment by dmvolod** [comment]
@rajasekharb please also squash commits

**Comment by rajasekharb** [comment]
@dmvolod Thanks for the review. Have squashed the commits.

**Review by oscerd — APPROVED** [review]

**Comment by rajasekharb** [comment]
Thanks to @oscerd, @dmvolod for reviewing the changes.

**Pull request merged**
