### PR TITLE
[CAMEL-16736] Preserve captured headers during CSV Unmarshalling

### PR DESCRIPTION
**Pull request by mgenereu**
During the parsing of the CSV and `setHeader` is set to `new String[0]{}`, the headers are collected and beautifully validated.  These headers are then used in Map output but discarded on List output.  It would be nice to preserve that knowledge downstream in the Message header.

### CODE REVIEW

**Comment by davsclaus** [comment]
I think you should find another way, the header on camel-csv is when you want to specify the headers yourself as an input to the parser.

Instead you can find a way to always just output the headers to a message header in the output. And we can then introduce a new boolean option to turn this on|off.

**Comment by mgenereu** [comment]
@davsclaus So you're thinking a flag like `collectHeaderNames` on CsvDataFormat that would trigger this?  I'm confused on your second paragraph because that's what I'm doing now on the output.

**Comment by mgenereu** [comment]
Update the PR for a flag and updated the tests to match.  Please confirm this was what you were expecting for the interface.  Also, this now introduces some of the the Camel Autoconfiguration mechanisms that I'm not familiar with.  I updated the `components/camel-csv/src/generated/resources/org/apache/camel/dataformat/csv/csv.json` but I'm not sure what else needs to be updated after that.

**Comment by mgenereu** [comment]
Okay.  I updated everything to what I think it should look like but I can't figure out how to get the autogenerators to create the matching effects.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Yeah adding new options to a dataformat is more tricky as you need to add it into the core model. I will take a look at doing that, as it also requires a rebuild of dsl and whatnot.

**Pull request merged**
