### PR TITLE
CAMEL-12969: Adding ServiceReference Cache to prevent memory leak.

### PR DESCRIPTION
**Pull request by bobpaulin**

### CODE REVIEW

**Comment by bobpaulin** [comment]
@davsclaus Yes I would also like to avoid the background thread if possible.  The problem I ran into with removing the service reference on the unregister event is per the OSGi spec[1] (and in the Felix implementation) the event is fired at the beginning of the service being unregistered not at the end.  So it is possible that if the service is looked up after the event firing but before the service registration is invalidated and removed from Felix's registry [2] it could be re-cached without any other means to remove it other than stopping the camel context.  This gap between the unregistered event firing and the service actually being removed causes some problems for trying to invalidate the cache in a synchronous way.  The thread allows the code to check the ungetService return value which switches to false when the service is actually gone.  That allows the invalidation to work properly without locking but trades the extra resources that get allocated to the thread.

To your point of just applying the fix to the onContextStop being called.  I believe that could be applied separately which would improve the situation for users that are using the lookup calls conservatively.  Without the other parts of the patch (such as the cache reintroduction and invalidation strategy) the ConcurrentLinkedQueue$Node objects would continue to accumulate with each lookup call.  I'd prefer an approach that shields developers from the OSGi runtime and allows them make lookup calls as liberally as they can be with the  SimpleRegistry and JndiRegistry.

I agree with your point about complexity and I'm open to ideas to address the issue in a way that allows developers to use the Camel Registries in a uniform way.  Also sorry for the length of this note.  I wish I could have made it shorter but I think the issue is a bit tricky.

[1] https://osgi.org/specification/osgi.core/7.0.0/framework.api.html#org.osgi.framework.ServiceEvent
[2] https://github.com/apache/felix/blob/trunk/framework/src/main/java/org/apache/felix/framework/ServiceRegistry.java (specfically the unregisterService method.

**Comment by bobpaulin** [comment]
If it makes sense I can split this PR into 2 separate PRs.  One with the changes to the code that ensures the onContextStop gets called and another including the re-adding of cache and invalidation strategy.  It seems like the onContextStop change is uncontroversial while the cache and invalidation strategy will take require more consideration.  

In my application the onContextStop fix without the other changes will not be of much benefit to me.  But it may benefit others in the community that call the lookup method less frequently and stop the context more frequently.  

If there are suggestions to this pull request that would reduce the complexity to an acceptable level without adding race conditions and managing OSGi reference counting properly I'm happy to adapt this PR as well.  Let me know what approach makes the most sense.

**Comment by davsclaus** [comment]
@bobpaulin yeah it would be good to separate this into 2 PRs. The onContextStop is a good fix IMHO.

For the other I would like to get more feedback and ideas, eg if you have 100 Camel bundles in a JVM, then you now get 100 more JVM threads which is pita. 
Maybe the background thread can be created on-demand or on when camel context is being shutdown.

**Comment by bobpaulin** [comment]
Split this into CAMEL-12987.  Closing this PR will open a new one that does not include the CAMEL-12987 changes.

**Pull request closed without merging**
