### PR TITLE
doc: Add default camel metrics to micrometer component

### PR DESCRIPTION
**Pull request by gansheer**
# Description

Add the default Camel metrics on the micrometer component documentation. 

# Target

- [X] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [X] I checked that each commit in the pull request has a meaningful subject line and body.

- [X] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Comment by gansheer** [comment]
Some metrics might still be missing, if anyone see one missing please feel free to tell me.

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Hmm we should check what that message history metric really output

**Comment by gansheer** [comment]
> Hmm we should check what that message history metric really output

I did not actually manage to see this one, if you have any idea what it does don't hesitate.

**Comment by davsclaus** [comment]
|camel.message.history| Timer.Sample | Sample of performance of each node in the route when message history is enabled

**Comment by gansheer** [comment]
> |camel.message.history| Timer.Sample | Sample of performance of each node in the route when message history is enabled

Thanks, I added it (with timer instead of Timer.Sample).

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
|camel.exchange.event.notifier |gauge + summary | Metrics for message created, sent, completed, and failed events

**Pull request merged**
