### PR TITLE
CAMEL-20722 + CAMEL-20680 - re-enabled tests for CI

### PR DESCRIPTION
**Pull request by jvsingh**
# Description

Removed this set of tests for CI, after multiple clean runs during local testing. (Ref: Jira comments) 

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [CAMEL-20722](https://issues.apache.org/jira/browse/CAMEL-20722) and [CAMEL-20680](https://issues.apache.org/jira/browse/CAMEL-20680) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by orpiske — CHANGES_REQUESTED** [review]
LGTM, but marking as request changes because I want to verify how the run on a CI environment before re-enabling them.

**Comment by orpiske** [comment]
I triggered the tests. It may take a few hours for everything to complete. Once completed, I'll share the results here.

**Review by orpiske — APPROVED** [review]
Seems to be OK. Let's merge and see how it goes on the ASF CI.

**Review by orpiske — CHANGES_REQUESTED** [review]
Ahh, oops. Not yet. 

@jvsingh Please, can you fix the formatting of the files? 

Just run `mvn verify` on the `camel-kafka` directory and commit the formatted files, please.

**Review by davsclaus — APPROVED** [review]

**Comment by jvsingh** [comment]
Attempting my local builds with MVND_OPT env variable set up to the same value as the failing job

**Comment by orpiske** [comment]
This is the failure:

| Failed Test | Duration | Failure Type |
| --- | --- | --- |
| org.apache.camel.component.kafka.integration.KafkaBreakOnFirstErrorReleaseResourcesIT.testCamel20563TestFix | 8.014s | FAILURE |

**Comment by orpiske** [comment]
[incremental-test.log.zip](https://github.com/apache/camel/files/15224408/incremental-test.log.zip)

Test log

**Comment by jvsingh** [comment]
> This is the failure:
> 
> Failed Test	Duration	Failure Type
> org.apache.camel.component.kafka.integration.KafkaBreakOnFirstErrorReleaseResourcesIT.testCamel20563TestFix	8.014s	FAILURE

Got an idea about this. Pushing soon. 
Spotted  a second one too in the logs you shared:
```
[ERROR] org.apache.camel.component.kafka.integration.KafkaConsumerFullIT.kafkaMessageIsConsumedByCamelSeekedToBeginning -- Time elapsed: 21.05 s <<< FAILURE!
java.lang.AssertionError: mock://result Received message count. Expected: <5> but was: <0>
```

**Comment by jvsingh** [comment]
> [incremental-test.log.zip](https://github.com/apache/camel/files/15224408/incremental-test.log.zip)
> 
> Test log

Spotted two failures. Committed two proposed fxes:
 1)  check more specific thread name to avoid clashes with unrelated kafka heartbeat threads
 2) Make topic name from test-full to something more unique less likely to clash with other tests running in parallel

**Comment by davsclaus** [comment]
@orpiske does this look good to you

**Review by orpiske — APPROVED** [review]
Looking good now. Let's merge. Thanks!

**Pull request merged**
