### PR TITLE
Updating Jakarta El to 3.0.4 (#11370) (#11371)

### PR DESCRIPTION
**Pull request by coheigea**
Backporting CVE fix for https://github.com/advisories/GHSA-v6w3-2prq-h95f

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by coheigea** [comment]
@oscerd Any idea what's going on here with the build?

**Comment by oscerd** [comment]
`"Caused by: org.apache.maven.wagon.TransferFailedException: transfer failed for https://repository.jboss.org/nexus/service/local/repositories/thirdparty-releases/content/io/nessus/weka/nessus-weka-api/1.0.1/nessus-weka-api-1.0.1.pom, status: 503 Service Unavailable"`

**Comment by oscerd** [comment]
But it's working now testin from local, I restarted the jobs.

**Comment by coheigea** [comment]
thanks @oscerd

**Pull request merged**
