### PR TITLE
CAMEL-9285 - controlbus - Allow to grab current route id so you can control current route easier

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you add some documentation about `current` in the endpoint class, for the routeId option.

**Comment by lburgazzoli** [comment]
Done, if ok with you, I will amend confluence too

**Comment by davsclaus** [comment]
Yes welcome to update the wiki

**Comment by lburgazzoli** [comment]
I will once merged so wiki and code are in-sync

**Comment by davsclaus** [comment]
merged now

**Comment by lburgazzoli** [comment]
wiki updatet

**Pull request closed without merging**
