### PR TITLE
Enable camel-kafka test suites execution on ppc64lle

### PR DESCRIPTION
**Pull request by Balavva-Mirji**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by Balavva-Mirji** [comment]
Note: quay.io/strimzi/kafka:latest-kafka-3.5.1 image has ppc64le support now.
Code reference: https://github.com/apache/camel/blob/70614e63c1d0a5cb5b46ba23200dd17ae7113ab6/test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java#L26

**Comment by orpiske** [comment]
Thanks for your contribution, @Balavva-Mirji. 

We have a lot of failures in Kafka on PPC64 LE at the moment. Is this aimed at fixing those?

i.e.: https://ci-builds.apache.org/job/Camel/job/el/job/main/466/testReport/

**Comment by Balavva-Mirji** [comment]
@orpiske Yes, this image will fix most of the kafka failures on ppc64le. I have validated it locally, couple of assertion failures are there. Also I observed those are fails on x86 too sometimes.

**Review by davsclaus — APPROVED** [review]

**Comment by orpiske** [comment]
> @orpiske Yes, this image will fix most of the kafka failures on ppc64le. I have validated it locally, couple of assertion failures are there. Also I observed those are fails on x86 too sometimes.

Thank you!!!

**Review by orpiske — APPROVED** [review]

**Pull request merged**
