### PR TITLE
CAMEL-6950 camel-sjms: Lacks reconnection logic in case of exception

### PR DESCRIPTION
**Pull request by globalbus**
Two tests of reconnect logic.

Reconnect for Producer is really simple, because it's based on GenericObjectPool capabilities. Providing session validation and testOnBorrow is enough to seamless reconnect.

Consumer is much worse case and I'm not so very proud about this solution. Because objects in pool are never pooled, there is no chance to test them on borrow. I'm catching exception on JMS connection and I'm doing a full reset of whole consumer (stop/start on executor). I'm opened for better ideas, that will probably need a small refactoring of MessageListener's creation.

### CODE REVIEW

**Comment by davsclaus** [comment]
Ah yeah the consumer side is always harder. spring-jms has a lot of logic for dealing with this. 

So the restart on camel consumer can maybe be improved as you say if we can isolate the logic so it can do a jms connection / consumer refresh. And also if the exceptio keeps happenig then you would need to have some delay between. sprig has 5 sec i think

**Comment by globalbus** [comment]
I did second attempt.
Because consumers could be created on different connections, flushing whole consumer pool on each error couldn't be a good idea. The one connection could be closed by network and another ones could be still available.
Now "pool" is just a WeakMap, with Connections as keys and list of consumers created on each connection as value.

When error happens on connection, all consumers on this connection will be destroyed and removed from map. After that, task to refill pool will be scheduled, with configurable backoff policy.

**Comment by davsclaus** [comment]
Using `Backoff` as endpoint configuration option is likely a bit too advanced. Can we start with just a normal long for setting a delay value. This makes configuring this much easier in endpoint strings.

Also make the options configurable on the component level so you can configure this once and then all endpoints inherit this settings (they can override if they desire)

**Comment by davsclaus** [comment]
Great work we are almost there

**Comment by globalbus** [comment]
@davsclaus I forgot about uri compatibility, I'm using only java api on daily basis.
I could do a improvement in this area. For this repo, changes flow should be like "jira issue first, then PR", right?

Anyway, I only checked this with activemq broker. I'm wondering how this will work with artemis and advanced features, like session re-attachment. Artemis has own built-it mechanism to deal with dead connections. I must do some investigation. For right now I only can advice that both mechanisms (artemis built-in and sjms reconnect) shouldn't be used at once at the moment.

**Comment by davsclaus** [comment]
Oh we implemented this so it was in 3.1.0 release as just a simple delay as number. 

You are surely welcome to do more research and also to do PRs agains the sjms documentation (the adoc file in src/main/docs)

**Pull request merged**
