### PR TITLE
[CAMEL-16108] The S3 metadata is included in the Exchange as a Header

### PR DESCRIPTION
**Pull request by vilmosnagy**
- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by vilmosnagy** [comment]
@oscerd Could you help me where should I write the documentation for this? And how?

As I've searched for examples in the project I've found the following:
 - the `CamelAwsS3BucketName` is documented in the `generated/docs` folder. Should I document this header in that file as well? Then why it's in the `generated` folder?
 - and I can't find any documentation for the `CamelAwsS3DowloadLinkExpirationTime` header (ps.: there's a typo in that header)

**Comment by oscerd** [comment]
@vilmosnagy all the documentation is in the src/main/docs of the componet, the src/generated stuff is auto-regenerated when you build the component. You can add the documentation in src/main/docs, there is only one adoc file.

For the header I think we need to fix the error and add a note in the migration guide.

**Review by oscerd — APPROVED** [review]

**Comment by vilmosnagy** [comment]
@oscerd  Thanks for the clarification, I've pushed the docs.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
Thanks

**Pull request merged**
