### PR TITLE
fix doc problem, change 'turn of' to 'turn off'

### PR DESCRIPTION
**Pull request by EvanMi**
# Description

fix doc problem, change 'turn of' to 'turn off'

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
You need to change the java source code, do a git grep to find where in the source code

**Comment by EvanMi** [comment]
> You need to change the java source code, do a git grep to find where in the source code

My git grep results show the keyword only appear in .json and .xsd,  and they are all generated.  And i find the field in org.apache.camel.processor.SendDynamicProcessor , but found no docs.

**Comment by davsclaus** [comment]
This PR is broken, do you mind start all over and from latest code from main branch

**Comment by EvanMi** [comment]
> This PR is broken, do you mind start all over and from latest code from main branch

sure

**Pull request closed without merging**
