### PR TITLE
Camel 19234: avoid ambiguity when looking up a bean 

### PR DESCRIPTION
**Pull request by louisa-fr**
Issue: https://issues.apache.org/jira/browse/CAMEL-19234

This code was a suggestion from the camel-zulip-chat, where it wasn't sure, whether it would have any side effects, so we thought we would open a PR with it to trigger discussion as it would help unblock an issue in the quarkus-artemis project :) 

Zulip-Chat: https://camel.zulipchat.com/#narrow/stream/257302-camel-quarkus/topic/Resolution.20of.20.40Identifier.20dependency

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
There is already mandatoryLookup that takes name and type you should use instead. This method is for converting to the type as it also states in the javadoc.

**Comment by turing85** [comment]
@davsclaus I am not quite sure this is possible. We do not call this part directly; it is called through the runtime, especially in the `quarkus-camel` extension. See [the corresponding JIRA issue](https://issues.apache.org/jira/browse/CAMEL-19234).

If it is possible, can you give us a pointer where we have to adjust the corresponding call?

**Comment by turing85** [comment]
No results. The stack trace in https://github.com/apache/camel-quarkus/issues/4725 indicates that it comes from some implementation of the `AbstractCamelContext` (-> `JmsComponent`) -> `DefaultComponent` -> `EndpointHelper` -> `CamelContextHelper`

**Comment by davsclaus** [comment]
Here is a PR with a fix
https://github.com/apache/camel/pull/9811

Try this on CEQ

**Comment by louisa-fr** [comment]
@turing85 has verified that https://github.com/apache/camel/pull/9811 fixes the issue, thanks for working on it ! I'll close this PR then.

**Pull request closed without merging**
