### PR TITLE
Implement consumer priority in camel

### PR DESCRIPTION
**Pull request by rnetuka**
Issue: https://issues.apache.org/jira/browse/CAMEL-16008

Provide a way or option to implement consumer-priority in _camel-amqp_ and _camel-jms_ components.
https://activemq.apache.org/components/artemis/documentation/latest/consumer-priority.html

### CODE REVIEW

**Comment by davsclaus** [comment]
This seems to be an ActiveMQ only feature and therefore we cannot have it as first class in the component as its for general JMS.

There is the camel-activemq component where such ActiveMQ only features can be implemented.

**Comment by rnetuka** [comment]
I can move the changes to camel-activemq, but this needs to work also with ActiveMQ Artemis. Is there any special component for Artemis?

**Comment by davsclaus** [comment]
We do already have an artemisStreamingMode so it may be okay to rename this to artemisConsumerPriority, then it indicate its only for this broker.

However one day it may be worth to have camel-artemis component that has only those additional options.

**Comment by davsclaus** [comment]
So I am merging this and updating it. Then later we can consider the camel-artemis

**Pull request closed without merging**
