### PR TITLE
[CAMEL-17844] Handle FunctionalInterface (lambas) in BeanInfo

### PR DESCRIPTION
**Pull request by bjornomy**
This PR aims to fix a regression regarding FunctionalInterfaces in BeanInfo.

* let BeanInfo ignore methods from synthetic classes (proxies and lambdas) when choosing what method to call on a bean
* remove BeanInfoTypeResolver, as it's not longer necesary
* add a doc snippet on `@FunctionalInterface` usage

- [X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [X] Each commit in the pull request should have a meaningful subject line and body.
- [X] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [X] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

### CODE REVIEW

**Comment by bjornomy** [comment]
Is there a way to automatically format the source in such a way that `sourcecheck` passes?

**Comment by oscerd** [comment]
> Is there a way to automatically format the source in such a way that `sourcecheck` passes?

If you run a full build the code will autoformat.

**Comment by davsclaus** [comment]
Also need to test that camel-karaf would still work, as it has special case for beans, the interface that was deleted was in use by camel-karaf, so we need to update its source code also

**Comment by essobedo** [comment]
> Is there a way to automatically format the source in such a way that `sourcecheck` passes?

What I personally do for this is to launch the formatter (`formatter:format`) when I build, so I end up with the next command `mvn formatter:format clean install -Psourcecheck`

**Comment by davsclaus** [comment]
Your changed with checking for synthetic later could potentially make no need for the camel-bean-osgi module which we then can remove - I am testing this now

**Comment by davsclaus** [comment]
Thanks for the PR I have merged it manually

**Pull request closed without merging**
