### PR TITLE
CAMEL-20250: resume after restart of Kinesis consumer

### PR DESCRIPTION
**Pull request by abendt**
# Description

While trying to implement a resume strategy for a Kinesis consumer I ran into some issues that prevented me from implementing a strategy:
* the shardId is not available in the exchange. The shardId is required to properly configure the GetShardIteratorRequest in the resume scenario ([AWS doc](https://docs.aws.amazon.com/streams/latest/dev/developing-consumers-with-sdk.html#kinesis-using-sdk-java-get-data-shard-iterators))
* the KinesisResumeAdapter API does not allow to pass in the shardId. 
* When consuming multiple shards the KinesisResumeAdapter will potentially be used by multiple threads concurrently. With the current API, this could cause concurrency issues

This PR proposes changes for the mentioned problems and provides a KinesisResumeStrategy implementation.
 

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

https://issues.apache.org/jira/browse/CAMEL-20250

Mailing list: 
* https://lists.apache.org/thread/sc6oks5jckcbj19t06chmfpm6dpwt60t
* https://lists.apache.org/thread/6zfs1ppz5bdsvlkyfjhftn7pfjnm9477

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
LGTM but @orpiske should take a look too

**Comment by davsclaus** [comment]
There are uncommitted changes
HEAD detached at pull/12462/merge
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	components/camel-aws/camel-aws2-kinesis/src/generated/resources/META-INF/services/org/apache/camel/kinesis-resume-strategy

**Comment by davsclaus** [comment]
The PR has some changes not committed so the PR cannot automatic be tested, can you take a look and add those files in this PR

**Comment by orpiske** [comment]
Thanks for your contribution. I am on PTO... I will take a look tomorrow.

**Comment by abendt** [comment]
I have committed the missing files

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks for your contribution!!!

Overall it looks good to me. As this seems to cause the Kinesis resume to not work correctly, I created the ticket CAMEL-20250 so we can track it.

Once merged, we also need to [review the example](https://github.com/apache/camel-examples/blob/main/resume-api/resume-api-aws2-kinesis). 

For now, I am only putting as "request changes" in order to ask for the commit message to be adjusted to mention the ticket I created (i.e.: just adjust the commit message to be something like "CAMEL-20250: the description of the changes" .

**Comment by abendt** [comment]
@orpiske i have added the ticket# to the commit message

**Review by orpiske — APPROVED** [review]
Thanks @abendt !

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
