### PR TITLE
CAMEL-10019 - Consider sortBy header when performing findOneByQuery operation

### PR DESCRIPTION
**Pull request by kb1ca**
There is a often a requirement to fetch the min/max record from Mongo based on a particular field. Typically the operation is performed using syntax similar to:
```
 db.collection.find().sort({_id: -1}).limit(1)
```
or
```
 db.collection.findOne({$query:{},$orderby:{_id:-1}})
```
As implemented the findOneByQuery operation currently ignores the sortBy header. This trivial patch passes sortBy to the sort parameter of findOne(), if set. 

Helpfully, if the projection parameter is null findOne() returns all fields, so the state of fieldFilter is not checked before passing when the sortBy header has been set.

### CODE REVIEW

**Comment by davsclaus** [comment]
This branch has merge conflicts. Wonder if you can try to fix this?

**Comment by kb1ca** [comment]
It seems this component just underwent a substantial change... I can rewrite the patch to apply and resubmit, but would you mind if I also submitted it against 2.17.x so it can get into the next minor update?

**Comment by davsclaus** [comment]
Yeah sure 2 PRs - one for master, and another for 2.17.x

**Comment by anoordover** [comment]
@kb1ca, I also introduced a MongoDB2 component because of performance issues in MongoDB version 3. When my PR gets pulled, could you also apply your patch in this component. See https://jira.mongodb.org/browse/JAVA-2110

**Pull request closed without merging**
