### PR TITLE
RFC: adjustments to the contributing guide

### PR DESCRIPTION
**Pull request by orpiske**
The recent attacks to open source projects, by malicious actors trying to obtain privileged access to the repositories and injecting malicious code has been pretty frightening. Just recently we had an influx of short-lived accounts (just a few days old and likely fake) trying to submit "cleanups" to the code base without any discussion with the community. 

I think it would be important for us to clarify what we expect from anyone contributing to Apache Camel and what other committers should look when reviewing contributions. 

Please note that many of the additions to the document are things that we already expect, but have never been formalized before. 

I have discussed with a few others about this (@davsclaus, @oscerd) and I think it's time to bring it to the community for review and discussion.

Please review and share your thoughts.

Note: keeping it as a draft for a while until we receive some community feedback.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Review by squakez — APPROVED** [review]
Good one to have some formality explanation.

**Review by jvsingh — APPROVED** [review]
All edits sound very reasonable

**Comment by orpiske** [comment]
Ok, it's been a while without comments. I think we can merge.

**Comment by orpiske** [comment]
Thanks everyone for the comments!

**Pull request merged**
