### PR TITLE
CAMEL-12317: Fix naming convention for header constants

### PR DESCRIPTION
**Pull request by vignesh-manel**
# Description

Fixed naming convention

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
We did you see that very shothand naming convention ?

**Comment by vignesh-manel** [comment]
The aws sdk client itself uses shorthand convention https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sfn/SfnClient.html

So I thought header constants will have a consistent and short names, just a suggestion, if we could use this, as the previous names which were used in code were not consitent

**Comment by vishalsingh2972** [comment]
is this issue still open @davsclaus ?

**Comment by davsclaus** [comment]
The naming convention in Camel is for headers to have their component name as prefix.

So if you wanted to use `sfn` then the component should been named `camel-aws2-sfn`

**Pull request closed without merging**
