### PR TITLE
CAMEL-12599: Upgrade to CXF 3.2.5

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by davsclaus** [comment]
@ppalaga did you really compile and test camel-cxf after this upgrade? 

I had to revert it
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project camel-cxf: Compilation failure
[ERROR] /Users/davsclaus/workspace/camel/components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java:[1238,64] error: incompatible types: Map<String,Object> cannot be converted to ClientImpl.ResponseContext
```

**Comment by ppalaga** [comment]
> did you really compile and test camel-cxf after this upgrade?

No, I just wanted to test the review process. Is there no CI that would uncover such an apparent mistake?

**Comment by oscerd** [comment]
A build may takes 4 hours for a single PR, that's why there is not a PR job. Usually we build what is needed locally and test it.

**Comment by ppalaga** [comment]
There is even not a strongly simplified smoke build?

**Comment by oscerd** [comment]
No. Any update may breaks stuff in different places: Karaf feature, tests, itests, spring-boot, documentation, code style.. A smoke build doesn't solve the problem. We can add a PR job, but I don't think is feasible to wait 4 hours.

**Comment by ppalaga** [comment]
Please feel free to take CAMEL-12599 over if you are interested to get it in quickly. I will not have time to take care in the coming days.

**Pull request merged**
