### PR TITLE
Use Camel SSLContext in CXF-endpoint

### PR DESCRIPTION
**Pull request by anoordover**
Can you provide feedback on this "solution" for CAMEL-9046.
I tried to add a chain of CxfEndpointConfigurers to be able to set the conduit in a generic manner.
Can you take a look at the inner NullCxfEndpointConfigurer.
Should there be a singleton (public static final instance) in some class?
Should the same kind of solution be used for the CxfRsEndpoints?
Should new Configurer classes be introduced e.g. CxfRsEndpointConfigurer?

### CODE REVIEW

**Comment by davsclaus** [comment]
Good work.

Can you keep the existing unit tests as-is and then create a new unit test about using the SSL configuration.

**Comment by anoordover** [comment]
Unittest added.
Is it ready to be pulled?
Should we also introduce a CxfRsEndpointConfigurer in via a new Jira-issue?

**Comment by davsclaus** [comment]
Yeah good idea about a new JIRA for the RS part of camel-cxf.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
