### PR TITLE
CAMEL-20202: Read Azure BinaryData as stream

### PR DESCRIPTION
**Pull request by jono-morris**
# Description

Prefer the toStream method over the toString method on the BinaryData

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — CHANGES_REQUESTED** [review]
you should not create uow and release uow when creating the exchange. Also this code seems to read the entire stream into memory, which is not much improved over the old code.

**Comment by oscerd** [comment]
Maybe look at AWS SQS

**Review by oscerd — APPROVED** [review]

**Comment by jono-morris** [comment]
Thanks for that. Let me investigate further.

**Comment by jono-morris** [comment]
Updated to pass the InputStream from the Azure BinaryData object to the exchange body.  Also added a `SynchronizationAdapter` to close the stream when the exchange is complete similar to what is done in `AWS2S3Consumer`.  That method also has an `autocloseBody` option, would it make sense to also include that option here?

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
The `autocloseBody` is related to `includeBody` option in AWS. I dont think we have those in Azure. And would that make sense. If you have includeBody=false, then you just get the metadata about the file. But nevermind that would be another JIRA and another PR.

**Pull request merged**
