### PR TITLE
CAMEL-9416 - Creation of camel-mllp component

### PR DESCRIPTION
**Pull request by hqstevenson**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you fix the checkstyle erros, you can see here how to run with that\
http://camel.apache.org/building

    mvn -Psourcecheck clean install

**Comment by hqstevenson** [comment]
The previous commit had the wrong email address (from my previous employer) - but the commit is from me.  I've corrected my ~/.gitconfig.  Sorry for any confusion this may have caused.

**Comment by davsclaus** [comment]
We cannot merge and rebase this on the master branch, there is merge conflicts. We really would like to do so, so we keep our git tree clean and easy. 

As this is a monster PR, I wonder if you can rebase or do a new PR without 70+ commits which we can apply cleanly.

For example you have git commits that want to change the root pom.xml gitignore and other files which are not the same files as yours.

eg I suggest to try a new PR and then just do 1 or a few commits for the new component, and another commit for the changes in the various camel pom.xml files to add the component. Then we can apply merge and rebase this on the camel source code.

**Comment by hqstevenson** [comment]
Closing this PR - will open a new one with only a few commits.

**Pull request closed without merging**
