### PR TITLE
CAMEL-15120: camel-jslt - Use headers as variables in the jslt component

### PR DESCRIPTION
**Pull request by jflabatBCSS**

### CODE REVIEW

**Comment by davsclaus** [comment]
a)
I think this needs an option to turn on|off - and be off by default. As its a potential vulnerability as your extract all headers (and some may not be desired).

b)
the component could support HeaderFilterStrategy to filter out unwanted (and often internal hedaers). And ppl can plugin custom filters.

**Comment by davsclaus** [comment]
Argh we could maybe make camel-jslt a bit similar to the other templating components, such as velocity that creates the headers map ala

Map<String, Object> variableMap = ExchangeHelper.createVariableMap(exchange, isAllowContextMapAll());

Then it has prefix headers.xxx. Then you use that in the template and know its from a header.
And yeah would need to still do the json node mapping. But what happens if the header type is not json friendly then the mapper would throw an exception. So there need to be some way of avoiding this / skipping bad headers by default etc.

**Comment by jflabatBCSS** [comment]
This is my new proposition.

I followed the usage of "Map<String, Object> variableMap = ExchangeHelper.createVariableMap(exchange, isAllowContextMapAll());" but I only applied it for headers and exchange.properties since the other values seem not to be relevant for jslt transformation (The body is already the context of the jslt and the other values can provoke infinite recursion and some values are replicated, e.g. headers and properties for exchange). 

I made an additional step for converting the maps since there can be values that could not be converted with Jackson (e.g. infinite recursion in the given value). Such values are simply denied in the converted maps (for headers and exchange.properties) instead of denying the whole map.

**Comment by davsclaus** [comment]
Great work, can you fix the CS issue by running

mvn compile -P sourcecheck

**Comment by jflabatBCSS** [comment]
> 
> 
> Great work, can you fix the CS issue by running
> 
> mvn compile -P sourcecheck

yes, it's now ok

**Comment by davsclaus** [comment]
Btw would you mind updating the jslt documentation about this with headers? you can find the docs in the src/main/docs folder

**Comment by jflabatBCSS** [comment]
> 
> 
> Btw would you mind updating the jslt documentation about this with headers? you can find the docs in the src/main/docs folder

Sure, should I supply another issue and pull-request ?

**Comment by davsclaus** [comment]
Yeah a new PR is fine (no JIRA needed)

**Pull request merged**
