### PR TITLE
CAMEL-10338 - Fix formatting in CDI-OSGI example readme

### PR DESCRIPTION
**Pull request by johnpoth**
https://issues.apache.org/jira/browse/CAMEL-10338

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks @johnpoth . I'll merge ASAP :-)

**Comment by johnpoth** [comment]
Very reactive :100: Thanks @oscerd !

**Comment by oscerd** [comment]
Merged :-) Thanks!

**Comment by oscerd** [comment]
Can you close the PR? :-)

**Pull request closed without merging**
