### PR TITLE
Fix bug for https://github.com/apache/camel/pull/10400

### PR DESCRIPTION
**Pull request by EvanMi**
For detail see https://github.com/apache/camel/pull/10400, this PR fixed a bug.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@EvanMi can you check camel-undertow, it has failure with RestUndertowHttpGetCorsTest

**Comment by EvanMi** [comment]
@davsclaus I found the problem out, the reason is that /users/{a}/b?restrickedMethod=GET&OPTIONS /users/{a}/b?restrickedMethod=POST&OPTIONS , these two routes a all match when options request coming in.Should i treat OPTIONS as special? Or an good advice?

图片

**Comment by EvanMi** [comment]
> @davsclaus I found the problem out, the reason is that /users/{a}/b?restrickedMethod=GET&OPTIONS /users/{a}/b?restrickedMethod=POST&OPTIONS , these two routes a all match when options request coming in.Should i treat OPTIONS as special? Or an good advice?
> 图片

图片

**Comment by EvanMi** [comment]
@davsclaus with this condition add, test passed
图片

**Comment by davsclaus** [comment]
Yeah options is _special_

**Pull request merged**
