### PR TITLE
CAMEL-11181 Replace gmaven with gmavenplus Maven plugin

### PR DESCRIPTION
**Pull request by zregvart**
This replaces the use of `gmaven` plugin with `gmavenplus` plugin.

### CODE REVIEW

**Comment by oscerd** [comment]
+1, LGTM :-)

**Comment by zregvart** [comment]
Thanks @oscerd I'll just wait if @dmvolod has time to review this as well, seems trivial enough...

**Comment by dmvolod** [comment]
Thanks @zregvart , looks good!

**Comment by zregvart** [comment]
Thank you @oscerd and @dmvolod 👍

**Pull request closed without merging**
