### PR TITLE
Separated PGPDataFormat into camel-cypto-pgp

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://issues.apache.org/jira/browse/CAMEL-20922

The PGPDataFormat is extracted to the component `camel-crypto-pgp`.

# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
After this we need to add a SB starter for this, and regen the old starter

**Comment by JiriOndrusek** [comment]
@davsclaus Do you know why the CI failed?
(I downloaded all logs from the CI and I can see only error in  line without seeing what is wrong :
```
2024-06-26T07:40:27.0675695Z WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2024-06-26T07:40:27.0693104Z [main] WARN org.jline - Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
2024-06-26T07:43:24.6590782Z Processing surefire and failsafe reports to create the summary
2024-06-26T07:43:25.6438654Z ##[error]Process completed with exit code 1.
````
)

**Comment by davsclaus** [comment]
No but the CI can sometimes fail with this - i think it may use maven daemon that can crash. We should just use maven wrapper always then we can 100% control it via the .mvn folder

**Comment by davsclaus** [comment]
SB is done

**Pull request merged**
