### PR TITLE
CAMEL-14321: camel-osgi-activator support pre-startup routebuilders

### PR DESCRIPTION
**Pull request by bobpaulin**

### CODE REVIEW

**Comment by oscerd** [comment]
Merged on master. @bobpaulin thanks, when you have time, can you double check the IT test with JDK11? it is failing consistently on CI.

**Comment by bobpaulin** [comment]
Hi @oscerd I'm able to reproduce locally on Java 11.  Looks like it's something due to the removal of the JavaEE jars occurred between 8 and 11.  Will need to tweak the karaf settings to make sure those Jars are available to the runtime.

**Comment by bobpaulin** [comment]
Looks like the issue is actually PAX-EXAM https://github.com/ops4j/org.ops4j.pax.exam2/pull/87 .  Once this is fixed in the karaf container these tests pass as expected.  @jbonofre @oscerd

**Comment by oscerd** [comment]
Thanks for the heads up :-)

**Comment by jbonofre** [comment]
@bobpaulin it works fine with Java11 if you extend KarafTestSupport. I will fix that, just at least adding the starting options for Java11: https://github.com/apache/karaf/blob/master/itests/common/src/main/java/org/apache/karaf/itests/KarafTestSupport.java#L184

I will work on OSGi part (as I think some cleanup would be welcome).

**Pull request closed without merging**
