### PR TITLE
CAMEL-17941 - Dropbox: long-lived access tokens are retired, must use…

### PR DESCRIPTION
**Pull request by rhuan080**
Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/main/CONTRIBUTING.md

Dropbox does not support the long-lived token anymore. Now, the refresh token should be used.

https://dropbox.tech/developers/migrating-app-permissions-and-access-tokens

### CODE REVIEW

**Review by orpiske — CHANGES_REQUESTED** [review]
Thanks for the contribution! I left some comments about (minor) issues/improvements.

**Comment by orpiske** [comment]
As for the test failure, it's related to formatting:

```
[ERROR] Failed to execute goal net.revelc.code.formatter:formatter-maven-plugin:2.17.1:validate (validate) on project camel-dropbox: File '/home/runner/work/camel/camel/components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerMoveIT.java' has not been previously formatted.  Please format file and commit before running validation! -> [Help 1]
```

I think `mvn -Pformat,fastinstall install` will format it for you.

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by rhuan080** [comment]
@orpiske updated to use the ObjectHelper. Thank you! :-)

**Review by orpiske — APPROVED** [review]
Thanks @rhuan080

**Pull request merged**
