### PR TITLE
Use String#replace instead of String#replaceAll where possible for im…

### PR DESCRIPTION
**Pull request by PascalSchumacher**
…proved performance.

### CODE REVIEW

**Comment by davsclaus** [comment]
replace is also internally using a regexp but in a simpler mode, so yeah it ought to be a bit faster.
But we could pre-compile the patterns, and do what the replace does in String.

The org.apache.camel.util.StringHelper#replaceAll is also simple and fast.

**Comment by davsclaus** [comment]
But yeah String.replace should be the best as the JDK gets faster and faster, for example as posted on SO
https://stackoverflow.com/questions/16228992/commons-lang-stringutils-replace-performance-vs-string-replace

**Comment by davsclaus** [comment]
There are some more places in core where you can change replaceAll to replace, its where the replaced string is just literal text.

**Comment by davsclaus** [comment]
Ah it looks you have got them all, thanks

**Comment by PascalSchumacher** [comment]
> String.replace should be the best as the JDK gets faster and faster,

Yes, I checked the source code of OpenJDK 11 where `String#replace` is implemented without using a regex.

>Ah it looks you have got them all, thanks

The only usages left should be in tests.

**Pull request merged**
