### PR TITLE
camel-milo: enabled connection caching again.

### PR DESCRIPTION
**Pull request by attrobit**
- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Wasn't this removed?

**Comment by attrobit** [comment]
> Wasn't this removed?

Yes, but i down know why. For me the caching are useful and for my usecases necessary. I will have round about 400 routes to the same OPC-UA server. I think it is not a good idea to have for each route a separate connection. 

The difference to the old version is that the connection are not created on component start. Now the connection instance are later careted on consumer or producer start.

**Comment by attrobit** [comment]
Currently the connection get closed when component stops. But i think that is to late. I want to close the connection when the routes stops.

How does the component recognizes when all routes stops?

**Comment by davsclaus** [comment]
There is a ticket to make this better and similar to messaging components where there is a SPI
https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16094

**Pull request closed without merging**
