### PR TITLE
Integration compatibility with FCM

### PR DESCRIPTION
**Pull request by allancth**
Connection configuration for FCM parameters are referenced from [here](http://www.grokkingandroid.com/xmpp-server-google-cloud-messaging) and [here](http://javapapers.com/android/google-cloud-messaging-gcm-ccs-with-xmpp/).

### CODE REVIEW

**Comment by oscerd** [comment]
Please open your PR against master. We eventually backport it on other branches and please run also mvn -Psourcecheck to fix codestyle error if existing. Thanks.

When you're ready close this one and open against master. Thanks.

**Comment by allancth** [comment]
Noted.

**Comment by volodymyrrudyi** [comment]
@allancth Thanks for your work! Do you know if this changed was merged to the Apache Camel?

**Comment by allancth** [comment]
@volodymyrrudyi It is in 2.19 snapshot. [This](https://github.com/apache/camel/pull/1243) is the PR, and Jira [CAMEL-10423](https://issues.apache.org/jira/browse/CAMEL-10423). Cheers.

**Pull request closed without merging**
