### PR TITLE
CAMEL-14734 : camel-hbase - Upgrade to newer 2.x release

### PR DESCRIPTION
**Pull request by manonthegithub**

### CODE REVIEW

**Comment by manonthegithub** [comment]
ref: CAMEL-14734

**Comment by manonthegithub** [comment]
should I correct that? (stylecheck error, but in other project)
[ERROR] /home/runner/work/camel/camel/components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java:41: Wrong order for 'com.fasterxml.jackson.databind.JsonNode' import. [ImportOrder]

where is the actual build server where you do verification of builds? am I supposed to look at it?

**Comment by oscerd** [comment]
No, this is from a different commit. 

The github action here just run a full source check to report codestyle violation. The build is too long with tests, so at the moment with don't run a build on each PR. We have a cron build job on jenkins that we monitor.

**Comment by manonthegithub** [comment]
I can not figure out why, but running `HBaseTestUtility.startMiniCLuster` sometimes takes around 5 minutes on my machine, but sometimes only around 30 sec. So I hope it goes well on the build server :).

**Pull request merged**
