### PR TITLE
CAMEL-16390: Add salesforce 'raw' operation.

### PR DESCRIPTION
**Pull request by jeremyross**
For users who have been using the rawPayload option of the composite operation in unintended ways, this will give them a better option. Then we can [deprecate and remove](https://issues.apache.org/jira/browse/CAMEL-16388) most of the XML serialization that is just extra work to maintain and does not add value.

I've currently only got tests for queries and basic REST API operations, as the latter is what people have been using the rawPayload option for.

Would like feedback on the approach here. Also, since I didn't make it in time for 3.10, I'm wondering when we can remove XML serialization, and how to go about deprecating it. Warning messages? I'd really like to remove it for 3.11, but that wouldn't give a chance to deprecate. Thoughts appreciated.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I would deprecate in 3.11 and add some warning messages about the deprecations and removals in the next releases. After 3.11 we can wait just one or two releases and then remove the features.

**Review by omarsmak — APPROVED** [review]

**Comment by omarsmak** [comment]
Yeah, I am also in favor of only deprecating the XML serialization with a note in the documentation and maybe with `@Depecrated` annotations with XML related operations or even a warning message won't be a bad idea either. Fully removing the serialization, can be done in 3.12 in order to give the community sometime for feedback as you mentioned

**Comment by davsclaus** [comment]
The documentation for the raw headers vs raw query parameters seems a bit copy/paste and a little bit confusing. Also it would be good to add an example snippet in the docs, and explain what the raw uri then would become

**Comment by jeremyross** [comment]
> The documentation for the raw headers vs raw query parameters seems a bit copy/paste and a little bit confusing. Also it would be good to add an example snippet in the docs, and explain what the raw uri then would become

You're right. Not exactly sure what you mean by "explain what the raw uri then would become", so please let me know if you think I've addressed this.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
The docs are much improved, thanks

**Comment by jeremyross** [comment]
Ok to merge this? Don't want to conflict with the 3.10 release process.

**Comment by davsclaus** [comment]
Yeah this is fine, and if we recut 3.10.0 then this would be okay to include

**Pull request merged**
