### PR TITLE
CAMEL-8538 Add inOut support to the camel-rabbitmq component

### PR DESCRIPTION
**Pull request by brreitme**
This adds several major features to the camel-rabbitmq component that the camel-jms component has. InOut support that spins up a temporary reply queue that supports timeouts. Serializing / de-serializing objects that implement Serializable. Transfers exceptions that occur in consumers.

Added the following URI options (same usage as camel-jms)
transferException
requestTimeout
requestTimeoutCheckerInterval

### CODE REVIEW

**Comment by davsclaus** [comment]
Is this PR ready to go? And is there any documentation updates needed?

**Comment by brreitme** [comment]
Hi Claus,
We migrated all our customers from activemq to this about a month ago and have not had any issues.

Docs do need to be updated to include the new URI options (listed above). The usage is identical to activemq so it should be easy to copy paste. 

How do you want to handle that?  Do you usually edit them pre-merge or post?

**Comment by davsclaus** [comment]
The docs are usually edited after commit.

**Comment by davsclaus** [comment]
@brreitme are you able to rebase this PR with latest code from master branch as the camel-rabbitmq source code has changed since and there is too many conflicts for me to resolve.

**Comment by brreitme** [comment]
@davsclaus do you need it rebased and squashed into a single commit or is it ok now? I was able to fetch and merge from camel/master without any conflicts.

**Comment by brreitme** [comment]
@davsclaus Sorry about that. I rebased and squashed everything into a single commit.

**Comment by davsclaus** [comment]
Thanks @brreitme  - when we pull in PRs we do a pull and then a --rebase afterwards so the git tree is flatten and the pull is applied on top. And therefore we can hit merge errors.

**Comment by davsclaus** [comment]
Thanks the code has been pushed.

Do you mind working on fixing the code formatting issues. You can get a report by running

     davsclaus:~/workspace/camel/components/camel-rabbitmq (master)/$ mvn compile -Psourcecheck

Then open a new PR with those fixes.

**Comment by brreitme** [comment]
Thanks @davsclaus. I should be able to fix the formatting issues today. I'm waiting on my ICLA but plan on editing the docs

**Pull request merged**
