### PR TITLE
Upgrade solr container image used in test to 9.7.0

### PR DESCRIPTION
**Pull request by apupier**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by apupier** [comment]
requires manual change:
```
Caused by: org.apache.maven.plugin.compiler.CompilationFailureException: Compilation failure
/home/runner/work/camel/camel/components/camel-solr/src/test/java/org/apache/camel/component/solr/SolrCloudFixture.java:[137,17] no suitable method found for makePath(java.lang.String,java.nio.file.Path,boolean,boolean)
    method org.apache.solr.common.cloud.SolrZkClient.makePath(java.lang.String,byte[],boolean,boolean) is not applicable
      (argument mismatch; java.nio.file.Path cannot be converted to byte[])
    method org.apache.solr.common.cloud.SolrZkClient.makePath(java.lang.String,byte[],org.apache.zookeeper.CreateMode,boolean) is not applicable
      (argument mismatch; java.nio.file.Path cannot be converted to byte[])
    method org.apache.solr.common.cloud.SolrZkClient.makePath(java.lang.String,org.apache.zookeeper.CreateMode,org.apache.zookeeper.Watcher,boolean) is not applicable
      (argument mismatch; java.nio.file.Path cannot be converted to org.apache.zookeeper.CreateMode)

	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1309)
	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:208)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	... 15 common frames omitted
```

**Comment by apupier** [comment]
for the test of the component, it sound slike a previous version is still used:
```
[camel-solr] [ERROR] /home/runner/work/camel/camel/components/camel-solr/src/test/java/org/apache/camel/component/solr/SolrCloudFixture.java:[137,17] no suitable method found for makePath(java.lang.String,java.nio.file.Path,boolean,boolean)
    method org.apache.solr.common.cloud.SolrZkClient.makePath(java.lang.String,byte[],boolean,boolean) is not applicable
      (argument mismatch; java.nio.file.Path cannot be converted to byte[])
    method org.apache.solr.common.cloud.SolrZkClient.makePath(java.lang.String,byte[],org.apache.zookeeper.CreateMode,boolean) is not applicable
      (argument mismatch; java.nio.file.Path cannot be converted to byte[])
    method org.apache.solr.common.cloud.SolrZkClient.makePath(java.lang.String,org.apache.zookeeper.CreateMode,org.apache.zookeeper.Watcher,boolean) is not applicable
      (argument mismatch; java.nio.file.Path cannot be converted to org.apache.zookeeper.CreateMode)
```

**Comment by apupier** [comment]
locally with mvn clean install with this branch in camel-solr folder:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:17 min
[INFO] Finished at: 2024-09-11T11:32:02+02:00
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
