### PR TITLE
CAMEL-10513: Start BlueprintCamelContext on BlueprintEvent.CREATED

### PR DESCRIPTION
**Pull request by hqstevenson**

### CODE REVIEW

**Comment by davsclaus** [comment]
Have you tested this with the karaf examples? Don't think case the same problem as yesterday with the example `camel-example-mybatis` ?

**Comment by hqstevenson** [comment]
I ran a mvn clean test on camel/examples and I didn't see any failures, but that's as far as I went.  

When you see the failure, are you actually deploying the example?

**Comment by davsclaus** [comment]
Yes you need to deploy and run them in a real karaf container.

**Comment by hqstevenson** [comment]
OK.  Sorry for my ignorance, but which examples are "karaf" examples?

**Comment by davsclaus** [comment]
All the ones with karaf / blueprint / osgi etc. Their readme files mention something about that. And some like `camel-example-mybatis` are in fact for karaf also. So there is no clear sign.

**Comment by hqstevenson** [comment]
I changed the camel-example-mybatis example so that the DB initialization is bound to the Camel lifecycle rather than the Blueprint lifecycle.  This is more appropriate IMO (with or without the PR) because the way the initialization bean is written, it requires a running Camel Context to get the connection information for the DB in order to create the tables. 

The example would fail if the autoStartup="false" attribute were present in the XML as well, so I don't think the fact that this test used to fail should block the PR - if beans require a running Camel Context to do their work, they need to be aware of and use the Camel Lifecycle and not depend on the Blueprint/Spring lifecycle since Camel components/bean can be created and be valid without being started.

I'm going to look for some more examples that use Karaf and see if I can find any other issues.

**Comment by hqstevenson** [comment]
I grepped for Karaf in the README.md files of the examples, and I tested the ones I could - here's a summary of what I tested

camel-example-box: Can't test - I don't have a BOX acct
camel-example-cdi-osgi: N/A - doens't use Blueprint
camel-example-cxf-blueprint: VERIFIED through step 4 - didn't complete SoapUI part, but shouldn't matter because that isn't part of the Blueprint Lifecycle

camel-example-cxf-osgi: NA - doesn't use Blueprint
camel-example-etl:  NA - doens't use Blueprint
camel-example-netty-http: VERIFIED
camel-example-osgi-rmi: N/A - doesn't use Blueprint
camel-example-reportincident-wssecurity: N/A - doesn't use Blueprint
camel-example-servlet-rest-blueprint: VERIFIED
camel-example-spring-dm: N/A - doesn't use Blueprint
camel-example-sql: N/A - doesn't use Blueprint
camel-example-sql-blueprint: VERIFIED
camel-example-ssh: N/A - doens't use Blueprint
camel-example-ssh-security: N/A - doesn't use Blueprint
camel-example-swagger-osgi: VERIFIED
camel-example-twitter-websocket-blueprint: Verified installed, started and polled twitter (via logs).  Web Browser part didn't work for me - not sure why, but nothing to do with Blueprint lifecycle

camel-example-mybatis:  Updated to use Camel Lifecycle instead of Blueprint lifecycle

**Comment by davsclaus** [comment]
The EventNotifer is not intended for end users to use for initializing java beans etc.

What they should do is to keep using plain blueprint style with the init / destroy attributes as it does today, and then you can do IoC injection. Just as people are used to do this in Spring XML etc.

The EventNotifer is really for some cross cutting concern thingy you can plugin into Camel and it can do something, such as reporting timings of all messages, or something.

**Comment by hqstevenson** [comment]
Fair enough - I agree the examples shouldn't illustrate the using components/features in a manner that is different than they were intended.

I've changed the example so that the database initialization is independent of the Camel Context - hopefully this makes more sense.

**Comment by davsclaus** [comment]
Thanks that example looks better.

However due to the starting algorithm is changed, I would like to have an unit test where its the opposite, eg a `<bean>` has a `depends-on` the CamelContext so the bean is started after CamelContext and can have the CamelContext injected and use CamelContext in its logic.

**Comment by davsclaus** [comment]
I tested this with all the blueprint examples in a karaf container and this seems working fine.

However it would be good to have an example of `<bean> -> <camelContext>` depends-on example. A new PR with such example is welcome or as unit test.

I think its worth while to post on Camel dev/user mailing list about a [HEADS UP] about this camel-blueprint change, about the startup behavior made _more correct_ but that there is a change coming to 2.19.0 release, so people is welcome to test their existing blueprint apps and provide feedback.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by hqstevenson** [comment]
I'll close this PR, but I had question about the unit test you'd like to see.  I understand having a bean depend on the CamelContext - that makes sense. (BTW - you probably already know this, but you don't need the "depends-on" attribute if Blueprint can detect the dependency - Blueprint will detect the dependency when you inject the CamelContext into another bean).

The part that I'm unclear on is how you'd like to see the bean "use the camel context".  The example that didn't work with this PR had a problem because it depended on the state of the CamelContext (i.e. the context had to be started).  With this PR, the CamelContext will NEVER be started (at least by Blueprint/OSGi) until after all of the init-methods for all the beans have been called, so depending on the state of an injected CamelContext when using it in the init-method will always be a problem.

Hopefully I'm making sense - but could you elaborate on what you'd like to see a little more?

**Comment by davsclaus** [comment]
People may write beans that does something on startup, and that may require using Camel to eg call a HTTP server or something.

But this is PR change OSGi / blueprint and its ... after so many years working with OSGi .. always tricky to get right.

Well lets just close this PR and give the community a chance to feedback and test the master branch with their stuff and report back their findings.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
