### PR TITLE
CAMEL-5958: Bindy ignores bean class type

### PR DESCRIPTION
**Pull request by lburgazzoli**
re-build PR against latest sources

### CODE REVIEW

**Comment by davsclaus** [comment]
Sorry this got too old. We will revisit this in the future.

**Comment by lburgazzoli** [comment]
Shoul I try to keep it up to date with main code base ?

**Comment by davsclaus** [comment]
Oh that would be lovely if you have the time. Then we can take a look again and see if we can do this for next release if the impactive is low on any migration effort may needed

**Comment by lburgazzoli** [comment]
I will, no problem.

The impact is not very high:
- you need to specify the model class instead of the package so you can have multiple model in the same package
- the object you get back is not more a map of models but it is the model you specified so IMHO the code looks clearer 

If you see anything that should be improved, just tell me

**Comment by davsclaus** [comment]
Yeah that is much better and also an accepted trade-off for a little migration effort. 

Looking forward to your help.

**Comment by lburgazzoli** [comment]
has this PR been merged ?

**Comment by davsclaus** [comment]
Can you cleanup and do a new PR.

**Comment by lburgazzoli** [comment]
Done #586

**Pull request closed without merging**
