### PR TITLE
CAMEL-15346 Let xml-io pass the namespace info to NamespaceAware

### PR DESCRIPTION
**Pull request by ppalaga**
elements

### CODE REVIEW

**Comment by ppalaga** [comment]
a7fca1b successfully reverse-engineered all checkstyle's desires.

**Comment by oscerd** [comment]
We have about to formatting automatically. You're safe

**Comment by ppalaga** [comment]
> We have about to formatting automatically. You're safe

Great news!

**Comment by ppalaga** [comment]
The failure in camel-salesforce-maven-plugin seems to be unrelated. I can see it in other recent PRs too.

**Pull request merged**
