### PR TITLE
CAMEL-19152 - Add file client header and flush option

### PR DESCRIPTION
**Pull request by ank19**
# Description

Pls. see https://issues.apache.org/jira/browse/CAMEL-19152

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking

- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.
- [x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by oscerd** [comment]
May I ask you how you are authenticating and how you're setting the Azure Datalake? Are you using gen 2? I'm trying to make it work through Azure AD, but I had no luck (I'm removing the validateConfiguration method in the component, because it makes the clientId,clientSecret and tenantId useless). If you have some suggestions It would be great.

**Comment by ank19** [comment]
@oscerd - Sure, I also stumbled across the validateConfiguration method. Even if it's embarrassing, but I have to confess that on the fly I just derived a class from the configuration
```
@ConfigurationProperties(prefix="camel.component.azure-storage-datalake")
@Profile("!test")
public class Azure extends DataLakeConfiguration ...
``` 
and then I registered the component manually:
```
final var sharedKeyCredential = new StorageSharedKeyCredential(getAccountName(), getAccountKey());
final var builder = new DataLakeServiceClientBuilder();
builder.credential(sharedKeyCredential);
builder.endpoint("https://" + getAccountName() + ".dfs.core.windows.net");
final var dataLake = new DataLakeComponent(context);
setServiceClient(builder.buildClient());
dataLake.setConfiguration(this);
context.addComponent("datalake", dataLake);
```
Would it be possible to change that validate method so that setting the accountKey passes the validation and to create a StorageSharedKeyCredential from that then?

**Comment by oscerd** [comment]
@ank19 it would be nice, I'm removing the validateConfiguration method as first step, I'm going to merge it this morning. Would you mind opening a PR for add the needed steps to use accountName + accountKey? Also, could you please share how you are setting your Azure Datalake Gen 2? We could talk also on Zulip if you want. Thanks for sharing your approach.

**Comment by ank19** [comment]
@oscerd - Sure, I'll try to have a look at it as soon as possible, maybe tomorrow. Contributions to Camel are amongst the most interesting topics in my work, :-)

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
This PR is fine, so I think you could do another one for the accountkey and accountname fix.

**Comment by davsclaus** [comment]
Is this PR still valid, and do we have PRs for main and 3.20.x branch (if needed on this branch too) as well?

**Comment by oscerd** [comment]
https://github.com/apache/camel/pull/9577

For 3.20.x we don't, since there are some breaking changes. Maybe we should backport anyway, because it works better with this PR.

3.x PR can be merged.

**Pull request merged**
