### PR TITLE
CAMEL-18333: camel-kafka - better error messages during health check

### PR DESCRIPTION
**Pull request by rinaldodev**

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by rinaldodev** [comment]
@davsclaus @oscerd where do I find the log files for those failing tests? I tried `.github/actions/quick-test/quick-test.sh 9436b42f39af3e4328e6158b1264c4bd43caf7f4 c85811dc23c61b35ae315f8bf88e1b9abdcb79e9` locally but it works fine.

**Comment by davsclaus** [comment]
@orpiske knows how to get those log files from the CI server

**Comment by orpiske** [comment]
Unfortunately Apache restricts access to the build / test logs to committers. So we have to upload them manually when requested. 

I have just uploaded them to this comment. 
[test-logs(1).zip](https://github.com/apache/camel/files/9239838/test-logs.1.zip)

**Review by orpiske — APPROVED** [review]

**Comment by orpiske** [comment]
BTW, I have the impression that the test failing here is flaky. I have seen it fail on GitHub Actions in the past.

**Comment by davsclaus** [comment]
Okay if its not a consistent failure on the new tests from this PR, then I am okay for merging.

**Comment by orpiske** [comment]
Yeah. I triggered a new test execution to see how it goes.

**Pull request merged**
