### PR TITLE
CAMEL-11919 Adding new feature

### PR DESCRIPTION
**Pull request by DG007**
Salesforce REST API request headers not included in update,upsert,create
and query operations

### CODE REVIEW

**Comment by oscerd** [comment]
@zregvart do you mind taking a look?

**Comment by davsclaus** [comment]
The code need also to fix checkstyle, run

    mvn compile -P sourcecheck

**Comment by DG007** [comment]
I have now updated the code to pass checkstyle.

**Comment by zregvart** [comment]
@DG007 thank you for this pull request! I'll merge this in. I would like to cleanup the implementation a bit first, adding javadoc and such. And run the integration tests.

**Comment by DG007** [comment]
@zregvart Thank you accepting the PR. I have a general question regarding camel version 2.20.0. Can i clarify it here?

**Comment by zregvart** [comment]
@DG007 I've decided upon a slightly different take on this (see https://github.com/apache/camel/commit/eb38af78b850541037e14d4ce0919b13ed4b81c6). With this we can support any Salesforce header on any request and also get headers from response on outbound message.
If this is OK with you could you close this pull request or perhaps rebase and add any functionality that might be missing in your use case?

Thank you for raising the issue and taking a stab at implementing it -- it really makes a difference 👍

**Comment by oscerd** [comment]
@DG007 do you need to add something to the fix by @zregvart ? Can we close this and eventually you'll open a new PR with improvements? Thanks.

**Comment by DG007** [comment]
i was trying to test this build, but my camel version upgrade to 2.20.0 doesn't work. My application is not starting up. so couldn't test it yet. Is there a document which I could use to upgrade from camel 2.19.4-snapshot to camel 2.20.0?

**Comment by zregvart** [comment]
> i was trying to test this build, but my camel version upgrade to 2.20.0 doesn't work. My application is not starting up. so couldn't test it yet. Is there a document which I could use to upgrade from camel 2.19.x to camel 2.20.0?

Hi @DG007 to test these changes you would need to run with the latest `2.21.0-SNAPSHOT` version, as this has not yet been released, and will be a part of 2.21.0. There should not be that much difference between 2.19 and 2.20 to prevent your application from starting. If there is, we would like to address it so can you write to the users mailing list explaining your use case, or create a JIRA issue so we can have a look?

**Comment by DG007** [comment]
users@infra.apache.org is this where I can address my use case?

**Comment by zregvart** [comment]
> users@infra.apache.org is this where I can address my use case?

@DG007 we have a users mailing list at `users@camel.apache.org` see [here](https://camel.apache.org/mailing-lists.html) how to subscribe, there is also a [Gitter chat room](https://camel.apache.org/2017/07/11/official-apache-camel-chat-room-on-gitter.html), and the [JIRA is here](https://issues.apache.org/jira/projects/CAMEL).

**Comment by zregvart** [comment]
This has been implemented via https://github.com/apache/camel/commit/eb38af78b850541037e14d4ce0919b13ed4b81c6, see [CAMEL-11919](https://issues.apache.org/jira/browse/CAMEL-11919).

**Pull request closed without merging**
