### PR TITLE
CAMEL-10883: Support HTTP 1.1 continue in Undertow

### PR DESCRIPTION
**Pull request by RohanHart**
Adding support for "continue" processing in Undertow is trivially done in UndertowConsumer.

However, the processing of delayed payloads could truncate the data - for me this happened reliably if the payload was more than 16KB. This has been replaced by a standard blocking channel which supports the processing expectations of Undertow's HttpServerExchange.

### CODE REVIEW

**Comment by oscerd** [comment]
Can you please raise an issue on JIRA and rebase your commit with the issue id? This is an important change to track. Thanks.

**Comment by davsclaus** [comment]
Yeah we want a JIRA ticket for such changes. Trivial PRs are okay without a JIRA

**Comment by RohanHart** [comment]
rebased for CAMEL-10883

**Comment by davsclaus** [comment]
Thanks @oscerd do you want to take a look and if its okay merge to master?

**Comment by oscerd** [comment]
Sure :-)

**Comment by oscerd** [comment]
Looks good and merged. Thanks @RohanHart . Can you close the PR?

**Pull request closed without merging**
