### PR TITLE
Adding additional logging to scope creation and closing

### PR DESCRIPTION
**Pull request by marcingrzejszczak**
the problem we have is that one of the spans in one of the tests (most probably MulticastRouteTest) is not being closed and the span is left in the test thread. Due to this other tests are failing.

This PR removes the workaround that conditionally closes scopes. With these changes we're always closing scopes even multiple times.

related to pr gh-10539

closes https://issues.apache.org/jira/browse/CAMEL-19569

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by marcingrzejszczak** [comment]
I think that should fix things cc @davsclaus @oscerd @ppalaga

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Thanks @marcingrzejszczak do you know if we need to backport this to 3.x LTS branches?

**Comment by marcingrzejszczak** [comment]
I'll check it out tomorrow

**Comment by marcingrzejszczak** [comment]
Do we observe any issues with the builds for other branches? Which branches are the LTS ones? 3.21.x, 3.20.x, 3.18.x, 3.14.x ?

**Comment by davsclaus** [comment]
I dont think we have seen this, but some of these branches may had a JDK11 compile problem that we didnt got attention (we are busy with v4)

The latest JDK17 on 3.x seems not to have micrometer/observer any problems
https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/camel-3.x/lastCompletedBuild/testReport/

**Comment by marcingrzejszczak** [comment]
So maybe we shouldn't touch that code unless we see that there are issues? WDYT?

**Comment by davsclaus** [comment]
Yes we assume 3.x is all good for now, thanks.

**Pull request merged**
