### PR TITLE
CAMEL-11726: Fixed the Elsql producer inconsistent behavior compared …

### PR DESCRIPTION
**Pull request by bonbonmark**
Add unit test to ensure we can get header value at following step

### CODE REVIEW

**Comment by onders86** [comment]
LGTM.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by bonbonmark** [comment]
Thanks. Closing then.

**Comment by bonbonmark** [comment]
Thanks. Closing then.

**Pull request closed without merging**
