### PR TITLE
CAMEL-11656 - add preSort option

### PR DESCRIPTION
**Pull request by onders86**
even though i believe this issue is not related to sorting file list beforehand, i am just opening the PR to discuss further and revise...
@davsclaus could you review?

### CODE REVIEW

**Comment by oscerd** [comment]
In my opinion it can be good to have this, but we need to avoid the options number explosion in this component. Lets wait for @davsclaus

**Comment by onders86** [comment]
yes sure.updated.

**Comment by davsclaus** [comment]
Maybe we can improved the documentation a bit, something like:
```
When pre-sort is enabled then the consumer will sort the file and directory names during polling, that was retrieved from the file system. You may want to do this in case you need to operate on the files in a sorted order. The pre-sort is executed before the consumer starts to filter, and accept files to process by Camel. This option is default disabled.
```

**Comment by oscerd** [comment]
@onders86 is there a specific reason to backport to 2.20.x? This is a new option, so  usually we avoid new options in minor releases

**Comment by onders86** [comment]
@oscerd No there is not. I thought we would need to backport because this was a wish since 2.19.0. I dont mind reverting. Let me know.

**Comment by onders86** [comment]
@oscerd , reverted.

**Pull request merged**
