### PR TITLE
Http4+get with body

### PR DESCRIPTION
**Pull request by mthirion**
Added support for GET with body content on camel-http4. This is triggered with the 'getWithBody=true' uri parameter.

### CODE REVIEW

**Comment by valdar** [comment]
Hey there, thanks for the contribution! 

It seems a backport of https://issues.apache.org/jira/browse/CAMEL-14118 in particular https://github.com/apache/camel/commit/cf8c9a6505556e0df7ab426d787de4c1ced24131
Do you mind backporting, from that commit, the test as well (and check if it does pass)?

Also as a general note please run `mvn -DskipTest -Psourcecheck` in the component you modified (i.e. `camel-http4`) and see if there are code style violations.

**Comment by davsclaus** [comment]
Did you get a chance to work on this?

**Comment by mthirion** [comment]
Unfortunately not yet.  Will do as soon as I can.

**Comment by mthirion** [comment]
Hi!  I need a bit of advice here.  The commit "cf8c9a6" applies to camel-http while the current PR treats of camel-http4.  Backporting the above commit to the camel-http component of v2.25 is not that straightforward as the component has changed quite a lot in the meantime.  The commit "cf8c9a6" complemented the inclusion of a deleteWithBody feature, but this feature does not exist yet in camel-http 2.25 (while it exists on camel-http4).
I had heard that in v2 we were encouraging camel-http4 rather than camel-http, but I could see that in v3 the components converged and camel-http4 disappeared.  
So I would say it would be better to keep those 2 changes separate: one PR to update camel-http4 in v2, then another one to both backport getWithBody and add deleteWithBody to camel-http .
What do you think?

PS. In case, I've just added a commit to this PR branch to add the required unit test to camel-http4.

**Comment by davsclaus** [comment]
Only focus on camel-http4 in camel 2.x, the other camel-http is deprecated as its based on a very old EOL http client.

**Comment by mthirion** [comment]
Ok got it.  So it's actually camel-http4 v2 that led to the new camel-http in v3.  Makes more sense now.

**Comment by mthirion** [comment]
Done.

**Pull request merged**
