### PR TITLE
CAMEL-10451 camel-undertow - Add multipart request support

### PR DESCRIPTION
**Pull request by igarashitm**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks there is some checkstyle errors do you mind fixing them?

   mvn compile -Psourcecheck

**Comment by igarashitm** [comment]
Ugh sorry my bad. fixed. It seems like I break checkstyle rule everytime I edit...

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by igarashitm** [comment]
Thanks! closing

**Comment by wyz1450349230** [comment]
How send multipart/form-data request to spingboot interface in camel dsl?

**Pull request closed without merging**
