### PR TITLE
Camel 2.15.x

### PR DESCRIPTION
**Pull request by sajjadhasan**
Need to add server side encryption for S3 with camel 2.15 as we are using Jboss fuse 6.2.

### CODE REVIEW

**Comment by onders86** [comment]
i guess, this pr can not go in. 2.15.0 is quite old and suppose EOL.

**Comment by sajjadhasan** [comment]
That's okay, I guess. I was just looking for downloading the code and change it in my local to test those. I actually do not need to merge it as it is available from the upper version of camel anyway. Thanks though.

**Comment by tadayosi** [comment]
@sajjadhasan If you are using JBoss Fuse, request the backport to Red Hat.

**Comment by sajjadhasan** [comment]
@tadayosi : will do :+1: . Thanks.

**Pull request closed without merging**
