### PR TITLE
fix(core): use class type instead of text property

### PR DESCRIPTION
**Pull request by squakez**
Before this PR a route as for example `from("...").unmarshal().json(JsonLibrary.Jackson, User.class).to("...")` was initializing a `JacksonDataFormat` trying to dynamically load a `Class` from `unmarshalTypeName` parameter ([here the code](https://github.com/apache/camel/blob/main/components/camel-jackson/src/main/java/org/apache/camel/component/jackson/AbstractJacksonDataFormat.java#L512)). This resulted in a missing class loading when we are using a route loaded dynamically (as it happens in camel-k). This behavior happen when the class we want to unmarshal is for instance provided with the same route source (ie, a static inner class) because that class is not available in the classpath.

With this PR we'll be able to use the `Class` instead of leveraging a text property avoiding a dynamic load later when initializing the dataformat. This would apply to other dataformat as well.

Closes CAMEL-16760
Closes CAMEL-16755

### CODE REVIEW

**Comment by squakez** [comment]
cc @lburgazzoli

**Comment by davsclaus** [comment]
Nice attempt but we should think bigger picture, there are many dataformats, if you do a git grep asTypeName( you can see its used in many places.

Also camel-jackson does not have a reflection free setter for this
https://github.com/apache/camel/blob/e5c972aab914799907ed3482253f4fb81f91ce83/components/camel-jackson/src/generated/java/org/apache/camel/component/jackson/JacksonDataFormatConfigurer.java#L32

But its a good idea to look at those dataformats that allows to set the type from an existing Class instance, then we can have an unmarshalType as its setter, and ensure its in the generated configurer.

**Comment by davsclaus** [comment]
So a problem is that in the core model the unmarshalType is marked as transient due to XML / yaml DSL where you set this as text based. But Java based you can set it directly as a Class.

So to allow this for Java DSL then we need to add some way in the generated configurer so they include the unmarshalType for the Class, and then for all dataformat reifiers we need to update them to set the class directly and otherwise do as it does today.

**Comment by squakez** [comment]
Thanks @davsclaus , I knew it was not that easy... :) I'll start working on it. I wonder if it makes sense to add some interface in order to mark those dataformat that are meant to follow this pattern.

**Comment by davsclaus** [comment]
I added a comment in CAMEL-16760

Try to change from
```
    @XmlAttribute
    private String unmarshalTypeName;
    @XmlTransient
    private Class<?> unmarshalType;
```

To
```
    @XmlAttribute(name = "unmarshalType")
    private String unmarshalTypeName;
    @XmlTransient
    private Class<?> unmarshalType;
```

And then in the xxxReifier you change from

```
            if (definition.getUnmarshalType() != null) {
                properties.put("unmarshalTypeName", asTypeName(definition.getUnmarshalType()));
            } else {
                properties.put("unmarshalTypeName", definition.getUnmarshalTypeName());
            }

```

to

```
properties.put("unmarshalType", or(definition.getUnmarshalType(), definition.getUnmarshalTypeName()));
```

And you do this for the others like jsonView, collectionType etc.

And then you need to regen the core source code to update the model, and then also regen the source code of the components etc.

**Comment by davsclaus** [comment]
The drawback is that the XML and YAML DSL is changed, eg `unmarshal-type-name` to `unmarshal-type`

**Comment by squakez** [comment]
> The drawback is that the XML and YAML DSL is changed, eg `unmarshal-type-name` to `unmarshal-type`

As we're introducing this in a minor release, I guess we should not worry about backward compatibility here, is that correct?

**Comment by davsclaus** [comment]
Yes that is correct we document this in the 3.12 upgrade guide.

I am doing an example for you with the ASN1 data format, you can look at as inspiration and work on that for all the others.
Give me a sec to cleanup the PR

**Comment by davsclaus** [comment]
Okay here is the commit for AS1 data format, which is something similar to do for the others
https://github.com/apache/camel/commit/01260a4810c5348c1ff6edfa72f1537ad18c3dbf

**Comment by squakez** [comment]
Great, thanks a lot @davsclaus !!

**Comment by squakez** [comment]
FYI @davsclaus, this should be ready to go now

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
