### PR TITLE
CAMEL-11678 - clientIdentifer is not mandatory if accessToken exists

### PR DESCRIPTION
**Pull request by onders86**

### CODE REVIEW

**Comment by onders86** [comment]
@vrlgohel , made a sample PR. please take a look.

**Comment by vrlgohel** [comment]
@onders86, hi, did you check these changes with actual testing with a dropbox account ? Do all the tests pass fine ?

**Comment by vrlgohel** [comment]
@onders86 , the branch has conflicts as we updated and merged the other PR. You can resolve the conflicts or you can pull rebase and then submit a new PR if you like.

**Comment by onders86** [comment]
It was just a matter of small change in adoc because regen was needed. Adjusted. @davsclaus this may go into 2.20. Could you please check?
Thanks

**Comment by davsclaus** [comment]
Yeah that is my understand as well, this can be merged.

**Pull request closed without merging**
