### PR TITLE
CAMEL-21128: camel-core - Add trust all certificate for easier TLS/SS…

### PR DESCRIPTION
**Pull request by saravanakumar1987**
…L development

Please review the PR for CAMEL-21128

Thanks,
Saravanakumar

# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Thanks would you help with adding this to spring boot also, see
https://github.com/apache/camel-spring-boot/tree/main/core/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/security

**Review by oscerd — APPROVED** [review]

**Comment by saravanakumar1987** [comment]
> Can you add this file to the PR modified: core/camel-main/src/main/docs/main.adoc

The file is already up-to-date with main branch. No new commits to fetch.

**Review by aravindvelmurugan — APPROVED** [review]

**Comment by aravindvelmurugan** [comment]
Apologies for the accidental approval. Unsubscribed.

**Comment by saravanakumar1987** [comment]
> Manually merged. I toned down the WARN log as if you do performance testing with a lot of requests then the log gets filled up with WARNs

I see the log messages appearing only once for an SSL connection even though calling multiple times, possibly due to default SSL Session reuse strategy

**Pull request closed without merging**
