### PR TITLE
CAMEL-13209 Upgrading GRPC version to 1.20.0

### PR DESCRIPTION
**Pull request by dimitrisli**
Also upgrading associated dependencies and needed refactoring.

Addressing https://issues.apache.org/jira/browse/CAMEL-13209

It seems there were some breaking changes from version **1.15.0** to **1.20.0**

**Resources used for the version changes**
- [grpc version 1.20.0 is the latest Tag version](https://github.com/grpc/grpc-java)
- [grpc-google-auth-library-version](https://github.com/grpc/grpc-java/blob/v1.20.x/build.gradle#L111)
- [grpc-guava-version](https://github.com/grpc/grpc-java/blob/v1.20.x/build.gradle#L112)
- [grpc-netty-tcnative-boringssl-static-version](https://github.com/grpc/grpc-java/blob/v1.20.x/build.gradle#L228)
- [grpc-bundle-version](https://mvnrepository.com/artifact/org.apache.servicemix.bundles/org.apache.servicemix.bundles.grpc)
- [grpc-errorprone-version](https://github.com/grpc/grpc-java/blob/v1.20.x/build.gradle#L195)
- grpc-java-jwt-version -> Wasn't updated to 3.8.0 as a test was failing.

**Refactoring**

There is one thing in particular that has to be reviewed since I haven't used GRPC myself in the past:
the usage of the `io.grpc.internal.GrpcAttributes.ATTR_LB_ADDR_AUTHORITY` in place of the previous (and currently not available) `ATTR_AUTHORITY`.

**Additional Task per Code Review**
- [x] protobuf-maven-plugin-version -> 0.6.1 (raised by @dmvolod)
- [x] `.maxMessageSize(configuration.getMaxMessageSize()) -> .maxInboundMessageSize(configuration.getMaxMessageSize())` (raised by @dmvolod)
- [x] Untag @ignore("TODO: investigate for Camel 3.0") from tests and try to make them to be running. (raised by @dmvolod) - resolution comment: works out of the box. Only testPingAsyncAsyncRecovery was intermittently failing due to race condition. Increasing the sleep time to 1sec was consistently passing on multiple trials.
- [x] May be investigate why grpc-java-jwt-version update fails tests. (raised by @dmvolod) - resolution comment: works fine for version 3.7.0
- [x] correct grpc-errorprone-version -> 2.3.2 (raised by @dmvolod)
- [ ] Check Karaf feature related to camel-grpc and camel-protobuf under platform/karaf/features and check with the integration test in tests/camel-itest-karaf (raised by @oscerd)
- [ ] Check Spring Boot integration test in tests/camel-itest-spring-boot (raised by @oscerd)
- [x] libxcrypt-compat installation for security options per OS might be needed. It's would be nice to add this info from the https://github.com/grpc/grpc-java/blob/master/SECURITY.md or point this file link to the doc and some info. (raised by @dmvolod)

### CODE REVIEW

**Comment by oscerd** [comment]
I suspect is not straightforward for the Karaf feature, that's why I'm stressing to check.

**Comment by dimitrisli** [comment]
@dmvolod @oscerd many thanks for your feedback. I have added all these as tasks in the description to track progress.

**Comment by dmvolod** [comment]
@dimitrisli, please also pay attention, that some new Linux distribution, i.e. Fedora 30, etc. require to install libxcrypt-compat for security options using. It's would be nice to add this info from the https://github.com/grpc/grpc-java/blob/master/SECURITY.md or point this file link to the doc and some info.

**Comment by dimitrisli** [comment]
@dmvolod sure thanks for raising I've added in the TODO list of the description to track progress.

**Comment by dimitrisli** [comment]
@dmvolod There is an intermittent problem with the test `GrpcProducerStreamingTest#testPingAsyncAsyncRecovery `- it is failing intermittently regardless of the `Thread.sleep()` guard in between. I have tried an alternative approach as used in the `GrpcProducerAsyncTest.java` where I use a `CountdownLatch` of size `messageGroupCount` submitting `template.asyncCallbackSendBody(.,.,callback onComplete to latch.countdown())` with right after `latch.await()` but this doesn't help. Any ideas?

**Comment by dmvolod** [comment]
@dimitrisli this is strange, however it would be nice to review component code, enable debug and try to find the core problem. May be some changes in gRPC core could affect. I will try to dive into the problem and it's can't to be a problem with Thread.sleep() in test.

**Comment by davsclaus** [comment]
How is this going, there has been a lot of work already done and it would be great to get this done and merged to master so we get this in Camel 3

**Comment by dmvolod** [comment]
@davsclaus , ok, will look at the issue with test and additional tasks

**Pull request closed without merging**
