### PR TITLE
Camel 13368 - LevelDB NPE if fileName missing separator

### PR DESCRIPTION
**Pull request by hakuseki**
This is my first contribution so please be patient :)

### CODE REVIEW

**Comment by hakuseki** [comment]
https://issues.apache.org/jira/plugins/servlet/mobile#issue/CAMEL-13368

**Comment by davsclaus** [comment]
There may be some checstyle issues, can you run

    mvn compile -P sourcecheck

In the camel-leveldb folder and fix those issues

**Comment by hakuseki** [comment]
Fixed checkstyle issues

**Comment by oscerd** [comment]
There are conflicts actually

**Comment by hakuseki** [comment]
Conflicts resolved

**Comment by oscerd** [comment]
Thanks, merged on master, 2.23.x, 2.22.x and 2.x

**Pull request merged**
