### PR TITLE
CAMEL-10447 Split ContractAdvice#doTransform() into smaller methods

### PR DESCRIPTION
**Pull request by igarashitm**

### CODE REVIEW

**Comment by igarashitm** [comment]
ugh sorry hold on a sec - fixing cs error

**Comment by igarashitm** [comment]
OK now it's ready to go.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by igarashitm** [comment]
Thanks! closing

**Pull request closed without merging**
