### PR TITLE
updating rest tests for new restParam option

### PR DESCRIPTION
**Pull request by sebi-hgdata**
Hey,
   I'm a bit late on my promise, but here is the PR that updates the rest tests and fixes some issues that appeared after the code cleanup. (also it fixes an issue with includeRoutes method as it did not include the rest routes)
   I still need to have investigate why the blueprint tests fails... probably will do it over the weekend
  Also as a side note ,  I will add support also for https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#525-response-message-object in a separate PR

Seb Calbaza

### CODE REVIEW

**Comment by sebi-hgdata** [comment]
Hey,
 I rebased and cleaned up the branch.  Should be suitable for merging. 

Thanks,
  Seb Calbaza

**Comment by davsclaus** [comment]
Hi

1.
We do not use abrv names - could you rename msg to message.

2. 
I wonder if we should not lose the rest prefix as this is rest only, eg restParam -> param, restResponseMsg -> responseMessage, and so on.

3.
I think we should add some java fluent builder to make it easier to set those accepted values as a var ags, so you dont have to wrap them into a List instance, so it can be 

   acceptedValues("1", "2", "3")

or something as easy as that.

**Comment by sebi-hgdata** [comment]
Sure, will do

**Comment by davsclaus** [comment]
@sebi-hgdata did you have any chance to work on this?

**Comment by sebi-hgdata** [comment]
Will try to wrap it up today

**Comment by sebi-hgdata** [comment]
Hey,
  Check latest commit. Let me know if you need anything else

**Comment by davsclaus** [comment]
Thanks a lot @sebi-hgdata the code has been merged. Do you mind closing this PR.

Also we need to update the rest-dsl with this new functionality. Are you able to help with that?
http://camel.apache.org/rest-dsl

**Comment by sebi-hgdata** [comment]
Sure. Can you point me to the files that need to be updated?

**Comment by davsclaus** [comment]
Yes its this page
http://camel.apache.org/rest-dsl

But for editing docs you need to file a ICLA and follow this guide
http://camel.apache.org/how-do-i-edit-the-website.html

**Comment by sebi-hgdata** [comment]
Still trying to find some time to do the above...

**Pull request closed without merging**
