### PR TITLE
CAMEL-17062 Move camel-dependencies inside of camel-catalog to avoid deployment issues

### PR DESCRIPTION
**Pull request by cunningt**
https://issues.apache.org/jira/browse/CAMEL-17062

camel-dependencies has no dependencies and maven forces it early in the build order.    camel-catalog syncs the properties to camel-dependencies, but that doesn't happen till after camel-dependencies builds and install, which creates a build order issue - the camel-dependencies that is installed and deployed is not the synced copy.

An advantage to this approach is that if there are sync properties changes to camel-dependencies, the build is not overwriting source git files - camel-dependencies is synced within the target build directory.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
@cunningt is the file still being generated and up to date at
https://github.com/apache/camel/tree/main/camel-dependencies

**Review by oscerd — CHANGES_REQUESTED** [review]
Rethinking a bit about this, this early morning.

This cannot work for downstream project. Downstream project like camel-karaf/camel-spring-boot, still depends on camel-dependencies module SNAPSHOT. In this way the generated file will be in target, but it cannot be consumed by dependant downstream project, so we cannot accept this.

-1 from my side.

**Comment by cunningt** [comment]
Is there a reason that downstream projects cannot consume it?    camel-dependencies gets attached to the build here (https://github.com/apache/camel/pull/6462/files#diff-8c255d9bbb596757064bb75da2871b2891a104f3d2eaf8937dfc759081eb2d19R134-R142) and it would be deployed for the downstream projects.     SNAPSHOT version would still be available.     I know camel-quarkus also consumes camel-dependencies, and this change would help camel-quarkus.

@davsclaus I was hoping to move camel-dependencies/pom.xml -> catalog/camel-catalog/camel-dependencies-pom.xml  and no longer maintain it at https://github.com/apache/camel/tree/main/camel-dependencies.

**Comment by oscerd** [comment]
Ah ok, I thought it would live only in the target folder and not in the camel-dependencies SNAPSHOT. If it's available after a full build and the camel-dependencies still exist and it's still updated, it's fine.

**Comment by davsclaus** [comment]
IMHO we should generate camel-dependencies/pom.xml file as we do today so its included in the source code, and we can see its correct. In the old days of 2.x we had files generated at build time that we could not easily see if something was wrong.

Its also a great place to look at on github for what dependencies versions we use.

Have you tried moving it down after catalog in the root pom.xml so its build by maven after the catalog (and its generation).

**Comment by oscerd** [comment]
I think having a camel-dependencies pom evident in the source tree, it's a good choice. I don't see it as a limitation. Maybe we could find a way to build it later in the build, after the catalog.

**Comment by orpiske** [comment]
Can't we solve this by separating the concerns? I mean like separating refreshing the dependencies from the dependency management? 

We could use the [properties-maven plugin](http://www.mojohaus.org/properties-maven-plugin/) to write and read a properties file. 

One potential benefit is that, with this way we could remove the all duplicated dependencies which are also currently listed in the parent pom. IMHO it could make dependency maintenance much simpler and the build code smaller. 

Currently we have: 

`camel-dependencies` -> `camel-catalog` -> `camel-dependencies` (sync-properties) 

Instead, we could refresh the dependencies as part of the the `camel-parent` (or `camel-dependencies` ?) build. 

Granted: this is a much bigger proposition, but may lead to a cleaner build and remove the cyclic dependency.

**Comment by oscerd** [comment]
The properties maven plugin won't write a full POM like we need for the downstream projects. This was something that was evaluated at the time, but in the need wasn't good for the job.

**Comment by orpiske** [comment]
> The properties maven plugin won't write a full POM like we need for the downstream projects. This was something that was evaluated at the time, but in the need wasn't good for the job.

The idea is not to rewrite the pom. The idea is to externalize only the properties in the pom.

**Comment by oscerd** [comment]
I do not have strong opinion, but to me, having the camel-dependencies to be regenerated is not a limitation or a problem. Maybe externalize would work, but don't we have the properties duplicated anyway? In the parent pom and in the externalized properties file? This build system is stable from a while, eventhough it's not perfect.

**Comment by davsclaus** [comment]
> camel-dependencies -> camel-catalog -> camel-dependencies (sync-properties)

No I dont think this is correct - its

> camel-catalog -> camel-dependencies (sync-properties)

In the camel-catalog there is a maven plugin that sync that camel-dependencies.

However what is the "problem" is that running camel-catalog should be done after all the components are build etc, which was tricky in the past with maven as it can build in "whatever order it thinks its best" - so there is this camel-allcomponents "trick".

**Comment by davsclaus** [comment]
So at the end of the day, what we can try is to move that generation of camel-dependencies out of catalog, and to some place where its run at the very end.

**Comment by orpiske** [comment]
> > camel-dependencies -> camel-catalog -> camel-dependencies (sync-properties)
> 
> No I dont think this is correct - its
> 
> > camel-catalog -> camel-dependencies (sync-properties)
> 

Actually, we do seem to build the [camel-dependencies before the catalog](https://github.com/apache/camel/blob/main/pom.xml#L72). 

> In the camel-catalog there is a maven plugin that sync that camel-dependencies.
> 
> However what is the "problem" is that running camel-catalog should be done after all the components are build etc, which was tricky in the past with maven as it can build in "whatever order it thinks its best" - so there is this camel-allcomponents "trick".

I understand.  But it seems to me that we are using the catalog build only to refresh the dependency pom, no? 

BTW, I'm not trying to push to an specific solution here ... but it does seem odd that we have this cyclic dependency (but, as you know, I may be missing previous context here).

**Comment by orpiske** [comment]
> I do not have strong opinion, but to me, having the camel-dependencies to be regenerated is not a limitation or a problem. Maybe externalize would work, but don't we have the properties duplicated anyway? In the parent pom and in the externalized properties file? This build system is stable from a while, eventhough it's not perfect.

Yeah. I think the build works just fine. It can certainly be improved, of course, but it does not seem to me like there's a big problem. 

I think the biggest problem may be for vendoring, when there's any sort of checking of the sources during the build.

**Comment by cunningt** [comment]
> So at the end of the day, what we can try is to move that generation of camel-dependencies out of catalog, and to some place where its run at the very end.

Thank you all for the feedback and suggestions - I'll give this approach a try and resubmit.

**Comment by oscerd** [comment]
Moving the camel-dependencies after catalog did the trick, I pushed the fix for it and took the liberty to use this approach. We can always change it later if not ok.
```

[INFO] Camel :: Catalog ................................... SUCCESS [  1.470 s]
[INFO] Camel :: Catalog :: Dummy Component ................ SUCCESS [  0.446 s]
[INFO] Camel :: Catalog :: Camel Catalog .................. SUCCESS [  4.145 s]
[INFO] Camel :: Catalog :: Lucene ......................... SUCCESS [  0.616 s]
[INFO] Camel :: Catalog :: Maven .......................... SUCCESS [  0.787 s]
[INFO] Camel :: Catalog :: Camel Route Parser ............. SUCCESS [  0.858 s]
[INFO] Camel :: Catalog :: Camel Compiled Simple Maven Plugin SUCCESS [  0.711 s]
[INFO] Camel :: Catalog :: Camel Report Maven Plugin ...... SUCCESS [  0.832 s]
[INFO] Camel :: Dependencies .............................. SUCCESS [  1.433 s]
```

**Comment by davsclaus** [comment]
Okay closing this as Andrea moved the build to later.
@cunningt let us know if you have any problems still.

**Pull request closed without merging**
