### PR TITLE
CAMEL-10983: Fail early and show meaningful log for invalid endpoint URI in Blueprint

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.apache.org/jira/browse/CAMEL-10983

### CODE REVIEW

**Comment by davsclaus** [comment]
@oscerd looks good to me

**Comment by oscerd** [comment]
Sure. Merging.

**Comment by oscerd** [comment]
@tadayosi Thanks a lot. Can you close the PR? It has been merged.

Please resolve the JIRA ticket too :-)

**Comment by tadayosi** [comment]
Thanks!

**Pull request closed without merging**
