### PR TITLE
[CAMEL-20747] Migrate SpringSecurityAuthorizationPolicy to Spring 5

### PR DESCRIPTION
**Pull request by santam85**
# Description

Changed the SpringSecurityAuthorizationPolicy to remove deprecated methods and classes, using the new Authorization manager. See the following links for reference:

- https://docs.spring.io/spring-security/reference/5.8/migration/servlet/authorization.html
- https://docs.spring.io/spring-security/reference/servlet/authorization/architecture.html#authz-access-decision-manager
- https://camel.zulipchat.com/#narrow/stream/257301-camel-spring-boot/topic/Route.20Policies.20and.20Spring.20Security.206

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
[CAMEL-20747 - Remove usage of deprecated Spring Security classes for route policies](https://issues.apache.org/jira/browse/CAMEL-20747)

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by santam85** [comment]
Tested the snapshot locally with success using the following policy definition:

```
	@Bean(RolePolicy.ADMIN)
	public AuthorizationPolicy authorizationPolicyAdmin(AuthenticationManager authenticationManager) {
		SpringSecurityAuthorizationPolicy authorizationPolicy = new SpringSecurityAuthorizationPolicy();
		authorizationPolicy.setAuthenticationManager(authenticationManager);
		authorizationPolicy.setAuthorizationManager(AuthorityAuthorizationManager.hasRole("ADMIN"));
		return authorizationPolicy;
	}
```

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
the PR gives a test error with

org.apache.camel.component.spring.security.config.SpringSecurityAuthorizationPolicyConfigTest.testAuthorizationPolicy

**Comment by santam85** [comment]
> the PR gives a test error with
> 
> org.apache.camel.component.spring.security.config.SpringSecurityAuthorizationPolicyConfigTest.testAuthorizationPolicy

Sorry, missed one of the test resources. Ran `mvn test` on the whole component, all seems to pass now.

**Comment by davsclaus** [comment]
Can you add a section about this change to the 4.7 upgrade doc at
https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc

**Review by oscerd — APPROVED** [review]

**Pull request merged**
