### PR TITLE
fix multi-value property lost problem

### PR DESCRIPTION
**Pull request by EvanMi**
# Description

the multi-value property is lost

# Target

we should put the key from a multi-value (prefix) in the properties too, or the property may be lost

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you point to an example or use-case where you had a problem? And if we agree its a bug then we need a JIRA to track this and for backports too.

**Comment by EvanMi** [comment]
> Can you point to an example or use-case where you had a problem? And if we agree its a bug then we need a JIRA to track this and for backports too.

yeah, 
blabla...
<toD uri="https://camel.apache.org?okStatusCodeRange=200-500&amp;httpClient.socketTimeout=60000&amp;bar=bar"></toD>
blabla...

on the above route, the "bar" param will be add to header, "okStatusCodeRange" will be suitable set, but "httpClient.socketTimeout" will lost.

> Can you point to an example or use-case where you had a problem? And if we agree its a bug then we need a JIRA to track this and for backports too.

yeah, 
blabla...
<toD uri="https://camel.apache.org?okStatusCodeRange=200-500&amp;httpClient.socketTimeout=60000&amp;bar=bar"></toD>
blabla...

on the above route, the "bar" param will be add to header, "okStatusCodeRange" will be suitable set, but "httpClient.socketTimeout" will lost.

**Comment by davsclaus** [comment]
Thanks for that, can you create a JIRA and if possible add an unit test

**Comment by EvanMi** [comment]
> Thanks for that, can you create a JIRA and if possible add an unit test

ok,i'll do both

**Comment by davsclaus** [comment]
Thank you very much

**Review by davsclaus — APPROVED** [review]

**Comment by EvanMi** [comment]
> we should put the key from a multi-value (prefix) in the properties too, or the property may be lost

i've add the unit test and JIRA https://issues.apache.org/jira/browse/CAMEL-19663

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Thanks I had to merge this manually to resolve some regens

**Comment by EvanMi** [comment]
> Thanks I had to merge this manually to resolve some regens

ok, but i found you missed the toD.json. or it's really should be "turn of" but not "turn off"

**Comment by davsclaus** [comment]
> > Thanks I had to merge this manually to resolve some regens
> 
> ok, but i found you missed the toD.json. or it's really should be "turn of" but not "turn off"

You need to fix this in the java source code - the json file is auto generated

**Pull request closed without merging**
