### PR TITLE
CAMEL-14180: Upgrade maven-checkstyle-plugin

### PR DESCRIPTION
**Pull request by zregvart**
Created to see if it'll pass the CI checks.

### CODE REVIEW

**Comment by zregvart** [comment]
Link to the [CI build](https://builds.apache.org/view/C/view/Apache%20Camel/job/Camel/job/CAMEL-14180/1/).

**Comment by oscerd** [comment]
It seems there is more work to do https://builds.apache.org/view/C/view/Apache%20Camel/job/Camel/job/CAMEL-14180/1/console

**Comment by zregvart** [comment]
I was grepping the output and failed to see the error. Even when I upgraded the Checkstyle DTD to the one supporting `suppress-xpath` the checks failed as the check I wanted to suppress (ImportOrder) is not supported for XPath filtering.

I have a successful build locally and I'll update this branch shortly.

**Comment by zregvart** [comment]
This has [passed](https://builds.apache.org/view/C/view/Apache%20Camel/job/Camel/job/CAMEL-14180/2/) the Checkstyle stage on CI, I'm going to merge this now.

**Pull request merged**
