### PR TITLE
CAMEL-15361 Use predictible doc page name for threadpoolfactory-vertx

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by davsclaus** [comment]
The doc files should be the name of the artifact (without the camel- prefix) when its not a component.

So the old name was correct.

**Comment by davsclaus** [comment]
But the thread pool factory name is wrong

❯ ls src/main/docs
reactive-threadpoolfactory-vertx.adoc
  ~/workspace/camel/components/camel-threadpoolfactory-vertx   master ❯

That should be

threadpoolfactory-vertx

**Comment by ppalaga** [comment]
Oh f***, I renamed the wrong one?!?!

**Comment by ppalaga** [comment]
Thanks catching it, @davsclaus ! a1d73c8 should be OK.

**Pull request merged**
