### PR TITLE
CAMEL-12293: Avoid KeyAlreadyExistsException for listTypeConverters JMX operation

### PR DESCRIPTION
**Pull request by jamesnetherton**
https://issues.apache.org/jira/browse/CAMEL-12293

### CODE REVIEW

**Comment by davsclaus** [comment]
I think we should skip adding if there are duplicates - a duplicate is not really intended to exists. The registry should have detected this and you can only do 
- override
- ignore
- fail
(see TypeConverterExists)

So I wonder how you got duplicates in the first place. Is it something about WildFly?

**Comment by jamesnetherton** [comment]
Yeah It's something I noticed on WildFly. With the Camel subsystem, all components are available on the classpath by default (hence all type converters).

I guess skip adding would be better. But, let me have a quick check why duplicates aren't detected in the first instance.

**Comment by jamesnetherton** [comment]
Think I nailed down what's going on....

Both camel-elasticsearch and camel-elasticsearch5 are on the classpath and their `TypeConverter` handles Elasticsearch types with the same class name.

`BaseTypeConverterRegistry` keys things on Class, where as when `ManagedTypeConverterRegistry` creates `CompositeData`, it uses the string representation of the from & to class name. Hence it'll encounter duplicates when processing the elasticsearch converters.

I see camel-elasticsearch(5) is deprecated so I can remove support for these on the wildfly-camel side. Just wondering if it'd still be worth adding a check for duplicates in `ManagedTypeConverterRegistry`? It's a bit of an edge case but it could happen.

**Comment by davsclaus** [comment]
Ah thanks for digging into the issue. Yeah so maybe we should just skip the duplicate keys in the JMX.

**Comment by jamesnetherton** [comment]
Thanks for the feedback. I pushed a simple duplicate check onto master.

**Pull request closed without merging**
