### PR TITLE
(chores) More of replacing inner classes with lambda

### PR DESCRIPTION
**Pull request by gilvansfilho**
Solving some sonar issues about [replacing inner classes with lambdas](https://rules.sonarsource.com/java/tag/java8/RSPEC-1604).

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by gilvansfilho** [comment]
What about `PR Build (Camel 4) / checkstyle (pull_request)` ? I have ran checkstyle and did not give nothing.

**Comment by oscerd** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle (default-cli) on project camel-parent: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.camel:camel-buildtools:jar:4.0.0-SNAPSHOT from/to apache.snapshots (https://repository.apache.org/snapshots/): transfer failed for https://repository.apache.org/snapshots/org/apache/camel/camel-buildtools/4.0.0-SNAPSHOT/camel-buildtools-4.0.0-SNAPSHOT.jar, status: 502 Proxy Error -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle (default-cli) on project camel-parent: Execution default-cli of goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:checkstyle failed: Plugin org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.camel:camel-buildtools:jar:4.0.0-SNAPSHOT from/to apache.snapshots (https://repository.apache.org/snapshots/): transfer failed for https://repository.apache.org/snapshots/org/apache/camel/camel-buildtools/4.0.0-SNAPSHOT/camel-buildtools-4.0.0-SNAPSHOT.jar, status: 502 Proxy Error

There is a scheduled maintenance on Nexus Repository in Apache.

**Comment by orpiske** [comment]
> I accidentally closed PR.

No worries. It LGTM, but as this one is open for a few days, you might need to rebase it.

**Comment by orpiske** [comment]
Merging, the PR was already up-to-update upon reopening and the tests ran fine.

**Pull request merged**
