### PR TITLE
Huawei Doc Title Updates

### PR DESCRIPTION
**Pull request by hokutor**
Removing Huawei Cloud prefix for each component to reduce the long component naming. Huawei Cloud will only be shown in the title of the parent documentation page.

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
Sorry we cannot do this as the titles are too generic, eg Simple Notification System. You must have Huawei as prefix, eg we have Google, AWS, Azure for the other cloud providers.

**Comment by davsclaus** [comment]
You can maybe consider Huawei instead of Huawei Cloud to make it a little bit shorter

**Comment by hokutor** [comment]
> Sorry we cannot do this as the titles are too generic, eg Simple Notification System. You must have Huawei as prefix, eg we have Google, AWS, Azure for the other cloud providers.

Yes, I think you are right. Will update the PR

**Comment by davsclaus** [comment]
merged

**Pull request closed without merging**
