### PR TITLE
CAMEL-10914: CxfConsumer doesn't clean up the CXF endpoint MBean upon stop

### PR DESCRIPTION
**Pull request by tadayosi**
https://issues.apache.org/jira/browse/CAMEL-10914

### CODE REVIEW

**Comment by davsclaus** [comment]
Looks good to me @oscerd do you mind review and merge to older branches

**Comment by oscerd** [comment]
Sure

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by tadayosi** [comment]
Thanks @davsclaus and @oscerd!

**Pull request closed without merging**
