### PR TITLE
CAMEL-11332: Create a new camel-thrift data format

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by davsclaus** [comment]
Just a note that we need to fix https://issues.apache.org/jira/browse/CAMEL-11369 first before merging this PR

**Comment by dmvolod** [comment]
Ok, will wait for fix or will find a time to fix...

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by dmvolod** [comment]
Thanks, PR closed

**Pull request closed without merging**
