### PR TITLE
Upgrade to couchbase 7.2.0 container image

### PR DESCRIPTION
**Pull request by davsclaus**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
It seems this PR has some of the same docker errors as before with something about not starting up the couchbase container

**Comment by orpiske** [comment]
> It seems this PR has some of the same docker errors as before with something about not starting up the couchbase container

Yeah. Couchbase is one hell of a pain to upgrade. I think there's a ticket about problems with it.

**Comment by orpiske** [comment]
Here: https://issues.apache.org/jira/browse/CAMEL-19228

**Comment by orpiske** [comment]
Looking at the logs: it seems that there is some change on 7.2.0 which breaks the container initialization check on TestContainers.

**Comment by davsclaus** [comment]
closing old PRs

**Pull request closed without merging**
