### PR TITLE
CAMEL-14137 Thread leak in camel-jetty component if maxThreads or min…

### PR DESCRIPTION
**Pull request by luigidemasi**
…Threads property is set

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks just need the license header in the unit test source code

**Comment by davsclaus** [comment]
Is this also a problem on master branch? And if so can you create a new PR for that too ?

**Comment by oscerd** [comment]
It's already merged on master.

**Comment by luigidemasi** [comment]
> Is this also a problem on master branch? And if so can you create a new PR for that too ?



already done, this is a backport  of [3315](https://github.com/apache/camel/pull/3315
)

**Pull request merged**
