### PR TITLE
CAMEL-10726 Correlation of JMS InOut exchanges ...

### PR DESCRIPTION
**Pull request by zregvart**
...with custom JMS property

This commit adds a new configuration option `correlationProperty` if set
its value will be used instead of `JMSCorrelationID` JMS message
property to correlate messages in InOut (request-reply) exchange.

Also, if this `correlationProperty` is set, `JMSCorrelationID` will not
be consulted on the incoming message or set on the outgoing message.

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you make it configurable on the component level also, eg JmsComponent

**Comment by zregvart** [comment]
Thanks for looking at this @davsclaus, I've added a setter in the `JmsComponent` in 0bcd31a.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by zregvart** [comment]
Thanks @davsclaus :+1:

**Pull request closed without merging**
