### PR TITLE
CAMEL-19314 - Fixing the connection pool shutdown when aws health checks are used

### PR DESCRIPTION
**Pull request by rhuan080**
# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Comment by davsclaus** [comment]
Does this create a new client for each health check call?

**Comment by davsclaus** [comment]
I would assume for health-checks we should reuse the existing client, and NOT close it when check is done. 
Creating a new client is "expensive" as you then setup a new connection to the cloud.

**Comment by rhuan080** [comment]
I'll create a separated client for the health checker and reuse it. I'll send a commit to change it

**Comment by simon-ras** [comment]
The reporter of https://issues.apache.org/jira/browse/CAMEL-19281 claimed that they saw a connection leak from the original implementation. Would it be possible to maybe verify this before making further changes?

We manage our aws clients as Spring beans and our client shouldn't not be shut down before the spring context is destroyed. We are heavily using the SNS and SQS camel components across many services and have not seen any connection leaks on version 3.20.2.

**Comment by rhuan080** [comment]
Hi @simon-ras, 

I have reviewed the changes applied on https://issues.apache.org/jira/browse/CAMEL-19281 and I have seen a potential connection leak to KinesisClient only. I agree the client should not be shut down. However, this fix will solve the problem of closing connections. I think after applying this fix we can back to https://issues.apache.org/jira/browse/CAMEL-19281 and ask to the customer for a reproducer and further information.

**Comment by rhuan080** [comment]
Now, after reviewing the https://issues.apache.org/jira/browse/CAMEL-19281, I'm not sure the KinesisClient is used by the reporter, then I'm not sure the issue is generated by the health checker. However, I think we can apply this fix to solve the close connection.

**Comment by simon-ras** [comment]
The proposed PR does not work for injected clients. I would suggest reverting the previous "fix" instead.

**Comment by rhuan080** [comment]
Thus, I will revert the connections and apply a fix just to KinesisClient, as it has an real scenario of connection leak.

**Comment by davsclaus** [comment]
Is this PR ready to be merged?

**Comment by rhuan080** [comment]
Hi, @davsclaus 

Yes, we can merge this.

**Comment by simon-ras** [comment]
> This PR also need to be backported into 3.20.x as all AWS components are broken on that branch.

I just realized that this was already done!

**Pull request merged**
