### PR TITLE
Add option to use Java 1.8 `Optional<?>` for POJO fields

### PR DESCRIPTION
**Pull request by sirlatrom**
Also upgrades to Jackson 2.x to allow injecting a custom `ObjectMapper` into `SalesforceEndpointConfig`, which in turn allows registering the `Jdk8Module` when using Java 1.8, which handles (de)serializing of `Optional<?>` in a reasonable manner. Jackson 1.x does not have the `Jdk8Module`.

Note that this requires that the project using the plugin is itself using Java 1.8+.

To use `Jdk8Module`, add this dependency:
```xml
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jdk8</artifactId>
		</dependency>
```

Then configure a custom `ObjectMapper` like the following snippet:
```java
import org.apache.camel.component.salesforce.SalesforceEndpointConfig;
...
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
...
	@Bean
	public SalesforceEndpointConfig salesforceEndpointConfig() {
		SalesforceEndpointConfig salesforceEndpointConfig = new SalesforceEndpointConfig();
		...
		ObjectMapper objectMapper = new ObjectMapper();
		objectMapper.registerModule(new Jdk8Module());
		objectMapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
		salesforceEndpointConfig.setObjectMapper(objectMapper);
		return salesforceEndpointConfig;
	}
```

Signed-off-by: Sune Keller <absukl@almbrand.dk>

### CODE REVIEW

**Comment by sirlatrom** [comment]
@davsclaus This is a bigger one, mainly due to upgrading to Jackson 2.x.

**Comment by davsclaus** [comment]
This upgrade will also require upgrading camel-salesforce in the karaf features xml file
https://github.com/apache/camel/blob/master/platforms/karaf/features/src/main/resources/features.xml#L1386

And can you log a JIRA ticket so we have that to track this change. And it can only be done on master, eg for 2.18.

**Comment by sirlatrom** [comment]
JIRA issue: https://issues.apache.org/jira/browse/CAMEL-10059

**Comment by davsclaus** [comment]
Can you fix the checkstyle errors by running

    /components/camel-salesforce (master)/$ mvn compile -Psourcecheck

**Comment by sirlatrom** [comment]
@davsclaus Checkstyle errors should be fixed now.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
