### PR TITLE
Change SMPP default enquireLinkTimer from 5 seconds to 60 seconds.

### PR DESCRIPTION
**Pull request by pmoerenhout**
- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

Change the default SMPP enquireLinkTime from 5 to 60 seconds. The default of 5 seconds is too aggressive for default connections not specifying an other value.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
LGTM but there is no JIRA issue about this change.

**Comment by pmoerenhout** [comment]
I can create the Jira, no problem, I also see that the sourcecheck failed on the imports. Will redo the PR...

**Comment by oscerd** [comment]
The sourcecheck is failing for another commit, the jira is not really needed, I was noticiing this because you marked the first point of PR template

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by PascalSchumacher** [comment]
+1, at work we also changed it to 60 seconds years ago, because the SMSC colleagues complained about the 5 second interval.

**Pull request merged**
