### PR TITLE
CAMEL-16882 Add ddl sql output in header

### PR DESCRIPTION
**Pull request by wingerx**
issue links: https://issues.apache.org/jira/browse/CAMEL-16882

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
Looks good to me, can you briefly explain the use case anyway?

**Comment by wingerx** [comment]
To support downstream decide what to do with this ddl SQL from DBZ connector instead of discarding it directly

**Comment by davsclaus** [comment]
Should the header key be DDLSQL to better reflect its the kind of SQL and not just "whatever SQL"

**Comment by wingerx** [comment]
> Should the header key be DDLSQL to better reflect its the kind of SQL and not just "whatever SQL"

got it, tks

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Pull request merged**
