### PR TITLE
CAMEL-12674 - upgrade sshd-core and replace it specific ones by versi…

### PR DESCRIPTION
**Pull request by onderson**
…on 2.0.0

### CODE REVIEW

**Comment by onderson** [comment]
Checked but had a different issue. Will check after fixing up my local issue

**Comment by onderson** [comment]
karaf is ok but not sure about spring-boot because the test hangs up in my vm and i don't have a clue now.

**Comment by onderson** [comment]
@oscerd , do you have any idea why the test may hang on local box?

**Comment by oscerd** [comment]
I'll test the PR tomorrow and check the SB tests

**Comment by oscerd** [comment]
In my case the test for ftp and jsch on SB are not hanging, but they fail.

**Comment by onderson** [comment]
even this hangs.. is this what you do?

camel\tests\camel-itest-spring-boot% mvn -Dtest=CamelSshTest test

**Comment by oscerd** [comment]
Since this is for 2.23.0 we can merge this stuff if unit tests and karaf tests are ok and then check the Spring-boot part

**Comment by onderson** [comment]
Is it corresponding to your case?

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 351.747 sec <<< FAILURE! - in org.apache.camel.itest.springboot.CamelSshTest
org.apache.camel.itest.springboot.CamelSshTest  Time elapsed: 351.745 sec  <<< ERROR!
java.lang.RuntimeException: Could not invoke deployment method: public static org.jboss.shrinkwrap.api.Archive org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage() throws java.lang.Exception
        at org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage(CamelSshTest.java:32)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.apache.camel:camel-starter-parent:pom:2.23.0-SNAPSHOT
        at org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage(CamelSshTest.java:32)
Caused by: org.apache.maven.model.resolution.UnresolvableModelException: Could not transfer artifact org.apache:apache:pom:20 from/to central (http://repo1.maven.org/maven2/): Connect to repo1.maven.org:80 timed out
        at org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage(CamelSshTest.java:32)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact org.apache:apache:pom:20 from/to central (http://repo1.maven.org/maven2/): Connect to repo1.maven.org:80 timed out
        at org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage(CamelSshTest.java:32)
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.apache:apache:pom:20 from/to central (http://repo1.maven.org/maven2/): Connect to repo1.maven.org:80 timed out
        at org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage(CamelSshTest.java:32)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to repo1.maven.org:80 timed out
        at org.apache.camel.itest.springboot.CamelSshTest.createSpringBootPackage(CamelSshTest.java:32)


Results :

Tests in error:
  CamelSshTest.org.apache.camel.itest.springboot.CamelSshTest » Runtime Could no...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

**Comment by oscerd** [comment]
No I don't have errors of downloading from maven repo.

**Comment by nicolaferraro** [comment]
I'll have a look..

**Comment by nicolaferraro** [comment]
@onderson the test works, so I think there is a issue with the proxy. Maybe you can merge this and open a issue for the proxy problem.

**Comment by oscerd** [comment]
We can go ahead then.

**Comment by onderson** [comment]
btw, @nicolaferraro camel-ssh SB itest is OK.
camel-jsch and camel-ftp tests are broken after this PR. tried again with mvn -U. no change yet.
it seems requiring deep dive in camel-itest-spring-boot.

**Comment by nicolaferraro** [comment]
I switched to your branch, did a full Camel "mvn clean install -P fastinstall" and ran the itest-springboot as "mvn clean install -Dtest=CamelJschTest", everything fine.

Your exception is not so clear, but I think there's something dirty in your environment. The spring-boot itests use the starters, so make sure they are fully built and run the tests with "clean" to remove cached resolved artifacts from previous runs.

**Comment by onderson** [comment]
Thanks @nicolaferraro. In case of clean build, it is ok.

**Pull request merged**
