### PR TITLE
Elasticsearch Component, Let BulkRequest return the whole BulkResponse.

### PR DESCRIPTION
**Pull request by segalziv**
Hi, sorry if I'm not following the right PR procedure. I would like to contribute and learn the right process. 

I'm creating this PR to suggest a better return value for elasticsearch bulk-request operation. 

I found out that I needed to get more information from the bulk-request result. elasticsearch provides the BulkResponse with the full info. returning the full BulkResponse allows the caller to tell the reason of index failures and more.

### CODE REVIEW

**Comment by segalziv** [comment]
Closing this PR for now, as I got no feedback on it.

**Comment by oscerd** [comment]
If you look at this issue on Apache Camel JIRA, https://issues.apache.org/jira/browse/CAMEL-8299, you'll see your PR has been merged, https://github.com/apache/camel/commits?author=segalziv.

Everything is ok. Always take a look at the Apache Camel JIRA and open an issue on the JIRA before submitting a PR on Github (link that PR to the JIRA ticket).

**Comment by segalziv** [comment]
@oscerd thanks for the update!

I wasn't aware of the Apache Camel JIRA. I will take this discussion there.

**Comment by oscerd** [comment]
You're welcome. I'm happy to help.

**Pull request closed without merging**
