### PR TITLE
CAMEL-12087: camel-core: WARN No CamelContext defined yet so cannot inject into bean

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by oscerd** [comment]
@davsclaus, since this is a bug I'm thinking about backporting it on 2.21.x and 2.22.x. Does it work for you?

**Comment by oscerd** [comment]
Maybe it's better to change to debug?

**Comment by lburgazzoli** [comment]
If there's no objection, I'm going to merge it. the log level can be changed later

**Comment by oscerd** [comment]
Go for it

**Pull request merged**
