### PR TITLE
CAMEL-11695: Add JWT algorithm and move to separate parameters class

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by davsclaus** [comment]
Hmm beforehand its easier to configure because you can set plain options in the endpoint uri, now you need to create that jwt class and have to bind it to the registry etc.

What is the benefit, I don't yet see it

**Comment by dmvolod** [comment]
With the addition of new parameters and types, there will be more variables, which will complicate the configuration. However, I could back parameters structure back to the UriParam, just keep new algorithm property.

**Comment by davsclaus** [comment]
Yeah that sounds better. Ideally there is one configuration class which holds them all. It makes things easier from tooling, end users, and whatnot.

**Comment by dmvolod** [comment]
Okya, will return back soon without additional classes.

**Comment by dmvolod** [comment]
Updated. @davsclaus , please review.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by dmvolod** [comment]
PR closed, thank you.

**Pull request closed without merging**
