### PR TITLE
CAMEL-12554 - camel-geocoder - Use new API

### PR DESCRIPTION
**Pull request by onderson**
linked to #2415

### CODE REVIEW

**Comment by oscerd** [comment]
I'm fixing the Karaf feature. It wasn't updated.

**Comment by oscerd** [comment]
We need to take a look at the camel-example-spring-boot-geocoder I fixed the code, but it doesn't seem to work correctly even by passing clientId and secret. @onderson @jborza

**Comment by oscerd** [comment]
The build was broken

**Comment by jborza** [comment]
sure - I can look at the camel-example-spring-boot-geocoder.

**Pull request merged**
