### PR TITLE
CAMEL-9649: Do not require @XmlRootElement annotation in JAXB FallbackTypeConverter

### PR DESCRIPTION
**Pull request by basovnik**
https://issues.apache.org/jira/browse/CAMEL-9649

### CODE REVIEW

**Comment by basovnik** [comment]
@davsclaus, could you please check my fix before I amend my commit? I am not sure how to call `context#getClassResolver()` when exchange is `null`. So I use context only in case exchange is set. If it is not set I use `org.apache.camel.util.ObjectHelper#loadClass()`.

I created `ThreadLocal<CamelContext>` to do no change API of `protected` methods, is it ok? Is this class expected to be thread-safe?

fix: https://gist.github.com/basovnik/0ac4c0742c291f39bfc3

**Comment by davsclaus** [comment]
Ah can you try implementing CamelContextAware in the class. Ideally we should let Camel inject itself to these type converters if they impl that interface, so you have access to Camel.

**Comment by basovnik** [comment]
I fixed it. New version of patch is on the same link as before. If it is ok, I will amend it if not, fell free to add new comments.

**Comment by davsclaus** [comment]
Yep looks much better. You are welcome to update this PR

**Comment by davsclaus** [comment]
Thanks the code has been merged. Can you close this PR

**Pull request closed without merging**
