### PR TITLE
Camel 16643

### PR DESCRIPTION
**Pull request by aldettinger**

### CODE REVIEW

**Review by oscerd — APPROVED** [review]
This may have impact on the karaf features too.

**Comment by oscerd** [comment]
Can you give a look at Karaf features?

**Comment by aldettinger** [comment]
Sorry, I missed the first comment, let me have a look at karaf features.

**Comment by aldettinger** [comment]
@oscerd I think karaf features are ok. I've built features and found no WARN related to this PR. Then, I've repo-add, feature:install camel-saxon, camel-soap and camel-xslt-saxon to Karaf 4.2.6. All bundles are Active, and there are no error messages.

**Comment by oscerd** [comment]
Thanks for checking.

**Pull request merged**
