### PR TITLE
CAMEL-14597 fix the IllegalAccessException when private default const…

### PR DESCRIPTION
**Pull request by xldai**
…ructor

### CODE REVIEW

**Comment by davsclaus** [comment]
Instead can you create an unit test in camel-test-blueprint

**Comment by xldai** [comment]
Claus, the test line added into the BlueprintBeanInjectRoute. you will get the IllegalAccessException as shown below:

-------------------------------------------------------------------------------
Test set: org.apache.camel.test.blueprint.BeanInjectTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 6.481 s <<< FAILURE! - in org.apache.camel.test.blueprint.BeanInjectTest
testBeanInject(org.apache.camel.test.blueprint.BeanInjectTest)  Time elapsed: 2.15 s  <<< ERROR!
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[ID-tal-xldai-1582534317134-1-1]
	at org.apache.camel.test.blueprint.BeanInjectTest.testBeanInject(BeanInjectTest.java:32)
Caused by: org.apache.camel.RuntimeCamelException: java.lang.IllegalAccessException: Class org.apache.camel.util.ObjectHelper can not access a member of class java.lang.System with modifiers "private"
	at org.apache.camel.test.blueprint.BeanInjectTest.testBeanInject(BeanInjectTest.java:32)
Caused by: java.lang.IllegalAccessException: Class org.apache.camel.util.ObjectHelper can not access a member of class java.lang.System with modifiers "private"
	at org.apache.camel.test.blueprint.BeanInjectTest.testBeanInject(BeanInjectTest.java:32)

**Comment by davsclaus** [comment]
Thanks for the test case

**Comment by davsclaus** [comment]
You can use `${bean:type:java.lang.System?method=currentTimeMillis}` eg the bean type to refer to the FQN class type which wont create an instance

**Comment by davsclaus** [comment]
Ok see comment on JIRA, closing

**Comment by xldai** [comment]
yes, I know the bean:type but for older versions e.g. 2.23.x, it's not supported unfortunately.

Caused by: org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: type:java.lang.System
	at org.apache.camel.test.blueprint.BeanInjectTest.testBeanInject(BeanInjectTest.java:32)

**Comment by davsclaus** [comment]
2.23 is EOL. And you can use .method(System.class, "curretTimeMillis") which is also more correct

**Comment by xldai** [comment]
Did the same test with "bean:type" on 3.0.1, but failed with the same NoSuchBeanException.

Caused by: org.apache.camel.NoSuchBeanException: No bean could be found in the registry for: type:java.lang.System
	at org.apache.camel.test.blueprint.BeanInjectTest.testBeanInject(BeanInjectTest.java:32)

**Pull request closed without merging**
