### PR TITLE
Backport of SPI security provider for camel-undertow

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Backport of several features involving UndertowSpringSecurity interface.

Cherry-picked from 9784e2841b382f16cc81f11be487bd09b26e7918, dbf68d8b6eb02ea8a3b3b526221485277ee0842c, a77ee789aad3cf2093e54db901a1400c93b17fe6 and a630a37502ca90b4f3e7589822f6ee52066817a4
+ several changes because of backport

Here is example of the use: https://github.com/JiriOndrusek/reproducers/tree/master/undertow_keycloak_camel_bearer_spring_security5_provider
example + usage (starter) is covered by https://issues.apache.org/jira/browse/CAMEL-14962

@davsclaus I'm not sure what version to use in documentation for undertow-spring-security. It now contains version 3.3 but it is not probably correct, as I'm backporting it into 2.25

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by JiriOndrusek** [comment]
I forgot to fix style, I'll prepare it in a moment

**Comment by oscerd** [comment]
I didn't notice you were pointing 2.25.x, here it doesn't make sense to add this.

**Comment by oscerd** [comment]
You can close this, thanks and sorry.

**Comment by JiriOndrusek** [comment]
this PR is not needed in this branch, closing

**Pull request closed without merging**
