### PR TITLE
CAMEL-10491 - Spring-LDAP - Add support for authenticate, modify_attributes and function_driven operations 

### PR DESCRIPTION
**Pull request by bhaveshdt**
Please pay special attention to the newly added FUNCTION_DRIVEN operation.

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks. I will review and merge tomorrow :-)

**Comment by oscerd** [comment]
Thanks. The PR has been merged. 

Can you add the description of the new operations here?

https://github.com/apache/camel/blob/master/components/camel-spring-ldap/src/main/docs/spring-ldap-component.adoc

Maybe with a new PR?

Thanks a lot :-)

**Comment by oscerd** [comment]
Can you please close this PR and open a new one with the docs update? Just to avoid confusion.

Thanks.

**Comment by bhaveshdt** [comment]
Hey Andrea

I wasn't aware of this file although it has now been updated and pushed. 

Thanks.

**Comment by bhaveshdt** [comment]
Oops, I just noticed your comment about opening a new PR. Are you still wanting me to create a new one?

**Comment by oscerd** [comment]
Yes, if you can :-)

**Comment by bhaveshdt** [comment]
Not a problem. Just created a new one @ https://github.com/apache/camel/pull/1286 :)

**Pull request closed without merging**
