### PR TITLE
CAMEL-11704

### PR DESCRIPTION
**Pull request by cschachinger**
This PR allows a queue to be declared "passively".

### CODE REVIEW

**Comment by oscerd** [comment]
Thanks, I will review soon.

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close this?

For the next PRs (I hope there will be others :-) ) can you please run:

```bash
mvn -Psourcecheck
```
and fix the codestyle and then

```
mvn clean install
```

to eventually update the docs generated automatically?

Thanks :-)

**Comment by cschachinger** [comment]
Ok, thank. What about the conflicts, don't they need to be resolved?

**Comment by oscerd** [comment]
It is already merged. The conflicts are related to the fix I've done to fix the code style.

**Comment by cschachinger** [comment]
ah, I see. Thanks for your time!.

**Comment by oscerd** [comment]
Thanks to you for the contribution :-)

**Pull request closed without merging**
