### PR TITLE
CAMEL-6766 Generated produces string now includes media types from all responses

### PR DESCRIPTION
**Pull request by calleandersson**
# Description

Changed the behavior to include media types from all existing responses when generating produces string. Information about previous behavior can be seen in [issue 6776](https://github.com/apache/camel-quarkus/issues/6766).

Of some reason, I wasn't able to download artifacts from https://repository.apache.org/snapshots so I have not been able to run `mvn clean install -DskipTests`.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by davsclaus** [comment]
https://issues.apache.org/jira/browse/CAMEL-21430

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Can you fix code formatting issue in

--- a/components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/OpenApiUtilsTest.java
+++ b/components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/OpenApiUtilsTest.java

**Comment by calleandersson** [comment]
Sorry, created a Camel Quarkus issue instead of a Camel issue by mistake.

Of some reason, I'm not able to connect to https://repository.apache.org at the moment which means I have not been able to run `mvn clean install -DskipTests`. Therefor I don't get the automatically formatting. Is there a way to execute the formatting without having to run `mvn clean install`?

**Comment by calleandersson** [comment]
I removed the empty line mentioned [here](https://github.com/apache/camel/actions/runs/11777527033/job/32803652714#step:8:27). Do I have to wait for some automatically job to see if there are some more formatting issues or could I trigger some job myself?

**Pull request merged**
