### PR TITLE
CAMEL-5583 - Add ning-compress as data format

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by davsclaus** [comment]
See for example camel-zipfile as an example.

**Comment by lburgazzoli** [comment]
Ok so:
- create a new component camel-lzf 
- name it LZFDataFormat
- this won't be part of DataFormatClause

correct ?

**Comment by davsclaus** [comment]
1 and 2 = yes, 3 = no. In camel-core you add it to the model / fluent builder etc. Take a look at how zipfile do it in camel-core.

Yes building a data format is a bit harder than a component as you need to add some bits in camel-core for it.

**Comment by lburgazzoli** [comment]
Ok, I will clsoe this PR and rework the code.

Thx Claus

**Comment by lburgazzoli** [comment]
@davsclaus should I create camel-lzf and camel-lzffile ?

**Comment by davsclaus** [comment]
camel-lzf

**Pull request closed without merging**
