### PR TITLE
CAMEL-12607: When using Tokenizer skipFirst java.util.NoSuchElementException if only one element [will merge after 2.22.0 release]

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by oscerd** [comment]
LGTM l'età wait for release

**Comment by dmvolod** [comment]
Thanks, @oscerd , yes, will wait for release to avoid conflicts with build process

**Comment by oscerd** [comment]
You can merge it, I guess.

**Comment by dmvolod** [comment]
@oscerd , thanks, merged.

**Pull request closed without merging**
