### PR TITLE
CAMEL-16001 -  huawecloud camel-smn component

### PR DESCRIPTION
**Pull request by mathewsreji**
SMN is one among the Cloud product offering within HuaweiCloud ecosystem which enables cloud application users to broadcast/send out notifications to subscribers. It provides a single unified endpoint aka. topic for the application to push data.

Multiple subscribers can be associated with a given topic. Simple Message Notification (SMN) enables you to broadcast messages to subscribers who can chose to receive the notifications via an email addresses, phone numbers, serverless functions and HTTP/HTTPS servers and connect cloud services through notifications, reducing system complexity and developmental efforts to the publishing app.

- [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ ] Each commit in the pull request should have a meaningful subject line and body.
- [ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Review by oscerd — COMMENTED** [review]
This is a new component. It can only be merged on master

**Comment by oscerd** [comment]
This is a new component. It can only be merged on master

**Comment by oscerd** [comment]
Please open a PR against master branch

**Comment by mathewsreji** [comment]
@oscerd - thanks for the comment. I will raise a fresh PR shortly against the master branch.

**Comment by mathewsreji** [comment]
Fresh PR raised at https://github.com/apache/camel/pull/4900

**Pull request closed without merging**
