### PR TITLE
CAMEL-12943: Rest DSL generates invalid swagger operation Id

### PR DESCRIPTION
**Pull request by dmvolod**
@tdiesler , could you please to look at the PR, but RestSwaggerReaderEnableVendorExtensionTest which was failing also seem to be this issue test.

### CODE REVIEW

**Comment by tdiesler** [comment]
This patch seems to fix the contentID issue, but is still not working for nested context paths

```
09:28:45,428 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-2) MSC000001: Failed to start service jboss.deployment.unit."UndertowSecureRestDslSpringIntegrationTest3.war".CamelContextActivationService."UndertowSecureRestDslSpringIntegrationTest3.war": org.jboss.msc.service.StartException in service jboss.deployment.unit."UndertowSecureRestDslSpringIntegrationTest3.war".CamelContextActivationService."UndertowSecureRestDslSpringIntegrationTest3.war": Cannot create camel context: UndertowSecureRestDslSpringIntegrationTest3.war
	at org.wildfly.extension.camel.service.CamelContextActivationService.start(CamelContextActivationService.java:71)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1736)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1698)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1556)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.msc.service.StartException in anonymous service: Cannot start camel context: secure-rest-context2
	at org.wildfly.extension.camel.service.CamelContextActivationService.start(CamelContextActivationService.java:67)
	... 8 more
Caused by: org.apache.camel.RuntimeCamelException: java.lang.IllegalStateException: Cannot add io.undertow.server.HttpHandler for path /test defined in deployment.UndertowSecureRestDslSpringIntegrationTest3.war because that path is already served by deployment.UndertowSecureRestDslSpringIntegrationTest1.war
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1826)
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:136)
	at org.wildfly.extension.camel.service.CamelContextActivationService$1.run(CamelContextActivationService.java:63)
	at org.wildfly.extension.camel.proxy.ProxyUtils$1.invoke(ProxyUtils.java:51)
	at com.sun.proxy.$Proxy88.run(Unknown Source)
	at org.wildfly.extension.camel.proxy.ProxyUtils.invokeProxied(ProxyUtils.java:55)
	at org.wildfly.extension.camel.service.CamelContextActivationService.start(CamelContextActivationService.java:60)
	... 8 more
Caused by: java.lang.IllegalStateException: Cannot add io.undertow.server.HttpHandler for path /test defined in deployment.UndertowSecureRestDslSpringIntegrationTest3.war because that path is already served by deployment.UndertowSecureRestDslSpringIntegrationTest1.war
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$WildFlyUndertowHost.validateEndpointContextPath(CamelUndertowHostService.java:211)
	at org.wildfly.extension.camel.undertow.CamelUndertowHostService$WildFlyUndertowHost.validateEndpointURI(CamelUndertowHostService.java:170)
	at org.apache.camel.component.undertow.UndertowComponent.registerEndpoint(UndertowComponent.java:336)
	at org.apache.camel.component.undertow.UndertowConsumer.doStart(UndertowConsumer.java:77)
	at org.wildfly.extension.camel.undertow.WildFlyUndertowComponent$WildFlyUndertowUndertowConsumer.doStart(WildFlyUndertowComponent.java:86)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
	at org.apache.camel.impl.DefaultCamelContext.startService(DefaultCamelContext.java:3709)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRouteConsumers(DefaultCamelContext.java:4027)
	at org.apache.camel.impl.DefaultCamelContext.doStartRouteConsumers(DefaultCamelContext.java:3962)
	at org.apache.camel.impl.DefaultCamelContext.safelyStartRouteServices(DefaultCamelContext.java:3882)
	at org.apache.camel.impl.DefaultCamelContext.doStartOrResumeRoutes(DefaultCamelContext.java:3646)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:3489)
	at org.apache.camel.impl.DefaultCamelContext$4.call(DefaultCamelContext.java:3248)
	at org.apache.camel.impl.DefaultCamelContext$4.call(DefaultCamelContext.java:3244)
	at org.apache.camel.impl.DefaultCamelContext.doWithDefinedClassLoader(DefaultCamelContext.java:3267)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:3244)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:72)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:3160)
	at org.apache.camel.spring.SpringCamelContext.start(SpringCamelContext.java:133)
	... 13 more
```

You can reproduce this with branch 
https://github.com/wildfly-extras/wildfly-camel/tree/camel-2.23.x

```
mvn clean install -Dts.all -DskipTests
mvn install -Dts.all -pl itests/standalone/basic -Dtest=UndertowSecureRestDslSpringIntegrationTest
```

**Comment by oscerd** [comment]
This is the last issue for 2.23.0, I hope we can fix it before next weekend :-)

**Comment by dmvolod** [comment]
Yes, @oscerd ,sure. I'm trying to fix it, but build of the wildfly-camel fails for me with "Could not resolve dependencies for project org.wildfly.camel:wildfly-camel-feature-modules:pom:8.1.0-SNAPSHOT: Could not find artifact org.kie.remote:kie-remote-client:jar:7.14.0.Final"  seems to be big re-factoring in camel-jbpm

**Comment by oscerd** [comment]
It's not released from a while. We changed a bunch of stuff in camel-jbpm in 2.23.0. @mswiderski do you have any idea about the kie-remote-client dependecies in wildfly-camel?

**Comment by mswiderski** [comment]
kie-remote-client has been removed in v7 of jBPM. Please let me know where is wildfly-camel so I can have a look and provide fix for it

**Comment by mswiderski** [comment]
never mind just found it in the previous comments

**Comment by dmvolod** [comment]
@mswiderski , @oscerd thanks, full rebuild fixed build issue
@tdiesler I reverted all CAMEL-12908 related commits and test it again. The error stack was the same, as files secure-rest1-camel-context.xml and secure-rest3-camel-context.xml contains the separate verbs with same uri="/test". I think this need to be fixed in wildfly-camel.

**Comment by oscerd** [comment]
What's the status of this PR in the end?

**Comment by oscerd** [comment]
@dmvolod once you're available, feel free to merge this PR. Thanks

**Comment by dmvolod** [comment]
@oscerd, yes I will merge it tomorrow.

**Comment by dmvolod** [comment]
@ppalaga , thanks, PR merged.

**Pull request closed without merging**
