### PR TITLE
CAMEL-11927 - Improve support for soap header transformations - [Than…

### PR DESCRIPTION
**Pull request by onders86**
…ks for the PR - Richard Groote(helping to raise a github PR by onders)]

### CODE REVIEW

**Comment by richardgroote** [comment]
Thanx, for creating the pull request

**Comment by onders86** [comment]
@richardgroote , however I am not sure if this is needed OOTB. Because spring-ws component already allows to have custom filter and bind via `messageFilter` endpoint option. This seemed t like a custom implementation to me.
I would go with -1 for this PR.

**Comment by richardgroote** [comment]
Yes, it's possible to define your own message filter. But it would be nice if Apache Camel would support the functionality to transform the soap header before sending the soap message OOTB.

I've seen a lot of use cases by our customers where only adding the headers was not enough.
The soap header contained a lot of extra information when communicating with the external systems.

The solution for our customers was to use the header transformation filter which i supplied in the issue and i thought it might be useful for other users of Apache Camel

**Comment by onders86** [comment]
This was just my first sight. If the community sees the value, it will be good to go. Thanks for the contribution. Keep up the good work

**Comment by davsclaus** [comment]
You need to update the documentation as well.
https://github.com/apache/camel/blob/master/components/camel-spring-ws/src/main/docs/spring-ws-component.adoc

Also I suggest to add javadoc to that filter class where you say that its using XSLT only, which otherwise can take people by surprise. eg to do some transformation using simpler ways.

**Comment by onders86** [comment]
@richardgroote , do you mind adding javadoc so that we can update PR and have it merged?

**Comment by richardgroote** [comment]
See issue for the javadoc

**Comment by onders86** [comment]
@richardgroote , thanks. I have not yet found a time slot to reflect your changes. I will try to look and update and possibly merge your changes at the soonest I can. (sorry i am extremely busy with other stuff at the moment.) thanks

**Comment by onders86** [comment]
@richardgroote reflected your changes. @davsclaus wdyt?

**Comment by davsclaus** [comment]
Yeah this looks fine, thanks

**Pull request merged**
