### PR TITLE
CAMEL-11273: also process routeContext routes in auto ReloadStrategy

### PR DESCRIPTION
**Pull request by ronnyaerts**

### CODE REVIEW

**Comment by onders86** [comment]
I guess you have to branch from master unless no special fix goes to specific branch. Otherwise, hard to review..

**Comment by ronnyaerts** [comment]
I'm not familiar yet with pull requests. 

I re-cloned https://github.com/apache/camel.git to my local machine.
I created a pull request on the github website with number 1693. 
I locally executed a "git pull https://github.com/apache/camel camel-2.19.x" (as the mail suggest) but this went wrong because of "Automatic merge failed; fix conflicts and then commit the result." message. 

I don't know how to continue and my local folder is messed up.

**Comment by davsclaus** [comment]
There is a mini guide how to create a pull request
https://help.github.com/articles/about-pull-requests/

You should usually work against the master branch. The Camel team will backport if necessary and possible.

**Comment by davsclaus** [comment]
So I suggest to try again on a new PR. Your code change should just be 1 commit so the PR should just be 1 change.

**Pull request closed without merging**
