### PR TITLE
Implement chunking of payloads in Camel JMS

### PR DESCRIPTION
**Pull request by JoergKe**
Change-Id: Id8409275395bd49a2148ed21c3dfa4ea7a23708b
Hi,
this is about the JMS component available in Camel. What is currently missing in this component is that it can deal with brokers who limit the message size for queueing. The broker we are using limits the message size but we have to process larger messages. The idea is to cut the message in chunks in the component when the message is sent to the broker and to reassemble it when it is received. This feature can also be used to "stream" messages through brokers that do not support streaming since it is not supported in the JMS standard. The basic idea is that a large message is cut into a head message and several sub messages. The sub messages are later identified by a JMS property in form of GUID. The head messages is also indentified by a special JMS property. It also contains the identifier for the sub messages and it contains the count of the sub messages. The head message is stored last to the queue defined by the user. This ensures that the sub messages are already available when the head message is selected (by a selector).  The sub messages are also stored to the queue. The Camel producer uses a selector on the JMS property to process the head messages. During processing of a head message the sub messages are pulled from the queue using a selector and the complete message is assembled.  
The implementation has some limitations. 
- It only works for Camel payloads that can be converted into an input stream because this format       provides means to cut the message into chunks. 
- It only works in the transacted mode because only this mode garantees that a message can cut into pieces and can be reassembled without the risk of data loss.
- It works only for queues and not for topics since it is difficult if not impossible to garantee that no sub messages can be lost
- For request response pattern only the request is chunked.
  The consumer endpoint is configured as

"jms:queue:hello?maxChunkSize=1000000"

where maxChunkSize is in bytes and defines the maximum message size.
The provider endpoint is the defined as

"jms:queue:hello?chunking=true"

where chunking enables that first only the head messages are selected.
The overhead for message having a size that is smaller than maxChunkSize is low.
The impact on the existing code is surprisingly low. I had to create several 'mini' classes that implement the message creator interface. Before that extension these were anonymous classes. To avoid code duplication those classes were created (I think I also removed some code duplication in the existing code). This is the only bigger change if this feature is not enabled.

I hope you like this extension and I can contribute it to Camel. 

Jörg

### CODE REVIEW

**Comment by aaronjwhiteside** [comment]
Why not use split() and a custom expression/aggregation strategy?

**Comment by JoergKe** [comment]
Hi Aaron,
we also thought about this solution. I think if we had just one scenario we might have used this approach. But the JMS broker shall be used at many places and in conjunction with (reliable) protocol implementations. One always has to take care of preserving the order of the chunks and of transactions.  That seemed to be too complicated and error prone on the long run. In many middlewares the JMS broker or any messaging system is the backbone of the system.
I guess there are many features in Camel components that could also be modeled using Camel. But at one point Java is simpler and faster.

Best Regards,

Jörg

**Comment by aaronjwhiteside** [comment]
The order of the chunks don't/shouldn't matter for aggregate, since you would put the index in the message header when splitting. 

See Exchange interface:
```
    String SPLIT_INDEX        = "CamelSplitIndex";
    String SPLIT_COMPLETE     = "CamelSplitComplete";
    String SPLIT_SIZE         = "CamelSplitSize";
```

So your aggregation strategy should concatenate the pieces together based on the index. Off the top of my head I would say something like storing them in an ordered list then have a custom InputStream to wrap the ordered list and then return that InputStream as the result of the aggregation.

As for transactions you bring up a good point, and I think we it would be good to try and address that issue for everyone and not this specific use case. (Maybe a camel header that triggers a commit vs committing at the end of the route, via a Synchronization.onComplete()?)

**Comment by davsclaus** [comment]
Sorry this is not on our radar to change the logic of how camel-jms works. 

You should not use a message broker for sending very very big payloads, that is not its intension. Some brokers allows to use out of bands features.

**Comment by JoergKe** [comment]
No problem.
Yes that is exactly the problem we want to cover. It allows to split a large message in small chunks and our broker and maybe others do not have out of band features (whatever this means in details). Actually that is what the broker developers recommend as a work around to process large messages.

**Comment by aaronjwhiteside** [comment]
If you're able to change brokers, Artemis support large message streaming..

**Comment by JoergKe** [comment]
No, we are not able change the broker.

**Comment by davsclaus** [comment]
Do you mind closing this PR

**Comment by JoergKe** [comment]
Why do you want to close it without discussion? Is this feature so absurd?

**Comment by davsclaus** [comment]
This feature is not something we want in Camel. Do you mind closing this PR

**Comment by JoergKe** [comment]
No

**Pull request closed without merging**
