### PR TITLE
CAMEL-11622: Add test RestDslPostTest.testMultiplePostTypes to camel-spring-boot

### PR DESCRIPTION
**Pull request by bszeti**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for contributing to Apache Camel. This is good. But there is a little issue with the code formatting.

Do you mind fixing the checkstyle issues, you can run

    mvn compile -P sourcecheck

In the camel-spring-boot folder.

**Comment by bszeti** [comment]
Fixed checkstyle issues.
(unsing "sourcecheck" profile didn't seem to be enough to have the test classes checked, had to add includeTestSourceDirectory=true to plugin configuration)

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by bszeti** [comment]
Thanks. Closing...

**Pull request closed without merging**
