### PR TITLE
CAMEL-16532: Prevent unregistration of existing endpoints after attem…

### PR DESCRIPTION
**Pull request by mash-sap**
…pt to register a already existing endpoint

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by mash-sap** [comment]
I did some testing:
- The start-stop-mbean problem from CAMEL-10914 is still fixed with this change
- New behavior introduced with this change: Dangling mbeans appear when the route startup fails (jira reproducer extended). This is due to the new behavior, that a server.destroy() is only called once the route/server was started

Do you think the downside of this change is acceptable?

**Comment by tadayosi** [comment]
> New behavior introduced with this change: Dangling mbeans appear when the route startup fails (jira reproducer extended). This is due to the new behavior, that a server.destroy() is only called once the route/server was started

I am not sure if it's acceptable or not. At this moment, it's the choice between the following two:
- If you try to deploy a duplicate CXF consumer and fail then the existing consumer fails altogether, or
- If you try to deploy any CXF consumer and immediately fail then you'll see a growing number of dangling MBeans.

Ideally, `doStop()` should look for any other running MBean with the same identity and invoke `destroy()` only if there aren't any.

@davsclaus @oscerd What do you think?

**Comment by mash-sap** [comment]
@tadayosi Yes I agree. I think we can not fix this completly in camel. But this can probably be fixed in CXF. I will report this to the CXF community and try to get some feedback.

**Comment by davsclaus** [comment]
Yeah good idea to get feedback from CXF. It may be that they can make CXF detect the "port in use" sooner and avoid regsitering mbeans and other bits that is harder to cleanup.

**Comment by mash-sap** [comment]
The issue is addressed in CXF: https://issues.apache.org/jira/browse/CXF-8533
Closing this pullrequest.

**Pull request closed without merging**
