### PR TITLE
CAMEL-17307: camel-support - Added ThrowingPredicate interface to cre…

### PR DESCRIPTION
**Pull request by TCke83**
…ate the possibility to throw a custom exception when validation fails

This would allow for defining a custom exception when a certain predicate in the validate camel DSL doesn't match the expectations defined in the predicate.

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
I need to rethink this as we should not introduce a central api in camel-api for a tiny need into a single processor.

**Comment by TCke83** [comment]
What also could be a possible approach is to refactor the PredicateValidationException into a factory, it gets the predicate as an argument. That factory checks on a seperate interface of the supplied predicate, not extending from Predicate, e.g. HasCustomException or something like that. And if it implements the interface throw that exception, otherwise throw the default PredicateValidationException

**Comment by davsclaus** [comment]
I think a factory is a good idea, but then you can implement a custom factory where you can build your custom exceptions based on the predicate. I do not think we should/need to add some `HasCustomException` interface but just rely on the predicate instance where you can check yourself what you want to do, in your custom factory.

Then this is non invasive on the camel-core.

**Comment by TCke83** [comment]
@davsclaus what is the best way to implement the wiring of the factory in the camel codebase?

**Comment by davsclaus** [comment]
@TCke83 I added a suggestion to this branch (one commit)
https://github.com/apache/camel/tree/throw-predicate

Then what is needed is to make it possible from camel-validator to setup a custom exception factory. And add docs to the component. And add an unit test as well.

Would you be able to help with that?

**Comment by TCke83** [comment]
@davsclaus i'm going to try to do this next week. I'll keep this pull request updated.

**Comment by davsclaus** [comment]
Oh sorry in the mean time I have been working on this. Have the implemented ready, just doing a rebuild of code before merging.

**Comment by TCke83** [comment]
@davsclaus okay thanks, looking forward to use it.

**Comment by davsclaus** [comment]
Take a look at
https://github.com/apache/camel/commit/ed4d79bef73fdb650d8c4b8531f3441b7224f620

The unit tests show what you can do. If you have feedback, suggestions then you are welcome to post them, or send a PR from the main branch.

**Comment by TCke83** [comment]
Code change looks good, nice to be able to set it globally (using the
registry) and locally in the route.

Going to try it out but it seems a fit for the use case i need it for.

Thanks a lot!

Op zo 23 jan. 2022 om 11:39 schreef Claus Ibsen ***@***.***>:

**Pull request closed without merging**
