### PR TITLE
CAMEL-10328 : Support for attachments in Slack incoming web hooks

### PR DESCRIPTION
**Pull request by ssharma**
Added support for sending attachments as part of incoming webhooks to Slack. 

Reference : https://api.slack.com/docs/message-attachments

@davsclaus  I couldn't find camel-slack category in JIRA component field and hence haven't tagged the JIRA ticket

### CODE REVIEW

**Comment by jdavey** [comment]
Why was this closed? This is useful feature as attachment formatting in slack is more robust then the straight text formatting.

**Comment by oscerd** [comment]
It has been merged

**Comment by jdavey** [comment]
Ah i see it now.  It's unclear to me how to use this in practice, from the readme there is no options for attachments.

https://github.com/apache/camel/tree/master/components/camel-slack

**Comment by oscerd** [comment]
The original commit is this one https://github.com/apache/camel/commit/67386c9b31f8f7f865f3dd1e640ee0026010b3e1

**Pull request closed without merging**
