### PR TITLE
CAMEL-14344 camel-milo - Upgrade to newer milo version

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Issue: https://issues.apache.org/jira/browse/CAMEL-14344

Upgrade of Milo from version 0.2.5 to version 0.3.7. Configuration has been refactored because it was changed in Milo library.

Java 9 is now required. Several tests are ignored for execution on jdk 8.
1 property on server Milo component was removed (as it was removed in milo library):
strictEndpointUrlsEnabled - eclipse/milo#277
2 properties were changed:
serverName was replaced by path.
hostName (it was the same property as serverName) was replaced by path too.

Endpoint syntax was changed from ..:tcp:.. to ..:opc.tcp:.. according to the milo library.

All changes are mentioned in 3x-upgrade-guide.

Replaces https://github.com/apache/camel/pull/3539

### CODE REVIEW

**Comment by davsclaus** [comment]
Oh no they started using guava :(

**Comment by JiriOndrusek** [comment]
Milo needs the same version of guava as camel-jira (<jira-guava-version>26.0-jre</jira-guava-version>). So there should be no more problems added by this dependency.

**Comment by omarsmak** [comment]
@JiriOndrusek a question, since camel-jira and camel-milo has the same guava version, does it make sense to just have one guava property version instead of two {{jira-guava-version}} and {{milo-guava-version}}?

**Comment by oscerd** [comment]
> @JiriOndrusek a question, since camel-jira and camel-milo has the same guava version, does it make sense to just have one guava property version instead of two {{jira-guava-version}} and {{milo-guava-version}}?

Probably not too much, because at some point they will diverge for sure

**Comment by JiriOndrusek** [comment]
@oscerd @omarsmak I agree

**Pull request merged**
