### PR TITLE
CAMEL-10543: possible new logo with PD camel shape

### PR DESCRIPTION
**Pull request by dustmachine**
In the originally commissioned logo I could not vouch for provenance of camel shape. This revised logo uses a public domain camel shape turned into vectors by me personally

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the proposal. The shape of the Camel is really nice.

**Comment by onders86** [comment]
Nice & colorful. 
It has sharp ears. It is just a thing i don't feel good at the first sight.

**Comment by nicolaferraro** [comment]
Really nice.
Yeah, the ears are the only thing that seems odd (too sharp and wrong direction).

**Comment by dustmachine** [comment]
Ears can be adjusted. I'll look at various camel images tonight and make some changes, or feel free to point me at sketches of what you're thinking.

**Comment by dustmachine** [comment]
- found "camel_market" on instagram
- made ears more rounded mostly
- made nose more pronounced

**Comment by zregvart** [comment]
Hi we are voting on the received proposals, the vote is open till 15.5. see all the proposals and [cast the vote](https://goo.gl/forms/A3pIzPyWzU8rlMJ13) for the three designs you prefer the most.
Also read the news announcement on [Camel blog](https://camel.apache.org/2017/05/03/new-apache-camel-logo-voting-is-now-open.html).

**Comment by oscerd** [comment]
Since the vote ended I'm closing the related PRs

**Pull request closed without merging**
