### PR TITLE
Make HL7 MllpDecoder more robust when requests are flooding

### PR DESCRIPTION
**Pull request by ohr**
Make MllpDecoder more robust when requests are flooding in faster than they can be responded to.
Also, allow to configure what happens upon charset encoding errors.

### CODE REVIEW

**Comment by davsclaus** [comment]
There is likely some code formatting issues, can you run

     mvn compile -P sourcecheck

in that module and fix the mistakes and push updates here

**Comment by davsclaus** [comment]
@hqstevenson do you have time to help review this PR ?

**Comment by hqstevenson** [comment]
I’ll look at it tonight 

Quinn Stevenson
quinn@pronoia-solutions.com
(801) 244-7758

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
