### PR TITLE
CAMEL-17751: Extracting Camel-Saga-Compensate & Camel-Saga-Complete f…

### PR DESCRIPTION
**Pull request by vagpap**
If the verifyRequest method is not able to retrieve:

`Camel-Saga-Compensate` & `Camel-Saga-Complete`

as individual headers, try to extract them from the `CamelHttpQuery` header.
If found, add them also as headers to the exchange.getIn since if they are not there, neither the compensation or the completion is called correctly.

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
Can you use URISupport from camel camel-util which has APIs to extract http headers

**Comment by vagpap** [comment]
The code currently throws a RuntimeCamelException in case the URISupport.parseQuery method throws the URISyntaxException.

Is this appropriate? Should it throw something else?

**Review by oscerd — APPROVED** [review]
LGTM, we need to backport on main too

**Comment by vagpap** [comment]
@oscerd should I do it and then open a new PR for main?

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
I think we can cherry pick to main so lets try this first

**Pull request merged**
