### PR TITLE
Fix for CAMEL-11723

### PR DESCRIPTION
**Pull request by pchhabra11**

### CODE REVIEW

**Comment by pchhabra11** [comment]
Changed to fetch the system encoding

**Comment by onders86** [comment]
Lgtm, single line would help having less lines of code though

**Comment by pchhabra11** [comment]
Done within the same line

**Comment by oscerd** [comment]
@onders86 feel free to merge and push yourself :-)

**Comment by onders86** [comment]
@oscerd , i would be happy doing it but i am afraid i am away from my computer for two days. If no rush, i can. Or maybe next time :-)

**Comment by oscerd** [comment]
No rush :-)

**Comment by davsclaus** [comment]
Hmm it would IMHO be good to check the XML library in the JDK to see what encoding it uses when outputting XML. Assuming its system default or some other kind is just a hunch. If we can either hardcode that the UTF-8 or really know that it uses system-default then we can do this kind of PR.

I would like that someone checks upon this first before we do a code change

**Comment by oscerd** [comment]
Sure, @pchhabra11 can you check and report please?

**Comment by onders86** [comment]
I dont bet but AFAIK the output xml encoding can be set by system properties or maybe jvm args, i guess the root of the issue is due to system property has cp-1252 but the xml files jmx try to read is utf-8 which has Danish characters. The change only guarantees jmx will also try to read xml with system properties, or there may be some way that you can configure your both execution env and jmx have the same settings to read xml. This may not completely resolve the problem mentioned in the issue but ensures configs are at the same level. If you still have system setting cp-1252 and jmx config file is utf-8, i suppose this should be done via some kind of configuration to avoid such issue and maybe no code change (as getbytes() already uses system property) but a config change. Or maybe there maybe some way to provide and option to set encoding in such situations...

**Comment by onders86** [comment]
Also these lines would worth looking into 

https://github.com/apache/camel/blob/1fcdd918832f6bcffa34a5314b8e7d8077c01014/camel-core/src/main/java/org/apache/camel/model/ModelHelper.java#L83

https://github.com/apache/camel/blob/1fcdd918832f6bcffa34a5314b8e7d8077c01014/camel-core/src/main/java/org/apache/camel/model/ModelHelper.java#L104

As marshaller property to convert xml to string and string to dom and dom to string again may be having lack of right setting regarding to encoding.

and maybe the internals of this method worth looking into a bit more. 
https://github.com/apache/camel/blob/1fcdd918832f6bcffa34a5314b8e7d8077c01014/camel-core/src/main/java/org/apache/camel/model/ModelHelper.java#L67

**Comment by onders86** [comment]
@pchhabra11, did you have a chance to look?

**Comment by pchhabra11** [comment]
@onders86 : I got tied up with some work, so did not get a chance to look into it :(

**Comment by davsclaus** [comment]
I had a look and pushed a fix to make it consistent to use utf-8 as input and output from the parser.

Can you close this PR

**Pull request closed without merging**
