### PR TITLE
CAMEL-12895: TransactionErrorHandler fails if UnitOfWork is null

### PR DESCRIPTION
**Pull request by jsight**
https://issues.apache.org/jira/browse/CAMEL-12985

### CODE REVIEW

**Comment by jsight** [comment]
Last commit adds a unit test that fails on master.

**Comment by jsight** [comment]
I'm not sure that I understand. It is good if the test fails on master and passes in the pr, right? It demonstrates that the PR fixes the problem.

**Comment by oscerd** [comment]
Thanks, merged on 2.22.x, 2.23.x, master and sandbox/3.x

**Comment by jsight** [comment]
Ah, np... my comment was ambiguous now that I think about it. Thanks!

**Pull request closed without merging**
