### PR TITLE
CAMEL-18520 Google-secrets-manager:resolved conflicts

### PR DESCRIPTION
**Pull request by JiriOndrusek**
fixes https://issues.apache.org/jira/browse/CAMEL-18520

I aligned versions of google-secret-manager to com.google.cloud/libraries-bom/25.4.0 (which dictates versions to other google dependencies)
@oscerd What do you think about it? (The fix removes conflicts from the issue and make sense to me)

### CODE REVIEW

**Comment by oscerd** [comment]
Looks good to me, but I'd like to test it

**Review by oscerd — APPROVED** [review]

**Comment by JiriOndrusek** [comment]
I agree that test have to be run. 
(I run test in the component and in the camel-quarkus google-secret-manager - all OK and now waiting for the CI build.)

**Comment by oscerd** [comment]
Yeah, I mean against the real service.

**Comment by JiriOndrusek** [comment]
Do you have an opportunity to run those real tests (like having a real configured account) or should I try to run it?

**Comment by oscerd** [comment]
Yes.

**Review by davsclaus — APPROVED** [review]

**Comment by oscerd** [comment]
We could merge. I'll test next week

**Review by oscerd — COMMENTED** [review]
Fine.

**Pull request merged**
