### PR TITLE
Update amqp-component.adoc

### PR DESCRIPTION
**Pull request by agiertli**
Fixing the qpid broken link.

Working link: https://qpid.apache.org/releases/qpid-jms-1.7.0/index.html

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
need to cherry pick to main after merting

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
> need to cherry pick to main after merting

I think we need a new PR. On 3.18.x we're using 0.61.x on main 1.7.0

**Comment by davsclaus** [comment]
Yes for 3.18.x we need to adjust the link

**Comment by davsclaus** [comment]
@agiertli I wonder if you would send a new PR for main editing this file
https://github.com/apache/camel/blob/main/components/camel-amqp/src/main/docs/amqp-component.adoc

**Pull request merged**
