### PR TITLE
Camel 20567 make it possible to define restconfiguration in xml-io-dsl and xml-jaxb-dsl

### PR DESCRIPTION
**Pull request by johnpoth**
# Description

Done in a similar way as the yaml-dsl, hope this is ok! Not sure why it's possible to define [multiple](https://github.com/apache/camel/blob/e6cede73c02c88d83ffd5876090e0072f9ea8e7b/core/camel-core-model/src/main/java/org/apache/camel/model/app/BeansDefinition.java#L92) restConfigurations in xml. It also seems that the xml-io-dsl can handle a root \<camel\> tag while the xml-jaxb-dsl cannot. Thanks !

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Can you update this PR as there are modified files

	modified:   dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlLoadAppTest.java
	modified:   dsl/camel-xml-jaxb-dsl-test/definition/src/test/java/org/apache/camel/dsl/xml/jaxb/definition/LoadRestConfigurationFromXmlTest.java

**Review by orpiske — APPROVED** [review]

**Comment by johnpoth** [comment]
Thanks @davsclaus @orpiske for reviewing ! I rebased `main`, thanks !

**Comment by johnpoth** [comment]
Looks like there are still uncommitted changes ... let me check

**Comment by johnpoth** [comment]
Looks like I missed some spaces in the commit, should be good now thanks !

**Comment by davsclaus** [comment]
org.apache.camel.dsl.xml.io.XmlLoadAppTest.testLoadCamelAppRestConfiguration | 0.064s | FAILURE
-- | -- | --

**Comment by davsclaus** [comment]
Maybe you can force rebase from main to get the langchain fix, and also your code changes is formatted and this file is changed

/dsl/camel-xml-jaxb-dsl-test/definition/src/test/java/org/apache/camel/dsl/xml/jaxb/definition/LoadRestConfigurationFromXmlTest.java

**Comment by johnpoth** [comment]
thanks @davsclaus , after rebasing and running manually the formatter `mvn -f definition net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format` we should be good ... fingers crossed

**Pull request merged**
