### PR TITLE
doc: Include supported protocol names in PLC4X component description

### PR DESCRIPTION
**Pull request by apupier**
# Description

Include supported protocol names in PLC4X component description
It will help discoverability. It is often that users are aware of a specific protocol but not that PLC4X can handle them.

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
The description is actually intended to be a fairly short description. However in the docs its great to have all that text you added.

**Comment by apupier** [comment]
only inside the documentation won't help to find from the tooling using the catalog.

But let's start to add it nin the component documentation only. Where should it be added? I thought the component documentation is all genrated from the source code.

**Comment by davsclaus** [comment]
its in the src/main/docs folder of the component

**Comment by apupier** [comment]
created dedicated Pull request for documentation improvement https://github.com/apache/camel/pull/14439

Other ideas to improve discoverability:
- add protocol as category
- improve catalog by adding "search field" but maybe too much redundant with category
- have tooling searching in dcoucmentation pages too (even if I do not see well how it can work easily)

**Comment by davsclaus** [comment]
you should create a JIRA for your ideas, closing this PR

**Comment by apupier** [comment]
reported https://issues.apache.org/jira/browse/CAMEL-20871

**Pull request closed without merging**
