### PR TITLE
CAMEL-12113: Camel healthcheck spring-boot actuators don't honor endp…

### PR DESCRIPTION
**Pull request by valdar**
…oints.*.enabled property

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks, just wonder if you have checked for checkstyle errors?

   mvn compile -P sourcecheck

in that camel-spring-boot folder.

**Comment by oscerd** [comment]
I'll try to run this locally

**Comment by valdar** [comment]
Ooops, after I don't know how many camel PR I still forget this step :/ 
Amended the commit.

**Comment by oscerd** [comment]
on master I have

[ERROR] Errors: 
[ERROR] org.apache.camel.spring.boot.cloud.CamelCloudServiceCallGlobalConfigurationTest.testServiceCall(org.apache.camel.spring.boot.cloud.CamelCloudServiceCallGlobalConfigurationTest)
[ERROR]   Run 1: CamelCloudServiceCallGlobalConfigurationTest.testServiceCall:56 » CamelExecution
[ERROR]   Run 2: CamelCloudServiceCallGlobalConfigurationTest.testServiceCall:56 » CamelExecution
[ERROR]   Run 3: CamelCloudServiceCallGlobalConfigurationTest.testServiceCall:56 » CamelExecution
[INFO] 
[INFO] 
[ERROR] Tests run: 74, Failures: 0, Errors: 1, Skipped: 0

**Comment by davsclaus** [comment]
Yeah I have that error too without this PR

**Comment by davsclaus** [comment]
Okay to fix that error add camel-http4 to pom.xml with test scope

**Comment by davsclaus** [comment]
This has been merged

**Pull request closed without merging**
