### PR TITLE
CAMEL-12931 - Upgrade jBPM component to use 7 series with consumer ca…

### PR DESCRIPTION
**Pull request by mswiderski**
…pability to react to produced events by jBPM

### CODE REVIEW

**Comment by mswiderski** [comment]
@oscerd thanks for pointing that out, will look into it directly and update PR once done

**Comment by oscerd** [comment]
Thanks for your contribution!

**Comment by mswiderski** [comment]
@oscerd features updated and verified with CamelJbpmTest

**Comment by oscerd** [comment]
Awesome! I'll merge this afternoon, thanks a lot for this!

**Comment by mswiderski** [comment]
excellent, will work on a blog article about this. Any plans to have release v2.23?

**Comment by oscerd** [comment]
You're just in time, we'll start the cut of 2.23.0 next weekend probably :-)

**Comment by oscerd** [comment]
Thanks this has been merged.

**Comment by oscerd** [comment]
Can you please take a look also at the camelJbpmTest in camel-itest-spring-boot? Thanks for your time. It can be part of a different PR. I'm closing this one. Thanks again @mswiderski

**Pull request closed without merging**
