### PR TITLE
CAMEL-11925: Migrate atmos properties file configuration to component properties

### PR DESCRIPTION
**Pull request by jamesnetherton**
https://issues.apache.org/jira/browse/CAMEL-11925

### CODE REVIEW

**Comment by oscerd** [comment]
LGTM

**Comment by oscerd** [comment]
Thanks the PR has been merged. I'm closing this.

**Comment by oscerd** [comment]
@davsclaus I guess it would be useful to backport to 2.20.x too. WDYT?

**Comment by davsclaus** [comment]
Yeah sure the old code is clunky

**Comment by oscerd** [comment]
Backported to 2.20.x too

**Pull request closed without merging**
