### PR TITLE
CAMEL-10308

### PR DESCRIPTION
**Pull request by tivv**
Provide a way to use async engine from ProducerTemplate

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks really good work. Its good that CompletableFuture is a Future so the API is backwards compatible. Camel users should be able to take their 2.17 or older code and just compile as java 8 + Camel 2.18 and run as-is.

Can you fix the checkstyle errors, you run this in camel-core

    mvn compile -Psourcecheck

**Comment by davsclaus** [comment]
@tivv are you able to update this PR with the checkstyle fix and the new name for that option we talked about on the mailing list ?

**Comment by tivv** [comment]
Sure. Planning to do this till Sunday.

**Comment by davsclaus** [comment]
Thanks then we get this into the upcoming release.

**Comment by tivv** [comment]
Done

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by tivv** [comment]
Sure. BTW: May be we should add information about checkstyle to http://camel.apache.org/contributing.html?

**Pull request closed without merging**
