### PR TITLE
CAMEL-11569: Implements CAMEL-11425 for camel-olingo4

### PR DESCRIPTION
**Pull request by dmvolod**
@sarhaynes , please also look at this PR.

### CODE REVIEW

**Comment by sarhaynes** [comment]
This looks good to me.  I don't have a way to check it out locally, but the changes seem to be in the right places.

**Comment by dmvolod** [comment]
Thanks for review, @sarhaynes

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by dmvolod** [comment]
Thanks for merging

**Pull request closed without merging**
