### PR TITLE
CAMEL-10242 - add timeout

### PR DESCRIPTION
**Pull request by hqstevenson**

### CODE REVIEW

**Comment by davsclaus** [comment]
Are the timeout values in milli seconds? It would be good to have comments in the javadoc what the unit is, so we get that generated into the component documentation.

**Comment by hqstevenson** [comment]
I noticed that the generated adoc has exchangePattern defaulting to InOnly, which is wrong for this component (it should be InOut).  I don't explicitly allow this parameter, so how should I configure this so the generated docs are correct?

**Comment by davsclaus** [comment]
Ah yeah its a general problem with the generated doc. We could likely remove it from the docs as it generally has no value, if you could tamper with it in the endpoint uri.

**Comment by davsclaus** [comment]
Logged a ticket: https://issues.apache.org/jira/browse/CAMEL-10294

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
