### PR TITLE
Document update

### PR DESCRIPTION
**Pull request by NiteshKoushik**
Removal of duplicate words

[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by NiteshKoushik** [comment]
Change in the key word "slowCallDurationThreshold(Duration" to "slowCallDurationThreshold Duration"

**Review by oscerd — CHANGES_REQUESTED** [review]
This is autogenerated from the javadoc of the component, you need to modify there.

**Comment by NiteshKoushik** [comment]
Tried searching for the Javadoc of the component, but unable to get the appropriate link where to change.  It would be helpful if you can share the appropriate link, so that I can do the respected changes.

**Comment by oscerd** [comment]
https://github.com/apache/camel/blob/master/core/camel-core-engine/src/main/java/org/apache/camel/model/Resilience4jConfigurationCommon.java#L181

**Comment by NiteshKoushik** [comment]
I have done the changes in the below mentioned link.
https://github.com/apache/camel/blob/master/core/camel-core-engine/src/main/java/org/apache/camel/model/Resilience4jConfigurationCommon.java#L181

Shall I close this request ?

**Comment by oscerd** [comment]
Yes please

**Comment by NiteshKoushik** [comment]
Thanks

**Pull request closed without merging**
