### PR TITLE
Upgrade plugins to have better reproducible builds

### PR DESCRIPTION
**Pull request by gnodet**
[ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ ] Each commit in the pull request should have a meaningful subject line and body.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no checkstyle violations. A more thorough check will be performed on your pull request automatically.
Below are the contribution guidelines:
https://github.com/apache/camel/blob/master/CONTRIBUTING.md

### CODE REVIEW

**Comment by gnodet** [comment]
AFAIK,  the build was failing (see https://github.com/apache/camel/runs/646344290#step:5:6326), did you fix anything ?

**Comment by oscerd** [comment]
I think we need to revert

**Comment by gnodet** [comment]
> I think we need to revert

Agreed, I was planning to investigate the failure tomorrow, but in the meantime, I think it would be safer to revert.

**Comment by oscerd** [comment]
Reverted

**Pull request merged**
