### PR TITLE
CAMEL-16639: Use symbolic links

### PR DESCRIPTION
**Pull request by zregvart**
With Antora 3 we can now use symbolic links within the git repository, and we no longer need to copy files over to the `docs` directory. This is a major refactor of how the Gulp is configured not only for creating symbolic links but also removing duplicate functionality and utilizing a configuration object to generate Gulp tasks from instead of manual task generation.

Having the configuration now effectively declarative (look for details in the gulpfile.js) it should be easier to tweak and maintain how the content is managed in the `docs` directory.

Other relevant changes also included as they were part of the refactoring:
 - images are now stored in `../images` instead of `../assets/images`
 - templates for `nav.adoc` files have a uniform naming
 - a summary document (`dsl/src/main/docs/dsl.adoc`) was added to help group DSL documents in the _other_ category
 - adds symbolic links for JSON Camel metadata documents, currently disabled (see NOTE in gulpfile.js)

This work takes is largely inspired by the work by David Jencks on #6040

This PR also contains two other commits for fixing grouping attribute. And to keep the PR as small as possible doesn't include a regen commit which would apply the changes in the Gulp build.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by zregvart** [comment]
I've converted this to draft, I need to investigate why the website build fails with the broken xref's. Could be on my end, but just to make sure this doesn't break the website build.

**Comment by zregvart** [comment]
I'm having quite a bit of weird issues with this, when running locally, that is pointing antora-playbook.yml to my local git repository two issues occur:

 1. `_attachments/Hohpe_EIP_camel_20150622.zip` is a directory not a ZIP file
 2. source points to my GitHub fork not referenced in the paybook

```
[17:07:09.934] INFO (asciidoctor): possible invalid reference: MicrometerComponent-counter
    file: docs/components/modules/ROOT/pages/micrometer-component.adoc
    source: https://github.com/zregvart/camel.git (refname: camel-2.x, start path: docs/components)
EISDIR: illegal operation on a directory, open '.../camel-website/documentation/components/latest/eips/_attachments/Hohpe_EIP_camel_20150622.zip'
```

So I've pushed to a [`test`](https://github.com/zregvart/camel/tree/test) branch, with regenerated documentation (i.e. I ran `yarn gulp` in `docs`), and pointed the playbook to that (instead of `main`), and that seems to work without issues (still need to run checks).

So unless I'm doing something wrong, and I can't find what, this seems to cause issues when working locally, which would point to a bug in Antora/isomorphic-git?

**Comment by djencks** [comment]
Sorry, I should have mentioned those problems.

1. I have to run `rm core/camel-core-engine/src/main/docs/modules/eips/attachments/*` to get a build against local  sources to succeed. The build works fine against remote repos.
2. There's a problem with logging that doesn't reference the local worktree source, instead it references the origin repo. I mentioned this one on Zulip but haven't seen a response. https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.5BAntora.203.20a.2E9.5D.20Logger.20appears.20to.20specify.20the.20wrong.20source

**Comment by zregvart** [comment]
Thanks for the hint @djencks, seems that inability to build from a local branch other than `main` is a preexisting issue. I've tested on a copy of `main`, i.e. without these changes and received the same error.

I think this is now ready to be merged. I'll leave it open for a bit if anyone else wishes to provide some feedback.

**Review by djencks — APPROVED** [review]
This is OK as is, and I left a couple of comments suggesting what I think would be improvements.

**Comment by zregvart** [comment]
> I'm amazed by this naming trick! I still don't understand why it works... What would you think of encapsulating it in a method, like

JavaScript has some interesting properties, I was also trying to create a function that would make this a bit readable, but did not succeed. This is how I tested:

```javascript
const name='xyz'
const { [name]: f1 } = { [name]: () => void 0 }
const { [name]: f2 } = { [name]: function() {} }

const lambda = (n, f) => {
  const { [n]: ret } = { [n]: f }
  return ret
}

const func = function(n, f) {
  const { [n]: ret } = { [n]: f }
  return ret
}

console.log(f1)
console.log(f2)
console.log(lambda('xyz', () => void 0))
console.log(lambda('xyz', function() {}))
console.log(func('xyz', () => void 0))
console.log(func('xyz', function() {}))
```

When run it gives:

```
[Function: xyz]
[Function: xyz]
[Function (anonymous)]
[Function (anonymous)]
[Function (anonymous)]
[Function (anonymous)]
```

So that halted that effort...

**Comment by djencks** [comment]
You have to construct the lambda in the closure in order for the name to stick (at least that's my interpretation of the behavior).  So my first suggestion

```
function nameTask (name, task) {
  const { [name]: x } = { [name]: () => task() }
  return x
}
```
works because of the new lambda () => task() in the function.  After some more consideration, I like this better:

```
function nameTask2 (name, task, args) {
  const { [name]: x } = { [name]: () => task(...args) }
  return x
}
```
called like
```
    const c = nameTask2(`clean:asciidoc:${type}`, clean, [asciidoc.destination, asciidoc.keep])
```
or maybe

```
    allTasks.push(series(
      nameTask2(`clean:asciidoc:${type}`, clean, [asciidoc.destination, asciidoc.keep]),
      nameTask2(`symlink:asciidoc:${type}`, createSymlinks, [asciidoc.source, asciidoc.destination]),
      nameTask2(`nav:asciidoc:${type}`, createNav, [asciidoc.destination] )
    ))
```

**Comment by zregvart** [comment]
I included the suggestion from @djencks and the changes resulting from running the build in `docs`. I'm going to merge this and keep an eye on the website build.

**Pull request merged**
