### PR TITLE
CAMEL-4725: Batch support. Single Producer for both SQL-components.

### PR DESCRIPTION
**Pull request by snurmine**
Added batch support for StoredProcedures. It uses Spring API as much as possible.

StoredProcedure can be read from message body and parameters are read from header.
Only Map is supported as parameter in this case.

Refactored SqlProducer to support both CallableStatement and PreparedStatement. New name is DefaultSqlProducer(as it is now more general class). Adapters  for PreparedStatement, CallableStatement and CallableStatement batch mode are in "wrapper"-package. 

Moved parameters only sensible for SQL component into SqlComponent and
left common properties into DefaultSqlComponent.

There are a lot of changes to avoid duplicate logic in code between CallableStament and PreparedStatement implementations.

### CODE REVIEW

**Comment by snurmine** [comment]
I started wondering, should it be single component, because now with these wrappers, Producer could easily select at runtime which one to use(Prepared or Callable wrapper). Callable statement syntax could start with something that differentiates it from SQL clause.

**Comment by davsclaus** [comment]
The camel-elsql component extends the sql component so all this code changes may break it. Wonder if you could take a look and compile and test that component too with all these changes.

**Comment by snurmine** [comment]
I checked, but it does not compile. Should I just make sql-stored endpoint and component, without extending sql-component ? Then there would be much less code changes. Maybe that refactoring can be done later, if wanted.

**Comment by davsclaus** [comment]
Yes we favor separating concerns - much easier to reason and understand.
So try to separate the refactoring and the added code for the batch support.

+1 to do refactoring later.

**Comment by davsclaus** [comment]
Thanks @snurmine I got your latest code merged into the master branch. You are welcome to close this PR. And keep on the good work on the component.

**Comment by snurmine** [comment]
Thank you. There probably will some at least one new PR.

**Pull request closed without merging**
