### PR TITLE
added a test for switching between different versions / runtimeproviders

### PR DESCRIPTION
**Pull request by lhein**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you move the test to camel-catalog-maven, as camel-catalog should be independent, and build first.

**Comment by lhein** [comment]
yeah, will do

**Comment by lhein** [comment]
moved

**Comment by lhein** [comment]
should be fine now

**Comment by davsclaus** [comment]
Thanks I have merged this and improved/fixed the test, as you need to set the karaf runtime provider also. See how I did that in this commit: https://github.com/apache/camel/commit/077e5df4f6904e13d76444821737bcc0dafe23c0

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
