### PR TITLE
CAMEL-18255: Address memory leak caused by scheduling MDC.afterProcess.

### PR DESCRIPTION
**Pull request by klease**
Call the afterProcess from the MDCcallback instead of scheduling it
separately. Reset current routeId on MDC from startProcess.

### CODE REVIEW

**Comment by orpiske** [comment]
@klease hello, we have just fixed the infra issue preventing the checkstyle from running. Please, would you mind rebasing the code and pushing it again? This should ensure the checks run with the updated code. 

Thanks!

**Comment by klease** [comment]
@orpiske Done (hopefully correctly)

**Comment by klease** [comment]
Since this changes some core Camel components, I'd welcome a code review.

**Review by orpiske — APPROVED** [review]
LGTM. Worst case scenario we can revert if broken.

**Pull request merged**
