### PR TITLE
CAMEL-10387 - Return null if the byte array contains only 0x0 values

### PR DESCRIPTION
**Pull request by guillaumeterral**

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you fix checkstyle

    mvn compile -Psourcecheck

in the camel-jms directory.

Also when you create the new String then use the existing byte[] and not call the getter again

**Comment by guillaumeterral** [comment]
New commit done with the changes you asked for

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by guillaumeterral** [comment]
Thanks for the merge

**Pull request closed without merging**
