### PR TITLE
Fixed deadletter test in sqs and revert of previous fix of CAMEL-17437

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Issue: https://issues.apache.org/jira/browse/CAMEL-17437

Partial revert of ad116075001fa6f1d2c53faa0d05f9c17bfc8d80

I started verifying other aws components, to validate potential error (CAMEL-17437) in them. I discovered that I made a mistake in the junit test (issue reproducer). Since the test was fixed, it is obvious that the issue is not happening at all. This PR reverts changes brought my previous PR (https://github.com/apache/camel/pull/6668) and keeps the fixed version of the test (integration test using deadletter). I'm sorry for wrongly reported issue.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Remember to backport to 3.14.x as I backported the previous commit, so we need a revert there too

**Comment by oscerd** [comment]
Yean

**Comment by oscerd** [comment]
Yeah. If Jiri won't open a PR there I'll do that later

**Comment by JiriOndrusek** [comment]
I created backporting PR int camel;-3.14.x here - https://github.com/apache/camel/pull/6675

**Pull request merged**
