### PR TITLE
CAMEL-21369: camel-jbang kubernetes - add quarkus extensions configuration for Route trait

### PR DESCRIPTION
**Pull request by gansheer**
# Description

Use quarkus extensions openshift to configure route with properties. This does not solve the openshift manifest merge issue [CAMEL-21365](https://issues.apache.org/jira/browse/CAMEL-21365) but at least allow the Route openshift Resource to be present on camel-jbang kubernetes run command.

# Target

- [X] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [X] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [X] I checked that each commit in the pull request has a meaningful subject line and body.

- [X] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by orpiske — APPROVED** [review]
Overall I am OK with it, so +1 from me, but I would like more reviews from the community.

**Comment by gansheer** [comment]
@orpiske I added some chore commit non-related to my work for the build to run correctly.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@christophd or @tdiesler  do you have any comments ?

**Comment by tdiesler** [comment]
Well done - LGTM

**Pull request merged**
