### PR TITLE
CAMEL-17021: camel-minio - Determine content-length in a smarter way

### PR DESCRIPTION
**Pull request by davsclaus**

### CODE REVIEW

**Comment by davsclaus** [comment]
@oscerd I wonder if this helps you with the performance tests to avoid the minio byte[] overhead. 

For kafka payloads we may need additional logic to determine the content-length in a smarter way, but I think this should at least work for string or byte[] serializers with kafka.

**Review by oscerd — APPROVED** [review]
I think we have a similar approach in S3 too.

**Comment by oscerd** [comment]
It will helps for sure, but MinioClient is also doing some byte array allocation while calculating his digest. So this will help, but we still have some allocation there. I'll retest.

**Comment by oscerd** [comment]
Sorry, hit wrong button.

**Comment by davsclaus** [comment]
Ah yeah s3 is the same, I created a ticket for it
https://issues.apache.org/jira/browse/CAMEL-17024

**Pull request merged**
