### PR TITLE
CAMEL-11079: session keepAlive in batch consumer

### PR DESCRIPTION
**Pull request by blove319**
Problem:
When using failover in queue consumption, if a connection is bumped to another broker then the session in SjmsBatchConsumer becomes invalid and an IllegalStateException is thrown, which causes the route (and possibly the application) to exit.

Solution:
Introduce a new URI param that allows the SjmsBatchConsumer to create a new session when this situation occurs, but default the param to a value that preserves the original behavior so nobody gets a nasty surprise.

I Know the mock classes I created to support the test are less than ideal, but that's an area of inexperience for me, and they do work as intended.

### CODE REVIEW

**Comment by davsclaus** [comment]
There is some checkstyle errors, can you fix that with

    mvn compile -P sourcecheck

And can you log a JIRA ticket also.

**Comment by pboekelheideio** [comment]
Please see https://issues.apache.org/jira/browse/CAMEL-11079

**Comment by blove319** [comment]
Working on it

**Comment by blove319** [comment]
checkstyle errors fixed, except for the ones that previously existed in SjmsEndpoint.java.

**Pull request closed without merging**
