### PR TITLE
(chores) camel-zeebe: avoid polluting the build

### PR DESCRIPTION
**Pull request by orpiske**
Remove unnecessary profile to avoid polluting/over-complicating the build

Signed-off-by: Otavio R. Piske <angusyoung@gmail.com>

### CODE REVIEW

**Comment by davsclaus** [comment]
I think you also need to change the IT classes as they are configured to only run if that value = true

**Comment by orpiske** [comment]
> I think you also need to change the IT classes as they are configured to only run if that value = true

It's not necessary. They are already blocked by JUnit's `@EnabledIfSystemProperty`:

```
[INFO] --- failsafe:3.2.5:integration-test (integration-test) @ camel-zeebe ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.camel.component.zeebe.internal.ZeebeServiceIT
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0.003 s -- in org.apache.camel.component.zeebe.internal.ZeebeServiceIT
[INFO] Running org.apache.camel.component.zeebe.ThrowErrorIT
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0 s -- in org.apache.camel.component.zeebe.ThrowErrorIT
[INFO] Running org.apache.camel.component.zeebe.ResourceDeploymentIT
[WARNING] Tests run: 3, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 0.001 s -- in org.apache.camel.component.zeebe.ResourceDeploymentIT
[INFO] Running org.apache.camel.component.zeebe.ZeebeConsumerIT
[WARNING] Tests run: 2, Failures: 0, Errors: 0, Skipped: 2, Time elapsed: 0.001 s -- in org.apache.camel.component.zeebe.ZeebeConsumerIT
[INFO]
[INFO] Results:
[INFO]
[WARNING] Tests run: 10, Failures: 0, Errors: 0, Skipped: 10
```

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
So if you want to not skip the tests, you need to find out to set that magic JVM system property

**Comment by orpiske** [comment]
Yes. That's how it works for all of our tests that depend on an external infrastructure that we cannot provide.

**Comment by orpiske** [comment]
But, if you have that external infrastructure, triggering the test is actually pretty simple, though: 

`mvn -Dzeebe.test.integration.enable=true verify`.

That has the added benefit that we don't have to add a profile (and 20+ lines of build code) for every component that needs an external entity to run.

**Comment by davsclaus** [comment]
ok

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
