### PR TITLE
CAMEL-11425 Add dynamic HTTP header capability on producer endpoints.

### PR DESCRIPTION
**Pull request by sarhaynes**

### CODE REVIEW

**Comment by dmvolod** [comment]
Please run 'mvn clean install -Psourcecheck' and fix misprints and compiling issues

**Comment by sarhaynes** [comment]
Fixed issues.  Project now compiles clean.

**Comment by davsclaus** [comment]
Why do you store response headers in a header also, its like double wrapping, why wont you store them directly as-is in the camel message headers.

Also this has api changes which is not so good in a patch release eg 2.19.x. This kind of functionality is best only introduced on master branch for the 2.20 release.

**Comment by sarhaynes** [comment]
The reason I stored them in a header is to keep them from conflicting/colliding with any potential existing Camel headers.  It also followed the paradigm on how the other headers were passed in.  I wanted to differentiate between the HTTP and Camel headers.  If we decide to unwrap them, then I would suggest that they are prefaced by httpResponse.<header>.

**Comment by sarhaynes** [comment]
If we decide to move this to 2.20 I will need to update my documentation.

**Comment by davsclaus** [comment]
Yes we should do this for 2.20 release. You are welcome to update the docs.

**Comment by sarhaynes** [comment]
Updated documentation to indicate Since 2.20.

**Comment by davsclaus** [comment]
Can you do a new PR against master branch with this functionality so we can merge it there, this PR started against 2.19.x.

Also you are welcome to look at creating similiar functionality for camel-olingo4 so we have this in both of them, you can do this in another PR to keep them separated. 

Thanks

**Comment by sarhaynes** [comment]
I will do another PR against the master branch. 
I am not comfortable doing a change for camel-olingo4 as I have no way to test the change.  I can't run the test in camel-olingo4 due to proxy/firewall issues at work.  I also have no real systems to test the change against at this time.  If there is someone that could perform testing for me, I might be able to take a look and make the changes.

**Comment by sarhaynes** [comment]
This PR is OBE.  See PR #1835

**Pull request closed without merging**
