### PR TITLE
Added option for path-style access to S3

### PR DESCRIPTION
**Pull request by FingolfinTEK**

### CODE REVIEW

**Comment by oscerd** [comment]
Is this a refactoring of RabbitMQ or an AWS S3 improvement?

Maybe you can split this in two different PRs? Many thanks :-)

**Comment by oscerd** [comment]
Ok, I'm reviewing this :-)

**Comment by FingolfinTEK** [comment]
Yeah, the RabbitMQ commit was from an improvement that I submitted back in
December and as you can see it included no changes; honestly, I don't know
why it was included, let me try to clean it up.

Sorry for the hassle :)

**Comment by oscerd** [comment]
I'm still have that commit when I try to pull

**Comment by FingolfinTEK** [comment]
You should have no issues now - I used pull instead of fetch+rebase, that's why the phantom RabbitMQ commit showed.

**Comment by oscerd** [comment]
Thanks :-)

**Comment by oscerd** [comment]
Merged. Many thanks for the PR :-) Can you close this PR if ASF Git will be slower than you?

I'll take care of the 2.17.x one too.

**Comment by FingolfinTEK** [comment]
Closing, thanks!

**Pull request closed without merging**
