### PR TITLE
CAMEL-13749: Added MapAccessor to SpEL evaluation context

### PR DESCRIPTION
**Pull request by renjfk**

### CODE REVIEW

**Comment by renjfk** [comment]
Humm... But it's still supporting old behavior just introducing additional way to access.

**Comment by oscerd** [comment]
> Humm... But it's still supporting old behavior just introducing additional way to access.

If so why did you remove the old assertions?

**Comment by renjfk** [comment]
Well, following tests are doing more less same thing from Map accessing perspective so I changed one bracket usage to `MapAccessor`. I can simply duplicate all bracket tests and apply with `MapAccessor` if you think otherwise.

```java
assertExpression("#{request.Headers.foo}", "abc");
assertExpression("#{getRequest().Headers['foo']}", "abc");
```

**Comment by oscerd** [comment]
I think we need to maintain both kind of tests.

**Comment by renjfk** [comment]
Sure thing, lemme change it that way.

**Comment by renjfk** [comment]
Aight, you think it would also be convenient to have example on docs for this usage?

**Comment by oscerd** [comment]
yes, I think so. There is the spel-language.adoc to modify for this

**Comment by renjfk** [comment]
Alright, changed two existing usages since there are also still the ones with square brackets.

**Comment by oscerd** [comment]
Please by the way open this on master too.

**Comment by oscerd** [comment]
Merged on 2.x, thanks

**Pull request merged**
