### PR TITLE
CAMEL-11235: Proposal to fix an issue where a method inherited from a superclass overrides a superinterface method

### PR DESCRIPTION
**Pull request by aldettinger**
This PR proposes a fix for [CAMEL-11235](https://issues.apache.org/jira/browse/CAMEL-11235).

Basically, the `BeanInfo` introspection mechanism traverses the single rooted class hierarchy collecting overrides first, and then proceed with interfaces.
I've also created a new overload of `ObjectHelper.isOverridingMethod(...)` to deal with the case where a method inherited from a class [overrides a superinterface method](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.8.1).

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR, giving that a test now

**Comment by davsclaus** [comment]
@aldettinger btw I wonder if you would fancy looking at https://issues.apache.org/jira/browse/CAMEL-11178 its related to this great fix you did

**Comment by aldettinger** [comment]
Hi Claus. I have quite a lot of interviews these days, but I would be happy
to have a look at it in a week or two if it is not too urgent.

**Comment by davsclaus** [comment]
Thanks @aldettinger that sounds good

**Pull request closed without merging**
