### PR TITLE
CAMEL-19638 : Mockito core version update

### PR DESCRIPTION
**Pull request by mayyanar27**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
We need to recompile everything and test all components that uses mockito as its a big upgrade and likely something is changed/broken

**Comment by mayyanar27** [comment]
> We need to recompile everything and test all components that uses mockito as its a big upgrade and likely something is changed/broken



> We need to recompile everything and test all components that uses mockito as its a big upgrade and likely something is changed/broken

@davsclaus  I have recompile in local and validated the same

**Comment by davsclaus** [comment]
> > We need to recompile everything and test all components that uses mockito as its a big upgrade and likely something is changed/broken
> 
> > We need to recompile everything and test all components that uses mockito as its a big upgrade and likely something is changed/broken
> 
> @davsclaus I have recompile in local and validated the same

Okay thanks for doing this

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
CI is 100% passed so lets merged and see if something else starts to fail

**Comment by davsclaus** [comment]
Okay so there are some test failures in camel-pgevent

**Pull request merged**
