### PR TITLE
CAMEL-11731 - add asynccallback and sync camel and servlet async APIs

### PR DESCRIPTION
**Pull request by onderson**

### CODE REVIEW

**Comment by davsclaus** [comment]
This is not entirely correct, its more complicated to implement

**Comment by onderson** [comment]
AFAIK, async servlet API handles requests by writing to HttpServletResponse and setting context.complete(). Currently (before what i have done) what is done in CamelServlet is to do this and process camel's exchange with  `consumer.getProcessor().process`. What i have added is to call `consumer.getAsyncProcessor().process(exchange, asyncCallback)` with a proper asyncCallBack in which callkback.done(false) is called after completing to write to HttpServletResponse, which will trigger context.complete(). 
If you can describe what your thinking around the subject of the complexity, i'd like to try to implement..

Thanks for the review.

**Comment by davsclaus** [comment]
Its more tricky than that, the Camel routing engine can process sync and async depending on what happens in the Camel routes / components in use etc. And that complete method must be called regardless at the right time, and only when all the data is done being written in the reply. So ordering matter, and also it maybe must be called even if Camel routing engine was not kicked as something failed beforehand.

**Comment by onderson** [comment]
in doServiceAsync method, all the exceptions must be handled and in finally block `asyncCallback.done(false)` must be called so that ,after proper error message provided in HttpServletResponse ,context should be completed as a result of it. I think i understand what you mean by the importance of ordering, maybe in callback handler's implementation, 
instead of 

`public void done(boolean doneSync) {
    if (!doneSync) {
        context.complete();
    }
}`

it should be 

`public void done(boolean doneSync) {
        context.complete();
}`

and in here, context should not be completed before camel's async processing is completed.

So, i am wondering in such case would it be simpler not having camel's async processing may not be needed if Camel Servlet is already asynchronous.

**Comment by onderson** [comment]
PR withdrawn. Thanks

**Comment by onderson** [comment]
@nhoughto , processing asychronously in camel and servlet brings up the ordering problem which @davsclaus described earlier. I thought it would not be that to easy to sort this out by myself. So i did pull out the PR. Hope somebody else will take a look at this. I have a similar scenario but not killing me at the moment.

**Pull request closed without merging**
