### PR TITLE
CAMEL-XXX Update documentation for SASL_SSL kafka security protocol

### PR DESCRIPTION
**Pull request by r00ta**
# Description

`SASL_SSL` is currently a supported security protocol in Kafka, but the docs was not including it.

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]

**Comment by r00ta** [comment]
Hi @oscerd @orpiske , I just added manually the `SASL_SSL` info the files that I found (after a global search). I don't know if some files were supposed to be generated with some commands. Just FYI

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@r00ta @orpiske is this also needed for camel-3.x branch? If so we can cherry-pick to that branch, or @r00ta can create a new PR for `camel-3.x` branch.

**Comment by r00ta** [comment]
> @r00ta @orpiske is this also needed for [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).x branch? If so we can cherry-pick to that branch, or @r00ta can create a new PR for `camel-3.x` branch.

Hi @davsclaus , sure here it is https://github.com/apache/camel/pull/9217

**Comment by orpiske** [comment]
> @r00ta @orpiske is this also needed for [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).x branch? If so we can cherry-pick to that branch, or @r00ta can create a new PR for `camel-3.x` branch.

Yes, we should have this one on 3.x. Thanks @r00ta and @davsclaus

**Pull request merged**
