### PR TITLE
CAMEL-13718 - fixed wrong syntax for pulsar endpoints

### PR DESCRIPTION
**Pull request by lhein**
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

This is a change proposal. I haven't tested it in all details. Please make sure to review the change carefully.

### CODE REVIEW

**Comment by oscerd** [comment]
I think this can be closed, @davsclaus

**Comment by davsclaus** [comment]
I am a bit knee deep with some properties component refactoring. 

For what its worth its important to keep the camel-pulsar uri with that persistent/non-persistent/tenant stuff that it was originally. So I think the "bug" is that the uri path does not reflect this to well from tooling point of view.

**Comment by lhein** [comment]
Just as a comparison take the Camel JMS Component. It provides path type parameters for all parts of the syntax. The Pulsar component does not.

**Comment by davsclaus** [comment]
Thanks for the patience @lhein - I will take a look tomorrow now that the big work on the properties component refactor is done

**Comment by lhein** [comment]
no need to rush.

**Comment by davsclaus** [comment]
Yeah I have just updated it so the url is split up into individual parts

**Pull request merged**
