### PR TITLE
CAMEL-20776: Kinesis Consumer uses a separate thread to monitor shard changes

### PR DESCRIPTION
**Pull request by fanyang**
# Description

Each time when camel kinesis connector requests records, it gets shard list first. This will increase E2E latency for each message. In most scenario, shard list won't change frequently. So, it's unnecessary to get shard list before every data request. 
This PR added a separate thread for Kinesis Consumer to monitor shard changes
This PR also fixed kinesis consumer flaky integration tests.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
Also we mostly use millis for values, so its better to use `10000` for that delay.

**Comment by fanyang** [comment]
Resolved above comments. Please review again.

**Review by davsclaus — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
I would mark this new option as `consumer,advanced` as end users likely is not going to tweak this option as much

**Comment by fanyang** [comment]
Sure, added "advanced", please review again. Thanks.

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
