### PR TITLE
CAMEL-12966: camel-netty4-http use relative path by default

### PR DESCRIPTION
**Pull request by vrlgohel**
Make useRelativePath to true, to get the relative path by default.

### CODE REVIEW

**Comment by vrlgohel** [comment]
@oscerd , @davsclaus , changes done. Can you pls review ?

**Comment by davsclaus** [comment]
```
     * An example with relative path:
     * GET /foo HTTP/1.1
     * Host: myserver.com
     *
     * And with absolute path:
     * GET http://myserver.com/foo HTTP/1.1
     * Host: myserver.com
```

eg we do today as the bottom, but we want to use the upper as the new default when using netty4-http producer

**Comment by davsclaus** [comment]
You can turn on DEBUG logging and netty will log the actual HTTP request and responses so you can see the HTTP headers

**Comment by vrlgohel** [comment]
Well, the earlier approach i used, making the default 'useRelativePath' to true had quite a few tests failing. These were tests with non GET requests. So, there are quite a few tests that need to be changed and code be refactored. In addition, we are restricting this for GET only.

For example, we have this test, NettyHttpBindingUseRelativePathInPostTest, 
```
@Test
    public void testSendToNetty() throws Exception {
        Exchange exchange = template.request("netty4-http:http://localhost:{{port}}/myapp/myservice?query1=a&query2=b&useRelativePath=true", new Processor() {

            public void process(Exchange exchange) throws Exception {
                exchange.getIn().setBody("b1=x&b2=y");
                exchange.getIn().setHeader("content-type", "application/x-www-form-urlencoded");
                exchange.getIn().setHeader(Exchange.HTTP_METHOD, HttpMethods.POST);
            }

        });
        // convert the response to a String
        String body = exchange.getOut().getBody(String.class);
        assertEquals("Request message is OK", body);
    }
```
and if we change the default value to 'true', i guess we probably then lose the objective this unit test class has for relative address in POST requests. We need to showcase the flip side of the test, by turn the value to 'false' in the unit test.

I understand we have specified the hard code for GET request, but if the change is going to use relative paths for only GET, i find this approach to be more simpler. 

Thank you Claus for taking a look here. I will check with the earlier approach and modifying the tests.

**Comment by davsclaus** [comment]
On the other hand I would find it _too magic_ if GET is doing it this way, and all the other HTTP verbs are doing it another way.

To my knowledge the HTTP protocol and other http clients are more often using the relative syntax where the hostname is provided in the `Host` header and the top header with the request uri is the relative path from the `Host`.

**Comment by oscerd** [comment]
Any news on this?

**Comment by oscerd** [comment]
I'm closing this.

**Pull request closed without merging**
