### PR TITLE
Force some dependencies into the classpath

### PR DESCRIPTION
**Pull request by orpiske**
Removing the secretsmanager in change
(317a2baa00c666c27fe51f3996989a42607192fe) resulted in these
dependencies being ignored in the component / endpoint DSL classpath.
This forces them back into it.

### CODE REVIEW

**Comment by orpiske** [comment]
This is kinda of an ugly fix @davsclaus @oscerd. I am not sure if we have a better way to solve it ...

**Comment by oscerd** [comment]
I'm moving the Secrets Manager aws properties Source in the aws secrets manager component. This should fix the situation a bit.

**Review by oscerd — CHANGES_REQUESTED** [review]
Let's wait for move of the properties source and then check again.

**Comment by orpiske** [comment]
> Let's wait for move of the properties source and then check again.

Ahhh, nice! Yeah, let's wait for that ... I was suspecting this was not a good approach for it. Thanks for the heads up!

**Comment by oscerd** [comment]
It should be fixed with https://github.com/apache/camel/commit/cfa5189d83e1eff0afc738988f827f0603598f63 and https://github.com/apache/camel/commit/cfa5189d83e1eff0afc738988f827f0603598f63

**Comment by oscerd** [comment]
cc @orpiske

**Comment by orpiske** [comment]
Thanks @oscerd! Let's close this.

**Pull request closed without merging**
