### PR TITLE
Bug/camel 12969: Adding ServiceReference Cache to prevent memory leak.

### PR DESCRIPTION
**Pull request by bobpaulin**
This patch also includes a FF merge of CAMEL-12987.  This PR is specific to readding the service cache and invalidation strategy.

### CODE REVIEW

**Comment by oscerd** [comment]
@davsclaus what do you think about this?

**Comment by davsclaus** [comment]
We can probably instead just have a callback on after the camel context has stopped all of its other services then we can do the unget services as one of the very last actions. Which we can do by making the lifecycle strategy implement service and do the unget in the stop method.

**Comment by davsclaus** [comment]
Okay @bobpaulin @oscerd I pushed an improved to master branch which cleans/ungets the service later in the shutdown procedure so ideally we dont need any additional cache (osgi already caches) and background thread. 

@bobpaulin you are welcome to try with latest code, or apply the commit to your Camel version etc to give it a test and check for memory leaks/issues.

**Comment by davsclaus** [comment]
The commit is: https://github.com/apache/camel/commit/c331a80ec982edd97330151bf6eb751bfe38ba42

**Comment by oscerd** [comment]
Great, I'll push on 3.x too

**Comment by oscerd** [comment]
Lets leave this one opened and wait for @bobpaulin feedback

**Comment by oscerd** [comment]
@davsclaus it seems this is not fixed yet.

**Comment by davsclaus** [comment]
@bobpaulin ahh you gotta love OSGi ;)

Ideally we would just say - Hey I am uninstalling this bundle, please do GC of all the services this bundle may have used ;)

The problem with the internal cache is that we would then be out of sync with OSGi in case a new service was updated / added etc, and we use our local cached instance in the get.

So the cache should likely only keep track of the number of get's we are doing in Camel, and then unget equally as many time in the stop, where today the unget is invoked only once per object.

**Comment by bobpaulin** [comment]
@davsclaus yes OSGi add some complexity here that is not needed in camel.  

I think the approach where we track the number of gets to the ServiceReference rather than ungetting once per object in the queue could work.  It looks like the Felix framework does the same thing when they register/unregister internally.  The only issue would be that this increment/decrement would need to be thread-safe which could potentially introduce some locking into the lookup calls as well as the call back when the service is unregistered.  This  is done within Apache Felix by using AtomicLong objects to track usage counts.  

The approach I have in the PR also could work because it invalidates when services are unregistered.  New/Updated services should get a new ServiceReference object so would get a new key in the cache.  This PR also removes the blocking on the increments and decrements by introducing the thread to do the work asynchronously.  

It's a tradeoff either way.  A performance test would likely give some better clarify around how much we're trading off either way.  I do agree that that locking approach that you propose would be less complex code to maintain so if the results were comparable I would lean that way as well.   Would running a test like this be a reasonable next step?

**Comment by davsclaus** [comment]
Yeah the counting with the AtomicLong is preferred, also the JDK/JVM is very optimized for AtomicLong operations, and it has atomic operations for inc and get etc.

You are welcome to work on a fix and test it and then either update this PR or submit a new.

**Comment by davsclaus** [comment]
Just a note that we have switched master branch to the 3.x work, so this PR is now out of sync.

It would be good to revisit this again if we can come up with a better solution than the background thread.

**Comment by bobpaulin** [comment]
Thanks for the heads up.  Can we leave this issue open until a new PR is raised?

**Comment by davsclaus** [comment]
I think we should close it as there is already a JIRA ticket open that tracks this issue
https://issues.apache.org/jira/browse/CAMEL-12969

And the JIRA still refers to this PR so people can still find it.

**Comment by bobpaulin** [comment]
Ah good point.  Closing.

**Pull request closed without merging**
