### PR TITLE
Fix lumberjack doc + Fix flaky test

### PR DESCRIPTION
**Pull request by adessaigne**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by adessaigne** [comment]
Thanks !

**Comment by davsclaus** [comment]
btw you could allow to configure the SSL context on the component level (with getter/setter) and then set that on the endpoint (endpoint can override) so all endpoints could be SSL enabled if it was set on component.

**Comment by adessaigne** [comment]
And yet another pull request for the SSL configuration :)

See https://github.com/apache/camel/pull/1078

**Pull request closed without merging**
