### PR TITLE
only extract the ClassPathXmlApplicationContext once

### PR DESCRIPTION
**Pull request by TestBoost**
# Description

This pull request is to make sure only extract the `ctx` once from the xml file `org/apache/camel/spring/xml/handler/ErrorHandlerDefinitionParser.xml`. There are four tests in this test class. Every test tries to call `getBean()` from ctx to get an instance with its name and type. However, `getBean()` is not changing contents in the `ctx`. In other words, given that all tests do not try to change the contents of this `ctx` context and they are just trying to read from it, we can just create the `ctx` once to speed up the this test class.

When run on our own machine, the test runtime can jump from `4.873 s` to `3.2581 s` after applying the change.

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks, the test should really extend CamelSpringTestSupport and be something like

```
public class ErrorHandlerDefinitionParserTest extends SpringTestSupport {

    @Override
    protected AbstractXmlApplicationContext createApplicationContext() {
        return new ClassPathXmlApplicationContext("org/apache/camel/spring/xml/handler/ErrorHandlerDefinitionParser.xml");
    }

```

And `ctx` should then be `applicationContext`.

Can you try to change the PR to do that, thanks.

**Comment by TestBoost** [comment]
Thank you for the response. And I indeed find in the `CamelSpringTestSupport`, there is a place to only read the `context` once under certain conditions. I just refactored as you said but I am not sure if it looks OK.

Thanks a lot

**Comment by davsclaus** [comment]
Oh we cannot depend on `camel-test-spring-junit5` as its a chicken and egg situation. As camel-spring-xml is a dependency on the test module, so you end up with circular dependency.

**Comment by TestBoost** [comment]
Oh, I see and I did not notice this. So do we just extend `SpringTestSupport` rather than `CamelSpringTestSupport`? And it seems `SpringTestSupport` does not have the same way to check `isCreateCamelContextPerClass()`.

Thank you very much!

**Comment by davsclaus** [comment]
Did you notice that this was the only test that did this, or did you find others in camel-spring-xml

**Comment by TestBoost** [comment]
Thank you so much. I try to search in the test codes in camel-spring-xml and only find this test look like this as of now. However, there are indeed some tests like `ParentContextRegistryTest` (extends SpringTestSupport) and `FindSingleByTypeTest` (extends ContextTestSupport). For these two tests, maybe it's also better to choose `CamelSpringTestSupport` instead if there are no dependencies issues.

**Comment by klease** [comment]
Most of the tests in camel-spring-xml extend `org.apache.camel.spring.SpringTestSupport`. That also provides the method `getMandatoryBean(Class<T> type, String name)` which would allow to simplify the code in your test.

**Comment by davsclaus** [comment]
Sorry closing old PRs - the camel-spring-xml should ideally be built before the test modules. And its fine for us as is.

**Pull request closed without merging**
