### PR TITLE
Prevent OpenTracing tracer exceptions interrupting execution of route

### PR DESCRIPTION
**Pull request by objectiser**

### CODE REVIEW

**Comment by objectiser** [comment]
@davsclaus Could you review please? Found this issue when testing another OpenTracing provider which happened to throw an exception, which interrupted the execution of the route.

**Comment by davsclaus** [comment]
Can you maybe lower to WARN level and maybe considering adding `This exception is ignored.` or something which is what we tend to do in camel to tell the user

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by objectiser** [comment]
@davsclaus Thanks!

**Pull request closed without merging**
