### PR TITLE
CAMEL-11345: Remove dependency on spring-core from gRPC component

### PR DESCRIPTION
**Pull request by dmvolod**
This is PR on top of the camel-2.19.1

### CODE REVIEW

**Comment by davsclaus** [comment]
Is there something on my end, but just got this compile error on the 2.19.x branch
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project camel-grpc: Compilation failure: Compilation failure:
[ERROR] /Users/davsclaus/workspace/camel/components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcUtils.java:[62,56] error: cannot find symbol
[ERROR]   symbol:   method findMethod(Class,String,Class[])
[ERROR]   location: class ReflectionHelper
[ERROR] /Users/davsclaus/workspace/camel/components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcUtils.java:[78,40] error: cannot find symbol
[ERROR]   symbol:   method findMethod(Class<CAP#1>,String,Class[])
[ERROR]   location: class ReflectionHelper
[ERROR]   where CAP#1 is a fresh type-variable:
[ERROR]     CAP#1 extends Object from capture of ? extends Object
[ERROR] /Users/davsclaus/workspace/camel/components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcUtils.java:[102,40] error: cannot find symbol
[ERROR]   symbol:   method findMethod(Class<CAP#1>,String,Class[])
[ERROR]   location: class ReflectionHelper
[ERROR]   where CAP#1 is a fresh type-variable:
[ERROR]     CAP#1 extends Object from capture of ? extends Object
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

with this PR merged

**Comment by davsclaus** [comment]
I have not rebuild 2.19.x branch but it pulled down the ASF SNAPSHOT JARs.

**Comment by davsclaus** [comment]
Yes that was the problem, after rebuild locally it works.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by dmvolod** [comment]
Thanks, PR closed

**Pull request closed without merging**
