### PR TITLE
CAMEL-13351: camel-netty4-http: error resolving relative path

### PR DESCRIPTION
**Pull request by lburgazzoli**

### CODE REVIEW

**Comment by lburgazzoli** [comment]
@janstey do you mind a quick review of this pr ?

**Comment by davsclaus** [comment]
btw this reminds me of that other JIRA ticket about using relative by default. We should look into that for camel 3

**Comment by lburgazzoli** [comment]
I guess we are good to merge

**Comment by lburgazzoli** [comment]
@davsclaus this one I think https://github.com/apache/camel/pull/2689

**Comment by lburgazzoli** [comment]
@janstey yes they pass, I've added new tests but older ones are left untouched

**Pull request merged**
