### PR TITLE
Component influxdb

### PR DESCRIPTION
**Pull request by jlpedrosa**
This has two commits, one for the component one for the merge.

### CODE REVIEW

**Comment by oscerd** [comment]
Looks good to me, can you amend the commit message to trace the issue number?
https://issues.apache.org/jira/browse/CAMEL-10066

Thanks! :-)

**Comment by oscerd** [comment]
The Karaf feature doesn't work. I'll merge this PR and I'll fix it.

**Comment by oscerd** [comment]
The PR has been merged @jlpedrosa. Many thanks for your contribution :-)

Can you close the PR? Thanks!

**Comment by oscerd** [comment]
Can you create a page on confluence with documentation? Also I don't get why the automatic generation of asciidoc documentation doesn't work for this component

**Comment by jlpedrosa** [comment]
Hi Andrea,

I don't have access in the cwiki to create documentation, I already have the ICLA signed, sent and archived by the secretary people. My username in the cwiki is jlpedrosa. 

Thanks andrea!

**Comment by oscerd** [comment]
Ok, @davsclaus can you grant karma to @jlpedrosa ? Thanks!

**Comment by davsclaus** [comment]
Karma granted

**Comment by oscerd** [comment]
Can you please add the headers in the asciidoc file of the component? They are not automatically generated for the moment. So you have to populate the table by hand.

**Comment by jlpedrosa** [comment]
Hi Andrea
I think it'd be better if I manage to get it generated automatically, so I'd preffer to work in fixing it radther than filling it manually no? 
What is the maven task that should generate it?

Thanks to you!

**Comment by oscerd** [comment]
Yes, but it should work for all the components and not all the components use the same naming convention for the class containing the header files, so it won't be easy :-)

The Mojo is here:
https://github.com/apache/camel/blob/master/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ReadmeComponentMojo.java

**Comment by jlpedrosa** [comment]
Hi Andrea i've narrowed a little bit more.

this mojo leverages a generated file that is named componentname.json, then reads it to get the adoc and update it.

Basically, this: ` String json = loadComponentJson(jsonFiles, componentName);` returns null in my component. [https://github.com/apache/camel/blob/master/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ReadmeComponentMojo.java#L94]
example: ./target/classes/org/apache/camel/component/mongodb/mongodb.json

I still don't have a clue what is generating that json file, once I get it, I may fix why it's not being generated.

**Comment by oscerd** [comment]
Hi @jlpedrosa 

This is already solved here:

https://github.com/apache/camel/commit/ee03cec2a92a48358bf2b503c160d46b51a036f2

**Comment by oscerd** [comment]
There were to empty lines under the influxdb file

**Pull request closed without merging**
