### PR TITLE
CAMEL-16389 - Remove json-smart

### PR DESCRIPTION
**Pull request by coheigea**
I'm not sure if it makes sense to make it configurable whether to install Jackson, json-smart, etc.

### CODE REVIEW

**Comment by oscerd** [comment]
There is already a ticket about this and I don't think exclude it is enough.

**Comment by oscerd** [comment]
Chunk will bring the dependency as transitive dependency: https://mvnrepository.com/artifact/com.x5dev/chunk-templates/3.6.0

**Comment by oscerd** [comment]
For jsonpath yes, I was planning to do the same. For the other transitive dependencies we have, there is no solution.

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
and json-smart is used as dependency in camel-karaf, so either you need to leave the placeholder in parent/pom or move the property placeholder in camel-karaf pom.

**Review by davsclaus — COMMENTED** [review]
What can be done at camel-chunk? Can it use another json provider, or do we need to keep it only for this component.

**Comment by oscerd** [comment]
No, it works only with json-smart. So if we want to get rid of it we need to remove the component.

**Comment by coheigea** [comment]
OK let me know what you think and removing camel-chunk or not, and I will update the PR

**Comment by oscerd** [comment]
I think we should merge this as-is and think about the component removal later.

**Comment by davsclaus** [comment]
Have anyone reported to the chunk report about moving to another json library?

**Comment by oscerd** [comment]
https://github.com/tomj74/chunk-templates/issues/37

**Comment by davsclaus** [comment]
Lets get this removed from camel-jsonpath first. Then we can look at chunk later. At least we can then deprecate chunk for 3.10, and remove in the future.

**Comment by oscerd** [comment]
We can wait for camel-chunk, the maintainer will release a new version with json-smart as optional dependency and jackson-databind as base provider.

**Comment by oscerd** [comment]
Chunk 3.6.1 released

**Comment by oscerd** [comment]
Merged. Some work to do on the Karaf side, and I'll update chunk.

**Pull request closed without merging**
