### PR TITLE
CAMEL-10115: introduced pollTimeOutMs with default 30000

### PR DESCRIPTION
**Pull request by anoordover**
Please provide comment about two things:
- the default time of 30000ms for pollTimeOutMs;
- the assumption that the configuration of the endpoint (see line 50 in KafkaConsumer) is never null.

### CODE REVIEW

**Comment by oscerd** [comment]
Looks good to me :-)

**Comment by davsclaus** [comment]
I think the timeout is too high, this would lead to a long delay in shutting down. 

Maybe set it to 5 seconds. Also does the poll always return a value? If the timeout triggers is the returned value null or an empty list? If null we would need a null check.

Also the name TimeOut, can that be in lowercase, eg pollTimeoutMs.

**Comment by oscerd** [comment]
https://kafka.apache.org/0100/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#poll(long)

**Comment by oscerd** [comment]
It will return an empty topic to records map in case

**Comment by anoordover** [comment]
Looking at the poll method in Kafka I see that it alway ends with return new ConsumerRecords<K, V>(consumeBufferedRecords()); where the consumeBufferedRecords method might return an empty collection.
I will add a test where I check whether the loop after the poll in the camel consumer could fail or not.
The test will create a ConsumerRecords with an empty collection and check whether the partitions() method on this new ConsumerRecords doesn't return null.

**Comment by davsclaus** [comment]
Looks good

**Pull request closed without merging**
