### PR TITLE
Upgrade ActiveMQ Artemis 2.31.0

### PR DESCRIPTION
**Pull request by davsclaus**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by oscerd** [comment]
I'm re-running the Stomp tests, but it seems it is failing.

**Comment by oscerd** [comment]
No, it's failing:

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.60 s <<< FAILURE! -- in org.apache.camel.component.stomp.StompConsumerTest
[ERROR] org.apache.camel.component.stomp.StompConsumerTest.testConsume -- Time elapsed: 22.30 s <<< FAILURE!
java.lang.AssertionError: mock://result Received message count 23, expected at least 100
	at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:1860)
	at org.apache.camel.component.mock.MockEndpoint.assertTrue(MockEndpoint.java:1830)
	at org.apache.camel.component.mock.MockEndpoint.doAssertIsSatisfied(MockEndpoint.java:460)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:426)
	at org.apache.camel.component.mock.MockEndpoint.assertIsSatisfied(MockEndpoint.java:416)
	at org.apache.camel.component.stomp.StompConsumerTest.testConsume(StompConsumerTest.java:55)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by davsclaus** [comment]
The tests works locally for me

**Comment by essobedo** [comment]
Maybe the timeout should be increased https://github.com/apache/camel/blob/main/components/camel-stomp/src/test/java/org/apache/camel/component/stomp/StompConsumerTest.java#L54 ?

**Pull request merged**
