### PR TITLE
Revert "[CAMEL-12593] Active deploy profile when deploying"

### PR DESCRIPTION
**Pull request by oscerd**
Reverts apache/camel#2390

### CODE REVIEW

**Comment by oscerd** [comment]
Reverting this because CI job looks broken.

**Comment by candrews** [comment]
Will you be fixing whatever the problem is?

I'm sorry my PR didn't work out... as I said, it looked right, but I couldn't test it.

**Comment by oscerd** [comment]
We'll tale a look with @zregvart

**Comment by oscerd** [comment]
If he has time

**Pull request merged**
