### PR TITLE
Updating Kudu to 1.17.0 (#11323) (#11324)

### PR DESCRIPTION
**Pull request by coheigea**
CVE fixes, same reason as main PR

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by essobedo** [comment]
> /component-tests camel-kudu

@oscerd please note this GH action doesn't exist on branches 3.X (https://github.com/apache/camel/tree/camel-3.21.x/.github/actions)

**Comment by coheigea** [comment]
@oscerd Is PR build working on this branch?

**Comment by coheigea** [comment]
I don't see anything in the logs and the tests pass locally. Any objections if I merge and keep an eye on Jenkins?

**Comment by essobedo** [comment]
The build failure is not related to this change, it seems to be due to a corrupted artifact in the local maven repository on the GH node
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-yarn (install node and yarn) on project docs: Could not extract the Node archive: Could not extract archive: '/home/runner/.m2/repository/com/github/eirslett/node/16.17.1/node-16.17.1-linux-x64.tar.gz': EOFException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.12.1:install-node-and-yarn (install node and yarn) on project docs: Could not extract the Node archive: Could not extract archive: '/home/runner/.m2/repository/com/github/eirslett/node/16.17.1/node-16.17.1-linux-x64.tar.gz'
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:375)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:351)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:215)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:171)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:163)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl.buildProject(SmartBuilderImpl.java:178)
	at org.mvndaemon.mvnd.builder.SmartBuilderImpl$ProjectBuildTask.run(SmartBuilderImpl.java:198)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.maven.plugin.MojoFailureException: Could not extract the Node archive: Could not extract archive: '/home/runner/.m2/repository/com/github/eirslett/node/16.17.1/node-16.17.1-linux-x64.tar.gz'
	at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailureException(MojoUtils.java:28)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:103)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:370)
	... 12 common frames omitted
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException: Could not extract the Node archive
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installNodeDefault(NodeInstaller.java:209)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.install(NodeInstaller.java:95)
	at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndYarnMojo.execute(InstallNodeAndYarnMojo.java:101)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:94)
	... 14 common frames omitted
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ArchiveExtractionException: Could not extract archive: '/home/runner/.m2/repository/com/github/eirslett/node/16.17.1/node-16.17.1-linux-x64.tar.gz'
	at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.extract(ArchiveExtractor.java:139)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.extractFile(NodeInstaller.java:324)
	at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installNodeDefault(NodeInstaller.java:143)
	... 17 common frames omitted
Caused by: java.io.EOFException: null
	at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStream.read(GzipCompressorInputStream.java:306)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:738)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1309)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:978)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1282)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:953)
	at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtractor.extract(ArchiveExtractor.java:127)
	... 19 common frames omitted

```

**Comment by coheigea** [comment]
Thanks, let me rebase then and see if it works

**Review by orpiske — APPROVED** [review]
LGTM

**Pull request merged**
