### PR TITLE
[CAMEL-19703] [yaml dsl] remove kebab-case schema definition

### PR DESCRIPTION
**Pull request by igarashitm**
# Description
Removing camel-yaml-dsl.json schema file in favor of camelYamlDsl.json. Also changed schema validation tests to use camelYamlDsl.json

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
https://issues.apache.org/jira/browse/CAMEL-19703

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by davsclaus** [comment]
We should add a note in the 4.1 upgrade guide.

Also that website (schema store) that links to our schema needs to be updated also

**Review by oscerd — APPROVED** [review]
Just approving, but please take into account what @davsclaus said

**Review by davsclaus — APPROVED** [review]

**Comment by igarashitm** [comment]
SchemaStore - https://github.com/SchemaStore/schemastore/pull/3178

**Comment by igarashitm** [comment]
@jamesnetherton good catch! done.

**Comment by igarashitm** [comment]
Added like this, does it look OK?
https://github.com/apache/camel/pull/11245/files#diff-a15c79f82f45a38fd9ce6aceabd27c6c824eb13c738c9f076eb8c197c3dfb0ebR101-R102

**Comment by davsclaus** [comment]
LGTM

**Pull request merged**
