### PR TITLE
fix(components): Micrometer Prometheus configurable path

### PR DESCRIPTION
**Pull request by squakez**
We can now customize the `camel.metrics.path=/camel/metrics` and call the metrics endpoint in main as:

```
$ curl http://localhost:8080/camel/metrics
# HELP camel_exchange_event_notifier_seconds  
# TYPE camel_exchange_event_notifier_seconds summary
camel_exchange_event_notifier_seconds_count{camelContext="camel-1",endpointName="timer://yaml?period=1000",eventType="ExchangeCompletedEvent",failed="false",kind="CamelExchangeEvent",routeId="route1"} 17
...
```

Closes CAMEL-21414

# Description

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by squakez** [comment]
> You need to add this configuration also in org.apache.camel.main.MetricsConfigurationProperties

I've applied the change over there as well. However, I don't understand why these configurations are duplicated in main. The component configuration was already defined in the micrometer-prometheus component.

**Comment by davsclaus** [comment]
> > You need to add this configuration also in org.apache.camel.main.MetricsConfigurationProperties
> 
> I've applied the change over there as well. However, I don't understand why these configurations are duplicated in main. The component configuration was already defined in the micrometer-prometheus component.

It makes it possible to configure this via camel-main / jbang - there is some code there that copies over these configs to the micromemter component on startup

**Comment by davsclaus** [comment]
And you need to build the catalog and include this file

	modified:   catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/main/camel-main-configuration-metadata.json

**Review by davsclaus — APPROVED** [review]

**Comment by squakez** [comment]
> And you need to build the catalog and include this file
> 
> ```
> modified:   catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/main/camel-main-configuration-metadata.json
> ```

Yeah, I've seen that. I'm rebuilding the entire project right now locally. Is there any quickest way to regen the catalog? would it be enough to just build it instead of the entire project?

**Comment by davsclaus** [comment]
https://camel.apache.org/camel-core/contributing/#_building_camel_4

**Pull request merged**
