### PR TITLE
CAMEL-20686 - changed file resources in tests to more unique & dynamic UUID

### PR DESCRIPTION
**Pull request by jvsingh**
# Description
Initial change set for CAMEL-20686
Changed three test files which had the maximum number of static filename usage (hello.txt etc.)
Appended `UUID `to make these more unique
```

- core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerMoveExistingTest.java
- core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerTempFileExistsIssueTest.java
- core/camel-core/src/test/java/org/apache/camel/component/file/FilerProducerDoneFileNameTest.java

```

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL-20686) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by jvsingh** [comment]
Unrelated to these, I noticed that some camel-core tests like `UriAsJava17TextBlockTest` only worked locally on Ubuntu and not on Windows. I hope others have had the same results

**Review by davsclaus — APPROVED** [review]

**Comment by jvsingh** [comment]
PR builds complained about some unrelated files like `camel-spring.xsd` & `core/camel-core-model/src/main/java/org/apache/camel/model/ProcessDefinition.java`
I synced my branch from apache/camel:main a couple of times just now

**Comment by davsclaus** [comment]
you are welcome to rebase

**Comment by jvsingh** [comment]
> you are welcome to rebase

Done now

**Pull request merged**
