### PR TITLE
CAMEL-10317: Added support to use Http synchronous client with Olingo…

### PR DESCRIPTION
**Pull request by kiransg**
…2 Component

### CODE REVIEW

**Comment by davsclaus** [comment]
This is against the 2.17 branch which is a patch release. It seems a bit invasive to do these code changes on that. Do you mind doing this PR against the master branch?

**Comment by kiransg** [comment]
Actually I branched out from camel-2.17.x, do you want me to submit these against master as base?

**Comment by kiransg** [comment]
Added another pull request from master
https://github.com/apache/camel/pull/1176

**Comment by oscerd** [comment]
Since we have merged the PR on master, can you close this PR please? :-) Thanks!

**Comment by kiransg** [comment]
Closing as the PR is merged

**Pull request closed without merging**
