### PR TITLE
[CAMEL-11999] Cannot create queue/message for Azure

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by oscerd** [comment]
@davsclaus can we pull this one in 2.20.x before the 2.20.1 cut or do we have to wait?

**Comment by davsclaus** [comment]
@onders86 +1 to backport

**Comment by davsclaus** [comment]
Also seems like you need to fix checkstyle

**Comment by oscerd** [comment]
Thanks for the PR.

**Comment by onders86** [comment]
@davsclaus i guess i missed your message. I will cherry-pick. Thanks.

**Comment by oscerd** [comment]
I guess the message was for me. I already cherry picked and backported. Thanks @onders86

**Pull request closed without merging**
