### PR TITLE
CAMEL-20113: camel/tests consolidating

### PR DESCRIPTION
**Pull request by kulagaIA**
# Description
org.apache.camel.itest.jms:
-AdviceWithTransactionIssueTest - moved to camel-jms;
-DynamicRouteTest - moved to camel-jms;
-FileToJmsTest - moved to camel-jms;
-JmsConsumerShutdownTest - moved to camel-jms;
-JmsIntegrationTest - jms sending to queue and processing with custom bean is checked in others tests, so it is deleted;
-JmsMediumQueuePerformanceTest - tests to play with the performance tuning are org.apache.camel.component.jms.tuning.PerformanceRouteTest and PerformanceRoutePojoTest, so this test is deleted;
-JmsPerformanceTest - tests to play with the performance tuning are org.apache.camel.component.jms.tuning.PerformanceRouteTest and PerformanceRoutePojoTest, so this test is deleted;
-JmsPollingConsumerTest - moved to camel-jms;
-JmsPollEnrichTest - moved to camel-jms;
-JMSNestedTransactionRollbackTest - moved to camel-jms;
-JmsResequencerTest - resequence is checked in other camel-jms tests, so this test is deleted;
-JmsValidatorTest - moved to camel-jms;
-SpringJmsValidatorTest - moved to camel-jms;

# Tracking
https://issues.apache.org/jira/browse/CAMEL-20113

### CODE REVIEW

**Comment by davsclaus** [comment]
I wonder if this test fails for you also


org.apache.camel.component.jms.JmsDeliveryDelayTest.testInOnlyWithDelay | 10.21s | FAILURE
-- | -- | --

**Comment by kulagaIA** [comment]
> I wonder if this test fails for you also
> 
> org.apache.camel.component.jms.JmsDeliveryDelayTest.testInOnlyWithDelay	10.21s	FAILURE

Yes, it have failed in the build job, but it passes in /component-test camel-jms and local runs

**Comment by orpiske** [comment]
> > I wonder if this test fails for you also
> > org.apache.camel.component.jms.JmsDeliveryDelayTest.testInOnlyWithDelay	10.21s	FAILURE
> 
> Yes, it have failed in the build job, but it passes in /component-test camel-jms and local runs EDIT: it seems that sometimes it fails in /component-test camel-jms also. Should I look into why it fails?

Hi, yes. Ideally we want to reduce the flakiness of our tests, so we can trust the results from our CI.

**Comment by kulagaIA** [comment]
> > > I wonder if this test fails for you also
> > > org.apache.camel.component.jms.JmsDeliveryDelayTest.testInOnlyWithDelay	10.21s	FAILURE
> > 
> > 
> > Yes, it have failed in the build job, but it passes in /component-test camel-jms and local runs EDIT: it seems that sometimes it fails in /component-test camel-jms also. Should I look into why it fails?
> 
> Hi, yes. Ideally we want to reduce the flakiness of our tests, so we can trust the results from our CI.

Hello, thanks for the reply! Ok, I'll look into it. 
Do I understand correctly that it is failing due to assertion error? 
Also, should I work on it into a separate pr? It seems nothing to do with the tests moved in this pr.

**Comment by orpiske** [comment]
> Do I understand correctly that it is failing due to assertion error?

I think so. It seems to be flaky, but unfortunately GH doesn't keep logs from multiple runs so I cannot double check (and add it here to make it easier for you to debug). 

> Also, should I work on it into a separate pr? It seems nothing to do with the tests moved in this pr.

Oh, my bad. I am sorry. I thought this test was one of the tests modified as part of the PR ... but after a second review, that's not the case. 

In this case, it's something to be fixed later (feel free to contribute it if you want, otherwise we will fix it eventually). 


Based on that, I think this one is ready to go.

**Review by orpiske — APPROVED** [review]
There was a small confusion with a flaky test, but it is unrelated to this PR. It is good to be merged.

**Pull request merged**
