### PR TITLE
CAMEL-10491 - Spring-LDAP - Updated documentation to reflect the new operations.

### PR DESCRIPTION
**Pull request by bhaveshdt**

### CODE REVIEW

**Comment by oscerd** [comment]
@bhaveshdt can you please open a PR with only the commit for the docs update? It will be more clear in git log. Thanks.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

@oscerd I created a local branch and switched to that, and then merged this PR, and then switched to master, and then cherry-picked only the commit with the doc change. But yeah ideally a PR should be against master with only the commits with their work so they are clean.

**Comment by oscerd** [comment]
Thanks @davsclaus :-)

**Comment by bhaveshdt** [comment]
@oscerd @davsclaus 

Please accept my apologies for the trouble and thanks for taking care of the merge. I will go ahead and close this pull request.

Best Regards and Happy Holidays!

**Pull request closed without merging**
