### PR TITLE
Add influx db component

### PR DESCRIPTION
**Pull request by jlpedrosa**
This PR covers https://issues.apache.org/jira/browse/CAMEL-10066 

So far it´s a producer only components, lets do iterations to improve it later.

### CODE REVIEW

**Comment by oscerd** [comment]
Looks good to me. Can you rebase and maybe squash? I think improvements are possible. Also I don't understand why the documentation isn't automatically generated for this component..

**Comment by jlpedrosa** [comment]
Hi Andrea

I've rebased it will all the commits from master of camel. I've just realized I did not add the karaf features, I'll do it ASAP (this week) meanwhile let's review the other. I don't have a clue how to squash this thing.

**Comment by oscerd** [comment]
To squash you just need to do:

```shell
git rebase -i HEAD~8
```

because you did the last 8 commits.

You should have a list of 8 commits with the **pick** instruction before.

Maintain **pick** for the first commit and change it to **squash** for all the other commits, then just save and add a unique commit message when asked for it.

**Comment by jlpedrosa** [comment]
Hi Andrea

But the last commit is a merge of camel trunk, that won't make your life (or whoever merges this into camel) harder?  see this one ` Merge remote-tracking branch 'camel_upstream/master' into CAMEL-10066	`

**Comment by oscerd** [comment]
The result should be just a single commit with a message like:

"Camel-10066 - Add an InfluxDB component"

**Comment by oscerd** [comment]
So I believe it shouldn't be harder than now :-)

**Comment by oscerd** [comment]
Here is a little guide about git squash

https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/

**Comment by jlpedrosa** [comment]
Andrea, 
I've run exactly the command you said, but I'd say this is not what you expected.

**Comment by oscerd** [comment]
So maybe go back to the original PR, otherwise I'll try to understand what happened here.

**Comment by jlpedrosa** [comment]
Discarded by gitar hero.

**Pull request closed without merging**
