### PR TITLE
camel-sftp: Permanently added 'X' (RSA) to the list of known hosts.

### PR DESCRIPTION
**Pull request by justinwrobel**
This fixes the "Permanently added 'X' (RSA) to the list of known hosts."
warning message by using the users home.

This was fixed for ssh but not for sftp in CAMEL-8202

 * Updated sftp to use user's home .ssh/known_hosts file by default
 * 'Implemented' updateFileHeaders as log messages

### CODE REVIEW

**Comment by davsclaus** [comment]
Can you fix this PR as it has merge conflicts.

**Comment by davsclaus** [comment]
And log a new CAMEL ticket as what you refer to is an old ticket about another component.

**Comment by justinwrobel** [comment]
Okay, I'll look in to both of those later tonight.

And log a new CAMEL ticket as what you refer to is an old ticket about
another component.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/apache/camel/pull/993#issuecomment-220960411>

**Comment by justinwrobel** [comment]
Okay so I've fixed my branch and added [CAMEL-9990](https://issues.apache.org/jira/browse/CAMEL-9990). It was only conflicting with a test where someone did a noop comment and I did a log.warn. So I merged in favor of the noop.

**Pull request closed without merging**
