### PR TITLE
20008 xml tokenizer expected bodies check without xml unit dependency on camel mock

### PR DESCRIPTION
**Pull request by apupier**
# Description

alternative implementation without a new dependency on an xml library on camel-mock

see https://github.com/apache/camel/pull/11756

include commit from https://github.com/apache/camel/pull/11754

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
Can we please fix the XML tests without changing anything in camel-mock.

Changes to camel-mock is another conversation and needs more work to make a better API, there is already a bunch of methods, but some improvements can later be done with respect to Java 8 lambda style and whatnot.

But first we need to leave as-is and focus on Java 21 tests to fix.

**Comment by apupier** [comment]
> Can we please fix the XML tests without changing anything in camel-mock.

I think it will require to duplicate hundreds (if not thousands) of lines of codes

**Comment by davsclaus** [comment]
No it will not - if you are not able to do it, then you are welcome to close this PR

**Comment by davsclaus** [comment]
I created a ticket about camel-mock
https://issues.apache.org/jira/browse/CAMEL-20020

**Pull request closed without merging**
