### PR TITLE
CAMEL-15632: Geocoder - Mock API google Maps when no API key available

### PR DESCRIPTION
**Pull request by zbendhiba**
- enabling tests units in Geocoder component while not possible to call API.
- I've added a wrapper, to mock the request call within the google maps API.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
I think the mock should be avalaible only in test. I don't think it has so much sense in the producer configuration. Lets wait for others opinion, I think it's a bit misleading, if it's only for testing purpose.

**Comment by ppalaga** [comment]
Being able to test an API client component like this without accessing the actual remote API is a good thing and we'd definitely like to utilize that option in Camel Quarkus. The question is only where in the stack should the mocking happen. The current proposal 36fe01b does that inside the Camel component, thus fully circumventing the Google API client and the HTTP communication. I think that esp. when testing Camel Quarkus native mode, keeping the Google API client and the HTTP communication in game is very important and thus the mocking should happen on the remote side of the REST API. So what I think we'd need is a way to switch the URI base of the Google API client.

**Comment by zbendhiba** [comment]
If you have ideas on how I can mock that URL or call, or how we can use a mock proxy to redirect  to another URL, as described here https://github.com/googlemaps/google-maps-services-java/issues/132.
For camel-quarkus, it would be cool if you can test the API, since it needs reflection. So that we can check that newer versions of the API are still compatible with native mode. With this solution, I have some part of the API tested + the response classes that needed reflection, but not the call of the API and parsing the response.
Also it would be nice to test our producer, since we just ignore the tests completely.

**Comment by ppalaga** [comment]
> If you have ideas on how I can mock that URL or call, or how we can use a mock proxy to redirect to another URL, as described here [googlemaps/google-maps-services-java#132](https://github.com/googlemaps/google-maps-services-java/issues/132).

I think the proxy solution could work for us in Camel Quarkus without any change here in Camel. The rough idea is as follows:

* Have a set of HTTP endpoints on `localhost:somePort` that would return the pre-recorded JSONs as you have them here. This can be done using `platform-http` as we do in telegram: https://github.com/apache/camel-quarkus/blob/master/integration-tests/telegram/src/main/java/org/apache/camel/quarkus/component/telegram/it/TelegramRoutes.java#L75-L93
* Set the geocoder component's proxy options to `localhost:somePort`. This would be done only if `GOOGLE_API_KEY` is not set, so that we test against the real remote API if GOOGLE_API_KEY is available. Again, this would be similar to what we do in Telegram: https://github.com/apache/camel-quarkus/blob/master/integration-tests/telegram/src/main/java/org/apache/camel/quarkus/component/telegram/it/TelegramRoutes.java#L55-L71

That might do what we need. WDYT?

**Comment by zbendhiba** [comment]
@ppalaga  I'll try that option

**Pull request closed without merging**
