### PR TITLE
CAMEL-21019: Create a Camel TensorFlow Serving component

### PR DESCRIPTION
**Pull request by tadayosi**
# Description

https://issues.apache.org/jira/browse/CAMEL-21019

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Comment by tadayosi** [comment]
@davsclaus @oscerd Is it still possible to make it in the 4.9.0 release?  It'd be great if we can have it in the 4.9.0 train. Otherwise, I'm fine with holding it for 4.10.0.

**Comment by davsclaus** [comment]
No its too late for 4.9, so it will be in 4.10

**Comment by tadayosi** [comment]
OK, then I'll keep it until 4.10 development starts.

**Review by davsclaus — APPROVED** [review]

**Comment by gansheer** [comment]
@tadayosi @davsclaus  How does declaring Apache and Google license works in practice for the filescomponents/camel-ai/camel-tensorflow-serving/src/main/proto/google/protobuf/any.proto and components/camel-ai/camel-tensorflow-serving/src/main/proto/google/protobuf/wrappers.proto ?

**Comment by tadayosi** [comment]
@gansheer Camel's build tool requires and automatically add the license header to every text file in the project. But the actual file `any.proto` and the other proto files are originally copied from the TensorFlow repository as-is, that's why it has double license headers. My understanding is however that APL-2.0 is so permissive that there's no problem with doing so and there should be no practical implications with it.

**Review by gansheer — APPROVED** [review]

**Comment by tadayosi** [comment]
Rebased to 4.10.0-SNAPSHOT. I'll merge it once CI passes.

**Pull request merged**
