### PR TITLE
Do not play some tests of Tahu on s390x and ppc64le

### PR DESCRIPTION
**Pull request by apupier**
Some Tahu tests are requiring a container to be started. Moved them to IT tests. It allows to not play them on s390x and ppc64le architecture as these containers require HiveMQ container which is not available on these platforms.

# Description

fix main branch, see https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/327/testReport/org.apache.camel.component.tahu/

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
Thanks for this! I was just looking at the latest results and noticed it.

**Comment by apupier** [comment]
Seems a test is hanging with JDK 21 on GitHub CI

I cannot reproduce locally

**Comment by apupier** [comment]
here are the last log lines during the first attempt:
```
[camel-tahu] [INFO] Running org.apache.camel.component.tahu.TahuEdgeProducerIT
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,537 I [main           ]   o.a.c.impl.engine.AbstractCamelContext          Apache Camel 4.8.0-SNAPSHOT (camel-4) is starting
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext          Routes startup (total:2)
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext              Started route3 (direct://SPARKPLUG_TCK/LOG)
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext              Started route4 (direct://SPARKPLUG_TCK/RESULT)
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext          Apache Camel 4.8.0-SNAPSHOT (camel-4) started in 1ms (build:0ms init:0ms start:1ms)
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,666 I [main           ] a.c.t.i.c.TransientCamelContextExtension          ********************************************************************************
[camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,666 I [main           ] a.c.t.i.c.TransientCamelContextExtension          Testing: [1] profile=SESSION_ESTABLISHMENT_TEST (org.apache.camel.component.tahu.TahuEdgeProducerIT)
```

**Comment by orpiske** [comment]
> here are the last log lines during the first attempt:
> 
> ```
> [camel-tahu] [INFO] Running org.apache.camel.component.tahu.TahuEdgeProducerIT
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,537 I [main           ]   o.a.c.impl.engine.AbstractCamelContext          Apache Camel 4.8.0-SNAPSHOT (camel-4) is starting
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext          Routes startup (total:2)
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext              Started route3 (direct://SPARKPLUG_TCK/LOG)
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext              Started route4 (direct://SPARKPLUG_TCK/RESULT)
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,538 I [main           ]   o.a.c.impl.engine.AbstractCamelContext          Apache Camel 4.8.0-SNAPSHOT (camel-4) started in 1ms (build:0ms init:0ms start:1ms)
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,666 I [main           ] a.c.t.i.c.TransientCamelContextExtension          ********************************************************************************
> [camel-tahu] [INFO] [stdout] 2024-08-26 07:39:10,666 I [main           ] a.c.t.i.c.TransientCamelContextExtension          Testing: [1] profile=SESSION_ESTABLISHMENT_TEST (org.apache.camel.component.tahu.TahuEdgeProducerIT)
> ```

Let's merge this PR and then take a look at this. Worst case scenario, we might disable it on ASF CI.

**Pull request merged**
