### PR TITLE
CAMEL-16237 : Allow to easily set user-agent on component level

### PR DESCRIPTION
**Pull request by erayerdem**
Adding custom user agent to apache http client

JIRA - https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16237?filter=allopenissues

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
I think you need to add `userAgent` to `HttpComponent` and have getter/setter for it there, so you can set it once on the component. And if really needed it can be added on endpoint too, so you can configure it there per endpoint, or override the component option.

**Comment by erayerdem** [comment]
@davsclaus I don't understand why exactly we need something like this. Could you please explain in more detail?

**Comment by oscerd** [comment]
It makes sense to have the option at component level, because it should defined just one time and re-used each time you create an endpoint. You could then override the behavior of the component, by specifying the userAgent option at endpoint level if you want to override the default value coming from the component.

**Comment by oscerd** [comment]
I guess we can close this, eventually you can re-open it once moved to component.

**Comment by davsclaus** [comment]
Sorry I am on PTO and have not had time to provide feedback, let me merge this and polish it.

**Pull request merged**
