### PR TITLE
CAMEL-11369: camel-spring-boot-starter generator paste incorrect default value

### PR DESCRIPTION
**Pull request by dmvolod**
@davsclaus, the problem was in type comparison, not in enum processing at all
Other code looks like working fine, but need to be reviewed for better understanding, join reusable methods, common type comparison and using constants (classes) instead of string values

### CODE REVIEW

**Comment by davsclaus** [comment]
Ah good, have you tried to rebuild the project to see if the generated source code is not changed elsewhere or broken something else?

You can do a full rebuild with

    mvn clean install -P fastinstall

from the root dir

**Comment by dmvolod** [comment]
Thanks for tip, processing right now

**Comment by dmvolod** [comment]
Oh, @davsclaus , there are many components were regenerated and filled with default values after this fix. Please check.

**Comment by davsclaus** [comment]
Ah okay yeah looks like we should include those as well

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by dmvolod** [comment]
Thanks, PR closed

**Pull request closed without merging**
