### PR TITLE
CAMEL-10118: Fix Zipkin Spring-boot configuration

### PR DESCRIPTION
**Pull request by nicolaferraro**
The documentation of the zipkin component states that it must be activated using the `@CamelZipkin` annotation, so the `spring.factories` file should be removed, otherwise it will be configured even if the annotation is not present on the main class.

The annotation alone is sufficient.

### CODE REVIEW

**Comment by davsclaus** [comment]
Yeah but I think we need to support both kind adding the annotation, or setting camel.zipkin.enabled=true in the applicaiton.properties.

So the auto configuration need some logic to only run if either
- annotation present
- enable=true

**Comment by nicolaferraro** [comment]
Maybe this can be a solution.

Now the semantics is:
Annotation present -> enabled, can be disabled with camel.zipkin.enabled=false
Annotation absent -> disabled, can be enabled with camel.zipkin.enabled=true

So, now it is disabled by default, otherwise the annotation is meaningless.

**Comment by davsclaus** [comment]
Yeah this is good.

Though I wonder if spring boot allows to check if that property == true. I think I have seen some SpEL evaluation you can do. But not sure if you can do a OR so its Annotation present or that property == true in the same auto configuration class.
```
+@ConditionalOnProperty(value = "camel.zipkin.enabled")
```

**Comment by nicolaferraro** [comment]
Yeah, I tried that way. It seems there is no standard way to express the predicate "is annotation present", because annotations are just used to provide additional behaviour (eg. Import).

Going by reflection ... maybe not..

**Comment by davsclaus** [comment]
Ah okay, then it sounds better to do what you have done in this PR

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Pull request closed without merging**
