### PR TITLE
fuse-doc-2017 updated links to box.com

### PR DESCRIPTION
**Pull request by MelissaFlinn**
Hi - I'm contributing a fix to the ASCII-doc documentation. 

I replaced each box.com link with the appropriate https://developer.box.com/reference link.

Thank you...

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by MelissaFlinn** [comment]
Thank you! I have one more minor fix for this file. Can I re-use this pull request or should I create a new one?

**Comment by davsclaus** [comment]
You need to create a new PR

**Comment by MelissaFlinn** [comment]
I fixed the link to box-java-sdk (it was working fine in upstream doc but not downstream doc) - now will work in both places. If I need to close this pull request and create a new one, let me know...Thanks...

**Pull request closed without merging**
