### PR TITLE
Camel-19445. Simplified assertion in CaffeineIdempotentRepositoryTest

### PR DESCRIPTION
**Pull request by LostArtist**
# Description

# Target

- [ ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by essobedo** [comment]
Hi 👋  thank you for the contribution, could you please update your commit message to replace `Camel-19445.` with `CAMEL-19445:`

**Comment by LostArtist** [comment]
> Hi wave thank you for the contribution, could you please update your commit message to replace `Camel-19445.` with `CAMEL-19445:`

Hi Nicolas. Just changed it. I am a new contributor, so still learning things. Thanks for suggestion.

**Comment by essobedo** [comment]
> > Hi wave thank you for the contribution, could you please update your commit message to replace `Camel-19445.` with `CAMEL-19445:`
> 
> Hi Nicolas. Just changed it. I am a new contributor, so still learning things. Thanks for suggestion.

to change your commit message simply execute the command `git --amend` see https://www.w3schools.com/git/git_amend.asp?remote=github, then set the new commit message. This command will update your local history, you will then have a divergence with the history of the remote branch so you will need to force push your changes with `git push -f..." https://git-scm.com/docs/git-push

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]

**Review by orpiske — APPROVED** [review]
The commit message was fixed, so this one is ready to merge! Thanks everyone!

**Pull request merged**
