### PR TITLE
CAMEL-11757: Upgraded CometD library

### PR DESCRIPTION
**Pull request by vrlgohel**
Fix for issue: https://issues.apache.org/jira/browse/CAMEL-11757

### CODE REVIEW

**Comment by vrlgohel** [comment]
Hi Andrea, 
I checked with camel-cometd and camel-salesforce components, running the tests & i see no issues.

**Comment by oscerd** [comment]
Great. Thanks :-)

**Comment by oscerd** [comment]
Thanks the PR has been merged, can you close this?

**Comment by vrlgohel** [comment]
Hi Andrea, 
Thanks for reviewing this. I will close the PR now.

**Pull request closed without merging**
