### PR TITLE
CAMEL-11869: Adopted mockito-core 2.10.0 except for camel-core

### PR DESCRIPTION
**Pull request by aldettinger**
I've moved forward all components but not camel-core yet as its build seems to be broken.

Please check [CAMEL-11869](https://issues.apache.org/jira/browse/CAMEL-11869) out for more details.

### CODE REVIEW

**Comment by aldettinger** [comment]
I've checked locally for potential contradictions with a related [PR](https://github.com/apache/camel/pull/1983) and found that it should be ok.

**Comment by PascalSchumacher** [comment]
:+1: 

And you very much for checking for compatibility with #1983

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by davsclaus** [comment]
Ah darn this causes problems / test failures in camel-aws. Maybe in other components as well.

@aldettinger going to revert this. Can you check camel-aws and try to fix it there. Then you need to test each camel component that uses mockito if everyone of them passes with this PR. As there may be others.

You can use git grep mockito to find the components.

**Comment by aldettinger** [comment]
@davsclaus, I had a successful 'mvn clean install' build of the whole components folder on sunday.
Si, I'll rebase in the coming days and get it fix.

**Comment by aldettinger** [comment]
@davsclaus I've just pushed a version where camel-core and most components have been upgraded to mockito 2.10.0. I would commit remaining components in separate PRs then.

**Comment by PascalSchumacher** [comment]
By the way I'm working on migrating camel-smpp (the last component using easymock) to mockito.

**Comment by davsclaus** [comment]
@aldettinger is all this mockito migration all done - if so then close the PRs

**Comment by aldettinger** [comment]
@davsclaus The mockito migration is not done yet. Anyway, I'll tackle this component per component. So, closing then.

**Pull request closed without merging**
