### PR TITLE
CAMEL-11130 Jenkins - Camel.trunk.itest.karaf doesn't run all tests in camel-itest-karaf

### PR DESCRIPTION
**Pull request by tadayosi**
`camel-itest-karaf` should be all back to normal again.

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by oscerd** [comment]
Darn, @davsclaus was too fast :-)

**Comment by davsclaus** [comment]
@oscerd dont worry I am getting older and slower ;)

**Comment by oscerd** [comment]
@davsclaus like a camel :-)

**Comment by tadayosi** [comment]
Thanks!

**Pull request closed without merging**
