### PR TITLE
CAMEL-9210 accessKey and secretKey are optional

### PR DESCRIPTION
**Pull request by onders86**
these options are optional now, if not provided, AWS SDK handles them

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by onders86** [comment]
happy to hear that. thanks

**Comment by ThomasDemande** [comment]
This seems to break working (dynamic) endpoints that provided _accessKey_ and _secretKey_ as endpoint params, giving this error message: 

> org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: aws-s3://bucket?accessKey=ABDCEFG&fileName=xxx.csv&secretKey=RAWSECRETKEY) due to: AmazonS3Client must be specified

Is this the intended behavior?

**Comment by davsclaus** [comment]
Hi @ThomasDemande yeah it looks like it may be optional. So you are welcome to log a JIRA and provide a PR with a fix to remove that constrain in the S3Component

**Comment by dwsjax** [comment]
Please restore my booter I was hacked

**Pull request closed without merging**
