### PR TITLE
CAMEL-14344 camel-milo - Upgrade to newer milo version

### PR DESCRIPTION
**Pull request by JiriOndrusek**
Issue: https://issues.apache.org/jira/browse/CAMEL-14344

Upgrade of Milo from version 0.2.5 to version 0.3.7. Configuration has been refactored because it was changed in Milo library.

Java 9 is now required. Several tests are ignored for execution on jdk 8. 
1 property on server Milo component was removed (as it was removed in milo library):
`strictEndpointUrlsEnabled` - https://github.com/eclipse/milo/issues/277
2 properties were changed:
`serverName` was replaced by `path`.
`hostName` (it was the same property as `serverName`) was replaced by `path` too.

Endpoint syntax was changed from `..:tcp:..` to `..:opc.tcp:..` according to the milo library.

All changes are mentioned in 3x-upgrade-guide.

### CODE REVIEW

**Comment by oscerd** [comment]
@davsclaus

**Comment by davsclaus** [comment]
Can you add to the docs in camel-milo that the server component requires Java 9+ (eg java 11 - nobody should use 9, or 10)

**Comment by JiriOndrusek** [comment]
@davsclaus There are notes about jdk 9 in bot client and server doc:
https://github.com/apache/camel/pull/3539/files#diff-c9d8574bbbb3680601bfd6dd9f3dc9acR13
https://github.com/apache/camel/pull/3539/files#diff-3d0274b169a20e482061c1f824fc5643R13
I've changed to 9+ (from 9) - to be more clear.

**Comment by JiriOndrusek** [comment]
@omarsmak Fixed.
(these validations are great, at least in this case it saved possible wrong behavior)

**Comment by roberto-isi** [comment]
It's seems that the OPC-UA "samplingInterval" parameter it's taking no effect in my APP! This upgrade will solve that?

**Comment by oscerd** [comment]
Please report on a new jira issue or users mailing list. This is a PR with a different purpose. Thanks

**Comment by davsclaus** [comment]
I get these compilation errors now on JDK8

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project camel-milo: Compilation failure: Compilation failure:
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[30,72] error: cannot find symbol
[ERROR]   symbol:   method setStrictEndpointUrlsEnabled(Boolean)
[ERROR]   location: class MiloServerComponent
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[31,57] error: cannot find symbol
[ERROR]   symbol:   method setServerName(String)
[ERROR]   location: class MiloServerComponent
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[32,55] error: cannot find symbol
[ERROR]   symbol:   method setHostname(String)
[ERROR]   location: class MiloServerComponent
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[41,156] error: package org.eclipse.milo.opcua.stack.core.application does not exist
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[58,72] error: cannot find symbol
[ERROR]   symbol:   method setStrictEndpointUrlsEnabled(Boolean)
[ERROR]   location: class MiloServerComponent
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[59,57] error: cannot find symbol
[ERROR]   symbol:   method setServerName(String)
[ERROR]   location: class MiloServerComponent
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[60,55] error: cannot find symbol
[ERROR]   symbol:   method setHostname(String)
[ERROR]   location: class MiloServerComponent
[ERROR] /Users/davsclaus/workspace/camel/components/camel-milo/src/generated/java/org/apache/camel/component/milo/server/MiloServerComponentConfigurer.java:[69,156] error: package org.eclipse.milo.opcua.stack.core.application does not exist
[ERROR] -> [Help 1]

**Comment by davsclaus** [comment]
Can you fix and do a new PR

**Comment by JiriOndrusek** [comment]
@davsclaus I'll prepare new PR during the day. It seems, that I didn't commit generated files.

**Comment by JiriOndrusek** [comment]
@davsclaus New PR was created https://github.com/apache/camel/pull/3548

**Pull request merged**
