### PR TITLE
Add possibility to override LRAClient

### PR DESCRIPTION
**Pull request by johbossle**
# Description

As a follow up on #10498 

The Saga EIP pattern is using rest based communication for interaction with the lra-coordinator (e.g. narayana). Although there are ways to secure the communication with the coordinator, this is not supported by the underlying code. Also, it is not possible to easily override some implementations, since they are created by internal constructors.

This change is targeting, that one can override (influence) the creation of the LRAClient in the LRASagaService. With this "extension", it is then possible to override some default behavior and for example you can set the HttpClient and use your own adjusted instance with an Authenticator or ssl-settings.

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [CAMEL 19508](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-19508) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.
- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by zhfeng — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Review by oscerd — APPROVED** [review]
Should be on main too.

**Review by zhfeng — APPROVED** [review]

**Comment by davsclaus** [comment]
If this is a good idea to backport to 3.20.x/3.21.x etc then we need a JIRA to track each non-trivial change in LTS branches

**Comment by johbossle** [comment]
> Yes @oscerd is correct we need also to remember to cherry pick this to main branch

@davsclaus Is there something where I can help to cherry-pick and port to main-branch?

**Comment by davsclaus** [comment]
No its fine we could cherry pick this cleanly to main branch

**Comment by johbossle** [comment]
Just want to end up here with an example usage pattern to supply custom authentication header:

```java
public class AuthenticatingLRASagaService extends LRASagaService {
  @Override
  protected LRAClient createLRAClient() {
    return new LRAClient(this, HttpClient.newBuilder().build()){
      @Override
      protected HttpRequest.Builder prepareRequest(URI uri) {
        HttpRequest.Builder builder = super.prepareRequest(uri);
        builder.header("Authentication", "MY_TOKEN");
        return builder;
      }
    };
  }
}
```

**Pull request merged**
