### PR TITLE
CAMEL-10798 Splitted camel-ignite component for each endpoint

### PR DESCRIPTION
**Pull request by igarashitm**
I've been looking for a easy way to get around CAMEL-11150, but it turned out it's easier to address CAMEL-10798. This splits the ignite component into 7 which corresponds to each ignite endpoint, and also it preserves existing IgniteComponent with deprecated flag. In this way the old syntax like `ignite:cache` is still allowed with having WARN log saying that the syntax has been deprecated.

I wonder it may be a bit too big change at this stage as 2.19.0 release is around the corner though. If so let's just have it after the release.

### CODE REVIEW

**Comment by oscerd** [comment]
@davsclaus what do you think?

**Comment by davsclaus** [comment]
Yeah this is better than today where its not included in the docs. 

We would need to improve the descriptions of what each of them do. But we can do this in a new PR after this.

+1

**Comment by oscerd** [comment]
I'm merging then

**Comment by igarashitm** [comment]
Ah I should have updated javadoc for those endpoints! I'll update it soon, maybe in a separate PR?

**Comment by oscerd** [comment]
If you can update this PR it would be good.

**Comment by igarashitm** [comment]
OK cool, give me a sec

**Comment by igarashitm** [comment]
Updated javadoc. It should be good to go now.

**Comment by oscerd** [comment]
Thanks the PR has been merged. Can you close this? :-)

**Comment by igarashitm** [comment]
Thanks! closing

**Comment by oscerd** [comment]
We still have to do the same in camel-twitter I guess

**Comment by igarashitm** [comment]
yep twitter and hazelcast, so we need to keep CAMEL-10798 open :)
I'll close CAMEL-11150 as it was solved by this one.

**Comment by oscerd** [comment]
Thanks @igarashitm

**Pull request closed without merging**
