### PR TITLE
[CAMEL-10543] new logo

### PR DESCRIPTION
**Pull request by fi-**

### CODE REVIEW

**Comment by zregvart** [comment]
Nice and clean design :clap:

**Comment by davsclaus** [comment]
The shape of the Camel animal looks nice and elegant

**Comment by fi-** [comment]
Thanks. I wanted it to be minimalistic and aesthetically pleasant, while maintaining the distinctive camel shape.

**Comment by gzurowski** [comment]
+1; nice and clean

**Comment by onders86** [comment]
+1; nice and clean

**Comment by zdanek** [comment]
I know Filip. He's good designer.
+1

**Comment by zregvart** [comment]
Hi we are voting on the received proposals, the vote is open till 15.5. see all the proposals and [cast the vote](https://goo.gl/forms/A3pIzPyWzU8rlMJ13) for the three designs you prefer the most.
Also read the news announcement on [Camel blog](https://camel.apache.org/2017/05/03/new-apache-camel-logo-voting-is-now-open.html).

**Comment by oscerd** [comment]
Since the vote ended I'm closing the related PRs

**Pull request closed without merging**
