### PR TITLE
CAMEL-9047: Replace deprecated boxjavalibv2 with box-java-sdk

### PR DESCRIPTION
**Pull request by punkhorn**

### CODE REVIEW

**Comment by davsclaus** [comment]
Thanks Bill. Just a quick observation, at ASF we dont have `@author` tags in the javadoc / source code. 

Do you mind remove those and push code to this PR

**Comment by davsclaus** [comment]
Also I am not sure if you are aware of checkstyle.

Can you run checkstyle to update the code to the code format we use

Run in the box2 folder of the new component

     mvn compile -Psourcecheck

And then fix those errors and push updated PR here, thanks

**Comment by punkhorn** [comment]
Hi Claus,

Sure I can pull out the @author tags no problem.

I did already run mvn compile -Psourcecheck before doing the PR and cleaned up all of the validation error.  So I think the source code should be compliant with the Camel project style settings.

William

**Comment by punkhorn** [comment]
Updated PR with new commit removing @author tags.

**Comment by davsclaus** [comment]
I wonder if you would like to add a documentation page, eg in the src/main/docs there should be a box2-component.adoc file.

See for example the doc to the old component
https://github.com/apache/camel/blob/master/components/camel-box/src/main/docs/box-component.adoc

Mind that those tables with all the options is auto generated, so all you need to do is keep those START END tags and then the build does add the table content itself.

**Comment by davsclaus** [comment]
And the pom.xml files should have the ASF license header in the top. See any of the existing pom.xml file to copy the lic header

**Comment by punkhorn** [comment]
The box2-component.adoc is already there in PR. Please see: https://github.com/punkhorn/camel-upstream/blob/1b82a0d3b07f47d786660dc81186c7927dacbd86/components/camel-box2/camel-box2-component/src/main/docs/box2-component.adoc

**Comment by punkhorn** [comment]
Updated PR with new commit adding ASF headers to pom.xml files.

**Comment by davsclaus** [comment]
Thanks for the PR it has been merged. Do you mind closing this?

**Comment by davsclaus** [comment]
Thanks.

The code has been merged and replaced the old camel-box, as its going to die anyway when box closes that v1 api.

There is few more things and I logged a ticket. You are welcome to take a look and provide a new PR
https://issues.apache.org/jira/browse/CAMEL-10947

**Pull request closed without merging**
