### PR TITLE
CAMEL-10171 memory leak when continuation expires

### PR DESCRIPTION
**Pull request by onders86**
setobject done earlier and exception set on camelExchange.
Before being able to call isExpired method thru Continuation interface, please update your cxf to include this PRs as for below issues

https://issues.apache.org/jira/browse/CXF-7011
https://issues.apache.org/jira/browse/CXF-7002

### CODE REVIEW

**Comment by onders86** [comment]
I have got no idea why my earlier fix got into this PR. My local git copy required merge and those went into my commit as well. :(  not sure

**Comment by davsclaus** [comment]
Maybe you can try again, and do a new PR.

From a clean master create a new branch. And then cherry pick the single commit for the CAMEL-10171 commit from this branch. 

Also mind about checkstyle, run from camel-cxf

    mvn compile -Psourcecheck

And fix any errors it reports

**Comment by onders86** [comment]
Hi @davsclaus,

I am trying to create a new PR but as suggested, mvn compile -Psourcecheck command giving errors.
Is there a way to fix them quickly, because i am not sure i interpret the errors to fix :(

**Comment by onders86** [comment]
tab & spaces issues.. is not there an easy what to fix while writing the code, i wonder? thanks

**Pull request closed without merging**
