### PR TITLE
[CAMEL-13466] Fully populate (including routes which failed to start) routes to be stopped in the CamelContext

### PR DESCRIPTION
**Pull request by jbonofre**

### CODE REVIEW

**Comment by jbonofre** [comment]
@oscerd I'm adding new tests to validate the behavior, but in the mean time, it would be great if you can take a look.

**Comment by oscerd** [comment]
I'm not sure about this, I'd like to have feedback from @davsclaus too

**Comment by oscerd** [comment]
I think it doesn't hurt the normal behavior.

**Comment by jbonofre** [comment]
@oscerd yes, I tested with both "success" and "failure" routes, and it works fine.

**Comment by davsclaus** [comment]
So the point is that the RouteStartupOrder list does not currently contain routes that failed to startup? And those "invalid routes" should be attempted to stop anyway?

And to ensure this, you add all defined routes with the addAll method? And if so, don't you add duplicate routes, eg all the existing routes that started up are already there.

So I think you should only add the routes which are not already present.

And would it be possible to create an unit test that reproduces this and verifies the fix. This is a core feature in camel to startup and shutdown gracefully and therefore unit test is much appreciated.

**Comment by jbonofre** [comment]
@davsclaus yes, I'm adding a test to illustrate. Good point to verify if a route doesn't appear twice.

**Comment by jbonofre** [comment]
I've updated the PR to avoid duplicated in the `RouteStartupOrder` list. I'm working on a test to illustrate.

**Comment by davsclaus** [comment]
Working on a fix with unit test. Closing this PR

**Pull request closed without merging**
