### PR TITLE
Align versions to spring boot 2.7.4

### PR DESCRIPTION
**Pull request by cunningt**
Align versions to versions in spring-boot-dependencies 2.7.4 : https://repo1.maven.org/maven2/org/springframework/boot/spring-boot-dependencies/2.7.4/spring-boot-dependencies-2.7.4.pom

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Please have a look at Karaf features too, if involved

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
yes this will be good to get into 3.19.0 before its released

**Comment by cunningt** [comment]
@oscerd I tried building/testing apache/camel-karaf locally against this branch, and I didn't get any failures.    The spring-batch version here is different than what is in apache/camel-karaf/pom.xml, and the jboss-logging version is different, but I don't see a couchbase/hibernate version in camel-karaf.    Is there something else I should test this against?    I'm happy to do whatever testing is necessary but I'm not all that familiar with karaf and what to test there.

**Comment by davsclaus** [comment]
@cunningt this is fine, the test on karaf is usually to test the platform/karaf/features that tests that the components can be installed in karaf, which is often where things can break if versions are upgraded or other dependency chagnes.

**Comment by davsclaus** [comment]
@cunningt this PR now has merge conflicts

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
