### PR TITLE
fix binary operator match problem

### PR DESCRIPTION
**Pull request by EvanMi**
# Description

The binary operator is recognized in some places that should not be recognized, just like the “in” keyword in test case, which is recognized from “minValue”。

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [ ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [ ] I checked that each commit in the pull request has a meaningful subject line and body.

- [ ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Review by davsclaus — CHANGES_REQUESTED** [review]
Can you avoid adding new JAR for testing, and also the big test class avoid implementing an empty dummy camel context extension.

**Comment by EvanMi** [comment]
> Can you avoid adding new JAR for testing, and also the big test class avoid implementing an empty dummy camel context extension.

Any advice ? there has no test in this modual, so i import juit. And to avoid import other modual, i create the dummy camel context.  So, if move the testcase to other modual to avoid this? any suggested modual?

**Comment by davsclaus** [comment]
tests are in core/camel-core

**Comment by davsclaus** [comment]
This PR causes many new test failures in camel-core

**Comment by EvanMi** [comment]
> This PR causes many new test failures in camel-core

Okay, I'll test it locally

**Comment by EvanMi** [comment]
> This PR causes many new test failures in camel-core

All test cases in core have passed

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
