### PR TITLE
CAMEL-11436: camel-spring-ldap - Has test failures

### PR DESCRIPTION
**Pull request by dmvolod**

### CODE REVIEW

**Comment by davsclaus** [comment]
@oscerd looks good you are welcome to merge

**Comment by oscerd** [comment]
Sure. I'll tale care of thi s PR tomorrow :-)

**Comment by oscerd** [comment]
Thanks a lot @dmvolod the PR has been merged. Can you close this?

**Comment by dmvolod** [comment]
Thanks @oscerd , PR closed.

**Comment by oscerd** [comment]
Thanks @dmvolod

**Pull request closed without merging**
