### PR TITLE
CAMEL-18928: removed component camel-datasonnet

### PR DESCRIPTION
**Pull request by orpiske**

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Don't we disable them only? Without removing them?

**Comment by zhfeng** [comment]
Where can we put these disabled components?

**Comment by orpiske** [comment]
> Don't we disable them only? Without removing them?

My suggestion to @davsclaus earlier today was to: tag the code, remove them and keep the code base and git history clean. Once they are available, we can simply revert the change and do that on top of it. 

@davsclaus did I understand it differently?

**Comment by orpiske** [comment]
> Where can we put these disabled components?

There's a list of components to be disabled here: https://issues.apache.org/jira/browse/CAMEL-18928. You can add them to the list and I'll take care of removing them cleanly.

**Review by davsclaus — APPROVED** [review]

**Review by zhfeng — APPROVED** [review]

**Comment by orpiske** [comment]
Folks, can I merge this one? 

> ### Components tested:
> Total 	Tested 	Failed ❌ 	Passed ✅
> 2 	2 	0 	0

**Pull request merged**
