### PR TITLE
(chores) replacing inner classes with lambda

### PR DESCRIPTION
**Pull request by gilvansfilho**
Solving some sonar issues about [replacing inner classes with lambdas](https://rules.sonarsource.com/java/tag/java8/RSPEC-1604).

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by davsclaus** [comment]
This makes it a bit harder to backport bugs when the code is changed soo much. And camel-jbang is much in development so we should then backport to 3.x 3.20.x branches as well.

**Comment by gilvansfilho** [comment]
> This makes it a bit harder to backport bugs when the code is changed soo much. And camel-jbang is much in development so we should then backport to 3.x 3.20.x branches as well.

Should I do something or at moment we will discard this? Please give me know if I did something wrong.

**Comment by davsclaus** [comment]
> > This makes it a bit harder to backport bugs when the code is changed soo much. And camel-jbang is much in development so we should then backport to 3.x 3.20.x branches as well.
> 
> Should I do something or at moment we will discard this? Please give me know if I did something wrong.

Nothing wrong. However we should ideally also do the same changes in camel-3.x and 3.20.x for the camel-jbang part of your PR.

**Comment by gilvansfilho** [comment]
> > > This makes it a bit harder to backport bugs when the code is changed soo much. And camel-jbang is much in development so we should then backport to 3.x 3.20.x branches as well.
> > 
> > 
> > Should I do something or at moment we will discard this? Please give me know if I did something wrong.
> 
> Nothing wrong. However we should ideally also do the same changes in [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).x and 3.20.x for the camel-jbang part of your PR.

Great but that method `XmlHelper#colorPrint` don't exist at camel-3.x neither at camel-3.20.x

**Comment by davsclaus** [comment]
> > > > This makes it a bit harder to backport bugs when the code is changed soo much. And camel-jbang is much in development so we should then backport to 3.x 3.20.x branches as well.
> > > 
> > > 
> > > Should I do something or at moment we will discard this? Please give me know if I did something wrong.
> > 
> > 
> > Nothing wrong. However we should ideally also do the same changes in [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).x and 3.20.x for the camel-jbang part of your PR.
> 
> Great but that method `XmlHelper#colorPrint` don't exist at [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).x neither at [camel-3](https://issues.apache.org/jira/browse/CAMEL-3).20.x

Yes can you do this PR without changing camel-jbang that is better.

**Comment by gilvansfilho** [comment]
camel-jbang / camel-kamelet-main changes removed from PR

**Pull request merged**
