### PR TITLE
Salesforce consumer should use AyncCallback, fixes CAMEL-12780

### PR DESCRIPTION
**Pull request by dhirajsb**

### CODE REVIEW

**Comment by oscerd** [comment]
I believe you need to follow the process on gitbox.apache.org

**Comment by dhirajsb** [comment]
I had started it earlier but I didn't get a confirmation or something. I'm trying to do it again. Hopefully it will work this time.

**Comment by oscerd** [comment]
Let us know if you're able to push @dhirajsb otherwise I can take care of your PR :-)

**Comment by dhirajsb** [comment]
Finally sorted it out and got through the gitbox process today.

**Comment by oscerd** [comment]
Salesforce tests are failing now.

**Comment by oscerd** [comment]
Fixed.

**Pull request merged**
