### PR TITLE
CAMEL-12317: Added AWS StepFunctions Component

### PR DESCRIPTION
**Pull request by vignesh-manel**
# Description

Added AWS Step Functions Component

# Target

- [x] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)

# Tracking
- [x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

# Apache Camel coding standards and style

- [x] I checked that each commit in the pull request has a meaningful subject line and body.

- [x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

### CODE REVIEW

**Comment by vignesh-manel** [comment]
Appreciate if someone would review this PR and suggest if this is in right direction, and mention changes if any, post that I will be writing test cases and component doc.

**Comment by davsclaus** [comment]
Looks good to me, great work.

**Comment by davsclaus** [comment]
Are you able to add docs and tests within the next couple of days? We have deadline wednesday for source code going into 4.0 GA

**Comment by vignesh-manel** [comment]
@davsclaus I have added test cases,doc and some auto generated files, pls review.

**Comment by davsclaus** [comment]
LGTM

**Comment by davsclaus** [comment]
After this PR then we need a SB starter for this
https://github.com/apache/camel-spring-boot

**Comment by davsclaus** [comment]
[camel-package-maven-plugin] [INFO] --- invoker:3.6.0:integration-test (default) @ camel-package-maven-plugin ---
[INFO] Building: HeaderSupport/pom.xml
[INFO] run post-build script verify.groovy
[INFO]   The build exited with code 1. See /home/runner/work/camel/camel/tooling/maven/camel-package-maven-plugin/target/it/HeaderSupport/build.log for details.
[INFO]           HeaderSupport/pom.xml ............................ FAILED (11.55 s)
[camel-package-maven-plugin] [INFO] 
[camel-package-maven-plugin] [INFO] --- invoker:3.6.0:verify (default) @ camel-package-maven-plugin ---
[camel-package-maven-plugin] [INFO] -------------------------------------------------
[camel-package-maven-plugin] [INFO] Build Summary:
[camel-package-maven-plugin] [INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[camel-package-maven-plugin] [INFO] -------------------------------------------------
[camel-package-maven-plugin] [ERROR] The following builds failed:
[camel-package-maven-plugin] [ERROR] *  HeaderSupport/pom.xml
[camel-package-maven-plugin] [INFO] -------------------------------------------------

**Comment by vignesh-manel** [comment]
Will check today

**Comment by davsclaus** [comment]
Tested this locally and this is okay. The camel-package-maven-plugin error is not related to this and the tests works fine locally.

**Comment by davsclaus** [comment]
@vignesh-manel can you do the PR for camel-spring-boot thanks

**Comment by vignesh-manel** [comment]
@davsclaus I see you have already added it, thanks

**Pull request merged**
